### ISSUE TITLE
Отдельные опции для каждого шаблона

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#100]
В 0.92 я начал работу по перетусовке опций. Это первая часть работы. Вторую часть я оставил для следующей, которую пока откатаем на dev-версии.

Смысл в том, чтобы ряд опций сделать уникальтным для каждого шаблона. Сейчас у нас выходит так. Настроил в default компоненты и, скажем юниты главной. Дальше переключился на другой шаблон и там оказались те же самые настройки. Если в этом шаблоне нет компонентов из default или они другие по именованию, то во втором шаблоне они исчезают. Приходится отмечать уже этот вариант, сохранять. Теперь, если переключиться на default (или третий шаблон), то ситуация повторяеся. И так до бесконечности...

Я предлагаю для некоторых опций использовать только собственные ключи. Технически это options_type в ini-файлах. Привязку удобно сделать через getinfo('template').

Нужно обсудить какие именно настройки сделать уникальными. 

Мой список таков: 
* выбор компонентов
* все компоненты в шаблоне
* Главная (units) — Юниты для главной
* Шаблоны вывода (все типы)
* Свои CSS-стили
* CSS профили

Минус этого подхода только в том, что при обновлении в следующей версии MaxSite CMS придется заново отметить эти опции (потому что поменяется options_type).

**Comment by vimruler** [comment]
Идея разделения опций для каждого шаблона мне очень понравилась. Сходу особо возражений придумать не могу.

По поводу списка уникальных опций пока вопрос возник по настройкам меню - оно относится к компонентам (т.е. будет уникальным)?

**Comment by maxsite** [comment]
Меню общее, поскольку это больше навигационный элемент, не зависимый от шаблона.

**Comment by vimruler** [comment]
Тогда к твоему списку добавить нечего. Все остальные опции независимые от шаблона.

**Comment by maxsite** [comment]
Тогда тестируем :-)

**Comment by maxsite** [comment]
Выкачу версию 0.93 немного раньше из-за этой смены опций. Нужно, чтобы шаблоны использовали уже новый механизм.
