### ISSUE TITLE
Вопросы/доработки по 92й версии

### ISSUE THREAD

**Issue by multVVM** [maxsite/cms#101]
Используется ли сейчас система gravatar.com, если да, то можно ли почту сохранять в нижнем регистре, т.к. картинка не находится.

Когда заходишь под комментатором, в footer'е остается ссылка "Вход", поидее наверное должна быть ссылка "Выход"

**Comment by vimruler** [comment]
>Используется ли сейчас система gravatar.com, если да, то можно ли почту сохранять в нижнем регистре, т.к. картинка не находится.

Я так понимаю, что не обязательно сохранять в базе в нижнем регистре емайл. Достаточно делать строку вызова аватарки буквами нижнего регистра. Это можно решить средствами шаблона.
