### ISSUE TITLE
Идея: Unit типа «хук»

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#102]
Если в качестве юнитов можно использовать ушки или компоненты, то может имеет смысл для полного комплекта добавить возможность использовать в качестве юнита хук? Т.е. сделать стандартный юнит типа:

<pre>
[unit]
hook = название_хука
param1 = значение1
param2 = значение2
[/unit]
</pre>

Тогда параметры (если они есть) просто загонять в массив $args и передавать в обработчик хука.

Использование такой фичи я вижу в том, что можно распространять не "юниты для главной", а плагины, которые имеют более гибкие возможности. Например, слайдеры. В рамках юнита нет возможности сделать подключение js-части перед тэгом body. А плагин такую возможность имеет.

Понятно, что можно сделать файл юнита (в котором вызывается хук) и распространять с плагином, но если будет стандартная возможность, то можно было бы упростить для пользователей использование и установку.

@maxsite что скажешь?

ЗЫ: Ещё есть аналогичная идея по компонентам. Т.е. - компонент вызывающий нужный хук.

**Comment by maxsite** [comment]
Почти все js-скрипты можно и в большей части нужно, подключать либо в теле body, либо в самом конце. Поэтому я просто не вижу применения в юнитах хуков. Мне даже тядело представаитьтакую задачу...

**Comment by vimruler** [comment]
> Мне даже тядело представаить такую задачу...

Попробую помочь с этим. Я рассматриваю ситуацию среднестатистического неопытного вебмастера. Он скачивает и устанавливает некий шаблон, в котором есть возможность настраивать юниты из админки. Есть мой плагин слайдера или ещё какого не весть эффекта для главной страницы. Мне нужно иметь такой простой способ, чтобы вебмастеру нужно было просто скопировать папку моего плагина и чуток поработать в админке, т.е. без правки файлов шаблона. Свою разработку хочу распространять именно плагином, т.к. в нём могу правильно задать место подключения скриптов и стилей и не парить вебмастера лишними инструкциями куда и что положить в папку шаблона. Т.е. вебмастеру останется только добить подключение юнита (скопировать пример кода из памятки) или включить компонент (актуально для шапки и подвала).

Распространять именно компонент или юнит не считаю хорошей идеей, т.к. это заставляет вебмастера делать кучу лишних действий по раскладыванию по нужным местам файлов стилей и скриптов или же они подключаются прямо по месту вызова юнита или компонента, т.е. не оптимально. Внятно изложил ситуацию?

И да, у меня уже есть один такой компонент. Просто хотелось бы из коробки иметь стандартную возможность. Хотя конечно не принципиально, если тебя не пронимает эта задача :)

**Comment by maxsite** [comment]
Илья, ты просто неверно ставишь задачу. :) Не нужно абстрагироваться на какого-то мифического вебмастера. Твои (как и мои, и любого другого) компоненты сто лет никому не нужны. На эти грабли уже многократно наступлено... Твоя задача сделать даже не шаблон, а сайт. Реальная потребность клиентов очень далека от всей этой работы «про запас». Делать нужно ровно то, что требуется клиенту. И только в этом случае у тебя будет понимание как упростить работу именно себе. Если тебе нужен слайдер, то делай его на уровне шаблона. Это простая задача, где не требуется извращаться через хуки или какие-то другие сложные вещи. Когда у тебя будет два заказа, где используется слайдер, то ты делаешь такой компонент, который будет универсальным, потому что третьему клиенту ты сможешь уже сам предлагать этот слайдер. Но это всё уровень шаблона, причем конкретного клиента.

**Comment by vimruler** [comment]
Согласен :) В чём-то я действительно люблю работать "про запас". Хорошо, тогда тикет пока можно закрывать.
