### ISSUE TITLE
Идея: Добавить поддержу SVG в функцию mso_get_path_files

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#103]
По умолчанию, четвёртый параметр функции (расширения файлов) принимает массив со стандартными типами, но в нём нет svg. Цитирую из __common.php__:

```php
function mso_get_path_files($path = '', $path_url = '', $full_path = true, $exts = array('jpg', 'jpeg', 'png', 'gif', 'ico'))
```

Предлагаю добавить в массив svg так как те же логотипы могут быть в этом формате:

```php
function mso_get_path_files($path = '', $path_url = '', $full_path = true, $exts = array('jpg', 'jpeg', 'png', 'gif', 'ico', 'svg'))
```
Тогда функция __default_header_logo__ сможет находить SVG файлы логотипов тоже.

**Comment by maxsite** [comment]
Ок. Добавлю.
