### ISSUE TITLE
Возожность задавать вкладки в редакторе записей

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#104]
**Хотелось бы:** возможность задавать вкладки самостоятельно, и группировать по ним заданные метаполя. Например, некоторые метаполя, которые не очень часто используются, поместим на отдельную вкладку.
![123123](https://cloud.githubusercontent.com/assets/13200830/10561424/55df04a6-7541-11e5-91b9-534180738d2c.png)

**Comment by maxsite** [comment]
Даже не представляю себе как это можно сделать. :-(

**Comment by vimruler** [comment]
Пока была только идея реализовать такое плагином, который с помощью js согласно настройкам создавать вкладку и перекладывать нужным образом опции. На уровне движка (в php) тоже нет идей как сделать такое.

**Comment by amigoscs** [comment]
Так может хотя-бы добавить какое-нибудь условие в плагин <strong>admin_page</strong> для файлов <strong>edit.php</strong> и <strong>new.php</strong> там где мета подключаются 
<code>require($MSO->config['admin_plugins_dir'] . 'admin_page/all_meta.php');</code>
добавить
<code>
if($fn = mso_fe('custom/vkladka.php'))
require($fn)
</code>
и файл <strong>form.php</strong> добавить по этому же условию добавление вкладки

Очень часто приходилось сталкиваться, что при добалении своих опций хотелось их видеть отдельно от дефолтных.

а может сразу сделать так, чтобы кастомные опции выводились в отдельной вкладке?

**Comment by maxsite** [comment]
Пометил как задача на будущее. Чтобы такое реализовать, потребуется полная переделка существующей схемы работы метаполей.

**Comment by vimruler** [comment]
А можно сделать как-то так, чтобы плагины тоже могли добавлять свои мета-поля к форме редактирования записи? Например, у меня плагин «Прислать статью» активно сохраняет свои данные в мета-полях, но понятно, что вывести их значения на форме редактирования записи нет возможности без редактирования meta.ini файла шаблона.

По сути задача сводится к вопросу: можно будет как-то плагином влиять на то, какие мета-поля отображаются (и на каких конкретно табах), а какие нет?

Ну и вопрос из той же «оперы»: в таблице mso_page хранится информация о количестве просмотров и голосов (page_rating) записи, но на форме таких полей нет - можно их тоже давать редактировать?
