### ISSUE TITLE
Метаполя для категорий

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#105]
Знаю, что тема уже обсуждалась, но все же...
Очень не хватает возможности добавлять свои метаполя для категорий. Вот просто очень часто ловлю себя на мысли, что не хватает этого.

**Comment by vimruler** [comment]
А плагин [category_title](http://maxhub.ru/page/plugin-category-title) не решает проблему? Почему не решает?

**Comment by skull3d** [comment]
**vimruler**, новерно потому что он не позволяет создавать произвольные мета поля для категорий, а только добавляет мета теги.

**Comment by vimruler** [comment]
Максим, задача всё актуальнее и актуальнее :-) Может возобновим обсуждение способов реализации? А там, глядишь, у меня время появится реализовать.

Когда я начинал переделку плагина управления рубриками, то была идея реализовать мета-поля примерно так же, как мета-поля записей - через настройку ini-файла. Сейчас хотел бы добавить по-умолчанию поля: title, description, keywords. Возможно стоит добавить поле template - чтобы можно было выбрать шаблон вывода. Но это ещё стоит обсудить.

Какие правки делать в дефолтном шаблоне - не думал пока.

Ну, или, если моё участие не требуется, то может обозначишь, когда стоит ждать твоей реализации?

**Comment by maxsite** [comment]
Илья, нет я не делал, поэтому тебе и карты в руки. :) 

Что касается ini-файла. С одной стороны — это неплохо. С другой — а какая именно информация будет в этом ini-файле? Если так подумать, то только обычный текст (например textarea). Если нужны будут вдруг те же чекбоксы, то их легко можно заменить на текстовые 0 и 1. То есть получается, что весь ini-файл будет состоять только из трех строчек:

title
description
keywords 

Есть ли смысл городить ради этого ini-файл? Ведь это не сколько «классический» ini-файл, сколько шаблон для каждой рубрики. Возможно будет проще использовать какой-то другой механизм. На ум приходит что-то вроде отдельной (глобальной) опции в Основных настройках «Дополнительные поля рубрик» в Прочее (categor_meta) в виде textarea, где, собственно и будут содержаться эти три строчки. 

title = Заголовок в браузере
description = Описание рубрики
keywords = Ключевые слова

Далее. Мета-данные рубрик будут храниться в таблице meta где `meta_table = category`. Это позволяет нам использовать существующие функции `mso_get_meta('title', 'category', ID рубрики)` и `mso_add_meta('title', ID рубрики, 'category', 'значение поля')`.

По интерфейсной части.

Думаю, что все эти мета-поля нужно выводить в конце формы под **Ссылка-Родитель-Порядок** в виде textarea для каждого мета-поля.

Таким образом первая часть работы: сделать опцию и сделать вывод метаполей в **admin.php**. Поле формы будет иметь id вида `cat[[ID]][category_meta][META]`, где META — это title, description и т.п. То есть в `$format` нужно передать $переменную с уже готовыми полями META (получаем все мета из опции, получаем по их именам одним запросом, чтобы получить их values, после через цикл прогоняем и формируем html-поля формы). Обрати внимание, что в `mso_create_list()` мы не можем передать метаполя и их значения в format в текущем варианте. При этом `$all` в текущем варианте тоже не получает этих мета (`mso_cat_array()`). То есть нужно придумать как добавить мета в `$all` (можно через обычный цикл), после придумай какие-нибудь простые замены в `mso_create_list()` вроде `[META-title]`, `[META-description]` и `[META-keywords]` и пропиши их замены. Это «костыли», которые я уже сам после переделаю на нормальный вариант. В прототипном варианте нам будет этого достаточно.

Далее нужно отработать **do-ajax.php**. Мета прибывают в `$post['cat'][$cat_id]['category_meta']`. Добавлять после «Рубрика сохранена!» циклом с `mso_add_meta()` (сложность в том, что может быть как добавление новой строчки в базу, так и обновление insert/update. Хотя можно сделать одним запросом через INSERT INTO ... ON DUPLICATE KEY UPDATE — это я уже сам поковыряю). 

После этого уже можно будет добавить добавление метаполей в форму `$add_new` и доделку его post-запроса вверху файла.

В общем примерно так. Если что-то непонятно, уточняй.

**Comment by vimruler** [comment]
> Что касается ini-файла. С одной стороны — это неплохо. С другой — а какая именно информация будет в этом ini-файле? Если так подумать, то только обычный текст (например textarea). Если нужны будут вдруг те же чекбоксы, то их легко можно заменить на текстовые 0 и 1. То есть получается, что весь ini-файл будет состоять только из трех строчек:

Если мета-поля должны состоять только из html-ных мета-полей, то согласен. Но я бы предложил смотреть немного шире. Например, через мета-поле можно давать выбрать фоновую картинку рубрики или картинку в шапке (здесь можно использовать textarea или список доступных файлов). Тогда в ini-файле есть все средства для задания сканирования директории картинок и т.д. Снова же выпадающие списки для выбора можно задавать с жёстким списком вариантов. Да-Нет - это самый простой случай. Я вот хочу давать возможность выбора способа отображения списка записей (простой, сложный, сложный с «рюшечками» и т.п.). И пока не ясно как в твоём варианте такое задать.

В принципе, можно было бы совместить два варианта. По-умолчанию, внедрить твой способ (через опции в Основных настройках «Дополнительные поля рубрик»). Этого вполне хватит для основных seo-потребностей. Если кому-то нужно большее, то пусть создаёт файл **\custom\cat-meta.ini** 

По остальному пока вопросов нет. Когда начну делать - задам.

**Comment by maxsite** [comment]
Ну исходя из по опыта, каких-то особых задач с выводом рубрик практически не стоит.  Даже main-шаблон вывода или info-top для рубрик можно задать через опции в шаблоне по адресам (это в последних версиях MaxSite CMS появилось). То есть я к тому, что ini-файл — это явный перекос в сторону шаблона. А мой варант через опции — общедоступный с любой части системы. Это значит, что если делать через ini, то неизбежно появится «хвост» в виде самого ini-файла или его файла функций. Давай попробуем определить какие-то конкретные задачи по рубрикам, чтобы понять что нужно в итоге.

**Comment by vimruler** [comment]
> можно задать через опции в шаблоне по адресам (это в последних версиях MaxSite CMS появилось)

Да, видел новую возможность. Задавать целиком шаблон отличная возможность. Но, имхо, если задача просто разными цветами выводить страницы рубрик, то делать для этого разные main-шаблоны как-то избыточно. Проще было бы один main-шаблон, который берёт нужные цвета из мета-полей рубрики.

> Давай попробуем определить какие-то конкретные задачи по рубрикам, чтобы понять что нужно в итоге.

Я уже обозначил свои самый актуальные задачи:

- разнообразный по оформлению вывод списка записей. Их больше чем два текущих по-умолчанию. 

- разное оформление шапки/всей страницы. Где-то это может быть разная картинка в фоне, где-то цвет разный, стили элементов. 

- вывод большого текста описания рубрики. Он больше чем description. Возможно имеет смысл хранить в записи (чтобы легче было править) и тогда в мета-поле нужно хранить ID записи.

Возможно кто-то добавит свои задачи.

> неизбежно появится «хвост»

Хм. Действительно. Хотелось бы этого избежать. Тогда может расширим твой вариант? Чтобы через вертикальную черту можно было не только название поля и заголовок задавать, но и тип со значениями (например, для списков использовать, как обычно, знак # )?

**Comment by vimruler** [comment]
> неизбежно появится «хвост»

С другой стороны, с ini-файлом можно было бы распространять шаблоны с возможностью более гибкой настройки отображения рубрик. А так придётся писать инструкцию как настраивать через Основные настройки...

**Comment by maxsite** [comment]
Я понимаю о чём ты говоришь. Сейчас мы просто обсуждаем все идеи.

> вывод большого текста описания рубрики. Он больше чем description. Возможно имеет смысл хранить в записи (чтобы легче было править) и тогда в мета-поле нужно хранить ID записи.

Ну вроде как это и сейчас есть в виде ушек category_SLUG.

> разное оформление шапки/всей страницы. Где-то это может быть разная картинка в фоне, где-то цвет разный, стили элементов.

Строго говоря это и есть main-шаблон, который можно назначить по адресу. Ты же понимаешь, что даже если и сделать такой выбор в настройках рубрик, потребуется где-то это все прочесить и сделать изменения в функциях шаблона? Например в том же main-файле или my-template.php. То есть такая задача всё-таки больше относится к опциям шаблоне, нежели к настройкам рубрик.

Еще такой момент. Ты путаешь ini-файл и выводд ini-файла в виде опций. Последнее — это набор функций с автоматическим выводом полей формы, их обновлением и т.п. И этот функционал мы не можем просто так прилепить к совершенно другой форме (настройки рубрик). Таким образом потребуется распарсить ini-файл уже своим способом. Чтобы понять объём посмотри в admin_page/all_meta.php, где мне пришлось поступить аналогичным образом. Там объем кода больше, чем все файлы рубрик, при том что функционал скорее всего будет невостребован в 99% случаев.

Поэтому я бы всё-таки не использовал ini-файла, из-за его чрезмерной сложности. Вместо этого можно сделать всё-таки опцию, как я предложил и это покроет основные потребности. А для более сложных случаев можно предусмотреть в шаблоне, например через mso_set_val() некую переменную-массив, в который будет присоединять в виде html-кода нужных полей. Нам ведь поля нужны только для `$format`.

**Comment by vimruler** [comment]
В целом, согласие с твоим подходом у меня пришло. Осталось найти время на реализацию. Детали реализации буду спрашивать в личке, когда начну делать.

**Comment by maxsite** [comment]
Я, кстати, на днях смог решить одну давнюю задачку по рубрикам. Пока ещё не выкладывал, тестирую. Будет некая опция в админке, в которой можно будет задать для разных рубрик свои юнит-файлы.

news = 2col.php
genry = full.php
ford = list.php

При type-выводе рубрики будет проверяться эти соответствия и вместо типового вывода будет подключаться указанный файл. То есть для news будет подключаться `type/category/units/2col.php`

Таким образом можно будет определить произвольный вывод для любой рубрики.

**Comment by vimruler** [comment]
> На ум приходит что-то вроде отдельной (глобальной) опции в Основных настройках «Дополнительные поля рубрик» в Прочее (categor_meta)

А как на счёт вкладки "Мета-поля"? Просто сделать там отдельную секцию (визуально будет выглядеть как, например, на вкладке "Загрузки") "Дополнительные поля рубрик".

> По интерфейсной части.
> Думаю, что все эти мета-поля нужно выводить в конце формы под Ссылка-Родитель-Порядок в виде textarea для каждого мета-поля.

А как быть с разным количеством строк у textarea - не всем же полям нужно большое поле (например, если в мета-поле задаётся просто число в качестве значения)? Или всем одинаково задавать, скажем, 2 строки?

**Comment by maxsite** [comment]
> А как на счёт вкладки "Мета-поля"? Просто сделать там отдельную секцию (визуально будет выглядеть как, например, на вкладке "Загрузки") "Дополнительные поля рубрик".

Так это же вкладка для поисковиков. Это html meta, а мы обсуждаем свои мета. :)

> А как быть с разным количеством строк у textarea - не всем же полям нужно большое поле (например, если в мета-поле задаётся просто число в качестве значения)? Или всем одинаково задавать, скажем, 2 строки?

Это технический момент. Строки можно уменьшать в зависимости от наполнения поля. Но меньше 2-х делать нельзя, иначе это вызовет путаницу с однострочным input.

Вообще я вот о чём подумал. Эти мета для рубрик должны быть на каком уровне? Если это общесистемные, то логично их вынести в отдельный файл в admin-каталоге и обновлять с системой. Если это уровнеь шаблона, то тут опция. Но! А будет ли эта опция востребована именно через админ-панель? Ну выставит пользователь кучу метаполей и толку? Всё равно для его вывода потребуется править php-код шаблона. То есть мы опять спускаемся на уровень шаблона, а точнее даже вебмастера шаблона. А это наводит на мысль, что проще — это всё-таки отдельный php-файл в шаблоне с описанием доп. полей рубрик. Примерно как это сейчас сделано с custom/my_meta.ini

**Comment by vimruler** [comment]
> То есть мы опять спускаемся на уровень шаблона, а точнее даже вебмастера шаблона.

Согласен с рассуждением. 

> А это наводит на мысль, что проще — это всё-таки отдельный php-файл в шаблоне с описанием доп. полей рубрик. Примерно как это сейчас сделано с custom/my_meta.ini

Вот тут нужно поподробнее раскрыть мысль. Сейчас я не понимаю что значит "отдельный php-файл", а потом речь идёт об ini-файле.

Я мыслю, что для настройки мета-полей было бы достаточно дать вебмастеру возможность править некий файл **custom/cat_meta.ini**, в котором по умолчанию уже заложить мета-поля title, description, keywords. Вебмастер может добавить свои поля. Если файла нет, то и мета-полей не выводить. По-умолчанию, можно файл отключить знаком подчёркивания в начале имени **custom/_cat_meta.ini**

**Comment by maxsite** [comment]
Я против ini файла, потому то его придется дополнительно парсить. Поскольку мы говорим об вебмастере, то для него задать опции в виде массива не проблема. Что-то вроде:

```php
$cat_custom_meta['ключ'] = array(
	'name' : 'Имя',
	'description' : 'Описание',
	''type: 'textarea',
);
```
Такой массив лучше передавать через mso_set_val. То есть в шаблоне он задаётся, а в рубриках читается и формируются поля.

**Comment by vimruler** [comment]
> Я против ini файла

Это было понятно давно (жаль теряется единообразие в подходах к настройке, но зато php-файл будет работать шустрее). Поэтому и попросил развернуть мысль - как делать? Сейчас вроде понятнее стало. Но лучше бы поподробнее расписать всю схему работы, а то я при упоминании **mso_set_val** получил несколько вариантов и не знаю какой нужен.

**Comment by maxsite** [comment]
Илья, я думаю, что нужно какой-то прототип на коленке собрать и посмотреть как работает. У нас еще есть один необсуэжденный момент — использование этих мета от рубрик в шаблоне. Ну вот например произвольный title. Сразу нужно думать как и где эта опция будет использована.

> mso_set_val 

В чем именно сложность? Придумываем некий ключ, например cat_custom_meta. В неё и загружаем массив данных.

**Comment by vimruler** [comment]
> У нас еще есть один необсуэжденный момент — использование этих мета от рубрик в шаблоне. Ну вот например произвольный title. Сразу нужно думать как и где эта опция будет использована.

Я понимаю. Пока стараюсь об этом не думать, ибо ещё нечего использовать.

> В чем именно сложность?

Я имел в виду вопрос о том, в каком файле делать такие настройки? Создать отдельный php-файл или же в файле custom/set_val.php всё размещать?

> 'type': 'textarea',

А какие ещё типы будут? Если тип только textarea, то зачем вообще этот параметр вводить?

**Comment by maxsite** [comment]
Файл должен быть доступен для админки, поэтому это `custom/set_val_admin.php` или `custom/my-template.php`.

Типы любые. Я привёл код лишь как пример.

Но я бы всё-таки обсудил вначале полный объем задач. Пусть у нас уже есть эти поля. Какие и что с ними делать?

**Comment by vimruler** [comment]
> Но я бы всё-таки обсудил вначале полный объем задач. Пусть у нас уже есть эти поля. Какие и что с ними делать?

Поля имеющиеся в default-шаблоне "по-умолчанию" - title, description, keywords. С ними вроде всё понятно - нужно прописать использование в функции **my_default_head_section**. Всё.

Остальные поля, которые вебмастер сам может прописать - он сам и определяет как и где использовать. Главное, что есть механизм получения значений через функцию mso_get_meta.

Если хочется пример в default-шаблон - можно сделать смену цвета шапки рубрик.

**Comment by maxsite** [comment]
Ну вот уже интересней :) Попробуем решить задачи без мета.

title - с точки зрения seo, title всё-таки лучше если совпадает с названием рубрики. То есть вряд ли это будет нужно.

description — это и сейчас есть.

keywords — это поле уже давно не используется поисковиками. У него нулевая потребность в принципе.

Смена цвета — это css-класс для BODY. И здесь завязка на сам шаблон. Плюс я не понимаю, каким образом будут меняться компоненты Шапки, в зависимотсти от этой опции? Это переделывать компоненты? Давай определимся точнее по этой задаче в качестве тестового примера.

**Comment by vimruler** [comment]
> Давай определимся точнее по этой задаче в качестве тестового примера.

Пожалуй с шапкой немного замутно выходит. Можно взять другую задачу - попроще. Например, смена фонового изображения для заливки. Для этого достаточно указать название css-класса. Фактически, нужно просто подставить значение, например, в тег body. Разные значения у разных рубрик - разное оформление. Как тебе такой вариант?

Ну и ещё вопрос возник. Если по факту выходит, что большинство стандартных мета-полей для seo не нужны, а с нестандартными как-то неопределённо, то может вообще имеет смысл не городить огород, а вынести админ-работу с мета-полями в плагин? Тогда, фактически, нам нужно только сделать возможность цепляться по хукам на вывод формы редактирования и сохранения рубрики. Остальное пусть делает плагин (формирует поля для ввода значений мета-полей рубрики, сохраняет значения, управляет настройками) и сам вебмастер - куда и как будет ему нужно в шаблоне. Как тебе такой подход?

**Comment by maxsite** [comment]
> Пожалуй с шапкой немного замутно выходит. Можно взять другую задачу - попроще. Например, смена фонового изображения для заливки. Для этого достаточно указать название css-класса. Фактически, нужно просто подставить значение, например, в тег body. Разные значения у разных рубрик - разное оформление. Как тебе такой вариант?

Тут фишка в том, что это завязка не просто на шаблон, а на конкретный шаблон и его вёрстку. А это значит, что вебмастеру придется какую-то дополнительную логику городить. То есть недостаточно просто прописать css-класс, нужно его ещё и описать в стилях. Тогда проще вынести это в настройки шаблона, где указывать рубрики и их класс.

>  вынести админ-работу с мета-полями в плагин?

Интересный вариант. По сути можно сделать админ-плагин для работы с таблицей мета. Ну только разные фильтры для полей предусмотреть. Там можно будет не только редактировать, но и добавлять и удалять данные. Тогда можно вообще ничего не цеплять, и при этом появляется возможность редактировать все мета, включая и служебные, и шаблоные.

**Comment by vimruler** [comment]
> Тогда проще вынести это в настройки шаблона, где указывать рубрики и их класс.

Согласен.

> По сути можно сделать админ-плагин для работы с таблицей мета.

Да, можно такой сделать. Другой вопрос, что сейчас я пока не готов такую задачу решать, ибо там на мой взгляд многовато делать придётся, а времени не так легко найти.

Что-то на мой взгляд задача доработки админ-панели рубрик для работы с мета-полями как-то плавно потеряла актуальность. Ты как думаешь?

**Comment by maxsite** [comment]
Скажем так, у меня вообще никогда не возникало потребности в мета-полях рубрик. :) Вот main-файлы, info-top-файлы, а теперь и юнит-файлы — это да, была потребность. А мета — вообще непонятно для чего...

**Comment by vimruler** [comment]
> Скажем так, у меня вообще никогда не возникало потребности в мета-полях рубрик.

Понимаю :)

Тогда чтобы совсем уж не сливать запрос (в этой ветке кроме нас ещё вроде два человека отметились) предлагаю сделать по простому варианту - как предлагал чуть ранее, добавить в админ-плагин **admin_cat** возможность цепляться по хукам при формировании формы редактирования/создания рубрики и при обработки данных присланной формы. Кому нужно, пусть делаю плагины и не ноют, что чего-то не хватает. Ну и использование этих мета данных пусть сами продумывают.

**Comment by maxsite** [comment]
Я предлагаю просто ничего не менять. Но если найдется кто-то кто сможет обрисовать реальную потребность, то заново тикет откроем. :)

**Comment by vimruler** [comment]
> Я предлагаю просто ничего не менять. Но если найдется кто-то кто сможет обрисовать реальную потребность, то заново тикет откроем.

Тоже вариант. А то у меня сложилось впечатление, что это только одному мне нужно.

**Comment by maxsite** [comment]
Ок.

**Comment by maxsite** [comment]
Вплотную занялся вопросом мета к рубрикам... В общем всё довольно сложно получается, но уже есть промежуточный положительный результат.

Главная сложность в том, что в теле mso_create_list() нужно вычленять сторонний массив (с данными мета) под каждую рубрику. Исхитрился тем, что прописал дополнительную функцию, которя и выполняет нужные действия. Кроме того, пришлось придумать и добавить к данным рубрик их метаполя.

Из неожиданных проблем — непонятно как реализовать разные типы полей. Решил, что оптимальным будет оставить только textarea. 

Подключение своих мета делается так. Файл `custom/my-category-meta.php`.

```php
<?php if (!defined('BASEPATH')) exit('No direct script access allowed'); 
/*
 * (c) MaxSite CMS
 * http://max-3000.com/
 *
 */

return array(
	'mytitle' => array(
		'name' => 'Title в браузере', // имя поля
		'attr' => 'rows=1',          // дополнительные атрибуты 
		),

	'mydescription' => array(
		'name' => 'Дополнительное описание',
		'attr' => 'rows=2',
		),
);

# end of file
```
Дальше всё автоматом. Получение же мета полностью ложится на сам шаблон. 

```php
require_once( getinfo('common_dir') . 'meta.php' ); 
$m = mso_get_meta('mydescription', 'category', $current_cat_id, 'meta_value');
pr($m);
```

Сегодня выложу обновление MaxSite CMS, где можно будет потестировать новую возможность.

Пока ещё не решил как выполнять удаление мета при удалении рубрики. Теоретически это может затронуть не только объявленные в **my-category-meta.php** поля, но и другие, которые были объявлены плагинами или ещё как. Поэтому этот вопрос пока открыт и мета данные не удаляются.
