### ISSUE TITLE
Id всех страниц текущей категории

### ISSUE THREAD

**Issue by amigoscs** [maxsite/cms#106]
Удобно было бы сделать доступным получение всех id страниц на странице категорий. Чтобы не перебирать массив $pages, а просто их получить, например через $MSO->data['pages_id'].

В функции mso_get_pages() есть место, где они (id-шники) формируются в массив $all_page_id[] (строка 263). Загрузить их в $MSO->data['pages_id'] = $all_page_id;

Ну или сделать в массиве $pages ведущими ключами id страниц (что было бы еще удобнее). А лучше и так и так:)

Самостоятельно сделать можно, но ведь при обновлении системы все сотрется...

**Comment by vimruler** [comment]
А можете описать задачу, которую будете решать такой доработкой?

**Comment by amigoscs** [comment]
Да собственно все просто. Мне нужно извлечь все ['page_meta'] и ['page_id'] из массива $pages за раз ДО отображения страниц. Сейчас приходится решать перебором. Получается двойной foreach: первый - я вытаскиваю page_meta и page_id, второй - сам вывод.

**Comment by vimruler** [comment]
А вы не думали, что пытаясь сэкономить в одном месте, вы тем самым просто перекладываете нагрузку в другое? Я о том, что ваш "лишний" foreach теперь будет происходить где-то в движке, но он всё равно будет. Теперь нужно понять, а насколько актуальна решаемая вами задача (по описанию - не понятно что именно вы делаете потом с мета-информацией) для большинства сайтов?

**Comment by amigoscs** [comment]
Так в том и смысл, что в mso_get_pages( ) уже есть foreach. И id страниц собираются в $all_page_id[]. (common/page.php - строка 262)

foreach ($pages as $key=>$page)
		{
			$all_page_id[] = $page['page_id'];
...
}
Дальше только присвоить их в $MSO. 
$MSO->data['pages_id'] = $all_page_id;

Правда согласен, что вот сделать в $pages ведущими ключами id страниц, скорее всего без доп. нагрузки не получится при нынешнем положении дел. Ну хотябы просто дать быстрый способ получения id страниц.

**Comment by maxsite** [comment]
См. `mso_cat_array_single()`

**Comment by amigoscs** [comment]
<code>mso_cat_array_single()</code> конечно хорош, но тогда придется все-равно активировать <code>foreach</code> (в функции <code>mso_get_cat_from_slug()</code>), чтобы получить id текущей рубрики. Плюс к тому же в массиве содержатся ВСЕ страницы категории, однако в текущий момент отображается их, например 7. Обработка невидимых страниц не имеет смысла.

Кстати, функция <code>mso_get_cat_url_from_id()</code> использует перебор для получения url из массива <code>mso_cat_array_single()</code>. Однако последняя возвращает массив, где ключом является id рубрики.
Таким образом можно первую упростить до 
<code>return getinfo('siteurl') . 'category/' . $all_cats[$id]['category_slug'];</code>

**Comment by maxsite** [comment]
Вы бы определились с задачей. Если нужны только текущие записи, то используйте $pages в каком-нибудь unit-файле или type_foreach-файле от category.

**Comment by amigoscs** [comment]
Нужны только текущие записи.
Просто часто возникала необходимость в этом. И постоянно приходилось перебирать $pages. Думал, упростить задачу.

**Comment by maxsite** [comment]
Нативные циклы, если в них примитивные операции, не создают нагрузку. В крайнем случае есть функции работы с массивами. Если нужны только ключи, то вполне сходится какой-нибудь array_keys().
