### ISSUE TITLE
Вопрос по хуку new_comment

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#107]
Возникла необходимость делать дополнительную обработку нового комментария сразу после его сохранения. В функции __mso_get_new_comment__ нашёл хук __new_comment__ и перед ним код, который, как я понимаю, должен был помочь обработчику хука получить информацию об id нового комментария:

```php
// посколько у нас идет редирект, то данные об отправленном комменте
// сохраняем в сессии номер комментария
if ( isset($MSO->data['session']) )
{
	$CI->session->set_userdata(array( 'comments' =>
			array(
			// $CI->db->insert_id()=>$comments_page_id
			$id_comment_new
	)));
}
mso_email_message_new_comment($id_comment_new, $ins_data, $args['page_title']);
mso_flush_cache();
$CI->db->cache_delete_all();
mso_hook('new_comment');
mso_redirect(mso_current_url() . '#comment-' . $id_comment_new);
```

Обработчик хука у меня выглядит так:

```php
function my_plugin_new_comment()
{
	$CI = & get_instance();
	global $MSO;
		
	$out = pr($CI->session->all_userdata(), false, false); 

	die( $out );
}
```

По идее, в полученном массиве должен был быть ключ __comments__, в котором id нового комментария. Но увы, нет ничего такого. Массив с данными выглядит так:

```php
Array ( 
[session_id] => 2222222222222222222222222222222 
[ip_address] => 127.0.0.1 
[user_agent] => Mozilla
[last_activity] => 1446655242 
[user_data] => 
[userlogged] => 1 
[last_activity_prev] => 1446654934 
[comuser] => 0 
[users_id] => 3 
[users_nik] => admin 
[users_login] => admin 
[users_password] => 00000000000000000000000000000000 
[users_groups_id] => 1 
[users_last_visit] => 2015-09-27 14:55:40 
[users_show_smiles] => 1 
[users_time_zone] => 7200 
[users_language] => ru 
[users_avatar_url] => 
[users_email] => admin@admin.ru 
) 
```
Так как в хук напрямую данные об id комментария не передаются в качестве аргумента, то отсюда вопрос - может я чего-то не понимаю, но как получить в обработчике id нового комментария? Или эта задача не решается совсем?

Пока нашёл только "обходной путь" - в функции __mso_email_message_new_comment__  в хук __mso_email_message_new_comment__ передаётся явно id комментария. Но это как-то длинно, что ли. Или так и было задумано?

Заранее спасибо за ответ, Максим!

**Comment by maxsite** [comment]
Илья, во-первых меня аж предернуло от этого кода:
```
    $out = pr($CI->session->all_userdata(), false, false); 
    die( $out );
```
Ты серьёзно?

Во-вторых, по хуху. После отправки комментария происходит редирект. Установка кук (а это и есть CI-сессии) возможна только в момент начала загрузки страницы (для простоты будем так считать). Таким образом хук  new_comment срабатывает перед редиректом, когда данные текущей ci-сессии ещё старые. Собственно редирект для того и делается, чтобы обновить сессию, а при этом происходит сброс кэша, включая и кэш sql-запросов. Таким образом, если в твоём обработчике используется `$CI->session->set_userdata`, то там будет уже устаревшая информация.

То есть всё напрямую зависит от самой задачи. Подозреваю, что это как-то связано не сколько с самим комментом, сколько с данными комюзера. ID комментария нужен только в одном случае — если ты попытаешься ещё раз выполнить запрос к БД и что-то с ним сделать. Если запросов базе не будет, то следует использовать другие более «тематические» хуки.

**Comment by vimruler** [comment]
> Ты серьёзно?

Это отладочный код. Само собой реальная логика осталась за кадром (на тот момент её и не было вовсе).

> Таким образом хук new_comment срабатывает перед редиректом, когда данные текущей ci-сессии ещё старые. Собственно редирект для того и делается, чтобы обновить сессию, а при этом происходит сброс кэша, включая и кэш sql-запросов. Таким образом, если в твоём обработчике используется $CI->session->set_userdata, то там будет уже устаревшая информация.

Да, разобрался. Спасибо за подтверждение моих догадок. $CI->session->set_userdata я собирался использовать только как способ получения ID камента. Сейчас сделал всё по другому.

>Подозреваю, что это как-то связано не сколько с самим комментом, сколько с данными комюзера. ID комментария нужен только в одном случае — если ты попытаешься ещё раз выполнить запрос к БД и что-то с ним сделать. Если запросов базе не будет, то следует использовать другие более «тематические» хуки.

По факту, мне нужна информация о каменте в том виде, какой бывает перед выводом страницы с комментариями (т.е. и инфа об авторе, и инфа о самом комментарии). Это нужно было для того, чтобы получать отправлять заполненную форму комментарования через аякс, а потом обработанный комментарий пропускать через шаблон и отправлять в браузер чтобы добавить в конец списка каментов.

В общем, сейчас сделал всё через __mso_email_message_new_comment__.

**Comment by maxsite** [comment]
> Это отладочный код. Само собой реальная логика осталась за кадром (на тот момент её и не было вовсе).

При чём тут это? Меня пугает, что такой опытный разработчик не знает как использовать _pr().

**Comment by vimruler** [comment]
> Меня пугает, что такой опытный разработчик не знает как использовать _pr().

Знаю :) И про то, что die внутри него есть - знаю :) Просто в ходе тестирования кроме непосредственного вывода этой переменной я ещё иногда разного добавлял в конец переменной. Поэтому пришлось извращаться таким странным образом. А потом просто осталось и т.к. всё равно это всё переделывать.

**Comment by maxsite** [comment]
Успокоил. :-) У нас частая ситуация, когда кто-то из новичков копирует код бездумно. Хотелось бы  сразу показывать хорошие примеры. ;-)

**Comment by vimruler** [comment]
> Хотелось бы сразу показывать хорошие примеры.

Понимаю! Учту :)
