### ISSUE TITLE
Предложение: добавить хук капчи на страницу регистрации

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#108]
Обратил внимание, что стало приходить много уведомлений о невозможности доставки моим почтовым сервером писем по странным адресам. Начал смотреть. Выяснилось, что походу кто-то настроил робота регистрировать комюзеров, чтобы ставить ссылки на сайты.

Например:

Комюзер по имени «__Валера или же Няма__» есть на сайтах:
* http://max-3000.com/users/1159
* https://gas45.ru/users/97
* были и у меня на vizr.ru и maxhub.ru - удалил

Т.к. nofollow ссылки тоже могут учитываться, то спамить - есть смысл. Но как выяснилось, капча на странице регистрации не выводится даже в 0.93. Так что имеет смысл озаботиться.

ЗЫ: На max-3000.com я смотрю уже прилично наспамили - http://max-3000.com/users/

**Comment by maxsite** [comment]
Сомневаюсь, что nofollow будут учитываться... Это ручной спам. Реально от этого не избавиться, только постмодерация. В крайнем случае можно запретить указывать адрес сайта. Но думаю, что капча не поможет — она всё-таки от  автоспама.

**Comment by vimruler** [comment]
> Сомневаюсь, что nofollow будут учитываться...

То,ч то вес ссылка не передаёт - это согласен. А вот учёт для выравнивания ссылочного профиля (в котором должен быть приличный процент nofollow-ссылок) в сторону "естественности" вполне может быть.

Ручной это спам или не ручной - фактов доказать то или иное мнение у меня нет. Просто есть наблюдение за одним клиентским сайтом, где роботы долбятся на страницу /registration хотя на неё нигде ссылок нет (да и сама страница 404 показывает), но там есть в сайдбаре форма заказа звонка и роботы счастливые заполняют её. После этого возникают сомнения в человечности регистрации на нормальных сайтах.

Если думаешь, что не поможет капча, то буду сам пробовать. Делать то всё равно что-то нужно.

**Comment by maxsite** [comment]
Сама по себе капча может и не помешает. Просто сейчас говорить, что это именно роботы регистрируются я бы не стал. А от ручного спама никто не защитит.

**Comment by vimruler** [comment]
> Просто сейчас говорить, что это именно роботы регистрируются я бы не стал. А от ручного спама никто не защитит.

Так то да. Постмодерацию заменить сложно. 

Кстати, а имело бы смысл слать уведомление, если была регистрация без комментирования?

**Comment by maxsite** [comment]
А зачем?

**Comment by vimruler** [comment]
Контролировать «рождаемость» комюзеров. Чтобы не от случая к случаю модерировать, а быть на связи каждый раз. Если ты такой вопрос задаёшь, то я понимаю, что тебе не актуально. А лично я бы воспользовался. Тем более, эта возможность могла бы быть опциональной. По хорошему, можно было бы отдать на откуп плагину, если есть хук, на который можно повесить обработку. Поищу потом.

ЗЫ: Не знаю как тебе, а мне новые реальные подписчики греют душу :-)

**Comment by maxsite** [comment]
Ну, конечно лучше плагин. Хук добавить-то не проблема. Если получится что-то стоящее, то можно думать и об интеграции в систему. :-)
