### ISSUE TITLE
Проблема после внедрения выбора парсера HTML

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#109]
Все записи создавались на старой версии движка, до введения возможности выбора парсера HTML. То есть функционировал, как я понимаю, стандартный парсер в движке - DEFAULT.

После обновления до версии 0.93 получилась ситуация, что у части записей активирован парсер DEFAUL, а у другой части парсер не установлен. Из-за этого поехало форматирование многих записей.

Почему это произошло? В основном у всех записей парсер установился правильно - DEFAUL, но есть записи, у которых парсер не активировался. Можно ли восстановить парсер как DEFAUL, чтобы у всех старых записей он активировался?

Плагин parser_default активирован.

Спасибо!

**Comment by maxsite** [comment]
Единственной причиной может быть только то, что вы начали редактировать записи до активации плагина парсера. Просто отредактируйте записи, где укажите нужный парсер.

**Comment by ekkky** [comment]
Я правильно понимаю, что причина такая: на новой версии MS не был активирован плагин parser_default, я открыла некоторые записи и нажала на кнопку "Сохранить", поэтому вариант парсера был выбран как "Нет"?

Можно ли как то узнать, у каких из записей не активирован парсер DEFAUL, кроме ручного перебора каждой записи?

**Comment by vimruler** [comment]
__Катя__, можно попробовать через PhpMyAdmin выполнить запрос (предварительно открыв базу данных сайта):

```sql
UPDATE `mso_meta` SET `meta_value`='Default' WHERE  `meta_key`= 'parser_content' and `meta_value`='none';
```

Только ещё бэкап сперва сделать нужно всей базы.

> Посмотреть у каких записей нет парсера можно запросом:
```sql
SELECT * FROM `mso_meta` WHERE `meta_key`= 'parser_content' and `meta_value`='none';
```

**Comment by ekkky** [comment]
Илья, Спасибо! Супер!

**Comment by ekkky** [comment]
Илья, если необходимо вообще у всех записей, у которых даже не установлено `meta_key`= 'parser_content', то какой будет запрос?

**Comment by vimruler** [comment]
> если необходимо вообще у всех записей, у которых даже не установлено meta_key= 'parser_content', то какой будет запрос?

Что-то ничего толкового на языке SQL в голову не приходит. Возможно одним запросом сделать не получится. Лично мне такую задачу проще решать на php.
