### ISSUE TITLE
Автоматически обновлять превьюшки файлов на странице создания записи

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#11]
Предлагаю избавиться от ссылки "обновить" которая появляется после загрузки файлов, привязанных к записи. Видимо, можно сделать, чтобы превьюшки обновлялись автоматически. Если получится, вышлю пулл-реквест ;)

**Comment by maxsite** [comment]
В чём здесь фишка? localStorage — это на всех браузерах работает?

**Comment by cuprum** [comment]
На современных - у всех. http://caniuse.com/#search=localstorage

**Comment by maxsite** [comment]
А по какому принципу срабатывает обновление файлов?

**Comment by cuprum** [comment]
@maxsite при загрузке файла со страницы загрузок в локальное хранилище пишется циферка, а на странице создания записи обработчик слушает, есть ли изменения в лок. хранилище, если есть то обновляет превьюшки (раньше для этого надо было кликать "Обновить" ручками)

**Comment by vimruler** [comment]
Даже если само localStorage работает стабильно и логика верна, то как это поможет обработать ситуацию, когда над постом работают несколько человек (или один, но из разных браузеров)? Допустим даже не одновременно. ИМХО, самый надёжный способ обноволять превьюшки - периодически делать ajax-запрос к спец-скрипту, который следит за содержимым папок.

ЗЫ: Спрашиваю без претензии, просто пытаюсь понять насколько предложенная схема работоспособна.

**Comment by maxsite** [comment]
Почему именно localStorage? И почему нельзя оставить ссылку «Обновить»?

**Comment by cuprum** [comment]
@vimruler да не будет работать,когда один человек работает на записью из разных браузеров, только что-то слабо представляю, зачем это нужно.

@maxsite а какие есть еще варианты? Можно, конечно, ссылку "Обновить" оставить, если что-то пойдет не так, то обновлять вручную.

**Comment by maxsite** [comment]
Юра, я не против. Код необычный, поэтому хочу разобраться. Как именно работает вот это — «обработчик слушает». Какая часть кода? Эта: «$(window).on("storage"...» ???

И по какому событию обновляется localStorage? Как будто это $(".update"). Но ведь это просто div с сообщением о результате...

**Comment by cuprum** [comment]
@maxsite да, так и есть. На странице загрузок при каких-то изменениях (загрузка или удаление) появляется блок div.update. Вот его я и отлавливаю. Если он есть (updateMsg.length), то пишем в лок.хранилище ID страницы, которое берем из URL.
Есть событие storage, которое возникает, когда в хранилище пишется или удаляется из него инфа (или хранилище очищается). Вот на странице создания записи обработчик `$(window).on("storage", function(e) {...}` этим и занимается. Если событие возникло, он смотрит значение ID записанное в хранилище, если это значение совпадает с ID страницы, которую юзер редактирует, то посылается запрос на обновление превьюшек. Когда ответ пришел и  превьюшки обновились, хранилище очищается - `localStorage.clear();`
Фишка в том, что если послать запрос на изменение хранилища в одной вкладке (странице загрузки), то событие появится во всех других отрытых вкладках, по крайней мере, в пределах домена. 
В целом вроде так, давно делал, может забыл чего ;-) Ты попробуй протестировать, должно работать.

**Comment by maxsite** [comment]
Ок. Понял. Добавлю в dev ветку MaxSite CMS. Потестируем.
