### ISSUE TITLE
Предложение: добвить хук в mso_find_ts_file

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#110]
В функции __mso_page_foreach__ есть вызов хука __type-foreach-file__, что позволяет плагинам удобным образом переопределять используемый type_foreach-файл шаблона.

В последних версиях движка стала намного больше и чаще использоваться функция __mso_find_ts_file__, которая также по смыслу помогает находить  полный путь подключаемого файла (как правило шаблона). Считаю, что было бы логичным добавить и в эту функцию возможность вызова какого-нибудь специального хука, чтобы плагины могли и здесь перехватывать логику шаблона на себя.

Например, в __\shared\type\page\page.php__ вывод комментариев осуществляется кодом:

```php
// здесь комментарии
			
if (mso_get_option('comment_other_system', 'general', false))
{
	if ($fn = mso_find_ts_file('type/page/units/page-comments-other-system.php')) require($fn);
}
elseif ($fn = mso_find_ts_file('type/page/units/page-comments.php')) require($fn);
``` 

Если мне нужно выводить комментарии каким-то своим способом (не обязательно сторонним сервисом), то приходится в папке своего шаблона делать свой файл __type/page/units/page-comments.php__ и уже в нём вызывать хук или свою логику прописывать.

В случае одного клиентского сайта не велика сложность файл запилить. Но вот хотелось бы уменьшить эту рутину до простого копирования и включения плагина, который бы уже сам мог подхватывать и переопределять вывод. 

Максим, что скажешь?

**Comment by maxsite** [comment]
Ну ты представляешь сколько всего переделывать ради какого-то мифического хука?

**Comment by vimruler** [comment]
> Ну ты представляешь сколько всего переделывать ради какого-то мифического хука?

Не понял о чём ты переживаешь «столько всего переделывать»? Там надо то, встроить в логику определения адреса обращение к хуку. Т.к. сейчас обработчиков хука нет, то всё будет работать как и работало (т.е. сработают обычные ветки условий). Появится обработчик - сработает он.

Может напомнить тебе как сделано в __mso_page_foreach__? Вот нужный фрагмент:

```php
if (in_array($type_foreach_file . '.php', $files)) // есть файл в шаблоне
	return getinfo('template_dir') . 'type_foreach/' . $type_foreach_file . '.php';
else 
{	
	// файла нет
	// если есть хук type-foreach-file
	if (mso_hook_present('type-foreach-file'))
	{
		// получим его значение
		// он должен возвращать либо полный путь к файлу, либо false
		if ($out = mso_hook('type-foreach-file', $type_foreach_file)) 
			return $out; // указан путь
		else 
			return false; // вернул false
	}
	else // нет хука type-foreach-file
		return false;
}

```

Вот нечто подобное я и прошу сделать в __mso_find_ts_file__.  Сейчас там вот такая логика:

```php
$fn1 = getinfo('template_dir') . $fn; // путь в шаблоне
$fn2 = getinfo('shared_dir') . $fn; // путь в shared
	
if ( file_exists($fn1) ) return $fn1; // если шаблонный
elseif (file_exists($fn2)) return $fn2; // нет, значит shared
else return $default;
```

А могло быть что-то типа такого:

```php
$fn1 = getinfo('template_dir') . $fn; // путь в шаблоне
$fn2 = getinfo('shared_dir') . $fn; // путь в shared
	
if ( file_exists($fn1) ) return $fn1; // если шаблонный
elseif (mso_hook_present('find_ts_file') && $out = mso_hook('find_ts_file', $fn) ) return $out; // указан путь
elseif (file_exists($fn2)) return $fn2; // нет, значит shared
else return $default;
```

**Comment by maxsite** [comment]
Там разная логика при использовании функций. В type_foreach файла может и не быть. Тогда и нет подключения либо при вызове отлавливается это условие. В mso_find_ts_file файл всегда есть, только он может быть либо в shared, либо в каталоге шаблона. То есть эта функция только для того, чтобы отдать приоритет шаблону и если файла нет, то берем из shared. 

Таким образом я не понимаю, что делать будет хук в mso_find_ts_file. Я вообще не уверен, что есть такие задачи. Скорее всего срабатывает твоя любовь к хукам и желание сделать на будущее «а вдруг пригодится». :-)

**Comment by vimruler** [comment]
> Таким образом я не понимаю, что делать будет хук в mso_find_ts_file. Я вообще не уверен, что есть такие задачи. Скорее всего срабатывает твоя любовь к хукам и желание сделать на будущее «а вдруг пригодится». :-) 

Увы, но у меня пока есть только одна реальная задача для этого хука - я сделал свой плагин древовидных комментариев ~~с картами и девушками~~ и пока подключаться в работу получается только бросанием в папку шаблона своего файла __\type\page\units\page-comments.php__. В этом файле просто хук для цепляния плагина. Так приходится делать потому что сейчас вывода каментов в __\shared\type\page\page.php__ прописан кодом:

```php
if (mso_get_option('comment_other_system', 'general', false))
{
	if ($fn = mso_find_ts_file('type/page/units/page-comments-other-system.php')) require($fn);
}
elseif ($fn = mso_find_ts_file('type/page/units/page-comments.php')) require($fn);
```
В нём через page-comments-other-system.php подключиться нельзя, т.к. там просто html код из опций выводится. Вот и остаётся свой файл /type/page/units/page-comments.php в папке шаблона делать.

Гипотетически, можно не делать хук в __mso_find_ts_file__, а просто расширить логику выбора источника вывода комментов и в неё добавить хук. Меня такой вариант тоже бы вполне устроил и ты бы не переживал, что сделали избыточный функционал.

**Comment by maxsite** [comment]
Вот по задаче и нужно решать что делать. Прописать отдельный хук под конкретную задачу гораздо проще. Насколько я понял, то нужно добавть еще одну условие на наличие какого-то хука перед mso_find_ts_file и если хук есть, то выполнить его и получить путь к файлу для подключения?

**Comment by vimruler** [comment]
> Вот по задаче и нужно решать что делать. Прописать отдельный хук под конкретную задачу гораздо проще.

Просто внутри плагина я тоже разбиваю на подшаблоны вывод и их хотел дать возможность вебмастеру свои создавать и размещать в стандартном месте. Но ладно, обыграю иначе.

> Насколько я понял, то нужно добавть еще одну условие на наличие какого-то хука перед mso_find_ts_file и если хук есть, то выполнить его и получить путь к файлу для подключения?

Да. Примерно так:

```php
if (mso_get_option('comment_other_system', 'general', false))
{
    if ($fn = mso_find_ts_file('type/page/units/page-comments-other-system.php')) require($fn);
}
elseif (mso_hook_present('page-comment-other') && $fn = mso_hook('page-comment-other') )  require($fn);
elseif ($fn = mso_find_ts_file('type/page/units/page-comments.php')) require($fn);
```

**Comment by maxsite** [comment]
Для «подшаблонов» мы условились, то будет использоваться custom/plugins/ПЛАГИН/

Хук пусть будет page-comment-unit-file.

**Comment by vimruler** [comment]
> Для «подшаблонов» мы условились, то будет использоваться custom/plugins/ПЛАГИН/

Хорошо. Это больше нужно пользователям, но постараюсь учесть в инструкции.

> Хук пусть будет page-comment-unit-file.

Хорошо. Спасибо!

**Comment by maxsite** [comment]
Выложил. Проверь.

**Comment by vimruler** [comment]
Да, всё так. Ещё раз спасибо!
