### ISSUE TITLE
Когда на maxhub.ru появится дизайн? Такой, как на max-3000.com, презентабельный

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#111]
Когда это будет?
Вот, даже статья есть http://max-3000.com/page/differences-templates

**Comment by vimruler** [comment]
Лестно конечно, но не думаю, что тема имеет отношение к Максиму и движку :)

Сайт конечно будет переделываться, но по мере сил и времени. Ну и выбрать оформление надо. На офсайте хоть и презентабельный дизайн, но хотелось бы некоторые моменты сделать иначе.

**Comment by vimruler** [comment]
Да, лучше этот вопрос было задавать [здесь](http://maxhub.ru/page/katalog-plaginov-vossozdan-nashi-dalnejshie-plany).
