### ISSUE TITLE
обратная связь отправляет письма на admin@site.com

### ISSUE THREAD

**Issue by Fore-Man** [maxsite/cms#113]
Стандартная страница обратной связи **/contact** в версии 0.93 отправляет письма непонятно куда
>Письмо admin@site.com не может быть доставлено Причина: письмо отправлено на несуществующий адрес

Подскажите, что подправить до момента решения в коде

**Comment by maxsite** [comment]
Ну так укажите нормльный email.

**Comment by Fore-Man** [comment]
Настройки >> основные >> Email-адреса
> Укажите необходимые email-адреса

Указаны первых 2
еще есть несколько сайтов. Проверял и на них. На 0,90 версии, тоже не отправляет, а с версией 0,863 живущий - письма идут как положено.
Если у Всех все нормально, а лишь у меня не отправляет, то возможно нужна поправка как и для инсталяции движка. У меня Fast CGI на сервере.

**Comment by maxsite** [comment]
Для контактной формы есть отдельная вкладка.

**Comment by Fore-Man** [comment]
Нашел. Странно, почему такого плана вопросы мне постоянно приходится Вам задавать первым, или может просто плохо ищу на форуме.
Раньше все работало автоматом, а с новыми версиями до последнего сайта не использовал страницу обратной связи.

**Comment by maxsite** [comment]
Потому что менялся формат формы. Об этом я писал в анонсах на офф.сайте.
