### ISSUE TITLE
Проблемы во время установки 0.93

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#114]
Здравствуйте. Может и на более ранних это есть - не знаю.
1. mso-config.php-distr не переименовывается в mso-config.php;
2. Данные базы данных в database.php не вводятся, хотя установщик сообщает, что всё успешно. И -distr у него не удаляется.

**Comment by maxsite** [comment]
Файлы «-distr» и не должны удаляться. Должны создаваться новые (без «-distr»), если их нет. Если в них нет записи, значит нет прав на сервере.

**Comment by denis-skripnik** [comment]
Я не говорил, что они должны удаляться. Дело в том, что без -distr файлы не создаются. Права должны быть 0777?

**Comment by maxsite** [comment]
Файлы -distr — это шаблон/заготовка. Права на файлы 666, каталоги 777.
