### ISSUE TITLE
Предложение: генерировать в last_pages превью картинку под нужный размер

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#115]
Сейчас превью картинка для отображения в списках (на главной, в рубриках, тэгах) и на самой странице записи обрабатывается __\shared\stock\thumb\thumb.php__ и создаётся копия картинки нужного (как правило уменьшенного) размера. Но плагин __last_pages__ при выводе виджета тоже использует картинку записи, однако сейчас её приходится масштабировать через css, что бывает не оптимально при отображении на странице.

Клиент просит доработать плагин чтобы в нём тоже создавалось превьюшки нужного размера для виджета. Хочу чтобы правка вошла в дистрибутив (думаю полезная доработка), поэтому хочу спросить, Максим, как лучше сделать доработку? Вижу так:
* Ввести в настройки виджета опцию размера
* Подключить __\shared\stock\thumb\thumb.php__ 
* Сгенерить картинку. В качестве примера код можно взять, например, из юнита __last-pages.php__

Есть какие-то рекомендации?

**Comment by maxsite** [comment]
Вообще, конечно, я вот глянул на юнит last-pages.php и вижу, что он делает тоже самое, только круче. Если использовать юнит, то формат плагина last_pages можно сделать как в юните в виде textarea. Правда потеряется совместимость со старым. Или старый переименовать в last_pages_old. Как идея?

**Comment by vimruler** [comment]
Я не любитель плодить модификации плагинов и тем более держать их рядом. Поэтому давай сперва ещё обсудим такой вариант: задействовать стандартные опции плагина и сделать там textarea, чтобы было что-то типа хранилища настроек для виджетов. Только придётся расширить синтасис настройки юнита параметром UID  - т.е. нужен «идентификатор», если настроек несколько. Тогда в настройках виджета можно добавить поле (текстовое или выпадающий список) для указания идентификатора настроек и если поле будет заполнено, то будут использоваться настройки для юнита. Если поле «пустое», то также будет работать юнит, просто настройки будут формироваться из значений полей опций виджета.

Как-то так. При таком варианте плагин продолжит работать после обновления движка и сохранится обратная совместимость. 

Что скажешь?

**Comment by maxsite** [comment]
Не, если делать, то новый. Старый оставить на пану версий, а после убрать. Это проще, чем менять код.

Сам плагин довольно простой, поскольку он обычным require подключат last-pages.php, который, собственно всё и делает. Сделать только две настройки: секция unit (только секция без обрамления) и условие вывода, как в универсальных компонентах. Можно там же предусмотреть и время кэширования виджета.

**Comment by vimruler** [comment]
> Старый оставить на пару версий, а после убрать. Это проще, чем менять код.

А, ну если можно будет потом убрать из коробки старый плагин, то конечно проще так сделать, как ты предлагаешь. Ок, тогда реализую и пришлю.

> и условие вывода, как в универсальных компонентах.

А разе условие вывода не реализуется уже на уровне настройки сайдбара? Там же вроде есть возможность указать условие.

> Можно там же предусмотреть и время кэширования виджета.

Т.е. поле такое оставить и не ориентироваться на настройку с главной страницы?

**Comment by maxsite** [comment]
> А разе условие вывода не реализуется уже на уровне настройки сайдбара? Там же вроде есть возможность указать условие.

Да, точно. Забыл. :)

> Т.е. поле такое оставить и не ориентироваться на настройку с главной страницы?

Лучше отдельно. Пусть у каждого виджета будет свой выбор.

**Comment by vimruler** [comment]
> Вообще, конечно, я вот глянул на юнит last-pages.php и вижу, что он делает тоже самое, только круче. Если использовать юнит, то

Вот эти слова "если использовать юнит" - они что значат? Ты имеешь в виду, что в плагине нужно сразу цеплять файл юнита или всё таки просто его код скопировать?

**Comment by maxsite** [comment]
Скопировать файл из default-шаблона в каталог плагина и там его через require подключать. Так я смогу его обновлять просто заменив файл.

**Comment by vimruler** [comment]
Понятно. Так и сделаю.
