### ISSUE TITLE
Ошибка в работе плагина оценки страниц

### ISSUE THREAD

**Issue by LeonisX** [maxsite/cms#116]
Нет возможности поставить оценку новости, так как блок не виден.

![2015-12-04 21 51 18](https://cloud.githubusercontent.com/assets/13258944/11599744/3989af76-9ad1-11e5-97db-4c577e7dca66.png)

На странице код есть:

<div class="mso-page-content mso-type-page-content">
Это ваша первая запись. <strong>Вы можете</strong> её отредактировать или удалить через админ-панель.<div class="mso-clearfix"></div><aside>
	<div id="rater" title="Текущая оценка: 0. Голосов: 0"><script>
		$('#rater').rater('http://scala.16mb.com/ajax/cGx1Z2lucy9yYXRlci9yYXRpbmdzLXBvc3QtYWpheC5waHA=', {maxvalue:10, style:'basic', curvalue:0, slug:'1'});
	</script></div>

В консоли браузера: TypeError: $(...).rater is not a function

Причину не нашёл :(

**Comment by maxsite** [comment]
Исправлю. Неверно js-скрипт вызывался.

**Comment by LeonisX** [comment]
Благодарю :) Забыл сказать, что вчера просмотрел несколько движков, MaxSite на их фоне смотрится очень круто, остановился именно на нём, несмотря на то, что поставить вышло не с первого раза (лень было сразу инструкцию прочесть и разобраться :))
