### ISSUE TITLE
Неправильное отображение Дефолтного шаблона версии 0.93

### ISSUE THREAD

**Issue by Kantona74** [maxsite/cms#119]
Нечайно вышел на свой блог с браузера SAFARI и увидел такую вот проблему - http://vk.com/doc87129068_437100484 . Тестировалось на ipad и ПК. Возможно в бругих браузерах          так же отображается неправильно! Кто знает как поправить??

**Comment by maxsite** [comment]
Скриншот покажите нормально. Не все в vc имеют доступ. :)

**Comment by Kantona74** [comment]
![2015-12-07_195146](https://cloud.githubusercontent.com/assets/16192549/11632862/8c646dc0-9d2a-11e5-98a7-0162d7124919.png)

**Comment by maxsite** [comment]
Какой ужас... А версия браузера какая?

**Comment by Kantona74** [comment]
Я не знаю( Заходил с iPada знакомого, а тестировал с помощью сервиса https://www.browserling.com/

**Comment by maxsite** [comment]
Сафари должен быть не менее 8- версии: http://caniuse.com/#search=flex

**Comment by Kantona74** [comment]
Значит все таки на самом деле все в порядке?))

**Comment by maxsite** [comment]
Будем считать что да.

**Comment by Kantona74** [comment]
Ну и отлично))
