### ISSUE TITLE
Опции для настройки текстов почтовых уведомлений

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#12]
Сейчас тексты уведомлений «прошиты» в движке. Иногда возможностей стандартных текстов не хватает. Например, текст когда нужна активация или уведомление «Спасибо за регистрацию на сайте...» бывает нужно подправить согласно поставленной перед сайтом задачей.

Предлагаю сделать специальные опции для шаблонов писем, а потом, в коде делать проверку наличия заданной опции и если она есть, то подставлять её. Конечно же в каждом случае нужно предусмотреть макросы для подстановки. Как минимум те данные, которые используются в стандартных уведомлениях.

Могу реализовать всё необходимое сам, если идею поддержат.

**Comment by maxsite** [comment]
Строго говоря там нужно делать по другому. Должны быть шаблоны писем, где используются спецвставки для замен. Например  [SITEURL] будет заменен на адрес сайта. Такми образом потребуется всего несколько опций.

**Comment by vimruler** [comment]
Если шаблоны стандартных писем будут вынесены и доступны для кастомизации - будет совсем здорово. Правда затрудняюсь пока предложить вариант реализации. Возможно, было бы логичным использовать механизм type_foreach.

**Comment by maxsite** [comment]
На самом деле там не очень сложно. Например функция mso_email_message_new_comuser(). Формируется $text. Для начала нужно переделать функцию без использования опций (потом её добавить не проблема). 

```
$text = "Вы или кто-то еще зарегистрировал ваш адрес на сайте [SITEURL] ...";

$text = str_replace('[SITEURL] ', getinfo('siteurl'), $text);

```

То есть в $text задается исходное письмо с вставками, а в коде производятся замены.
