### ISSUE TITLE
Загрузка файлов для редактора на лету

### ISSUE THREAD

**Issue by wave-maxsite** [maxsite/cms#120]
**Имеется код загрузки файлов на лету во вкладке под редактором.**
Писался для версии 0.863, адаптировался для 0.932.

Выглядит так. Во вкладке «Файлы» под редактором добавлена кнопка «Загрузить файлы». Доступная только при наличии соотв. прав. По нажатию на неё, появляется панелька с опциями «Размер изображения» и прочими, и кнопкой выбора файлов. После выбора файлов они на лету без перезагрузки страницы грузятся в соответствующий каталог `_pages/###` и тут же обновляется сама вкладка файлов.

Если это не редактирование страницы, а создание, файлы грузятся во временный каталог (в настройках сайта добавлена опция), а при сохранении страницы переносятся в уже постоянную локацию `_pages/###`. Также если файлы вставлялись в текст записи или метаданные (изображение страницы), они правятся на новый путь.

**Comment by maxsite** [comment]
Очень большой и неоптимальный код.

**Comment by wave-maxsite** [comment]
Насчёт большого не согласен, для такой задачи меньше никак. Да и чистого кода там всего килобайт 20, остальное — небольшой jquery-плагин и собственно код admin_page.

Насчёт неоптимальности — что именно непотимально и как оптимизировать?

**Comment by vimruler** [comment]
> Очень большой и неоптимальный код.

Согласен. Есть спорные моменты, но можно получить от тебя конкретнее указания где оптимизировать? Функционал очень востребованный и хотелось бы сдвинуть вопрос в положительную сторону...

**Comment by maxsite** [comment]
В первую очередь все jQuery-плагины. Код аякс загрузки должен быть гораздо меньше. Типовой вариант умещается гдето в 3-5Кб включая разные плюшки, вроде вывода messages.

**Comment by maxsite** [comment]
Отмечу несколько моментов. Первое — загрузка только после сохранения записи. Никаких искуственных привязок к сессиям и т.п. Пока у записи нет id, мы не можем ничего к ней привязать. К сессии привязываться вообще очень спорный момент. Вылетел Инет, переконетился уже другой ip и другая сессия. Всё — появляются какие-то висячие файлы.

Второе. Загрузка должна быть автоматическая по аяксу, включая и перетаскивание drag-n-drop. Никаких панелек не нужно. Просто перетащил файл в выделенную обрасть и всё — файл автоматом загрузился. Миниатюра создается на основе заданных опций. Размер/обрезка также на основе указанных настроек. Если нужны какие-то особые операции с файлами, то переходим на Загрузки и там все делаем.

**Comment by vimruler** [comment]
> В первую очередь все jQuery-плагины. Код аякс загрузки должен быть гораздо меньше. Типовой вариант умещается гдето в 3-5Кб включая разные плюшки, вроде вывода messages.

Думаю, что этап минификации можно отложить до момента, когда будет согласован основной функционал. Другой вопрос, что если сейчас используется опенсорсная библиотека и она имеет избыточный функционал, то будет довольно сложно выпиливать из неё "ненужное". Можно было бы подумать о другой библиотеке. Раз ты так уверенно говоришь про размеры js-файла, то наверно у тебя есть перед глазами подходящий пример - поделишься названием/ссылкой?

>Первое — загрузка только после сохранения записи. Никаких искуственных привязок к сессиям и т.п. Пока у записи нет id, мы не можем ничего к ней привязать. 

С одной стороны я понимаю, почему ты так говоришь. Но с другой стороны, у меня перед глазами есть пример моего плагина, в котором реализована привязка к сессии и всё работает нормально (мусор чистится) даже в более агрессивной среде, чем админ-панель блога одного человека. Поэтому хотелось бы услышать про минусы, на которых ты основываешь своё решение - это просто для общего развития. Думаю, что для движка Вадим вполне может переделать код так, чтобы до сохранения записи его код ajax-загрузки не срабатывал и не показывался вообще (может стоит тогда сделать вывод блока-сообщения, что удобная загрузка файлов будет доступна после сохранения записи?).

> Загрузка должна быть автоматическая по аяксу, включая и перетаскивание drag-n-drop. 

Эта возможность во многом зависит от используемой библиотеки загрузки - т.е. снова возвращаемся к вопросу о твоих предложениях (если они есть) по js-библиотеке для File Upload-а.

В общем, какие-то моменты я думаю вполне реально подправить. Но что делать, если пожелания в контексте проделанной работы не возможно удовлетворить? Может можно будет как-то оформить наработку в виде плагина (тогда нет нужды включать спорный код в дистрибутив)? Если Вадим укажет места, в которых нужны хуки для подключения - Максим, можно будет получить твою поддержку (хуки в ядре движка)?

**Comment by maxsite** [comment]
У меня только в работе есть код для LPF. Но вообще, вот например http://www.sitepoint.com/html5-file-drag-and-drop/ 

> Но с другой стороны, у меня перед глазами есть пример моего плагина, в котором реализована привязка к сессии и всё работает нормально

В этом коде каталог создается по сессии. Вообще — нельзя привязываться к записи, пока её нет. Это вообще противоречит здравому смыслу. Есть запись, тогда работаем.

> В общем, какие-то моменты я думаю вполне реально подправить. Но что делать, если пожелания в контексте проделанной работы не возможно удовлетворить?

Я уже неоднократно предупреждал: посоветуйтесь перед тем, как менять что-то в системе. Или вы думаете, что у меня самого нет подобных заготовок? Ну вот даже эта же аякс-загрузка, Юра не даст соврать, год назад делали, но так и не побороли, хотя там и js-скрипт и код есть. За это время новые наработки и идеи появились. В данном случае я обрисовал задачу. Для обкатки могу только поделиться наработками для LPF. Там у меня эти вещи уже реализованы. На них можно базироваться и как минимум потестировать, прежде чем портировать на MaxSite CMS.
