### ISSUE TITLE
Проблема - Fatal error: Allowed memory size of 134217728

### ISSUE THREAD

**Issue by amigoscs** [maxsite/cms#122]
Выдал ошибку:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8273049 bytes) in /.../application/maxsite/common/common.php on line 1171

При построении списка категорий. Плагин category.

В таблице page - 14,330 записей.
В таблице cat2obj - 42,758 записей
В таблице category - 128 записей
В .htacces память - <strong>php_value memory_limit 128M</strong>

Если не увеличивать память, то проблему можно как-то решить?

**Comment by maxsite** [comment]
Статистика в футере какая?

**Comment by amigoscs** [comment]
Отмечу, ошибка произошла после сброса кэша.

Поднял память до 256M. Заработало. Статистику стал показывать около 3-х секунд скачет. Это для страницы категории. Для главной - 0.15 с. (на главной кроме плагина category ничего динамического)

Я так понял, список рубрик закэшировался и category перестал грузить.

Дальше - в двух местах применяю функцию mso_get_cat_from_slug();
Вместо функции в этих местах прописал вручную Id категории. Статистика улучшилась до 0.8(плюс/минус) в категории .

**Comment by maxsite** [comment]
Статистика в футере какая?

**Comment by amigoscs** [comment]
Время: 0.6246 | SQL: 10 | Память: 11.93MB

**Comment by maxsite** [comment]
А сразу после сброса кэша?

**Comment by amigoscs** [comment]
Сейчас.
Время: 4.8819 | SQL: 21 | Память: 12.11MB

**Comment by maxsite** [comment]
Значит для php хватит и 16Мб. Возможно проблема в настроках самого php. Если там загружаются большие модули, то тогда лимитов может и не хватить. По статистке видно, что потребление памяти относительно небольшое.

**Comment by amigoscs** [comment]
Так то оно так. Аналогичная проблема у меня случилась и на другом сайте. Там на тот момент было около 16000 тыс записей. Тоже поднял лимит до 256, все заработало. В футере статистика так-же около 11Мб. (Кстати, иногда ошибку выдавал и если кэш НЕ сбрасывался) 
Я подумал, что хостинг дурацкий. Не стал заморачиваться. Но сейчас хостинг другой и дороже. 
Хз.

С ростом записей все-равно скорость вывода в категории падает. Надо что-то делать с foreach-ми. Слишком большие массивы приходится перебирать.
В двух функциях 
<code>mso_get_cat_url_from_id()</code>
<code>mso_get_cat_from_id()</code>
я заменил foreach на 
<code>if(isset($all_cats[$id]['category_slug'])) return $all_cats[$id]['category_slug'] </code>
и 
<code>if(isset($all_cats[$id][$find_key])) return $all_cats[$id][$find_key] </code>
А также в функции <strong>mso_get_cat_from_slug()</strong> я сделал запрос SQL (здесь согласен, не совсем полный функционал - но это так, для теста). 
Эти манипуляции дали мне выигрыш в приблизительно 0.5с на вывод страницы категории.

**Comment by maxsite** [comment]
А сколько рубрик всего?

**Comment by maxsite** [comment]
И это на default-шаблоне?

**Comment by maxsite** [comment]
Ясно. Ещё проверьте один момент. Сбросьте кэш и обновите страницу. В каталоге cache появятся файлы, один из них как раз кэш mso_cat_array_single() (по содержимому будет понятно). Какой у него размер?

**Comment by amigoscs** [comment]
793 959 байт. Вроде он. Самый большой.

**Comment by maxsite** [comment]
Да, большой. Хотя для сервера не проблемный. Можно еще включить Динамическое кэширование в настройках. Это приведет к увеличению памяти, но снимет нагрузку с этого файла (он только 1 раз загрузится). Если есть возожность включите для php eAccelerator. Он сразу снимет все эти проблемы.

**Comment by amigoscs** [comment]
Ок. Буду пробовать.
