### ISSUE TITLE
Баг: количество записей на страницах рубрик вычисляется по старому

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#123]
Способ хранения опций недавно сменился и теперь идёт привязка к шаблону. Но в шаблонах на основе __shared__ есть места, где привязка осталась просто к "templates". Например, в выборке записей категорий количество постов получает по-старому ( __\application\maxsite\shared\type\category\category.php__  ):
```php
// параметры для получения страниц
$par = array( 
		'limit' => mso_get_option('limit_post', 'templates', '7'),
		'cut' => mso_get_option('more', 'templates', 'Читать полностью »'),
		'cat_order' => 'category_id_parent',
		'cat_order_asc' => 'asc',
		'type' => false,
		'content' => $full_posts
	); 
```
Поиск 'templates' в shared папке выдал ещё много мест, где значения опций берутся по старому. Надо бы поправить на getinfo('template').

**Comment by maxsite** [comment]
Это не баг, так и задумано. Опции есть общие для всех шаблонов, тогда у них тип templates, а есть индивидуальные, тогда у них тип уже свой. В данном примере — общая опция. Её нет смысла делать индивидуальной.

**Comment by vimruler** [comment]
А, точно. Что-то я не догадался сразу заглянуть в ini файл, чтобы проверить откуда берётся значение. Топик снимаю. Это не баг.
