### ISSUE TITLE
Email отправителя при регистрации комюзеров. Получается сам себе почту отсылаешь.

### ISSUE THREAD

**Issue by genjae** [maxsite/cms#124]
Добрый день. 

Проблема такая. При регистрации комюзеров, при необходимости подтверждения емайла, на почту приходит письмо от самого себя же. Почему не от имени сайта/сервера, указанного в настройках? 
Считаю надо поменять по двум причинам:
1. Это было бы логичнее, получать письма например от "noreply@site.ru", а не от самого себя. 
2. Почтовики не хотят просто так пропускать такие письма. Gmail предупреждает о возможном фишинге, Mail.ru вообще не принимает такие письма, даже в спам, Yandex тоже проблемно принимает. На других не пробовал.

**Comment by vimruler** [comment]
Добавлю. Это в __\application\maxsite\common\comments.php__ строка 412:
```php
 return mso_mail($email, $subject, $text, $email); // поскольку это регистрация, то отправитель - тот же email
```

**Comment by maxsite** [comment]
Ну и пусть попадает в спам. Это гораздо лучше, чем вычищать свой сервер от левых адресов.

**Comment by genjae** [comment]
В наш сервер письма попадать не будут: это ведь исходящие сообщения. 
И в спам они не попадают, а вообще не появляются на mail.ru.  

И для посетителей странно, что им приходят сообщения с кодом подтверждения емайла с уведомлением о возможном фишинге, или вообще не приходят. Это сильно бьет по репутации сайта.

**Comment by maxsite** [comment]
Чаcто указывают левые email. Если указывать свой сервер для ответа, то они все и вернутся. Мне всё равно что там в глючном яндексе или майл-ру. Это их проблемы.

**Comment by vimruler** [comment]
Максим, думаю вопрос __genjae__ снялся бы, если бы была возможность переопределять параметры отправки почты. Посмотрел функцию mso_mail и там есть только хук, полностью перехватывающий отправку письма. А можно как-то предусмотреть хук, именно для переопределения параметров отправки? Есть же нечто такое в __mso_get_pages__?

Понимаю, что введение такого хука может потребовать переделки функции на использование вместо поступивших в функцию переменных, например, элементов массива $arg. Поэтому если у тебя нет принципиальных возражений, то я бы переделал функцию и прислал тебе на утверждение. Что скажешь?

**Comment by maxsite** [comment]
Хук на что, $email?

**Comment by genjae** [comment]
Максим, по-моему очень наплевательское отношение у Вас к посетителям сайтов, сделанных на MaxSite cms. А ведь именно ради посетителей и создаются проекты. 

Насчёт левых емайлов. Кто не хочет оставлять емайл, тот пишет без регистрации. Регистрируются только те, кому это необходимо. И на серьёзных проектах не принято оставлять левые емайлы. Также могу сказать, администратор для того и нужен, чтобы следить за порядком и "вычищать сервер от левых адресов", если для большинства посетителей это будет удобно.

**Comment by vimruler** [comment]
> Хук на что, $email?

Ты меня пугаешь :) Там есть массив $arg для передачи в хук mail. Ну так вот, нужно этот массив передать в хук, например, __mail_params__ Хук вернёт изменённый массив (или такой же) и потом элементы массива уже можно использовать в формировании письма. Вроде же всё очевидно...

**Comment by maxsite** [comment]
У меня наплевательское? Ок. Принципиально не буду ничего менять.
