### ISSUE TITLE
editor_markitup

### ISSUE THREAD

**Issue by Kmartynov** [maxsite/cms#125]
В админ Plugins Есть editor_markitup.
По идее к хуку editor_markitup_bbcode можно навешать своих кнопок.
Но как я не старался прицепиться к нему. Что-то не вышло.
Пробовал на лету через ушки к хуку. Может что-то делаю не так?

**Comment by vimruler** [comment]
У меня в плагине [Down Counter](http://maxhub.ru/page/plugin-down-counter) можно посмотреть пример добавления кнопок в editor_markitup

**Comment by Kmartynov** [comment]
Именно все так и делаю, правда пока для тестирования использую ушки и ушки к хукам. Вешаю свою ушку на хук editor_markitup_bbcode и пока просто добавляю сепаратор.
Ничего не меняется

**Comment by Kmartynov** [comment]
Что-то странное творится, если делаю плагин, то кнопки цепляются, почему через ушку не хочет?
В чем принципиальное отличие?

**Comment by vimruler** [comment]
> почему через ушку не хочет?

А код в ушке правильно оформлен? Ошибок нет? Тестовый вывод pr() - срабатывает из ушки?

**Comment by Kmartynov** [comment]
Вроде как да, Но наверное мне более не актуально.
Обошелся через плагин. Так удобнее %)
