### ISSUE TITLE
Админ-панель рубрик - есть пожелания?

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#126]
Клиент выразил пожелание повысить удобство работы в админ-панели рубрик, цитирую фрагмент переписки:

> в админ-панеле в рубриках сделать общую кнопку "сохранить". Иногда бывает много изменений сразу в нескольких рубриках и неудобно сохранять каждое небольшое изменение по отдельности в каждой рубрике (еще и вверх страница прокручивается при сохранении).

Мне по-любому придётся решать эту задачу для него. По возможности хотелось бы эту наработку включить в ядро. Поэтому приглашаю высказывать пожелания и ценные указания. Особенно жду от Макса - есть идеи?

У меня в голове пока крутится только идея сделать аякс-сохранение правок одной рубрики. Может ещё что-то нужно?

**Comment by maxsite** [comment]
По-идее там нужно всё переделывать. Текущий вариант довольно простой, потому что не было идей как это всё нормально организовать. Теперь, если есть желание, то я вижу страницу рубрик немного по-другому.

Выводится весь список примерно кака сейчас, но без полей редактирования. Отображаются Название, короткая ссылка, ссылка на рубрику на сайте и на фильтр редактирование записей этой рубрики (это всё уже есть). Тут же кнопка «Редактировать». По её нажатию открывается сразу под рубрикой блок, где размещаются уже все поля input/textarea и кнопка Обновить. Само сохранение, согласен с тобой может быть по аяксу. Поскольку в один момент времени может быть открыт только один блок, то проблем быть не должно — фактически сохраняется одна рубрика.

Добавление новой рубрики добавить вверху по этому же принципу. Кнопка Добавить рубрику, которая открывает блок, где форма добавления. Но в этой форме идет обычный POST, чтобы была перезагрузка страницы.

**Comment by vimruler** [comment]
Помню ещё когда то был вопрос - как удобнее сделать изменение порядка рубрик? Сейчас нужно руками поправить у одной рубрики номер позиции и после сохранения (обновления) страницы она встанет на своё место. По идее, было бы к месту перетаскивание. Но вот надо ли такое? И если надо, то какой скрипт использовать? 

По остальным идеям - согласен. Вот только хотел бы предложить такой вариант ещё - можно не открывать снизу под рубрикой форму её редактирования, а чтобы все редактируемые значения сразу становились полями формы при нажатии кнопки "редактировать". 

Также можно было бы просто отправлять данные формы при выезде мышки за пределы области формы или полей. Но вот не уверен, что пользователи не будут переживать из-за отсутствия кнопки :)

Кстати, если перегрузки страницы не будет, то ещё актуальнее встаёт вопрос по управлению порядком рубрик.

**Comment by maxsite** [comment]
Я не думаю, что порядок это самая востребованная задача. С перетаскиванием нужно сразу решать кучу проблем, поскольку оно может затронуть сразу несколько рубрик. Думаю, что там где порядок важен, достаточно будет вручную его поменять.

>  Вот только хотел бы предложить такой вариант ещё - можно не открывать снизу под рубрикой форму её редактирования, а чтобы все редактируемые значения сразу становились полями формы при нажатии кнопки "редактировать". 

Форма содержит больше полей и данных, чем отображение элемента списка. Поэтому другой альтернативы (ну кроме отдельной страницы для редактирования), я просто не вижу.

Кстати, если будем менять, то можно как-то предусмотреть и подключение метаполей к этой странице. Например некий файл в каталоге шаблона, где будут описаны метаполя (название/ключ (input) : значение (textarea)), которые будут выводиться в этой же форме.

**Comment by vimruler** [comment]
> Я не думаю, что порядок это самая востребованная задача. С перетаскиванием нужно сразу решать кучу проблем, поскольку оно может затронуть сразу несколько рубрик. Думаю, что там где порядок важен, достаточно будет вручную его поменять.

На моей практике часто приходится менять, особенно у новых сайтов пока они «устаканятся». Так что задача вполне актуальная. Другой вопрос, что перетаскивание именно, что создаёт кучу ненужных проблем и связываться с этим бы не хотелось. Такое решение скорее «рюшечка», чем что-то стабильно работающее. Так что пусть будет по старому.

> Форма содержит больше полей и данных, чем отображение элемента списка. Поэтому другой альтернативы (ну кроме отдельной страницы для редактирования), я просто не вижу.

Понял. Согласен.

> Кстати, если будем менять, то можно как-то предусмотреть и подключение метаполей к этой странице. Например некий файл в каталоге шаблона, где будут описаны метаполя (название/ключ (input) : значение (textarea)), которые будут выводиться в этой же форме.

Отлично, что вспомнил про это! Обязательно надо добавить мета-поля! Я так понимаю, что можно сделать файл по-умолчанию в shared папке и внести в него настройку для полей title, description, keywords. А если в папке текущего шаблона есть кастомный файл, то использовать его. Так? Может сделать появление формы для мета-полей только по нажатию на кнопку?

Пока писал понял что ещё смущает в обсуждаемом варианте. В текущем варианте (когда всё уже есть форма) получалось, что можно быстро править несколько рубрик и не хватало только единой кнопки сохранить. Сам несколько раз ловил себя на том, что начинал редактировать следующую рубрику не сохранив правки в предыдущей отредактированной. А теперь мы обсуждаем вариант, когда нужно будет делать больше кликов мышкой (начать редактирование, сохранить). Может всё таки можно улучшить сценарий?

**Comment by maxsite** [comment]
Когда сохранение по аяксу нет перезагрузки страниц, поэтому всё будтет происходить гораздо быстрей. Сейчас время тратится не сколько на само редактирование и нажатие Сохранить, а на перезагрузку и скроллинг к этому же месту на странице.

> Отлично, что вспомнил про это! Обязательно надо добавить мета-поля! Я так понимаю, что можно сделать файл по-умолчанию в shared папке и внести в него настройку для полей title, description, keywords. А если в папке текущего шаблона есть кастомный файл, то использовать его. Так? Может сделать появление формы для мета-полей только по нажатию на кнопку?

Пока я не знаю как это будет выглядеть, просто нужно будет заранее предусмотреть что будет какой-то вариант. Думаю, что после основной переделки займемся и метаполями.

**Comment by vimruler** [comment]
> Думаю, что после основной переделки займемся и метаполями.

Отчасти понимаю почему будем позже обсуждать. Но с другой стороны, если сейчас заложить, например, такой момент, что форма редактирования рубрики имеет табы (на одной основные поля, а на второй для мета-полей), то не придётся потом переделывать много кода.

**Comment by maxsite** [comment]
Это уже визуальные тонкости. Мне табы не нравятся, лишние движения. Тем более, что форма небольшая получается. Как вариант, нарисуй схематично своё видение, так будет даже проще для понимания.

**Comment by amigoscs** [comment]
Так плагин <a href="http://maxhub.ru/page/plagin-category_editor">Category editor</a> решает задачу порядка рубрики путем перетаскивания. Плюс перетаскиванием можно назначить родительскую рубрику. Порядок меняется у всех рубрик сразу согласно расположению в списке. + редактирование на отдельной странице с добавлением meta-полей.

**Comment by vimruler** [comment]
> плагин Category editor
в чём-то он хорош. Но выбивается по стилю оформления и использование мета-полей довольно своеобразно реализовано без подробного документирования. Клиентам я такую штуку поставить не могу, увы.

**Comment by vimruler** [comment]
> Тем более, что форма небольшая получается. 

Да, пожалуй. 

> Как вариант, нарисуй схематично своё видение, так будет даже проще для понимания. 

Да вроде понятно как ты говоришь. Схема пока избыточна. Может в процессе реализации потребуется - нарисую.

**Comment by maxsite** [comment]
Тогда ставлю как задачу.

**Comment by ekkky** [comment]
Метаполя для рубрик... Не верится... =)))
А долго ждать?

Можно еще одно дефолтное поле добавить, что-то вроде описания рубрики (текст для страницы рубрики, как текст у page). Для этого поля использовать текстовый редактор.

**Comment by vimruler** [comment]
> А долго ждать?

Пока сложно сказать. Есть текущие дела, но и с реализацией мне нельзя затягивать. В любом случае, как сделаю - узнаете :)

**Comment by ekkky** [comment]
Даже лучше идея насчет текстового редактора. Будет хорошо, если возможность использования тестового редактора будет всегда, но скрытая. Например, будет иконка, при нажатии на которую активируется текстовый редактор.

**Comment by ekkky** [comment]
Еще возможность использования тестового редактора можно сделать опциональной. Например, если опция активирована, то появляется иконка (в разделе редактирования рубрик), при клике на которой появляется тестовый редактор.

**Comment by vimruler** [comment]
Начал понемногу продумывать реализацию. Хотел бы показать наброски, чтобы подсказали в правильном ли направлении двигаюсь. Итак, в старом варианте это выглядело так:

![old](https://cloud.githubusercontent.com/assets/2382857/12114490/7eaf5ec2-b3d4-11e5-8934-ce4232c11c5b.png)

Новый вариант предлагаю сделать с использованием табов (вместо размещения кнопки добавления новой рубрики с выезжанием формы). Т.е. чтобы создать новую рубрику нужно будет перейти на таб «Добавить рубрику»

![new](https://cloud.githubusercontent.com/assets/2382857/12114478/6be81964-b3d4-11e5-9ada-c0d87a5dd7a7.png)

Я убрал форму у каждой рубрики, оставив только то, что Макс написал. (Кстати, там вёрстка с использование table - оставить? Если убирать, то стили надо будет править) Понятно, что при нажатии кнопки «Редактировать» будет выезжать форма. Но вот здесь у меня что-то затык. Что должно произойти со стройкой id+title+slug+filter, которые слева от кнопки Редактировать? Да и с самой кнопкой Редактировать? Их все нужно скрыть и отобразить форму редактирования? 

Как должна выглядеть форма редактирования? Так же как и форма создания? Т.е. поля на всю ширину области? Такой вариант?

![form](https://cloud.githubusercontent.com/assets/2382857/12114916/31486c74-b3d8-11e5-9429-cc746e0f0bdb.png)

**Comment by amigoscs** [comment]
А смена родителей перетаскиванием не будет реализована?

И форму редактирования лучше наверно во всплывающем окне типа лайтбокс.

И мое мнение - слишком огромные размеры инпутов и шрифтов и отступов. На небольшом мониторе множество рубрик обрабатывать неудобно жутко. А если еще сохранение с перезагрузкой страницы - получается вообще засада.

**Comment by maxsite** [comment]
Илья, ты делаешь ошибку, что используешь текущий плагин. Нужно делать новый. Естественно без таблицы на обычном ul/li-списке (см. mso_create_list). 

То есть не как ты показал на скриншоте, а полностью исключив все input'ы. Примерно как делается вывод виджета рубрик. По клику на заголовок/название рубрики вниз раскрывается форма, где и будут все поля.

По расположению я думаю, что оптимальным будет так (построчно):

Название  Ссылка
Описание
Родител Порядок
Дополнительные поля (это уже на будущее)
Сохранить

**Comment by vimruler** [comment]
> делаешь ошибку, что используешь текущий плагин. Нужно делать новый.

Совсем новый или имеется в виду, что просто нужно переделать момент с версткой? Собственно, показанные скриншоты были не по поводу внутренностей, а скорее согласовывать внешний вид. Если переделывать верстку совсем, то мне пока не ясно на какой стиль оформления ориентироваться.

> Естественно без таблицы на обычном ul/li-списке (см. mso_create_list)

Да, видел её и планировал использовать.

> По клику на заголовок/название рубрики вниз раскрывается форма, где и будут все поля.

Примерно понятно. Хотел только уточнить - форма в каком месте должна разворачиваться? Прям рядом с нажатым названием или просто в месте около конца/начала списка рубрик?

Получается, что форму редактирования нужно изначально скрыть, а потом через js вставлять по месту использования?

> А смена родителей перетаскиванием не будет реализована?

Изначально я это не планировал делать. Да и высказывания выше вроде не поддерживают эту идею. Однако, можно было бы подумать над вариантом смещения формы редактирования в зависимости от значения поля __родитель__ или __порядок__ - там по сути надо прикрутить реакцию на событие изменения значения и передвигание формы в нужную позицию DOM-дерева. Другой вопрос - а надо ли такое вообще?

**Comment by maxsite** [comment]
Внешний вид можно будет позже дошаманить. Основа ul-список, где каждая рубрика  li-элемент в котором будет и форма. Точнее сама форма здесь не нужна — это скрытый div-блок с полями ввода и кнопкой Сохранить. Кникнули на название рубрики, блоку show(). Второй раз кликнули — скрылась.

**Comment by vimruler** [comment]
> Внешний вид можно будет позже дошаманить.

Хорошо. Тогда этим пока не морочусь.

> Точнее сама форма здесь не нужна — это скрытый div-блок с полями ввода и кнопкой Сохранить.

Я планировал код формы выводить один раз в скрытом блоке, а потом js кодом его выводить в нужном месте. Ты тоже такой вариант имеешь в виду?

**Comment by maxsite** [comment]
Можно и так. Как будет форма делаться всё равно. Хоть одна, хоть в каждом li-элементе. Там объем маленький, не вижу проблем.

**Comment by vimruler** [comment]
Хочу показать скриншот текущих наработок:
![screen-cat2](https://cloud.githubusercontent.com/assets/2382857/12487145/200fd7ca-c090-11e5-82c7-c39c1f2e8f80.png)

1. Список рубрик формируется mso_create_list. Я только немного оформил примерно как в прошлых скриншотах. Без оформления как-то тяжко работать не видя результата.

2. Сейчас показываю только самые первые результаты и кнопки ещё не функционируют. Единственное, что работает - подгрузка формы редактирования рубрики. Подгрузка всего хтмл-кода формы происходит аяксом при нажатии на название рубрики (подчёркнуто dashed - это один из классических вариантов обозначения аякс-кнопок). Повторное нажатие на название приводит к удалению блока с формой и возвращения стиля надписи в исходное (не подсвеченной красным) состояние.

Аякс-подгрузку кода формы целиком решил делать по той причине, чтобы не перегружать логикой работы с DOM js код. Пока вроде критических минусов в таком подходе не вижу.

3. Мета поля пока не делал. Поэтому на скриншоте их ещё нет. Но уже есть идеи и к следующему скриншоту думаю покажу что-нибудь и по этому вопросу.

Из вопросов пока возник такой - правильно ли разместил (может нужно было после списка рубрик) кнопку добавления новой рубрики? При её нажатии будет "выезжать"/появляться пустая форма, а что делать с кнопкой? В общем, мне пока не понятен визуальный сценарий работы при добавлении новой рубрики.

**Comment by maxsite** [comment]
Выглядит неплохо. :-)

По форме. Поля: Ссылка, Родитель и Порядок можно сделать в одну строчку. Они всегда маленькие, нет смысла отдавать по одной строчке.

Кнопку Добавить рубрику, даже не знаю, можно оставить вверху. Возможно это лучший вариант, чем внизу. После добавление новой рубрики должна происходить перезагрузка страницы. Так что после этого форма автоматом спрячется. В любом случае форму добавление сделать по принципу спойлера: один раз нажал, форма появилась, второй — скрылась. А в самой форме уже отдельная submit-кнопка Добавить. 

В чём причина выбора подгрузки формы через аякс? Мне кажется, что обычный show/hide проще, удобней для реализации и не будет лишних запросов к серверу.

**Comment by vimruler** [comment]
> В чём причина выбора подгрузки формы через аякс? Мне кажется, что обычный show/hide проще, удобней для реализации и не будет лишних запросов к серверу.

В том-то и дело, что работа не ограничивается только show/hide - в частности, после сохранения правок если, например, было изменено название рубрики, то нам нужно не просто скрыть форму, но и обновить видимое значение в li. А потом, если вебмастер снова решил подправить - где брать текущее значение, которое поместить в поле для редактирования? Снова делать запрос на сервер или хранить где-то рядом в атрибутах?

Я не говорю, что сделал окончательный выбор, но пока вариант с подгрузкой формы мне видится наиболее логичным и простым в разработке и поддержке вариантом. Во-первых, нет нужды нигде хранить и обновлять значения полей (они каждый раз приходят актуальные с сервера и "разложенные" по полям). Во-вторых, также нет нужды учить js код работать с изменяемым количеством полей (у нас может быть переменной количество полей в форме за счёт мета-полей) формы. 

Единственный момент, который меня пока смущает - некоторое (небольшое) время ожидания, которое происходит после нажатия заголовка до появления формы (пока она загружается). Думаю на всякий случай прикрутить какой-нибудь простенький лоадер на css, чтобы он сообщал о процессе - крутить какую-нибудь awesome-иконку.

>В любом случае форму добавление сделать по принципу спойлера

Так и будет.

**Comment by maxsite** [comment]
Одно дело, когда ожидание при сохранении, а другое, когда при  открытии данных. Это будет довольно неприятно. 

Я понимаю о чём ты говоришь и не вижу особых сложностей в реализации. Твой вариант предполагает обновление всего элемента li при его открытии и при сохранении. Но сформировать исходный li проще и быстрей в момент открытия страницы рубрик. Это даже будет проще чем на аяксе. А дальше show/hide.

Насколько я понял, ты боишься, что будет «расхождение» после аякс-сохранения формы. Я думаю, что после отправки аякса на сохранении, аякс может вернуть не html, вроде «готово», а реальные данные этой же рубрики после mso_new_category() в формате json, который разбирается и на его основе заполняются/обновляются input'ы.

Если именовать input'ы (параметр name) по какому-то единому шаблону, то в принципе ими манипулировать будет несложно. Навскидку: у button (кнопка Сохранить) прописываем value=ID_рубрики. При нажатии (onclick) получаем этот ID. Все input'ы именуем в виде массива, например cat_slug[7], cat_name[7] и т.п. (ID рубрики не меняется, поэтому прописываются один раз в момент загрузки страницы рубрик.) Дальше, получив ID мы получаем нужные данные из соответствующих input'ов и формируем POST-запрос для аякса и отправляем его.

При обратном ответе получаем массив json, которым в обратную заполняем input'ы.

Можно попробовать поиграться с именованием  input'ов, например так: cat[7][slug], cat[7][name]. Тогда можно получить данные по единому ключу cat[7], а сервер пусть сам разбирается какие данные пришли (все равно с ними проверку делать придётся). Но я еще не проверял будет ли работать такой вариант, хотя он мне больше нравится.

**Comment by vimruler** [comment]
> Твой вариант предполагает обновление всего элемента li при его открытии и при сохранении.

Не совсем всего. Если нажали название рубрики чтобы поредактировать, то содержимое li не перегружается, а только лишь вставляется код формы (который приходит по аякс-запросу) в заготовленное блок-место. Если нажали кнопку сохранить, то в ответ аякс вернёт новое содержимое li и тогда действительно произодёт обновление.

>Насколько я понял, ты боишься, что будет «расхождение» после аякс-сохранения формы.

Именно.

Вот какой шаблон содержимого li:
```php
	$format = '
	<div data-id="[ID]">
		<span class="id" title="' . t('ID рубрики') . '">[ID]</span>. 
		<a class="edit" title="' . t('Нажмите, чтобы перейти к редактированию') . '">[TITLE_HTML]</a>
		<span>[ ' . t('ссылка: ') . '<a href="' . getinfo('siteurl') . 'category/[SLUG_HTML]" target="_blank" title="' . t('Смотреть рубрику на сайте') . '">[SLUG_HTML]</a> ]</span>
		<span>[ ' . t('записей: ') . '<a href="' . getinfo('site_admin_url') . 'page/category/[ID]" title="' . t('Список записей') . '" target="_blank">[COUNT]</a> ]</span>
		
		<button type="button" class="delete"><i class="i-trash"></i></button>
	</div>
	<div class="form"></div>
';
```

При таком варианте я всегда имею чёткое место, где брать id рубрики. Больше нигде ничего хранить не нужно и можно со спокойной совестью заменять (только лишь навешивая обработчики событий нажатия двух "кнопок").

При твоём варианте у нас логика шаблона перетекает в js-код, ибо его нужно будет учить (даже цикл пробежаться по массиву с полями) где и что менять. При любой правке шаблона придётся править js-код. В плане дальнейшей поддержки такой вариант не шибко дружественный. Хотя соглашусь, обмен только json данными с сервером всегда выглядит как вроде бы более "технологичный" метод.

Что касается «поиграться с именованием input'ов» - я понимаю о чём ты. Можно конечно. Но вот сейчас занимаюсь добавлением мета-полей (за основу взял изрядно поправленный код работы с meta.ini, но только завёл новый тип ini - cat.ini ) и там для мета полей добавляется дополнительное "измерение" в именах. Т.е. например, имя формируется не на основе значения $options_key, а сложнее - f_new_meta[' . $options_key . '] - это позволяет при сохранении формы отделить значения для мета-полей от значений основных полей. 

Кстати, хранение значений мета-полей будем делать в таблице mso_options? Чтобы потом можно было в любом нужном месте получать. Только надо придумать логику для ключей...

**Comment by maxsite** [comment]
Не вижу смысла сейчас заниматься мате-полями. Там всё сто раз успеет поменяться. Вначале нужно сделать основу.

Твой вариант с аякс-просмотром плох тем, что там будут постоянные задержки. Добавь задержку в 3 секунды в php-обработчик аякса (через sleep) для иммитации реальной работы и попробуй поработать с 10-20 рубриками. Так что здесь вопрос не сколько в коде, сколько в ошибочном алгоритме, который гарантированно будет создавать «тормоза». Тем более, что введя такой аякс ты создал проблему на ровном месте, поскольку при загрузке страницы рубрик данные рубрик уже получены, нужно лишь их вывести списком. Аяксом здесь даже не пахнет. :)

**Comment by vimruler** [comment]
>Твой вариант с аякс-просмотром плох тем, что там будут постоянные задержки.

Согласен. Это меня тоже смущает больше всего. Ладно, тогда буду делать иначе.

> поскольку при загрузке страницы рубрик данные рубрик уже получены, нужно лишь их вывести списком. 

Мне кажется ты так и не понял о чём шла речь. Хотя это уже не важно.

**Comment by vimruler** [comment]
>По форме. Поля: Ссылка, Родитель и Порядок можно сделать в одну строчку. Они всегда маленькие, нет смысла отдавать по одной строчке.

Максим, вопрос по вёрстке возник. Сейчас html-код формы выглядит примерно (вырезал не существенное) так:
```html
<form class="mso-cats">
	<div>
		<p><label><span>Название</span><input name="f_new_name" value="Астрономия" type="text"></label></p>
		<p><label><span>Ссылка</span><input name="f_new_slug" value="astro" type="text"></label></p>
		<p><label><span>Родитель</span><input name="f_new_parent" value="0" type="number"></label></p>
		<p><label><span>Порядок</span><input name="f_new_order" value="0" type="number"></label></p>
		<p><label><span>Описание</span><textarea name="f_new_desc">Астрономические заметки</textarea></label></p>
		<p><button type="submit" name="f_new_submit" class="button i-save">Сохранить</button></p>
	</div>
</form>
```

Как написать css для чтобы выполнить твоё пожелание? Сейчас на поля распространяются только свойства стандартного __form.mso-cats__

**Comment by maxsite** [comment]
Давай так. Ты верстку особо не делай. Пусть будет простой html с UniCSS-классами. Главное сейчас сделать основной функционал. После вышли этот вариант, отладим его и уже после по дизайну подумаем.

**Comment by vimruler** [comment]
> Ты верстку особо не делай.

Хорошо. Там всё равно мне сложно оформление делать ибо сейчас стили в админке понамешаны (или не прописаны для нужных элементов) и ещё не до конца переведены на UniCSS-классы.

**Comment by ekkky** [comment]
Илья, заглохла идея?

**Comment by vimruler** [comment]
> Илья, заглохла идея?

Катя, нет. Времени пока нет. Но надеюсь скоро появится доделать.
