### ISSUE TITLE
После настройки меню слетает header

### ISSUE THREAD

**Issue by sd-design** [maxsite/cms#127]
После настройки меню (при этом никаких изменений не вношу - просто нажимаю сохранить), происходит отключение заголовка страницы вместе с меню. Скриншот во вложении. Только установил на локальной машине - ознакамливаюсь с системой.
![error](https://cloud.githubusercontent.com/assets/7020373/11986236/519e1fe0-a9de-11e5-97bb-38560ed1e034.jpg)

**Comment by vimruler** [comment]
В настройках шаблона на вкладке Компоненты установите хотя бы один компонент (top1 если нужно меню) для шапки.

**Comment by sd-design** [comment]
Спасибо! Только начал осваивать Maxsite
