### ISSUE TITLE
Плагин Tabs — совместимость с jQuery 1.9.x

### ISSUE THREAD

**Issue by wave-maxsite** [maxsite/cms#128]
В строке
`var cookieName = $(this).parents(".tabs_widget").attr("class").match(/tabs_widget_[0-9a-z]+/).join(),`
заменить `attr` на `prop`.

`var cookieName = $(this).parents(".tabs_widget").prop("class").match(/tabs_widget_[0-9a-z]+/).join(),`

http://jquery.com/upgrade-guide/1.9/#attr-versus-prop-

**Comment by maxsite** [comment]
Это будет работать на текущей 1.8?

**Comment by wave-maxsite** [comment]
Да.

**Comment by maxsite** [comment]
Ок.
