### ISSUE TITLE
[pre] и смайлы

### ISSUE THREAD

**Issue by Kmartynov** [maxsite/cms#129]
Столкнулся с тем, что в блоки вставки кода лезут смайлы
Простой пример кода

@[int]::Parse($string)@

вместо :P вставляется рожа, если отключить обработчик то img адрес до этой рожи.
Как забороть?

**Comment by maxsite** [comment]
Зачем, это же и есть рожа?

**Comment by Kmartynov** [comment]
@maxsite шутник.
Этот код обрамление через pre,  рожа должна игнорироваться.

**Comment by maxsite** [comment]
Не представляю себе такую регулярку...

**Comment by Kmartynov** [comment]
А я себе представил :).  Как поделиться с общественностью?

**Comment by maxsite** [comment]
Выложите измененные файлы.

**Comment by Kmartynov** [comment]
Пользоваться Гитхабом не умею :) Тут как-то все сложно. Вот ссылка http://olorg.ru/page/maxsite-cms-obnovil-smiles-plugin

**Comment by maxsite** [comment]
Немного подозрительная регулярка. Я хочу, чтобы вы протестировали новый вариант совместно с другими плагинами, в первую очередь с теми, которые меняют PRE. Это вв-код, shjs (с разными lang) и другими.

**Comment by Kmartynov** [comment]
А почему подозрительно?
В этот плагин входит текст уже после того как его обработал плагин BBCode.
Непонятно на каком основании назначается порядок обхода контента через плагин, подозреваю, что это алфавитный ;).
Как он себя поведет если в [pre] вложить <pre> или [pre] не проверял, но думаю и стандартный bbcode не справится.

**Comment by maxsite** [comment]
У плагинов разный приоритет, поэтому и могут возникнуть разные коллизии. Нужно тестировать со **всеми** плагинами, которые обрабатывают текст и особенно что-то делают с pre.

**Comment by Kmartynov** [comment]
кроме подсветки, bbcode, и псевдокодов еще что использовать?

**Comment by Kmartynov** [comment]
Одинаково себя ведут, не взирая на подозрительную для Вас регулярку.
На ваш горячо-любимый shjs  не влияют.
А вот BBcode косячный, плохо обрабатывает вложенные в pre pre. Тут уже не моя доработка виновата.

**Comment by maxsite** [comment]
Не надо ехидничать. Я вего лишь прошу полноценно протестировать новый код. Нет теста — нет изменений.
