### ISSUE TITLE
Мета-поля для комюзера

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#13]
Предлагаю реализовать возможность использования мета-информации для комюзера. По типу как устроены опции шаблона. Т.е., например, на **/admin/options** сделать вкладку по типу forms, где можно задавать настройки мета-полей комюзера. Второй вариант - в папке **custom** шаблона должен быть файл типа **my-comuser-meta.ini**. Если хотя бы ожин из этих вариантов заполнен админом, то на странице редактирования комюзера после всех обязательных полей будут выводится дополнительные meta-поля. Значения этих полей будут сохраняться в таблице **meta**.

Благодаря таким полям можно будет реализовывать любые мыслимые сочетания полей, котоые могут понадобиться при создании сайта. Например, поле **«Телефон»**. Также, можно было бы реализовать скрытие неиспользуемых полей типа **Jabber** или **ICQ**.

Если идея интересна, то могу взяться за реализацию.

**Comment by maxsite** [comment]
Проще взять type_foreach-файл users-add.php Через него что угодно можно сделать.

**Comment by vimruler** [comment]
Ок. Тогда закрываю.
