### ISSUE TITLE
Сохранить и сохранить в фоне

### ISSUE THREAD

**Issue by Kmartynov** [maxsite/cms#131]
Есть все подозрения, что если нажать кнопку сохранить в фоне не обрабатывается HTML обработчик, в отличие от кнопки сохранить в  самом низу страницы редактирования статьи.
Почему не удается выбрать обработчик "по умолчанию" Если не путаю в прошлых версиях в настройках системы указывался обработчик, но это до того как его вынесли на уровень плагинов.

**Comment by maxsite** [comment]
Ну наверное потому-то не включили плагины обработчиков.

**Comment by Kmartynov** [comment]
Вот как раз включен Default

**Comment by Kmartynov** [comment]
Есть еще вариант что виной может быть наличие всякого уже на текущий момент "хлама" в таблице options.
Из за тестирование в проме плагинов или из-за отказа части функций.

**Comment by maxsite** [comment]
Описывайте проблему полноценно.
