### ISSUE TITLE
Добавить для admin/editor_files исключение: node_modules/

### ISSUE THREAD

**Issue by nicothin** [maxsite/cms#132]
Периодически собираю стили и скрипты прямо в папке шаблона, было бы здорово, чтобы `node_modules/` (там уйма файлов и относительно глубокая вложенность) игнорировалась в разделе редактирования файлов шаблона.

**Comment by maxsite** [comment]
Ничего не понял...

**Comment by vimruler** [comment]
Николай, т.е. нужно чтобы встроенный редактор файлов (пункт меню «Файлы для редактирования шаблона») игнорировал папку node_modules и они не попадали в выпадающий список? Может имеет смысл тогда сделать глобальную опцию, чтобы можно было задавать список папок для игнорирования?

**Comment by nicothin** [comment]
@maxsite для работы с фронтендом сейчас почти все используют nodeJS и таскраннеры. Соответственно, модули-зависимости ставятся в названную мной папку и имеют внутри нее весьма развесистую структуру, которую не хочется видеть в выпадающем списке в разделе редактирования файлов шаблона.
@vimruler да, именно.

**Comment by maxsite** [comment]
Какие предложения по реализации (кроме жесткой прописки в сам плагин)?

**Comment by nicothin** [comment]
Ситуация относительно специфическая, думаю, лучше в сам плагин прописать массив игнорируемых папок/файлов.

**Comment by maxsite** [comment]
И каких?

**Comment by nicothin** [comment]
начать можно с `node_modules` и `.*`

**Comment by maxsite** [comment]
Мне не нравится... Можно попробовать как-то задействовать mso_set_val() в functions.php где и указывать разрешенные расширения файлов и строки-вхождения для исключаемых каталогов. Тогда каждый шаблон можно подстраивать под свою задачу.

**Comment by nicothin** [comment]
Вам решать. Как по мне — подобных переусложнений в движке и без того много )
