### ISSUE TITLE
Идея: плагин «Нравится»

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#133]
После того, как твиттер закрыл кол-во ретвитов, стало тяжело ориентироваться на рейтинг записи. Поэтому предлагаю сделать какой-то свой аналог, где можно будет просто выставить отметку Нравится.

То есть выводится кнопка и рядом кол-во нажавших. Без рейтингов и прочей мутотени.

**Comment by mowshon** [comment]
Было бы весьма удобно.

**Comment by vimruler** [comment]
Можно по-подробнее? Не понял, это что-то типа своих лайков для записей из той же серии что и плагин rater?

**Comment by maxsite** [comment]
Rater немного по-другому, но суть похожая, грубо говоря там будет всего одна звездочка. Если статья понравилась, просто кликаешь, +1 бал в рейтинг.

**Comment by vimruler** [comment]
Теперь понятно. Я нечто подобное внедрил в своём плагине comments (чуть позже опубликую) - тем более в таблицах есть столбцы под такую задачу. А ты где планируешь хранить данные о количестве нажатий? В таблице mso_page?

Единственное, что меня сейчас в твоей идее волнует - чтобы было удобно вставлять в любое нужное место шаблона «кнопку» голосования. Не только на странице записи, но и на страницах рубрик, тэгов, домашней...

Ну и возможность настраивать верстку (например, прикрутить семантическую верстку) и стили оформления - нужна.

**Comment by maxsite** [comment]
У меня пока просто идея. Реализации нет. В теории это простенький jQuery-плагин, который лепится на любой html-элемент. По клику он делает аяск-запрос. Так что оформление — любое.

Хранить результат можно в page-таблице, поскольку там есть поле page_rating. Если же делать для любых страниц сайта, то таблицу лучше сделать отдельной, где ключом будет адрес страницы (mso_current_url).
