### ISSUE TITLE
mso_hook('page-comment-form') и плагин maxsite_auth

### ISSUE THREAD

**Issue by wave-maxsite** [maxsite/cms#134]
В девяностых, если не в восьмидесятых версиях из формы комментирования исчез сабжевый хук.
В плагине maxsite_auth остался код:

```php
mso_hook_add('page-comment-form', 'maxsite_auth_page_comment_form');

# сообщение в форме комментариев
function maxsite_auth_page_comment_form($args = array())
{
	echo '<span><a href="' . getinfo('siteurl') . 'maxsite-auth-form">MaxSiteAuth</a>.</span> ';

	return $args;
}
```

Как правильно цепляться к форме комментариев сейчас? По ошибке убран хук или не обновлён плагин?

P.s. Увидел хуки comments_content_start и comments_content_end.

**Comment by maxsite** [comment]
Этот хук теперь вроде бы login_form_auth. Поправить нужно в плагине, насколько я понимаю. Проверишь?

**Comment by wave-maxsite** [comment]
login_form_auth — это хук для формы логина. Т.е. то, что выводишь там, появляется в виджете login_form и на странице /login. А то, что выводилось по хуку page-comment-form, появлялось в форме комментирования. В maxsite_auth на оба хука функции навешаны.

Похоже, просто, что page-comment-form разнесён на comments_content_start и comments_content_end.

**Comment by maxsite** [comment]
Немного запутался... А как раньше хук page-comment-form выводился? Вернуть его не проблема, но я не понимаю где он должен быть.

**Comment by wave-maxsite** [comment]
\type\page\units\page-comment-form-tmpl.php в версии 0.94
```php
				<!-- простая форма -->
				{%  if (mso_get_option('form_comment_easy', 'general', '0')) : %}
					<div class="mso-comments-auth">

						{% if (mso_get_option('allow_comment_anonim', 'general', '1') ) : %}
						
							<input type="hidden" name="comments_reg" id="comments_reg_1" value="noreg">
							
							<p><input type="text" name="comments_author" placeholder="{{ tf('Ваше имя') }}" class="mso-comments-input-author"></p>
								
							<p><i>{{ $to_moderate }}</i></p>
						
						{% endif %}
						
						{% if (mso_get_option('allow_comment_comusers', 'general', '1')) : %}
							<p>{{ $to_login }}</p>
						{% endif %}
						
					</div> <!-- class="mso-comments-auth"-->
				{% endif %}	<!-- / простая форма-->
			
			
			{% endif %} <!-- / нет залогирования -->

			{% mso_hook('comments_content_end') %}
```

\type\page-comment-form.php в версии 0.82
```php
				<?php } // else form_comment_easy ?>
				 
				<?php 
					if (mso_hook_present('page-comment-form')) 
					{
						echo '<p class="hint comments_auth"><span class="ffirst">' . tf('Авторизация') . '&nbsp;</span>';
						mso_hook('page-comment-form');
						echo '</p>';
					}
				?>
			
			</div> <!-- class="comments-auth"-->
			
			<?php  } // залогирование ?>

			<?php mso_hook('comments_content_end') ?>
```

А на этот хук вешаются плагины ulogin_auth, fbauth и пара-тройка подобных. Соответственно, для новых версий их надо переписывать на хук `comments_content_end` или возвращать хук `page-comment-form`. Я просто не знаю, в чём была идея. Мне понадобилось добавить пару кнопок в форму комментирования, полез смотреть, как это делается в аналогичных плагинах и увидел эту проблемку.

**Comment by maxsite** [comment]
Ну давай вернем хук. Только я всё-равно не улавливаю куда его нужно прописать.

**Comment by wave-maxsite** [comment]
\application\maxsite\shared\type\page\units\page-comment-form-tmpl.php
после `{% endif %}	<!-- / простая форма-->` (это строка 123).
Вроде бы так.
Собственно, получается, разница между `page-comment-form` и `comments_content_end` в том, что первый только для незалогиненных.

**Comment by maxsite** [comment]
Давайт так. Ты внеси правку, погоняй с этими плагинами и своей задачей и вышли мне готовый файл. Так будет намного быстрей.

**Comment by wave-maxsite** [comment]
[Uploading page-comment-form-tmpl.zip…]()
Работает как раньше — под формой комментирования, если не залогинен юзер-комьюзер, выводит что там от плагина надо — кнопки логина, ссылку на логин и т.п..
