### ISSUE TITLE
Не срабатывает проверка капчи в MaxSite CMS 0.93

### ISSUE THREAD

**Issue by lider33** [maxsite/cms#137]
Заметил, что не срабатывает проверка _капчи_ в версии **MaxSite CMS 0.93** и выше. 
Настройки плагина контактной формы - **forms** стандартные.
При вводе неверного значения _капчи_ сообщение отправляется без предупреждения.

Объясните пожалуйста странное поведение контактной формы.

**Comment by vimruler** [comment]
Подтверждаю. На 0.94 тот же самое. Поправлю только, что имеется ввиду «капча» самого плагина forms.

**Comment by maxsite** [comment]
Исправлю.
