### ISSUE TITLE
Сайдбар админки - «в пол»

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#138]
Юра уже поднимал эту тему [здесь](https://github.com/maxsite/cms/issues/85#issuecomment-135497789). Но т.к. решения до сих пор нет, то снова поднимаю вопрос - как сделать так, чтобы сайдбар в админ панели на больших мониторах всегда доставал до пола? А то выглядит странно на мой вкус.

![- _-_ _-_dev_-_2016-01-31_10 49 31](https://cloud.githubusercontent.com/assets/2382857/12700357/f9841640-c808-11e5-810a-3cf900a5c872.png)

Сейчас у меня появился вариант решения:

```css
.my-nav-panel { min-height: 100vh; }
```

У меня в тестах вроде работает (сайдбар встаёт на «пол»), но может я что-то упускаю?

**Comment by maxsite** [comment]
На малых экранах все развалится.

**Comment by vimruler** [comment]
> На малых экранах все развалится.

Проверил на низких разрешениях (меньше 1000px). У тебя же в там сделаны @media так, что дизайн меняется совсем (сайдбар превращается в панельку) и ничего не разваливается. Попробуй потестить. Я просто добавил файл css-профиля с этим кодом чтобы посмотреть.

Или что ты имеешь в виду под малыми экранами?

**Comment by maxsite** [comment]
Я не проверял. Но такие вещи я хочу на 200% чтобы прошли полное тестирование.

**Comment by vimruler** [comment]
> Но такие вещи я хочу на 200% чтобы прошли полное тестирование.

Понимаю. Хорошо, подождём, может ещё кто-нибудь даст отклик о результатах тестирования.

**Comment by cuprum** [comment]
Посмотрел решение Ильи, в последних Хроме и Лисе все ок. В IE 11 тоже.

**Comment by maxsite** [comment]
Ок. Добавлю.

**Comment by v0ff4k** [comment]
как насчет сделать меню как на ссылке ? https://codyhouse.co/gem/responsive-sidebar-navigation/
Отзывчивый дизайн, и меню "в пол". зачем придумывать велосипед, когда есть неплохое решение!
