### ISSUE TITLE
Устаревшее значение настроек шаблона

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#139]
После установки системы первым блоком шапки дефолтного шаблона идет компонент **top1**. Но в настройках шаблона на вкладке **Компоненты** он не подставляется

**Comment by maxsite** [comment]
И не должен. Он же не выбран.

**Comment by cuprum** [comment]
Но ведь при установке он появляется на сайте. Значит выбран. Меня просто смущает, что после установки, если сохранить настройки шаблона, ничего в них не меняя, top1 исчезает.

**Comment by maxsite** [comment]
Он прописан как дефолтное значение опции, которая еще не сохранена, а значит не определена.
