### ISSUE TITLE
Требуется обновить Font Awesome с 3.2.0 до 4.1.0

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#14]
В составе шрифта появились новые полезные иконки. Подробности - https://github.com/FortAwesome/Font-Awesome/releases

**Comment by maxsite** [comment]
Чтобы обновить шрифт потребуется изменить less-файл. У меня есть изменения, но там завязка на стили, поэтому шрифт будет обновлен комплексно со стилями.

**Comment by vimruler** [comment]
Это понятно. Главное, чтобы в движке стали доступны новые иконки из шрифта.

**Comment by maxsite** [comment]
Я бы советовал в шаблонах использовать свою версию шрифта. Это в рамках концепции D3 более правильный подход. Просто у нас это «хвост» образовался из-за админки и default-шаблона.

**Comment by vimruler** [comment]
Когда речь идёт о своём шаблоне - там да, желательно использовать свою вресию. Я создавал issue как раз по причине того, что мне не хватило стандартных иконок в админ-панели. Я их активно использую при разработке плагинов.
