### ISSUE TITLE
Обработчик HTML

### ISSUE THREAD

**Issue by leonovmax** [maxsite/cms#141]
При создании новой записи, если в тексте записи  есть тег `<br>`. 
Пример:
Создаем новую запись, в ней текст:

тут какой-то текст...
```
[pre lang=php]
<?
echo "test <br>";
echo "test2";
[/pre]
```

В итоге,  в опубликованной новости не печатается `<br>`, а обрабатывается .
Скрин создания записи - 
![addnewpost](https://cloud.githubusercontent.com/assets/11669994/12818531/f938ab10-cb5f-11e5-9368-d4a605cf9c22.png)

Скрин результата опубликованной записи - 
![result](https://cloud.githubusercontent.com/assets/11669994/12818532/f93abd88-cb5f-11e5-89f6-8f19fe136f76.png)

**Comment by maxsite** [comment]
Вот так:
&lt;br>
