### ISSUE TITLE
ошибка при попытке использования плагина less_compiling на 0.94

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#142]
Обновил сайт, используя универсальный способ, до 0.94. Скопировал default шаблон, выставил права для записи assets/css, включил less_compiling, в опциях задал правила, выставил галочки "Включить less-компиляцию" и "Выполнять компиляцию только для авторов и админов". При переходе на сайт получаю 

 lessphp fatal error: .border_loop is undefined: line: 22
```
 
 1.    /* .UniCSS -> http://unicss.maxsite.com.ua/ */
 2.    
 3.    // mixins
 4.    @import 'unicss/mixins/less-framework-lite.less';
 5.    @import 'unicss/mixins/colors-gmd.less';
 6.    
 7.    // less-variables
 8.    @import 'main/variables.less';
 9. 
 10.    // UniCSS
 11.    @import 'unicss/unicss.less';
 12.
 13.    // main
 14.    @import 'main/extension-unicss.less';
 15.    @import 'main/base.less';
 16.    @import 'main/forms.less';
 17.    @import 'main/fontawesome.less';
 18.    @import 'main/my-template.less';
 19.    @import 'main/print.less';
 20. 
 21.    @import 'component/menu.less';
 22.

```
при этом никаких правок в less-файлах не делалось... видимо, в комплекте идет скомпилированный css и модифицированный и не отлаженный less. Можно что-то подправить? Или глюк в самом плагине? Пробежался по всем less-файлам - ни в одном не нашел ссылку на border_loop в 22-й строке

**Comment by maxsite** [comment]
Этот плагин не поддерживает все возможности LESS. Используйте стандартный less-компилятор.

**Comment by Den2016** [comment]
грустно. Придется обвес плодить на всех компах, с которых работаю...
