### ISSUE TITLE
xss codeigniter 2.1.4 !!!

### ISSUE THREAD

**Issue by v0ff4k** [maxsite/cms#143]
https://github.com/bcit-ci/CodeIgniter/issues/2965

может пора обновить кодигнайтр до версии 3.0 ?

**Comment by maxsite** [comment]
У нас 2.2.6. При чём тут 2.1.4?

**Comment by v0ff4k** [comment]
от версии 2.1.4, 2.2.6 также уязвима !
Лечение пришло в весии 3.0(или может там просто еще пока ненашли.)

**Comment by maxsite** [comment]
Перехода на CodeIgniter 3 не будет. Будет исправление в текущей версии, сделаем обновление. Найдете применение этой уязвимости в рамках MaxSite CMS, тогда и будем исправлять локально.

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by v0ff4k** [comment]
да, впринцепе локально можно не обновлять, необходимо просматривать изменения:

функция public function xss_clean
в ветке  CodeIgniter/system/core/Security.php

**Comment by maxsite** [comment]
Я не уверен, что данная проблема может быть воспроизведена в MaxSite CMS. Нужно найти её в рамках MaxSite CMS и тогда исправлять. Заниматься исправлением CodeIgniter я не буду.

**Comment by Furnicarium** [comment]
тоже интересует. Хотел задать вопрос о переходе на новые версии фреймворка (не знаю, зачем, просто кажется, что новое оно лучше и быстрее) или даже более радикально - возможен ли переезд на какой-нибудь более хороший фреймворк, даже если его пока ещё нет, а как вариант на будущее.
Объясню, почему. я нахожусь в поиске инструмента для создания сайта, читаю разные рейтинги и обзоры и в сторону Кодигнайтера вижу только насмешки о том, что он устарел, а МаксЦМС написана грязным кодом, особенно на хабре. Я-то на практике знаю, что это офигенно удобная, понятная и быстрая ЦМС, но вот таких новичков как я много и они читают комменты и всё, что на кодигнайтере даже не рассматривают как варианты. на тостере новички спрашивают на чём сделать сайт, им отвечают только про всякую откровенно **парашу** типа модикс и джумлы.  К примеру, есть фреймворки, на которых не существует таких же удобных и быстрых движков, может, стоит выбрать современный быстрый фреймворк и перенести туда движок. Никаких модных юи2 и симфони. то, что их много в поиске ищут, это ещё не значит, что они популярны. это значит, что они нифига не понятны и тупы, вот поэтому люди и лезут в поиск. хочется прорекламировать fat free, но сам не уверен в том, что это именно оно. просто по бенчмаркам он быстрее остальный, но одновременно он как серая мышка, недостаточно популярен, так же незаслуженно, как и MaxCMS. если лишнего написал, можешь удалить коммент или отредактировать, я никому не хочу рекламу делать, хотел просто вопрос задать и получить ответ.

**Comment by vimruler** [comment]
> возможен ли переезд на какой-нибудь более хороший фреймворк, даже если его пока ещё нет, а как вариант на будущее.

Максим уже когда-то отвечал на подобный вопрос. Ответ звучал примерно так: он заниматься этим не будет точно, т.к. сам переезд на другой фреймворк равносилен разработке нового движка.

Лично я иногда примерял мысленно на себя роль создателя движка на другом фреймворке и тут же забывал про эту "идею", т.к. понимаю, что нужны тысячи часов программинга, чтобы хотя бы воссоздать уже имеющийся сейчас в MaxSite CMS функционал. Эту работу никто оплачивать не будет. Сама по себе она тоже не шибко интересна, так что увы. Думаю, что большинство коллег размышляет примерно так же. Максим занимается своим движком от того, что думает, что так он себя как фрилансера раскручивает. Других таких идейных, кому нужна такая раскрутка, я пока особо не видел.

> на тостере новички спрашивают на чём сделать сайт, им отвечают только про всякую откровенно парашу типа модикс и джумлы.

Я даже больше скажу, когда я стал рекомендовать там MaxSite CMS, то нашлись неадекваты, которым мешали мои рекомендации, хотя по сути претензий к движку они выдвинуть так и не смогли. Но смогли добиться того, чтобы меня там забанили. Так что пусть теперь сами набивают шишки на своих супер-пупер "движках". Понимающие люди сами всё найдут и разберутся.

Про претензии к CodeIgniter недавно [писал тут](http://maxhub.ru/page/davajte-pogovorim-o-principah-dvizhka-i-soobshhestva-maxsite-cms#comment-2290).

**Comment by maxsite** [comment]
CodeIgniter 3 был сделан в угоду нового хозяина, которому нужно было показать, что работа идёт. Это было ошибочное направление в развитии фреймворка. И те кто перешёл на него, сделали болшую глупость. Сейчас запущена разработка CodeIgniter 4, который потреряет совместимость с предыдущими версиями, включая и 3-ку. Новая версия, как я надеюсь, будет идеологически уже более «правильной», что позволит в будущем рассмотривать вопрос её использования в MaxSite CMS. Однако, пока на текущий момент для CodeIgniter 4 объявлена минимальная версия PHP 7, что опять закрывает вопрос его использования.

Если же рассматривать CodeIgniter с точки зрения функционала и удобства, то ему до сих пор нет равных. Единственный минус — это не полная поддержка новых версий PHP, вроде 5.5 и выше. С другой стороны это сильно расширяет границы его использования на серверах со старыми версиями. Например 5.3 очень часто используется.

Так что вопрост обновления CodeIgniter в MaxSite CMS на текущий момент просто не актуален.

**Comment by Den2016** [comment]
Вот! Вот именно на 5.5 я и огреб проблему с почтой! Макс, ты до сих пор будешь утверждать, что это проблема только моего сервера?

**Comment by maxsite** [comment]
Именно так. Больше ни у кого проблем не было. Проверяй работу почты на других серверах, тогда и будет разговор.
