### ISSUE TITLE
Сайдбар в админке всегда виден

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#144]
Идея проста. Сейчас при прокрутке сайдбар в админке прокручивается вместе со всем остальным.
А что если сделать так, чтобы он всегда был на виду?
Вот, набросал предварительно [так](https://jsfiddle.net/Cuprum/t6mcnbzq/).
Правда, там есть нюансы, которые надо учесть т.к. верстка поменяется. Но пока не о них.
Я думаю, что так будет удобнее.
Ваше мнение, товарищи?

**Comment by vimruler** [comment]
Так то да, такой вариант может быть удобнее. Правда есть привычка проматывать всю страницу и привычку придётся ломать, это сложно пока :)

**Comment by v0ff4k** [comment]
нужно делать плавающее меню, при наведении на которое,  оно будет разворачиватся.
+ обязательно сделать с вертикальной перемоткой(overflow: auto;), в случае если объектов меню будет много.

атак, идея очень хорошая ! буду ждать результата.

**Comment by maxsite** [comment]
Наверное, пока не пощупаем, не получится точно сказать. Можно это сделать в виде отдельного css-профиля для админки?

**Comment by cuprum** [comment]
@vimruler 

> Так то да, такой вариант может быть удобнее. Правда есть привычка проматывать всю страницу и привычку придётся ломать, это сложно пока :)

Ты о том, когда в сайдбаре много пунктов и они не помещаются в один экран по высоте? По-моему это происходит не очень часто. При первоначальной установке системы все пункты помещаются, еще и место остается. По крайней мере на fullHD-мониторе. Допускаю, что на ноутах места не хватает. Как вариант - показывать полосу прокрутки в таком случае постоянно, а не по наведению (как в примере по ссылке).

@v0ff4k 

> нужно делать плавающее меню, при наведении на которое, оно будет разворачиватся.

Вы ссылку из первого сообщения смотрели? Объясните про плавающее меню.

@maxsite 

>  Можно это сделать в виде отдельного css-профиля для админки?

Не уверен, что можно отделаться дополнительным CSS... Скорее всего придется немного поменять верстку. Я могу в своем форке завести отдельную ветку под это дело и в ней сделать нужные изменения.

**Comment by maxsite** [comment]
Если можно измениьт верстку, чтобы не сломать текущий вариант и вынести новый в css-профиль, то делай. Нужно посмотреть, там уже решим, стоит ли делать для всех.

**Comment by cuprum** [comment]
Итак, верстка остается прежней. Ниже файл профиля для админки. Простой пример, чтобы наглядно показать; Если сайдбар не помещается в экран, то появляется полоса прокрутки. Смотреть лучше на fullHD, на других могут быть косяки. Если делать такую штутку для паблика, надо еще допиливать.
[sidebar-visible.zip](https://github.com/maxsite/cms/files/133162/sidebar-visible.zip)

**Comment by maxsite** [comment]
Непривычно, конечно, постоянный второй скроллбар.
