### ISSUE TITLE
Горизонтальное меню 4-уровневой вложенности в дефолтном шаблоне

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#145]
Перестают выпадать пункты горизонтального меню, если имеем 4 уровня вложенности.

Обсуждал проблему с Ильёй на МаксХабе: http://maxhub.ru/page/oshibki-v-otobrazhenii-gorizontalnogo-menju-4-urovnevoj-vlozhennosti#comments

Там же было предложено решение:
Нужно найти файл \application\maxsite\templates\default\assets\js\lazy\my.js и заменить код:
`.mouseenter(function()
{
 // $(this).children('ul').first().hide().stop().fadeIn(400);
 $(this).children('ul').first().hide().stop().slideDown(200);
})
  
.mouseleave(function()
{
 // $(this).children('ul').first().stop(0).fadeOut(400);
 $(this).children('ul').first().stop(0).slideUp(200);
});`

на код:

`.mouseenter(function()
{
 // $(this).children('ul').first().hide().stop().fadeIn(400);
 $(this).children('ul').first().show();
})
  
.mouseleave(function()
{
 // $(this).children('ul').first().stop(0).fadeOut(400);
 $(this).children('ul').first().hide();
});`

Проблема решается, правда исчезает анимация. Вот сейчас вышла новая версия, где все то же самое повторилось. Сигнализирую о проблеме.

**Comment by maxsite** [comment]
Если речь об анимации, то её давно пора переписать на css.
