### ISSUE TITLE
Shortcode — новая возможность

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#146]
По своей сути shortcode — это привычный bb-код. Смысл затеи в том, чтобы разрешить на уровне шаблона создавать свои варианты. Приведу простой пример.

Шорткод, который обрамляет текст в SPAN с заданным классом.

``
[class t-red bold]text page[/class]
``

В файле шаблона **custom/my-template.php**

```php
mso_shortcode_add('class', 'my_class');

function my_class($attr)
{
	return  '<span class="' . $attr[1] . '">'. $attr[2] . '</span>';
}
```

То есть вначале задается сам шорткод и его функция. Функция принимает один входящий параметр, где `$attr[1]` — это параметры шорткода, а `$attr[2] ` — текст внутри. Всё возвращается по return.

Таким образом можно формировать любой шорткод на уровне шаблона или плагина. Обработка полностью ложится на функцию шорткода. 

Также есть функция `mso_shortcode_parse` для распарсивания шорткодов вида 

`[shortcode par=val par1=val1]text page[/shortcode]`.

На выходе будет массив

```
 Array:
 		[par] => val
 		[par1] => val1
		[content] => text page
```

Элемент **content** добавляется автоматом, как синоним `$attr[2] `.

**Comment by vimruler** [comment]
Это что-то подобное шорткодам WP? Занятная возможность!

**Comment by maxsite** [comment]
Да, что-то вроде того.

**Comment by maxsite** [comment]
Сделал шорткод для слайдера. В тексте можно так:
```
[html][lightslider 1]
[js]
item: 2,
auto: true,
loop: true,
speed: 400,
[/js]

[slide]
<h3 class="bg-blue pad20 t-center">1</h3>
[/slide]

[slide]
<h3 class="bg-yellow pad20 t-center">2</h3>
[/slide]

[slide]
<h3 class="bg-red t-white pad20 t-center">3</h3>
[/slide]

[slide]
<h3 class="bg-gray800 t-white pad20 t-center">4</h3>
[/slide]
[/lightslider][/html]	
```
