### ISSUE TITLE
Ошибка Disallowed Key Characters

### ISSUE THREAD

**Issue by 8091** [maxsite/cms#148]
Добрый день! Disallowed Key Characters вот такая ошибка в Мозилле, версия 0,94, домен находится в зоне .РФ думаю из-за этого проблема, хотя когда делал установку проблем не было.
первый раз помогло почистить кэш
второй раз не срабатывает

перешел на Хром, но это не выход

в инете есть похожие темы, не помогло добавление А-Я в файл core/input.php 
function _clean_input_keys($str)
    {
        if ( ! preg_match("/^[А-Яа-яa-z 0-9:_\/-]+$/i", $str))
        {
            exit('Disallowed Key Characters.');
        }

```
    // Clean UTF-8 if supported
    if (UTF8_ENABLED === TRUE)
    {
        $str = $this->uni->clean_string($str);
    }

    return $str;
}
```

**Comment by maxsite** [comment]
Как вариант, попробуйте явно указать адрес сайта в стандартном варианте в конфигурации $config['base_url'].

**Comment by 8091** [comment]
Не прокатило(

**Comment by maxsite** [comment]
Тады, ой.

**Comment by 8091** [comment]
Все разобрался, у мозиллы нужно всю историю удалять Настройки -> Приватность -> удалить вашу недавнюю историю

**Comment by amigoscs** [comment]
Есть такая проблема с кириллическими доменами. Disallowed Key Characters возникает тогда, когда в cookies прописывается кириллица. CI начинает ругаться.

У меня такая беда была в админ-панели. Лечил плагин Showhide (<code>maxsite/common/jquery/jquery.showhide.js</code>).
Правил строку 
<code>cookieName : ( window.location.host + window.location.pathname ).replace( /\//g, '-' )</code>
на
<code>cookieName : ( window.location.pathname ).replace( /\//g, '-' )</code>

В свою очередь хотелось бы попросить автора MaxSite обратить внимание на проблему с кириллическими доменами (Disallowed Key Characters) и по возможности в новых версиях внести правки.
