### ISSUE TITLE
Достать slug для каждой рубрики в юнитах

### ISSUE THREAD

**Issue by SWAT727** [maxsite/cms#150]
Недавно столкнулся  с проблемой, как через юнит-файлы достать ссылку рубрики. Задача в вёрстке - на странице вывода записей к каждой рубрике выводить уникальную иконку.

Делаю вывод на `type/home/units/` с помощью юнита `last_pages.php`

Если через плагин вывода рубрик это решается легко и просто:
`<span class="icon-[SLUG]"></span>`

то такого функционала там по ходу нету (если есть просвятите плиз).

Предлагаю добавить что то навроде `[cat_slug]`

**Comment by maxsite** [comment]
Если рубрик несколько? Попробуй использовать [val@XXX]

**Comment by SWAT727** [comment]
А доки есть какие по этой штуковине?
