### ISSUE TITLE
Проблема check-latest на HTTPS сайтах

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#151]
Есть сайт, который переведён на HTTPS и недавно обратил внимание, что блок информации про обновление движка "не работает". Отображается сообщение об ошибке.

В Firefox это выглядит так:

![https1](https://cloud.githubusercontent.com/assets/2382857/15098016/6ff238ee-1551-11e6-86cf-0114b0cea488.png)

В Chrome примерно также:

![https2](https://cloud.githubusercontent.com/assets/2382857/15098022/9ba67fcc-1551-11e6-91f4-0aa357c03c14.png)

Поглядел /application/maxsite/admin/plugins/admin_home/admin.php - там iframe дёргает адрес //max-3000.com/check-latest - вроде всё нормально. Но браузеры воспринимают такое обращение как попытку загрузить смешанное содержимое и не пропускают.

Я так понимаю есть два варианта преодолеть это:

1. Перевести сайт max-3000.com на HTTPS
2. Переделать загрузку на CURL

**Comment by vimruler** [comment]
Второй вариант перегнул конечно. Можно просто **file_get_contents** использовать...

**Comment by maxsite** [comment]
А если явно прописать http?

**Comment by vimruler** [comment]
Т.е. в /application/maxsite/admin/plugins/admin_home/admin.php вместо
```php
<iframe src="//max-3000.com/check-latest?<?= getinfo('version') ?>" scrolling="auto" frameborder="no" style="width: 100%; min-height: 100px; margin-top: 20px;"></iframe>
```

поставить что-то типа:
```php
<div style="width: 100%; min-height: 100px; margin-top: 20px; overflow-y:auto;"><?= file_get_contents("http://max-3000.com/check-latest?".getinfo('version')); ?></div>
```

Пока единственный видимый минус такого варианта - необходимость жестко задавать протокол http для адреса проверки.

**Comment by vimruler** [comment]
> А если явно прописать http?

Вообще ничего не загружает и явной ошибки не показывает. Только в консоле видно сообщение об блокировке:

![https3](https://cloud.githubusercontent.com/assets/2382857/15098085/92163ac6-1554-11e6-8479-d918c2b88220.png)

**Comment by vimruler** [comment]
> Пока единственный видимый минус такого варианта

Есть "невидимый" минус - может потребоваться дополнительная настройка php. Как минимум:

> allow_url_fopen = On

Поэтому код превращается в нечто такое:
```php
$checkurl = "http://max-3000.com/check-latest?".getinfo('version');
if (function_exists('curl_version'))
{
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $checkurl);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    $content = curl_exec($curl);
    curl_close($curl);
}
else if (file_get_contents(__FILE__) && ini_get('allow_url_fopen'))
{
    $content = file_get_contents($checkurl);
}
else
{
    $content = "";
}
echo '<div style="width: 100%; min-height: 100px; margin-top: 20px; overflow-y:auto;">'.$content.'</div>';
```

**Comment by vimruler** [comment]
Но я буду рад, если найдётся более простой вариант :)

**Comment by maxsite** [comment]
Тогда не знаю. Переводить сайт на https пока не собираюсь. Iframe тем и хорош, то я сам решаю что там делать, включая скрипты, стили и т.п. Получение контента уже было, возвращаться не будем.

**Comment by vimruler** [comment]
> Получение контента уже было, возвращаться не будем.

Вот-вот. Не хотелось бы.

**Comment by vimruler** [comment]
А нельзя размещать содержимое iframe где-нибудь на https-сайте и при обращении на стандартный текущий адрес редиректить туда?

**Comment by maxsite** [comment]
Где именно? У меня https-сайто просто нет...

**Comment by vimruler** [comment]
>Где именно?
Так то идей особо нет. Может на Github можно как-нибудь "пристроить"?

**Comment by vimruler** [comment]
Есть ещё вариант: Сделать поддомен на max-3000.com с самоподписанным сертификатом. Можно хотя бы попробовать...

**Comment by maxsite** [comment]
Не знаю, я с таким вещами особо не разбирался.

**Comment by v0ff4k** [comment]
запускаете прокси на своем сервере и подтягиваете хттп содержимое. только аккуратно !
решение на хабре habrahabr.ru/company/mailru/blog/210050/
