### ISSUE TITLE
Временами выпадающее меню прячется под основной контент

### ISSUE THREAD

**Issue by Demyanych** [maxsite/cms#153]
Есть рабочий сайт lada-moscow.com на MaxSite CMS: 0.93 с глюком в выпадающем меню. 
Временами, выпадающее меню при наведении курсора на него, выпадает и прячется как бы под  контент. На виду только один раздел подменю. Шаблон дефолтный.
Подскажите пожалуйста, как с этим бороться?

**Comment by maxsite** [comment]
Первым делом добейтесь валидного html-кода. Ctrl+U в браузере. Только после этого можно рассматривать проблему.

**Comment by Demyanych** [comment]
Подскажите пожалуйста, где там нет валидности. Как по мне, так все вроде бы с html-кодом нормально. Честно, не вижу

**Comment by v0ff4k** [comment]
выделил жырным то, что первым нашел файерфокс(в основном потерянное открытие тегов):

косяки небольшие есть, но они невлият!!!
------------------------------
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
**</div>**<div
------------------


</p>**</div></center>**	</div>

</div></div>

влияет скриптовый код (lada-moscow.com/application/maxsite/templates/default/assets/js/lazy/my.js) а именно : 

```
$(function(){
	// анимация меню
	$('div.MainMenu li.group')	
		.mouseenter(function()
		{
			// $(this).children('ul').first().hide().stop().fadeIn(400);
			$(this).children('ul').first().hide().stop().slideDown(200);
		})
		
		.mouseleave(function()
		{
			// $(this).children('ul').first().stop(0).fadeOut(400);
			$(this).children('ul').first().stop(0).slideUp(200);
		});
```

они немогут оприделить реальную высоту и с каждым разом все меньше и меньше показывают высоту, пока совсем мелкую не покажут !
попробуйте другой эффект, вместо **slideDown**  использовать **show** и вместо **slideUp** **hide**.  либо любую простую меню:

но я бы посоветовал использовать  css3.
 cssdeck.com/labs/pure-css3-smooth-drop-down-menu
(еще примеры cssmenumaker.com/blog/10-free-html-drop-down-menu-navigations)
готовое на кодепен codepen.io/philhoyt/pen/ujHzd

либо комбинирование (разница в скрипте !)
callmenick.com/post/slide-down-menu-with-jquery-and-css

**Comment by Demyanych** [comment]
Спасибо v0ff4k, за дельные подсказки!
