### ISSUE TITLE
Не публикуются новые записи на сайте.

### ISSUE THREAD

**Issue by erak31** [maxsite/cms#154]
Новая созданная запись, не публикуется на сайте. В админке появляется. Так же с рубриками, не отображаются новые рубрики.
На скрине видно, что создана запись в категории "Рубрика: Настройка Windows", но кликнув на эту категорию, получаем 404.

PHP Version 5.6.22
![git1](https://cloud.githubusercontent.com/assets/20263542/16544049/c4f9353a-4117-11e6-996b-11ebde2c315e.JPG)
![git2](https://cloud.githubusercontent.com/assets/20263542/16544050/c4fe8396-4117-11e6-9c38-1261c167aa79.JPG)

**Comment by maxsite** [comment]
Значит запись не опубликована.

**Comment by erak31** [comment]
)))) логичный ответ.
Запись публикуется позже, как оказалось. Спустя пару часов, хотя коррекция времени правильная.
