### ISSUE TITLE
Проблема с auto_post

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#155]
Здравствуйте. Установил 0.94, попробовал загрузить файл по шаблону:
title: Заметки
CAT: Новости
SLUG: zametki
TYPE: blog
STATUS: publish

META-TITLE: Заметок много
META-DESCRIPTION: Тестовая запись
META-KEYWORDS: Тест, запись
META-PARSER_CONTENT: default

<p>---</p>

< h1>Тест</h1 >
< h2>Запись №1</h2 >
< p>Поехали!</p >

Но запись не появилась, а на самой странице показан такой текст:

1.txt
upload 1.txt
1.txt:
title: Заметки
CAT: Новости
SLUG: zametki
TYPE: blog
STATUS: publish

META-TITLE: Заметок много
META-DESCRIPTION: Тестовая запись
META-KEYWORDS: Тест, запись
META-PARSER_CONTENT: default

<p>---</p>

< h1>Тест</h1 >
< h2>Запись №1</h2 >
< p>Поехали!</p >
File information: 1.txt type: text/plain size: 325 bytes

Поскольку сайт установлен на локалке, речи о не тех правах быть не может. Система чистая - ничего своего не вносил. Буду благодарен за исправление.
P. S. Прикладываю скриншот страницы.
![scrin-auto-post](https://cloud.githubusercontent.com/assets/13224778/16571285/bb8dea54-427a-11e6-8b77-6537b164d1c9.png)

**Comment by maxsite** [comment]
* Все опции регистрозависимы и строятся по схеме КЛЮЧ:ЗНАЧЕНИЕ. Каждый элемент в отдельной строке. 

* Обязательным является только заголовок записи (TITLE). Если заголовка нет, то файл игнорируется.

**Comment by denis-skripnik** [comment]
Разве я что-то неправильно ввёл? Вроде всё согласно шаблону.

**Comment by denis-skripnik** [comment]
Разве я что-то неправильно ввёл? Вроде всё согласно шаблону.

**Comment by maxsite** [comment]
Регистр TITLE неверный.

**Comment by denis-skripnik** [comment]
Благодарю. Всё получилось.
