### ISSUE TITLE
Элемент .mso-clearfix без css

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#156]
В дефолтном шаблоне, на странице записи, внизу есть такой участок
```
<aside>
<div class="mso-clearfix"></div>
...
```
Раньше у него было класс .clearfix. Сейчас класс сменился и никакой CSS к нему не цепляется.
Может вернуть старое название? Функционал, как понимаю у него должен быть прежним.

**Comment by maxsite** [comment]
Так и задумано. Класс .clearfix может конфликтовать с другими фреймворками или кастомными стилями.
