### ISSUE TITLE
Копирование/клонирование записей

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#157]
Статьи само собой копировать смысла нет обычно. Но вот если в теле записи коды лендинга или ещё какие-нибудь плюшки, то бывает полезно иметь кнопку для клонирования. Ну или хотя бы для того, чтобы не переносить вручную многочисленные настройки мета-полей.

Как сделать пока не придумал. Да и когда делать тоже пока не нашёл :) Сейчас хочу просто положить эту идею здесь, чтобы не забыть и набрать ещё желающих подобное получить.

**Comment by maxsite** [comment]
Текстовая заготовка и через AutoPost.
