### ISSUE TITLE
Форма обратной связи и DMARC policy for mail.ru

### ISSUE THREAD

**Issue by Fore-Man** [maxsite/cms#158]
Уже несколько месяцев письма с формы обратной связи не приходят, так как в адрес отправителя вставляется емейл написавшего письмо. Можно ли сменить адрес отправителя, а его емейл перенести в тело письма. Или подскажите в каких файлах искать сей код.

**Comment by maxsite** [comment]
В dev-версии эта проблема решена.

**Comment by v0ff4k** [comment]
можно поискать по тексту письма и потом посмотреть что его подгружает, и найдете свою форму обратной связи.

например в гостевой(возможно это та самая "форма обратной связи") /application/maxsite/plugins/guestbook/guestbook.php

**Comment by Fore-Man** [comment]
Пока нет возможности перехода на новую версию в связи с кучей своих заплаток в дефолт шаблоне. Подскажите пожалуйста какой файл просмотреть в старой и новой версиях для решения данного вопроса.
