### ISSUE TITLE
Ошибка компиляции с помощью WinLess

### ISSUE THREAD

**Issue by Sl-Alex** [maxsite/cms#159]
style.less в default шаблоне не компилируется при помощи WinLess:
`
Time	File	Compiler Result
16:46:50	D:\test\cms-0.95\application\maxsite\templates\default\assets\less\style.less	SyntaxError: variable @undefined is undefined in D:\test\cms-0.95\application\maxsite\templates\default\assets\less\unicss\unicss.less on line 295, column 1:
294 
295 .border_list_color_loop(length(@border_list_color));
296
`

Компиляция через Node.js и Grunt по [этой](http://maxsite.org/page/less-compiling-nodejs-and-grunt) инструкции проходит успешно.
WinLess рекомендуется в assets/readme.txt шаблона.

**Comment by maxsite** [comment]
Используйте «глобальный компилятор». Опция **Use globaly installed less**.

**Comment by Sl-Alex** [comment]
Похоже, readme немного устарел (ссылка на http://unicss.maxsite.com.ua/compiling нерабочая).
Большое спасибо за подсказку, мне не пришло в голову их скрестить :)

**Comment by maxsite** [comment]
Ок. Поправлю текст.
