### ISSUE TITLE
Любой сторонний редактор и MaxSite 0.95 вызывает неработоспособность табов.

### ISSUE THREAD

**Issue by JekaWm** [maxsite/cms#160]
На 0.94. Использовал редактор и все работало. Стояло обновиться к 0.95 и включить мой редактор как табы становятся неактивными. Попробовал еще пару редакторов к примеру : http://maxhub.ru/page/plugin-editor-wysibb . Та же проблема. Табы работают нормально только с стандартным редактором.

**Comment by cuprum** [comment]
Я проверил, этот редактор не подключает скрипт tabs.js

**Comment by Den2016** [comment]
Проблема заключается в том, что появился блок do-script, который "любой сторонний редактор" просто не знает.
Решение для tinymce

правке подлежат два файла в плагине tinymce

application/maxsite/plugins/editor_tinymce/index.php
в функции editor_tinymce вставляем в 50-ую строку

if (isset($args['do_script'])) $editor_config['do_script'] = $args['do_script'];
else $editor_config['do_script'] = '';


application/maxsite/plugins/editor_tinymce/editor.php

в последней строке между </script> и <form> вставляем <?= $editor_config['do_script'] ?>

и добавляем Id для формы

 <form id="form_editor" method="post".....

**Comment by maxsite** [comment]
Значит дело в самом плагине? Закрывать тикет?

**Comment by Den2016** [comment]
Ну по сути, да. Изменения в 0.95 (а может и ранее) не учтены плагином. Если его подправить - все работает

**Comment by maxsite** [comment]
Киньте тогда исравленный вариант Илье, пусть заменит на архив сайте. Думаю это самый простой вариант.

**Comment by Den2016** [comment]
Эээ... я как бы не силен в связках Ник-Имя ))) Кинул бы, да не знаю - куда)))

**Comment by vimruler** [comment]
> Кинул бы, да не знаю - куда)))

Это Максим про меня. Кидайте на contact@maxhub.ru

**Comment by Furnicarium** [comment]
не закрывайте тикет, проблема осталась и в 2018 году. универстальное решение выложено было на максхабе 


> Просто поставить после
```
require($MSO->config['admin_plugins_dir'] . 'admin_page/form-do_script.php');
echo $do_script;
```
в файле      /application/maxsite/admin/plugins/admin_page/form.php
