### ISSUE TITLE
Server Ubuntu 16.04.2 / PHP 7.0.8 MySQL 5.7.15 / Apache 2.4.18 - Пустая страница после установки.

### ISSUE THREAD

**Issue by setuppc** [maxsite/cms#161]
Версия движка 0.95
Ставил на сервер
sudo apt install apache2
sudo apt install mysql-server
sudo apt install php libapache2-mod-php php-mcrypt php-mysql
sudo apt install phpmyadmin php-mbstring php-gettext

В Ubuntu 16.04.2 Что то изменилось в MySQL 5.7.15 (права и привилегии к базе вроде) и PHP 7.0.8  (PHP что именно не знаю но 7-ка говорят работает в 2 раза быстрее 5-ой ) куда копать пока понять не могу , пара движков отличных от Maxsite запускаются без проблем на данной конфигурации.

Логи Apache2  /var/log/apache2/error.log  (в одну строку в оригинале то что ниже с переносами строк для удобства прочтения)

PHP Fatal error:  Uncaught Error: Call to a member function num_rows() on boolean in
/var/www/html/application/maxsite/common/page.php:611\nStack trace:\n#0
/var/www/html/application/maxsite/common/page.php(214): _mso_sql_build_home(Array, NULL)\n#1
/var/www/html/application/maxsite/shared/type/home/units/home-full.php(23): mso_get_pages(Array, NULL)\n#2
/var/www/html/application/maxsite/shared/type/home/home.php(136): require('/var/www/html/a...')\n#3
/var/www/html/application/maxsite/templates/default/index.php(22): require('/var/www/html/a...')\n#4
/var/www/html/system/core/Loader.php(830) : eval()'d code(12): require('/var/www/html/a...')\n#5
/var/www/html/system/core/Loader.php(830): eval()\n#6 /var/www/html/system/core/Loader.php(420): CI_Loader->_ci_load(Array)\n#7
/var/www/html/application/controllers/maxsite.php(133): CI_Loader->view('index', Array)\n#8
/var/www/html/application/controllers/maxsite.php(68): Maxsite->_view_i('home')\n#9
/var/www/html/system/core/CodeIgniter.php(326): Maxsite->_remap('home', Array)\n#10 /var/www/ht in
/var/www/html/application/maxsite/common/page.php on line 611

Заранее всем спасибо. Выручайте , можно конечно и Ubuntu 14.04 вернуть но .......

**Comment by maxsite** [comment]
Такая ошибка свидетельствует о какой-то проблеме с выборкой данных из базы. Всё-таки поставьте phpMyAdmin и проверьте доступность базы под данным пользователем. То есть вначале нужно исключить самые базовые проблемы.

Я сейчас точно не помню, но кажется в MySQL 5.7 меняли какой-то режим на принудительно «строгий» для запросов SQL. Возможно и в этом проблема. Для таких вещей нужно будет включить логирование в MySQL и посмотреть какие sql-запросы создает MaxSite CMS и их вручную через phpMyAdmin выполнить и посмотреть что в итоге. Это второй шаг.

**Comment by setuppc** [comment]
phpMyAdmin установлен "sudo apt install phpmyadmin php-mbstring php-gettext" 6-я строчка тикета выше. Пользователя задавал и рутового и отдельного с глобальными правами - все едино.
Логи апача визжат на строки в php файлах в папках движка
page.php: 611и 214 строка
home-full.php 23 строка
Loader.php 830 строка
И так далее .... Установка других CMS проходит нормально. Может что то в PHP отключить или в MySQL "строгости" по убавить? К сожалению ума хватает только на то что бы настроить простейший сервер и поставить по инструкции CMS , в PHP не бум-бум вообще.
Как включается логирование в MySQL? Есть ли консольная команда? Где потом смотреть логи? И как их выполнить в ручную? Не могли бы Вы с моделировать хотя бы в виртуалке мой конфиг там дел то на 20 минут не более , так возможно будет быстрее чем с моей подготовкой в данном вопросе. Спасибо.

**Comment by maxsite** [comment]
Ошибка говорит о том, что не получены данные с БД. И тут вопрос только в том на каком уровне эта проблема возникает. Как правило — это недостаточный уровень пользователя. То есть нужные все разрешения на операции с БД, а не просто на доступ. Другая причина — битая база.

Посеколку у вас новая MySQL 5.7, то проблема может быть и на её уровне. Это от неверной конфигурации до каких-то новых «особенностей» версии. Простой вариант — попробовать поставить другую версию, например типовую 5.5. Если с ней заработает, то уже от этого и плясать.

**Comment by setuppc** [comment]
Базы точно не битые -100% каждый месяц скрипт делает бекап всех баз , рабочие проверенно.
Что сделал за ночь ....

На одной виртуалке  поставил свежую Ubuntu 14.04.5 
PHP 5.5.9 / MySQL 5.5.52/ Apache 2.4.7 - Ubuntu 14.04.5

mysql -u root -p
create database maxsite;
use maxsite
alter database character set utf8;
alter database collate utf8_general_ci;

create database wordpress;
use wordpress
alter database character set utf8;
alter database collate utf8_general_ci;
exit

Установка  чистой  CMS  Maxsite - 0.95 ............ Ok!
Сайт открывается в админку пускает.
Установка  чистой  CMS  Wordpress - 4.6.1 ............ Ok!
Сайт открывается в админку пускает.

На другой виртуалке  поставил свежую  Ubuntu 16.04.2 
PHP 7.0.8 / MySQL 5.7.15 / Apache 2.4.18 - Ubuntu 16.04.2

mysql -u root -p
create database maxsite;
use maxsite
alter database character set utf8;
alter database collate utf8_general_ci;

create database wordpress;
use wordpress
alter database character set utf8;
alter database collate utf8_general_ci;
exit

Установка  чистой  CMS  Maxsite - 0.95 ............ Установщик пишет что все все соединилось и база создана (и так оно и есть) но, сайт НЕ открывается в админку НЕ пускает. В окне любого браузера пустая страница.
Установка  чистой  CMS  Wordpress - 4.6.1 ............ Ok!
Сайт открывается в админку пускает. 
Что как бы говорит что PHP 7.0.8+ MySQL 5.7.15+Apache 2.4.18 - в принципе нормальные ребята и они свое отработали и к ним претензий нет.

Откатится на Ubuntu 14.04.5 это вовсе не трудно ибо все конфиги и базы и каталоги забекаплены и в данный момент все работает штатно. Но .....
Хочется новую Maxsite 0.95 + PHP 7.0.8 +MySQL 5.7.15+Apache 2.4.18+Ubuntu 16.04.2
Буду бороть как умею по результатам - получится запилю тут новый тикет как.
Знания сильно ограниченны в этом направлении и буду признателен за любые подсказки от всех.

**Comment by maxsite** [comment]
Ну а если попробовать варианты с PHP 7 с MySQL 5.5 и PHP 5.5 с MySQL 5.7?

**Comment by setuppc** [comment]
Да можно в принципе.  А есть ли смысл? Кто в здравом уме ( кроме меня конечно ) будет на рабочем сервере заниматься таким непотребством? Да хостинги умеют одной кнопкой переключать версии PHP но там скорее всего будет тот же результат а это даунтайм. Потом в случае с  ubuntu 16.04.2 это установка LAMP "из коробки" в два клика и 20 минут на развертывание бекапов.
А путь с вариантами это подключение старых репов и неизвестное количество костылей и распорок для конфигов , подтягивание зависимостей .  Старая связка работает и поддерживается до 2018 года вместе с хардваре стеком. Новая до 2021 года. Время есть.... 
Наверняка все упирается в отключение какой нибудь функции в PHP или как это часто бывает в замене пары строчек в конфигах в каталогах с движком - вопрос времени. Может со временем кто то еще  кроме меня решит заполучить себе связку "хочу ВСЕ НОВОЕ" и запостит решение, не может быть что я один такой.  В свободное время от основной работы буду мучать виртуалку и почему то кажется что эту траблу мы заборем в ближайшее время. Может апдейт какой нибудь все решит. Не плохо бы PHP гуру глянуть на тему. Не прощаюсь.

**Comment by maxsite** [comment]
На рабочих серверах PHP 5.3, даже 5.2, максимум 5.5. Семерку нет смысла использовать, поскольку они там много чего поломали и это вызовет проблемы совместимости со старым софтом. Поэтому PHP 7 — это скорее для энтузиастов. К вам претензий нет. Вопрос только в том, чтобы выяснить корень проблемы — в новом PHP или в новом MySQL. В виду слабого Инета я это сделать не смогу. Если сможете сами выявить зависимость, то отлично, будет понятно направление работы. Нет, тикет закрывать пока не буду, может кто-то подключиться и тоже проверит.

**Comment by setuppc** [comment]
Касательно MySQL 5.7 и «строгий» режим
На самом деле является списком следующих настроек включенных в 5.7 по умолчанию:
ONLY_FULL_GROUP_BY
STRICT_TRANS_TABLES
NO_ZERO_IN_DATE
NO_ZERO_DATE
ERROR_FOR_DIVISION_BY_ZERO
NO_AUTO_CREATE_USER
NO_ENGINE_SUBSTITUTION

До версии 5.7 единственный режим, который был включен по умолчанию — NO_ENGINE_SUBSTITUTION.

Точная настройка режимов если  не устраивают режимы 5.6 и 5.7 по умолчанию

'connections' => [
        'mysql' => [
           // Игнорировать этот ключ, полагаться  на ключ strict
            'modes' => null,

           // Отключить принудительно все режимы, переопределяя  настройку strict
            'modes' => [],

           // Принудительно включить только указанные  режимы, переопределяя  настройку strict
            'modes' => [
                'STRICT_TRANS_TABLES',
                'ONLY_FULL_GROUP_BY',
            ],
        ]
    ]
 Пишут что параметры живут в конфигурационном / database.php в connections.mysql разделе.
Взято с  https://habrahabr.ru/post/278629/ 
Пытаюсь найти документ в каталоге движка где это можно опробовать найти не могу.
Логично предположить что менять настройки глобально всего сервера не есть хорошо ибо возможны косяки на других проектах и правильнее заставить движок подключаться к MySQL с нужными ему параметрами. Есть идеи? Готов пробовать и тестировать. Описать действия лучше подробнее как для "блондиюзера" что и где именно прописать.

**Comment by maxsite** [comment]
По-умолчанию в MaxSite CMS строгий режим (stricton или STRICT_ALL_TABLES) как раз отключен. Все настройки базы в **application/config/database.php**. Там есть описание каждого параметра. Вот здесь небольшой хелп: http://cidocs.ru/210/database/configuration.html

Поэтому в теории всё должно через этот файл настраиваться. Строгий режим в CodeIgniter выполняется через sql-запрос `SET SESSION sql_mode="STRICT_ALL_TABLES"` Влияет ли этот запрос на другие «строгие» настройки MySQL неизвестно.

Попробуйте всё-таки попробовать поменять настройки непосредственно в MySQL. Тогда будет понятно какой параметр создает проблему.

**Comment by maxsite** [comment]
Логирование sql-запросов можно включить в my.ini

```
[mysqld]
log = полный путь\mysql\logs\mysql.log

```

**Comment by multVVM** [comment]
установил на OpenServer чистую установку max cms 0.95, выставил настройки для php 7, не создается таблица mso_page.

**Comment by multVVM** [comment]
можно пока в ручную создать таблицу, тогда сайт запуститься

**Comment by multVVM** [comment]
связка  PHP 7 с MySQL 5.7 не работает
в связке PHP 7 с MySQL 5.5/MySQL 5.6 все нормально

**Comment by maxsite** [comment]
Можете проверить sql-запросы по созданию таблицы? Они в **install/distr/sql/model.sql**. Каждый по отдельности можно. Только нужно сделать текстовую замену **TABLE _PREFIX_** на **mso_** и **_CHARSETCOLLATE_** на **DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci**

**Comment by multVVM** [comment]
ошибка в этой строке

page_date_dead datetime NOT NULL default '0000-00-00 00:00:00',

если ее заменить на 

page_date_dead datetime NOT NULL default '2008-01-01 00:00:00',

таблица создается

**Comment by maxsite** [comment]
То есть если изменить эту цифру всё работает как нужно?

**Comment by maxsite** [comment]
Включая и инсталяцию, и сам сайт.

**Comment by multVVM** [comment]
да, все работает
скорее всего проблема в настройках MySQL

ONLY_FULL_GROUP_BY
STRICT_TRANS_TABLES
NO_ZERO_IN_DATE
NO_ZERO_DATE
ERROR_FOR_DIVISION_BY_ZERO
NO_AUTO_CREATE_USER
NO_ENGINE_SUBSTITUTION

не разрешает по дефолту устанавливать дату '0000-00-00 00:00:00'

**Comment by maxsite** [comment]
Ок. Спасибо, внесу исправление. :-)

**Comment by setuppc** [comment]
Полностью подтверждаю! Не поленился с нуля на виртуалке выставил Server Ubuntu 16.04.2 / PHP 7.0.8 MySQL 5.7.15 / Apache 2.4.18 - Все работает! Сайт утанавливается , открывается в админку пускает. 

В  install/distr/sql/model.sql  до установки движка исправил число в строке
page_date_dead datetime NOT NULL default '0000-00-00 00:00:00',  на
page_date_dead datetime NOT NULL default '2008-01-01 00:00:00',

Вопрос как быть с уже созданными / перенесенными проектами а есть и совсем старенькие ...
С базами все понятно как чего и куда  а  если я переношу готовый "рабочий" каталог уже существующего проекта.  В каком файле что заменить? Что бы не было пустой страницы.
Что бы соединение проходило так же. 
Еще одна строка в конфиге в папке с движком?
