### ISSUE TITLE
Audio плеер на HTML5

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#162]
В движке есть хороший плагин **audioplayer** для проигрывания mp3 и обрабатывающего бб-код [audio]. Всё хорошо, но он использует flash, который сейчас активно "выдавливается" из браузеров. В этой связи хотел бы обозначить задачу (самому пока некогда, да и сперва хотел бы обсудить) обновления плагина для перевода его на рельсы HTML5.

За основу можно взять, например, вот [этот WP-плагин](https://wordpress.org/plugins/simple-audio-player/).

**Comment by maxsite** [comment]
Ну так и обсуждать нечего — flash нужно убирать. :)

**Comment by vimruler** [comment]
> Ну так и обсуждать нечего

Обсуждать нужно какую реализацию плеера использовать в новой версии :-)

**Comment by maxsite** [comment]
А разме стандартного тэга audio не достаточно?

**Comment by vimruler** [comment]
> А разве стандартного тэга audio не достаточно?
Ну может и достаточно. Я пока не вникал и размышляю "по-старинке".

**Comment by maxsite** [comment]
Закрываем обсуждение?

**Comment by vimruler** [comment]
Думаю, да.
