### ISSUE TITLE
Быстрая загрузка картинок - отключение изменения размера

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#164]
Сейчас на страницы записи у быстрой загрузки картинок можно указать размер уменьшения но никак нельзя это уменьшение отключить. В смысле отключить можно, но надо переходить на страницу загрузок и шаманить-загружать там.
А что если  в блок быстрой загрузки добавить птичку отключения?

**Comment by vimruler** [comment]
Поддерживаю запрос. Дико мешает отсутствие возможности отключить ресйзинг, ибо чаще нужно именно без переделки загружать картинку. Приходится переходить на страницу загрузок.

**Comment by maxsite** [comment]
Наверное можно что-то придумать.

**Comment by maxsite** [comment]
Вот, вспомнил! :) Сейчас при загрузке можно указать только один размер, который автоматом интерпретируется либо как высота, либо как ширина. Лично меня этот момент несколько раздражает. Например если нужно загрузить портретное фото например 500х1200, то в результате получится 250х600 (при выставленном размере 600). То есть можно добавить некую опцию, которая будет указывать как именно выбирать вариант уменьшения. Если это будет select, то здесь же можно будет указать и «загружать как есть».

**Comment by maxsite** [comment]
Вот так это может выглядеть:
![Image](http://s.wbloger.com/2016/2016-11-21-12-51-000.png)

**Comment by maxsite** [comment]
Можно тестировать.

**Comment by cuprum** [comment]
Да, с селектом было бы неплохо.

**Comment by cuprum** [comment]
Все работает. Максим, может варианты изменения миниатюр написать на русском?

**Comment by maxsite** [comment]
Я как-то пытался, но там они такие длинные получаются, что просто не влезают в select.

**Comment by cuprum** [comment]
Но нужны ли эти все варианты? Потому что сейчас все равно трудно понять по английским сокращениям. А если оставить только 2. Чтоб было как в загрузках: пропорциональное уменьшение и обрезка по центру.

**Comment by maxsite** [comment]
Жалко отказываться от существующих возможностей.
