### ISSUE TITLE
common/page.php нарушает идеологию

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#165]
В функции mso_get_pages со строки  316 по 361 идет формирование ссылки "Читать далее...". Функция генерирует жесткую ссылку, которая будет всегда и везде без правки кода ядра. Таким образом, становится невозможным создание шаблона с другим расположением этой ссылки. 
Необходимо вывести эту ссылку на уровень шаблона.

**Comment by maxsite** [comment]
Скрываете её через css и делаете свой вариант на любом уровне..

**Comment by Den2016** [comment]
)))) об этом я не подумал ))) Спасибо за подсказку. Но нарушение все же имеет место быть, но тут уже и shared надо подправлять

**Comment by maxsite** [comment]
Там довольно сложный алгоритм, так просто это не перенести. Задач, где нужна своя обработка cut практически нет, поэтому проще отдать это на откуп системе.
