### ISSUE TITLE
Разрешения - Группы пользователей

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#166]
Есть механизм задания групп. Создал я еще одну группу. Проставил галочки. Но не нашел способа ввода комюзера в группу. Он вообще существует? Или это заготовка, не дошедшая до реализации?

**Comment by vimruler** [comment]
Вообще-то, комюзеры - это только комментаторы. В движке специально разведены юзеры и комюзеры, чтобы последние вообще не имели доступа в админку.

**Comment by Den2016** [comment]
Ну эту идеологию я знаю. Помнится, Макс мне жестко сказал "нет" на предложение объединить )))
Но смысла эти группы не имеют. Либо их убрать совсем, либо все-таки позволить комментаторам быть частично авторами. Использую CMS для разработки интернет-магазина, и как-то не очень удобно перелогиниваться между двумя учетками. Хотел было задать для своей комюзер-учетки админские права, чтобы не париться - облом.

**Comment by maxsite** [comment]
Ну вообще-то есть многоавторские сайты, где деление на группы очень даже востребовано. Если хотите кого-то пускать в админку, делайте их сразу авторами, а не комюзерами.

**Comment by Den2016** [comment]
К сожалению, этот вариант мне не подходит
