### ISSUE TITLE
mso_mail - _safe_mode - необходимо внести в админку

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#167]
Полдня убил на загадку - почему wordpress с моего хостинга отправляет письма, а MaxSite нет.
Разгадка оказалась проста - в mso_mail() пришлось закомментировать строку
`$CI->email->_safe_mode = true; # иначе CodeIgniter добавляет -f к mail - не будет работать в не safePHP`

и сразу все заработало. По-моему - это неправильно. Эта настройка должна быть в админке, не все могут копаться в исходниках, это раз, при обновлении опять придется туда лезть - это два.

**Comment by vimruler** [comment]
Denis, а какие настройки у вашего php  на сервере были в плане safe_mode?

**Comment by Den2016** [comment]
Илья, если честно - даже знать не хочу. И так голова пухнет от других задач, чтобы еще узнавать, что в php есть safe_mode, а в CMS есть грабли с этим делом при отправке писем. Просто (имхо) эта штука должна быть в настройках, чтобы чайник мог попереключать и получить рабочую отправку почты.
Однако, осознавая важность данной инфы )))) полез в гугл и на сервер. Вот что на [php.net](url=http://php.net/manual/ru/features.safe-mode.php) по этому вопросу


> 5.4.0 	Удален из PHP, генерирует фатальную ошибку E_CORE_ERROR при попытке включения.
> 5.3.0 	Помечен устаревшим, при включении генерируется ошибка уровня E_DEPRECATED. 

вот что на сервере

# grep -R safe_mode\ =
cli/php.ini:safe_mode = Off
cli/php.ini:sql.safe_mode = Off
cgi/php.ini:safe_mode = Off
cgi/php.ini:sql.safe_mode = Off
fpm-fcgi/php.ini:safe_mode = Off
fpm-fcgi/php.ini:sql.safe_mode = Off
apache2-mod_php/php.ini:safe_mode = Off
apache2-mod_php/php.ini:sql.safe_mode = Off

При этом установлен php 5.5.24, то есть safe_mode отсутствует в принципе. И если опухший мозг правильно соображает, то у меня "не safe_mode" и "CodeIgniter добавляет -f к mail - не будет работать в не safePHP" для моего "не safePHP" вообще неверно. Осталось выяснить - safe_mode === safePHP ?

**Comment by maxsite** [comment]
В CodeIgniter'e в библиотеке email.php есть странная связка с safe_mode PHP. В этом режиме PHP, с точки зрения CodeIgniter, функция mail() должна получать дополнительные параметры в виде флага -f и from. Почему именно так сделано сказать сложно, кроме использования -f для sendmail. Чтобы отключить это безобразие и ставится `$CI->email->_safe_mode = true;` который как раз и **отключает** эти непонятные заголовки (мы их формируем сами). 

Если у вас на сервере какая-то особая настройка mail, то это отдельный разговор, где нужно иметь точные данные как админ сервера предполагает отправку почты. Например требует тот же -f, без которого почта просто не работает.

**Comment by Den2016** [comment]
На сервере я сам админ, но так глубоко не лез в настройки и вряд ли полезу. Но если у меня такие грабли обнаружились, где гарантия, что не будет таких граблей у других? Поэтому и прошу вынести этот флажок в админку, чтобы была возможность **не лезть в исходники** для обхода этих граблей

**Comment by maxsite** [comment]
Эти грабли именно у вас на сервере. Другим это просто не нужно.

**Comment by Den2016** [comment]
Ну слава тебе, Господи! Хоть в чем-то я уникален...
