### ISSUE TITLE
Оптимизированный рандом

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#168]
в адмике есть функция выводить посты на главной рандомно. Если это делается просто функцией RAND, это не есть хорошо. Есть способ, который сокращает время запроса в 3-12 раз. 
http://www.simplecoding.org/wordpress-vybor-sluchajnyx-postov.html тут статья об этом.

**Comment by maxsite** [comment]
Данная статья некорректна. Время SQL-запроса следует определять по логам при профилировании. Рандомные запросы, естественно будут дольше, чем по интексируемому id. Но это только при небольшом количестве записей.

**Comment by Furnicarium** [comment]
почему при небольшом? небольшой это сколько? Я, например, хочу выводить 100 похожих постов из 10 000 постов. Существующий вариант рандома лучше, чем оптимизированный из статьи, подойдёт для этой цели? в теории. тем более, если вывод делается с помощью плагина.

**Comment by maxsite** [comment]
Вы мне зачем эти вопросы задаёте? Это ваша хотелка, вот и проводите профилирование и выясняйте какие запросы сколько выполняются. У меня нет сомнений в работе MySQL и я не вижу необходимости заниматься этим вопросом основываясь на чужой некомпетентности.

**Comment by Furnicarium** [comment]
вот ты злой. тут я не пул-реквест делаю со всеми готовыми наработками, это раздел для обсуждения идей. ты сам сюда пригласил людей для обсуждений "хотелок" и предложений, а сейчас унижаешь на том основании, что у тебя побольше знаний о работе MySQL. молодец.
