### ISSUE TITLE
Метки в отдельную таблицу

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#169]
Что-то не так с таблицей меток (тегов) к постам. Они находятся в таблице mso_meta, где по соседству ещё 7 столбцов, а должно быть около 3. Это нужно для того, чтобы ускорить вывод похожих постов, необходимо реализовать связь "многие ко многим", для её работы нужны три таблицы, одна уже есть это пост - id1, другая это уникальный тег и айди постов, где он встречается, третья это просто тег-id2. Поправьте, если чушь несу.

**Comment by maxsite** [comment]
Количество столбцов никак не влияет на скорость выборки. Ваши рассуждения ошибочны.

**Comment by Furnicarium** [comment]
я предлагал сделать так - создать таблицу, где тег будет уникальным, и в соседнем столбце будут прописаны id постов, к которым прикреплен именно этот тег. Всё-таки, количество постов может быть хоть 100 000, а тегов на сайте всего 50, в лучшем случае 300. не годится идея?

**Comment by maxsite** [comment]
Судя по вашей орфографии вы также плохо разбираетесь и в работе БД. Не вижу смысла это обсуждать дальше.

**Comment by Furnicarium** [comment]
лол, во-первых, писал это в 3 ночи, во-вторых, тут такой шрифт, что фиг точку от запятой отличишь, а в-третьих - вообще-то предложение написано орфографически правильно, или каждое новое предложение в комментариях в интернете обязательно должно начинаться с заглавной буквы? ты не выспался и не с той ноги встал. Я даже не спрошу, где у меня там ошибки ты увидел, потому что ты просто придираешься и не хочешь по-человечески ответить на вопрос. я спросил, годится ли идея, поэтому меня бы устроил ответ "нет", а ты пустился в рассуждения о моей орфографии. Это адекватно, ты считаешь? 
Вот у кого проблемы с орфографией, так это у тебя. в твоём предложении "Вашей"  и "Вы" надо с заглавной написать, потому что это вежливое обращение, "также" написать либо раздельно, либо не употреблять вместе с союзом "и", не знаю, с чем ты сравнивал мои познания о работе БД. Злой ты.

**Comment by maxsite** [comment]
У вас мания величия. Вы не только в базах плохо разбираетесь, но и в русском языке.
