### ISSUE TITLE
Загрузка картинок прям в пост

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#170]
Предлагал это в комментарии на сайте. Я вижу, что идёт активная работа над способом обработки изображений (разные варианты обрезки) и способами прикрепления их к постам. Но всё же. Если Вы реализуете загрузку картинок по ссылке или прямо в пост, то цены этому редактору просто не будет. js редакторы это умеют уже несколько лет как и это не является чем-то необыкновенным, но внедряют это почему-то крайне редко. даже в ls эта опция не идёт из коробки, а реализуется с помощью плагина, но зато работает.

**Comment by maxsite** [comment]
Проблема новичков в том, что они видят только дерево перед своим носом. Вам не приходило в голову, что вопрос загрузки файлов с другого сервера может поставить под угрозу сайт? Например вам могут подсунуть шел или ещё какой-нибудь зловред? Вы и знать про это не будете, но файл окажется на вашем сервере и дальше возникает море вариантов его использования.

**Comment by Furnicarium** [comment]
нет, не приходило. закрывай.
