### ISSUE TITLE
Плагин для Open Graph

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#171]
Думаю, что нужно вынести поддержку Open Graph на уровень плагина. Там есть ряд настроек, которые могут по разному применяться для разных og-типах и зависеть от вывода на сайте (главная, рубрики, записи и т.п.) Здесь же нужно сделать и поддержку твитера. Там всё тоже самое, только свои мета (twitter:title и т.п.).

Линки: 
http://ruogp.me/
https://habrahabr.ru/post/278459/

**Comment by vimruler** [comment]
А как быть с местом вставки разметки? Его же придётся заранее предусмотреть. Или уже всё нужное есть?

**Comment by maxsite** [comment]
Теоретически должно быть достаточно хука head. А для атрибутов <HTML>придется придумать новый хук, поскольку mso_get_val будет недостаточно.

**Comment by maxsite** [comment]
Я наверное сделаю тестовый плагин к MaxSite CMS 0.96. Правда всё равно не ясно как тестировать эту разметку...

**Comment by maxsite** [comment]
Текущий вариант: https://github.com/maxsite/cms/commit/cdd1a3e474e241ea8b9e4b0eab1bbf90da0112fa

**Comment by maxsite** [comment]
В последней версии добавил нормальную поддержку твиттера. А вот с фейсбуком никак не понимаю как можно оттестировать...
