### ISSUE TITLE
Система не пускает комюзера редактировать данные

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#172]
Ситуация такая. Комюзер залогинился через форму сайт/login. Перешел на свою страницу, отредактировал данные, нажал ссылку "Выход".
Появляется форма

![form](https://cloud.githubusercontent.com/assets/532546/22181024/63ffe69a-e093-11e6-91ca-37a4372c0b1f.png)

Теперь, если комюзер введет свои учетные данные для входа -> Отправить, то ничего не происходит.

**Comment by maxsite** [comment]
Да, нужно разобраться в чём-там дело.

**Comment by maxsite** [comment]
Поправил. Должно всё работать.

**Comment by Furnicarium** [comment]
> Поправил. Должно всё работать.
Неа, не работает. ни с автоматической активацией, ни с совершённой активацией, комюзер не может редактировать свои данные.
