### ISSUE TITLE
Maxsite и поддомен

### ISSUE THREAD

**Issue by Anchovys** [maxsite/cms#173]
Maxsite по какой-то причине полностью отказывается работать на поддомене. Когда заходишь на поддомен типа **m.mysite.ru**, то автоматом перекидывает на основной домен - **mysite.ru**. Как решить данную проблему? Возможно как-то поиграться с настройками  htaccess?

**Comment by maxsite** [comment]
Смотря как организованы поддомены на сервере. Если бы это был подкаталог (mysite.ru/m), то нужно было бы его указать в .htaccess в RewriteBase и RewriteRule. А так, это считается корнем сайта и проблем быть не должно и ничего менгять не нужно. Скорее всего таковы настройки сервера. Уточните у админа сервера, он может подскзать.

**Comment by Anchovys** [comment]
Использую хостинг Макхост, субдомены лежат в папке **/subdomains/m/httpdocs/**, а основной сайт в **/httpdocs/**. Каким образом нужно настроить .htaccess в таком случае?

**Comment by maxsite** [comment]
Здесь httpdocs — корневой, поэтому ничего в .htaccess менять не нужно. Вам нужно определить откуда вообще идет редирект. Возможно он прописан для основного домена. Если любые запросы на поддомен получают редирект на основной, то проблема скорее всего имено в настройках .htaccess основного домена.

**Comment by Anchovys** [comment]
```
Options +FollowSymLinks
Options -Indexes
DirectoryIndex index.php index.html
AddDefaultCharset UTF-8

#php_flag register_globals off
#php_value memory_limit 16M

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?/$1 [L,QSA] 
</IfModule>
```
Вот htaccess главного домена. Используется htaccess от maxsite 0.86.  Полагаю, нужно как-то изменить строку **RewriteRule ^(.*)$ /index.php?/$1 [L,QSA]** , верно?

**Comment by maxsite** [comment]
Тут всё нормально. Если убрать всю секцию IfModule, редирект сохраняется?

**Comment by Anchovys** [comment]
Кажись всё заработало. Главная страница отображается корректно, но если захожу в любую новость, выдает 404 error и изредка белый экран с "No input file specified. "

```
Options +FollowSymLinks
Options -Indexes
DirectoryIndex index.php index.html
AddDefaultCharset UTF-8

#php_flag register_globals off
#php_value memory_limit 16M

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
# RewriteRule ^(.*)$ /index.php?/$1 [L,QSA]
</IfModule>
```

Это уже .htaccess сайта, работающего на поддомене. В процессе установки он закомментировал ту самую заветную строку **RewriteRule ^(.*)$ /index.php?/$1 [L,QSA]**. 

И вот прикол в том, что у меня уже была ошибка  "No input file specified. ", когда я устанавливал в корень. Она решалась заменой строки  **RewriteRule ^(.*)$ /index.php/$1 [L,QSA]** на  **RewriteRule ^(.*)$ /index.php?/$1 [L,QSA]**. Но в этом случае она закомментирована. Как быть в таком случае?))))

**Comment by maxsite** [comment]
Менять RewriteRule нужно только если сервер работает в каком-нибудь «экзотическом» режиме, вроде CGI или fastCGI. Дня них характерна немного другая передача get-параметров url-запросов. Точнее сказать сложно, поскольку это зависит от настроек сервера. Ошибка «No input file specified» как раз и говорит о том, что запрос передан неверно. Нужно подбирать правильный вариант вручную. Ну или вручную анализировать GET-запросы в _SERVER.

Но вообще я первый раз слушу про такую проблему с макхостом. Может проще им написать и уточнить?

**Comment by Anchovys** [comment]
Благодарю за помощь. Сайт заработал как нужно, все работает кроме авторизации. Т.е не могу авторизоваться под админа (пишет, что неверный пароль). На главном сайте все работает отлично. Так как оба сайта подключены к одной Б.Д, то статьи будут отображаться на обоих сайтах. Можно-было бы так и оставить, но нужно включить лишь один плагин  для работы BB-кодов, ибо сейчас они не отображаются как нужно. Как мне можно исправить эту проблему, либо как включить этот плагин вне админки? Я так понимаю, что данные о плагинах хранятся не в БД.

**Comment by maxsite** [comment]
Если на уровне шаблона в районе `functions.php`, то плагин можно подключить по нужному условию примерно так:

```php
if (!function_exists('bbcode_autoload'))
{
	require_once(getinfo('plugins_dir') . 'bbcode/index.php');
	bbcode_autoload();
}
```

**Comment by Anchovys** [comment]
Спасибо! Все работает идеально. p.s ридерит сделал через php, в начало index.php на основном сайте дописал 
```
$useragent=$_SERVER['HTTP_USER_AGENT'];
 if(preg_match('/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i',$useragent)||preg_match('/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i',substr($useragent,0,4)))
    {
      header("Location:http://m.".$_SERVER['HTTP_HOST']. $_SERVER['PHP_SELF'].$_SERVER['QUERY_STRING']);
    }
```

**Comment by maxsite** [comment]
Ну хоть я и не поддерживаю такой подход (адаптивность всё-таки получше будет), но вообще можно воспользоваться Mobile Detect: http://mobiledetect.net/

**Comment by Anchovys** [comment]
Хорошо, воспользуюсь этим. Адаптивный не получится. Вернее получится, но он будет очень тяжелым. Основной сайт слишком "Навороченный". Там подключено слишком много ненужных плагинов и прочего, за счет чего, он грузится очень долго. Конечно-же, при надобности можно их вмиг все отключать, но по-моему проще и надежнее просто перебрасывать посетителя на другой сайт, на котором все по-максимуму выключено. Да и навыков у меня еще не так много. Но по скорости, по-моему, это лучший вариант. ИМХО.

**Comment by maxsite** [comment]
C точки зрения сервера, разница небольшая. С точки зрения браузера, тоже отличий минимум. С точки зрения трафика, тут просто посмотреть что именно его составляет. Обычно тексты и картинки, а это многократно перевесит любую «мобильную оптимизацию». Да и современные смартфоны уже полноценные компютеры. Для них отобразить полноценную страницу не проблема. Главной решить волпрос с шириной экрана, а это как раз и есть адаптивная верстка.

**Comment by Anchovys** [comment]
Всё-таки да, я с вами полностью согласен. Как только появится время, поменяю движок на последнюю версию и переделаю шаблон. Сейчас сайт висит на 0.86, переход на новую версию ограничивает лишь шаблон. 

Сайт относительно популярный (около 1000 уников в день). Есть проблемы со спамом. Уже придумали что-то типа спам-бота, который с разных ip-адресов регистрирует  сотню комюзеров с рандомными никнеймами, емейлами и в поле "сайт" вбивают ссылки на сайты. Это продолжалось около месяца, потом перестали. Но кто и зачем это делает? Ведь адрес сайта нигде не фигурирует (кроме комментариев и персональной страницы пользователя), но комментарии проходят только через модерацию, а персональные страницы по-дефолту не индексируются. Я думаю, что это решиться с добавлением на страницу регистрации капчи, а лучше полностью заменить стандартную капчу на так называемую Re Captha (если конечно в новой версии движка этого нет). 

Это так, мои рекомендации)

**Comment by maxsite** [comment]
Капчу можно сделать отдельным плагином. Делайте новый тикет, возможно кто-то и возьмётся. ;-)

Про спам интересны подробности. Что за спам-бот?

**Comment by Anchovys** [comment]
Просто пачками в день регистрирует комюзеров с рандомными именами и емейлами, при чем с разных ip адресов и в поле "сайт" вбивают ссылки на сайты сомнительного содержания (что-то типа казино какого-то). Я запрещал доступ по ip, но каждый раз ip адреса меняются. Видимо какой-то скрипт уже придумали, либо руками так забивают. Причем дата и время регистрации отличается на доли секунды. Т.е явно автоматически все это происходит. Это 100% решиться добавлением капчи на страницу регистрации. Это все, что мне известно :)

**Comment by maxsite** [comment]
Мы вроде бы эту проблему прикрыли в сентябре. Как раз с помощью капчи.

**Comment by Anchovys** [comment]
Это хорошо. Вообщем загадка. Не могу войти под админа на сайте, который лежит на поддомене и подключен к БД главного. Что это может быть? Когда пытаюсь войти, пишет - неверный пароль.  Скидываю БД на ту, на которой регистрировал сайт - все гладко. P.S пароль и логин админа на обеих БД одинаков.

В БД случаем не прописывается что-то типа URL-адреса, на котором устанавливался сайт? И если я в дальнейшем перенесу весь движок в корень(без поддомена) все заработает?
И это не должен быть кеш браузера, обновляю страницу с Ctrl F5 и чистил кеш браузера и заходил с разных браузеров.

Сейчас просто настраиваю сайт как основной на поддомене, а потом просто перенесу все в корень с заменой.

**Comment by maxsite** [comment]
Наверное секретная фраза разная.

**Comment by Anchovys** [comment]
Точно! Огромное спасибо!

**Comment by Anchovys** [comment]
В 0.86 она в **application/maxsite/mso_config.php**, а в 0.95?
