### ISSUE TITLE
Не могу установить Maxsite под OpenServer

### ISSUE THREAD

**Issue by Mikich221** [maxsite/cms#175]
В общем создал базу, в настройках выставил Apache 2.4 php 5.5, все вроде нормально, но установка не запускается, вообще ничего не происходит. Что я делаю не так?
P.S. Решил поставить на хостинг сначала и подцепить к существующей базе, выдает вот такое, перечень несколько таблиц "Существующая таблица: mso_groups". Что это значит?

**Comment by maxsite** [comment]
Логи ошибок смотрите.

**Comment by Mikich221** [comment]
Нет там логов ошибок, не создались...

**Comment by maxsite** [comment]
Ну включите.

**Comment by Mikich221** [comment]
В общем такая вещь.. Если я создаю пустую базу, то инсталяция работает. Если я восстанавливаю базу с существующего сайта, то инсталяция не идет. Если восстановить базу после инсталяции, то в phpAdmin выдает вот такие ошибки "INSERT INTO `mso_cat2obj` (`cat2obj_id`, `page_id`, `category_id`, `links_id`) VALUES
(1200, 10, 25, 0),
(2, 0, 2, 1),
(1248, 71, 14, 0),
(1154, 3, 10, 0),
..................................
Ответ MySQL: 
#1062 - Дублирующаяся запись '2' по ключу 'PRIMARY' "
А на самом сайте только морда, страницы не открываются. У меня старые версии cms, может это как то влияет...

**Comment by maxsite** [comment]
Инсталяция это и есть установка в пустую базу.

**Comment by Mikich221** [comment]
Ясно, просто очень давно не занимался всем этим, забыл уже что да как... А что с ошибками? Как-то будет влиять на работоспособность сайта?

**Comment by maxsite** [comment]
Гадательный эликисир закончился... Опишите проблему подробно. Со всем шагами.
