### ISSUE TITLE
Задачи по переходу на https

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#176]
Сделаю единый тикет для задач по использованию https на MaxSite CMS.

Здесь следует отметить, что проблемы могут быть именно из-за перехода на новый протокол. Гугл слишком настойчиво всех пересажиывает на https, поэтому нужно предумотреть подводные камни. Если сайт работал на http, а теперь на https, то возникает несколько проблемных мест. 

Это может быть ка отдельный плагин, так и уровень шаблона.

1. В текстах записей используются абсолютные ссылки с http.

Решение. Сделать автоматические замены `http://` на универсальный `//`.

2. Канонические ссылки. Будут показываться в том протоколе, на котором работает сайт. Для гугла http и https — разные адреса, поэтому неизбежно возникнут дубли. Хотя, возможно, что гугл сам разрулит этот момент и перестроит поисковый индекс на новые https-адреса.

Решение. Пока не ясно. Указывать адрес без протокола нельзя.

3. Карта в sitemap.xml (плагин xml_sitemap). 

Решение. Узнать можно ли в этом файле указывать адреса без протокола? Если да, то сделать замены. Если нет, то вынести опцию в настройки плагина, чтобы принудительно менять протокол.

4. Адреса вне текста записи в HTML-коде.  Проблемная зона — секция HEAD. Часть адресов можно смело заменить на «без протокола». Часть, вроде канонических ссылок, нужно оставить как есть. Script (подключение) можно заменить на «без протокола». 

Решение. В LPF я давно уже использую функцию `mso_remove_protocol()`, которая прекрасно работает внутри BODY. Для HEAD потребуется более сложные замены чтобы явно указывать где можно менять, а где нельзя. То есть это какие-то опции должны быть.

**Есть какой-то способ тестировать локалхост https-сайт на Open Server?**

**Comment by vimruler** [comment]
OpenServer сам подхватывает https, там самоподписные сертификаты. Главное, чтобы сайт был настроен на https, т.е. был редирект с http на https.

Есть ещё одна задача - в админке блок информации о версии ругается, что идёт обращение к max-3000.com по http, а не по https

**Comment by maxsite** [comment]
Точно, спасибо! Почему-то думал, что нужно какие-то опции менять. :-)

Сайт max-3000.com работат по http, поэтому как тут сделать другой адрес неясно.

**Comment by maxsite** [comment]
Внес изменения в систему и default-шаблон. Появилс новая опция Использовать универсальный http-протокол, которая делает нужные замены. В xml_sitemap тоже опция по выбору протокола. К сожалению без него нельзя отдавать адреса.
