### ISSUE TITLE
Вид страницы отличается от вида на предпросмотре

### ISSUE THREAD

**Issue by uverg** [maxsite/cms#177]
Установлена версия MaxSite CMS: 0.959 (последняя на 31.01.2017 г.)
При редактировании текста, если не указать теги [p][/p], весь текст "лепится" в один абзац. Страницы созданные на пред. версии отображаются корректно, хотя там тегов [p][/p] нет. Если старую страницу отредактировать и сохранить, структура по абзацам также ломается. Приходится добавлять [p][/p]. При этом предпросмотр отображает все нормально.

**Comment by maxsite** [comment]
Плагин парсера включите.

**Comment by uverg** [comment]
Спасибо.
