### ISSUE TITLE
не могу залогиниться администратором

### ISSUE THREAD

**Issue by justman4** [maxsite/cms#178]
Сайт http://www.sculptor88.com/articles/ работает нормально.  Но не пускает в админку, говорит Неверный логин/пароль, а ф-я восстановления пароля - емейла не находит. 
Ставил последнюю версию макссайта с нуля, проработала около 2 недель. 
Комюзером залогиниться можно.

Что делал:
1. Чистил кеш браузера
2. Менял пароль(хеш) для админа
3. Менял версии ПХП на хостинге.
НЕ помогло.

Из ошибок в логах апача, только:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php56/lib/php/extensions/no-debug-non-zts-20131226/php_imap.dll' - /usr/local/php56/lib/php/extensions/no-debug-non-zts-20131226/php_imap.dll: cannot open shared object file: No such file or directory in Unknown on line 0, referer: http://www.sculptor88.com/articles/admin/

Что может быть, куда смотреть?
Заранее спасибо за помощь!

**Comment by maxsite** [comment]
Для админ-панели нужно вводить логин и пароль. Если меняли секретную фразу, то пороль нужно новый задавать через базу. Восстановления через сайт нет (из-за безопасности), 

Сделайте в главном каталоге сайта файл **pass.php** такого содержания:

` <?= strrev( md5('новый пароль' . 'секретная фраза из application/maxsite/mso_config.php') );`

и перейдите через браузер. Появится шифрованная строка, которую нужно через phpMyAdmin внести в таблицу **mso_users** в поле **users_password** соответствующего логина.

После всех операций  **pass.php** нужно удалить.

**Comment by justman4** [comment]
спасибо! 
Эту манипуляцию я уже делал (описал в 1м своем посте как "менял пароль(хеш) для админа"). Да и секретную фразу не менял...
Что еще может быть?

**Comment by maxsite** [comment]
Может браузер куки не сохраняет? Адреса www и без разные.

**Comment by justman4** [comment]
может и с куками... Но браузер куки принимает!
От сайта есть свежие куки "ci_session", а если ходить по страницам блога - "maxsite-cms". 
Что еще заметил:
Если входить со страницы /blog/login - то после ввода логина/пароля загружается блог с записями возле которых есть иконка "Редактирование" (на иконке ссылка вида /blog/admin/page_edit/1"), в меню появляется "Админ-панель maxsite" (с выпадающим списком: создать запись, список записей и т.д.), а внизу "Привет, admin! Выйти". Т.е. могу сделать вывод что логин прошел успешно. 
Но при клике по любой ссылке из меню Админ-панели maxsite, например "Опции сайта" (/blog/admin/options) или при попытке отредактировать запись блога - опять выдается логин форма на синем фоне. Если здесь ввести логин/пароль - перекидывает на страницу /loginform/error с ошибкой. 



![ms_login](https://cloud.githubusercontent.com/assets/25510381/23076399/fa18b106-f548-11e6-99b6-742f7a590231.jpg)
![ms_login2](https://cloud.githubusercontent.com/assets/25510381/23076400/fa1b60cc-f548-11e6-8a43-54923e071079.jpg)
![ms_login3](https://cloud.githubusercontent.com/assets/25510381/23076401/fa1eda5e-f548-11e6-848a-37f9c3578dd7.jpg)

**Comment by maxsite** [comment]
Все адреса с www? В другом браузере пробовали?

**Comment by justman4** [comment]
да, все адреса с www, в другом браузере (FF) тоже самое.

**Comment by maxsite** [comment]
Пароль только из цифт и букв?

**Comment by justman4** [comment]
да, в пароле только есть цифры и буквы, латиницей.

**Comment by maxsite** [comment]
Тогда либо неверный логин и пароль. Либо что-то с куками (нужно почистить). Других вариантов я не вижу.

**Comment by justman4** [comment]
спасибо, Максим! скорее всего что-то с куками тогда...

а за вознаграждение можете помочь системе нормально работать на нашем хостинге? если да, отпишитесь пожалуйста на justman4spam@gmail.com

**Comment by maxsite** [comment]
Лучше вы мне. :)
