### ISSUE TITLE
Хелп по редактору и bb-кодам

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#180]
Нужно переделать html-файл который сейчас в `bbcode/bbcode-help.html` и вызывается из текстового редактора. 

Поменять дизайн. Убрать тени, лишний фон. Привести примеры использования как положено. 

Привести в полное соответствие с текущими возможностями bb-кодов.

Есть желающие взяться?

**Comment by Fafofu** [comment]
Хм. Ща глянем :)

**Comment by Fafofu** [comment]
Может взять вот этот и дополнить? http://escort.sso.ru/html/bbcode.html

**Comment by maxsite** [comment]
Проще с нуля сделать. Нужно использовать текущие возможности плагина.

**Comment by Kotgo** [comment]
`<style>
		body{color:#333; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; background: none; margin: 0; padding: 0;}
		table{padding: 20px; margin:0 0 40px 0; border-spacing: 0px; border:1px dashed #dcdcdc; border-radius: 7px; background: #fbfcfd; width: 940px;}
		th{background: #deedc8; text-align: left; font-size: 110%; padding:4px;}
		td{padding:4px; border: 1px dashed #dcdcdc}
		span{color: #1a80ec; text-shadow: 1px 1px 3px #fff; font-weight: 700;}
		i{color: #006f01; font-style: normal;}

		#main{width: 940px; margin: 20px auto; padding: 20px; background: white; border-radius: 7px; border: 11px #ddd solid; box-shadow: 0 0 7px #ffff;}
		.zagolovok{font-size: 24px; text-align: center; border-bottom: 2px solid #777; padding-bottom: 20px; margin-bottom: 40px; text-shadow: 1px 1px 3px #fff;}
		.podzagolovok{font-size: 20px; text-shadow: 1px 1px 2px #fff; margin: 0 0 10px 0; color: #556b2f;}
		.kurs{font-style: italic; color: #333;}
		.primer{padding:0 20px; margin:0; border:1px dotted #dcdcdc; border-radius: 7px; background: #deedc8; box-shadow: 1px 1px 3px #fff;}
	</style>`

**Comment by Kotgo** [comment]
Фон убрал, тени убрал, дизайн не трогал, нормальный не раздражает, по остальному не знаю как делать.

**Comment by Kotgo** [comment]
Подскажите, а где вообще актуальный BB-code по которому равняться нужно? И как исходный код HTML в редакторе проверять?

**Comment by maxsite** [comment]
Нужно сделать с нуля, а не переделывать. Основа плагин BBCode — там все коды и есть примеры и описания. Нужно их нормально оформить хелпом.

**Comment by Kotgo** [comment]
Максим, а есть сторонние примеры оформления, как надо оформлять? А нынешние описания уже не актуальны?

**Comment by maxsite** [comment]
Оформлять как документацию. :-) Некоторые старые описания немного устарели. Сейчас для многих bb-кодов используется единый подход, поэтому нужно это отразить. В общем см. BBCode.

**Comment by Kotgo** [comment]
Максим, а не проще сделать визуальный редактор и плюс к нему возможность вставлять HTML с небольшим количеством BBcode для опасного содержимого. 
Прочитал про BBcode и выходит то, что это изменённые тэги HTML для того чтобы плагин их преобразовал в HTML. И не пойму смысла зачем они нужны когда можно вставить HTML код кому нужно, а остальное визуально в редакторе править. 

А так выходит нужно знать HTML чтобы понять что означает BBcode, тогда зачем нужен  BBcode , когда лучше учить HTML ???

**Comment by maxsite** [comment]
Не проще. BBcode для того и нужен, чтобы не работать с html.

**Comment by Kotgo** [comment]
До сих пор не понял как с помощью BBcode сделать трехколоночный адаптивный макет и не используя Flex изUniCSS? Или как задействовать в редакторе Flex изUniCSS , когда нет возможности вставить HTML код в макет страницы. Также BBcode центрующий абзац не центрует его. Приходится сидеть и думать какой BBcode подходит нужному тегу HTML и как к нему прописать стили для одной страницы. Плюс чтобы толком что то оформить на странице, приходится сохранять страницу и просматривать её получившийся код на базе BBcode. Размер он увеличивает почему-то только у первой строки, хотя ставишь на весь текст в колонке. Очень сложно оформлять это всё выходя за обычные рамки не оформленного текста и не удобно, используя BBcode . Моё мнение из личного опыта. Возможно, кому-то нравится, писать статьи как на обычном форуме без дополнительного оформления.

**Comment by Kotgo** [comment]
Я бы взялся за это оформление, если бы этот BBcode действительно был удобен и эффективен для гибкого оформления страниц. Но здесь по другому выходит , кроме 

> цитирования

 и **выделения жирным** и _курсивом_ больше ничего не подходит для того, чтобы как хочется сделать и начинает напрягать, когда всё не так как хотелось бы получается в конечном итоге. 

Поэтому предложил улучшить визуальный редактор до визуальности оформления (для тех кто не знает HTML и вряд ли поймёт BBcode) и возможности вставлять HTML код при оформлении страницы и править его.

А так, даже Хелп по BBcode не поможет, как его не оформляй. Личный опыт.

**Comment by maxsite** [comment]
Возможности плагина bbcode достаточно большие и они не отражены в текущем хелпе. Если вы не можете разобраться с плагином, то как вы собираетесь делать хелп? Я понимаю, что вы хотите помочь, но в данном случае нужна такая помощь при которой я не буду объяснять самые азы. :-)
