### ISSUE TITLE
Новые Загрузки

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#181]
Планирую полные переделки страницы Загрузок. Основа будет та, что сейчас при редактировании записей.

Останется навигация по каталогам, плюс нужно как-то продумать отдельную навигацию (выпадающий список select) для _pages, чтобы можно было явно зайти в каталог записи.

Нужно будет как-то решить вопрос с удалением файла. Там аякс и с этим сложности, нужно какой-то чекбокс вводить и кнопку удалить. В идеале я бы хотел удаление файлов и на страницу записи вынести (хотя бы по-одному).

Описание файла предлагаю удалить полностью. Практика показала, что оно и не нужно. Для [IMG] проще явно указать текст в записи, чем вводить его при загрузке. Тем более это сложно сделать при множественной загрузке.

Генерацию кода галерей нужно вынести в отдельный блок и подключать по хуку, чтобы перенести функционал на уровень плагина. Проблема в том, что для разных галерей требуется разный результирующий код и пусть сам плагин его и формирует.

Ватермарка — пока не всё решил. Текущий вариант точно должен остаться, но есть возможность формировать текстовую ватермарку. Скажем указывается текст, размер, цвет и положение на фото. Правда пока не ясно как делать обводку для оформления и прочие визуальные эффекты. Так же есть идея ставить разные ватермарки из списка файлов предопределенного каталога. И по ватермаркам вроде как есть проблема их масшабирования для малых изображений. Тут можно испльзовать разные ватермарки для разных размеров. Например для больших одна, мелких — другая. Впрочем я с такой проблемой не сталкивался, возможно она надумана.

Загрузку по url пока склонен не делать. Во первых — из соображений безопасности, во-вторых функционал не будет реально затребован, в третьих — это можно сделать простыми манипуляциям мышкой в несколько кликов.

**Comment by vimruler** [comment]
Нравится всё.

> Описание файла предлагаю удалить полностью. 

Согласен, что не нужный перегруз.

**Comment by Furnicarium** [comment]
1. разные ватермарки для разных размеров это излишне, Никогда не видел, чтоб нужно было ставить на мелкие картинки их, лучше просто не ставить, т.к. и так маленькие. т.е. если надо, то сделать условие, где меньше 100рх - не ставить.
2. очень приятно, что ты думаешь о безопасности, но функция загрузки по ссылке нужна хотя бы в виде опции, где надо её использовать только там, где доверяешь. Зачастую загрузить по ссылке это намного проще и быстрее, чем искать нужную картинку на компе. 
3. Описание файла мне как раз необходимо, иначе какой смысл публиковать что-то, если его не найдут через поиск.
4. вот сделать бы загрузку прям в новый пост, это задача.
