### ISSUE TITLE
favicon в админке

### ISSUE THREAD

**Issue by Avishgreen** [maxsite/cms#182]
фавикон в админке всегда стандартный, вне зависимости от выбранного в настройках для сайта. Это не удобно когда открыты несколько админок разных сайтов. Не знаю правда, баг это или фича? Версия 0.96

**Comment by maxsite** [comment]
Ну да, там одна фавиконка. Ну а как её менять?

**Comment by Avishgreen** [comment]
логично было бы показывать ту же фавикон, что и на пользовательской стороне сайта. Мы же в админке указываем какую фавикон отображать? Оттуда и брать данные

**Comment by maxsite** [comment]
Ну да, сейчас это в админке. Раньше в шаблоне иконка была. Ок. Подумаю.
