### ISSUE TITLE
Мистическое исчезновение и возвращение частей страницы сайта

### ISSUE THREAD

**Issue by andr55** [maxsite/cms#184]
![404](https://cloud.githubusercontent.com/assets/25886797/23106585/9efa9a64-f700-11e6-883f-f6aa371be699.gif)
![4041](https://cloud.githubusercontent.com/assets/25886797/23106589/a9e6e0d6-f700-11e6-9223-33fed7b97a2f.gif)

Здравствуйте. Помогите разобраться с причиной мистического исчезновения разных частей страниц на сайте bel-jurist.com. PHP Version 5.2.17, MySQL 5.1.61-log - FreeBSD port: mysql-server-5.1.61.

Сайт находится на Maxsite CMS 0.77 с 2012 года у одного и того же хостера (виртуальный хостинг) и вообщем-то нормально работал до середины 2016 года. С тех пор все чаще стали возникать ошибки, связанные с частичной недозагрузкой частей страниц (см. логи - http://www.host-tracker.com/Stat/Daily/29eca114-714f-e611-80c1-0003ff733473 )

Как правило, исчезает только контент страницы, а шапка, сайдбар и футер остаются. Ошибка может захватывать только главную страницу или все страницы сайта одновременно. Я сделал 2 скрина главной страницы, как это выглядит. Ошибок в БД нет (когда в БД слетела однажды таблица, на сайте я увидел белый лист с php fatal error). Отключение кэширования страниц на сайте с помощью штатного плагина ничего не меняет.

Заметил также, что когда на bel-jurist.com исчезает блок контента, на соседнем друпаловском сайте аккаунта может пропадать сайдбар.

Файлы проверял Айболитом, ничего подозрительного не нашел.

Подскажите, пожалуйста, в чем может быть причина и какими способами ее подтвердить/опровергнуть на виртуальном хостинге?

**Comment by maxsite** [comment]
Тут однозначно проблемы с хостингом. Недоступность по 7 часов в сутки довольно красноречиво об этом говорит. Лучше спростить у хостера, возможно какие-то работы или что-то сломалось на сервере.

**Comment by andr55** [comment]
Ошибка 404 выдается из-за того, что не загружается главный контент страницы, но видимых ошибок на сайте нет. И проблема случается преимущественно по ночам. Хостер отвечает, что повышенной нагрузки на сервере сайта и серверах БД нет и предлагает только восстановить сайт из бэкапа. У меня подозрение, что отваливается передача данных по сети между сервером и сайтом. Вы можете что-нибудь посоветовать, каким образом идентифицировать, на каком участке проблема?

**Comment by maxsite** [comment]
База отваливается. Идет например создание бэкапа, в это время и глючит. Тыкните хостеру ссылка на аптайм, пусть объяснит почему сервер по нескольку часов в сутки недоступен. В любом случае это решать с хостером.

**Comment by andr55** [comment]
В техподдержке сами не знают, ведь явных ошибок на сайте нет и сам сайт в целом грузится.  Предлагают только восстановить из бэкапа. Максим, а в каком месте CMS происходит получение основного контента страницы из БД и отдача заголовков? Я бы попробовал эти функции скопировать и запустить отдельно, чтобы посмотреть результат.

**Comment by maxsite** [comment]
Вопрос некорректный. У нас множество запросов к базе. Используйте phpMyAdmin, чтобы убедиться в наличии записей в таблице mso_page в тот момент, когда их на сайте нет. Тогда возможно вам удастся отловить момент нарушения работы.

**Comment by andr55** [comment]
Спасибо вам, Максим, за хорошую идею. Сегодня днем сайт заново упал в ошибку 404, а на соседнем пропал сайдбар. Зашел в phpMyAdmin и стал смотреть. Размер базы - нормальный, автоматическая проверка всех таблиц выдала "ОК", даже экспортируется содержимое БД нормально, но когда попытался просмотреть содержимое таблицы mso_page и некоторых других таблиц, то там ничего не было (сделал скриншот). Написал хостеру, и вскоре сайт заработал, а содержимое таблиц стало возможным посмотреть. Теперь я буду знать, кого пинать.
![2](https://cloud.githubusercontent.com/assets/25886797/23166696/abddbaec-f852-11e6-9539-033379d40c4e.gif)

**Comment by andr55** [comment]
Из саппорта еще ответили: 
 Проблема действительно присутствовала, сегодня наши администраторы устранили ее, повториться не должно.

**Comment by maxsite** [comment]
Ну и хорошо. :)
