### ISSUE TITLE
Гостевая книга - спам

### ISSUE THREAD

**Issue by DizeLyaka** [maxsite/cms#185]
Приветствую всех. Спамеры заваливают сообщениями "Гостевую книгу" - капча не помогает. Сообщения проходят модерацию, но от этого легче не становиться.
Прошу помощи!

**Comment by maxsite** [comment]
Так если это ручной спам, то уже ничего не поможет.

**Comment by DizeLyaka** [comment]
Скорей всего капча распознается легко. Может как-то можно её усложнить?

**Comment by maxsite** [comment]
Зачем?

**Comment by DizeLyaka** [comment]
Капча легкая. Может необходимо усложнить ее распознавание ботами.

**Comment by maxsite** [comment]
Вы уверены что это боты?

**Comment by DizeLyaka** [comment]
Не уверен, но спам "сыплется" часто, с разных IP-шников, с разным содержимым и на разных языках! Даю скрин:
![1](https://cloud.githubusercontent.com/assets/25928283/23201924/742474be-f8e4-11e6-8206-b0c9cf23f188.jpg)

**Comment by maxsite** [comment]
Больше похоже на ручной спам. Попробуйте поменять адрес гостевой. После этого по логам смотрите какие http-запросы идут. Если на старый адрес и POST, то может и бот. Если по новому, то с большой вероятностью это ручной спам, там капча не поможет.

**Comment by DizeLyaka** [comment]
Спасибо, попробую.

**Comment by DizeLyaka** [comment]
Сменил адрес гостевой- поток спама уменьшился, но не до конца - есть подозрение на "ручной" спам.

**Comment by maxsite** [comment]
Может как-то прикрутить к гостевой антиспам в виде списка запрещенных слов и ссылок...

**Comment by DizeLyaka** [comment]
Нашел обзор 5-ти методов антиспама: https://www.michel-kraemer.com/5-anti-spam-measures-for-phpbb3/

**Comment by Kotgo** [comment]
А плагин с выбором картинок пробовали включать активировать? 

mkj_sc 0.3 |   | Капча SimpleCaptchasecurity | Простая капча - выбрать из трёх рисунков 

Сам не пробовал.
