### ISSUE TITLE
Кириллица в метках (tag) и поиске (search)

### ISSUE THREAD

**Issue by 4ppl** [maxsite/cms#186]
Добрый день.
Сайт работает на связке IIS 10 + php 5.3 + php 5.6 + MaxSite CMS 0.96
URLRewrite включен, .htaccess в корневом каталоге сайта импортирован в web.config
Ситуации, приведенные ниже по тексту, воспроизводились на:

- Win 10 + Microsoft Edge
- Win 7 + Opera 43
- Debian 8 + Firefox 45.7.0 (скриншоты сделаны на этом рабочем месте)

Опубликовал пару записей, сопроводив их метками (часть меток на латинице, часть на кириллице).

При клике по любой метке из облака, сформированного плагином tagclouds v1.2 (_метка (tag) на кириллице; не имеет значения из скольких слов состоит метка_), всегда получал результат 404:
![image](https://cloud.githubusercontent.com/assets/26070089/23375965/63f0bafc-fd3b-11e6-93ac-f738e3021e98.png)
![image](https://cloud.githubusercontent.com/assets/26070089/23375987/7b86afb4-fd3b-11e6-8923-a1798f2e4214.png)

При поиске любого слова на кириллице (заведомо имеющегося как в тексте заметки, так и в метках):
Заголовок сайта уже состоит не из ромбиков, но все так же результат поиска - страница 404:
![image](https://cloud.githubusercontent.com/assets/26070089/23376055/ca70027e-fd3b-11e6-8c44-77e77f8fb3bb.png)

Исправить удалось внеся правки в файлы:

- \application\maxsite\common\common.php (блок: типовое определение канонического адреса)
- \application\maxsite\common\page.php (блок: страница меток)
- \application\maxsite\shared\type\tag\tag.php (блок: meta title страницы, h1 class="mso-tag")
- \application\maxsite\shared\type\search\search.php

заменив код **`mso_segment(2)`** на **`htmlspecialchars(urldecode(iconv('windows-1251', 'utf-8', mso_segment(2))))`**

Переходы по кириллистическим меткам после исправлений работают, поиск тоже. Заголовок страницы (и содержимое тегов title, canonical - в порядке, ромбиков с вопросами нет :))

Прошу прокомментировать эти ошибки и вариант исправления.

**Comment by 4ppl** [comment]
**UPD.**
для канонического адреса (файл \application\maxsite\common\common.php) решение не подходит, т.к. ссылка имеет вид:
**`<link rel="canonical" href="http://*********.***/tag/интерфейс клиентского приложения">`**
что недопустимо с точки зрения валидности html:
![image](https://cloud.githubusercontent.com/assets/26070089/23380793/39704466-fd4d-11e6-9605-7e21119d097c.png)

В данном случае нужна обратная операция - кодирование строки (как это делается в плагине tagclouds):
**`$url = getinfo('site_url') . mso_segment(1) . '/' . urlencode(mso_segment(2));`**
т.о. канонический адрес становится валидным:
**`<link rel="canonical" href="http://*********.***/tag/%E8%ED%F2%E5%F0%F4%E5%E9%F1+%EA%EB%E8%E5%ED%F2%F1%EA%EE%E3%EE+%EF%F0%E8%EB%EE%E6%E5%ED%E8%FF">`**

**Comment by maxsite** [comment]
IIS — это спортивный интерес или неизбежная необходимость? ;-)

Поскольку у нас utf8, то все запросы автоматом url-кодируются/декодируются. На уровне сервера массив $_GET должен быть автоматически декодирован, поэтому к нему недопустимо применять повторную декодировку. Что вы и сделали.

Поскольку у вас сервер работает в win-1251, то наверное где-то в его настройках можно указать правильную кодировку сайта (utf-8), или возможно, как-то заставлять сервер выполнить url-декодирование суперглобальных массивов.

**Comment by 4ppl** [comment]
IIS - был выбран ради спортивного интереса - в "песочнице" обкатываю совместную работу сайта и web-клиентов 1С (в которых используется доменная аутентификация и прочие windows-плюшки :-) ). 
Спасибо за ответ, благодаря ему стало понятно куда "копать". Если найду решение как принудить ISS нормально работать с utf-8, оставлю сообщение в этой теме.

**Comment by 4ppl** [comment]
Решение нашлось тут: https://support.microsoft.com/ru-ru/help/820129/http.sys-registry-settings-for-windows
а именно параметр **FavorUTF8 = 0**, добавленный в реестр, позволил вернуть весь код в первоначальное состояние, при этом переходы по кириллистическим меткам работают, поиск тоже, заголовок страницы без "ромбиков". Остался один вопрос: ссылка канонического адреса для страницы, сформированной при переходе по метке имеет вид:
<link rel="canonical" href="http://*********.***/tag/интерфейс клиентского приложения">
что является ошибкой при проверке валидности html:
![image](https://cloud.githubusercontent.com/assets/26070089/23404902/70b5de24-fdc8-11e6-86b8-cae7145e6901.png)
Если не затруднит - поясните, какие могут быть "неприятности" от этого эффекта при взаимодействии с роботами гугла, яндекс метрики? В плагине "XML карта сайта" я на всякий случай отключил пункт "Добавить страницы меток" и в файле sitemap.xml ссылок на страницы меток нет.

**Comment by maxsite** [comment]
По правилам в адресе не должно быть пробелов, да и вообще всех «не-английских» символов. Однако на практике кодировка utf8 позволяет не выполнять кодирование «не цифробуквенных символов» в вид «%XX», кроме тех которые явно используются для формирования URL (вроде «/»). Насколько я понимаю, то правильным будет всё-таки полное кодирование второго сегмента. 

В common.php в строчке 3680 (функция mso_link_rel) нужно изменить строчку так:

```php
$url = getinfo('site_url') . mso_segment(1) . '/' . urlencode(mso_segment(2));
```
Проверьте, я также внесу изменения у себя.

**Comment by 4ppl** [comment]
Спасибо! Вопрос считаю закрытым 👍
