### ISSUE TITLE
На шаг впереди (загрузки в черновик)

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#187]
Известна проблема с загрузками, а именно, эта функция работает лишь при **редактировании** поста, т.е. для того, чтобы опубликовать пост с картинкой, мы вынуждены его редактировать, а это лишние движения, от которых можно избавиться. Причина в том, что пост уже должен быть создан, чтоб движок знал, в какой именно пост цеплять картинку.
Очевидным решением напрашивается такой метод - всегда иметь в запасе 1 скрытый пост, отмеченный как черновик. Когда пользователь будет создавать новый пост, на самом деле он будет редактировать существующий черновик, в который УЖЕ является возможным загружать картинки. При нажатии на кнопку "опубликовать" пост из скрытого становится открытым и в то же время создаётся новый пустой скрытый черновик.
Как вам такая идея?

**Comment by maxsite** [comment]
Даже черновик имеет ID. Пока запись не создана, то ID не существует. Таким образом нет возможности предугадать действия пользователя. Может он просто закроет и не будет создавать  запись.

**Comment by maxsite** [comment]
Сделал так. По-умолчанию опция «Вернуться к редактированию» будет отмечена. Также я добавил новую опцию в Основных настройках «Статус новой записи по-умолчанию». Ставим её как «Черновик».

Теперь идём в `Создать запись`. Вводим заголовок и жмём Enter. Запись создана и доступна для редактирования включая и загрузку файлов.
