### ISSUE TITLE
Проблема с наложением водяного знака

### ISSUE THREAD

**Issue by Taishet24** [maxsite/cms#188]
Добрый день! Я в системе всего несколько дней. Осуществить настройку под требуемые параметры и решить ряд существующих проблем помог Илья Земсков.

Есть одна сложность, с которой он рекомендовал обратиться сюда.

Создал файл watermark.png и в соответствии с инструкцией положил его в uploads (http://narod.taishet24.ru/uploads/watermark.png).

Далее при загрузке изображения ставлю галочку "Для изображений установить водяной знак", выбираю файл, нажимаю "Загрузить".

Вверху страницы появляется текст:
A PHP Error was encountered
Severity: Warning
Message: imagecopymerge() expects parameter 9 to be long, string given
Filename: libraries/Image_lib.php
Line Number: 955

При этом сама картинка загружается, но без водяного знака.

Каким образом решается этот казус?

Спасибо.

**Comment by maxsite** [comment]
Пока не ясно. Проверяю свой файл — проблем нет. С вашим — есть. Буду разбираться.

**Comment by Taishet24** [comment]
Пока не разобрались?

**Comment by maxsite** [comment]
9 days ago.
