### ISSUE TITLE
Проблема с mso_get_pages

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#189]
Максим, после обновления с 0.95 до 0.961 как-то странно отвалились на главной странице юниты, в которых шло получение контента записей через такой код:

```php
$pages = mso_get_pages(
	array( 
		'page_id' => trim($UNIT['page_id']),
		'show_cut' => false,
		'show_xcut' => false,
		'type' => false,
		'page_status' => false, # не обращать внимание на статус записи
		'custom_type' => 'home',
		),
	$pagination
)
```

Причём раньше всё работало, а сейчас запись не находилась.

Поиски привели в функцию **_mso_sql_build_home** во фрагмент:

```php
// экранирование CodeIgniter! Приходится делать свои замены! 
if ($r['page_id']) 
{
	$CI->db->order_by('FIELD('page_id_MSO_ZAP_' . implode('_MSO_ZAP_', $r['page_id']) . ')');
}
else 
{
	if ($r['order']) 
		$CI->db->order_by($r['order'], $r['order_asc']);
}
```

Его отключение восстанавливало работу функции mso_get_pages. Дальнейшие разбирательства прояснили, что в работу отправлялся sql-запрос, фрагмент: 

> ORDER BY FIELD(page_id,1) 

Который приводил к ошибке mysql "#1052 - Column 'page_id' in order clause is ambiguous"

Как я понял, это из-за того, что mysql не знал к какой таблице относится поле page_id (CI почему-то не подставлял информацию о таблице при компиляции sql). Я поправил код на такой:

```php
$CI->db->order_by('FIELD('.$CI->db->dbprefix.'page.page_id_MSO_ZAP_' . implode('_MSO_ZAP_', $r['page_id']) . ')');
```

Ошибка исчезла, юниты заработали нормально.

Что это за магия такая - хз. Как раньше работало - тоже не ведаю. Оставляю это на всякий случай здесь, вдруг у кого-то повторится проблема, так хоть времени на поиски сэкономите...

**Comment by maxsite** [comment]
Странно, вроде не должно быть коллизий. Попробуй проверить с убранным префиксом:

`$CI->db->order_by('FIELD(page.page_id_MSO_ZAP_' . implode('_MSO_ZAP_', $r['page_id']) . ')');`

**Comment by vimruler** [comment]
> Попробуй проверить с убранным префиксом:

Я и сам такой вариант пробовал, а сейчас попробовал снова - не работает.

**Comment by maxsite** [comment]
Странно это. Попробую разобраться.

**Comment by vimruler** [comment]
Сейчас обновил ещё один сайт - та же ситуация. Обновлялся с dev-ветки.

**Comment by maxsite** [comment]
Я смог воспроизвести проблему. Достаточно указать номер записи для главной и записи не выводятся. Причем сам sql-запрос без ошибок. Но твоё предположение скорее всего верное. Пока играюсь с именованием.

**Comment by maxsite** [comment]
Илья, ты прав. Похоже когда-то упустили префикс. Вот рабочаа строчка. То что ты написал, только добавил экранирование для порядка:

```sql
$CI->db->order_by('FIELD(`' . $CI->db->dbprefix . 'page`.`page_id`_MSO_ZAP_' . implode('_MSO_ZAP_', $r['page_id']) . ')');
```

**Comment by vimruler** [comment]
> Причем сам sql-запрос без ошибок.

Да, в рамках работы движка запрос не вызывает ошибки. Просто выборка пустая возвращается. Ошибку я получал, когда тестировал весь откомпилированный запрос через HeidiSQL.

**Comment by maxsite** [comment]
Я думаю это какая-то нестыковка по версии MySQL. Этот код очень старый, а в новых версиях MySQL более строгий режим работы. Вот и вылезло...
