### ISSUE TITLE
Плагин "Голосования" (samborsky_polls)

### ISSUE THREAD

**Issue by dignityinside** [maxsite/cms#19]
Ошибка 1:
В "Защита от накрутки по-умолчанию" в выпадающем меню опечатка в слове "Coookies" (убрать одно "о")

Ошибка 2:
При нажатии на кнопку "Добавить новое" выходит Warning:

A PHP Error was encountered
Severity: Warning
Message: Creating default object from empty value
Filename: samborsky_polls/manage.php
Line Number: 254

**Comment by deeptenk** [comment]
Ошибка 2:
При нажатии на кнопку "Добавить новое" выходит Warning:

A PHP Error was encountered
Severity: Warning
Message: Creating default object from empty value
Filename: samborsky_polls/manage.php
Line Number: 254

Еще нет решения?

**Comment by maxsite** [comment]
Исправлено в последнем коммите.
