### ISSUE TITLE
Проблема с масштабированием изображения для записи

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#190]
Вводная.

Разрабатываю шаблон. Использую units.php для главной.
Мне необходимо сделать следующее - изображение для записи смасштабировать в 320px про ширине, но при этом высота чтобы изменилась пропорционально. Высота может быть произвольной.
Если thumb_height=0, то приходится отключать placehold, иначе просто получаю ошибку инициализации GDI, но оно так правильно и так и надо. 
Но вот картинка при этом выводится в размере 320х1
Есть вариант, как сделать, чтобы картинка масштабировалась пропорционально, а не обрезалась? 
Или это все гвоздями внутри прибито и только править код?

[unit]
file = last-blogs.php
type = blog
limit = 2
thumb_width = 320
thumb_height = 0
placehold = 0
pagination = 1
page_start = <div class="w48 w100-tablet pad20-rl mar15-tb bor1px bor-solid bor-gray400">
[/unit]

**Comment by maxsite** [comment]
Прибито внутри. Здесь работа происходит через функцию thumb_generate() и всегда используется метод resize_full_crop_center. Поэтому и нужно всегда указывать высоту и ширину. Менять этот метод вобщем-то никогда потребности и не было, поскольку само по себе масштабирование изображения работает через CSS.

Теоретически возможно создать опицю для любого метода генерации (в last-pages.php), но там придется как-то выкручиваться с именем файла: сейчас он строится на основе width и height.

**Comment by Den2016** [comment]
А если из stock скопировать thumb & page-out в шаблон и подправить вызовы в самом шаблоне - какие грабли можно оттоптать?

**Comment by maxsite** [comment]
Только те, что вы сами создадите. :)

**Comment by Den2016** [comment]
логично ))

**Comment by maxsite** [comment]
Если не срочно, могу поставить как задачу. Она хоть и специфичная, но не очень сложная.

**Comment by Den2016** [comment]
Было бы неплохо, потому что сильно на этом споткнулся.
