### ISSUE TITLE
Превью картинок в редакторе записи.

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#191]
При редактировании записи в списке изображений записи отсутствует превью, стандартный document_plain.png и все. В то же время в "Управление файлами" превью есть. Было бы хорошо сделать и в редакторе так же, чтобы визуально видеть, какую картинку куда вставлять. И еще совсем здорово, чтобы по кнопкам URL/[img]/[image] формируемый текст вставлялся в текущее положение курсора редактора.

**Comment by Den2016** [comment]
О! оказывается уже вставляет. Только URL выводит диалоговое окно. )) Эта часть снимается ))

**Comment by maxsite** [comment]
Чего-то я ничего не понял...

**Comment by Den2016** [comment]
лучше один раз увидеть https://imgdepo.com/show/10476397

**Comment by maxsite** [comment]
Превью итак делается автоматом, если это картинка.

**Comment by Den2016** [comment]
ну я ж с рабочего сайта снял скрин, система установлена с нуля. Может, я не так выразился, но в редакторе не видно изображение загруженных файлов. Первый скрин - собственно редактирование записи, второй скрин - результат нажатия на "Управление файлами". То есть, если для записи загружено несколько изображений, то уже визуально не видно, где какая картинка.

**Comment by maxsite** [comment]
Превью может не создаваться из-за проблем на сервере. Проверяйте права на каталоги.

**Comment by Den2016** [comment]
всё чудесатее и чудесатее... Полез смотреть права. С ними вроде все нормально, но вылез другой прикол - создал новую запись, все путем, каталоги имеют 0777, загрузил пачкой несколько файлов и
```
# ls -l -R ./uploads/_pages/21
./uploads/_pages/21:
итого 588
-rw-rw-rw- 1 apache2 webmaster 117684 апр  1 09:14 111.png
-rw-r--r-- 1 apache2 webmaster  50986 апр  1 09:14 11-702x340.jpg
-rw-r--r-- 1 apache2 webmaster  55676 апр  1 09:14 151-702x390.jpg
-rw-rw-rw- 1 apache2 webmaster  45159 апр  1 09:14 1.png
-rw-r--r-- 1 apache2 webmaster 215480 апр  1 09:14 2d4630948ed6abc2028b3eb1627d2878_1920x.jpg
-rw-rw-rw- 1 apache2 webmaster  94834 апр  1 09:14 2.png
drwxr-sr-x 2 apache2 webmaster   4096 апр  1 09:14 mini
drwxr-sr-x 2 apache2 webmaster   4096 апр  1 09:14 _mso_i

./uploads/_pages/21/mini:
итого 56
-rw-rw-rw- 1 apache2 webmaster 20877 апр  1 09:14 111.png
-rw-rw-rw- 1 apache2 webmaster 14066 апр  1 09:14 1.png
-rw-rw-rw- 1 apache2 webmaster 12812 апр  1 09:14 2.png

./uploads/_pages/21/_mso_i:
итого 28
-rw-rw-rw- 1 apache2 webmaster 9935 апр  1 09:14 111.png
-rw-rw-rw- 1 apache2 webmaster 6957 апр  1 09:14 1.png
-rw-rw-rw- 1 apache2 webmaster 5878 апр  1 09:14 2.png

```

для jpg превьюшек нет, только для png

копаюсь дальше...

**Comment by Den2016** [comment]
В общем, закрываю тему.
