### ISSUE TITLE
Ошибка Not Found The requested URL /login was not found on this server. 

### ISSUE THREAD

**Issue by Sundego** [maxsite/cms#192]
Добрый день! Скачал дистрибутив, распаковал, настроил БД - все прошло успешно. При переходе на сайт загружается главная страница с демонстрационными данными. Но при попытке перейти по любой ссылке - сайт выдает 404 ошибку и пишет:

Not Found The requested URL /login was not found on this server

Подскажите, в чем может быть проблема?

**Comment by v0vas** [comment]
install-ru.txt
1. Возможность работы с .htaccess и включенный mod_rewrite.
Надо настроить ЧПУ на веб сервере.

**Comment by maxsite** [comment]
И вообще проверить наличие файла .htaccess

**Comment by Sundego** [comment]
Решено. Проблема была в  .htaccess
При заказе хостинга он лежал в корневом каталоге. При установке он не перезаписывался, оставался по умолчанию.. Удалил файл и установил заново. Спасибо помогавшим в решении проблемы.
