### ISSUE TITLE
Не отображается в шапке сайта его наименование и описание

### ISSUE THREAD

**Issue by v0vas** [maxsite/cms#193]
Используется шаблон default. В блоке «Шапка» сайта существует название сайта и его краткое описание, В компонентах шаблона выбран Первый блок шапки - Top1. В блоке "Логотип для шапки (адрес) (top1)" указана ссылка на логогип сайта. При октрытии главной страницы наименование сайта и описание не выводятся.
![2017-04-13_12-04-28](https://cloud.githubusercontent.com/assets/24398074/24998141/c849e00e-2041-11e7-954d-d71d8babb680.jpg)
Как можно вывести наименование сайта поверх логотипа без использования css? Или это невозможно стандартными настройками?
Спасибо!

**Comment by maxsite** [comment]
Оптимально — это сделать новый компонент и там разместить как нужно.

**Comment by v0vas** [comment]
Спасибо, буду пробовать.
