### ISSUE TITLE
Не создаёт запись Auto_post

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#195]
Здравствуйте. Версия 0.96.
Создал файл с текстом в 6 тысяч с чем-то символов, прописал так:
Title: Вступление
CAT: Практическая работа
---
`<p>Сменялись версии языка C++,
добавлялись новые объекты,
появилась библиотека
MFC и различные
мастера (Wizard),
помогающие создать
приложение за несколько
минут. Но созданные
этими мастерами
приложения необходимо
наполнять  реальными  классами,
устанавливать их
взаимосвязи, а
это требует
«ручного» программирования и,
как следствие,
трудоемкой поддержки и
сопровождения. Даже
если вы
используете собственную
библиотеку классов, внесение изменений
в код самого
класса чревато нарушением его
работоспособности,
особенно  после
нескольких месяцев или
лет работы, когда
многие ограничения
и связи,
которые  учитывались при
создании, забыты. Так
где  же
решение? А
решение, как
это часто  бывает,
лежит  на
поверхности.
Нужно уменьшить
«ручное» программирование,
чреватое
ошибками  и
вносимыми каждым
разработчиком личными
предпочтениями  в
программу.</p>`

Создал рубрику "Практическая работа".

Сам файл, похоже, загрузился, но запись не создалась (Уже прошло минут 15).
Вот что на странице auto_post:
1.txt
upload 1.txt
1.txt:
Title: Вступление
CAT: Практическая работа
---
`<p>Сменялись версии языка C++,
добавлялись новые объекты,
появилась библиотека
MFC и различные
мастера (Wizard),
помогающие создать
приложение за несколько
минут. Но созданные
этими мастерами
приложения необходимо
наполнять  реальными  классами,
устанавливать их
взаимосвязи, а
это требует
«ручного» программирования и,
как следствие,
трудоемкой поддержки и
сопровождения. Даже
если вы
используете собственную
библиотеку классов, внесение изменений
в код самого
класса чревато нарушением его
работоспособности,
особенно  после
нескольких месяцев или
лет работы, когда
многие ограничения
и связи,
которые  учитывались при
создании, забыты. Так
где  же
решение? А
решение, как
это часто  бывает,
лежит  на
поверхности.
Нужно уменьшить
«ручное» программирование,
чреватое
ошибками  и
вносимыми каждым
разработчиком личными
предпочтениями  в
программу.</p>`

А в конце:
File information: 1.txt type: text/plain size: 11494 bytes

В чём может быть причина? может надо какие-то права изменить? Можно ли где-то посмотреть лог успешности создания записи? Благодарю.

**Comment by maxsite** [comment]
Неверный формат.

```
TITLE: Заголовок записи
CAT: Новости
---
текст записи
```

В `application\maxsite\admin\plugins\auto_post\lib\format.txt` есть полное описание.

**Comment by denis-skripnik** [comment]
Что-то не вижу разницы в формате.
Что именно неправильно введено?

**Comment by denis-skripnik** [comment]
Что-то не вижу разницы в формате.
Что именно неправильно введено?А всё: увидел. Хотя я вводил все буквы большие, почему-то в заголовках только первые заглавные.
