### ISSUE TITLE
Попытка взлома

### ISSUE THREAD

**Issue by DizeLyaka** [maxsite/cms#198]
Приветствую. Помогите закрыть уязвимость.
Воспользовавшись файл менеджером http://"корень"/filemanager//dialog.php
злоумышленику удалось загрузить на сайт в папку "uploads" файл с shell-ом:

_PHP Shell - A very simple web shell (very much inspired from r57shell - rst team)_

Благо воспользоваться шеллом не успел или не смог :)
Может закрыть папку htaccess-ом ? Но надо оставить работающим filemanager с Админки.

**Comment by maxsite** [comment]
Она и так закрыта. В этом каталоге php-скрипты не работают.

**Comment by DizeLyaka** [comment]
В этом каталоге не работают, но через "filemanager" можно загрузить скрипт в другую папку. В моем случае загрузили в папку  "uploads".

**Comment by maxsite** [comment]
В uploads и не работают.

**Comment by DizeLyaka** [comment]
Скрипты не работают, а удалить файлы из "uploads" можно.

**Comment by maxsite** [comment]
Естественно. Это же каталог для манипуляций с файлами.

Я не понимаю, в чём именно проблема (кроме filemanager)?

**Comment by DizeLyaka** [comment]
В  "uploads" есть много чего (хотя бы содержимое страниц), не хотелось бы его потерять,

**Comment by maxsite** [comment]
Ну так не пользуйтесь непонятно какими плагинам. :-)

**Comment by DizeLyaka** [comment]
Кому интересно нашел решение: В filemanager\config\config.php правим переменные 
define('DEBUG_ERROR_MESSAGE', true); 
и
'access_keys' => array('ba-bla'),
также в application\maxsite\plugins\editor_tinymce\editor.php
filemanager_access_key:"ba-bla",
