### ISSUE TITLE
Проблема со входом

### ISSUE THREAD

**Issue by Valik58** [maxsite/cms#199]
Всем приветик,скачал,залил на хост,всё сделал как надо,по адрессу открываеися сайт,админки нет,как в неё попасть? При установке демо не ставил,т.е. галочку не ставил,прошу помоши.

**Comment by maxsite** [comment]
Ссылка на вход есть в подвале. Или сайт/admin

**Comment by Valik58** [comment]
Спасибо,сейчас поробую.

**Comment by Valik58** [comment]
No input file specified.   Смотрите,вот что выдаёт.

**Comment by maxsite** [comment]
Проверяйте `.htaccess`.

**Comment by Valik58** [comment]
Перезалил на другой хост,всё супер.Спасибо ребята,WordPress отдыхает,все сайты были на пресс,сейчас переделаю на эту. И вопросик,чуть не по теме,но простите-как поменять шаблон по умолчанию который,он узкий и цвет синий,огромное спасибо.

**Comment by maxsite** [comment]
Посмотрите бесплатные шаблоны на http://wbloger.com/

**Comment by Valik58** [comment]
Спасибооооооооооо!

**Comment by Valik58** [comment]
Уважаемый МАКС,скажите пожалуйста,а можно как то размер шаблона увеличить,и цвет другой поставить,я имею ввиду рабочую часть ,а не фон,ну уж слишком короткие шаблоны по умолчанию(бесплатные) или только надо платить.Спасибо,CMS очень классная.

**Comment by maxsite** [comment]
Стандартно все шаблоны используют адаптивный дизайн. То есть он должден корректно отображаться на телефоне (650px), планшете (768px и 1024px) и десктопе (до 1200px). Шире делать нет смысла — будет сложно скомбинировать блоки, да и тексты и картинки окажутся слишком широкими. Оптимальным вариантом будет ширина контента примерно совпадающей с листом А4.
