### ISSUE TITLE
Проблема с автоустановщиком

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#201]
Создал пустой каталог, настроил поддомен, закинул туда правильный .htaccess, распаковал туда _update_mso, делаю переход по http://site/_update_mso

> Последняя версия MaxSite CMS: 0
> MaxSite CMS на вашем сервере не найдена
> Обновление не требуется

Так там вообще ничего нет! Он что, только апдейт умеет делать? С нуля не поставит? В инструкции написано

> С помощью специального автоустановщика можно как установить новую систему, так и обновить 
> существующий сайт.

**Comment by maxsite** [comment]
Возможно на сервере нет curl.

**Comment by Den2016** [comment]
есть и активно используется.
Поставил обычным образом, копаться некогда.

**Comment by MaximVanyushkin** [comment]
Та же проблема
