### ISSUE TITLE
Вылезли ошибки

### ISSUE THREAD

**Issue by Mikich167** [maxsite/cms#202]
День добрый. На днях вылезли ошибки на сайте который работает многие годы, это хостер какие настройки поменял или глюконуло что-то? И что делать?
![1111](https://cloud.githubusercontent.com/assets/29090230/26623344/163169d4-45f6-11e7-87a6-5ef5e8d34b63.jpg)

**Comment by maxsite** [comment]
Попробуйте перезалить этот файл. Впечатление, что он либо битый, либо взлом.

**Comment by Mikich167** [comment]
Спасибо. Перезалил и ошибки исчезли. Файл на был меньше по размеру чем тот который залил из архива.
Возник еще один вопрос на один из сайтов идет куча спама в комментах. Это кто-то дырку нашел? Как от этого избавиться и как удалить все комменты оптом? А то там больше тысячи записей и вручную их удалять влом как-то...

**Comment by maxsite** [comment]
От ручного спама никак не избавиться. Если есть какие-то повторяющиеся фразы, то настройте антиспам-плагин.
