### ISSUE TITLE
Как в sitemap_cat реализовать фильтрацию по типу записи?

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#203]
При выводе карты сайта в виде дерева (работает функция sitemap_cat плагина sitemap) происходит вывод всех опубликованных записей в базе. Даже если это не "blog" или "static". Т.е. например, если был создан какой-то специальный тип страниц, который для особых задач (например, для страниц с платным доступом), то такие страницы будут тоже выводится и тем самым попадут в открытый доступ.

Вот как такое побороть? Там для получения дерева записей используется функция mso_cat_array и к ней особо не подобраться (при обычном выводе есть возможность создать свой type_foreach с параметрами выборки). Есть идеи?

**Comment by maxsite** [comment]
То есть ты хочешь как-то ограничить вывод только на blog?

**Comment by vimruler** [comment]
> То есть ты хочешь как-то ограничить вывод только на blog?

У меня кроме blog и static есть ещё тип event. Хочу скрыть записи, которые типа event.

**Comment by maxsite** [comment]
Наверное это нужно как-то через опции плагина сделать. По другому не представляю как этим управлять.

**Comment by maxsite** [comment]
Илья, если не сложно, попробуй поиграть в функции `sitemap()` в 61 строчке параметром `type`. Сейчас он закоментирован.

**Comment by vimruler** [comment]
> попробуй поиграть в функции sitemap() в 61 строчке параметром type. Сейчас он закоментирован.

Перед тем как сюда написать я именно в том месте и пробовал экспериментировать. Создал type_foreach файл sitemap-mso-get-pages.php и именно параметр type задавал под свою задачу. Работает отлично. Но в том то и дело, что это только часть задачи. Т.е. сокрытие ненужных записей происходит при выводе записей в податовом виде. Если вывод переключить на дерево рубрик, то там работает другая функция и там type_foreach файл не применим. Там как-то всё иначе реализовано и без использования функции mso_get_pages.

**Comment by maxsite** [comment]
Получается, что ты используешь для разных типов записей те же рубрики? По идее, если рубрика не указана, то запись будет «висеть» сама по себе.

**Comment by vimruler** [comment]
> Получается, что ты используешь для разных типов записей те же рубрики?

Нет. Разные рубрики.

**Comment by maxsite** [comment]
Не в этом дело. Просто вывод рубрик идёт как есть. Если у записи отмечена рубрика, то она и выводится.

**Comment by vimruler** [comment]
Хм. Т.е. деревом выводятся все рубрики без разбора? Но ведь рубрики в этом месте тоже вроде нельзя отфильтровать, так что не понимаю что в итоге...

**Comment by maxsite** [comment]
Вывод записей — это `mso_get_pages()`. Здесь как раз можно что-то придумать с типом записи. А вывод рубрик — это `mso_cat_array()`. Здесь вывод рубрик в чистом виде. Если у записи есть эта рубрика, то она и выводится. Ведь зачем-то эта рубрика отмечена у записи.

**Comment by vimruler** [comment]
> Здесь вывод рубрик в чистом виде. Если у записи есть эта рубрика, то она и выводится. Ведь зачем-то эта рубрика отмечена у записи.

Да, я понимаю. Но как наличие рубрики должно мешать отфильтровать записи по каком-то дополнительному параметру? Может рубрики были поставлены записи для удобства админа или для работы закрытой группы пользователей сайта. Но Общая карта сайта не должна отображать такие записи в принципе. И не понятно как отфильтровать нежелательный вывод.

**Comment by maxsite** [comment]
Ну нет. Здесь же приоритет именно вывод рубрик, а записи — это скорее следствие. :-)

Функция mso_cat_array() получает лишь номера записей, без какого-либо анализа типа.

Если нужна фильтрация, то нужно копать в строну `_sitemap_cat_elem()`. Нужно вводить if-проверку на тип записи, коороый недоступен. Поэтому наверное нужно запускать `mso_cat_array_single()` (строчка 172), где и указывать нужный тип записи (параметр `$type_page`).

**Comment by vimruler** [comment]
> Если нужна фильтрация, то нужно копать в строну _sitemap_cat_elem()

Да, логично и передача нужного значения параметра $type в функцию mso_cat_array_single() решило бы ситуацию. Вот только непонятно как это сделать, ибо в функции _sitemap_cat_elem() нет даже вызова type_foreach файла, в котором можно было бы свои настройки вызова функции задать. 

Там код:
```php
	if ($all_cat === false) $all_cat = mso_cat_array_single();
```

Может доработаем? Например, до такого варианта (не претендую на истинность, просто идею показать):
```php
	if ($all_cat === false)
	{
		if ($f = mso_page_foreach('sitemap-cat-elem')) require($f); 

		if ($all_cat === false) $all_cat = mso_cat_array_single();
	}
```

**Comment by maxsite** [comment]
Сейчас нужно попробовать проверить будет ли работать данная схема «в лоб». То есть прямо в плагине пропиши нужные данные. Если это работает, то нужно будет сделать отдельную опцию «Включить в вывод типы записей», где можно будет указывать типы через запятую.

**Comment by vimruler** [comment]
Если я правильно понял твою идею, то сделал такую правку в функции function _sitemap_cat_elem($elem):

```php
	#if ($all_cat === false) $all_cat = mso_cat_array_single();
	if ($all_cat === false) $all_cat = mso_cat_array_single('page', 'category_name', 'ASC', 'blog');
```

Желаемого эффекта это не принесло. Записи всё ещё видны. Да там, если приглядеться, то кроме одного типа указать больше всё равно ничего нельзя, ибо потом это знание применяется в коде mso_cat_array_single таким образом:

```php
	if ($type_page) $CI->db->where('page_type_name', $type_page);
```

**Comment by maxsite** [comment]
Ну ты проверь что там $all_cat выводится. Если $type_page не работает, значит дело в кэше. Нужно его сбросить. 

Несколько типов задаются в $type_page либо как массив, либо строчкой для `db->where`. Посмотри в хелпе CodeIgniter в секции Active Record Class. Там есть примеры, чтобы здесь не дублировать. Наверное только нужно будет скодки равильно расставить. 

Но вообще пока достатчно только с одним типом добиться нужного результата.

**Comment by HaipaiUser** [comment]
**vimruler** вот набросал на скорую руку:
1. Добавить в опции плагина sitemap после строки 133:
`			'exclude' => array(
							'type' => 'text', 
							'name' => t('Исключить типы страниц'), 
							'description' => '',
							'default' => ''
						),`
2. После строки 170 добавить:
`	$options = mso_get_option('plugin_sitemap', 'plugins', array() );
	$exclude_page = array();
	if (!$limit == '') {
		$par = array( 
			'no_limit' => true,
			'type'=> $options['exclude'],
			'custom_type' => 'home', 
			'content' => false,
			'order' => 'page_id',
			'order_asc' => 'asc',
			'get_page_categories' => false,
			'get_page_count_comments' => false,
			'get_page_meta_tags' => false,
		); 
		$exclude = mso_get_pages($par, $pagination);
		foreach ($exclude as $page_ex)
		{
			$exclude_page[$page_ex['page_id']] = '';
		}
	}`
3. Строку 178:
`if ($page['page_status'] == 'publish')`
заменить на:
`if ($page['page_status'] == 'publish' && !isset($exclude_page[$page['page_id']]))`
4. Зайти в админку и вписать в новое поле к примеру - event
После этого будут рубится все страницы с типом event

**Comment by maxsite** [comment]
Не-не.  Нужно сделать опцию «Включить» типы, а не «исключить». Если эта опция пустая, то просто type не указываем ( = false).

Но это не проблема. Главное — проверить возможность указывать тип в `mso_cat_array()` и `mso_cat_array_single()`. В этом загвоздка.

**Comment by HaipaiUser** [comment]
**maxsite** нвсколько я понял первый пост от **vimruler**, то как раз ему было нужно исключить определенный тип страниц из карты сайта.

**Comment by HaipaiUser** [comment]
По поводу mso_cat_array() и mso_cat_array_single() посмотрю что можно придумать.

**Comment by maxsite** [comment]
> maxsite насколько я понял первый пост от vimruler, то как раз ему было нужно исключить определенный тип страниц из карты сайта.

Верно. Но технически проще указывать включаемые типы.  Сейчас нужно просто посмотреть как «грязно» можно это сделать. Дальше я уже сам подумаю как и что поменять в ядре.

**Comment by HaipaiUser** [comment]
> Но технически проще указывать включаемые типы. Сейчас нужно просто посмотреть как «грязно» можно это сделать.

Кстати, плагин нужно все равно переделать, т.к. если выбрано - Группировка по датам, он все рано ничего кроме типа blog не выводит.

**Comment by HaipaiUser** [comment]
В общем разобрался с mso_cat_array()
Достаточно в category.php вставить одну строчку, скажем в 68 строку:
`$CI->db->where_in('page.page_type_id', array('1','3'));`

array содержит номера типов страниц.
Как туда это передать, думаю объяснять не нужно.

**Comment by maxsite** [comment]
Есть функция `mso_explode()`. Лучше ей, хотя передавать нужно либо массив, тогда работает where_in, либо строку, тогда работает where. Такой пример кода есть в _mso_sql_build_home()

```php
if ($r['type']) 
{
	if (is_array($r['type'])) 
		$CI->db->where_in('page_type.page_type_name', $r['type']);
	else 
		$CI->db->where('page_type.page_type_name', $r['type']);
}
```
Илья, ты проверил у себя?

**Comment by HaipaiUser** [comment]
Не совсем так.
В данном месте where работать нормально не будут.
Вернее если придет одно значение, к примеру:
`$explode = '1'`
то where отработает нормально,
а если придет:
`$explode = '1,3,7'`
то where нормально не отработает.
а where_in в моем примере в обоих случаях отработает правильно.
А по условиям было нужно передавать количество от ничего, до ...

Ну и page_type.page_type_name в том месте тоже не прокатывает.
Чтоб лишнего не городить, яи использовал page.page_type_id

**Comment by maxsite** [comment]
Конечно, where_in должен быть массив. В принципе, я согласен, что использовать можно только входящую строчку. Но, часто бывают задачи, когда лучше передать данные в виде массива. В этом случае проверка is_array и используется.

Для отладки можно использовать функцию `pr()`.

Еще в `mso_cat_array()` идет подсчет колва записей, поэтому филтр по статусу нужно добавить и в неё.

**Comment by HaipaiUser** [comment]
> Еще в mso_cat_array() идет подсчет колва записей, поэтому филтр по статусу нужно добавить и в неё.
Да, я знаю, я этот кусок добавлял в 237 строку.
Но тут я это опустил, т.к. в данном случае это не столь было важно, поскольку задача стояла просто фильтрацию оттестировать.

**Comment by maxsite** [comment]
У меня пока тоже нет времени плотно заняться. Пока поставил статус задачи.

**Comment by vimruler** [comment]
Отправил Максиму свой вариант необходимых правок. Если кому-то интересно что получилось - прикладываю архив сюда.
[sitemap_src.zip](https://github.com/maxsite/cms/files/1111570/sitemap_src.zip)

**Comment by maxsite** [comment]
Ок. Гляну.
