### ISSUE TITLE
Неверный код капчи

### ISSUE THREAD

**Issue by XNTPbIY** [maxsite/cms#204]
При регистрации такая надпись. но капча не выводится .
Облазил всю админку и не нашел настройки по капче. Направте куда копать. Заранее спасибо.

**Comment by maxsite** [comment]
А плагин капчи включен?

**Comment by XNTPbIY** [comment]
Да включил разобрался.  При регистрации пользователя когда он регистрируется , на следующем этапе  ошибка 500 но письмо приходит с активацией.

**Comment by XNTPbIY** [comment]
Сейчас заново ставлю движок

**Comment by XNTPbIY** [comment]
Проблема при регистрации осталась, после регистрации 500 ошибка. На mail приходит письмо с регистрацией ( пробовал и отключать активацию и включать) , не могу зайти под новой учеткой пишет не верный логин или пароль.

**Comment by maxsite** [comment]
Попробуйте куки очистить в браузере.

**Comment by XNTPbIY** [comment]
Куки чистил ) и с другова браузера пробовал результат тот же. http://blog.sar-info.ru можете проверить сами.  И есть еще вопрос по шаблону,  с демо каталога был скачен шаблон и не где не могу вывести 
название бокового блока пробовал category_widget Рубрики , но как я понимаю то название блока должно автоматом выводить.

**Comment by XNTPbIY** [comment]
С вашем движком первый первый опыт работ.

**Comment by maxsite** [comment]
Скорее всего что-то на сервере. На nginx скорее всего выделен малый размер для http-заголовка. Нужно дёрнуть хострера, пусть смотрит логи ошибок и увеличвает размер буфера заголовка.

**Comment by XNTPbIY** [comment]
в конфиге НАСТРОЙКИ СЕРВЕРА / NGINX НАСТРОИТЬ PHP.INI прописаны такие данные :
 client_header_buffer_size       2k;
    client_body_buffer_size         256k;
    client_max_body_size            100m;
Какие должны быть что бы корректно работал ваш движок ?

**Comment by XNTPbIY** [comment]
в php.ini  
memory_limit 128M

**Comment by XNTPbIY** [comment]
Какие минимальные требования под ваш продукт? У меня на сервере vds еще несколько проектов один из них на DLE , другой самописный движок. Все работает ровно. С вашем продуктом не могу разобраться.

**Comment by maxsite** [comment]
Похоже, что вот этот  `client_header_buffer_size 2k;` слишком мал. Попробуйте увеличить до 5..10 и посмотрите.

**Comment by XNTPbIY** [comment]
увеличил до 10 такой же эффект. 
**nginx.conf**  client_header_buffer_size       5k; и 10 к пробовал
`    # Main settings
    sendfile                        on;
    tcp_nopush                      on;
    tcp_nodelay                     on;
    client_header_timeout           1m;
    client_body_timeout             1m;
    client_header_buffer_size       5k;
    client_body_buffer_size         256k;
    client_max_body_size            100m;
    large_client_header_buffers     4   8k;
    send_timeout                    30;
    keepalive_timeout               60 60;
    reset_timedout_connection       on;
    server_tokens                   off;
    server_name_in_redirect         off;
    server_names_hash_max_size      512;
    server_names_hash_bucket_size   512;`

**Comment by XNTPbIY** [comment]
И не пускает под новой учеткой и 500 ошибка

**Comment by XNTPbIY** [comment]
Из логов
[Sat Jun 17 19:06:25 2017] [error] [client 192.166.117.4] Directory index forbidden by Options directive: /home/admin/web/blog.sar-info.ru/public_html/
[Sat Jun 17 19:06:25 2017] [error] [client 192.166.117.4] File does not exist: /home/admin/web/blog.sar-info.ru/document_errors/noindex.html

**Comment by XNTPbIY** [comment]
Ваша пробная учетка есть http://blog.sar-info.ru/users/2  Вы смогли войти под ней ?

**Comment by maxsite** [comment]
Нет не получается. Ошибка

HTTP/1.1 502 Bad Gateway

**Comment by XNTPbIY** [comment]
У меня такой ошибки не было

**Comment by XNTPbIY** [comment]
Как я понимаю , на моем сервере ваш движок не будет работать полноценно , надо искать что то другое ?

**Comment by maxsite** [comment]
Ошибку нужно смотреть в логах или по http-ответу сервера. Думаю, что тут дело в настройках сервера. С nginx проблемы обычно в малом буфере, а так в общем-то всё должно работать. Для «движка» в первую очередь требуется php, а с остальным это уже серверная часть. :-)

**Comment by XNTPbIY** [comment]
Хорошо буду дома вечером, гляну логи на самом сервере , с работы заблокированы порты для работы через puty . О результате отпишу. Спасибо.

**Comment by XNTPbIY** [comment]
По логам для данного домена нет не каких ошибок :)

**Comment by XNTPbIY** [comment]
Тока на GET запросы ошибки такого плана
192.166.117.4 - - [18/Jun/2017:15:47:17 +0300] "POST /login HTTP/1.0" 302 - "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:47:21 +0300] "GET /loginform/error HTTP/1.0" 200 8996 "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:47:27 +0300] "GET /loginform HTTP/1.0" 200 8907 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:47:38 +0300] "POST /login HTTP/1.0" 302 - "http://blog.sar-info.ru/loginform" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:47:41 +0300] "GET /loginform/error HTTP/1.0" 200 8990 "http://blog.sar-info.ru/loginform" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:47:42 +0300] "GET /password-recovery HTTP/1.0" 200 9173 "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:47:58 +0300] "POST /password-recovery HTTP/1.0" 302 - "http://blog.sar-info.ru/password-recovery" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:48:06 +0300] "POST /password-recovery HTTP/1.0" 302 - "http://blog.sar-info.ru/password-recovery" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:48:09 +0300] "GET / HTTP/1.0" 200 10537 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:50:07 +0300] "POST /login HTTP/1.0" 302 - "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:50:10 +0300] "GET /loginform/error HTTP/1.0" 200 8996 "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:50:13 +0300] "GET /loginform/error HTTP/1.0" 200 8996 "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:50:13 +0300] "GET /application/maxsite/templates/max-turdus/assets/css/owl.theme.default.css HTTP/1.1" 304 0 "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
192.166.117.4 - - [18/Jun/2017:15:50:13 +0300] "GET /application/maxsite/common/jquery/jquery.cookie.js HTTP/1.1" 304 0 "http://blog.sar-info.ru/loginform/error" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"

**Comment by maxsite** [comment]
На ошибки не похоже. Наверное это всё-таки лог от access. 302 — это редирект. 304 — это признак, что адрес не менялся. 200 — Ok.

**Comment by XNTPbIY** [comment]
Это все логи которые есть в папке var/log/httpd/  (access_log) и (error_log) 
 в папке  var/log/nginx/ вообще пусто по данному домену

**Comment by maxsite** [comment]
Тут сложно что-то сказать. Может будет проще поискать специалиста, который правильно настроит сервер.

**Comment by XNTPbIY** [comment]
Знать бы какие требования и какие настройки нужны , я бы все сам настроил.  Возможно скрипты выполняющие Get и Post запросы может что там не так. Ладно буду искать альтернативу.  Просто с другими движками проблем не наблюдал. Я даже пробовал по разному прописать .htaccess ключи некоторые коментировал , но результат "0"

**Comment by maxsite** [comment]
Никаких особых требований к серверу со стороны MaxSite CMS нет. Всё типовое. Из того, что я понял — есть проблема только в неверно настроенном буфере http. CodeIgniter создает довольно большую куку (там и шифрование и идентификация). Видимо из-за этого сервер nginx и вываливает ошибку. Если бы дело было в php-скриптах, то были бы и php-ошибки. Но их нет.

**Comment by maxsite** [comment]
Файл .htaccess по сути только для ЧПУ. У вас все работает, поэтому ничего менять не нужно. Кроме того .htaccess nginx может просто игнорировать.

**Comment by XNTPbIY** [comment]
Ясно, по вожусь ещё , если решения не найду то буду что то ещё искать. А так спасибо за советы и помощь .
