### ISSUE TITLE
Database not connected

### ISSUE THREAD

**Issue by jorjik** [maxsite/cms#205]
после запуска скрипта Авто-апдейта
не видит базу, но в конфиге она есть...
* прошлая версия 0,85

**Comment by maxsite** [comment]
Если ваша версия MaxSite CMS ниже 0.90, то используйте УНИВЕРСАЛЬНЫЙ СПОСОБ ОБНОВЛЕНИЯ.

**Comment by jorjik** [comment]
? это как http://max-3000.com/search/%D1%83%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9

ручной что-ли..?

**Comment by maxsite** [comment]
См. install-ru.txt
