### ISSUE TITLE
Доработка плагина Гостевая книга и Обратная связь

### ISSUE THREAD

**Issue by opiumgg** [maxsite/cms#207]
Сделать возможность согласиться или отказаться от обработки и хранения данных (какое нибудь поле для галки или отметки), если галки нет, то отправки формы не будет. Спасибо.

**Comment by maxsite** [comment]
Какой «обработки»? Зачем такие сложности?

**Comment by opiumgg** [comment]
Это под  новые требования [https://journal.tinkoff.ru/news/personalnye-dannye/](url)

**Comment by maxsite** [comment]
Что мешает сделать отдельную страницу с правилами сайта?

**Comment by opiumgg** [comment]
75 тысяч рублей — штраф за то, что клиент не согласился на обработку своих данных (не поставил галку в соответствующем месте или на сайте вообще нет места, где это можно сделать);

_сделать галочку_

**Comment by maxsite** [comment]
Что за бред...

**Comment by opiumgg** [comment]
Да есть такое. Но вот 5 лет на максайт и все время чтото да надо дорабатывать под требования.

**Comment by maxsite** [comment]
В гостевой книге разместите текст, что нажатие на кнопку и есть согласие с бла-бла-бла. А в регистрации и так есть опция согласия с правилами.
