### ISSUE TITLE
Проблемы с отображением кода

### ISSUE THREAD

**Issue by 4ppl** [maxsite/cms#208]
## Во встроенном редакторе записей подготавливаю следующий текст:
![1](https://user-images.githubusercontent.com/26070089/28166645-60cd987a-67e1-11e7-8692-d3bccaec9836.PNG)

## В готовой странице "потерялась" часть текста:
![2](https://user-images.githubusercontent.com/26070089/28166651-68388b92-67e1-11e7-9861-5b0d4e7decec.PNG)

**Comment by maxsite** [comment]
Версия системы?

**Comment by 4ppl** [comment]
Версия 0.96 - последняя на текущий момент

13 июля 2017 г. 15:49 пользователь "MAX" <notifications@github.com> написал:

**Comment by maxsite** [comment]
На dev-версии проверьте.

**Comment by 4ppl** [comment]
## Проверка на dev-версии:
![1](https://user-images.githubusercontent.com/26070089/28171565-83aea248-67f1-11e7-8c31-77810e9008ca.PNG)

## Результат без изменений:
![2](https://user-images.githubusercontent.com/26070089/28171617-b0cf2626-67f1-11e7-946c-2836f86a5151.PNG)

**Comment by maxsite** [comment]
Текстом дайте этот код.

**Comment by 4ppl** [comment]
while [ $# -gt 0 ]; do
        case $1 in
                -c)
                        CONFIG_FILE_PATH="$2"
                        shift 2
                        ;;
                *)
                        ${ECHO} "Unknown Option \"$1\"" 1>&2
                        exit 2
                        ;;
        esac
done

**Comment by maxsite** [comment]
Воспользуйтесь здесь кнопкой в редакторе «Insert code».

**Comment by maxsite** [comment]
wewqeqw
Вот проблем не вижу:
http://s.wbloger.com/2017/2017-07-13-18-01-22.png

**Comment by 4ppl** [comment]
## Воспользовался советом, потерь нет:
![2](https://user-images.githubusercontent.com/26070089/28173034-e913cbbe-67f5-11e7-8669-f3692f8efa23.PNG)

Такое поведение системы (не обрамлять код "руками", а пользоваться кнопками) вызвано особенностями работы встроенного редактора?

**Comment by maxsite** [comment]
Понятия не имею. :-)

**Comment by 4ppl** [comment]
Кажется эта проблема воспроизводится, если код дополнительно "обернуть" конструкцией [spoiler]....[/spoiler]

**Comment by 4ppl** [comment]
Да, эта проблема со спойлером, при формировании страницы его (спойлерные) переменные подставляются в переменные кода:
![1](https://user-images.githubusercontent.com/26070089/28174474-47eb7836-67fa-11e7-94e6-87cec0f788cc.PNG)

Результат:
![2](https://user-images.githubusercontent.com/26070089/28174633-b09e5696-67fa-11e7-86bc-8e92a4746505.PNG)

Соответственно, если не задавать спойлеру заголовок, он "обнуляет" и &1 и &2, если они попадаются в коде....

**Comment by maxsite** [comment]
Надо этот плагин вообще убрать. Есть bb-код [show].

**Comment by 4ppl** [comment]
Только хотел написать не используйте спойлер, используйте [show]...[/show], но Вы меня опередили.
