### ISSUE TITLE
Как настроить поиск на сайте?

### ISSUE THREAD

**Issue by bulllest** [maxsite/cms#209]
При поиске на сайте искомое слово находится и выводится в виде меток и с адресом домен/tag/искомое слово, т.е. если правильно понимаю, то поиск осуществляется по тегам. Если я нажимаю на ссылку с результатом поиска, то выводится страница 404. Ничего не найдено...
Нужно, чтобы искомое слово находилось где либо на страницах сайта, с ссылкой на страницу.

В фалах шаблона никаких изменений не делал. Файл в шаблоне /type/search/search.php есть.
Что нужно и где поправить?

**Comment by maxsite** [comment]
С примером было бы понятней...

**Comment by bulllest** [comment]
![poisk3](https://user-images.githubusercontent.com/30588099/28777421-6f495876-7614-11e7-9a18-41ae57c8b399.png)
Пример, пожалуйста.
![poisk2](https://user-images.githubusercontent.com/30588099/28777415-683a85aa-7614-11e7-9dcb-b87538bba10b.png)

**Comment by maxsite** [comment]
Попробуйте на дефолтном шаблоне.

**Comment by bulllest** [comment]
Все тоже самое ((( Ничего не поменялось.

**Comment by maxsite** [comment]
Ну а просто метки-то на сайте работают?

**Comment by bulllest** [comment]
Вроде бы работают, опять же это в моем понимании, на сайте к статьям прописываю Метки (через запятую), они отображаются вверху каждой статьи.

**Comment by maxsite** [comment]
А при переходе по этим ссылкам что происходит?

**Comment by bulllest** [comment]
Если я нажимаю на какой-либо тег, то картина повторяется, как и с поиском, ошибка 404. Ничего не найдено...Видимо где то скрывается ошибка, поэтому я к Вам и обратился за помощью!

**Comment by maxsite** [comment]
Проверьте работу на чистой dev-версии MaxSite CMS на дефолтном шаблоне. Отключите сторонние плагины.

**Comment by bulllest** [comment]
Т.е. мне нужно активировать на сайте дефолтный шаблон и отключить все плагины?

**Comment by bulllest** [comment]
отключил плагин range_url и все заработало. Про него написано, что он позволяет задать шаблоны «правильных» URL сайта. Адреса, не подходящие ни под один шаблон, будут отдаваться как 404-страница.

**Comment by bulllest** [comment]
Смысл этого плагина Вы можете мне объяснить?

**Comment by maxsite** [comment]
Сомневаюсь, что дело в этом плагине. Вы указали опцию Использовать стандартные шаблоны URL?

**Comment by bulllest** [comment]
Где эту опцию устанавливать?

**Comment by bulllest** [comment]
Если я создаю новую статью, то сейчас без плагина range_url адрес страницы выглядит домен/no-url.
Приходится в настройках к статье, в пункте прочее, Короткая ссылка: в ручную прописывать адрес статьи. А раньше при написании статьи, адрес  автоматически латинскими буквами прописывался, как пример адрес статьи домен/statya-pro-pingvinov

**Comment by maxsite** [comment]
Ну и сейчас автоматом ставится как и прежде. Плагин range_url влияет только на входящие ссылки, никакого отношения к созданию записи он не имеет.

**Comment by bulllest** [comment]
Добрый день.
Подскажите как настроить поиск так , чтобы метки не выводились в результатах? Мне нужны только записи.

**Comment by maxsite** [comment]
Скопировать из shared в свой шаблон  type\search\search.php и там внеси изменения.
