### ISSUE TITLE
Планы по MaxSite CMS

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#21]
Несколько принципиальных изменений. Они все между собой связаны, поэтому определить приоритет будет сложно.

Принципиально: есть желание серьезно подчистить старые хвосты. Это касается удаления каких-то старых файлов, вроде jQuery-плагинов или стилей. Они нужны только ради совместимости со старыми версиями и шаблонами. Плюс мы отказываемся от поддержки старых браузеров, в частности минимальная версия IE11. Это то, что заявляется. Остальное на откуп вебмастера. Хоть для IE6 делай.

Скорее всего это приведет к частичной потери совместимости со старыми шаблонами. Поэтому основное требование для шаблонов — использование концепции D3. Как «отсекать хвосты» я уже писал на своем сайте.

LESS-компилятор заменю на новый. Но, тут важно отметить, что я планирую всё-таки использовать его опционально. На текущий день тот же winless с родной версией less.js работает лучше. Поэтому lessphp будем рассматривать как фишку, но не более того. К сожалению поддержка php-компиляторов less практически прекратилась, а то, что есть сильно отстает от нативного less.js.

Касаемо less в шаблоне есть пара моментов. В первую очередь я хочу изменить логику секции HEAD (см. mso_default_head_section() ). Подключение css/less-стилей очень запутанны. Вместо этого там оставить единый style.less, который автоматом компилируется в style.css. Но при этом автоматом подключаются все css-файлы из /css/. Эта логика сейчас используется в LPF и отлично себя зарекомендовала.

Далее по шаблонам. Дефолтный шаблон хочу переписать с использованием a-style (http://lpf.maxsite.org/rules-for-css) и только в варианте D3. 

Админку тоже планирую переделать с помощью a-style. В админке есть несколько нехороших вещей, нужно будет их поправить. Там же нужно добавить адативность. Сам дизайн меня устраивает, но рассмотрю ваши идеи.

Часть вещей, придуманных для LPF, я бы хотел внедрить в MaxSite CMS. В частности очень нравится парсер simple. Чтобы его использовать потребуются некоторые переделки во встроенном autotag. Это сложная проблема и как её решать нужно ещё подумать. То есть основная идея в том, чтобы вынести все autotag отдельно и подключать опционально для каждого случая. Этот подход позволит разрешить конфликт визуально/невизуалього редактирования — используй тот парсер, который больше нравится.

Вот это основные моменты.

**Comment by vimruler** [comment]
По «подчистке хвостов» - полностью поддерживаю по всем пунктам.

Жаль, что с LESS как-то мутно получается. Не хотелось бы терять отличную возможность компиляции на лету и переходить на js-версию. Можно раскрыть поподробнее, что устарело в текущей версии компилятора и что интересного появилось в новой, что обязательно надо переходить на неё?

По новому способу подключения less и css - поддерживаю.

По внешнему оформлению админки есть вопросы-пожелания: 
* переделать стили блоков, в которых раполагются инструкции по заполнению полей. Очень сложно выводить туда фрагменты кодов, цитаты, списки.
* внедрить эффект сворачивания для групп параметров на странице опций плагинов. Могу поделиться кодом, если нужно (там нужно немного переделать стандартную функцию и добавить стили). 
* добавить дополнительные font-awesome иконки. Их удобно использовать для оформления своих пунктов меню и т.п. в админке.

Новый дефолтный шаблон будет адаптивным?

По остальному пока затрудняюсь высказаться.

**Comment by maxsite** [comment]
Текущий less.js имеет версию 2.2.0. Наш less-php застрал где-то на 1.2. Новый lessphp где-то в раойне 1.6 и больше не развивается. Я рекомендую использовать winless, который использует 1.9, а если использовать node.js, то последнюю версию less.js. LESS сейчас развивается очень активно: https://github.com/less/less.js/blob/master/CHANGELOG.md Так что лучше сразу на него ориентироваться. Кроме того winless будет работать быстрее, чем lessphp. И less требуется только на этапе разработки. Так что настроить компиляцию один раз не проблема. 

> Новый дефолтный шаблон будет адаптивным?

Да, конечно.

> переделать стили блоков, в которых раполагются инструкции по заполнению полей. Очень сложно выводить туда фрагменты кодов, цитаты, списки.

Пока сложно что-то конкретное говорить. Ближе к делу будет понятней.

> внедрить эффект сворачивания для групп параметров на странице опций плагинов. Могу поделиться кодом, если нужно (там нужно немного переделать стандартную функцию и добавить стили). 

Согласен. Думаю что js прицепить будет не сложно.

> добавить дополнительные font-awesome иконки. Их удобно использовать для оформления своих пунктов меню и т.п. в админке.

FA будет последней версии в варианте, как он используется в a-style.

**Comment by cuprum** [comment]
Хорошо, что дело начало двигаться.
Я бы еще предложил рефакторинг-ревизию javascript-кода в админке. Сейчас там разрозненные куски для разных страниц. Может, весь js, который для нужд админки причесать и слить в один файл?

**Comment by maxsite** [comment]
Пока сложно сказать. Наверное вначале нужно html сверстать, а потом с js разбираться. В любом случае переделок много.

**Comment by vimruler** [comment]
Всё понятно. LESS действительно можно компилить локально.

По эффекту сворачивания групп опций - действительно легко будет прикрутить, ибо js уже есть. Там весь вопрос только в стилях по сути.

Вспомнил ещё одно пожелание по админке. У плагинов часто выводится дублирующиеся хлебные крошки. Т.е. есть стандартные «серые» (которые почему-то без ссылок, т.е. практически бесполезные) и иногда (на старницах опций) зачем-то выводятся дополнительные ссылки на общую страницу плагинов. Например, это можно увидеть здесь - /admin/plugin_options/bbcode В общем, хорошо бы приглядеться к хлебным крошкам админки.

**Comment by maxsite** [comment]
По-идее эти хлебные крошки вовсе не нужны. Я их чисто для красоты сделал, поэтому такой бардак и получился.

**Comment by maxsite** [comment]
Ещ«по less. Сегодня занимался этим вопросом, решил, что нет смысла обновлять lessphp. Всё равно другой вариант сильно отстает от нативного less.js. Поэтому оставим как есть, просто будем считать его эдакой lite-версией. :)

**Comment by vimruler** [comment]
> По-идее эти хлебные крошки вовсе не нужны.

Да, думаю, что можно было бы совсем убрать, чтобы не перегружать интерфейс.

> решил, что нет смысла обновлять lessphp. Поэтому оставим как есть, просто будем считать его эдакой lite-версией.

Понятно. ИМХО, нормальный вариант.

По админке есть ещё [предложения от Дениса Скрипника](http://maxhub.ru/page/srochno-plany-maksima-po-maxsite-cms#comment-496):

* > сделать на странице списка плагинов не подряд два блока: активные и неактивные, а создать вкладки, причём по умолчанию выводятся активные плагины.

* > создать фильтр по названию и описанию плагина... он видет только этот плагин в таблице, а не кучу разных

Второе предложение хоть и интересное, но ИМХО, пока не шибко актуальное. А вот первое - думаю можно было бы взять в работу уже сейчас, если согласен. Тем более, в админке много где используется идеалогия табов и это для движка практически стандартный подход уже, так что у пользователей не должно быть сложностей с освоением.

**Comment by monenkeskinen** [comment]
Еще бы вывод включенных плагинов, имеющих опции, сделать в левой колонке админ-меню. А то долго приходиться идти в настройки: плагины - ищем нужный - опции. Так малость удобнее. Если можно, конечно)

**Comment by vimruler** [comment]
> вывод включенных плагинов, имеющих опции, сделать в левой колонке админ-меню.

Возможно это удобно. Но как часто приходится обращаться к опциям не в момент разработки, а в обычной жизни? Лично я редко лезу в настройки и только когда совсем что-то припекло :)

Поэтому я наоборот считал, что надо разгрузить сайдбар админ-панели. Например, очень хочется убрать ссылки на ушки, feedburner, Loginza и т.п. плагины, которые нужны очень редко.

Но чтобы и вы остались довольны можно разработать специальный плагин, который бы при необходимости создавал специальный виджет в сайдбаре админ-панели с ссылками на страницы опций плагинов, которые имеют страницы опций. Надо только понять, если ли хук для вывода своего виджета в сайдбар админ-панели...

**Comment by monenkeskinen** [comment]
Ну, можно, например, убрать все это дело под спойлер, чтобы не загромождать сайдбар. Или, как вы говорите, через плагин. Просто на этапе разработки (а он, к сожалению, не один день занимает) очень часто приходится ходить по опциям плагинов.

Вообще, чтобы все было справедливо, мое предложение можно на голосование сообщества вынести и отказаться от него, если большинство не поддержит)

**Comment by maxsite** [comment]
Наверное самое оптимальное — это придумать «нечто», что позволит отметив нужные плагины, автоматом выводить на них ссылки с сайдбаре админ-панели. Отмечай только то, что нужно.

**Comment by monenkeskinen** [comment]
Я секунду назад тоже об этом подумал) Например, поставить в списке плагинов чекбоксы с возможностью выбрать все, ни одного или поштучно. Как-то так)

**Comment by vimruler** [comment]
> придумать «нечто», что позволит отметив нужные плагины автоматом выводить на них ссылки с сайдбаре админ-панели

Плагин, который будет выводить специальный виджет в сайдбар админ-апнели и у которого будут опции настройки! :-) Хотя ещё не смотрел где плагины для админ панели хранят и выводят свои опции...

Кстати, вопрос к Максиму, а можно как-то пересмотреть виджет «Начало»? Ссылки «Переход к сайту» и «Выход» там слегка избыточны (есть в других местах страницы), но место занимают. По сути нужна только «Информация».

**Comment by vimruler** [comment]
А можно не городить плагин с виджетом, а просто добавлять список плагинов в конец виджета «Настройки». Просто завести опцию специальную в админ-панели.

**Comment by maxsite** [comment]
Там всё немного сложней. Механизм добавления в меню это одно, своя страница опций, это другое, а опции через mso_admin_plugin_options() - это уже третье. Я бы оставил всё как сейчас, только кукой-то блок в настройках по принципу главного меню «ссылка | название», которое выводится последним блоком в меню.

**Comment by vimruler** [comment]
> блок в настройках по принципу главного меню
Т.е. нужно руками задавать ссылки, которые нужны? В том числе речь и о страницах опций плагинов? Такой вариант сейчас действительно самый реальный. Остальное всё сложнее в реализации.

**Comment by maxsite** [comment]
Если не переделывать все плагины, то это самый простой вариант.

**Comment by dignityinside** [comment]
http://lpf.maxsite.org/rules-for-css - Ссылка не работает.

**Comment by maxsite** [comment]
Сейчас это уже http://unicss.maxsite.com.ua/
