### ISSUE TITLE
В полном тексте нет картинок

### ISSUE THREAD

**Issue by ottawa1** [maxsite/cms#210]
Здравствуйте. Создал рубрику поместил в меню. Начал делать записи с картинками. На главной странице помещаю анонсы. А полные записи появляются после нажатия на кнопку читать полностью. К сожалению в полных текстах нет картинок. Хотя припросмотре исходного кода страницы они есть т.е. картинки. Также при просмотре в рубриках видны анонсы тоже без картинок.

**Comment by maxsite** [comment]
Картинки как указываете?

**Comment by ottawa1** [comment]
<a href="http://mu.site.ru/uploads/prisins/10.jpg" class="lightbox"><img style="float: left;  margin-right:15px;" src="uploads/prisins/10.jpg" alt="" /></a>

**Comment by ottawa1** [comment]
`<a href="http://mu.site.ru/uploads/prisins/10.jpg" class="lightbox"><img style="float: left;  margin-right:15px;" src="uploads/prisins/10.jpg" alt="" /></a>`

**Comment by ottawa1** [comment]
Извинюсь что отвлек. Исправил. там где src тоже прописал полный путь. Вопрос решен.
