### ISSUE TITLE
Проблема установки на хостинг.

### ISSUE THREAD

**Issue by Luxors** [maxsite/cms#212]
Здравствуйте! Проблема с установкой на хостинг.
Устанавливаю с нуля. По FTP загружаю файлы в корень, запускаю процесс инсталляции, на странице "Установка MaxSite CMS" заполняю соответственные данные, нажимаю кнопку "Готово", и выкидавает на страницу со следующим содержанием: 

h1 Установка MaxSite CMS hr(dotted) _(t-green i-check-square-o) Файл robots.txt создан _(t-green i-check-square-o) Файл .htaccess создан _(t-green i-check-square-o) Файл sitemap.xml создан _(t-green i-check-square-o) Файл application/maxsite/mso_config.php создан . 

На этом все останавливается. В базу данных ничего не записывается, ошибок в лог не выдается. Тех. поддержка не помогла.
Подскажите, пожалуйста, возможные причины.

**Comment by maxsite** [comment]
Версия PHP какая?

**Comment by Luxors** [comment]
5.6.22

**Comment by maxsite** [comment]
Пропробуйте ещё раз загрузить каталог install.

**Comment by Luxors** [comment]
Проблема не решена. Тех поддержка так и не смогла диагностировать проблему, отправили к разработчику).

**Comment by maxsite** [comment]
У вас не работает парсер текста в инсталяции. Либо не загрузили, либо какие-то php-ошибки. Техподдержка такими вещами и не должна заниматься. Их задача — работа сервера. Требуйте ведение php-лога, тогда будет конкретный разговор.
