### ISSUE TITLE
Как создать карту сайта

### ISSUE THREAD

**Issue by ottawa1** [maxsite/cms#214]
Здравствуйте. Для создания карты сайта я включил плагин sitemap. В описании нашел :"В тексте вставьте [sitemap]" и типа будет вам счастье. Куда вставить? В записи? Как оформить пункт меню?

**Comment by maxsite** [comment]
Вставляете в текст. Вставляете в меню.

**Comment by ottawa1** [comment]
Я не могу понять. У меня есть запись. Это и есть текст? В конце записи вставляю  [sitemap]. В меню уже есть "sitemap | Архив"  Так делаю и ничего не получается. И что делать .Как связать концы?

**Comment by maxsite** [comment]
Запись это и есть текст записи. А меню — это меню.

**Comment by ottawa1** [comment]
Приветствую. Спасибо за обстоятельные ответы на вопросы. У меня оказались включены 2 плагина sitemap и sitemap.xml. создался файл  sitemap.xml , в в меню было указано "sitemap | Карта сайта" таким образом при переходе к пункту меню карта сайта я видел файл my.site/sitemap.xml а не карту сайта. После закрытия плагина  sitemap.xml и удаления одноименного файла, сайт начал показывать карту сайта. Но файл  sitemap.xml  нужен для роботов. Как совместить показ карты сайта для людей и роботов?

**Comment by maxsite** [comment]
Адреса сайт/sitemap и сайт/sitemap.xml — разные. Первый — это карта сайта или архив для посетителей и это плагин sitemap.

Второй — нужен только для роботов и формируется автоматом после включения плагина xml_sitemap.

Проверьте эти адреса — они должны отдавать разное содержимое.
