### ISSUE TITLE
Push Уведомления

### ISSUE THREAD

**Issue by RomanS2N** [maxsite/cms#215]
Ребята, планируете ли вы добавить плагин Push Уведомлений -  Onesignal?

**Comment by maxsite** [comment]
Что за зверь?

**Comment by RomanS2N** [comment]
Вы проспали целую эпоху, самая нужная вещь что бы вас не забыли :).
https://wordpress.org/plugins/onesignal-free-web-push-notifications/

**Comment by maxsite** [comment]
Ну поделитесь откровением, только так, чтобы понятно было.

**Comment by RomanS2N** [comment]
В каком смысле откровением, там же написано. Можно так конечно прочесть:  https://translate.google.ru/translate?sl=en&tl=ru&js=y&prev=_t&hl=ru&ie=UTF-8&u=https%3A%2F%2Fwordpress.org%2Fplugins%2Fonesignal-free-web-push-notifications%2F&edit-text=

**Comment by maxsite** [comment]
«Мы отправляем более миллиарда уведомлений в день» — замечательная реклама. Что бы что-то делать нужна техническая документация, спецификация и т.п. Подготовьте полноценное ТЗ, тогда будет предметный разговор.

**Comment by RomanS2N** [comment]
Ну и что ... У вас выходит статья, и все отправляется уведомление. К примеру, на МаксСайт вышло обновление и все об этом уже знают, даже те кто об этом не помнит. И вы в курсе кто это и где они находятся.
Плагин под ВордПресс уже готовый есть, API есть: https://documentation.onesignal.com/docs.

**Comment by maxsite** [comment]
Api чего? Какого-то сайта? И нужно ставить еще какую-то отдельную программу? 

Ещё раз. Делаете нормально ТЗ (по-русски) и тогда будет разговор. Сделайте такое объяснение, чтобы было понятно что именно вы хотите. Гадательный эликсир, к сожалению, уже закончился...

**Comment by RomanS2N** [comment]
Максим ни корвалол не эликсир не понадобятся, технология не новая и достаточно хорошо описана и в рунете тоже: https://www.yandex.ru/search/?clid=9582&text=onesignal%20ставим&lr=36&p=0
 
Для максайта, понадобиться две функции:
1. Оформление подписки (там в принципе только jquery понадобиться) для сатов работающих под HTTPS и HTTP:

Как вариант: https://codepaper.ru/article/18

Для настройки можно указать на что будем слать уведомления (может сейчас это автоматом делает), if mobile оправляем на мобильники else if win > 8.1  отправляем на рабочий стол if if win < 8.1 отправляем в браузер.

Всё.

2. Функция которая отправляет само уведомление, нужно зарегистрироваться на onesignalнужно зарегистрироваться на  onesignal и получить ключ. отправлять можно по разному, определённым подписчикам или всем. Я думаю на всех можно остановиться, в массайте. Как пример:
https://habrahabr.ru/post/279385/

Вроде всё , Максим пойдёт или нужны ещё медикаменты??? :)

**Comment by maxsite** [comment]
Мы яндексом не пользуемся. ;-) Насколько я понял, то это какой-то платный сервис делает push-уведомления, которые всех только раздражают. К MaxSite CMS это никакого отношения не имеет в принципе. Если хотите, то берёте их готовый код и вставляете на своём сайте. В MaxSite CMS для этого куча вариантов. Зачем мне ещё брать на себе поддержку чужого непонятно-какого сервиса, да ещё и бесплатно, я не понимаю. Хотят поддержку в MaxSite CMS, пусть платят за разработку плагина. Опционно, кому нужно, включат.

**Comment by RomanS2N** [comment]
Нет, сервис абсолютно бесплатный и надёжный (если бы это было по другому, соглашусь он нафиг, не нужен). Смысл его существования понятен: ваш сайт не будет следить за каждым устройством в сети и отправлять каждому миллион уведомлений.

Реализацию хочется увидит именно в виде плагина на Максайте, и связанна она с механизмом публикации, по типу пинга + да jquery подписка отдельно. Хорошо что jquery подписка. Я не представляю чего стоило бы реализация в плагине. Так что не понимаю что вас смущает.

**Comment by maxsite** [comment]
Сайт и не должен рассылать никаких уведомления. Для этого есть rss. Если нужно, то поищите того, кто возьмётся за реализацию этого плагина. Предложите свою цену, может кто и откликнется.

**Comment by RomanS2N** [comment]
Разработчики под Maxsite - редки стали. Поэтому на небольшие плагины наврали кого то найти можно, дешевле сайт новый заказать.

**Comment by maxsite** [comment]
Плагины MaxSite CMS очень простые по структуре, скорее дело в сложности интеграции стороннего API. Это касается не только этого сервиса, но и многих других.

**Comment by vimruler** [comment]
>Плагины MaxSite CMS очень простые по структуре,

Согласен.

> скорее дело в сложности интеграции стороннего API.

Тут скорее вопрос в размере бюджета на разработку. При адекватном бюджете могу любое API прикрутить.

**Comment by maxsite** [comment]
Наверное можно сделать некую «перепись» разработчиков... Мы когда-то делали реестр WordPress-разработчиков, работало хорошо.
