### ISSUE TITLE
Поддержка мультиязычности?

### ISSUE THREAD

**Issue by kamuz** [maxsite/cms#216]
Будет ли в будущем поддержка мультиязычности? Так бы был больше охват аудитории

**Comment by maxsite** [comment]
Что за зверь?

**Comment by kamuz** [comment]
Идеально это:

* При установке была возмность выбора языка
* Демоданные автоматически формировались для выбраной локализации
* В настройках при изменении языка менятся должна вся админка

Через плагин можно:

* Сделать возможность добавлять переводы для материалов (страницы, записи и т. д.)
* В настройках выбирать основной и дополнительные языки

**Comment by kamuz** [comment]
Этот принцип я взял из CMF MODX с которой работал долгое время, но там есть такое понятие как контекст и при измении локализации меняется контекст (фактически ещё один сайт внутри одной установки и адмики со своими страницами). Локализации файлоориентированная как и вашей CMS, файлы локализации по умолчанию кешируются для всех страниц. Хорошая реализация в CMS [Ionize CMS](http://ionizecms.com/), которая также постоенна на базе CodeIgniter, но уже долгое время не развивается.

**Comment by kamuz** [comment]
Все понимают что ваша CMS быстрее и написанна в OOP стиле с более широкими возможностями, но мало разработчиков присоединяются к её развитию, потому что все хотят работать с зарубежными клиентами, которые давно присели на простой, процедурныйй и не такой уже и "быстрый" WordPress. Любой инструмент можно оптимизировать, но всё же. Если сделать поддержку мультиязычности, добавить плагинов (ecommerce например), простой системы мастабирования приложения (CCK в Drupal, TV в MODX, и Custom Post Type в WordPress), добавить больше достойных проектов, которые используют вашу CMS и я уверен появиться намного больше людей, которые заходят использовать её в своих будущих проектах.

**Comment by kamuz** [comment]
Нужно ещё добавить доки для разработчиков, которые могли бы больше понимать как работает CMS, как создавать темы и плагины, а то я пока что нашёл только базовую информацию по установке и работе с системой.

**Comment by maxsite** [comment]
Хорошо, Что вы начнёте делать сами в первую очередь?

**Comment by kamuz** [comment]
Нужно сначала разобраться с самим движком. Вы можете где-то опубликовать статью для разработчиков. Если с темизацией особо разбираться не нужно, то с плагинами лучше разъяснить. После этого я смогу ответить что именно я мог бы взять на себя.

**Comment by maxsite** [comment]
Статей уже масса. Какой именно вопрос вас интересует?
