### ISSUE TITLE
Переделка Загрузок

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#219]
Думаю, что настала пора переделать эту страницу. Я не брался раньше, поскольку хотел отработать этот функционал на странице одиночной записи.  

Предлагаю здесь обсудить основные моменты.

1. Основной функционал по самой загрузке будет как у одиночной записи. То есть аякс-загрузка, размеры изображений, водяные знаки, миниатюры и т.п.

2. Вывод превьюшек. Мне бы хотелось сделать так, чтобы выводилась только миниатюра, а возле лишь кнопка удалить и получение адреса. Всё остальное здесь не требуется.

3. Убрать описание файла. Если нужно, то это проще прямо в тексте записи сделать. Изначально была идея использовать это описание при создании галереи, но по факту этот текст всё равно дублируется в текст записи.

4. Генератор галереи пока убрать.  Но подумать как можно будет прикрутить подобный функционал на уровне плагина. Идея в том, чтобы можно было генерировать и другие коды. Скорее всего это как-то через указание формата, как в разных виджетах. 

5. Удаление файла пока не определился. Можно оставить кнопкой для каждой миниатюры. Но когда много файлов, то это неудобно. Тогда нужно делать чекбокс, что усложняет код. Я думаю, что это не самая частая операция, поэтому может оставить только кнопку.

6. Навигация по каталогам. Исходить из тройной вложенности каталогов. Первый select содержит только каталоги в uploads. При выборе любого во втором select появляются уже его подкаталоги. Дальше уже третий селект.

Альтернатива — только два селекта, где во втором все под/под/каталоги. Примерно как в сейчас в Файлах. В таком варианте некоторое нагромождение, зато очень быстрая и простая навигация. 

7. Предусмотреть прямую адресацию в Загрузках,  сайт/admin/files/cat1/cat2/cat3 и т.п. Уровень вложенности ограничить, скажем 5 подкаталогов.

Если есть идеи и замечания, буду рад услышать. :-)

**Comment by vimruler** [comment]
> Мне бы хотелось сделать так, чтобы выводилась только миниатюра, а возле лишь кнопка удалить и получение адреса.

Так то да, достаточно. Но может стоит ещё заложить туда хук, чтобы плагины могли добавлять свои кнопки?

> Идея в том, чтобы можно было генерировать и другие коды. 

Да, так же - вынести на уровень плагинов, т.е. дать хук, а плагин пусть сам решает что там нужно сделать.

> Удаление файла пока не определился. Можно оставить кнопкой для каждой миниатюры. Но когда много файлов, то это неудобно. Тогда нужно делать чекбокс, что усложняет код. Я думаю, что это не самая частая операция, поэтому может оставить только кнопку.

Может имеет смысл сделать появление чекбокса при наведении мышки и оставлять только открыженный чекбокс? Тогда не нужно сразу генерить html код чекбоксов для всех файлов.

**Comment by iachaly** [comment]
Обращаю пристальное внимание, на отказ системы загрузки к записям на IDN доменах, например крайне любимых нами кириллических. Патч к загрузкам можно взять из той же темы: https://github.com/maxsite/cms/issues/194

Кроме того у загрузок к записям есть следующий незначительный недостаток: если загружается не картинка, а документ - отсутствует и миниатюра и название файла. Мелочь, но лучше добавить.

**Comment by Fafofu** [comment]
Нужно добавить возможность заливать сразу много картинок, не выделяя её по одной. Так же нужно при создании записи, внизу, предусмотреть возможность вставлять image ссылки, а то приходится туда сюда глядеть. Ещё нужно, добавить возможность дополнительного создания ссылок на контент... т.е. я заливаю файл, у него создаётся ссылка с полным путём и http протоколом, но я ещё и ftp поднял на сайте, хотелось бы, что бы при загрузке фала у него так же автоматически создавалась ссылка на ftp...

**Comment by Kotgo** [comment]
В 100 версии  когда грузим картинки, а потом переносим сайт либо на другой домен , либо на другой протокол типа https, то адреса остаются старые в ссылках на файлы. Потом требуется в ручную менять адреса.

**Comment by maxsite** [comment]
Относительная адресация не работает, если сайт расположен не в корне домена. Поверьте, абсолютная адресация не просто так используется. И не только в MaxSite CMS.

В целом же так. Если меняется домен, то при переносе в sql-дампе нужно пройтись обычной заменой старых адресов на новые. В общем-то так всегда и делается. Если же меняется протокол, то оптимальным будет вообще его не указывать, а использовать универсальный «//». Такая настройка есть в MaxSite CMS.

**Comment by maxsite** [comment]
Ещё добавлю. В версии 100.4 появилась возможность использовать шорткод [pi] или [page_images], которая автоматом меняется на page-каталог текущей страницы в uploads. То есть можно адhtc вообще не указывать. :-) 

https://github.com/maxsite/cms/commit/b97699ad80231a0d4a3de64dd53332a88f1a50e7

**Comment by Kotgo** [comment]
Не совсем так .

Заходим в админке **Редактирование записи ->Основные опции -> Изображение записи**
Там ндпись 

> Укажите url-адрес изображения записи. Автоматически будет создана миниатюра с размерами, заданными в Настройках шаблона (закладка «Изображения»). Файл должен находиться в Загрузках.
Я так делаю, это удобно! Но ничего кроме полного пути к картинке не принимается! Проверьте.

**Comment by Kotgo** [comment]
Я так делаю, это удобно! Но ничего кроме полного пути к картинке не принимается! Проверьте.

P.S. Wordpress мне не нравится, по множеству причин. Поэтому и ушёл с него.

**Comment by Kotgo** [comment]
Уточните, пожалуйста это https://github.com/maxsite/cms/commit/b97699ad80231a0d4a3de64dd53332a88f1a50e7
нужно в коде сейчас поменять? Для этого Редактирование записи ->Основные опции -> Изображение записи и для загрузок будет работать?

**Comment by Kotgo** [comment]
Здесь **редактирование записи ->Основные опции -> Изображение** 
И В **ЗАГРУЗКАХ**  не работает относительный путь без указания http!
А мне нравится вариант миниатюр и большой картинки!

**Comment by Kotgo** [comment]
у  меня сайт в корне находится, всё заливал в корень и потом устанавливал, затем просто установленное перенёс на новый домен, а базу прежнюю оставил. Про дамп понял. Но про то что кроме точного указания адреса здесь  **редактирование записи ->Основные опции -> Изображение
И В ЗАГРУЗКАХ**

Не понял? По другому там не работает!

**Comment by maxsite** [comment]
Изображение записи должно указываться полным вариантом. Этот адрес используется для создания миниатюр.

**Comment by Kotgo** [comment]
> 
> 
> Изображение записи должно указываться полным вариантом. Этот адрес используется для создания миниатюр.
Максим, я знаю, вот в этом и проблема, что если хочешь поменять домен или протокол на https все эти записи нужно менять в ручную, об этом я и писал с самого начала. И картинки придётся заново загружать в загрузках, чтобы миниатюры пересоздались, верно?
А возможно ли это исправить?

**Comment by maxsite** [comment]
Если домен, то при переносе ужно просто сделать замену в sql-дампе. Если протокол, то включите замену на универсальный «//».

**Comment by Kotgo** [comment]
Когда новую картинку загружаешь, то потом сложно её найти без ввода в строку поиска по странице  в браузере. А как сделать чтобы новые картинки были первыми по дате, а не в другом порядке, пока не понял.

**Comment by maxsite** [comment]
Сортировка задаётся в Основных настройках: Сортировка файлов в загрузках

**Comment by Kotgo** [comment]
Максим, благодарю! Разобрался. :-)
