### ISSUE TITLE
Проблема: RSS в записях в "будущем" не отображается.

### ISSUE THREAD

**Issue by alexanderbashkirov** [maxsite/cms#220]
Я активно использую механизм отложенных записей. То есть пишу несколько постов на неделю вперед, и живу спокойно. Но есть одна незадача - при появлении такого поста на сайте, он не появляется в фиде RSS - до тех пор, пока не зайдешь в запись и не пересохранишь её.
Вопроизводится при всех комбинациях опций кеша, которые смог найти.

**Comment by maxsite** [comment]
RSS всего сайта?

**Comment by alexanderbashkirov** [comment]
Да, в RSS всего сайта. Другие RSS не использую.
Версия maxsite - 0.96.

**Comment by maxsite** [comment]
Это кэширование rss, которое по умолчанию 24 часа. С отложенной публикацией возникает неопределенность — кэш не в курсе что запись должна быть опубликована. Наверное можно уменьшить время rss кэша, например до 1 часа.

В \shared\type\feed\home.php в конце функция mso_add_cache()

`mso_add_cache($cache_key, ob_get_flush());`

замените на 

`mso_add_cache($cache_key, ob_get_flush(), 3600);`

Это установит время кэша 3600 секунд.

**Comment by alexanderbashkirov** [comment]
Спасибо! Попробую!

**Comment by alexanderbashkirov** [comment]
Спасибо! Помогло.
