### ISSUE TITLE
Не входит в админку

### ISSUE THREAD

**Issue by mowshon** [maxsite/cms#221]
Здравствуйте!

Обновил свой сайт с версия 0.806 на текущую версию с сайта.
Все нормально, скопировал папки application, system и и т.д. (как и было в README.MD "УНИВЕРСАЛЬНЫЙ СПОСОБ ОБНОВЛЕНИЯ").

База данных осталась старой с версии 0.806 ничего не менял.
Проблема в том, что не заходит в админу с старыми данными входа.

**Comment by maxsite** [comment]
Проверьте секретную фразу. Нужно чтобы она осталась старой.

**Comment by mowshon** [comment]
Как я понял, секретаян фраза в **mso_config.php**

```php
$config['encryption_key'] = 'свой ключ шифрования сессии';
```

Только, вот у меня на старом сайте этот файл не тронут **mso_config.php-distr** видимо CMS воспользовался своей секретной фразой. 

Или я в неправильном файле её ищу?
Как и откуда я могу достать секретную фразу с старого движка?

**Comment by maxsite** [comment]
Всё верно смотрите. Если на старом сайте фраза не указана, то используйте адрес сайта.
