### ISSUE TITLE
MaxSite CMS v97 не работает на PHP 7.1

### ISSUE THREAD

**Issue by pwrsoft** [maxsite/cms#222]
На хостинге обновился PHP до версии 7.1
Перестала работать MaxSite CMS версии 97

**Comment by maxsite** [comment]
Что пишет?

**Comment by pwrsoft** [comment]
`A PHP Error was encountered
Severity: 8192
Message: Function mcrypt_get_iv_size() is deprecated
Filename: libraries/Encrypt.php
Line Number: 273

A PHP Error was encountered
Severity: 8192
Message: Function mcrypt_create_iv() is deprecated
Filename: libraries/Encrypt.php
Line Number: 274

A PHP Error was encountered
Severity: 8192
Message: Function mcrypt_encrypt() is deprecated
Filename: libraries/Encrypt.php
Line Number: 275`

**Comment by maxsite** [comment]
См. https://github.com/maxsite/cms/issues/218
