### ISSUE TITLE
Ошибка добавления комментария

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#223]
Развернул CMS, всё настроил, поменял шаблон. Но!
Не работают комментарии от зарегистрированных пользователей. Пишет "ошибка добавления комментария" и если пытаешься зарегистрироваться при добавлении комментария, тоже пишет, "ошибка добавления комментария". Регистрация проходит (приходит подтверждение на e-mail и пользователь активируется нормально). Но после активации учётной записи, комментарии тоже не добавляются. Также ошибка. А от анонимных пользователей комментарий добавляется. И от админа не добавляется... Как понять в чём проблема? Версия CMS 97.

**Comment by maxsite** [comment]
А капча включена?

**Comment by Fafofu** [comment]
Да, включён плагин "mkj_sc". От зарегистрированных пользователей стоит галочка скрывать капчу.

**Comment by maxsite** [comment]
Ну попробуйте без него.

**Comment by Fafofu** [comment]
Отключил. Не помогло. Анонимы добавляют у зарегистрированных ошибка.

**Comment by maxsite** [comment]
Попробуйте отключить все сторонние плагины, оставив обычную капчу. Шаблон default.

**Comment by Fafofu** [comment]
Эээээ... так там только ваши плагины... Всё всё отключить?

**Comment by maxsite** [comment]
Можно всё. Шаблон переключите на default. Нужно как-то выявить проблему, у меня не получается её воспроизвести.

**Comment by Fafofu** [comment]
Всё отключил. Убрал галочки модерировать комментарии... всё равно :( Да чтож такое то :((((

**Comment by maxsite** [comment]
Давайте по-порядку проверим.

1. Регистрация комюзера сайт/registration — нормально проходит?
2. После регистрации происходит автологин — то видно по новому пункту меню где есть сылка на свою страницу. Так?
3. Идем на любую страницу и пробуем добавить комментарий. Текст например «Привет!». Проходит?

**Comment by Fafofu** [comment]
Пытаюсь зарегистрироваться пишет "Неверный код капчи" но там нет капчи :)

**Comment by maxsite** [comment]
Так вы активируйте плагин капчи.

**Comment by Fafofu** [comment]
Активировал... 
1. Регистрация проходит.
2. Да, видно ссылку на страницу. (активировал пользователя в ручную)
3. Идём на любую страницу и "ошибка добавления комментария"...

**Comment by maxsite** [comment]
Посмотрите в php-логах может есть какая-то ошибка? Какой браузер? Версия php?

**Comment by Fafofu** [comment]
Браузер IE, версия PHP 5.6.14. Я пробовал и в бразере Opera. Так в PHP можно включить только ведение ошибок... ошибок нет. Там же когда ошибка в PHP прям в браузере пишет...

**Comment by maxsite** [comment]
Тогда не знаю. Данная ошибка может быть связана ещё с проблемами в базе данных. Как вариант попробуйте установить в новую базу или её оптимизировать через phpMyAdmin. Если это не поможет, то искать ошибку следует уже через отладку в файле common\comments.php. Смотреть какие данные идут в базу.

**Comment by Fafofu** [comment]
Если бы я умел пользоваться отладкой PHP :(

**Comment by maxsite** [comment]
Это я понимаю. :-) Если бы можно было как-то воспроизвести проблему, то что-то бы решили. А так, похоже это какая-то локальная проблема.

**Comment by Fafofu** [comment]
Я нашёл текст ошибки. Переименовал ошибку. Ошибка воникает вот этот месте:

`	if ($query->num_rows()) // есть такой комюзер
							{
								$comuser_info = $query->row_array(1); // вся инфа о комюзере
								
								// сразу же обновим поле последнего входа
								$CI->db->where('comusers_id', $comuser_info['comusers_id']);
								$CI->db->update('comusers', array('comusers_last_visit'=>date('Y-m-d H:i:s')));
								
								$expire  = time() + 60 * 60 * 24 * 30; // 30 дней = 2592000 секунд
								
								$name_cookies = 'maxsite_comuser';
								$value = serialize($comuser_info); 
								
								# ставим куку и редиректимся автоматом
								mso_add_to_cookie($name_cookies, $value, $expire, 
											mso_current_url(true) . '#comment-' . $id_comment_new);
								exit;
							}
							
							mso_redirect(mso_current_url() . '#comment-' . $id_comment_new);
						}
						else
							return '<div class="' . $args['css_error']. '">' . tf('Ошибка добавления комментария2'). '</div>';`

**Comment by maxsite** [comment]
Вот перед ним в строке 792 есть строчка

`$res = ($CI->db->insert('comments', $ins_data)) ? '1' : '0';`

Перед ней добавьте 

`pr($ins_data);`

Что выводит?

**Comment by Fafofu** [comment]
`Array
(
    [comments_page_id] => 9
    [comments_comusers_id] => 3
    [comments_author_ip] => 192.168.0.41
    [comments_date] => 2017-10-24 14:54:21
    [comments_content] => dsada
    [comments_approved] => 1
    [comments_parent_id] => 0
)


Ошибка добавления комментария2`

**Comment by maxsite** [comment]
Вместо (можно просто закомментировать)
 
`$res = ($CI->db->insert('comments', $ins_data)) ? '1' : '0';`

напишите 
```
$res = $CI->db->insert('comments', $ins_data);
pr($res);
$res = 0;
```
Что выводит?

**Comment by Fafofu** [comment]
`Array
(
    [comments_page_id] => 9
    [comments_comusers_id] => 3
    [comments_author_ip] => 192.168.0.41
    [comments_date] => 2017-10-24 15:01:21
    [comments_content] => Текст комментария.
    [comments_approved] => 1
    [comments_parent_id] => 0
)

FALSE

Ошибка добавления комментария2`

**Comment by maxsite** [comment]
Ясно. Скорее всего дело в базе данных. Почему-то не добавляется запись в таблицу. Попробуйте через phpMyAdmin выполнить оптимизацию всех таблиц.

**Comment by Fafofu** [comment]
Сейчас попробую. Только я использую Workbench. От анонимного пользователя то добавляется...

**Comment by Fafofu** [comment]
Оптимизировал. Пишет для всех таблиц "Ok". Ошибка та же...

**Comment by maxsite** [comment]
Значит нужно искать пролеа на урове базы, почему не хчет работать insert. Можно попробовать через логи MySQL найти sql-запрос и в phpMyAdmin (попрбуйте через него всё делать) выполнить его. Посмотреть что будет за ошибка.

**Comment by Fafofu** [comment]
Ну так базе данных безразлично, она же не анализирует что к ней приходит. Отправлять в базу или нет решает же PHP... Если в базу не отправляется, значит дело в том, кто отправляет... От анонимного пользователя всё пишет же. Логи.... сейчас погляжу как включить логи запросов для базы... phpmyadmin - нет, спасибо :)

**Comment by maxsite** [comment]
Здрасьте... Анализирует и ещё как. Вначале на уровне sql-запроса, дальше внутренняя кухня. Workbench я не пользуюсь, может это он косячит.

**Comment by maxsite** [comment]
Да, забыл спросить, MySQL какой версии?

**Comment by Fafofu** [comment]
Workbench это оболочка для работы с сервером :) Он в работе не участвует сервера...

Вот что пишет в логах, тут я ничего не понимаю :(

Версия MySQL 5.6.26

`FROM (`mso_page`)
JOIN `mso_users` ON `mso_users`.`users_id` = `mso_page`.`page_id_autor`
JOIN `mso_page_type` ON `mso_page_type`.`page_type_id` = `mso_page`.`page_type_id`
JOIN `mso_cat2obj` ON `mso_cat2obj`.`page_id` = `mso_page`.`page_id`
JOIN `mso_category` ON `mso_cat2obj`.`category_id` = `mso_category`.`category_id`
WHERE `page_status` =  'publish'
AND `mso_category`.`category_id` IN ('7') 
AND `mso_page`.`page_id` NOT IN ('9') 
GROUP BY `mso_page`.`page_id`
ORDER BY  RAND()
LIMIT 7
		   13 Query	SELECT `page_id`, `mso_category`.`category_id`, `mso_category`.`category_name`, `mso_category`.`category_slug`, `mso_category`.`category_desc`, `mso_category`.`category_id_parent`
FROM (`mso_cat2obj`)
JOIN `mso_category` ON `mso_cat2obj`.`category_id` = `mso_category`.`category_id`
WHERE `page_id` IN ('8') 
ORDER BY `mso_category`.`category_name` asc
		   13 Query	SELECT `meta_id_obj`, `meta_key`, `meta_value`
FROM (`mso_meta`)
WHERE `meta_table` =  'page'
AND `meta_id_obj` IN ('8') 
ORDER BY `meta_value` asc
		   13 Query	SELECT `comments_page_id`, COUNT(`comments_id`) AS `page_count_comments`
FROM (`mso_comments`)
WHERE `comments_page_id` IN ('8') 
AND `comments_approved` =  '1'
GROUP BY `comments_page_id`
		   13 Query	SELECT `comments_id`
FROM (`mso_comments`)
WHERE `comments_page_id` =  '9'
AND `comments_author_ip` =  '192.168.0.41'
AND `comments_content` =  'выфвыфвыф'
		   13 Query	SELECT `comusers_id`, `comusers_password`
FROM (`mso_comusers`)
WHERE `comusers_email` =  'fafofu@yandex.ru'
		   13 Query	INSERT INTO `mso_comments` (`comments_page_id`, `comments_comusers_id`, `comments_author_ip`, `comments_date`, `comments_content`, `comments_approved`, `comments_parent_id`) VALUES ('9', '3', '192.168.0.41', '2017-10-24 15:32:32', 'выфвыфвыф', 1, '0')
		   13 Query	SELECT `comusers_id`, `comusers_count_comments`, COUNT(comments_comusers_id) as comusers_count_comment_real
FROM (`mso_comusers`)
LEFT JOIN `mso_comments` ON `mso_comusers`.`comusers_id` = `mso_comments`.`comments_comusers_id`
WHERE `mso_comments`.`comments_approved` =  '1'
GROUP BY `comments_comusers_id`
		   13 Query	SELECT `mso_page`.`page_id`, `mso_page`.`page_slug`, `mso_page`.`page_title`, `mso_comments`.*, `mso_users`.`users_id`, `mso_users`.`users_nik`, `mso_users`.`users_count_comments`, `mso_users`.`users_url`, `mso_users`.`users_email`, `mso_users`.`users_avatar_url`, `mso_comusers`.`comusers_id`, `mso_comusers`.`comusers_nik`, `mso_comusers`.`comusers_count_comments`, `mso_comusers`.`comusers_allow_publish`, `mso_comusers`.`comusers_email`, `mso_comusers`.`comusers_avatar_url`, `mso_comusers`.`comusers_url`
FROM (`mso_comments`, `mso_page`)
LEFT JOIN `mso_users` ON `mso_users`.`users_id` = `mso_comments`.`comments_users_id`
LEFT JOIN `mso_comusers` ON `mso_comusers`.`comusers_id` = `mso_comments`.`comments_comusers_id`
WHERE `mso_page`.`page_id` =  '9'
AND `mso_comments`.`comments_approved` =  '1'
AND mso_page.page_id = mso_comments.comments_page_id
AND `mso_page`.`page_status` =  'publish'
ORDER BY `mso_comments`.`comments_date` asc
		   13 Quit`

**Comment by maxsite** [comment]
Смотрите на insert.

```
INSERT INTO `mso_comments` (`comments_page_id`, `comments_comusers_id`, `comments_author_ip`, `comments_date`, `comments_content`, `comments_approved`, `comments_parent_id`) VALUES ('9', '3', '192.168.0.41', '2017-10-24 15:32:32', 'выфвыфвыф', 1, '0')
```

**Comment by Fafofu** [comment]
Error Code: 1364. Field 'comments_author_name' doesn't have a default value

**Comment by maxsite** [comment]
Кажется понял. У вас MySQL работает в строгом режиме. Попробуйте добавить в массив $ins_data еще одну строчку, чтобы получилось так: 
```
$ins_data = array (
							'comments_page_id' => $comments_page_id,
							'comments_comusers_id' => $comusers_id,
							'comments_author_ip' => $comments_author_ip,
							'comments_date' => $comments_date,
							'comments_content' => $comments_content,
							'comments_approved' => $comments_com_approved,
							'comments_parent_id' => $comments_parent_id,
							'comments_author_name' => '',
							);
```

**Comment by Fafofu** [comment]
Хехей!!! Добавляется комментарий :))) 👍  Чей был косяк?

**Comment by Fafofu** [comment]
Да. 10 секунд страница отрабатывается при добавлении комментария.

`Имя	Протокол	Метод	Результат	Тип содержимого	Получено	Время	Инициатор
http://fafofu.ru/page/soft_pdf_xchange-viewer1	HTTP	POST	302	text/html	1,5 КБ	10,2 с	document`

**Comment by maxsite** [comment]
Я бы сказал — стечение обстоятельств. :-) Новые версии MySQL часто используют строгий режим, где шаг влево - расстрел. Внесу изменения в MaxSite CMS. Спасибо за помощь. :-)

**Comment by Fafofu** [comment]
А про тормоза новый запрос сделать?

**Comment by Fafofu** [comment]
> Внесу изменения в MaxSite CMS. Спасибо за помощь. :-)

На сколько я понимаю, нужно в базе данных внести изменения, добавив значение по умолчанию? Или лучше править PHP? (Я уже конечно php подправил в трёх местах. Но может лучше в базе данных?)

**Comment by maxsite** [comment]
> А про тормоза новый запрос сделать?

Тут ничего не скажу. Погоняйте немного у себя, может так сервер настроен.

> На сколько я понимаю, нужно в базе данных внести изменения, добавив значение по умолчанию? Или лучше править PHP? (Я уже конечно php подправил в трёх местах. Но может лучше в базе данных?)

Будет и там, и там. Проблем не будет.
