### ISSUE TITLE
Пагитация

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#224]
Я не понимаю :( Как? КАК? Как это использовать? Инструкцию найти не могу. Опишите пошагово как в записи (типа blog), если запись длинная, разделить её на несколько страничек с перелистыванием?

**Comment by maxsite** [comment]
Вы про плагин multipage?

**Comment by Fafofu** [comment]
Хм... видимо.

**Comment by Fafofu** [comment]
А то смотри какая большая запись получается :( fafofu.ru

**Comment by Fafofu** [comment]
Я разобрался (методом научного тыка :)
Вначале включаем плагин "multipage" и потом для его работы выбираем один из плагинов "pagination" они по разному выводят перелистывание страничек. Потом в статье, в том месте где ты хочешь чтоб был переход на следующую страницу вставляешь [pagebreak]
Есть ещё настройки в плагинах, но пока ничего не понятно :)
