### ISSUE TITLE
Невозможно юзеру разлогиниться в 0.862

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#225]
Есть сайт на 0.862. Есть несколько юзеров. Пока на разных компах пытались использовать разных юзеров - всё было нормально. Но потом на одном браузере попытались перейти с одного юзера на второго. Потом, после перехода, не получается вернуться к первому. При нажатии ссылок в админке "Выход" - происходит только редирект на /admin

Что за баг такой? Может в новых версиях уже решили, а я просмотрел? Подскажите, пожалуйста.

**Comment by maxsite** [comment]
Редирект идёт на ту страницы с которой был выход. Попробуй через форму сайдбара войти.

**Comment by vimruler** [comment]
Добавил виджет авторизации. Авторизовался с главной страницы. Перешёл в админку. Нажимаю ссылку "Выход" ( /admin/logout ии /logout )  - происходит перебрасывание на главную страницу сайта. Разлогинивания не происходит. 

Заметил, что при разлогинивании остаётся кука ci_session.  Если её вручную удалить, то разлогинивание происходит.

Однако, добавление в функцию _mso_logout (которая якобы вызывается при открытии страницы /logout ) кода, который должен бы удалять куку:

```php
$url = (isset($_SERVER['HTTP_REFERER']) and $_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
mso_add_to_cookie('ci_session', '', time() - 31500000, $url); // в куку для всего сайта
```
Ничего не происходит. Вообще, если поставить в начале этой функции, например, _pr($ci); то ожидаемого останова с выводом содержимого переменной не происходит. Как будто до этой функции вообще не доходит выполнение при открытии адреса /logout

Или я чего-то не понял в логике работы этой функции?

**Comment by maxsite** [comment]
Странно. Может какой-нибудь кэш используется? Я такой проблемы не вижу. Все нормально разлогинивается в любом порядке и месте.

Функция (в этом коде) mso_add_to_cookie() ставит куку с просроченным временем. Там же идет редирект, при котором кука и удаляется.

Проверь, может какие-то php-ошибки в логах. И в другом браузере. Может и плагин какой влияет...

**Comment by vimruler** [comment]
Действительно странно. На сайте никаких кешей не используется. Апач без nginx и без модулей кеширования. Локально и у хостера воспроизводится.

php ошибок нет в логах.

Посмотрел более свежие версии движка - вроде нет такой проблемы. Жаль только обновиться нельзя пока.

> Функция (в этом коде) mso_add_to_cookie() ставит куку с просроченным временем. Там же идет редирект, при котором кука и удаляется.

Это понятно. Для меня не ясно почему исполнение не доходит до этого места вообще. Там хоть что ставь - нет остановки по die(). Логично ведь, если во view для logout вместо функции  _mso_logout поставить die, то сайт просто должен белый экран показывать. Но этого нет, ибо происходит редирект.

**Comment by maxsite** [comment]
Эта вьюшка часть контролёра, а mso_add_to_cookie() только ставит куку для удаления другой куки уже в нём и при этом если стоит кука для редиректа, то идет редирект. :-) Поэтому скорее всего die ты ставишь где-то после редиректа, вот его и не видно. Принципиально логин/разлогин в 0.90 не менялся, хотя может какие-то правки и были. Я уже просто не помню... Не проще ли обновиться на новые версии?

**Comment by vimruler** [comment]
> Эта вьюшка часть контролёра, а mso_add_to_cookie() только ставит куку для удаления другой куки уже в нём и при этом если стоит кука для редиректа, то идет редирект. :-) Поэтому скорее всего die ты ставишь где-то после редиректа, вот его и не видно. 

Редирект в коде вырубал - не помогает. Лазил в контроллер - пока не увидел что там можно ещё проверить. Die ставил там, где нужно - ты же понимаешь, что в том месте трудно промахнуться? ;-)

> Принципиально логин/разлогин в 0.90 не менялся, хотя может какие-то правки и были. Я уже просто не помню... Не проще ли обновиться на новые версии?

Сегодня дошли руки накатить 98 версию движка. Причём накатывал так, что заменил всё, кроме шаблона и папки shared. Тестил на последней версии OpenServer с включенным Apache 2.4-x64 без nginx. Php-5.5-x64. Результат - проблема сохранилась!

Плагинов кеширования - нет. Глобальное кеширование через настройку шаблона - выключил.

Ранее не хотелось обновляться потому, что есть плагины, интерфейс которых ломается в новом дизайне админке.

А как ты тестишь? Создал двух юзеров и потом по очереди авторизуешься в админке и выходишь по ссылке /logout ?

**Comment by vimruler** [comment]
Причём первый раз разлогиниться получается. Но второй и последующие - нет. Заблокировал редиректы - всё равно редиректит. Грешу на кеш браузера, ибо после его чистки снова всё первый раз срабатывает. Правда не ясно тогда другое - в движке же вроде задаются заголовки nocache, тогда чего браузерам ещё надо?

Firefox и Chrome смотрел - одинаково, проблема воспроизводится

**Comment by maxsite** [comment]
Ну так и смотрю. :-) Вход что через сайдбар, что через /login. Происходит залогирование, можно на свою страницу зайти. После выход через /logout Всё, выход как положено. Испльзую Open Server с php 7.0.

**Comment by maxsite** [comment]
Илья, на чистой установке проверял?

**Comment by vimruler** [comment]
Нашёл причину. В .htaccess:

```
<ifModule mod_headers.c>
<filesMatch "\.(html|htm|php)$">
Header set Cache-Control "max-age=172800, private, must-revalidate"
</filesMatch>
</ifModule>
```
Эта штука перебивает заголовок и браузер кешировал редирект, из-за чего до logout не доходил запрос.

Можно закрыть тикет.

**Comment by maxsite** [comment]
:)
