### ISSUE TITLE
Ошибки при компиляции style.less

### ISSUE THREAD

**Issue by romangasymov** [maxsite/cms#226]
Здаствуйте!

На днях решил "вырости" из WP, осваиваю вашу. 
Начал типографику в base.less и menu.less но никаких изменений не заметил.

В readme в assets вы уточняете что компилирование .less лежит целиком на нас. Пока шаманил с бубном less.js и автокомпайлом Grunt ничего не получалось. Наткнулся в гугле на Koala, и эта красота при попытке собрать единый style.css мне выдала:

```
/Users/User/Downloads/cms-97/application/maxsite/templates/default/assets/less/style.less
SyntaxError: variable @undefined is undefined in /Users/User/Downloads/cms-97/application/maxsite/templates/default/assets/less/unicss/unicss.less:295:0
294 
295 .border_list_color_loop(length(@border_list_color));
296 
```

И сколько бы не заданных переменных я бы не исправлял, приходят новые. Либо я криворукий дилетант по части .less либо c файлом что-то.

Скомпилировать style.css Ооооочень хотелось бы. так как во всём остальном я безумно доволен. Скорость, простота, переезд блога идёт на ура, но к стилям пока не притронуться. 

Могу конечно обойтись UniCss прямо через код, для меню, как в footer.
Шрифт тоже можно через доп. профили подгрузить, но хотелось бы ваш механизм использовать, ведь модули хорошие, удобство на более поздних стадиях разработки гарантированно.

Благодарю за уделённое внимание.

**Comment by maxsite** [comment]
Попробуйте WinLess, только там влючите опцию использовать глобальный less.js.

**Comment by romangasymov** [comment]
Абсолютно такой же ответ от WinLess.

[https://scontent-ams3-1.xx.fbcdn.net/v/t35.0-12/23191753_1702128559860218_579262079_o.png?oh=afbf202809a2a824630189db518fd9b7&oe=59FD3A29](url)

[https://scontent-ams3-1.xx.fbcdn.net/v/t35.0-12/23223021_1702128549860219_1511168880_o.png?oh=a7e63e54cea0f8ae5075d4aa0248f188&oe=59FE4E5A](url)

**Comment by maxsite** [comment]
Для компиляции следует указать только style.less, а остальные не отмечать.
