### ISSUE TITLE
Шаблон на заказ

### ISSUE THREAD

**Issue by mowshon** [maxsite/cms#227]
Здравствуйте!

Так как форум в режиме чтения, то надеюсь помогут тут.
Есть несколько сайтов (~10) на MaxSite разной тематики.

Нужны тематические шаблоны:
строительная тематика, компьютеры, медицина...

Если есть знакомые или вы сами занимаетесь разработкой шаблонов под MaxSite, то оставьте контакты и приблизительно цену за 1 шаблон.

**Comment by maxsite** [comment]
На http://wbloger.com/ смотрели?
