### ISSUE TITLE
Установка проходит без ошибок, но  CMS не работает

### ISSUE THREAD

**Issue by o100lop** [maxsite/cms#229]
php 7.0.22
mysql 5.0.12
Устанавливал CMS по инструкции (скачивал дистрибутив и распаковывал вручную, пробовал и автоустановщик), в процессе установки и после никаких ошибок и предупреждений не появляется, пишет, что все прошло успешно. После установки не могу зайти в админку. Директория с сайтом выглядит так.
> 
application  index.php  robots.txt  sitemap.xml  system  _update_mso  _update_mso.zip  uploads

**Comment by maxsite** [comment]
Что пишет?

**Comment by o100lop** [comment]
Not Found

The requested URL /login was not found on this server.

**Comment by o100lop** [comment]
![image](https://user-images.githubusercontent.com/2247341/32507788-8019d256-c3f9-11e7-90ee-15412a87a989.png)

**Comment by maxsite** [comment]
Проверьте .htaccess.

**Comment by o100lop** [comment]
Тот, что в корневой папке сайта выглядит так:
```
Options +FollowSymLinks
Options -Indexes
DirectoryIndex index.php index.html
AddDefaultCharset UTF-8

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L,QSA]
# or for fastCGI
# RewriteRule . /index.php [L]
</IfModule>

<IfModule deflate_module>
AddOutputFilterByType \
DEFLATE \
application/javascript \
text/css \
text/html \
text/javascript \
text/plain \
text/xml
</IfModule>

<ifmodule mod_expires.c>
<filesmatch ".(jpg|jpeg|gif|png|svg|ico|css|js|woff)$">
ExpiresActive on
ExpiresDefault "access plus 1 month"
</filesmatch>
</ifmodule>
```
Что конкретно нужно проверить?

**Comment by maxsite** [comment]
Другие страницы сайта нормально доступны? По адресу сайт/admin что показывает?

**Comment by o100lop** [comment]
Ни одна страница сайта не доступна (/admin тоже), всегда показывает "404 Not Found"

**Comment by maxsite** [comment]
Скорее всего php работает в режиме CGI. В readme найдите замену для .htaccess. Попробуйте с ним.

**Comment by o100lop** [comment]
phpinfo пишет
`
Server API | Apache 2.0 Handler
`
`<?php
$sapi_type = php_sapi_name();
if (substr($sapi_type, 0, 3) == 'cgi') {
    echo "You are using CGI PHP\n";
} else {
    echo "You are not using CGI PHP\n";
}
?>`
говорит You are not using CGI PHP

**Comment by maxsite** [comment]
readme

**Comment by o100lop** [comment]
Перепробовал варианты .htaccess
```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# RewriteRule ^(.*)$ /index.php/$1 [L,QSA]
# or for fastCGI
# RewriteRule . /index.php [L]
</IfModule>
```

```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L,QSA]
# or for fastCGI
# RewriteRule . /index.php [L]
</IfModule>
```

```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# RewriteRule ^(.*)$ /index.php/$1 [L,QSA]
# or for fastCGI
RewriteRule . /index.php [L]
</IfModule>
```
добавлял в «application/config/config.php»
`$config['uri_protocol'] = "REQUEST_URI";`

результат не изменился.

**Comment by maxsite** [comment]
Сервер вообще .htaccess поддерживает? Пропишите там какую-нибудь белиберду - вываливается 500-ошибка?

**Comment by o100lop** [comment]
Благодарю за помощь! mod_rewrite был включен, но в конфиге apache2 нужно было прописать "AllowOverride All" соответствующей папке.
