### ISSUE TITLE
D4 - main-файл

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#23]
Несколько моментов, которые я хочу обсудить/предложить для будущего default-шаблона MaxSite CMS.

Есть некоторые моменты в текущем варианте, которые меня не устраивают и один из них main-файл. 

Напомню, сейчас это солянка из управляющих php-конструкций, вроде подключение компонентов, ушек и т.п. и непоследственной html-разметки. Анализ файла позволил выделить участки кода, которые никак не завязаны (в рамках main-файла) на html-разметку. Отсюда я пришел к выводу, что можно выделить такой код в отдельные файлы, оставив в main достаточно простые подключениия.

Чтобы было понятно, я разместил файлы в main/blocks. Сам main-файл размещается как обычно в main/main.php

```php
<?php if ($fn = mso_fe('main/blocks/body-start.php')) require($fn) ?>

<div class="header clearfix"><div class="wrap">
	<?php if ($fn = mso_fe('main/blocks/header.php')) require($fn) ?>
</div></div>

<?php if ($fn = mso_fe('main/blocks/header-out.php')) require($fn) ?>

<div class="layout-center-wrap"><div class="wrap flex flex-wrap-tablet main">

	<?php if ($fn = mso_fe('main/blocks/main-start.php')) require($fn) ?>

	<div class="content w70 w100-tablet"><div class="wrap">
		<?php if ($fn = mso_fe('main/blocks/content.php')) require($fn) ?>
	</div></div>
	
	<div class="sidebar1 w25 w100-tablet"><div class="wrap">
		<?php mso_show_sidebar('1', '<div class="widget widget_[NUMW] widget_[SB]_[NUMW] [FN] [FN]_[NUMF]"><div class="wrap">', '</div></div>') ?>
	</div></div>
	
	<?php if ($fn = mso_fe('main/blocks/main-end.php')) require($fn) ?>

</div></div>

<?php if ($fn = mso_fe('main/blocks/footer-pre.php')) require($fn) ?>

<div class="footer"><div class="wrap">
	<?php if ($fn = mso_fe('main/blocks/footer.php')) require($fn) ?>
</div></div>

<?php if ($fn = mso_fe('main/blocks/body-end.php')) require($fn) ?>

</body></html>
```

То есть здесь фактически оставлена только html-разметка. block-файлы, например header.php содержит более сложный код:

```php
if (function_exists('ushka')) echo ushka('header-start');

if ($fn = mso_fe('custom/header-start.php')) require($fn);

if ($fn = mso_fe('custom/header_components.php')) require($fn);
else
{
	if ($fn = get_component_fn('header_component1', 'menu-only')) require($fn);
	if ($fn = get_component_fn('header_component2')) require($fn);
	if ($fn = get_component_fn('header_component3')) require($fn);
	if ($fn = get_component_fn('header_component4')) require($fn);
	if ($fn = get_component_fn('header_component5')) require($fn);
}

if (function_exists('ushka')) echo ushka('header-end');
if ($fn = mso_fe('custom/header-end.php')) require($fn);
```
В этом файле (и других из block) нет html-разметки. То есть таким нехитрым способом у нас появляется возможность выполнять верстку непосредстено в main-файле, не задумываясь о сложном php-коде.

**Comment by cuprum** [comment]
Почему бы и нет? Только пусть в main в начале  останется head и body как сейчас:
``` php
# секция HEAD
if ($fn = mso_fe('custom/head-section.php')) require($fn); // подключение HEAD из файла
	else mso_default_head_section(); // подключение через функцию

?>

<body<?= (mso_get_val('body_class')) ? ' class="' . mso_get_val('body_class') . '"' : ''; ?>>
```

**Comment by maxsite** [comment]
Там остается полностью весь код, который и был. Я просто не привожу все main/blocks-файлы. :-)

**Comment by vimruler** [comment]
А в чём собственно сомнения? Хороший вариант разделить код и верстку. Возможно новичкам будет сложно сразу привыкнуть к логике. Но это тоже дело наживное.

**Comment by maxsite** [comment]
Тут дело даже не в новичках, а в том что php-логики в этом файле накопилось больше чем html-верстки. Я хочу, чтобы main файл мог быть полноценно используемым под любые задачи. Например если используется бустрап с его классами.

**Comment by vimruler** [comment]
Понятно. Возражений нет :)
