### ISSUE TITLE
Проблема с кодировкой ссылок после обновления с 0.84 до 0.90 (или 98)

### ISSUE THREAD

**Issue by alexvishweb** [maxsite/cms#230]
Решил обновить древнюю версию движка, но при переходе на версию 0.90 (с 98 то же самое, в версиях до 0.90 всё было нормально) возникла проблема со ссылками, у которых в url были японские иероглифы. Например, "スタイル" превращается во что-то такое "atilde�sup1atilde�iquestatilde�currenatilde�laquo". Обычный текст с иероглифами отображается нормально, проблема только в href ссылок, из-за чего они становятся нерабочими, и выдается ошибка 404 при переходе по ним. С чем это может быть связано и как починить?

Обновлял на локалке. OpenServer, PHP 5.3, MySQL 5.5, mod_rewrite в .htaccess включен.

**Comment by maxsite** [comment]
Юникод в ссылках преобразуется в английские символы. Думаю, что оптимально — это написать свой плагин, который будет цепляться на хук **slug**, или **slug_do** где и сделать такие специфичные замены.  См. функцию `mso_slug()`.

**Comment by alexvishweb** [comment]
Спасибо!
Не знаю, дойдут ли руки до плагина, пока просто закомментировал строчку 
$slug = htmlentities($slug);
в функции mso_slug() (application/maxsite/common/common.php)

**Comment by alexvishweb** [comment]
Сделал по-быстрому плагин.
Буквально пара строк:

mso_hook_add( 'slug', 'allow_unicode_links');

function allow_unicode_links($slug) 
{
	$slug = html_entity_decode($slug);
	return $slug;
}

Не знаю, плохое это решение или нет, но работает. Можно ли его куда-то выложить, обсудить и т.п.?

**Comment by maxsite** [comment]
Так а что обсуждать? С японскими иероглифами вряд ли кто-то еще работает. :) Проверяйте что в итоге, если все ок, значит ок.

**Comment by alexvishweb** [comment]
Ну, мало ли... Впервые плагин для Maxsite делал, поэтому был не уверен в правильности своих действий. Но раз ОК, значит, ОК :)
Есть ли какое-нибудь место, где собраны все плагины к Maxsite, и куда можно было бы добавить этот? Кому-нибудь, может и пригодится. В конце концов, не только в японском языке есть символы, не попадающие под нынешнюю таблицу преобразований.

**Comment by maxsite** [comment]
У себя или на maxhub.ru у Ильи наверное можно.

**Comment by alexvishweb** [comment]
Рано я радовался - функция декодирования приводила старые ссылки на сайте в порядок, но при создании новых постов, заголовки переносились в короткие ссылки без изменений со всеми пробелами, заглавными буквами, символами и пр. В конце концов, я просто скопировал в плагин функцию mso_slug из старой версии Maxsite, благо она отличалась всего двумя строчками

```
$slug = strtr(trim($slug), $repl);
$slug = htmlentities($slug); // если есть что-то из юникода
```

Пока я проверял ссылки, возникли ещё пара вопросов:
1) Новые посты почему-то не публикуются на главной. Их можно открыть напрямую по ссылке, но на главной они не появляются. Кэширование отключено, если что.
2) Раньше в главном меню была статичная страница. В настройках главного меню она была указана как "страница | Страница", Но теперь открывается только если указать page "page/страница | Страница". Можно ли как-то сделать без page?

**Comment by maxsite** [comment]
Вообще юникод отключается строчкой с htmlentities(), но тогда ссылки будут содержать иероглифы. Мне кажется, что лучший вариант — это ручное указание адреса ссылки при редактировании записи. Тогда проблем мне будет. Или ищите правила преобразования иероглифов в английский текст.

> Новые посты почему-то не публикуются на главной. Их можно открыть напрямую по ссылке, но на главной они не появляются. Кэширование отключено, если что.

Наверное дата публикации ещё не наступила. Проверьте смещение времени в настройках.

> Раньше в главном меню была статичная страница. В настройках главного меню она была указана как "страница | Страница", Но теперь открывается только если указать page "page/страница | Страница". Можно ли как-то сделать без page?

Настроить в `config/mso_config.php`, но лучше сделать редирект на новый адрес.

**Comment by alexvishweb** [comment]
Проблема была действительно во времени.
Теперь, вроде, со всем разобрался, спасибо!

Можно небольшое пожелание по юзабилити? В редакторе записей не хватает кнопки удаления записи. Сейчас, чтобы удалить запись, нужно искать её во всех записях, что, опять же, весьма проблематично, т.к. нет фильтра по названию. И во всех записях желательно перенести блок с кнопкой "удалить" с самого низа наверх, т.к. сейчас для выполнения самого часткого действия - удаления последней записи - нужно пролистывать страницу (а новички вообще, наверное, очень долго ищут, кнопку удаления)

**Comment by maxsite** [comment]
Удаление — редкая операция.
