### ISSUE TITLE
Обновление sitemap.xml

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#231]
По какой причине может перестать обновляться этот файл? Как понять, что он должен обновляться?
Он же вроде автоматически должен это делать?

**Comment by maxsite** [comment]
Плагин включен?

**Comment by Fafofu** [comment]
sitemap 2.1 - Да. Мне кажется всё работать перестало после того, как мы все плагины отключали...

**Comment by maxsite** [comment]
xml_sitemap

**Comment by Fafofu** [comment]
Ох, я его и не заметил :) Внизу то. Всё, включил, всё работает :) Спасибо.
