### ISSUE TITLE
IDN домены (в т.ч. кириллица) - старые песни о главном

### ISSUE THREAD

**Issue by iachaly** [maxsite/cms#232]
Пришлось создать новую тему, так как [старую открыть нельзя](https://github.com/maxsite/cms/issues/194). Подтверждаю наличие ошибки `Disallowed Key Characters` в новой версии 98 не смотря на вроде бы [внесённые изменения](https://github.com/maxsite/cms/commit/ac5cb78858c46b22c36510f9a9882aeae2218998). Патч за моим авторством всё также успешно исправляет ошибку, как и решение с процентом от HaipaiUser, не будем копировать, смотрите в старой теме по ссылке.
Проверено и на старье, специально был собран и свежий сервер на Ubuntu 16.04, mysqlnd 5.0.12, PHP: 7.0.18

Добавлено: проблема касается и быстрой загрузки, для оперативного исправления товарищами, добавляю обновлённые файлы input и all-files. Что и где менять указано в старой теме.
[chaly-maxsite98patch.zip](https://github.com/maxsite/cms/files/1480652/chaly-maxsite98patch.zip)

**Comment by maxsite** [comment]
Открыл старую тему.
