### ISSUE TITLE
The Encrypt library requires the Mcrypt extension.

### ISSUE THREAD

**Issue by tanc41** [maxsite/cms#233]
Как справить? The Encrypt library requires the Mcrypt extension. после автоустановки перекидывает на сайт и белое окно с The Encrypt library requires the Mcrypt extension.

**Comment by maxsite** [comment]
Мы пока не поддерживаем php > 7.0

**Comment by tanc41** [comment]
но у меня на хостинге выбрано php 5.3

**Comment by maxsite** [comment]
Значит не включена php-библиотека Mcrypt.

**Comment by tanc41** [comment]
а вот с этого момента по подробнее

**Comment by tanc41** [comment]
жду

**Comment by maxsite** [comment]
Чего?

**Comment by tanc41** [comment]
как это включить и все такое

**Comment by maxsite** [comment]
100$ и поработаю для вас гуглом.

**Comment by tanc41** [comment]
хм вот хитрецы

**Comment by Den2016** [comment]
а при чем тут хитрость? Хостеру претензии предъявляйте  - почему у него библиотека не включена. А еще можно тупо проверить, какой на самом деле PHP на сервере. Опять же - если не знаете как - гугл в помощь. Подсказка - "проверить версию php"

**Comment by tanc41** [comment]
Ладно, это я решил. Теперь проблема такова.вошел в админку через комп, потом пытаюсь войти в админку через телефон пишет неправильный логин или пароль хотя все данные верны

**Comment by Den2016** [comment]
Правило первое - проблему решил - поделись решением.
Макс, можно закрывать.
А про админку с телефона а это уже претензии к производителям телефона/браузера. Не все браузеры в телефоне одинаково пригодны для MaxSiteCMS. Пробуйте более другие. У меня, например, только с хрома получается нормально залогиниться.
