### ISSUE TITLE
не входит в админку

### ISSUE THREAD

**Issue by tanc41** [maxsite/cms#234]
Теперь проблема такова.вошел в админку через комп, потом пытаюсь войти в админку через телефон пишет неправильный логин или пароль хотя все данные верны. И такое перегрузил комп захожу на сайт тоже пытаюсь зайти тоже говорит "неправильный логин или пароль " хотя стоит все верно

**Comment by Den2016** [comment]
а какие данные? У меня, к примеру, с одного компа логинится с именем, а с другого - только через e-mail

**Comment by tanc41** [comment]
Логинюсь именем

**Comment by Den2016** [comment]
ну дык пробуйте e-mail

**Comment by Den2016** [comment]
кстати, Макс, а почему именем не логиниться? Потому что оно может дублироваться?

**Comment by tanc41** [comment]
Ден, пытаюсь вместо логина вписать почту все равно не входит

**Comment by Den2016** [comment]
у всех входит, а у одного нет. Копайте на сервере. Проблему же с криптом как-то решили?
