### ISSUE TITLE
Качество изображений

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#235]
Я в настройках поставил качество "100" но изображения при заливке, становятся просто удручающего качества :( 

Но при этом само изображение которое залито, вроде как качеством нормальным... а при выводе плохого...

[image=http://fafofu.ru/uploads/screenshots/mini/2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg 2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg]http://fafofu.ru/uploads/screenshots/2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg[/image]

Что можно сделать?

**Comment by maxsite** [comment]
Значит размер исходного меньше, чем получаемого.

**Comment by Fafofu** [comment]
Э? Не понял.

**Comment by Fafofu** [comment]
Я вижу, что скрип который выводит изображение, сжимает его, и качество ухудшается. Где глянуть настройки скрипта?

**Comment by maxsite** [comment]
Качество — это качество jpg-файла. Стандарная возможность CodeIgniter библиотеки image_lib. Смотрите там, если интересно.

**Comment by Fafofu** [comment]
Я имею ввиду, качество отображаемого на экране. Картинка чуть чуть сжимается, (по вертикали и горизонтали) и в результате отображается не красиво... Вы же можете зайти на мой сайт и сами увидеть, что я имею в виду :)

**Comment by maxsite** [comment]
Если вы хотите, что-то показать, то указывайте прямые ссылки. ;-)

**Comment by Fafofu** [comment]
Да, я в первом посту же добавил кучу ссылок :) 
Вот статья http://fafofu.ru/page/foxmail-luchshij-pochtovyj-klient#
Первая картинка, посмотрите как она отображается на сайте.
А вот как она выглядит на самом деле
http://fafofu.ru/uploads/screenshots/2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg

Неужели не видно разницы?

**Comment by maxsite** [comment]
Ну а сслылку на миниатюру дадите?

**Comment by Fafofu** [comment]
Так я не про миниатюру... ты когда на картинку тыкашь, он же не миниатюру открывает... Я вот про это говорю:
![2017-11-28 17_52_35-foxmail -](https://user-images.githubusercontent.com/1073471/33326095-00531f24-d465-11e7-953a-538e9c93aa16.jpg)

**Comment by maxsite** [comment]
Я никуда не тыкаю. Это ваша прерогатива. Нет ссылок, нет разговора.

**Comment by Fafofu** [comment]
Как я могу прислать ссылку на выводимую картинку плагином? о_О

**Comment by Fafofu** [comment]
Вот формируется DIV для вывода изображения:
`<div id="lightbox-container-image-box" style="overflow: hidden; width: 702px; height: 553px;"><div id="lightbox-container-image"><img id="lightbox-image" style="display: inline;" src="http://fafofu.ru/uploads/screenshots/2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg"><div style="display: block;" id="lightbox-nav"><a href="#" id="lightbox-nav-btnPrev" style="display: none; height: 553px; background: url(&quot;//fafofu.ru/application/maxsite/plugins/lightbox/images/lightbox-blank.gif&quot;) no-repeat transparent;"></a><a href="#" id="lightbox-nav-btnNext" style="display: block; height: 553px; background: url(&quot;//fafofu.ru/application/maxsite/plugins/lightbox/images/lightbox-blank.gif&quot;) no-repeat transparent;" data-vivaldi-spatnav-clickable="1"></a></div><div id="lightbox-loading" style="display: none;"><a href="#" id="lightbox-loading-link" data-vivaldi-spatnav-clickable="1"><img src="//fafofu.ru/application/maxsite/plugins/lightbox/images/lightbox-ico-loading.gif"></a></div></div></div>`

Размеры картинки соответствуют загруженной. Но отображается качество хуже...

**Comment by maxsite** [comment]
Я не понимю, вы так веселитесь или реально не можете открыть запись и дать две ссылки на обычную и mini-версию изображение?

**Comment by Fafofu** [comment]
В самом первом своём посту я выложил ссылку на "image" она содержит в себе обе ссылки. Мне не сложно. Могу и ещё раз скопировать.
http://fafofu.ru/uploads/screenshots/mini/2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg
http://fafofu.ru/uploads/screenshots/2017-11-08-10_31_59-ustanovka-fox-mail-7.2_.jpg

**Comment by maxsite** [comment]
В первом посте не ссылки, а непонятно что. 

И что вам не нравится в этих файлах?

**Comment by Fafofu** [comment]
Я же и говорю... файлы нормального качества, а выводятся качество хуже... как ещё объяснить, если вы не можете посмотреть.

**Comment by maxsite** [comment]
Я могу посмотреть, но мне нужна полная информация. На дефолтном шаблоне проверяли? Версия MaxSite CMS?

**Comment by Fafofu** [comment]
Версия 97
Да. Только что проверил. Качество хуже.

**Comment by maxsite** [comment]
Качество тут ни при чём. Так поджимает браузер. Проблема либо в самом плагине, либо в стилях. Нужно разбираться почему не формируется 100% размер.

**Comment by Fafofu** [comment]
Я рад, что мы поняли друг друга :)

**Comment by maxsite** [comment]
Воспроизвел проблему у себя. 

Дело в самом плагине. Он выставляет размер лайтбокса по ширине картинки. Но, в стилях используется внутренний отступ 10px (визуально это белые поля), что и приводит к масштабированию картинки браузером.

Исправить наверное можно, но только если редактировать сам js-скрипт. С точки зрения обычных фото, проблема несущественна.

Если это критично, то можете в файле jquery.lightbox-0.5.css убрать строчку 42
`#lightbox-container-image { padding: 10px; }`

Это уберёт отступ и белую окантовку, но сама картинка будет в 100% масштабе.

**Comment by Fafofu** [comment]
Воооот, уже ближе к телу :) Но зачем же так кардинально то, если всё убрать, оказывается, что текст под картинкой приползает к картинке, фе :) Я сделал вот так:
`#lightbox-container-image { padding: 0px 0px 10px 0px; }`
И теперь и картинки хорошего, прости хоспади "качества" и выглядит красиво.
Мы же с вами за быстрый и красивый интернет ;)
Спасибо большое за помощь.

**Comment by maxsite** [comment]
Согласен, так получше будет. Наверное внесу изменения в плагин.
