### ISSUE TITLE
AutoPost Ошибки PHP

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#236]
Добавлаяю запись через AutoPost, запись создаётся но пишутся вот такие ошибки:
![2017-11-28 13_49_11- - - autopost - _pro_ - qupzilla](https://user-images.githubusercontent.com/1073471/33316147-f5b7c036-d443-11e7-80c7-234c8453dddc.jpg)

Шаблон выглядит вот так:
```
TITLE: Название статьй
CAT+: Катягория
STATUS: draft
ID_AUTHOR: 2
META-image_for_page_out: no-page
META-title: Название статьй
---
[h4]Первое предложение[/h4]
Что будем делать

Зачем это будем делать

[cut]


Бла бла бла текст
картинки
```

**Comment by maxsite** [comment]
Ошибку прочитать можете?

**Comment by Fafofu** [comment]
Если такая ошибка, то нужно раскомментировать строку в PHP.ini "always_populate_raw_post_data"
