### ISSUE TITLE
Вставить в текст HTML теги как не теги %)

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#237]
Добрый день. Пытаюсь в текст статьи вставить вот такой текст
`</VirtualHost>`
Но как не бьюсь, он не хочет вставляться. Можно конечно использовать "ascii html" для замены угловых кавычек. Но это не очень удобно :( Может в следующей версии CMS можно добавить типа таблички, сверху нажал, и она предлагает замену символов... или добавить какой-то тег в который заключаешь, к примеру [ascii][/ascii] и текст заключённый в этот тег, если есть символы, то они автоматически подменяются при генерации страницы? А :)

**Comment by maxsite** [comment]
PRE для этого есть.

**Comment by Fafofu** [comment]
Да. Только он выделяет фон и переносит текст на новую строку :)

![2017-11-30 12_45_16- apache _mod_ratelimit_](https://user-images.githubusercontent.com/1073471/33424293-70529aa8-d5cc-11e7-90eb-06fd01e81d8e.jpg)

**Comment by maxsite** [comment]
Строчный элемент — CODE. Ну или html-сущностью — думаю, запомнить и набрать` &lt;` и `&gt;` не большая проблема.

**Comment by Fafofu** [comment]
Если убрать это в `<code>` то отображается пустота :) 
Ещё есть случае вот такие word:) и в конце поставиться смайлик. И как не крути поставиться. Только если заменять на ascii...

**Comment by maxsite** [comment]
Не пустота, а html-код. Ctrl+U в FireFox. Всех случаев замен не предусмотреть. Тем более, если это техническая информация.

**Comment by Fafofu** [comment]
Как скажите :) Мне как пользователю было бы удобнее если бы была табличка с ascii кодами :)
