### ISSUE TITLE
Возможно ли произвольное размещение ушек (ushka)?

### ISSUE THREAD

**Issue by eld0rad0** [maxsite/cms#239]
Версия Maxsite CMS 98
Шаблон MAX Turdus 2.0
Вопрос:
Сайт использует структуру с левым сайдбаром, в разделе файлы есть файл main/left-sidebar/main.php в нем есть строки, которые как я понял отвечают за краткий вывод страницы связанной с выбранной рубрикой:
/div class="content flex-order2 flex-order1-tablet w75 w100-tablet pad20-tb  pad60-l pad0-l-tablet"
php if ($fn = mso_fe('main/blocks/content.php')) require($fn)
div/ 
 
можно ли каким то образом привязать сюда вывод ушек, с возможностью указания в какой рубрике они будут отображаться, то есть я создаю рубрику /Байкал/, в ней мне надо что бы отображались 3 ушки, предположим, /реки/,/берега/, /мели/  и так по аналогии для каждой рубрики, а уже в теле ушки у меня будет ссылка на страницу с подробным описанием.

**Comment by maxsite** [comment]
В файле `main/blocks/content.php` прописаны подключения других файлов и ушек для кастомизации вывода.
