### ISSUE TITLE
D4 — функции шаблона

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#24]
Я буду выкладывать по отдельным тикетам свои соображения, чтобы после не путаться и чтобы держать вас в курсе своих планов. :-)

Функции шаблона работают через functions.php. В нем подключение файлов из shared_dir и custom/my_functions.php. Я хочу разорвать эту связку и переместить два файла из shared functions/template.php и functions/set_val.php в каталог шаблона custom/template.php и custom/set_val.php. 

Файл template.php содержит только функции шаблона. Единственная функция — mso_add_file() её можно перенести в common.php, поскольку будет востребована всеми шаблонами. Самая спорная функция mso_default_head_section(), если она будет на уровне каталога шаблона, то может меняться под задачу вебмастера.

Файл set_val.php переносим в шаблон, поскольку в нем, опять же, только то, что относится к шаблону.

**Comment by maxsite** [comment]
Вот результирующий function.php шаблона:

```php
mso_register_sidebar('1', tf('Первый сайдбар'));

# основные функции шаблона
if ($fn = mso_fe('custom/template.php')) require_once($fn);

# набор из mso_set_val
if ($fn = mso_fe('custom/set_val.php')) require_once($fn);

# библиотека для вывода записей в цикле и вывод колонок
require_once(getinfo('shared_dir') . 'stock/page-out/page-out.php');

# библиотека для работы с изображениями
require_once(getinfo('shared_dir') . 'stock/thumb/thumb.php');

# дополнительный файл my_functions.php
if ($fn = mso_fe('custom/my_functions.php')) require_once($fn);
```

**Comment by vimruler** [comment]
Т.е. получается, что теперь можно будет некоторые неиспользуемые в шаблоне функции удалить (т.е. не тянуть из шареда просто так за компанию), а некоторые переопределить под нужды шаблона (как раз речь про mso_default_head_section, которая действительно иногда напрашивалась на правки)? Если так, то хорошая идея.

**Comment by maxsite** [comment]
Да, верно. Из shared по сути берем только type-файлы. Под вопросом ещё page-out.php и thumb.php. Они используются в type-файлах, поэтому их логично подключать где-то на уровне main-start.php.
