### ISSUE TITLE
Неверный код капчи при выключенном плагине капчи

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#240]
С наступающим!
Чистая установка на host-food, версия 98.
При попытке зарегистрироваться комюзеру по ссылке "Регистрация" (не при комментировании) выдает "Неверный код капчи". Плагин выключен, после установки не включалось ни одного плагина.
При комментировании авторегистрация проходит, как и положено.

**Comment by maxsite** [comment]
Это по ссылке registration?

**Comment by Den2016** [comment]
да

**Comment by maxsite** [comment]
Ок, посмотрю.
