### ISSUE TITLE
Произвольный адрес страницы для загрузки файлов

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#242]
Давно вынашивал идею, но не знаю, стоит ли её реализовывать.

Сейчас файлы страницы автоматом привязываются к адресу uploads/_pages/ID. Но, теоретически мы можем в опции указать любой другой каталог для записи. Я думаю, что схема будет такая: делается мета-опция. Если она пустая, то используется каталог по-умолчанию, основанный на ID-записи. Если заполнен, то путь ищется относительно uploads/. Если его нет, то он создается. Если есть, то работаем с ним.

Теоретически это позволит «привязывать» к записи любые файлы из любых uploads-каталогов. Поскольку в тексте записи всё равно адрес указывается полный, то без разницы, какие файлы под записью фигурируют.

Другой вариант — это все-таки сделать не мета-опцию в настройках записи, а отдельный select, где можно выбрать произвольный каталог, как это сейчас в Загрузках. В этом случае вообще можно как-то на лету обновлять список файлов и использовать для страницы.

**Comment by vimruler** [comment]
А есть реальные задачи, где такая смена папок у записи на что-то влияет? Что-то даже придумать сразу не получается. Наоборот, когда жестко задано расположение, то уже можно многим не заморачиваться и привязываться именно к просчитываемому адресу.

**Comment by maxsite** [comment]
Да, бывают. Первая — при переносе записей, когда меняется ID (autopost). Вторая — иногда удобно взять картинку из другой записи, если будет select, то просто переключил каталог, добавил файл. :)

**Comment by vimruler** [comment]
Понятно. Да, тогда вариант с селектом как-то более понятен и удобен.

**Comment by maxsite** [comment]
Да, только непонятно как в селекте сделать навигацию по каталогам. Либо всё загнать как на странице Файлы, либо ... ?

**Comment by vimruler** [comment]
Так то в этом списке не всегда нужны все папки и на мой взгляд проблема только в том, как сделать выпадающий список не таким безразмерным. 

Поэтому можно было бы придумать некую глобальную опцию, где: вариант №1 - задавать список нужных папок, вариант №2 - задавать список исключения папок, а все остальные добавлять. вариант №3 - давать подключать type_foreach для формирования списка доступных для выбора папок.

**Comment by maxsite** [comment]
Проблема даже не в самих каталогах, а в их подкаталогах. Даже в том же uploads/_pages/ их может оказаться сотни. На вскидку приходит вариант, где вместо select использовать обычный тектсовы input, а рядом кнопка Select Dir. По ней всплывающее окно, где и будет происходить выбор одного каталога.

**Comment by vimruler** [comment]
> На вскидку приходит вариант, где вместо select использовать обычный тектсовы input, а рядом кнопка Select Dir. По ней всплывающее окно, где и будет происходить выбор одного каталога.

Нормальный вариант.

**Comment by maxsite** [comment]
Осталось придумать как это реализовать. :)
