### ISSUE TITLE
Идеи для консоли админ-панели MaxSite CMS

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#244]
Хотелось бы её как-то разнообразить. :) Мы раньше уже пытались, но ничего путного не вышло. За пару лет, я остановился на вот таких идеях.

1. Выводить страницы в режиме черновик. Просто ссылки на редактирование. Может как-то отмечать очень старые черновики.

2. Расчёт «эффективности», где смотрятся все рубрики и в них даты последней записи. Те рубрики, где не было давно публикация, выводится какое-то уведомление с предложение опубликовать запись.

3. Todo-список дел. Произвольный вариант в виде «чекбокс + текст/дата создания + кнопка Удалить». Тут можно попробовать придумать добавление в todo задачи не только из консоли, но и вообще по отдельному пункту меню в виде всплывающего окна, а значит будет доступен на любой странице админки. 

4. Новости MaxSite CMS. Сейчас это инфоблок в iframe и rss-лента. Rss можно отключить в админке, а iframe пока нет. В идеале было бы неплохо сделать загрузку iframe с гитхаба (или хотя бы файла с версией и датой), но как это сделать пока не знаю... Отказываться от iframe не хочется, поскольку это проще, чем организовывать http-запросы.

5. Произвольный блок в консоли. Уже есть в основных настройках.

**Comment by vimruler** [comment]
1. +
2. +
3. А это разве не на уровне плагина должно решаться? Хук же есть для подключения... Нужно будет только что-то типа MicroToDo Тормоза прикрутить ( скрипт в паблике сейчас нашёл вот тут toly-blog.ru/microToDo.htm )
4. Понятно, что с гитхаба нужно бы тянуть, но что-то идей по реализации тоже нет...

**Comment by maxsite** [comment]
Реализовал основные идеи в MaxSite CMS 99. C todo пока нужно думать. Скорее всего пойдет в долгий ящик...
