### ISSUE TITLE
The requested URL /index.phpindex.php/page/about was not found on this server.

### ISSUE THREAD

**Issue by dredius** [maxsite/cms#245]
Здравствуйте, установлена последняя версия и у меня проблема в том что при открытии любой страницы появляется ошибка 

Not Found
The requested URL /index.phpindex.php/page/about was not found on this server.

Apache/2.4.18 (Ubuntu) Server at blog5.server.pro Port 80

но если я ввожу http://blog5.server.pro/index.php/page/about то все прекрасно работает, другие CMS системы почему то без проблем работают. 

что не так то!? :))

**Comment by maxsite** [comment]
Проверяйте .htaccess.

**Comment by dredius** [comment]
да я вот только недавно начал эту тематику изучать 
мне надо что то типо аля RewriteEngine включить? или чего подскажите пожайлуста.

**Comment by Den2016** [comment]
ну как бы да. Но начинать надо с логов апача

**Comment by WilhelmWas** [comment]
Вам ответили:
_Проверяйте .htaccess_
Это более чем понятно, для специалистов или опытных.

В Вашем же случае, выход единственный:
Найдите в директории (в которую вы умудрились установить MaxSite CMS ) вашего сайта файл, с названием **.htaccess** - _название выделено жирным и с точкой впереди_

в этом файле у Вас ошибка, в строке:
RewriteRule ^(.*)$ **/index.phpindex.php/**$1 [L,QSA]

исправьте на:
RewriteRule ^(.*)$ **/index.php/**$1 [L,QSA]

заметна разница? - **/index.phpindex.php/** - дублируется _/index.phpindex.php/_
а должно быть только один раз, **/index.php/**

Файл с названием **.htaccess** - находится там же, где и такие есть папки как:
[**application**]
[**install**]
[**system**]
[**uploads**]
**.gitignore**
**.htaccess**
**README.md**
**index.php**

Удачи вам.
