### ISSUE TITLE
Ошибки орфографии/грамматики

### ISSUE THREAD

**Issue by WilhelmWas** [maxsite/cms#246]
Max пожалуйста, исправьте грамматическую ошибку (уже годами тянется) в дистрибутиве.
в файле: [ config/mso_config.php-distr ] ---> "// пазрешиьт сининимы "
$config['mso_permalink_no_slug'] = "yes"; // пазрешиьт сининимы 
$config['mso_permalink_slug_cat'] = "yes"; // разрешить также синонимы рубрик

второе: можно ли привести к одному стандарту окончания *.php файлов??
в файле: [ config/mso_config.php-distr ] окончание: /\* End of file */
в файле: [ maxsite/mso_config.php-distr ] окончание: # end file
в файле: [ config/database.php-distr ] окончание вообще :
/\* End of file database.php */
/\* Location: ./application/config/database.php */

Было бы элегантно:
[ # end of file ] - все маленькими буквами.
Было бы полным:
[ # location: ./application/config/database.php ] - предпоследняя строка
[ # end of file ] - последняя, также, все маленькими буквами.

Еще, где-то у вас читал, вы пишите, что не нужно закрывать php файлы \?\>
На деле это не так:
На вскидку: в папке /admin/plugins - все info.php файлы с закрытым тэгом,
то же в файле: /admin/plugins/admin_page/admin.php ... все перечислять не буду :-),
или это что-то специфичное(??? - да не должно), или я что-то не так понял(тогда извиняйте, молодой, исправлюсь)?
Может нужна? помощь с парсером, типа:
[ function check_end_of_file_all_php_files() ]
Тогда клич: "Даешь Парсер" - решит эту проблему.
БлагоДарю за терпение.

Не хочу быть назойливым или мелочным, но из двух одинаковых, новеньких машин, ту что с царапиной, вряд ли купят первой :-). - это я к записи выше.

Еще вот:
\<div class="update"\> и \<div class="error"\> - имеют разную смысловую нагрузку, но, одинаково плавно, растворяются с поля зрения (экрана) в небытие...

(я не искал специально, но по логике, ошибка должна оставаться видимой, а не исчезать!)
БлагоДарю за труд.

**Comment by maxsite** [comment]
Орфографию поправлю. :)

Окончания php-файлов исторически тянутся из старых версий, включая и от самого CodeIgniter. В общем-то это совершенно не принципиально и ни на что не влияет. Сейчас я использую вариант

`// end of file`

Если редактирую плагин, то там и исправляю. Админ-пагины info-файлы вообще не используют — это скорее информация для совместимости.

> <div class="update"> и <div class="error"> - имеют разную смысловую нагрузку, но, одинаково плавно, растворяются с поля зрения (экрана) в небытие...

Теоретичеки ошибки должны оставаться плавающими, но их окно можно закрыть по клику. Такой функционал я думал реализовать уже после переделки шаблона админ-панели на Sass. Но там большой объем работ, поэтому когда возьмусь не знаю.

**Comment by WilhelmWas** [comment]
Добрый День, благодарю за ответ и тысяча, нет N...

и текст ниже, не для публики:

"Окончания php-файлов исторически тянутся из старых версий, включая и от самого CodeIgniter.
В общем-то это совершенно не принципиально и ни на что не влияет."

я даже не берусь спорить насчет влияния, в ПХП я не силен... но в жизни все имеет принципиальное!!! значение!!!, даже взмах бабочки!!! - здесь я на 100% уверен! :-)

Еще один момент:
в последних инсталляшках, при новой установке, не создается файл config/mso_config.php из config/mso_config.php-distr

и опять же понимаю, что моего согласия/мнения никто не спрашивал и не будет, но
В общем-то это (ТОЖЕ) совершенно не принципиально и ни на что не влияет. 
(это тоже понимаю, только тогда зачем config/mso_config.php-distr нужен???) - это я так шучу.

я сейчас занимаюсь плагином multisite/multilang - поэтому так ярко встал вопрос именно об этих трех файлах:

1. config/mso_config.php
2. config/database.php
3. maxsite/mso_config.php

Мелкие тех. детали:
при подключении/установке/настройке плагин "смотрит" в эти три файла и вместо окончания, ну типа:
# end of file делает замену на: {свой код + # end of file}

получается такой алгоритм:
есть файл? на что он заканчивается? исправляем ну и т.д....

еще вот:
Я написал, что текст этот, не для публики (важно, это почти личное..., почти можно убрать)

Ответь, будь ласка! НАХЕРА?! - нужен этот код?
$out = NR . '' . NR;
и тому подобное...

Не думаю, что PHP имеет хоть какое - либо отношение к тем, кто у корыта, у власти!!!

Я далеко не пофигист (или так: я не похуист), но точно знаю, что подобными вкраплениями падает тень на:
язык PHP,
программирование вообще,
сайты под управлением MaxSite CMS,
разработчиков системы и разработчиков сайтов, тебя и тем кто тебе дорог, и в итоге на все чел-во

Я родом из Казахстана, точнее, Моя Родина СССР и потому (сам лично!) понимаю, как тебе не все равно,
что происходит во взаимоотношениях бывших БРАТСКИХ РЕСПУБЛИК и эти вставки, как бы личная, посильная помощь.....
только куда? и кому??? - Уверен! на эти вопросы у тебя ошибочное мнение!!!
Был бы верный ответ, то, что ты прочел, я бы не написал, а ты бы не прочел.

P.S. Литература:
Чезаре Ломброзо (весь).
Генерал Нечволодов (весь).
Генерал Петров К.П. (все видеолекции)
Г.П. Климов (весь и всё о дегенерации).
Владимир Пятибрат (Глубинная Книга).
В. Бехтерев (дохера)
Н. Бехтерева (дохерее)
БИБЛИЯ, ТОРА, КОРАН и т.д. - (все религии) + Буддизм, Дзэн, Рейки... Тибет (Книга мертвых - Бардо Тхёдол)
Ф. М. Достоевский (хотя бы Бесы).
К. Кастанеда (и все о шаманизме).
Лев Клыков (очень много).
Чарлз Уэбстер Ледбитер (ПО ТУ СТОРОНУ СМЕРТИ, Внутренняя жизнь ....)
Друнвало Мельхиседек (караул... сколько)
также: Р.Монро, Р. Моуди, Петерсон, Радов, Респе, Шемшук, Штайнер, Синельников, Свияш, Вердин, Воронин, Хэнкок, Зеланд...
система ДЭИР (Дальнейшее Энерго Информационное Развитие человека)
система/ы йоги (Агни, Хатха, Карма, Крийя, Раджа, Бхакти....)
А. Ч. Бхактиведанта (кришнаиты и с ними...)
Бхавад Гита, Шримад Бхагаватам и вся Индийская фил-я...
далее еще громадный список, это только так, на вскидку.


Не убеждает? - ознакомьтесь.
Пофигу? - извините, Вы Гений и я низко кланяюсь Вам.

P.P.S. ... разработанные до настоящего времени тех. уст-ва позволяют по одной клетке (слюны, крови, спермы, кала...)
и независимо от расстояний, влиять на человека (эмоции, психику, здоровье... жизнь и смерть)...................

Более подробно я могу рассказать (если он хочет и сам не идиот) собеседнику, глядя ему в глаза. (опыт с 1981 года)...

Максим, сделайте вашу CMS чистой от всякой скверны и Вам гарантировано светлое будущее (а жизнь вечная - это реальность!).

Если я что не так написал, еще раз прошу, извините,
ибо не во гневе пишу я сие, но в смирении.

Зло - это то, что вредит мне и тем, кто мне дорог.
Добро - это то, что приносит благо мне и тем, кто мне дорог.

А благо - это наслаждение.

Низко кланяюсь Вам, сын божий Василий.
(отправляю как есть, не перечитывая)
