### ISSUE TITLE
Метаописание категорий

### ISSUE THREAD

**Issue by Sergusnet** [maxsite/cms#247]
Кто и как решает проблему с отсутствием возможности создания своих метаописания и ключевых слов в категориях? Предполагается ли решение этого вопроса в следующих версиях?.

**Comment by maxsite** [comment]
Давно уже реализовано. См. my-category-meta.php

**Comment by Sergusnet** [comment]
Можете кинуть ссылку, где смотреть? Поиском Гугла ничего не смог найти.

**Comment by maxsite** [comment]
Шаблон Default.
