### ISSUE TITLE
Проблемы с регистрацией и логином на мобильных устройствах

### ISSUE THREAD

**Issue by Den2016** [maxsite/cms#248]
Замечаю уже не в первый раз. Андроид, гнилыми яблоками не увлекаюсь. 
На смартфоне года полтора назад залогинился в хроме без проблем, зато Браузер, который шел в оригинальной прошивке (хрен его знает, что там сунули) при каждой попытке логина выдавал "Неверный логин/пароль". Тогда забил на это, потому что неактуально было. 
Теперь уже стало надо. Но ситуация развернулась.
Вводная.
Планшет Lenovo Tab4, андроид 7.1, предустановлены Google Chrome & Yandex.Браузер. CMS 0.95
Процедуры проводятся явно, не через комментирование статьи.
В яндексе регистрация и авторизация проходят без проблем, но хром начал выпендриваться. Копание показало, что при авторизации на сайт отправляется форма с полями flogin_redirect, 
flogin_session_id, flogin_user, flogin_password, flogin_submit. И удивительным образом flogin_session_id не совпадает с $MSO->data['session']['session_id'] , что в функции _mso_login() при первой же проверке и приводит к редиректу на loginform/error
Судя по успешной авторизации в яндексе, там они совпадают.
При попытке прокомментировать что-либо авторизация тоже не проходит, выдает "Ошибка сессии! Обновите страницу". Обновление страницы не помогает. 

Вроде бы все по честному, формируется форма, туда передается $MSO->data['session']['session_id'], но почему вдруг потом они отличаются? При каждой попытке обе сессии разные
При этом интересно - в описании mso_form_session по умолчанию параметр равен flogin_session_id, но по факту везде, где эта функция вызывается явно указано f_session_id, кроме админки, в которой один раз проходит f_session2_id для загрузки файлов. И нет ни одного вызова с параметром по умолчанию. 

Куда копать? Как корректно залогиниться в хроме на планшете?

**Comment by maxsite** [comment]
Сессия формируется на стороне сервера, поэтому если браузер подставляет что-то другое, значит проблема в браузере. Возможно обрывается сессия и каждое обновление страницы формирует новую сессию. Так что смотреть следует в строну браузера или настроек ОС. Может какой-то режим приватности или файервол так настроен...

**Comment by Den2016** [comment]
интересно... Отсутствует кука PHPSESSID, хотя вроде куки включены. Корпорация зла опять впереди планеты всей, опять что-то не то делают...

**Comment by maxsite** [comment]
Куку еще может резать прокси.

**Comment by Den2016** [comment]
да вроде прокси нет, да и другой браузер нормально себя ведет. Проверил еще на смартфоне - то же самое, яндекс нормально авторизует, хром - нет. Причем из разных сетей.

**Comment by maxsite** [comment]
Наверное по фсбшным кукам авторизацию проводит. :)

**Comment by Den2016** [comment]
шутки шутками, но это уже на двух девайсах. Получается, сайт на MaxSiteCMS частично неработоспособен на мобильных устройствах при просмотре в хроме. Каковой предустановлен в каждом девайсе в качестве браузера по умолчанию.

**Comment by Den2016** [comment]
переоткрыл, передумал, перезакрыл. Хотя проблема есть.
После очередного обновления хрома на смартфоне слетела авторизация. И опять те же пляски - не хочет авторизоваться. 
PHPSESSID нашелся после того, как создал favicon.ico и положил в корень сайта. То есть механизм с переносом иконки в другие места ломает некоторые стандарты, которые неявно где-то используются.

**Comment by maxsite** [comment]
Старые браузеры делают http-запрос к favicon.ico. Новые смотрят его расположение в html-коде. Но при чем тут сессия совершенно неясно...

**Comment by maxsite** [comment]
Стоп. Сессии в терминах CodeIgniter (2-й версии)— это куки. Как таковые php-сессии не используются. Поэтому авторизация — это чистая работа с кукой. Начинать нужно с проверкой есть ли кука или нет. Если есть, то двигаться дальше.

**Comment by Den2016** [comment]
ВСЕ! Разобрался! Этот чертов хром работает не пойми как. 
Вариант, при котором не работает - сервер с сайтом одновременно раздает интернет в локалку. Мобила в локалке через wifi. Как истинный балбес, в логи смотрю в самом конце )))
выдержка из access_log
66.102.9.47 - - [13/Jun/2018:14:11:47 +0500] "GET /login HTTP/1.1" 200 9606
66.102.9.45 - - [13/Jun/2018:14:11:47 +0500] "GET /application/maxsite/templates/**/assets/js/lazy/my.js HTTP/1.1" 304 -
66.102.9.45 - - [13/Jun/2018:14:11:48 +0500] "GET /uploads/favicons/favicon1.png HTTP/1.1" 200 3043
192.168.0.223 - - [13/Jun/2018:14:11:54 +0500] "POST /login HTTP/1.1" 302 -
66.102.9.45 - - [13/Jun/2018:14:11:54 +0500] "GET /loginform/error HTTP/1.1" 200 9689
66.102.9.45 - - [13/Jun/2018:14:11:54 +0500] "GET /application/maxsite/templates/**/assets/js/lazy/my.js HTTP/1.1" 304 -

каким макаром все идет с разных ip - вообще непонятно. Поэтому и срабатывает защита на сессиях. И, видимо, мобильные операторы тоже имеют обыкновение иногда ip-шники передергивать и в этот момент я решил на даче залогиниться и тоже обломался. А сейчас вышел на улицу, переключился на мобильный инет и все стало хорошо. И в логах все запросы с одного ip-шника.
Прости, Макс, что думал всякую фигню ))) Сам дурак, как обычно ))

**Comment by maxsite** [comment]
Бывает. :)
