### ISSUE TITLE
D4 — css и less-файлы

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#25]
Сейчас сложилась довольно сложная схема работы с css-файлами. Там и css.php и style.php, а также style-all-mini, компоненты, профили и т.п.

Наличие php-файлов изначально требовалось для подключения less-компилятора. Я предлагаю полностью изменить данную схему.

В секцию HEAD будут автоматом подключаться все css-файлы каталога /css/. То есть кинул css-файл он автоматом появился. Никаких больше движений не будет. Подключение происходит в алфавитном порядке. Если имя файла начинается с _ или -, то файл не подключается. Основной (автоматически создаваемый) файл — style.css.

Каталог css-less содержит less-файлы, где основной файл style.less. Именно для этого файла подключается встроенный less-компилятор. Алгоритм такой: смотрятся даты создания css/style.css и если она раньше, чем style.less, то происходит компиляция. При этом, я планирую сделать проверку на дату создания всех less-файлов каталога css-less и его подкаталогов. Это позволяет изменить какой-нибудь css-less/mixins/my.less, что автоматом приведет к компиляции style.less и обновлении style.css.

Если требуется отключить встроенную less-компиляцию, а использовать внешнюю, например winless, то я предполагаю, что оптимальным будет использование какого-нибудь less-complier.php с массивом опций, где указывается что-то вроде $LESS['complier'] = false. Здесь можно будет размещать и какие-то другие опции, если они возникнут в будущем.

CSS-профили подключаются как и прежде. Здесь ничего не меняется.

Для плагинов предусмотреть новый хук «head-css», по которому подключать их css-файлы. Сейчас используется просто head и это порождает изрядную солянку css-js файлов. С новым хуком будет больший порядок.

В секции HEAD порядок подключения  css/js-файлов будет таким:

* вначале всё из css/
* css-файлы компонентов (out_component_css)
* хук head-css
* css-профили из css/profiles
* jQuery
* хук head
* все файлы из js/autoload/
* Файлы и ушки по head
* Стили из опций my_style
* Хук head-end
* Ушка google_analytics_top

Основная проблема всех этих переделок — частичная потеря совместимости со старыми шаблонами MaxSite CMS. Поэтому я думаю, что если перенести template.php с mso_default_head_section() на уровень шаблона, то это решит проблему: старые шаблоны будут использовать shared-версию, а новые уже свою.

**Comment by cuprum** [comment]
А если стили из my_style тоже поднять вверх? Чтобы было четкое разграничение - сначала весь возможный CSS, а потом уже весь Js.

**Comment by maxsite** [comment]
Дело в том, что у нас многие стили цепляются за хук head, по которму также выводится и js. Поэтому если поднять my_style, то не полчится перекрыть стили при необходимости.

**Comment by vimruler** [comment]
А какова будет судьба плагина less-компиляции - всё без изменений?
На хук head-css нужно будет формировать только адрес css файла или css код?

**Comment by maxsite** [comment]
С плагином пока не думал. Всё таки я склоняюсь к более простому варианту — использование стороннего компилятора. С этим lessphp мы попали в ловушку — он сильно устарел. Для вебмастера поставить winless не проблема и актуальность lessphp сводится к минимуму. Если будут сложности с плагином less, то наверное уберу из сборки системы.

> На хук head-css нужно будет формировать только адрес css файла или css код?
Я думаю, что css-файл. Хотя это не имеет значения. Он отдает текст, а будет там подключение файла или style — не важно.
