### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by RoyalC** [maxsite/cms#250]
hi i want to translate it to french , i'm beginning to do it but there are some word than i don't find in language file , are they hardcoded ?
![maxsite_cms_99_french](https://user-images.githubusercontent.com/4690205/40556605-91bebe22-604d-11e8-9f2d-dd912ba76909.png)

**Comment by maxsite** [comment]
No. :) Phrases for translation are a function of t(). For example:

`<?= t('Центр помощи') ?>`

**Comment by RoyalC** [comment]
ok thanks when i'll finish the translation i'll send you the files. Great work , i love this CMS.

**Comment by maxsite** [comment]
Ok, thanks :)

**Comment by Orkzed** [comment]
Здравствуйте. 

Я тоже хотел бы начать перевод системы на азербайджанский. Санкцию даете? :)

**Comment by maxsite** [comment]
Да, без проблем. :) Если вышлите готовые файлы, добавлю в комплект MaxSite CMS.

**Comment by Orkzed** [comment]
> Да, без проблем. :) Если вышлите готовые файлы, добавлю в комплект MaxSite CMS.

Спасибо :). Есть инструкции? Или пошарить сам в файлах?

**Comment by maxsite** [comment]
Исть информация в http://max-3000.com/page/jazykovoj-perevod-maxsite-cms и в common\language. Она немного устаревшая, но понять можно. Основной смысл в том, чтобы натравить PoEdit на файлы системы и получить язфковой файл. Дальше сделать сам перевод в PoEdit. После конвертнуть через php-скрипт в готовый языковой файл.

**Comment by Orkzed** [comment]
> Есть информация в http://max-3000.com/page/jazykovoj-perevod-maxsite-cms и в common\language. Она немного устаревшая, но понять можно. Основной смысл в том, чтобы натравить PoEdit на файлы системы и получить языковой файл. Дальше сделать сам перевод в PoEdit. После конвертнуть через php-скрипт в готовый языковой файл.

Ух ты, а почему такая мудреная система перевода? Почему не просто скажем переменные файлы типа en.php / az.php? Я вижу такие файлы но видимо они не полные что ли.

**Comment by maxsite** [comment]
Можно и через эти файлы. Просто они давно уже не обновлялись и скорее всего не полный перевод. Через PoEdit, кстати, удобней работать. Нужно только немного потренироваться, чтобы освоиться.

**Comment by Orkzed** [comment]
> Можно и через эти файлы. Просто они давно уже не обновлялись и скорее всего не полный перевод. Через PoEdit, кстати, удобней работать. Нужно только немного потренироваться, чтобы освоиться.

В последний раз я работал с PO когда переводил Ubuntu 12 (до Launchpad) или GIMP, не помню. Ну что же, будем пробовать.

**Comment by maxsite** [comment]
Ещё один момент — ini-файлы не получится отловить перевод, посольку в них нет функции перевода. Поэтому их фразы придется вручную вытягивать.

**Comment by Orkzed** [comment]
Нужно в будущем создать более удобные типы перевода. Это конечно дело будущего, но то что вы создали это прекрасно. Мне очень нравится и думаю популярность будет только расти.

**Comment by maxsite** [comment]
Вот сделал po-файлы. В каталоге «MaxSite CMS» исходные php-файлы. Poedit у меня 1.4.6.

[t.zip](https://github.com/maxsite/cms/files/2905472/t.zip)
