### ISSUE TITLE
Альтернативный feed

### ISSUE THREAD

**Issue by Kmartynov** [maxsite/cms#251]
есть стандартный адрес для получения rss записей "feed" , добавив его куда угодно можно получить RSS вывод.
Отлично, но только Яндекс турбо не воспринимает стандартный фид. сказано сделано, решил добавить альтернативный поток, но что-то тут не сходится. Попробовал создать плагином на custom_page_404.
function ya_turbo_custom_page_404($args = false)
{
	foreach (mso_segment_array() as $sg)
	{
		if ($sg == "turbofeed")
		{
			echo "Test"
		}
	}
	break;
}
но что-то я делаю не так

**Comment by maxsite** [comment]
Делаете свой type в шаблоне. Туда и файл.

**Comment by Kmartynov** [comment]
@maxsite  это тогда отдельный шаблон на вывод потока для Турбо?

**Comment by maxsite** [comment]
В шаблоне: **type/feed1/feed1.php** В файле свой вывод. Будет доступен как **сайт/feed1**

**Comment by Kmartynov** [comment]
@maxsite  Большое спасибо! Попробуем.

**Comment by Kmartynov** [comment]
@maxsite , не так в лоб не решается, так как дефолтный фид захардкожен.
так-же не получается по example.com/page/page-title/feed1
Ну или ткните носом что да как.

**Comment by maxsite** [comment]
Что именно не получается? Скопировать файл shared\type\feed\home.php в свой шаблон?

**Comment by Kmartynov** [comment]
@maxsite  скопировать получается.
Следуя Вашим советам в каталоге шаблона ШАБЛОН/type/ создаю каталог feed1 в него помещаю из shared\type\feed\home.php как feed1.php
При обращении получаю HTPP 500
и запись в errof log
[Fri Jun 08 08:43:34 2018] [error] [client IP] PHP Fatal error:  Cannot redeclare mso_get_pages() (previously declared in /var/www/clients/client1/web13/web/application/maxsite/common/page.php:17) in /var/www/clients/client1/web13/web/application/maxsite/templates/default/type/feed1/feed1.php on line 542
ЧЯДНТ?

**Comment by maxsite** [comment]
У меня такой ошибки нет. Откуда вообще идёт второе подключение функций? Наверное что-то не так подключили. Единственное, что нужно указать в параметрах получения записи 'custom_type'=>'home'.

**Comment by Kmartynov** [comment]
@maxsite  Итак по порядку.
Взял актуальную версию MaxSite.
Установил с демо данными.
все плагины отключены.
в каталоге шаблона ШАБЛОН/type/ создаю каталог feed1 в него помещаю из shared\type\feed\home.php как feed1.php
Дальше что?

**Comment by maxsite** [comment]
Дальше настроить его под свою задачу.

**Comment by Kmartynov** [comment]
@maxsite Спасибо что не помог.
