### ISSUE TITLE
Как насчёт уязвимостей? недавно проверил свой сайт http://1домбыта.рф на MaxSite CMS Version 99 выдал вот такую портянку

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#252]
[7770ba97-3cbd-427f-8ddb-2bcc7da9fabb.pdf](https://github.com/maxsite/cms/files/2129943/7770ba97-3cbd-427f-8ddb-2bcc7da9fabb.pdf)

**Comment by website-999development** [comment]
SCAN SUMMARY
This site was checked for 67 classes of vulnerabilities, with up to hundreds of tests for each
vulnerability class. This site is considered to be Very Unsafe as of June 23, 2018.

**Comment by maxsite** [comment]
Ну и зачем здесь портянка вашего сайта? Разбирайтесь сами в ней. Будет конкретная проблема, тогда и будет разговор.
