### ISSUE TITLE
помогите плз кто может! у сайта https://remontpc96.ru после конвертации с wpconvert 1.3 появились кракозябы

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#254]
у сайта https://remontpc96.ru после конвертации с wpconvert 1.3 появились кракозябы
![111](https://user-images.githubusercontent.com/29428663/43184508-4406af8e-9002-11e8-8496-177651d86571.png)

**Comment by website-999development** [comment]
![222](https://user-images.githubusercontent.com/29428663/43185029-1d71e1c0-9004-11e8-9fe4-e6776d4fd68c.png)

**Comment by website-999development** [comment]
кэш очистил

**Comment by website-999development** [comment]
помогите плз кто может

**Comment by maxsite** [comment]
В файлах переноса данные верные?

**Comment by website-999development** [comment]
ну глюки какие то были но я уже все удалил доже плагин wpconvert 1.3 и кэш очистил

**Comment by website-999development** [comment]
удалять теперь все добавленное через него или как?

**Comment by maxsite** [comment]
Не знаю. Смотрите какие файлы переноса. Если нормальные, то это одно, если нет, то другое. Гадать бессмысленно.

**Comment by website-999development** [comment]
вы так и не ответили в https://github.com/maxsite/cms/issues/255 что  именно исправлять

почему в статье Компьютер зависает миниатюра не отражается? это тоже на многих стр
