### ISSUE TITLE
помогите плз кто может! у сайта https://remontpc96.ru  сайдбар съехал вниз maxsite cms

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#255]
помогите плз кто может! у сайта https://remontpc96.ru  сайдбар съехал вниз maxsite cms
тоже после правки появилась это
прочитал  https://eavasi.com/maxsite-cms-cut-div/ все сделал как там не помогло

**Comment by website-999development** [comment]
![31](https://user-images.githubusercontent.com/29428663/43270301-2d697416-910e-11e8-9aa9-beda0d653e07.jpeg)

**Comment by Fafofu** [comment]
Привет :) Простите, чего съехало? Я зашёл на сайт, выглядит нормально...

**Comment by maxsite** [comment]
Ctrl+U в браузере и исправляете свой код записи.

**Comment by website-999development** [comment]
а что именно исправлять
и так уже все грохнул

**Comment by website-999development** [comment]
может в div дело?

<div class="layout-center-wrap my-main-container bg-white"><div class="layout-wrap">
--
  |  
  | <div class="flex flex-wrap-tablet my-container-content-sidebar">
  |  
  | <div class="w67 w100-tablet">
  | <div class="">
  |  
  | <div class="content">
  |  
  | <div class="mso-type-page">
  | <div class="mso-page-only"><article><header class="mar25-b"><div class="b-right mar10-t"><a href="https://remontpc96.ru/admin/page_edit/93"><i class="i-edit t-gray600 hover-t-black" title="Edit page"></i></a></div><h1 class="t-gray700 bor-dotted-b bor1 bor-gray400 pad10-b">Компьютерный мастер</h1><div class="info info-top t-gray600 t90 lh200"><time datetime="2018-07-22T06:27:51+0300" class="i-calendar">22 июля 2018 г.</time><span class="i-eye mar15-l">Просмотров: 1</span><span class="i-comment-o mar15-l">Комментарии: 0</span><br><span class="i-folder-open-o" title="Рубрика записи"><a href="https://remontpc96.ru/virus-removal/">Удаление вирусов</a><i class="i-folder-open-o mar10-l"></i><a href="https://remontpc96.ru/installation/">Установка программ</a><i class="i-folder-open-o mar10-l"></i><a href="https://remontpc96.ru/laptop-repair/">Ремонт ноутбуков</a><i class="i-folder-open-o mar10-l"></i><a href="https://remontpc96.ru/computer-repair/">Ремонт компьютеров</a></span><span class="i-tags links-no-color mar20-l" title="Метка записи"><a href="https://remontpc96.ru/tag/%D0%91%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%8B%D0%B9+%D0%92%D1%8B%D0%B5%D0%B7%D0%B4" rel="tag">Бесплатный Выезд</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%8F+%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C" rel="tag">Компьютерная помощь</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D0%BC+%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80" rel="tag">Настроим Компьютер</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0+%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BE%D0%B2" rel="tag">настройка компьютеров</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%9D%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA" rel="tag">Ноутбук</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%A0%D0%B5%D0%BC%D0%BE%D0%BD%D1%82+%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BE%D0%B2" rel="tag">Ремонт компьютеров</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82+%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA%D0%BE%D0%B2+%D0%B8+%D0%BD%D0%B5%D1%82%D0%B1%D1%83%D0%BA%D0%BE%D0%B2" rel="tag">ремонт ноутбуков и нетбуков</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%A0%D0%B5%D0%BC%D0%BE%D0%BD%D1%82+%D0%9F%D0%9A" rel="tag">Ремонт ПК</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D1%81%D1%80%D0%BE%D1%87%D0%BD%D1%8B%D0%B9+%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82+%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BE%D0%B2" rel="tag">срочный ремонт компьютеров</a><i class="i-tag mar10-l"></i><a href="https://remontpc96.ru/tag/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5+%D0%B2%D0%B8%D1%80%D1%83%D1%81%D0%BE%D0%B2" rel="tag">Удаление вирусов</a></span></div></header><div class="mso-page-content mso-type-page-content"><img src="https://remontpc96.ru/uploads/mini/computerrepair2-200-180.jpg" class="left" alt="Компьютерный мастер"><h2>Компьютерный мастер на дом - <a href="https://remontpc96.ru/kompjuternaja-pomoshh-ekaterinburg.html" class="perelink">помощь</a> <a href="https://remontpc96.ru/kak-sozdat-prostoj-sajt-bystro.html" class="perelink">быстро</a> и с гарантией</h2>
  | <p>У вас неисправен <a href="https://remontpc96.ru/laptop-repair/off.html" class="perelink">компьютер</a> или ноутбук? Мы специализируемся на выездном ремонте и настройке - в удобное для вас <a href="https://remontpc96.ru/vremja-v-internete-s-polzoj.html" class="perelink">время</a> наш специалист приедет к вам домой или в офис и <a href="https://remontpc96.ru/kak-sozdat-prostoj-sajt-bystro.html" class="perelink">быстро</a> проведет необходимые <a href="https://remontpc96.ru/blog/photo.html" class="perelink">работы</a> <a href="https://remontpc96.ru/info/price.html" class="perelink">любой</a> сложности. На все <a href="https://remontpc96.ru/kakie-uslugi-objazano-pokryvat-oms.html" class="perelink">услуги</a> действует длительная гарантия.</p>
  | На сегодняшний день в  <a href="https://remontpc96.ru/remont-i-nastrojka-kompjuterov.html" class="perelink">Екатеринбурге</a> много   предложений ремонта компьютерной техники. В основном это частные компьютерные мастера-самоучки, <a href="https://remontpc96.ru/5-prilozhenij-kotorye-nuzhno-udalit-s-android.html" class="perelink">которые</a> в лучшем случае вам не починят компьютер, в худшем обманут с ценами на <a href="https://remontpc96.ru/computer-repair-1.html" class="perelink">ремонт</a> или вообще сломают устройство. Помимо этого навязывают дополнительные услуги, затягивают сроки ремонта. Но мы для всех жителей города предлагаем не только качественные <a href="https://remontpc96.ru/kakie-uslugi-objazano-pokryvat-oms.html" class="perelink">услуги</a> компьютерной помощи, но и <a href="https://remontpc96.ru/samye-populjarnye-brauzery-preimushhes.html" class="perelink">самые</a> выгодные условия.
  | <p><strong>Почему <a href="https://remontpc96.ru/kak-iskat-luchshie-ceny-i-ponjat-stoit-l.html" class="perelink">стоит</a> обратиться именно к нам?</strong></p>
  | <p>Наш компьютерный <a href="https://remontpc96.ru/antivirus-windows-nachal-blokirovat-servis-ut.html" class="perelink">сервис</a> предоставляет услугу<strong>  <a href="https://remontpc96.ru/computer-repair-1.html" class="perelink">ремонт</a> <a href="https://remontpc96.ru/computer-repair-1.html" class="perelink">компьютеров</a> в г. Екатеринбург</strong>  только по низким ценам от 300 р. Компьютерные <a href="https://remontpc96.ru/vyzov-mastera.html" class="perelink">мастера</a> не самоучки, а только проверенные, с высшим техническим образованием, с прохождением ежегодных курсов повышения квалификации.  <strong> Мы</strong>  также осуществляем <strong>емонт <a href="https://remontpc96.ru/computer-repair-1.html" class="perelink">компьютеров</a>  </strong>с выездом <a href="https://remontpc96.ru/vyzov-mastera.html" class="perelink">мастера</a> бесплатно, а в сложных случаях <a href="https://remontpc96.ru/computer-repair-1.html" class="perelink">ремонт</a> и <a href="https://remontpc96.ru/diagnostika-kompjutera.html" class="perelink">диагностика</a> проводится непосредственно в сервисе. Выезд - немедленно <a href="https://remontpc96.ru/chto-budet-s-socsetjami-posle-prinjatija-n.html" class="perelink">после</a> обращения. Заявку вы можете оставить нажав на кнопку.</p>
  | <p><strong>Давайте определимся <a href="https://remontpc96.ru/kakie-uslugi-objazano-pokryvat-oms.html" class="perelink">какие</a> <a href="https://remontpc96.ru/laptop-repair/problems-with-the-motherboard.html" class="perelink">проблемы</a> с компьютером мы можем решить прямо у вас дома:</strong></p>
  | <ol>
  | <li>Удаление пыли, которое приводит к перегреву компьютера, а значит к его замедлению.</li>
  | <li>Исправление системных ошибок препятствующие нормальной работе <a href="https://remontpc96.ru/blog/pravilnoe-ispolzovaniye.html" class="perelink">компьютера</a> и загрузки Windows.</li>
  | <li>Установка или переустановка Windows.</li>
  | <li>Поиск и <a href="https://remontpc96.ru/virus-removal/virus-removal.html" class="perelink">удаление</a> вирусов, смс баннеров.</li>
  | <li>Замена неисправных комплектующих (видеокарты, <a href="https://remontpc96.ru/laptop-repair/problems-with-the-motherboard.html" class="perelink">материнской</a> платы, <a href="https://remontpc96.ru/chistka-sistemnogo-bloka.html" class="perelink">блока</a> питания, <a href="https://remontpc96.ru/computer-repair/not-enough-ram.html" class="perelink">оперативной</a> памяти, процессора).</li>
  | <li>Установка необходимого программного обеспечения и драйверов для нормальной ПК.</li>
  | <li>Настройка <a href="https://remontpc96.ru/kak-uvelichit-moshhnost-wifi-i-usilit-sig.html" class="perelink">WiFi</a> оборудования для нормальной <a href="https://remontpc96.ru/blog/photo.html" class="perelink">работы</a> <a href="https://remontpc96.ru/podkljuchenie-i-nastrojka-interneta-1.html" class="perelink">интернета</a> у вас дома.</li>
  | </ol>
  |  
  | <p>Компьютерный мастер приезжает к вам и оказывает компьютерную <a href="https://remontpc96.ru/kompjuternaja-pomoshh-ekaterinburg.html" class="perelink">помощь</a> в максимально короткие сроки имея при себе весь набор необходимых инструментов. Помимо этого, <a href="https://remontpc96.ru/chto-budet-s-socsetjami-posle-prinjatija-n.html" class="perelink">после</a> завершения ремонта наш мастер расскажет вам как <a href="https://remontpc96.ru/kak-pravilno-chistit-noutbuk.html" class="perelink">правильно</a> эксплуатировать компьютер, чтобы исключить серьезные поломки в дальнейшем.</p><div class="mso-clearfix"></div><aside><div class="page_other_pages"><div class="page_other_pages_header">Похожие страницы</div><table width="100%" border="0"><tr><td><a href="https://remontpc96.ru/laptop-repair/off.html" title="Компьютер сам выключается Приедем максимально быстро Разберемся в причинах проблемы Заставим компьютер хорошо работать Технический осмотр ПК: 400 р.">Компьютер сам выключается</a><br><img src="https://remontpc96.ru/wp-content/uploads/2016/11/strelka.png" width="100" alt="Компьютер сам выключается"><br>Выключается компьютер? Проверим. Настроим Компьютер, Ноутбук – Ремонт ...</td><td><a href="https://remontpc96.ru/computer-repair/hangs.html" title="Компьютер зависает Приедем в течение 1 часа Найдём проблемы зависания Устраним неполадки и дадим гарантию! Вызвать мастера Стоимость диагностики 0 р.">Компьютер зависает</a><br><img src="https://www.youtube.com/embed/hiYC8t5Mr9A" width="100" alt="Компьютер зависает"><br>Зависает компьютер? – Ремонт компьютеров и ноутбуков! Починим! – От 300 р. на ...</td></tr></table></div></div>

**Comment by website-999development** [comment]
и почему в статье Компьютер зависает миниатюра не отражается? это тоже на многих стр

**Comment by maxsite** [comment]
У вас html-код невалидный. Разберитесь с ним. И не нужно делать кучу тем и в них массу вопросов. Достаточно одного с нормальным и внятным описанием.

**Comment by website-999development** [comment]
вся невалидность не к статье относится
https://validator.w3.org/nu/?doc=https%3A%2F%2Fremontpc96.ru%2Fvirus-removal%2Fkompjuternyj-master.html 

Showing results for https://remontpc96.ru/virus-removal/kompjuternyj-master.html

Checker Input
Show sourceoutlineimage reportOptions…

Check by
https://remontpc96.ru/virus-removal/kompjuternyj-master.html
Check

Use the Message Filtering button below to hide/show particular messages, and to see total counts of errors and warnings.
Message Filtering
Error: Bad value imagetoolbar for attribute http-equiv on element meta.
From line 39, column 1; to line 39, column 45
ge">↩↩↩↩↩↩<meta http-equiv="imagetoolbar" content="no">↩↩↩</h
Error: The width attribute on the table element is obsolete. Use CSS instead.
From line 59, column 402; to line 59, column 446
x-grow3"> <table width="100%" border="0" align="left" >    <t
Error: The align attribute on the table element is obsolete. Use CSS instead.
From line 59, column 402; to line 59, column 446
x-grow3"> <table width="100%" border="0" align="left" >    <t
Error: The border attribute on the table element is obsolete. Use CSS instead.
From line 59, column 402; to line 59, column 446
x-grow3"> <table width="100%" border="0" align="left" >    <t
Error: The width attribute on the td element is obsolete. Use CSS instead.
From line 59, column 455; to line 60, column 18
 >    <tr>↩  <td width="51%"><ul>↩ 
Error: The width attribute on the td element is obsolete. Use CSS instead.
From line 66, column 13; to line 67, column 22
</ul></td>↩      <td width="49%"><p><st
Error: The width attribute on the table element is obsolete. Use CSS instead.
From line 130, column 717; to line 130, column 747
ницы</div><table width="100%" border="0"><tr><t
Error: The border attribute on the table element is obsolete. Use CSS instead.
From line 130, column 717; to line 130, column 747
ницы</div><table width="100%" border="0"><tr><t
Error: End tag div seen, but there were open elements.
From line 130, column 1615; to line 130, column 1620
ble></div></div>↩<div 
Error: Unclosed element aside.
From line 130, column 621; to line 130, column 627
ix"></div><aside><div c
Error: Stray end tag aside.
From line 136, column 3598; to line 136, column 3605
div></div></aside></div>
Error: End tag div seen, but there were open elements.
From line 136, column 3606; to line 136, column 3611
v></aside></div></article></div>
Error: Element p not allowed as child of element span in this context. (Suppressing further errors from this subtree.)
From line 167, column 129; to line 167, column 131
er"><span><p>ЦЕНЫ Н
Contexts in which element p may be used:
Where flow content is expected.
Content model for element span:
Phrasing content.
Error: No p element in scope but a p end tag seen.
From line 184, column 25; to line 184, column 28
се филиалы</p>↩Телеф
Warning: The type attribute is unnecessary for JavaScript resources.
From line 203, column 28; to line 203, column 58
counter--><script type="text/javascript">↩docum
Error: Stray end tag div.
From line 235, column 7; to line 235, column 12
>↩↩↩</div></div>↩↩<a h
Warning: The type attribute is unnecessary for JavaScript resources.
From line 243, column 49; to line 243, column 116
></script><script type="text/javascript" src="//vk.com/js/api/openapi.js?120"></scri
Warning: The type attribute is unnecessary for JavaScript resources.
From line 243, column 230; to line 243, column 365
></script><script type="text/javascript" defer src="https://remontpc96.ru/application/cache/assets/js/minify_5c77fbd8ef9b63cb697a4e34ba1c6f18.js"></scri
Warning: Consider using the h1 element as a top-level heading only (all h1 elements are treated as top-level headings by many screen readers and other tools).
From line 114, column 61; to line 114, column 120
"mar25-b"><h1 class="t-gray700 bor-dotted-b bor1 bor-gray400 pad10-b">Компью

**Comment by website-999development** [comment]
а почему в статье Компьютер зависает миниатюра не отражается?  это тоже  невалидность ?

**Comment by website-999development** [comment]
ну подскажите плз  хоть где html-код невалидный.

**Comment by vimruler** [comment]
Сейчас вроде всё нормально.

**Comment by website-999development** [comment]
убрал плагин    similar_posts 1.3 и сайдбар  вернулся 
--жалко конечно, привык к нему
может кто сможет его пофиксить?
