### ISSUE TITLE
Здравствуйте! помогите плз! пропали из поиска 80% страниц

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#256]
Здравствуйте!
у сайта https://remontpc96.ru  пропали из поиска 80% страниц индексированных ранее когда он был на Wordpress
Яндекс считает их неканоническими. 
/blog/бесполезные-предустановленные-мобил/
Неканоническая

26.07.2018	Статьи
/blog/владельцы-macbook-pro-с-бракованной-клавиатур/
Неканоническая

27.07.2018	Статьи
/blog/внешний-аккумулятор-topon-top-t72/
Неканоническая

27.07.2018	Статьи
/blog/время-в-интернете-с-пользой/
Неканоническая

27.07.2018	Статьи
/blog/встроенные-системные-утилиты-windows/
Неканоническая

27.07.2018	Статьи
/blog/выбор-видеокарты-советы-экспертов/
Неканоническая

28.07.2018	Статьи
/blog/в-роскомнадзоре-рассказали-как-будут/
Неканоническая

27.07.2018	Статьи
/blog/госдума-приняла-закон-о-блокировке-са/
Неканоническая

27.07.2018	Статьи
/blog/дуров-разрабатывает-альтернативный/
Неканоническая

27.07.2018	Статьи
/blog/искусственный-интеллект-смоделирова/
Неканоническая

27.07.2018	Статьи
/blog/какой-смартфон-выбрать-в-2018-году/
Неканоническая

27.07.2018	Статьи
/blog/как-зарабатывать-деньги/
Неканоническая

27.07.2018	Статьи
/blog/как-отформатировать-карту-памяти/
Неканоническая

27.07.2018	Статьи
/blog/как-правильно-чистить-ноутбук/
Неканоническая

27.07.2018	Статьи
/blog/как-превратить-ультрабук-в-игровую-си/
Неканоническая

27.07.2018	Статьи
/blog/как-увеличить-мощность-wifi-и-усилить-сиг/
Неканоническая

27.07.2018	Статьи
/blog/как-ускорить-работу-компьютера/
Неканоническая
и т.д.

В Настройках  плагина Friendly URLs  стоит галка  \/ Использовать нестандартные шаблоны URI
Что надо сделать чтобы они вернулись в поиск ?

**Comment by website-999development** [comment]
![123131212213](https://user-images.githubusercontent.com/29428663/43627501-17ccc5c4-9710-11e8-87c2-11cd9cb5bb75.png)

**Comment by website-999development** [comment]
мне надо чтобы каждая страница отображалась по своему адресу, а не в категориях.

**Comment by vimruler** [comment]
Так то плагин ЧПУ нестандартный для движка и с вашим вопросом надо обращаться к разработчику плагина, а не здесь писать.

**Comment by vimruler** [comment]
Какая у вас версия плагина friendly_urls?

**Comment by website-999development** [comment]
friendly_urls 2.1       а кто  разработчик?

**Comment by vimruler** [comment]
>  friendly_urls 2.1

У автора платно доступна более свежая версия, там вроде нет такой проблемы...

**Comment by website-999development** [comment]
так вроде или ...? как можно покупать, если уже ожегся ? и что вообще делать? подскажите лучше

**Comment by website-999development** [comment]
тут кто то еще может посоветовать?

**Comment by vimruler** [comment]
А что тут можно посоветовать? Думаю, что вы и так знаете варианты - отказаться от использования плагина ЧПУ или вообще вернуться на вордпресс.

**Comment by website-999development** [comment]
а мне интересен механизм этого, с какой версии MaxSite CMS пошли такие проблемы, я один на них жалуюсь и у всех все нормально ? отказаться от использования плагина ЧПУ проще, но может есть другие решения? вообще все глухо, так мало тут народу кто сталкивался с этой проблемой?

**Comment by vimruler** [comment]
> а мне интересен механизм этого, с какой версии MaxSite CMS пошли такие проблемы, я один на них жалуюсь и у всех все нормально?

Версия движка тут не при чём. Дело в плагине, точнее в том, что вы пытаетесь от демо-версии плагина ЧПУ получить полный функционал. Я специально посмотрел, текущая стабильная версия плагина - 2.6.6 Там явно много всего поправлено уже. Может и ваша проблема тоже.

>отказаться от использования плагина ЧПУ проще, но может есть другие решения?
В этом движке есть только два варианта - использовать стандартный чпу (но тогда ваши урлы нереализуемы в принципе) или использовать плагин ЧПУ friendly_urls. 

>вообще все глухо, так мало тут народу кто сталкивался с этой проблемой?

Глухо не в том, что народу мало, его то как раз много. Глухо в том, что в этом движке принято самостоятельно разбираться со всем или нанимать специалистов. Средний вариант (вариант бесплатной помощи) не прижился, ибо кризис и бла-бла-бла...

**Comment by website-999development** [comment]
Большое спасибо. а может подскажете как сделать чтобы со стр допустим https://remontpc96.ru/blog/быстрый-запуск-windows-10/ показывало именно эту страницу а не перекидывало на https://remontpc96.ru/blog/ ?    дописать к ним .html ? это можно  плагином ЧПУ friendly_urls. решить?

**Comment by vimruler** [comment]
Думаю, что это не поможет. Посмотрел плагин ЧПУ и возник встречный вопрос - а как вы от плагина добились того, чтобы ссылки были русскоязычные? Дело в том, что в опциях нет возможности подставлять в шаблон адреса ни title ни другое поле, где могли бы быть русские буквы. Поле page_slug согласно логике движка никогда не может содержать русские буквы.

**Comment by vimruler** [comment]
>а это стр конвертированные из wordpress через wpconvert

Откуда ноги растут я примерно догадался, но в том то и дело что эти ссылки для движка не имеют смысла и теперь нужно проверить как прошла конвертация и почему ссылки остались прежними. А потом сделать так, чтобы все ссылки стали родными для движка (на основе slug /page/).
