### ISSUE TITLE
Плагин Sape

### ISSUE THREAD

**Issue by Wovan1** [maxsite/cms#257]
Доброго времени.
Задал этот вопрос на сайте max-3000.com/page/articles-sape-ru, не знаю дождусь там ответ или нет, повторю сюда этот вопрос. Прошу извинить за настойчивость, задать вопрос больше негде, форум зарыт.

Плагин сапе установлен и работает с ссылками уже 2 года. Решил установить виджет со статьями, назвал его так.. sape_widget article, в настройках виджета включил "статьи".
Обновляю страницу на сайте и сайдбар не отображается. Убираю это виджет (статей) и становится все нормально, сайдбар отображается.

Если добавлять сайт в сапу articles.sape.ru, то если виджет установлен, пишет что url недоступен (хотя в браузере открывается нормально, только без сайдбара). Если виджет не установлен, то сапа при добавлении сайта пишет, страница найдена, код не обнаружен.

В настройках плагина, галочка "Включить публикацию статей" установлена.

Версия сайта 0,86, версия плагина 1,3, обновил до 100 версии сайта, плагин сапы 1,5, то же самое, сайдбар пропадает при выборе в виджете сапы пункта "статьи"
Шаблон сайта "Default".
Помогите запустить это дело?

**Comment by Wovan1** [comment]
[url=https://postimg.cc/XBjW34g8][img]https://i.postimg.cc/XBjW34g8/2018-10-05_22-25-37.jpg[/img][/url]

[url=https://postimg.cc/t7ppFNHx][img]https://i.postimg.cc/t7ppFNHx/2018-10-05_22-26-20.jpg[/img][/url]

**Comment by Wovan1** [comment]
Вот, до установки и после..
https://postimg.cc/XBjW34g8
https://postimg.cc/t7ppFNHx

**Comment by Wovan1** [comment]
Хотел напомнит, ссылки продаются и отображаются уже 2 года, то есть код сапы установлен правильно.

**Comment by maxsite** [comment]
Если сайдбар пропадает, то какая-то ошибка. Смотрите в html-коде, что выводится. Может в php-логах указана ошибка.

**Comment by Wovan1** [comment]
В коде, когда все нормально `<div class="aside sidebar sidebar1"><div class="sidebar1-wrap"><div class="widget widget_1 widget_1_1 login_form_widget login_form_widget_0"><div class="w0"><div class="w1"><p><strong>Привет, Admin!</strong><br>`

**Comment by Wovan1** [comment]
Когда сайдбар не отображается, то код страницы кончается строчкой `<div class="aside sidebar sidebar1"><div class="sidebar1-wrap"> ` как раз в этом месте начинается сайдбар.
Когда отображается, то код продолжается..

`<div class="aside sidebar sidebar1"><div class="sidebar1-wrap"><div class="widget widget_1 widget_1_1 login_form_widget login_form_widget_0"><div class="w0"><div class="w1"><p><strong>Привет, Admin!</strong><br>` и далее...

По логам PHP пусто, может не туда смотрю (ISPManager-PHP-Журналы) тут вообще ни чего нет.

Могу дать доступ на сайт и в ISPManager, сам не разберусь.

**Comment by Wovan1** [comment]
Может сервер не подходит для этого?
Apache | 2.4.6-80.el7.centos.1
MySQL | 10.2.18-1.el7.centos
Perl | 5.16.3-292.el7
Kernel | 3.10.0-862.14.4.el7.x86_64

**Comment by maxsite** [comment]
Судя по всему какая-то php-ошибка. Настраивайте логи, или сделайте в .htaccess отображение ошибок в браузер.

**Comment by Wovan1** [comment]
Настроил логи в PHP.ini, На другом сайте есть ошибка (у меня 2 сайта на этом сервере), пишется в лог (не касается этого сайта).
```
; log_errors
;   Default Value: Off
;   Development Value: On
;   Production Value: On
error_log = /var/www/zend/data/www/PHP_errors.log
```
Ошибок PHP для данного сайта нет.
Установил на денвер3, тоже самое, сайдбар пропадает.

**Comment by Wovan1** [comment]
Все же выловил на денвере.
`Z:\home\test1.ru\www\application\maxsite\plugins\sape\index.php on line 253`

Вот что в этой строке..
`$out = $SAPE_ARTICLE->return_announcements();`

**Comment by maxsite** [comment]
Версия sape.php какая?

**Comment by Wovan1** [comment]
protected $_version = '1.3.9';

Попробовал еще раз на денвере, вылетает такая ошибка вместо сайдбара (это когда статьи в виджете).
`Fatal error: Cannot access protected property SAPE_articles::$_data in Z:\home\test1.ru\www\application\maxsite\plugins\sape\index.php on line 256`

```
255	// это чеккод
256		if ($out == $SAPE_ARTICLE->_data['index']['checkCode'])
```
Когда ссылки в виджете, сайдбар загружается нормально, но ссылок нет (так как на денвере).

**Comment by maxsite** [comment]
У вас сколько виджетов в сайдбаре?

**Comment by Wovan1** [comment]
Саповских? один, меняю его на ссылки или статьи. Также ставил два саповских ссылки и статьи, тоже самое.

**Comment by maxsite** [comment]
Нет, всего виджетов (любых) в сайдбаре?

**Comment by maxsite** [comment]
Я вижу, что в этой версии сапа поменяла свой код. Попробуйте в sape.php в строчке 1658 

`protected $_data = array();`

убрать слово protected.

**Comment by Wovan1** [comment]
На денвере стоит версия 100 (скачал и установил, ни чего не менял кроме конфига для базы), шаблон дефаулт от версии 100, плагин сапе 1,5.

**Comment by Wovan1** [comment]
Хорошо, сейчас попробую

**Comment by Wovan1** [comment]
Так и написал..
![2018-10-06_22-28-28](https://user-images.githubusercontent.com/43891015/46574632-46462380-c9b7-11e8-8a17-a833c2eafe8e.jpg)

Сайт не грузится, ошибка..

![2018-10-06_22-30-05](https://user-images.githubusercontent.com/43891015/46574643-742b6800-c9b7-11e8-86bb-5f3ddb8af726.jpg)

**Comment by Wovan1** [comment]
Еще вот что, я создал ушку с кодом..

```
Для возможности отображения анонсов статей на тех страницах сайта, которые вы хотели бы подключить к системе, необходимо в начале исходного кода этих страниц сделать следующую php-вставку:

<?php
     if (!defined('_SAPE_USER')){
        define('_SAPE_USER', '28b972ecfe28affcf9b9524b7c7f5423');
     }
     require_once($_SERVER['DOCUMENT_ROOT'].'/'._SAPE_USER.'/sape.php');
     $sape_article = new SAPE_articles();
?>

Далее, в тех местах страницы, где вы хотели бы выводить ссылки на анонсы, необходимо вставить следующий код:
<?php  echo $sape_article->return_announcements(); ?>
```
Убрал виджет сапыиз сайдбара и с этой ушкой все нормально работает, сайт добваился в сапу. Но тут уже плагин не будет работать.

**Comment by maxsite** [comment]
Странно... А если вместо protected написать public?

**Comment by Wovan1** [comment]
Сейчас попробую

**Comment by Wovan1** [comment]
На денвере сайдбар появился с включенными статьями (версия движка 100). На настоящем сайте ни чего не поменялось, но тут версия 086, плагин сапы 1.5. Может из за этого?

**Comment by maxsite** [comment]
Сложно сказать. Может просто старый вывод закэшировался. Ну и ошибки проверьте.

**Comment by Wovan1** [comment]
Я попробую на настоящем сайте обновлю до 100 и попробую. Я откатился опять на 086  из того, картинки что то неправильно стали отображаться из за какого то плагина, а какого не помню, надо искать было.

**Comment by Wovan1** [comment]
Как сделаю, напишу.

**Comment by maxsite** [comment]
Ок. Тикет не закрывайте, я попозже у себя ещё проверю. Потом сам закрою. :)

**Comment by Wovan1** [comment]
Хорошо

**Comment by Wovan1** [comment]
Все заработало и с 086 версией движка и с 100 (наверно закешировалось).

Файл **sape,php** 1658 срока, меняем..
```
protected $_data = array(); 
на..
public $_data = array();
```
Спасибо за помощь, сам бы не разобрался.))

**Comment by maxsite** [comment]
Хорошо. Сапа поменяла код, отсюда и проблема возникла.

**Comment by Wovan1** [comment]
Получается, никто не пользуется статьями, раз вопросов не возникло?

**Comment by maxsite** [comment]
При нынешних мизерных саповских ценах это не удивительно...

**Comment by Wovan1** [comment]
Спасибо еще раз, можно закрывать.))
