### ISSUE TITLE
Адреса кратинок - загрузок при переносе сайта на новое имя или протокол типа https

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#258]
Предложение, Максиму об универсальных адресах для картинок.

Если мы сделали сайт загрузили картинки и установили адреса на них в статьях, то автоматически делаются миниатюры и большие картинки по размерам устанавливаются на страницу. С этим всё хорошо.
Но если мы хотим переехать на новый домен или сменить протокол на https, то придётся все адреса переписывать для каждой статьи.

Максим предлагаю это исправлять. Обсуждаем?

**Comment by Kotgo** [comment]
Здесь **Редактирование записи ->Основные опции -> Изображение
И В ЗАГРУЗКАХ** не работает относительный путь без указания http!
А мне нравится вариант миниатюр и большой картинки!

**Comment by maxsite** [comment]
Я же ответил. Не дублируйте темы.
