### ISSUE TITLE
Сайдбар last_comments_widget - как изменить длину статьи или убрать

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#259]
Сайдбар last_comments_widget
Выводит название статьи и комментарии.

По разным причинам не нужно название статьи и требуется регулировка длины ее. Лишние схожие слова и выглядит не очень.

Подскажите, пожалуйста, как мне убрать вобоще название статьи или изменить её длину?

Хочется либо просто комментарий( с возможностью сокращения) и/или возможность удаления и сокращения имени- названия статьи.

**Comment by maxsite** [comment]
У плагина только те настройки, которые вы видите. Если нужно что-то другое, то нужен другой плагин.

**Comment by Kotgo** [comment]
А я то обрадовался, думал нашёл что-то отличное от Wordpress, а оказывается та же политика.

**Comment by maxsite** [comment]
Вам 12 лет?

**Comment by Kotgo** [comment]
Нет, а к чему такой вопрос и на что он намекает ?

Вы же сами предложили здесь обсуждать. Если считаете что предложения не стоит вам писать и вы сами решаете что делать в вашей cms, то так и напишите. 

А что мне не понравилось в политики Wordpress , то что без спец. плагина или особых обновлений за деньги ничего не решается. То же вероятно и у вас?

**Comment by maxsite** [comment]
Если у вас нестандартная задача, то придется либо самому напрячься, либо кого-то за деньги. Взрослые люди это прекрасно понимают.

**Comment by Kotgo** [comment]
Значит мне 12 лет  :-))

А я почему то подумал что вам будет интересно мнение пользователя о новых вариантах.

Прочитал 
 http://maxhub.ru/page/moj-tretij-otzyv-o-maxsite-cms



Буду сам пробовать что-то изменить.

**Comment by maxsite** [comment]
Пробуйте. Дорогу осилит идущий.

**Comment by Kotgo** [comment]
Всё сделал. :-) Оказалось очень просто. Небольшая замена в плагине и всё работает как требовалось.
