### ISSUE TITLE
D4 — компоненты. Несколько шаблонов в комплекте

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#26]
Мне нравится текущая организация компонентов шаблона. Проблема только в том, что их много. Текущий вариант default позволяет использовать все 30 компонентов, и они даже по дизайну более-менее подходят. Но текущие компоненты это в первую очередь каркас для других шаблонов. И получилось так, что поддерживать их всех для одного шаблона просто бесмысленно.

Отсюда я предлагаю немного поменять концепцию default-шаблона. Сейчас он выполняет роль прототипа для новых шаблонов. Вместо этого отказаться от этой идеи и сделать просто какой-то красивый модный шаблон. Поскольку он будет менее функциональный и универсальный, чем текущий, то подумать о том, чтобы в комплекте MaxSite CMS шло несколько шаблонов, рассчитанных под разные потребности. Ну вроде «типовой блог», «аля-новости с колоночками» и «фотоблог». Построены они будут по единой схеме, с различиями по css-стилям, html-верстке и компонентами.

По компонентам, думаю, можно немного сменить парадигму. Если сейчас это возможность тусовать компоненты верх-вниз, то в новых шаблонах это может быть просто выбор заранее определенных полнофункциональных вариантов шапки/подвала. Например будет «шапка со слайдером», «шапка без слайдера», «шапка с видео» и т.п. Эти компоненты не нужно использовать оновременно, а нужно выбрать лишь один из них. Как вариант, если выбирается несколько, то в опциях можно выставить условия «только на главной», «только в записях» и т.п. То есть по технической реализации ничего не меняется, но меняется сам подход к понятию компонентов.

Что касается нескольких шаблонов в комплекте MaxSite CMS, сразу отмечу, что один я этого не потяну. Я бы с удовольствием полностью делегировал все работы по верстке, дизайну и поддержке шаблонов, включая и базовый default кому-то, кто заинтересуется. Мне интересна техническая сторона вопроса, прогрммирование, но поддерживать верстку и всё-такое, требует много усилий. В качестве альтернативы на начальном этапе можно не включать эти шаблоны в комплект, а выложить на гитхабе для пользования и отладки. После уже решить о включении в комплект. Главное, чтобы эти шаблоны всегда были полностью совместимыми с последней версией MaxSite CMS.

Предлагаю обсудить эти вопросы.

**Comment by cuprum** [comment]
В принципе, можно сделать какой то базовый шаблон, не такой навороченный как нынешний дефолтный и включить в него только компоненты, которые будут работать в этом шаблоне сразу, "из коробки". А все компоненты, которые сейчас есть, переместить в shared, пусть они хранятся там. Если кто-то делает свой шаблон с расширенной функциональностью, то он просто копирует нужные компоненты из shared в папку своего шаблона. Описания компонентов уже есть внутри папки каждого. Для верности еще можно завести общий readme, в котором указать список всех компонентов и что они делают.

**Comment by maxsite** [comment]
Честно говоря, я не заметил, что существующие компоненты как-то востребованы в других шаблонах. Как вариант — выложить их отдельно, как сейчас перевод. Кому нужно, пусть отдельно скачивают.

**Comment by cuprum** [comment]
Или так. Можно даже все компоненты закинуть сюда на гитхаб в отдельный репо.

**Comment by vimruler** [comment]
Да, компоненты из дефолтного шаблона в сторонних шаблонах скорее идут в качестве заготовок. Поэтому нет особой нужды вкладывать все компоненты в «коробку». Скорее должен быть репозиторий компонентов, где их смогут брать и делать с ними что захотят. Тогда и задача поддержки особо не стоит, ибо у них явно роль заготовок.

На счёт нескольких шаблонов в «коробке» - может это и хорошо было бы, но именно, что требует поддержки, а значит вероятность реализации - пока минимальная. Если не сделать шаблон, в котором демонстрируются все возможности, то для многих начинающих пользователей этих самых возможностей просто не будет существовать. В каком-то смысле получается диллема. Но если не брать в голову проблемы новичков, а сосредоточиться только на нуждах более опытных коллег, то действительно, нужно хотя бы две темы - «для старта» (та, которая будет из коробки реализовывать некий минимальный функционал блога) и «нулевая заготовка» (где по минимуму будут подключены файлы типа style-all-mini.css чтобы вебмастер сразу понимал, что его никто не ограничивает и ничего не навязывает - как хочешь, так и делай. Сейчас многим это не очевидно, при взгляде на default шаблон). Шаблоны «в три колонки» и т.п. - хорошо бы иметь такие, но именно, что это задача на будущее и скорее всего не для «коробки».

**Comment by maxsite** [comment]
Илья, тут всё не так просто. Вот для примера каркас WordPress-шаблона: https://github.com/Automattic/_s Официальный от автоматик. Я не думаю, что он проще, чем наш default. Моя ошибка только в том, что я не успел разглядеть потенциал в normalize и из-за этого теряется совместимость. Единая «коробка» это здорово, но появится ещё какой-нибудь тренд и всё придется переделывать. Поэтому я всё-таки склоняюсь к независимым шаблонам. Если получится отработать до конца свой css-фреймворк, то сделать несколько шаблонов в комплекте будет не очень сложно.

Еще дам интересную ссылку: http://designmodo.com/generator/ Представте себе, что это и есть наши компоненты.

**Comment by vimruler** [comment]
> Еще дам интересную ссылку: http://designmodo.com/generator/ Представте себе, что это и есть наши компоненты.

Действительно, очень занятно выглядит!

Собственно, проблемы сделать независимые шаблоны на основе своего css-фреймворка - нет. Сама идея мне нравится. Тут скорее вопрос в последующей необходимости обучения работе с ними всеми. Но думаю, что это тоже доступно реализации.

**Comment by dignityinside** [comment]
Сделать бы Drag&Drop для компонентов, чтобы можно было просто перетаскывать, а не выберат через "Dropdown" как сейчас. Примерно как это сделано на сайте, который показал Макс.
