### ISSUE TITLE
Какие варинаты защиты админки есть?

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#260]
Подскажите, пожалуйста, варианты защиты админки от разного рода угроз. Попытки взлома, подбор автоматическим брутфорсом и подобное на атвомате.

**Comment by maxsite** [comment]
У вас есть реальные примеры взлома админки MaxSite CMS?

**Comment by Kotgo** [comment]
Нет, но всё же в целях превентивных мер?

**Comment by maxsite** [comment]
Ну а вы как думаете: есть защита или нет? ;-)

**Comment by Kotgo** [comment]
Я не хакер, сложно сказать, но то что доступ к входу в админ панель через логин и пароль доступен для всех как-то настораживает. Не зря же большинство вебмастеров прячут админку.

**Comment by maxsite** [comment]
Никто ничего не прячет. Это глупость. Поверьте, выяснить адрес админ-панели, даже хакером не нужно быть. А логин/пароль — хотите изобрести что-то новенькое? :)

**Comment by Kotgo** [comment]
И даже аппаратный брутфорс не возьмёт, у всех сложные пароли?

**Comment by Kotgo** [comment]
Подскажите, что в htaccess нужно закрыть чтобы доступ в админ панель был закрыт, а открыть можно только редактированием файла htaccess?

**Comment by maxsite** [comment]
От брутфорса есть секундные задержки. Подобрать пароль будет сложно. Для запрета доступа можете включить плагин admin_ip.

**Comment by Kotgo** [comment]
Понял, спасибо.
