### ISSUE TITLE
Замена путей адреса, страницы и расширения документа по желанию (слэшь /, html)

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#261]
Замена путей адреса, страницы и расширения документа по желанию (слэшь /, html)

Сейчас у нас так http://max-3000.com/category/versions

но может и работать так , если случайно набрать http://max-3000.com/category/versions/
для этого есть canoncal rel

Но нет возможности выбрать что хочется либо слэшь на конце страницы, либо без него (как сейчас), либо htm или html на конце документа.

К тому же нет возможности замены category на то что хочется или page на то что хочется и возможности сделать из них рабочие страницы.

Если набрать так http://max-3000.com/category/
то выдаётся 404 ошибка, а было бы не плохо там сделать список всех рубрик.
А здесь http://max-3000.com/page/ список выбранных страниц.
Для SEO это хорошо.

В общем это предложение для того чтобы Maxsite была ещё лучше. А если нет возможности это сделать, то будем использовать то, что есть. Хотя описанное выше было бы вообще супер.

**Comment by maxsite** [comment]
MaxSite CMS формирует адреса по определенным стандартам и нигде не создает их нерабочими. То что вы вводите непонятно что, не означает, что система должна их ообрабатывать и угадывать что именно вы хотите получить.

**Comment by Kotgo** [comment]
Вообще-то выше было предложение.

**Comment by maxsite** [comment]
Тогда я его не понял... Слишком всё в куче у вас получилось.

**Comment by Kotgo** [comment]
Я предложил сделать возможность устанавливать на конце страниц слэшь или расширение типа html  или htm по выбору пользователя.
А в папках  /category/ и /page/ сделать что-то текстовое, а не 404 ошибку.
Плюс возможность менять /category/ и /page/ на те название которые интересны пользователю.
Как-то так.

**Comment by maxsite** [comment]
> Я предложил сделать возможность устанавливать на конце страниц слэшь или расширение типа html или htm по выбору пользователя.

html используйте. Слэш нет, поскольку это другой сегмент URL.

>  А в папках /category/ и /page/ сделать что-то текстовое, а не 404 ошибку.

Сделайте. На уровне шаблона вы можете переопределить поведение любых типов.

 >  Плюс возможность менять /category/ и /page/ на те название которые интересны пользователю.

Можете создавать свои типы данных.

**Comment by Kotgo** [comment]
Подскажите, а как это сделать, если честно, то не нашёл подробного описания.

**Comment by maxsite** [comment]
Я могу посоветовать начать с простых вещей, хотя бы с умением работать в админ-панели и настроек default-шаблона. После этого уже браться за более сложные вещи. Вы хотите всё с наскока, так вы ничего не поймёте. Материалов на оф.сайте масса.

**Comment by Kotgo** [comment]
Максим, всё сделал как мне нужно было за исключением того, что не понял как делать свои адреса, не меняя код. 
Нашёл только платный  плагин для Maxsite , но разработчик его сам не использует.

> Материалов на оф.сайте масса.

Однако по смене имён адресов типа **category и page** либо добавление на конце адреса .html нет информации.

**Comment by maxsite** [comment]
Это типы данных. Они не меняются.
