### ISSUE TITLE
Настройка https 

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#262]
Подкажите, пожалуйста, как правильно настроить Maxsite и htaccess если у меня хостер бесплатно выдаёт SSL сертификаты, только нужно настроить саму CMS и htaccess
+ Редирект с http на https

**Comment by Kotgo** [comment]
Пытаюсь сделать, но у меня выдаются пути такого вида  index.php/page/ или возникает ошибка.
Больше трогать htaccess не стал. Настроить не смог.

**Comment by Kotgo** [comment]
А ещё хотел прежние адреса страниц перенести на новые сделал по примеру:

```

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_URI} ^/o-site/$
RewriteRule ^.*$ http://mysite.ru/page/o-site? [R=301,L]
</ifmodule>
```

При вводе старой страницы по примеру: 

` http://mysite.ru/o-site/ `
показывается 404 ошибка , а 301 редирект не срабатывает.

**Comment by maxsite** [comment]
MaxSite CMS из «коробки» работает с https. Ничего менять обычно не нужно, разве что сделать 301-редирект в .htaccess. Как именно, уточните у своего хостера.

**Comment by Kotgo** [comment]
Всё настроил, теперь сайт работает на https !
Примечания.
Только если здесь **range_url** указать сайт с протоколом https  **range_url — позволяет задать главное зеркало сайта, а также отсекает ошибочные запросы к сайту.** то ошибка выдаётся, только обычный http принимается. Отключил отметку для использования этого плагина. Также указал адрес сайта в файле конфига.
