### ISSUE TITLE
Плагин wpconvert

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#263]
Так как это плагин переноса данных из вордпресс, то хотел огласить  следующее..

1. Не переносятся картинки, которые находятся в комментариях вордпресс.
2. Не правильно работает перенос картинок в статьи. Если в вордпрессе картинка стояла в короткой новости до тега "more", то она (код этой же картинки) вставляется повторно в полную запись после тега "cut". В полной записи получается 2 одинаковые картинки.
Код 2 картинки вставляется на этапе создания xml.

![1](https://user-images.githubusercontent.com/44212501/47045736-989bf700-d1a4-11e8-9878-ebceff365030.jpg)![2](https://user-images.githubusercontent.com/44212501/47045737-989bf700-d1a4-11e8-85eb-b7f7a0874a49.jpg)

**Comment by maxsite** [comment]
Данные для переноса отдаются как есть. Если что-то неверно, значит такие данные в базе данных. Может какой-то плагин используется в wp. Точнее сказать невозможно, поскольку нужен полный доступ к базе, сайту и там уже смотреть и разбираться.

**Comment by Sergeysem** [comment]
Возможно плагин, это в принципе не страшно, вторую картинку можно и удалить из xml.

Что делать с картинками в комментариях, в xml  их нет, а перенести надо.

**Comment by maxsite** [comment]
Комментарии переносятся всё, что есть в базе comments. Проверяйте что там.

**Comment by Sergeysem** [comment]
Посмотрел в базу, нету там ссылок (вообще во всей базе нет ссылок изображений, которые в на комментах).
Посмотрел плагин, похоже выводится этой строкой. 
```
{
            $comment .= '<p><a class="thickbox" href="' . $url . '/wp-content/comment-image/' . commentimage_find_original($id, $i) . '"><img src="' . $url . '/wp-content/comment-image/' . $id . ($i==0?'':('-'.$i)) . '-tn.jpg"/></a></p>';
        }
```
Если посмотреть код страницы, то там так..

`<p><a class="thickbox" href="http://site.ru/wp-content/comment-image/5285.jpg"><img src="http://site.ru/wp-content/comment-image/5285-tn.jpg"/></a></p>`

5285 соответствует ID комментария. Как тогда выдернуть эти картинки, понять не могу.((

**Comment by Sergeysem** [comment]
Придется вручную вставлять (а из там около 1000) по такому типу..
<a href="http://site.ru/wp-content/comment-image/5285.jpg" title="Название" class="lightbox"><img src="http://site.ru/wp-content/comment-image/5285-tn.jpg"></a>

**Comment by Sergeysem** [comment]
Максим, тут еще вот что, Список комментаторов сайта после переезда, пуст. Ники комментаторов только в комментах и больше их ни где нет.

**Comment by maxsite** [comment]
Комментаторы станут анонимами.

> 5285 соответствует ID комментария. Как тогда выдернуть эти картинки, понять не могу.((

Тут либо вносить правки в php-файл экспорта WordPress (export-max.php), либо уже в обработчике MaxSite CMS (admin.php). Сделать обработку текста комментария.

**Comment by Sergeysem** [comment]
Максим.
Я почему спросил про комментаторов.
Если в ставить код картинки в его комментарий..
1. Он не сохраняется после отправки. Приходится нажимать на редактирование и в админке уже опять вставлять этот код.
2. Картинка после этого отображается в комментарии, но не увеличивается по клику (lightbox включен).
3. Если я изменю авторство этого комментария на себя, то картинка становится кликабельна и открывается в большем размере по клику.

Получаемый код комментария у анонима такой..
`<p><img src="http://svapka.ru/wp-content/comment-image/5285-tn.jpg"></p>`

У комюзера или админа такой..
`<a href="http://site.ru/wp-content/comment-image/5285.jpg" title="Название" class="lightbox"><img src="http://site.ru/wp-content/comment-image/5285-tn.jpg"></a>`

Даже прописав в самой базе полный код картинки у этих анонимов, на странице он все равно короткий.

Где можно изменить, чтобы код картинки у анонимов не резался?
Остальное сам, перенос и тд в ручную сделаю.

**Comment by maxsite** [comment]
Не совсем уловил проблему, но предполагаю, что дело в запрете размещать определенные тэги. В функции mso_get_comments() указано что разрешено. Если нужно изменить, то можно в своем шаблоне определить функцию на хук mso_get_comments_args и задать в виде массива свои опции. 

Теоретически может ещё где-то резаться html-тэги, но это нужен конкретный пример.

**Comment by Sergeysem** [comment]
> но это нужен конкретный пример.
У меня стоит на опен сервере, пример показать не смогу. Основной сайт (который хочу перенести) еще на вордпресс.
Но это можно сделать самому, залив 2 картинки (маленькую и большую) на какой либо сайт и прописать код в комментарии у анонима и потом этот же код у комюзера. У анонима будет урезанная версия в коде страницы.

**Comment by Sergeysem** [comment]
> Если нужно изменить, то можно в своем шаблоне определить функцию на хук mso_get_comments_args и задать в виде массива свои опции.

> 

Что то типа этого, только добавить нужные теги?
```
$r = mso_hook('mso_get_comments_args', $r);
	if ( !isset($r['tags']) )	$r['tags'] = '<p><img><strong><em><i><b><u><s><pre><code><blockquote>';

	if ( !isset($r['tags_users']) )	$r['tags_users'] = '<a><p><img><strong><em><i><b><u><s><pre><code><blockquote>';

	if ( !isset($r['tags_comusers']) )	$r['tags_comusers'] = '<a><p><img><strong><em><i><b><u><s><pre><code><blockquote>';
```

Если это, то в какой файл шаблона вставить?

**Comment by Sergeysem** [comment]
Все, Максим спасибо, 
Вставил в этот файл, а верней добавил `<a> к $r['tags']` в этом файле site.ru\application\maxsite\common\comments.php
Теперь нормально.

**Comment by Sergeysem** [comment]
Этот сайт у меня не обновляется, комментарии закрыты, мне бы перенести его и забыть. То есть управлять я им не буду, он как сателлит.

**Comment by maxsite** [comment]
Лучше всего в my-template.php.

**Comment by Sergeysem** [comment]
Максим, благодарю.

**Comment by Sergeysem** [comment]
Максим.
Не переносится одна статься с сайта. Я бы ее вручную перенес, но в ней 928 комментариев. Коментарии я же не могу сидеть писать (копипастить) за людей.((
Что посоветуете?

**Comment by Sergeysem** [comment]
Вырезал из этого xml все статьи, оставил только нужную. Размер файла 1,17 мб. Не получается тоже.

**Comment by maxsite** [comment]
Обычно, если сайт большой и есть разные нюансы, то я делаю перенос через AutoPost. Небольшой php-скрипт на wp-сайт, который создает текстовые файлы под каждую запись. Плюс в скрипте можно сразу сделать нужные замены. Текстовый формат прекрасно читается и обрабатывается. Стандартный xml-перенос, по сути «костыль» — в wp слишкм большой бардак в базе и вообще в структурах данных, поэтому с ним проще кинуть всё в одну кучу и разгребать уже при импорте в MaxSite CMS.

**Comment by Sergeysem** [comment]
Максим. 
Я немного не понял, скрипт AutoPost уже готовый где то есть?  И он комментарии тоже берет?

**Comment by Sergeysem** [comment]
Максим.
Я могу дать вам этот проблемный файл xml, можете помочь?
Статью я могу и сам вручную перенести, проблема с большим количеством комментариев, которые вручную добавлять от имени опубликовавшего, это неделя не меньше.((

**Comment by Sergeysem** [comment]
И еще, сайт на wp 3.1, если обновится до последней 4.8, то может что то изменится в плане создания XML?
Все же проблема с импортом уже в админке максайта, плагин не определяет статью.

**Comment by maxsite** [comment]
Проще было заказать перенос. :) В любом случае это нужно смотреть по месту почему не переносятся данные и уже с этим разбираться. Если бы в wp былы нормальная структура данных, я бы что-то смог предположить, а так только гадать...

**Comment by Sergeysem** [comment]
Максим.
У меня такой еще вопрос. Почему был выбран метод через xml? То чувство, что автор блога вовсе не автор, а занимается граббингом своих же статей.
У автора блога есть же полноценная база данных своего сайта, из нее ни как нельзя выдернуть нужные данные?

**Comment by maxsite** [comment]
Наверное потому что в 2008 году это был самый простой и очевидный способ. Просто из базы в базу нельзя, поскольку одна таксономия wp сведёт с ума кого угодно.

**Comment by Sergeysem** [comment]
Установил Денвер и Wampserver, на обоих вылетает такая ошибка (куча таких ошибок подряд) при импорте xml (прямо в админке максайта)..
```
A PHP Error was encountered
Severity: Notice

Message: main(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "WP_Term" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

Filename: wpconvert/admin.php

Line Number: 51
```
На опен сервере такого не было. Что то говорит эта ошибка

**Comment by Sergeysem** [comment]
Установил макса на сервер в субдобен. Проблемная статья загрузилась.
 Ошибки на сервере как выше, 51я

и 
такие (много)..
```
A PHP Error was encountered
Severity: Notice

Message: main(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "WP_Term" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

Filename: wpconvert/admin.php

Line Number: 254
```

и такие же, только 253.

Когда 51, то не определяет категорию, когда 253 и 254, непонятно.

Но загрузилось главное.  ))

**Comment by Sergeysem** [comment]
Максим.
Можно как то избавится от этих ошибок?

**Comment by Sergeysem** [comment]
Максим, все заработало без ошибок. Что сделал, установил по новой макса, включил плагин пагинация 1.2.3.., включил плагин category. Сохранил все настройки в шаблоне (там где они не определены, красный текст, просто сохранил, ни чего не изменял).
Затем по 2 статьи в xml импортировал через плагин. Ошибок нет, все статьи добавились, довольный как слон.
На локалке не работает.
Спасибо за помощь.

**Comment by Sergeysem** [comment]
А, еще хотел добавить по картинкам в комментариях.
Сделал файл с запросами обновления к базе вордпреса по типу..

```
UPDATE `wp_comments` SET `comment_content` = CONCAT(`comment_content`,'<br><br><a href="http://site.ru/путь к папке с картинкамиt/1476.jpg" title="" class="lightbox"><img src="http://site.ru/путь к папке с картинкамиt/1476-tn.jpg"></a>') WHERE comment_ID = 1476; 

UPDATE `wp_comments` SET `comment_content` = CONCAT(`comment_content`,'<br><br><a href="http://site.ru/путь к папке с картинкамиt/1481.jpg" title="" class="lightbox"><img src="http://site.ru/путь к папке с картинкамиt/1481-tn.jpg"></a>') WHERE comment_ID = 1481; 

и тд, всего 1021 запрос
```
Обновил таким образом базу вордпреса и в ней, в каждом нужном комменте, появилась ссылка на кортинку.

После экспорта, через плагин wpconwert, в xml файлах появились ссылки на картинки и при импорте xml на максайт, в се отображается.

Может кому пригодится.
