### ISSUE TITLE
Ошибка PHP

### ISSUE THREAD

**Issue by sdoggy** [maxsite/cms#264]
Один из сайтов выдает ошибку

> A PHP Error was encountered
> Severity: Warning
> Message: flock() expects parameter 1 to be resource, boolean given
> Filename: common/common.php
> Line Number: 1339
> 
> A PHP Error was encountered
> Severity: Warning
> Message: fwrite() expects parameter 1 to be resource, boolean given
> Filename: common/common.php
> Line Number: 1340
> 
> A PHP Error was encountered
> Severity: Warning
> Message: flock() expects parameter 1 to be resource, boolean given
> Filename: common/common.php
> Line Number: 1341
> 
> A PHP Error was encountered
> Severity: Warning
> Message: fclose() expects parameter 1 to be resource, boolean given
> Filename: common/common.php
> Line Number: 1342

Вот строки файла common.php
```
if (!$dir)
		{
			$fp = @fopen($mso_cache_last, 'w');
			flock($fp, LOCK_EX);
			fwrite($fp, time());
			flock($fp, LOCK_UN);
			fclose($fp);
		}
```
Требуется помощь. Очень!(

**Comment by Den2016** [comment]
application/cache имеет права на запись?

**Comment by sdoggy** [comment]
> application/cache имеет права на запись?


Да имеет. 
Разобрался уже. Проблема была в превышении inodes (
Всем спасибо за внимание.
