### ISSUE TITLE
Плагин Colorbox и Lightbox 

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#266]
Максим.
Существует такая проблема. Много букв, но обозначить это надо.

У меня есть сайт, версия 086. На нем стоял плагин Lightbox. Все было хорошо до какого то момента.
Решил проверить сайт на индексацию картинок (через 1 год примерно). Набираю запрос с альтов картинок и пробую в яндексе и гуле поиск по картинкам. Картинки находит, присмотрелся, ватемарки какие то не такие. Перешел на сайт, а это не мой сайт. Думаю нифига себе, стырили картинку вместе со статьей, да еще и в выдаче на первом месте. Начал искать, моих картинок в выдаче нет, ни на каком месте, ноль!!

Захожу на свой сайт, нажимаю на картинку и вижу, что сохранить картинку как или открыть картинку в новом окне и тп  в меню нет!! Есть пункты про сохранение ссылки и тп, но это не то.

![2018-10-30_19-08-06](https://user-images.githubusercontent.com/44212501/47730504-bb85db00-dc7b-11e8-86e6-9f3085f5541d.jpg)

Что делаю, беру плагин Colorbox и после активации вижу уже такое меню..
![2018-10-30_19-10-31](https://user-images.githubusercontent.com/44212501/47730600-eff99700-dc7b-11e8-8831-dfc42991d854.jpg)

Через месяц мои картинки появились в поисковиках, а те, которые были на других сайтах, пропали в небытие.

Это было предисловие.

Теперь собственно что пишу.

Сайт, версия 100. 
1. При активации плагина Colorbox, не работают вв код [gallery] [gal] ( в тексте записи на странице сайта, вместо картинок я вижу эти вв коды вместе с кодом картинок).
Это самый удобный способ вставки картинок. Другой способ, через одиночную картинку или через див галереи, вставлять просто неудобно и долго.

2. Lightbox, вв коды работают, но картинки не индексируются. Также непонятно как изменить размер открываемого окна картинки. В Colorbox можно выставить в %, а вот Lightbox вообще нет настроек.

Что нужно. 
Как заставить плагин Colorbox видеть вв теги [gallery] [gal] или в Lightbox нужно сделать так, чтобы меню по правому клику по всплывшему окну, открывалось правильное, то есть такое, чтобы можно было картинку сохранить или открыть картинку в новом окне и тп? Также для Lightbox как изменить масштабирование всплывающего окна?

**Comment by maxsite** [comment]
Colorbox я удалил 3 года назад. Так что все новые версии и его развитие — вопросы не ко мне. Lightbox отдает ровно то, что предусмотрено самим jQuery-плагином.

**Comment by Sergeysem** [comment]
> Colorbox я удалил 3 года назад. Так что все новые версии и его развитие — вопросы не ко мне. 
Хорошо, что надо сделать, чтобы движок увидел вв теги [gallery] [gal] ?
Ведь Lightbox их видит и поменялось ведь не в Colorbox (там те же теги), а что то в движке.

**Comment by Sergeysem** [comment]
> Lightbox отдает ровно то, что предусмотрено самим jQuery-плагином.

> 
Это неправильный подход к озвученной проблеме.

**Comment by maxsite** [comment]
Эти bb-коды — уровень плагина Lightbox (и Colorbox). Я не поддерживаю сторонние плагины и не разрабатываю jQuery-плагины. Вопросы нужно задавать их авторам.

**Comment by Sergeysem** [comment]
Максим я понял вас.
Но вы тоже услышьте. Плагин  Lightbox находится в сборке, он не работает правильно. Или надо написать в инфо файле, что этот плагин затрудняет индексацию картинок или поменять jQuery-плагин. Это не хотелка же, я вам написал в первом сообщение, как он есть на самом деле.

**Comment by maxsite** [comment]
Lightbox работает нормально и он не может затруднять индексацию. Это обычный IMG обёрнутый ссылкой A. Все подобные плагины работают точно также. Если у вас возникли проблемы с индексацией, то уточняйте конкретную причину у поисковика. Если на сайте нет html-ошибок, то технических проблем для этого просто нет.
