### ISSUE TITLE
В дистрибутиве master 2 файла SCSS не проходят компиляцию из-за кодировки

### ISSUE THREAD

**Issue by murvanidze** [maxsite/cms#268]
При первой компиляции SCSS из дефольного шаблона выругался на два файла, что Invalid UTF-8 character, a именно: 

`assets/sass/template/_forms.scss`
`assets/sass/template/_message.scss` 

Глянул - и действительно. Может и другие файлы в ANSI, но там нет кириллических комментов, и поэтому они проходят.
Проблема решается конвертацией в UTF-8 в Notepad++, например. 
Предлагаю исправить файлы в дистрибутиве. 
Некритично.

**Comment by maxsite** [comment]
Ок. Заменю, спасибо.
