### ISSUE TITLE
Как поменять размер превьюшек у загруженных изображений.

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#269]
Доброго времени.
Решил поменять оформление сайта и понял, что с новым дизайном размер превьюшек картинок слишком маленький 150х150.

Вопрос собственно в том, как поменять размер превьюшек? Я так понимаю нужно все картинки по новой загружать, чтобы создались превьюшки с новыми размерами или можно без загрузки как то это сделать?
Речь не про изображение к записи, а про превьюшки, которые находятся в статье.

**Comment by maxsite** [comment]
Может миниатюры? Всё зависит от того, как они прописаны в тексте записи.

**Comment by Sergeysem** [comment]
Прописаны так.
site.ru/uploads/картинка.jpg оригинальная картинка.
site.ru/uploads/mini/картинка.jpg  миниатюра картинки.

**Comment by maxsite** [comment]
В Загрузках есть операция по обновлению миниатюр. Если имя файла не меняется, то проблем не должно быть.

**Comment by maxsite** [comment]
Шутите?

**Comment by Sergeysem** [comment]
Максим, прошу прощения. Но это кнопка (ссылка Загрузка файлов) как то не явно указывает, что при ее нажатии, откроется еще одно меню. 
В 086 версии у меня такого нет, поэтому и в 100 версии сюда не обратил внимания. 

Спасибо.
