### ISSUE TITLE
Поддержка в MaxSite CMS bootstrap-шаблонов

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#27]
Сейчас бутсраповских шаблонов как грязи. В основном они делаются ка лендинги, но иногда встречаются типовые блоговские варианты. Было бы неплохо придумать способ простой адаптации таких шаблонов под MaxSite CMS. Чтобы была простая схема переноса готовой html-верстки в MaxSite CMS-шаблон. Естественно, в этом варианте теряется много типовой функциональности default-шаблона, но зато нет необходимости возится с дизайном и версткой.

**Comment by cuprum** [comment]
Наверное, по простому не получится. В таких же шаблонах своя структура, классы. Если только сделать какой-то каркас-шаблон в котором такая же HTML структура, как в бутстрап + на эту структуру навесить базовые бутстраповские классы. Вот уже с таким шаблоном будет проще работать.

**Comment by maxsite** [comment]
Скорее не каркас-шаблон, а общая методика переделки любого html-шаблона под MaxSite CMS. Бутстрап лишь пример, — фреймворк или html может быть произвольным.

**Comment by cuprum** [comment]
Ну если как методика, то в целом несложно - добиваться такой же html-структуры с нужными классами как в определенном фреймворке и кидать CSS фрейморка-шаблона в папку /css шаблона CMS.

**Comment by vimruler** [comment]
Чтобы можно было брать любой html-шаблон и как-то использовать в MaxSite CMS нужно чтобы в движке можно было любой стандартный html-блок трансформировать в требуемый вид. Например, верстка виджетов в сайдбаре имеет жёсткую структуру, которую можно сменить только путем создания форка соответствующего плагина. Если структуру html-кода не менять, то переделка будет сводится к трудозатратной трансформации стилей из шаблона-донора в стили разрабатываемого шаблона. Т.е. просто кинуть css-файлы шаблона-донора в папку разрабатывамеого шаблона не получится. Я так понимаю, Юра об этом и написал:
> В таких же шаблонах своя структура, классы.

По большому счёту, всему html-коду, который формируется в шаблоне можно задать любую структуру и любые классы. Сложность только с плагинами и стандартными функциями. Если бы была какая-то возможность задавать в шаблоне свой вывод для любого нужного плагина (по типу type_foreach или с использованием mso_set_val), то проблема бы снялась.

**Comment by maxsite** [comment]
Кинуть получится, только это будут стили к другим блокам. :) Мы уже как-то обсуждали возможность менять имена css-классов или придумать какой-то свой специфичный префикс, но отказались. Если же разобраться детально, то получится, что

* стили и html-разметка модельной сетки (main) может быть произвольной.
* стили и html-разметка шапки (компоненты) также произвольны.
* аналогично и подвал.
* виджеты частично настраиваются через mso_set_val и mso_show_sidebar.

Таким образом остается только часть content, которая формируется в type-файлах. Причем часть файлов можно менять через type_foreach-файлы. Более сложные вещи вроде формы комментирования — это да, проще оставить как есть. Но такие случаи единичны.

**Comment by vimruler** [comment]
> Более сложные вещи вроде формы комментирования — это да, проще оставить как есть. Но такие случаи единичны.

Да, именно. Думаю, что на первое время будет достаточно инструкции как с этим работать.
