### ISSUE TITLE
Ошибка обновления комментария

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#270]
Не пойму в чем дело. На опенсервере редактирование комментариев работает нормально, на удаленном сервере не работает, выдает "Ошибка обновления" на красном фоне, если нажать сохранить комментарий в админке. Даже если ни чего не делать с комментарием, просто открыть для редактирования и сохранить, та же ошибка.

 Дальше скрин из phpMyAdmin опенсервера и удаленного сервера. Может причина в различиях версий? Проверил через phpinfo() версию PHP, на обоих серверах показывает PHP Version 5.6.38.

![1](https://user-images.githubusercontent.com/44212501/48775078-6e7aaf00-ece5-11e8-940c-425e55fae3ec.jpg)

Комментарии отправляются нормально, но редактировать их не могу. Как побороть?

**Comment by maxsite** [comment]
Вообще-то версия php разная. У нас максимум 7.0.

**Comment by Sergeysem** [comment]
Стоп, загружаю на сервер файл с содержанием..
```
<?php
phpinfo();
?>
```
Обновляю страницу, вижу PHP Version 5.6.38.
Что я делаю не так, чтобы узнать версию PHP?

**Comment by maxsite** [comment]
Понятия не имею. У вас на скриншоте другая версия.

**Comment by Sergeysem** [comment]
Скриншот из phpMyAdmin

**Comment by Sergeysem** [comment]
7 версия будет работать или лучше 5,6? То есть какую версию предпочтительней попросить установить хостера?

**Comment by maxsite** [comment]
7-я нормально.

**Comment by Sergeysem** [comment]
Вот что мне ответили с хостинга..

> Здравствуйте. У Вас оба сайта работают с 5.6.38, phpMyAdmin работает через другую версию, всё верно.

Попросил сменить версию для phpMyAdmin, вот что ответили..
phpMyAdmin работает на системном уровне и его не нужно никуда переключать. Он к работе ваших сайтов отношения не имеет.

**Comment by Sergeysem** [comment]
Замкнутый круг какой то, что делать то?

**Comment by maxsite** [comment]
Смотрите логи, может там какие-то сообщения.

**Comment by Sergeysem** [comment]
Я не знаю где там эти логи, в журнале ошибок ispmanager пусто. Так ведь не ошибка PHP, а информационное сообщение в админке, что ошибка обновления. 
Бред какой то.

**Comment by maxsite** [comment]
Если такое сообщение, то что-то с базой. MaxSite CMS отреагировала стандартно.

**Comment by Sergeysem** [comment]
Вот что ответил хостер, давал ему доступ..

> Тут дело не в php, а в БД - скрипт пытается пихнуть в базу невпихуемое. У нас используется ветка 10,2 MariaDB и там не всё можно использовать, что есть в старых версиях. Скорее всего есть несоответствие какого либо поля с передаваемым форматом данных, надо чтоб разработчик смотрел.

**Comment by Sergeysem** [comment]
Кстати, проверил другой сайт, он 086 версии, та же проблема с редактирование комментария. Я их ни когда не редактировал, но нужно было изменить в одном дату и вот "это" вылетело.

**Comment by maxsite** [comment]
Значит смотрите логи базы. Откуда же я знаю, что там изменили в ново версии.

**Comment by Sergeysem** [comment]
Вот что я нашел, больше нигде ни каких логов..

> [20-Nov-2018 18:11:56 Europe/Moscow] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

**Comment by maxsite** [comment]
Это настройка php. 

Логи смотрите по sql-запросам. Какая-то несовместимость с вашей версией MySQL и запросами MaxSite CMS. Какие именно невозможно сказать, пока не будет логов ошибок. Попросите хостера, чтобы он выловил эти запросы.

**Comment by Sergeysem** [comment]
По поводу логов что ответили..

> На хостинге лога SQL нету, у нас сейчас идёт: "Queries per second avg: 852.146" такое кол-во не реально логировать, любой диск нагнёт такой лог. Вам только в сам скрипт добавлять логирование завпроса перед выполнением.

Максим, помогите.

**Comment by Sergeysem** [comment]
Вот такое есть, как раз при редактировании комментария 3715.
> 94.178.173.214 - - [20/Nov/2018:17:22:31 +0300] "POST /admin/comments/edit/3715 HTTP/1.0" 200 29722 "http://site.ru/admin/comments/edit/3715" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 OPR/56.0.3051.52"
Но это о чем то разве говорит?

**Comment by Sergeysem** [comment]
Один сайт у меня давно, на 086 версии. Я на нем проблему не замечал, так как не редактировал комментарии в админке. Второй сайт у меня перенесен с вордпресса, на хостинге на новом движке он всего 4 дня. Нужно было поменять дату у одного комментария и вылезла эта ошибка обновления. Дату пришлось менять в самой базе через phpMyAdmin.
Подумал может неправильно что сделал и поэтому ошибка, проверил на другом сайте с 086 версией сайта, там тоже самое. 
Посмотрю, что там в #161

**Comment by maxsite** [comment]
На OpenServer вроде как есть MySQL 10 версии. Можете попробовать поставить сайт на эту базу и проверить что-там выходит.

**Comment by Sergeysem** [comment]
В файле application/config/database.php установил $db['default']['db_debug'] = TRUE;
После того, как нажал сохранить комментарий в админке, вылетела такая ошибка..

> Ошибка БД
> Error Number: 1366
> Incorrect integer value: 'NULL' for column 'comments_users_id' at row 1
> UPDATE `mso_comments` SET `comments_content` = 'belopolyy\nЖдем... Почта если что. :25a:
> \"Email', `comments_date` = '2012-08-20 00:03:36', `comments_approved` = 1, `comments_author_name` = 'admin', `comments_users_id` = 'NULL', `comments_comusers_id` = 'NULL' WHERE `comments_id` = '3715'
> Filename: /var/www/zend/data/www/site.ru/maxsite/admin/plugins/admin_comments/edit.php
> Line Number: 58

Не то?

**Comment by maxsite** [comment]
Уже похоже на правду. Скорее всего дело в каком-то строгом режиме MySQL. Попробую у себя воспроизвести проблему и отловить ошибку.

**Comment by maxsite** [comment]
Попробуйте в файле application\maxsite\admin\plugins\admin_comments\edit.php примерно в строчках 44 и ниже заменить «'NULL'» на «0». Примерно так получится:

`$data['comments_users_id'] = 0;`

**Comment by Sergeysem** [comment]
Сделал, тоже самое, ошибка обновления. 
Добавил еще  0 к комюзеру, все, заработало.))

```
44 $data['comments_users_id'] = 0;
45 $data['comments_comusers_id'] = 0;
```

Сейчас на сервере попробую, отпишусь.

**Comment by maxsite** [comment]
Там все вхождения NULL на 0 нужно заменить.

**Comment by Sergeysem** [comment]
Понял, сделаю

**Comment by Sergeysem** [comment]
Максим, спасибо большое, все заработало и на сервере.
Изменил:
```
44 $data['comments_users_id'] = 0;
45 $data['comments_comusers_id'] = 0;

50 $data['comments_comusers_id'] = 0;
55 $data['comments_users_id'] = 0;
```

**Comment by maxsite** [comment]
Хорошо. Внесу изменения в MaxSite CMS.

**Comment by maxsite** [comment]
Выложил обновление. Если что-то еще по базе, говорите. С этой версией мало кто работает, сразу поправим. :)

**Comment by Sergeysem** [comment]
Да вроде пока ничего не обнаружил. Второй сайт с 086 версии перенесу на 100, буду настраивать, если что вылезет, сообщу.

Yа опенсервере вернулся на MySQL 5.6, все работает с этими же строчками.

**Comment by Sergeysem** [comment]
На 086 версии тоже заменил, заработало.
