### ISSUE TITLE
Большой размер папки кеша.

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#271]
Сегодня обратил внимание, что папка кеша application/cache, занимает больше 400 мб.
Нажал на кнопку "очистить кеш системы" в админке, кеш из папки удалился.
Включено динамическое кеширование в "основные- служебное." Плагин global_cache не активирован.
В файле mso_config.php стоит дефолтное значение $MSO->config['cache_time'] = 9600;

Установил 5 секунд, обновляю папку application/cache каждые 10 сек , файлы из нее не удаляются. Удаляются только тогда, когда сам нажмешь в админке.

Я так понимаю не срабатывает задание по крону?

Попробовал выключить "динамическое кеширование", тоже самое, файлы в папке application/cache только прибавляются, но никак не стираются через 5 сек.

И не совсем понятно, если кеширование отключено, то почему создаются файлы в папке кеша?

**Comment by maxsite** [comment]
Они и не должны затираться. У каждого файла свое время. Если нет обращений, то он не меняется. Если есть, то просто обновляется.

**Comment by Sergeysem** [comment]
Хм, у меня места на диске так не хватит, куда такой размер в 400 мб, при том что сайт со всеми картинками занимает около 250 мб

**Comment by Sergeysem** [comment]
И не совсем понятно, если кеширование отключено, то почему создаются файлы в папке кеша?

**Comment by maxsite** [comment]
может включен кэш БД?

**Comment by Sergeysem** [comment]
$MSO->config['cache_time'] = 9600; За что отвечает этот параметр? Я дкумал что через это время папка кеша очищается.

**Comment by Sergeysem** [comment]
/www/svapka.ru/application/cache/db тут пусто. А где он включается кеш дб, что то я не знаю?

**Comment by maxsite** [comment]
У нас кэш пофайльный. Каждый сам по себе.

**Comment by Sergeysem** [comment]
Но у меня там нет столько страниц, чтобы 400 мб набралось

**Comment by maxsite** [comment]
А сколько файлов в кэше?

**Comment by maxsite** [comment]
В database.php $db['default']['cache_on']

**Comment by Sergeysem** [comment]
Когда было 400 мб, я не считал. Сейчас около 3, ноя только что очищал кеш.

**Comment by Sergeysem** [comment]
$db['default']['cache_on'] = FALSE;

**Comment by maxsite** [comment]
400 мб — это много. Это текстовые файлы, понаблюдайте что там за содержимое, будет понятно. Самый большой файл — это опции, может до 1Мб доходить. Остальные файлы — мелкие. Если что-то крупное, то смотрите по содержимому. Может какой плагин так работает.

**Comment by Sergeysem** [comment]
Хорошо, я послежу за этой папкой. Потом (дня через 3) отпишусь.

**Comment by Sergeysem** [comment]
Логика такая. Файл создается то, если не было ни каких изменений в этом файле, сервер отдает эту копию пользователю и в течении 9600 файл не обновляется. Как только прошло 9600 секунд и если обратились к этому файлу, то сервер отдает уже не его, а перезаписывает его и отдает.
Так?

**Comment by maxsite** [comment]
> Так это работает?
Да. 

>  Было бы неплохо какой то параметр, чтобы через определенное время, папка кеша очищалась сама
Смысла нет. Это снизит его эффективность и создаст повышенную нагрузку в момент построения.

**Comment by Sergeysem** [comment]
Последил за папкой. Набралось примерно 800 файлов, общим размером около 50 мб. Размер папки и количество файлов больше не растет. Это нормально, при условии, что на сайте можно попасть на не более 200 страниц (пагинация, статьи, категории)?

![777](https://user-images.githubusercontent.com/44212501/48966174-90c24480-efe5-11e8-9aed-43380ba21057.jpg)

**Comment by maxsite** [comment]
Посмотрите по времени создания файлов, какой самый старый и самый новый. В теории между ними не должно быть большого промежутка (скажем не более суток). Самым поздним должен быть _mso_cache_last.txt.  Если так, значит всё нормально. В кэш попадают разные данные, например sitemap даёт довольно много файлов, поскольку это ресурсоемкие вычисления, которые лучше закэшировать. 

Проблем на сервере от 1000 или даже 10 000 файлов точно не будет.

**Comment by maxsite** [comment]
Да, ещё момент. Время жизни кэша по умолчанию = 86400 (24 часа). Если кэш слишком большой, то его можно уменьшить в mso_config.php в $MSO->config['cache_time'].

**Comment by Sergeysem** [comment]
Самый старый _mso_cache_last.txt 11/23/18 05:54 
Самый свежий 11/24/18 09:52
Послежу еще, отпишусь позже.

**Comment by maxsite** [comment]
Значит все нормально.

**Comment by Sergeysem** [comment]
Хорошо, закрою пока, если опять вырастет до 400 мб, открою.
