### ISSUE TITLE
Валидность кода

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#272]
Хотел спросить, не страшно ли такое, а именно повторяющийся тег H1?
Для примера приведу страницу категории http://max-3000.com/category/versions

Вот что показывает валидатор.. https://validator.w3.org/nu/?doc=http%3A%2F%2Fmax-3000.com%2Fcategory%2Fversions&showsource=yes

И у комментариев нет заголовков.. https://validator.w3.org/nu/?doc=http%3A%2F%2Fmax-3000.com%2Fpage%2Fustanovka-i-nachalnaja-nastrojka-maxsite-cms-video

**Comment by maxsite** [comment]
Пофиг.

**Comment by Sergeysem** [comment]
Полегчало.))
Но надо все равно исправить?

**Comment by maxsite** [comment]
Кому надо?

**Comment by Sergeysem** [comment]
Ну я имею в виду, чтобы код был валидный, хоть и пофиг, все равно надо исправить (у себя).

**Comment by Sergeysem** [comment]
Или это никому не надо, только валидатору? ))
