### ISSUE TITLE
Не работает редирект

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#275]
В плагине redirect 1.3 вставляю такие строки..
```
http://site.ru/uploads/image.GIF | http://site.ru/uploads/image.gif
http://site.ru/uploads/iMaGes.GIF | http://site.ru/uploads/images.gif
```
Редиректа не происходит, открывается та же самая ссылка или первая или вторая.
То есть суть, редирект на те же урлы, только с прописными буквами вместо заглавных.

Почему так не работает?

**Comment by maxsite** [comment]
Это обычные файлы. Сервер их отдает как есть. MaxSite CMS здесь даже не запускается.

**Comment by Sergeysem** [comment]
Максим, а через htaccess как правильно организовать редирект с заглавных на прописные.
В интернете встречается один пример, но он не работает почему то.

```
RewriteEngine On
RewriteBase /
# If there are caps, set HASCAPS to true and skip next rule
RewriteRule [A-Z] - [E=HASCAPS:TRUE,S=1]
# Skip this entire section if no uppercase letters in requested URL
RewriteRule ![A-Z] - [S=28]
# Replace single occurance of CAP with cap, then process next Rule.
RewriteRule ^([^A]*)A(.*)$ $1a$2
RewriteRule ^([^B]*)B(.*)$ $1b$2
RewriteRule ^([^C]*)C(.*)$ $1c$2
RewriteRule ^([^D]*)D(.*)$ $1d$2
RewriteRule ^([^E]*)E(.*)$ $1e$2
RewriteRule ^([^F]*)F(.*)$ $1f$2
RewriteRule ^([^G]*)G(.*)$ $1g$2
RewriteRule ^([^H]*)H(.*)$ $1h$2
RewriteRule ^([^I]*)I(.*)$ $1i$2
RewriteRule ^([^J]*)J(.*)$ $1j$2
RewriteRule ^([^K]*)K(.*)$ $1k$2
RewriteRule ^([^L]*)L(.*)$ $1l$2
RewriteRule ^([^M]*)M(.*)$ $1m$2
RewriteRule ^([^N]*)N(.*)$ $1n$2
RewriteRule ^([^O]*)O(.*)$ $1o$2
RewriteRule ^([^P]*)P(.*)$ $1p$2
RewriteRule ^([^Q]*)Q(.*)$ $1q$2
RewriteRule ^([^R]*)R(.*)$ $1r$2
RewriteRule ^([^S]*)S(.*)$ $1s$2
RewriteRule ^([^T]*)T(.*)$ $1t$2
RewriteRule ^([^U]*)U(.*)$ $1u$2
RewriteRule ^([^V]*)V(.*)$ $1v$2
RewriteRule ^([^W]*)W(.*)$ $1w$2
RewriteRule ^([^X]*)X(.*)$ $1x$2
RewriteRule ^([^Y]*)Y(.*)$ $1y$2
RewriteRule ^([^Z]*)Z(.*)$ $1z$2
# If there are any uppercase letters, restart at very first RewriteRule in file.
RewriteRule [A-Z] - [N]
RewriteCond %{ENV:HASCAPS} TRUE
RewriteRule ^/?(.*) /$1 [R=301,L]
```

**Comment by maxsite** [comment]
Это файл, а имя файла на сервере регистронезависим. Попаробуйте создать файл SSS.txt и потом sss.txt. Получите ошибку. Поэтому то что вы хотите имеет нулевой смысл.

**Comment by Sergeysem** [comment]
Проиндексированное изображение в поисковике имеет такую ссылку http://site.ru/uploads/iMaGes.GIF. Если зайти на сервер по этой ссылке, то оно недоступно. 
Переименовал имя файла св нижний регистр.. http://site.ru/uploads/images.gif. Захожу по этой ссылке, изображение доступно. Захожу по ссылке http://site.ru/uploads/iMaGes.GIF .. недоступно.

Какой нулевой смысл?

**Comment by maxsite** [comment]
Тогда не знаю. Никогда с такой проблемой не сталкивался. На сервер нужно сразу нормальные файлы закачивать.

**Comment by Sergeysem** [comment]
Я же с вордпреса переехал, там эти файлы открывались. Вот что было в htaccess
RewriteEngine on
DirectoryIndex index.php index.html index.htm index.phtml
RewriteRule ^sitemap.xml$ /wp-content/uploads/sitemap.xml [L]
AddDefaultCharset UTF-8

```
# BEGIN WPSuperCache
# END WPSuperCache
<IfModule mod_security.c>
<Files async-upload.php>
SecFilterEngine Off
SecFilterScanPOST Off
</Files>
</IfModule>
<IfModule mod_security.c>
<Files upload.php>
SecFilterEngine Off
SecFilterScanPOST Off
</Files>
</IfModule>
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```
Я так понимаю где то стоит разрешение на игнорирование верхнего регистра?

**Comment by maxsite** [comment]
Переименуйте файлы в нормальный нижний регистр и поправьте в html на эти адреса. Делать редиректы для ошибочных картинок — это выше моего понимания.

**Comment by Sergeysem** [comment]
Я все поправил, имя файла в нижнем регистре, в html тоже уже давно. Но поисковик упорно ищет http://site.ru/uploads/iMaGes.GIF у меня на сервере, который недоступен.

**Comment by maxsite** [comment]
Ну и пусть ищет. Если ответ 404, то потом отстанет. Первый раз слышу, чтобы у гугла была такая проблема. Он, конечно, настойчивый, но не настолько, чтобы постоянно проверять 404-адреса.

**Comment by Sergeysem** [comment]
> Если ответ 404, то потом отстанет
А если картинка, верней ссылка на картинку вставлена где то на форумах, на сайтах, то что, потеря ссылающегося сайта?

**Comment by maxsite** [comment]
В вашем случае — либо настраиваейте редирект на уровне сервера, либо создайте файл с ошибочным именем на сервере — на линуксе это вроде как возможно, хотя наверное зависит от самого сервера. В любом случае я вам ничем помочь не могу, гуглите.
