### ISSUE TITLE
Не работает фоновое сохранение записи

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#277]
После переезда с 086 версии на 100, не работает фоновое сохранение записи (не появляется зеленая табличка "Запись сохранена"), ну и запись естественно не обновляется на сайте. Обычное сохранение работает. Обновлял через _update_mso_dev
В логе SQL пусто, как будто на кнопку не нажимаю, ошибок БД нет, проверяю на опен сервере. 
На 2 сайте, который с вордпреса перенесен, все работает (на опенсервере).

**Comment by Sergeysem** [comment]
Хм, зашел на удаленный сервер, туда, где установлена 086 версия. Там тоже в фоне не сохраняет (проверил несколько раз, сохранял измененную запись и проверял на сайте изменения).
С базой что то? Если да, то как обновить структуру?

**Comment by maxsite** [comment]
База не меняется. Скорее всего проблема с браузером или js. Фоновое сохранение это post/ajax-запрос.

**Comment by Sergeysem** [comment]
В том же браузере один сайт работает, другой нет (на опенсарвере).
Свеже установленный движок работает отлично, если подключить его к базе от моего сайта, который на 086 версии, перестает работать.

**Comment by maxsite** [comment]
База не менялась.

**Comment by Sergeysem** [comment]
Можно, как выход, перенести все записи с комментариями через AutoPost на новую, нормально работающую систему. Но тут теряются все комюзеры.
Я не знаю что делать.

**Comment by maxsite** [comment]
При чём тут записи? Смотрите логи ошибок, может там что-то.

**Comment by Sergeysem** [comment]
Записи? Не причем конечно, но как вариант перенести сайт на нормально рабочую версию, это через экспорт импорт с помощью AutoPost. Что бы не искать, из за чего оно там не работает.

Лог SQL пустой, если нажимать сохранить в фоне. Как будто я не нажимаю кнопку. Попробовал даже кнопкой таб подвести фокус на эту кнопку и нажать enter, тоже ни чего не происходит.

Конечно, не такая уже проблема, сохранение в фоне, но если уже переезжать, так нормально чтобы работало.

**Comment by maxsite** [comment]
При чём тут SQL? Смотрите лог php-ошибок.

**Comment by maxsite** [comment]
Плюс ошибки js в браузере: аякс это js+php.

**Comment by Sergeysem** [comment]
Посмотрел, вот что в мозиле..
SyntaxError: missing : after property id https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/Missing_colon_after_property_id

**Comment by maxsite** [comment]
Нет такого браузера. Гуглите.

**Comment by Sergeysem** [comment]
Ну если судить по отладчику, то указывает сюда..
```
	function select_page_type() {
		var page_type_id = +$(".mso-tabs-box.other input:radio:checked").val(),
			page_type_obj = {blog:1,static:2,Статьи для пасе:3},
			page_meta_block = $(".page_meta_block"),
			checked_type;

		for (var key in page_type_obj) {
			if (page_type_obj[key] === page_type_id) {
				checked_type = key;
			}
		}
```
Кажется вспомнил, что создавал тип страницы, как раз называется "пасе". Удалить не могу.

**Comment by Sergeysem** [comment]
Да, ошибка тут. Создал новый тип страниц на кириллице и с пробелами "Новый тип страниц".
В работающем сайте, перестало работать фоновое сохранение.

**Comment by Sergeysem** [comment]
Максим, помогите удалить этот неправильный тип страницы.

**Comment by Sergeysem** [comment]
Максим, там (при добавлении нового типа страниц) наверно как то предупреждение какое то повесить. А то ломай потом голову.)))

**Comment by Sergeysem** [comment]
Ну да, в пробеле, 43 символ как раз пробел, если судить по ошибке.

**Comment by maxsite** [comment]
Слишком специфичная вещь. Может только какую-то подсказку добавить.

**Comment by Sergeysem** [comment]
Ну я про это, что типа добавлять без пробелов иначе не будет работать фоновое сохранение.

**Comment by Sergeysem** [comment]
В этом файле   jquery.min.js:2:40278
application/maxsite/common/jquery/jquery.min.js
Мозила пишет предупреждение, что..
Метод getPreventDefault() является устаревшим. Для его замены используйте метод defaultPrevented.
