### ISSUE TITLE
Фокус на сообщение об ошибке отправки комментария, не работает!

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#279]
Если отправить пустой комментарий или капча неверная и тд, сообщение об ошибке высвечивается не понятно где, пользователь этого сообщения не видит.

Правильно отрабатывают (делают фокус на это сообщение) только 2 браузера, Мозила и IE, остальные просто открывают страницу  с самого сначала, после отправки комментария и все.

Что делать с остальными браузерами? Может что то уже устарело в движке и нужно подстроиться под браузеры?

**Comment by Sergeysem** [comment]
И еще, сообщение об ошибке, должно высвечиваться рядом с формой отправки комментария, а не где то там после статьи. Это же очевидно, почему изначально не сделано так?

**Comment by maxsite** [comment]
Мозила — нет такого браузера. Пишите правильно.

**Comment by Sergeysem** [comment]
Значит лиса

**Comment by maxsite** [comment]
Ну вы же не называете виндовс — майкрософтом. Для тех, у кого браузер основная программа, такие вещи слишком режут слух и говорят о неопытности. Поэтому я вас и поправил.

**Comment by maxsite** [comment]
Будет время, посмотрю.

**Comment by maxsite** [comment]
Скорее всего я просто заменю этот jQuery-плагин на простой код, чтобы не было зависимости.

**Comment by maxsite** [comment]
В файле application\maxsite\shared\type\page\units\page-comments.php примерно в строках 26 и ниже замените код на такой:

```
if ($out = mso_get_new_comment( array('page_title'=>$page['page_title']) ))
{
	$out .= '<script> $(function(){ $("body,html").animate({scrollTop: $("#comments").offset().top-50}, 500); }); </script>';
	
	echo $out;
}
```

**Comment by Sergeysem** [comment]
Поменял, все работает. Можно все же сделать как то, чтобы это сообщение выводилось рядом с комментарием, а не после статьи. Если комментариев много, чтобы посетителю не приходилось листать страницу вниз, до формы отправки комментария?

Ну то есть ошибка отправки должна выводится около формы ввода комментария.

**Comment by Sergeysem** [comment]
Ну тогда я не закрываю.

**Comment by Sergeysem** [comment]
Не знаю правильно, нет, но работает. Перенес сюда:
![44](https://user-images.githubusercontent.com/44212501/49644767-ec9fbb00-fa32-11e8-9d0d-f13dbff3e432.png)
Выглядит так:
![5555](https://user-images.githubusercontent.com/44212501/49644790-fd503100-fa32-11e8-832a-f78729474bf3.png)

Создал новую запись, комментарии отправляются.

**Comment by maxsite** [comment]
Я бы советовал использовать стандарные type из shared. Для кастомизации шаблона предусмотрено куча type_foreach-файлов. Так — на ровном месте создаёте себе проблемы...

**Comment by Sergeysem** [comment]
Назад пути нет, и я не знаю как правильно пользоваться type_foreach

**Comment by Sergeysem** [comment]
Например есть такая строка в application\maxsite\shared\type\page\units\page-comments.php
`if ($f = mso_page_foreach('page-comments-posle-list')) require($f);`
Создаю файл page-comments-posle-list.php, загружаю его в попку type_foreach швблона.
В этом файле создаю код:
```
<?php if (!defined('BASEPATH')) exit('No direct script access allowed'); 
/*
	выводим ошибку около формы ввода комментария
*/
echo '<span><a id="comments"></a></span>';

				// если был отправлен новый коммент, то обрабатываем его и выводим сообщение в случае ошибки
if ($out = mso_get_new_comment( array('page_title'=>$page['page_title']) ))
{
	$out .= '<script> $(function(){ $("body,html").animate({scrollTop: $("#comments").offset().top-50}, 500); }); </script>';
	
	echo '<br>' . $out . '<br>';
}
# end of file
```
Правильно?

**Comment by Sergeysem** [comment]
Но как тогда быть с этим же кодом, который уже присутствует в файле application\maxsite\shared\type\page\units\page-comments.php только немного выше?

**Comment by Sergeysem** [comment]
Да, так и есть, сообщение об ошибке выводится 2 раза. Первая после статьи, а вторая около формы ввода комментария (как прописано в type_foreach файле).

Максим, вот вы говорите использовать type_foreach файлы, но ведь не получается в данном случае. Надо удалять эту строку скролла из application\maxsite\shared\type\page\units\page-comments.php, тогда type_foreach будет нормально работать. Или копировать page-comments.php в каталог шаблона и там его менять, без применения type_foreach.

Что я сделал не правильно, подскажите?

**Comment by Sergeysem** [comment]
Код исправлять мне не надо, я не это прошу. Просто подскажите алгоритм, чтобы код скролла в page-comments.php ( в shared каталоге) не имел приоритета над type_foreach файлом с тем же кодом скролла.

**Comment by maxsite** [comment]
Вот на более простом примере. https://github.com/maxsite/cms/blob/dev/application/maxsite/shared/type/page/page.php

Вот такой кусок кода:

`
if ($f = mso_page_foreach('page-head-meta')) 
{
	require($f);
}
else
{ 
	mso_head_meta('title', $pages, '%page_title%'); // meta title страницы
	mso_head_meta('description', $pages); // meta description страницы
	mso_head_meta('keywords', $pages); // meta keywords страницы
}
`
Если сработает условие if, то будет выполнен код из type_foreach-файла page-head-meta.php, а ветка else будет проигнорирована. Таким образом вы перенесете логику на уровень шаблона. В исходном type-файле ничего править не нужно.

Бывают включения type_foreach-файлов без ветки else. В этом случае файл просто подключается как дополнительный. Например для вывода какого-то своего кода.

Поэтому если вам нужно заменить кусок кода из type-файла,  ищите type_foreach-файлы с else. Если таковых нет, то достаточно скопировать один единственный файл (который нужно изменить) из shared в свой шаблон по тому же пути.

**Comment by Sergeysem** [comment]
Спасибо, понял, в данном случае только копирование page-comments.php в каталог шаблона и там его редактирование.
Но я думаю вы все же перенесете вывод ошибки к форме комментария и не придется заниматься этим на другом сайте, который буду делать на MaxSite CMS,

**Comment by maxsite** [comment]
Я это и сделал и уже выложил.

**Comment by Sergeysem** [comment]
Что то сразу и не заметил.
Там код (фрагмент).
`echo '<a id="comments_message"></a>' . $message_out . '`
Сообщение выводится близко к комментарию, без отступа, особенно если после комментария hr стоит, то наезжает на него..

![ada](https://user-images.githubusercontent.com/44212501/49652141-a22a3880-fa4a-11e8-80f0-3ca19dfac60c.png)
Хотелось бы видеть этот код с br (это не мне, это (br) вообще наверно нужно там добавить).
`echo '<a id="comments_message"></a><br>' . $message_out . '`

Но наверно Максим вы не будете этого делать, и я сделал type_foreach файл  page-comments-posle-list.php с содержимым..
```
<?php if (!defined('BASEPATH')) exit('No direct script access allowed'); 
/*
выводим пробел после комментариев
*/
echo '<br>';
# end of file
```
И стало выглядеть так..
![ksdkd](https://user-images.githubusercontent.com/44212501/49652385-62178580-fa4b-11e8-9d0e-758f57d12fc3.png)

Максим, сами подумайте, нужен там br или нет.

**Comment by Sergeysem** [comment]
Хотя все шаблоны разные, в дефолтном шаблоне нет hr после последнего комментария и выглядит сообщение об ошибке нормально.
