### ISSUE TITLE
D4 — дизайн шаблона

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#28]
Пусть D4 будет заготовкой для будущего default. Давайте определяться с дизайном. За основу можно будет взять какой-то современный шаблон и переделать под свою задачу.

**Comment by vimruler** [comment]
Дизайн предложить сложно. Вкусы то у всех разные. Возможно имеет смысл сделать что-то типа такого шаблона - http://www.templatemonster.com/demo/52839.html или http://www.templatemonster.com/demo/52805.html (только не ясно как они будут выглядеть на страницах записей и т.д.). Сейчас стало много сайтов попадаться в таком стиле. Наверно модно такое оформление. Чем мне оно нравятся лично мне - визуальня простота.

Можно что-то более классическое сделать. Но тут мне тем более пока сложно что-то подсказывать - надо искать.

**Comment by maxsite** [comment]
Я думаю, что должен быть «типовой» вариант, содержащий шапку, подвал и сайдбар.

**Comment by mrGooDMaster** [comment]
Хотелось бы шаблон в стили 4pda.

**Comment by Sanes** [comment]
Предлагаю фрейворк Uikit

**Comment by mrGooDMaster** [comment]
А будет возможность обновиться со старой cms?

**Comment by Exgibichi** [comment]
http://confit-nbt.blogspot.ru
http://moments-theme.blogspot.ru
http://wilder-veethemes.blogspot.ru
http://classictradition-veethemes.blogspot.ru
http://gossip-veethemes.blogspot.ru
http://scoop-veethemes.blogspot.ru
http://addiction-soratemplates.blogspot.in
http://sora-article-soratemplates.blogspot.in
Вот на мой взгляд, неплохие темы. Только стоит убрать слайдеры и весь лишний мусор.

**Comment by skull3d** [comment]
Exgibichi, отличные примеры, есть из чего выбрать.
