### ISSUE TITLE
Отступ в плагине вывода списка рубрик

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#280]
Доброго времени.
Хотел спросить, как сделать отступ между родительским рубриками в виджете списка рубрик?
На скрине как сейчас и стрелкой указано как надо? 
Максим, кроме вас никто не поможет.

![444](https://user-images.githubusercontent.com/44212501/49463000-e29e7200-f810-11e8-919e-17b9c5d5081b.png)

**Comment by Sergeysem** [comment]
То есть нужно разделить разделы визуально, хотя бы пробелом, иначе все сливается и навигация становится не понятной.

**Comment by maxsite** [comment]
Смотреть какая получается html-структура и от этого задавать css-правила. Без html-кода что-то сказать сложно.

**Comment by Sergeysem** [comment]
Вот так выглядит код..
```
<ul class="mso-widget-list1">
    <li class="group">
        Раздел1
        <ul class="child level1">
            <li class="group">
                Подраздел1
                <ul class="child level2">
                    <li>Подраздел 1 подраздела 1
                </ul>
            </li>
            <li>Подраздел2</li>
        </ul>
    </li>

    <li class="group">
        Раздел2
        <ul class="child level1">
            <li class="group">
                Подраздел1
                <ul class="child level2">
                    <li>Подраздел 1 подраздела 1</li>
                </ul>
            </li>
            <li>Подраздел2</li>
        </ul>
    </li>
</ul>
```

**Comment by Sergeysem** [comment]
В коде я сделал визуально, где нужен пробел.

**Comment by Sergeysem** [comment]
Если делать отступы в CSS для li class="group", то отступы получаются везде, где надо и не надо.

**Comment by Sergeysem** [comment]
Может пометь логику в файле, где воспроизводится эта конструкция?
Только в каком, я не нашел.

**Comment by maxsite** [comment]
Наверное что-то типа такого:

`ul.mso-widget-list1 > li.group { margin-bottom: 30px; }`

**Comment by Sergeysem** [comment]
Максим, спасибо, заработало, но там еще есть текущий раздел, если стоит на радел1, то опять все соединяется Раздел1 с Разделом2
Вот код, когда выбран текущим Раздел1

```
<ul class="mso-widget-list1">
<li class="current-page">
    <span><font color="#7b0000">Раздел1</font></span>
    <ul class="child level1">
<li class="group">
    Подраздел1
    <ul class="child level2">
        <li>
            <a href="Подраздел1 подраздела1</li>
                </ul>
                </li>
                <li>Подраздел2 подраздела1</li>
                </ul>
                </li>

                <li class="group">Раздел2
            <ul class="child level1">
                <li class="group">
                    Подраздел1
                    <ul class="child level2">
                        <li>Подраздел1 подраздела1</li>
                    </ul>
                </li>
                <li>Подраздел2 подраздела1</li>
            </ul>
        </li>
    </ul>
```

**Comment by Sergeysem** [comment]
Максим, большое спасибо.Теперь то, что нужно, жалко что в плагине нет полей для вставки стилей для настройки.

Вот так у меня сейчас выглядит полностью..

```
ul.mso-widget-list1 {
	padding-left: 10px;
	list-style-type: none;
	margin-bottom: 5px;
}

.mso-widget-list1 li:before {
	float: left;
	margin-left: -10px;
	margin-right: 5px;
	content: "\2022";
	position: absolute;
}

ul.child {
	padding-left: 15px;
	list-style-type: none;
	margin-bottom: 2px;
	margin-top: 2px;
}

ul.mso-widget-list1 > li.group, ul.mso-widget-list1 > li.current-page {
	margin-bottom: 10px;
}
```

**Comment by Sergeysem** [comment]
А, еще в самом плагине пришлось поменять строку
`'class_ul'=>'mso-widget-list', `
на
`'class_ul'=>'mso-widget-list1', `

**Comment by Sergeysem** [comment]
И вот так выглядит, может кому пригодится..

![22](https://user-images.githubusercontent.com/44212501/49469834-f6060900-f821-11e8-98f5-35f58f010f49.png)
