### ISSUE TITLE
Ошибка добавления комментария админом

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#282]
Максим, доброго времени, это опять я )) 
Сегодня попытался ответить на комментарий и вылетела "ошибка добавления комментария"
Анонимы, комюзеры, отправляется нормально (проверил), у админа ошибка.

Включил $db['default']['db_debug'] = TRUE;
вылетала такая ошибка при добавлении комментария..
```
Ошибка БД
Error Number: 1364
Field 'comments_author_name' doesn't have a default value
INSERT INTO `mso_comments` (`comments_users_id`, `comments_page_id`, `comments_author_ip`, `comments_date`, `comments_content`, `comments_parent_id`, `comments_approved`) VALUES ('1', '77', '127.0.0.1', '2018-12-05 18:12:33', '35345', '0', 1)
Filename: W:\domains\site.ru\system\database\DB_driver.php
Line Number: 331
```
MySQL Maria-10.2

**Comment by Sergeysem** [comment]
Сделал как тут.. https://github.com/maxsite/cms/issues/223

> Вместо (можно просто закомментировать)
> `$res = ($CI->db->insert('comments', $ins_data)) ? '1' : '0';`
> напишите
> ```
> $res = $CI->db->insert('comments', $ins_data);
> pr($res);
> $res = 0;
> ```

После отправки комментария, пишет "False"

**Comment by Sergeysem** [comment]
Переключил Опенсервер на MySQL-5.6, все работает.
Выходит еще одна ошибка по базе MySQL Maria-10.2

**Comment by Sergeysem** [comment]
Поясню. Этот сайт был на 086 версии. Комментариев давно никто не писал. Буквально 2 месяца назад пришло письмо от Хостинга, что аккаунт перенесен на другой сервер. Похоже на старом сервере была MySQL-5.6 (я этого просто не помню), а на новом аккаунте уже MySQL Maria-10.2. Но так как никто давно не писал, то проблема с отправкой комментариев выявилась только сейчас, уже на 100 версии.

**Comment by maxsite** [comment]
На 100-й версии проблем нет?

**Comment by Sergeysem** [comment]
На 100 версии на MySQL-5.6 все работает (на опенсервере проверяю), на MySQL Maria-10.2 не работает. Об этом и пишу.

**Comment by Sergeysem** [comment]
Проверил на другом сайте, 100 версия, переезжал с вордпресса, там всё работает.
А тут (где не работает) просто подключился к существующей базе и все. 
То есть выходит, админ фейковый))) раз ругается на поле Field 'comments_author_name'
Как выйти из этой ситуации? Как создать нормального админа?

**Comment by Sergeysem** [comment]
Но на на MySQL-5.6  ведь работает, админ не фейковый))

**Comment by maxsite** [comment]
Пока ничего не скажу, нужно вначале как-то воспроизвести проблему. Лучше на чистой системе последней dev-версии. Возможный вариант, что исходная версия базы ещё более старая, где-то 0.40 — точно не понмю, но где-то в этом районе были мелкие изменения. В phpMyAdmin в таблице comments в поле comments_author_name по умолчанию что стоит?

**Comment by Sergeysem** [comment]
У меня сайт с 2012 года, не помню точно, какая тогда версия была. Может и 40, потом обновился до 086 (не помню уже, да и не было поводов запоминать это).

**Comment by Sergeysem** [comment]
Я могу установить новую dev версию, попробовать чистую версию на  MySQL-5.6 и MySQL Maria-10.2
Затем залить дистрибутив на опенсервер и просто подключить старую базу.

Так?

**Comment by maxsite** [comment]
Дайте просто скрин структуры comments в phpMyAdmin. Проблему воспроизвести у себя не могу, возможно дело в старой базе.

**Comment by Sergeysem** [comment]
Попробовал на dev версии 100.7. Новая установка, работает  и на MySQL-5.6 и MySQL Maria-10.2
Если подцепить старую базу, на MySQL-5.6, на MySQL Maria-10.2 не работает.

**Comment by Sergeysem** [comment]
Вот скрин..

![11](https://user-images.githubusercontent.com/44212501/49534440-f6aea600-f8da-11e8-8d27-2f75c9c7fbb7.png)

**Comment by maxsite** [comment]
В  comments_author_name по умолчанию нужно изменить на пустую строчку.

**Comment by Sergeysem** [comment]
Работает со все вариантами, кроме "нет". даже Если выбрать "Как определено" и написать абракадабру там.

**Comment by Sergeysem** [comment]
Интересно, какой еще "подарок" может вылезти. Вроде все работает, и на тебе, вылезло.))

**Comment by Sergeysem** [comment]
Если убрать галочку с NULL и нажать сохранить, то ошибка..

![444](https://user-images.githubusercontent.com/44212501/49535708-2f03b380-f8de-11e8-9864-099b00fd0a2c.png)

**Comment by maxsite** [comment]
Посмотрите просто как в новой базе это прописано и сделайте аналогично.

**Comment by Sergeysem** [comment]
В новой базе NULL - нет, но тут у меня не получается убрать галочку, ошибка, скрин выше.

**Comment by maxsite** [comment]
Ну разбирайтесь, нужно сделать как в нормальной базе.

**Comment by Sergeysem** [comment]
сейчас попробую на удаленном сервере сделать, может опенсервер не дает.

**Comment by Sergeysem** [comment]
А вот на удаленном сервере, NULL стоит нет. Изменил только comments_author_name на пусто. Все работает, спасибо Максим.

![118](https://user-images.githubusercontent.com/44212501/49536567-4ba0eb00-f8e0-11e8-8ca7-02339711eaa8.png)
