### ISSUE TITLE
Не хватает пробела Привет, Посетитель!Выйти

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#284]
Максим, удаляю все файлы из type каталога шаблона, чтобы заменить на type_foreach файлы (по возможности).
Выяснил, почему у меня файл type\page\units\page-comment-form-tmpl.php лежит в каталоге шаблона (сделал давно и забыл как говорится).
Если залогинится админом, то в поле приветствия в форме отправки комментария, отображается нормально Привет, Admin! Выйти. Речь про пробел после восклицательного знака.
Если залогинится комюзером, то пробела нет Привет, Посетитель!Выйти

Вот скрины для наглядности:

![11](https://user-images.githubusercontent.com/44212501/49664109-57201d80-fa6a-11e8-8347-dd3d5dc87bef.png)

Тут не хватает пробела..

![4444](https://user-images.githubusercontent.com/44212501/49664620-d8c47b00-fa6b-11e8-9a99-713b39779fd4.png)

Исправите?

**Comment by maxsite** [comment]
Пробел там скорее всего не поможет. Скорее всего просто включено сжатие html-кода страницы. Лучший вариант — это прописать для этой ссылки css-класс и настроить его как нужно.

**Comment by Sergeysem** [comment]
Да, это было из за сжатия, отключил, пробел появился.
Но с сжатием все же вот так работает, пробел есть. tf(' Выйти') }}

**Comment by Sergeysem** [comment]
Если без сжатия и с пробелом тут tf(' Выйти') }}, то 2 пробела не появляются, нормально отображается и css не нужен.

**Comment by Sergeysem** [comment]
И опять же, чтобы класс прописать, нужно этот файл копировать в свой шаблон и там присваивать. У этой ссылки не задан класс.

**Comment by Sergeysem** [comment]
Вот что в коде страницы:
```
<div class="mso-comments-user mso-comments-comuser">
Привет, <a href="http://site.ru/users/18">Тестер22</a>!
<a href="http://site.ru/logout">Выйти</a>
</div>
```

**Comment by Sergeysem** [comment]
И еще, когда вот так происходит, это нормально?

![33](https://user-images.githubusercontent.com/44212501/49666037-35c23000-fa70-11e8-9136-943ce13d2358.png)

**Comment by Sergeysem** [comment]
Максим, ну вы подправите файл или мне копировать его в type каталог шаблона?
Повторю, с пробелом работает при сжатии, не обрезает пробел.

**Comment by maxsite** [comment]
Пропишите для ссылки класс mso-comments-logout. Я его тоже поставлю.

**Comment by Sergeysem** [comment]
Хорошо, но нужен файл с изменениями.

**Comment by Sergeysem** [comment]
Вот так правильно?

`<a class="mso-comments-logout" href="{{ getinfo('siteurl') }}logout">{{ tf('Выйти') }}</a>`
```
.mso-comments-logout
{
margin-left: 5px;
}
```

**Comment by Sergeysem** [comment]
Максим, ну раз уже правите, то может и для ссылки комюзера тоже класс добавите?

`<a href="{{ getinfo('siteurl') . 'users/' . $comuser['comusers_id'] }}">{{ $comuser['comusers_nik'] }}</a>

Чтобы менять на свой вкус.

**Comment by maxsite** [comment]
К этой ссылке есть доступ по правилу `.mso-comments-comuser a`. Пока занят, позже выложу файл.

**Comment by Sergeysem** [comment]
Спасибо, работает, не забыть бы это все.))

```
.mso-comments-logout
{
 margin-left: 5px;
 color: #aaa
}
.mso-comments-comuser a
{
color: #aaa
}
```

**Comment by Sergeysem** [comment]
Еще хотел спросить, почему у  админа нет ссылки на профиль около формы отправки комментария, верней не только у админа а у юзеров? Дискриминация?

**Comment by Sergeysem** [comment]
И у юзеров в этом же файле, пред ссылкой Выйти, стоит таки пробел после восклицательного знака.
```
<div class="mso-comments-user">
{{ tf('Привет') }}, {{ getinfo('users_nik') }}! <a href="{{ getinfo('siteurl') }}logout">{{ tf('Выйти') }}</a></div>
```

**Comment by maxsite** [comment]
Кинул обновление.

> Еще хотел спросить, почему у админа нет ссылки на профиль около формы отправки комментария, верней не только у админа, а у юзеров? Дискриминация?

У них ссылки в меню. Но, если нужно, то tmpl-файлы как раз для того, чтобы подстраивать вывод под свою задачу.

**Comment by Sergeysem** [comment]
Там вот еще что, при сжатии html-кода, надпись "Ожидает модерации", прилипает.

![5555](https://user-images.githubusercontent.com/44212501/49671417-3911e780-fa81-11e8-9af5-5f2a24ecbc91.png)

**Comment by maxsite** [comment]
Наверняка там есть свой css-класс.

**Comment by Sergeysem** [comment]
Да, написал, не посмотрев..

```
.mso-comment-approved
{
margin-left: 5px;
}

```

**Comment by Sergeysem** [comment]
Максим, вот вы пишете, что tmpl-файлы можно копировать в каталог шаблона, но не желательно?

**Comment by Sergeysem** [comment]
Ладно, спасибо, закрываю))

**Comment by Sergeysem** [comment]
Доброго времени Максим.
Хотел еще спросить, в списке последних комментариев на странице site.ru/comments тоже нет пробелов пр включенном сжатии html кода. Верней режет не пробел, а переход на другую строку
Вот так выглядит код комментария:

`<div class="mso-comment-content"><p>Отличное видео!</p><p>Поддерживаю просьбу по использованию ушки и юнит файлов.</p></div>`
А вот так выглядит этот же комментарий на странице site.ru/comments:

`<a href="http://max-3000.com/page/ustanovka-i-nachalnaja-nastrojka-maxsite-cms-video#comment-5009"><b>Дмитрий »</b> Отличное видео!Поддерживаю просьбу по использованию ушки и юнит файлов.</a>`

Получается, что из кода удаляется <p></p>. Можно как то решить это, чтобы не обрезалось?

**Comment by Sergeysem** [comment]
Максим, вы ответьте пожалуйста что то?

**Comment by maxsite** [comment]
Пока не смотрел. Выходной же был, отдыхать нужно. :)

**Comment by Sergeysem** [comment]
Посмотрите, как время будет.

**Comment by maxsite** [comment]
Примерно посмотрел: вроде бы всё верно работает. При выводе на этой странице происходит удаление части html-тэгов, в том числе через автопарсер. Если этого не сделать, то сломается сам вывод (он в ul/li-списке). А делать какие-то сложные замены ради пробела... Тем более, что для таких случаев предусмотрены хуки по котором можно управлять выводом.

**Comment by Sergeysem** [comment]
Ну тогда и статьи надо сжимать, пусть будет все одной строкой, все быстрее будет загружаться. Посетители сами пробелы расставят.

**Comment by maxsite** [comment]
Не понимаю, при чём тут это?..

**Comment by Sergeysem** [comment]
Все го то надо, чтобы `<p>` заменялся на `&nbsp;`

**Comment by Sergeysem** [comment]
Что значит причем? Если все равно что текст слипается в комментариях, должно быть все равно как написана статья, по вашей логике.

**Comment by maxsite** [comment]
Это не «всего то», а значительный кусок кода, для того, чтобы правильно обработать парные тэги. Если типовой вариант не устраивает, цепляйтесь хуком и меняйте как вам нужно.

**Comment by Sergeysem** [comment]
Вот так более читабельно, но появляются пробелы в некоторых словах.
_Admin » ДимаМожно._ было
_Admin »  Дима Можн о._ стало

$comments_content = str_replace("<p>","&nbsp",$comments_content);
$comments_content_1 = strip_tags($comments_content); 

И еще, в комментарии может быть первой цитата, затем абзац. Надо и `<blockquote>` пробелом заменять.

**Comment by Sergeysem** [comment]
На счет слова **_Можн о_**, почему появляется пробел? Это слово первое после тега  `<p>`

**Comment by Sergeysem** [comment]
```
$comments_content = htmlentities($comments_content, null, 'utf-8');
$comments_content = html_entity_decode($comments_content);
$comments_content = str_replace('<p>', '&nbsp;', $comments_content);
$comments_content_1 = strip_tags($comments_content);
$comments_content_1 = html_entity_decode($comments_content_1);
```
Код комментария:
`<p><b>Сергей</b></p><p>Можно.</p>`
Код на странице site.ru/comments
`СергейМожно` **СергейМожно** до изменений.
`&nbspСергей&nbspМожно` **Сергей Можно** после изменений.

Максим, не знаю, какой тут такой сложный код нужен был, если даже я справился. Не желание?

**Comment by maxsite** [comment]
То что вы сделали «кодом» назвать сложно. Какой-то бессмысленный набор функций. Ещё раз: если вам нужно заниматься такой «ерундой», то цепляйтесь хуком и делайте что хотите.

**Comment by Sergeysem** [comment]
Максим сделайте правильно, зачем я это должен делать? У вас из коробки ни чего толком не работает, то пробелы не вам важны, то еще что то. 
Какой еще хук? Мне не надо менять вывод под свои нужды, сделайте чтобы выводилось изначально правильно.

**Comment by Sergeysem** [comment]
> Какой-то бессмысленный набор функций.
какой бы он бессмысленный не был, он выполняет свою функцию, а именно расставляет неразрывные пробелы там, где они нужны, в данном случае.

**Comment by Sergeysem** [comment]
В общем закрываю, автор не хочет заняться делом.

**Comment by maxsite** [comment]
Скорее не собирается тратить время на подобную глупость.

**Comment by Sergeysem** [comment]
Блогер, который хочет сделать свой сайт на этом движке, должен глубоко изучить PHP, затем все настраивать, вплоть до такой нелепой ошибки парсинга, которая проявляется при сжатии html-кода.
Понимаете почему нет популярности у движка? Вопрос задать даже негде. Здесь не считается, так как  ответа можно услышать от автора, а автор вопросов не слышит.

**Comment by maxsite** [comment]
Прежде всего — я вам ничего не должен. То что вы захотели какую-то «хотелку», не значит, что я должен всё бросать и её срочно делать. Это исключительно ваша проблема, которую не нужно смешиться ни со мной, ни с «движком». В крайнем случае у вас всегда есть выбор.

**Comment by Sergeysem** [comment]
>  Это исключительно ваша проблема, которую не нужно смешиться ни со мной, ни с «движком».

То есть, слипание слов на странице comments при включенном сжатии  html-кода, это исключительно моя проблема, которую я сам придумал? Я же говорю, автор не слышит.

**Comment by maxsite** [comment]
Никому, кроме вас, это не нужно. Сами выдумали проблему, — сами и решайте.

**Comment by Sergeysem** [comment]
Хорошо. 
Поделюсь с обществом решение проблемы, кому это нужно. Прошу потом отписаться, если это было нужно и помогло.
При включенном плагине last_comments, вывод комментариев на странице site.ru/comments идет через этот плагин.
Комментарии выводятся в одну строку. Если в комментарии (на странице статьи) были допущены переносы строк, то на странице site.ru/comment идет слипание слов в этих местах (см. примеры выше).
Чтобы этого не происходило, нужно в плагине last_comments, в файле index.php найти строки..

```
$comments_content_1 = strip_tags($comments_content);
$comments_content = mso_str_word($comments_content_1, $options['words']); // ограничение на количество слов
```
И до них написать следующий код..

```
$comments_content = str_replace('</p>', ' ', $comments_content);
$comments_content = str_replace('</blockquote>', ' ', $comments_content);
$comments_content = str_replace('<blockquote>', ' ', $comments_content);
```

После всех изменений, общий код в этом месте должен выглядеть так..

```
$comments_content = str_replace('</p>', ' ', $comments_content);
$comments_content = str_replace('</blockquote>', ' ', $comments_content);
$comments_content = str_replace('<blockquote>', ' ', $comments_content);
$comments_content_1 = strip_tags($comments_content);
$comments_content = mso_str_word($comments_content_1, $options['words']); // ограничение на количество слов
```
Все работает, слипшихся слов нет. Минусом данного способа является то, что при обновлении движка, перезапишется папка с плагином last_comments, но это решаемо, достаточно иметь копию этой папки и потом заменить ее при необходимости.
Есть еще один вариант, это изменить код этого плагина самим автором, чтобы не перезаписывать папку при обновлении. Но как выше выяснилось, ему это не интересно. Удачи всем.))
