### ISSUE TITLE
Экранирование всех кавычек в записях при сохранении в фоне

### ISSUE THREAD

**Issue by miguralex** [maxsite/cms#285]
Перевел несколько сайтов на версию Maxsite 1.0. При редактировании уже добавленных записей на сайте по нажатию на кнопку "Сохранить в фоне" все кавычки экранируются и сохраняются в таком виде:

`<div class=\"video\"><iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/VaciE3fDpLY\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div>`

Если сохранять запись не "в фоне", а просто кнопкой "Сохранить", то данной проблемы нет. Для обработки текста используется parser_default. Проблема наблюдается на всех сайтах с версией 1.0.

**Comment by maxsite** [comment]
См. https://github.com/maxsite/cms/issues/267

**Comment by maxsite** [comment]
Можно использовать любую, включая 7.0. На 7.1 и выше пока есть проблемы (из-за CodeIgniter), но я занимаюсь их решением.
