### ISSUE TITLE
сайт https://remontpc96.ru Дефолтный шаблон

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#286]
сайт https://remontpc96.ru Дефолтный шаблон не оптимизирован для мобильных устройств
![121](https://user-images.githubusercontent.com/29428663/50043186-9b767380-0091-11e9-8731-c6fbbc15d8c5.png)

**Comment by website-999development** [comment]
ниче особо не менял

**Comment by maxsite** [comment]
Пользуйтесь нормальными инструментами, а не какими-то «левыми» поделками: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fremontpc96.ru%2F&tab=mobile

Там же все рекомендации.

**Comment by website-999development** [comment]
так это ж Яндекс Вебмастер!!

**Comment by maxsite** [comment]
Ну я тут при чём? Еще раз: пользуйтесь нормальными инструментами.
