### ISSUE TITLE
cайт http://school-vr.ru Дефолтный шаблон ниче не менял Последняя версия MaxSite CMS 101 

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#288]
после установки вылезло такое
![opera _2018-12-24_171214_school-vr ru](https://user-images.githubusercontent.com/29428663/50399318-6a3c2880-07a0-11e9-83b4-c428e4cf87fa.png)

и нижний футер пропал

**Comment by maxsite** [comment]
Хоть одна запись с рубрикой есть?

**Comment by maxsite** [comment]
В файле application\maxsite\admin\plugins\admin_home\admin.php добавьте строчки с pr(), чтобы получилось так (примерно строчка 208-209):

```
		arsort($m); // обратный порядок
		echo '<h4 class="mar50-t i-bar-chart">' . t('Статистика рубрик') .'</h4>';
		
		pr($max);
		pr($max1);
		
		foreach($m as $id=>$count)
		{
```
Что выводится?

**Comment by website-999development** [comment]
добавил, спасибо, сейчас так 
![2018-12-24_220126_school-vr ru](https://user-images.githubusercontent.com/29428663/50404270-ba7ab100-07c7-11e9-8072-9c025d7be0da.png)

**Comment by website-999development** [comment]
а футер пропал из-за одного из этих плагинов

page_views_widget
search_form_widget
rater_widget
favorites_widget
guestbook_widget
box_pages_widget
di_yandex_money_widget

**Comment by website-999development** [comment]
счас их убрал все вернулось

**Comment by maxsite** [comment]
С консолью все нормально. Я как раз поправлю старые «хвосты» от другого вывода, ошибки не будет. Просто обновите файл из dev-версии.

«Футер пропал» что означает?

**Comment by website-999development** [comment]
вот так сайт выглядел 
![_school-vr ru](https://user-images.githubusercontent.com/29428663/50405388-a047cf80-07d5-11e9-9e0e-001dd3d00580.png),
без футера

**Comment by maxsite** [comment]
Наверное компоненты на настроили.

**Comment by website-999development** [comment]
просто убрал плагины
page_views_widget
search_form_widget
rater_widget
favorites_widget
guestbook_widget
box_pages_widget
di_yandex_money_widget
и
 все вернулось
ниче не менял больше

**Comment by website-999development** [comment]
ща вот так на http://school-vr.ru 
![opera _2018-12-24_235517_school-vr ru](https://user-images.githubusercontent.com/29428663/50405515-78596b80-07d7-11e9-8d4a-62a7b6ee0239.png)

**Comment by maxsite** [comment]
Может не плагины, а виджеты?

**Comment by website-999development** [comment]
ну да, виджеты

**Comment by website-999development** [comment]
гле то в них проблема

**Comment by maxsite** [comment]
Под одному переименовывайте и смотрите. Начните со сторонних.

**Comment by website-999development** [comment]
да это понятно, лень копаться, обойдусь без них

**Comment by website-999development** [comment]
спасибо, так то движок оч хороший, все нравится, когда будет мультиязычность из коробки?

**Comment by maxsite** [comment]
Да хоть сейчас. Ставите в отдельный каталог и будет другой язык. :)

**Comment by website-999development** [comment]
а базу одну можно юзать?

**Comment by website-999development** [comment]
ясно  спасибо 
![51dd52e5-af4e-434d-9a71-b4076bc43fe7](https://user-images.githubusercontent.com/29428663/50405826-37b02100-07dc-11e9-8825-fe4267de1e67.jpg)
