### ISSUE TITLE
Движок не отсылает письма

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#289]
Я уже задавал в прошлом году вопрос про письма с сервера. Не отправляет движок их почему-то... 

Как можно отследить, где именно проблема? Смотрю в логах ошибок своего ВПС - ничего про это не отмечается. Может быть права какие-то надо выставлять специфические?

**Comment by maxsite** [comment]
Какая версия MaxSite CMS?

**Comment by trommo** [comment]
Пробовал на разных версиях в течение последнего года, на различных доменах. Только что проверил последнюю - 101 версию. То же самое. Ошибок в файлах логов на сервере по этому поводу не вижу. Что делать?

**Comment by maxsite** [comment]
А как указан email сервера в настройках?

**Comment by trommo** [comment]
Та в том-то и дело, что указан - и в настройках контактной формы 

```
[form]
[options]
email = ot3@ukr.net
[/options]
.....
[/form]
```
и в Email администратора, и в Email для комментариев. Т.е. движок не только не присылает данные, введенные в форму, но еще и игнорирует уведомления на почту администратора, а также при комментариях.

Может быть какой-нибудь модуль у ПХП/Апача надо вручную подключать, когда ВПС, а не обычный хостинг, чтобы почтовые отправления работали?

**Comment by maxsite** [comment]
То есть email сервера у вас указан как ukr.net???

**Comment by Den2016** [comment]
Я как-то поднимал этот вопрос, Макс меня отшил, но посмею еще раз свои пять копеек воткнуть:
В моем случае помогает в common.php  в функции mso_mail перед самой отправкой ($res = @$CI->email->send();) закомментировать строку

`	//$CI->email->_safe_mode = true; # иначе CodeIgniter добавляет -f к mail - не будет работать в не safePHP
`

**Comment by trommo** [comment]
Сейчас да - @ukr.net, но я пробовал и почту, привязанную к имени домена - там были украинские ящики на @domain_name.co.ua, @domain_name.com.ua, @domain_name.net.ua. Для эксперимента пробовал и @gmail.com - не работало.

**Comment by maxsite** [comment]
Адрес сервера должен быть от вашего домена. Например webmaster@ВАШ.ДОМЕН

**Comment by trommo** [comment]
Ну вот, например, есть сайт на домене *.co.ua - у него есть действующий почтовый ящик mail@*.co.ua. Его я должен указывать в качестве почты для контактной формы, а также email сервера? Указал его только что там и там - не приходит сообщение из формы.

**Comment by maxsite** [comment]
В форме указывается только адрес получателя. Вы почитайте хелп по форме. А email-адрес отправителя (сервера!) должен быть только от этого же сайта. Иначе все письма у вас спамные. Ни один почтовик их не пропустит.
