### ISSUE TITLE
watermark

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#290]
Доброго времени.
Есть ли возможность установки watermark не одного, а двух. Название сайта например вверху, а домен сайта внизу.
То есть загружаем два watermarka и располагаем там где нужно?

**Comment by Sergeysem** [comment]
Или можно как то сначала установив один watermark при загрузке картинок, потом еще раз наложить другой обновив как то картинки?

**Comment by maxsite** [comment]
Что-то слишком сложно получается... Проще сразу сделать в фоторедакторе и загрузить на сервер.

**Comment by Sergeysem** [comment]
Ну я думал может не сложно продублировать функцию установки watermarka и иметь 2 настройки для них при загрузке, хочешь один устанавливаешь, хочешь 2 сразу в нужных местах.

**Comment by maxsite** [comment]
Всё не так просто. Ну и потребность, мягко говоря, странная. Тут не каждый-то одну ватермарку ставит, а вам две подавай. :)

**Comment by Sergeysem** [comment]
Воруют и обрезают watermark, так хоть шанс удваивается.

**Comment by maxsite** [comment]
Тогда лучше делать водяные знаки на все изображение в фотошопе, чтобы не мешали нормальному просмотру и оставляли копирайт.

**Comment by Sergeysem** [comment]
А средствами движка наложение водных знаком трудно реализовать?

**Comment by Sergeysem** [comment]
И другой момент (просто спрашиваю), если воруют картинку, то в принципе возможно ли реализовать, чтобы на нее при копировании накладывалась надпись, Например "Своровано с сайт site.ru" ?

**Comment by maxsite** [comment]
> А средствами движка наложение водяных знаков трудно реализовать?

Это уже реализовано. Есть фнукции и отлаженный механизм. Сложность в логике опций, которыми придется этим всем управлять.

> И другой момент (просто спрашиваю), если воруют картинку, то в принципе возможно ли реализовать такое, чтобы на нее при копировании накладывалась жирная надпись, например "Своровано с сайта site.ru" ?

Если кто-то загружает сайт со своего сервера, то на него никак нельзя повлиять. А так поищите в гугле по фразе «hotlink защита».

**Comment by Sergeysem** [comment]
> Это уже реализовано

А если сделать watermark как водяные знаки, если выберем установку по центру, то он ведь будет вставляться посередине изображения, а не на все изображение. Или будет на все изображение растягиваться?

**Comment by Sergeysem** [comment]
То есть пункт растянуть на все изображение нужен, так?

**Comment by Sergeysem** [comment]
Грузим фотки с watermark водяные знаки на сервер, потом копируем их, удаляем с сервера и опять грузим уже с нормальным watermark (например в нижнем правом углу).

В фотошопе это слишком долгое занятие.

**Comment by SivanovichP** [comment]
https://www.youtube.com/watch?time_continue=2&v=GOV66-Lx1nA  Для почитателей MaxSite CMS рассказываю как создать файл watermark.png - выкладывал видео Сергей Михалевич. Посмотри.

**Comment by SivanovichP** [comment]
И ставь водяной знак на фото в любом удобном месте до загрузки на сервер.

**Comment by Sergeysem** [comment]
То есть чтобы наложить такой ватемарк, нужно его создать с таким же разрешением (в данном случае 1100х806) и выбрать по центру?
![max-3000 com](https://user-images.githubusercontent.com/44212501/50458837-982b9380-097f-11e9-9e53-4412d5571473.jpg)

**Comment by Sergeysem** [comment]
То есть есть чтобы создать такой ватермарк, нужно его создать с таким же разрешением (в данном случае 1100х806) и выбрать по центру?
![max-3000 com](https://user-images.githubusercontent.com/44212501/50458915-34ee3100-0980-11e9-885b-4f3d8b1371b6.jpg)

**Comment by Sergeysem** [comment]
Я это сделал в программе Watermark Software, но хочется сделать так, чтобы при загрузке фото, все само накладывалось. Тут и так на написание статьи время уходит, а тут еще фото надо забрендить. 
Сторонние программы это тоже время.

**Comment by maxsite** [comment]
У нас используется CodeIgniter, где такой возможности нет. В вашем примере вообще больше похоже на наложение текста. Такие вещи достаточно сложны, тем более с переделкой кучи кода. Потребность — мизерная, чтобы я за неё вообще брался. Не думаю, что пару минут в сторонней программе больше, чем время на переделку системы.

**Comment by Sergeysem** [comment]
Спасибо.

**Comment by Sergeysem** [comment]
Сегодня загружал изображения и заметил , что после наложения watermark, изображения становятся больше по размеру почти в 2 раза. Размер watermark 10 кб.
Например было  81 кб, стало 143 кб, было 65 кб, стало 112 кб и так далее.

При загрузке изображений, галочка с "Для изображений изменить размер до 1100 px (по максимальной стороне)." снята, то есть я уже изменил размеры до нужных на компьютере.

Что сделать, чтобы размер не увеличивался?

**Comment by maxsite** [comment]
Значит таково сжатие jpg.

**Comment by Sergeysem** [comment]
Я перед загрузкой, на компьютере сохранил с 50% качеством эти картинки. Выходит опять скачивать их сервера и сохранять с качеством 50% и загружать в ту же папку на сервере по ftp? Больше никак?

**Comment by maxsite** [comment]
Попробуйте поставить качество 50 в админке. Может в этом случае размер будет меньше.

**Comment by Sergeysem** [comment]
Нет, не получается так. Если скачать картинку на компьютер и в графическом редакторе сохранить при 50% качества, то размер становится почти такой же, какой был.

**Comment by Sergeysem** [comment]
Тут хоть 1, хоть 50, хоть 100 ставь, размер полученного файла (загруженного) один и тот же во всех 3 случаях.

![555](https://user-images.githubusercontent.com/44212501/52087104-fd4b5800-25c1-11e9-9f5a-17523df5e9c0.jpg)

Делаю это на OpenServer, может в нем причина? Или все же не работает эта функция?

**Comment by maxsite** [comment]
Где именно вы загружаете файл?

**Comment by Sergeysem** [comment]
Вот так..

![888](https://user-images.githubusercontent.com/44212501/52109503-319d3380-2617-11e9-821c-7229165a9765.jpg)

**Comment by maxsite** [comment]
Понятно. В Загрузках эта опция не работает. Попробуйте через загрузку к записи.

**Comment by Sergeysem** [comment]
Максим, спасибо. Придется скачивать с сервера и сохранять опять с 50% качества на компьютере. Затем по ftp запружать в нужную папку.
