### ISSUE TITLE
Убрать ссылку на автора

### ISSUE THREAD

**Issue by eamibay** [maxsite/cms#291]
Здравствуйте.

Не могу убрать в постах активную ссылку на автора, много статей, много авторов, вес страницы уходит  вникуда.

$p->div_start('info info-top t-gray600 t90');
	$p->line('[date][author]');  - здесь выводит дату и ссылку на автора которую нужно убрать
        //$p->line('[date][view_count][comments_count][cat][tag]');
	//$p->line('[author]');
$p->div_end('info info-top');

Спасибо за помощь!

**Comment by eamibay** [comment]
Тогда не будет микроразметки "Автор"
$p->format('author', '   <span itemprop="author">', '</span>')

Есть другой способ?

**Comment by maxsite** [comment]
То есть вы хотите вывести автора без ссылки?

**Comment by maxsite** [comment]
`echo $p->val('users_nik')`

**Comment by eamibay** [comment]
`echo $p->val('users_nik');`  - Так тоже в валидаторе микроразметки яндекс и гугл пропадает данные Автор. 

`$p->format('author', ' <span itemprop="author">', '</span>')`
`$p->line('[date][author]');`  - Так микроразметка правильна, но есть ссылка на страницу автора. 3600 авторов, 2500 статей - вес страницы уходит на второстепенные страницы....

**Comment by eamibay** [comment]
page-comments-article-tmpl

Так же не могу убрать ссылку на автора комментария:

было `<span class="mso-comment-author">{{ $comments_url }}</span>`

пробовал:
`<span class="mso-comment-author">{{ $users_nik }}</span>`
`<span class="mso-comment-author">users_nik</span>`
`<span class="mso-comment-author">echo $p->val('users_nik');</span>`
`<span class="mso-comment-author">{{ $author }}</span>`
`<span class="mso-comment-author">{{ author }}</span>`

с каждой из 2500 статей вес уходит на старницу автора..

**Comment by maxsite** [comment]
Вы echo допишите нужную html-разметку. Я же показал, как вывести имя автора.

**Comment by Sergeysem** [comment]
То есть ссылки на профиля комментаторов в комментариях, это плохо?

**Comment by maxsite** [comment]
Нет такого понятия «вес страниц». С 2016 года PR обнулен и не участвует в ранжировании сайтов. Теперь используются другие показатели, вроде наличия мобильности и т.п.

**Comment by eamibay** [comment]
29.10.2018

В апреле 2016 года Google отключил показ тулбарного значения PageRank в браузерах и онлайн-инструментах. Оно рассчитывалось по шкале от 0 до 10 и давало общее представление о качестве страницы.
В августе того же года инженер поиска Google Гэри Илш заявил, что несмотря на отключение тулбарного PR, реальный PageRank по-прежнему учитывается в работе поисковой системы.
На днях сотрудник Google Джон Мюллер снова косвенно подтвердил эту информацию, сказав, что за эти годы все изменилось, и сомнительно, что это тот самый алгоритм, который когда-то был, и что он используется также, как в прежние времена.

**Comment by maxsite** [comment]
У меня соседка верит в единорогов. Клянется, что сама видела. Инфа 100%!

**Comment by Sergeysem** [comment]
> Зачем увеличивать вес страниц комментаторов? Если их более 2000? Лучше на продвигаемых страниц вес увеличивать.

На страницах комментаторов тоже есть ссылки на страницы, где они комментировали. Тем самым страницы комментаторов тоже увеличивают вес страниц.
