### ISSUE TITLE
Плагин addzakl

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#292]
Доброго времени.
Можно ли как то прикрутить к этому плагину количество переходов по клику кнопки в социалки?
Что то типа этого.

![44](https://user-images.githubusercontent.com/44212501/50536837-236c7b00-0b72-11e9-9a94-83b0153a7521.jpg)

Чтобы примерно оценивать количество возможных репостов.

**Comment by maxsite** [comment]
В GA можно трекер прикрутить. Будет отслеживать нажатия.

**Comment by Sergeysem** [comment]
В GA? Что это такое?

**Comment by Sergeysem** [comment]
Ну количество переходов буду видеть только я, хотелось бы чтобы видели все. Некое такое психологическое давление на сомневающихся добавить))
А через плагин down_counter можно как то сделать?

**Comment by maxsite** [comment]
Этот плагин, просто набор ссылок соцсетей. Если соцсеть имеет соответствующий функционал, то настраивайте его, получайте html-код для вставки на свой сайт.

**Comment by Sergeysem** [comment]
Обернуть получится в `[dc show][/dc]` эти ссылки?

**Comment by maxsite** [comment]
Понятия не имею.
