### ISSUE TITLE
Сразу после установки php 7.1

### ISSUE THREAD

**Issue by rumata-estor** [maxsite/cms#293]
В админке на /admin/page
A PHP Error was encountered
Severity: Warning
Message: A non-numeric value encountered
Filename: common/common.php
Line Number: 1967
A PHP Error was encountered
Severity: Warning
Message: A non-numeric value encountered
Filename: common/common.php
Line Number: 1967
A PHP Error was encountered
Severity: Warning
Message: require_once(...l/application/maxsite/plugins/plugins\pagination\index.php): failed to open stream: No such file or directory
Filename: admin/common.php
Line Number: 210

**Comment by maxsite** [comment]
Кэш удалите. Сервер перегрузите.

**Comment by rumata-estor** [comment]
Ну какой кэш, только установлено, с нуля... И сервер не могу перегрузить, это вирт. хостинг :-(

**Comment by maxsite** [comment]
Что ж тогда пути от windows...

**Comment by rumata-estor** [comment]
Да, странно расставлены слеши /application/maxsite/plugins/plugins\pagination\index.php. 
Первые два варинига фиксятся явным приведением типов в соответствующей строке: $time = $time - (int)getinfo('time_zone') * 60 * 60;

**Comment by maxsite** [comment]
Проверьте установку на локалхосте. Если всё ок, то что-то с сервером.

**Comment by rumata-estor** [comment]
У меня и на локалхосте линукс, которому слеши не нравятся, и php 7.1 стоят :-) Ладно, оставим это здесь, вдруг у кого-то будут такие же проблемы.

**Comment by maxsite** [comment]
Да, пока не закрывайте тикет. Проверю.

**Comment by maxsite** [comment]
Со слэшами точно мой «косяк». Даже не знаю, как они проскочили. Приведение типа тоже внес правку, хотя это противоречит докам PHP. Возможно какая-то особенность PHP или его настройки. В общем это не проблема добавить ему float. В dev-версии внес правки, попробуйте обновить файлы.

**Comment by rumata-estor** [comment]
Фича именно версии 7.1 [документация](http://php.net/manual/ru/migration71.other-changes.php#migration71.other-changes.apprise-on-arithmetic-with-invalid-strings)

**Comment by maxsite** [comment]
Похоже они переписали правила преобразования типов. Если опции нет, то там на выходе false получается. После преобразования типов это всегда был 0, а в 7.1 генерируется ошибка. Внесу ещё одну правку на получение опций таймзоны, чтобы предупредить подобную ситуацию.
