### ISSUE TITLE
Скрытый счетчик

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#294]
Доброго времени, С Новым годом.
Хочу установить счетчик LiveInternet, но не хочу чтобы его видели и в тоже время, хочу сам видеть показания на счетчике.
Как задать условие ушкe, чтобы она выполнялась только для админа?

`<?php if (function_exists('ushka')) echo ushka('liveinternet'); ?>`

Чтобы считало, на сайте будет установлен еще один код с картинкой 1х1 пиксель (невидимый). А чтобы видеть цифры на счетчике, будет установлен другой код, через эту ушку (с условием).

Как задать условие ушке?

**Comment by Sergeysem** [comment]
Или (если это возможно) как задать условие отображения только админу, текстового виджета или виджета ушки?

**Comment by Sergeysem** [comment]
Так надо? Или есть более правильный способ?

`<?php if (is_login()) if (function_exists('ushka')) echo ushka('liveinternet'); ?>`

**Comment by maxsite** [comment]
Если плагин ушек всегд включен, то можно проще:

`<?php if (is_login()) echo ushka('liveinternet'); ?>`

Или так:

`<?php if (is_login() and function_exists('ushka')) echo ushka('liveinternet'); ?>`

**Comment by Sergeysem** [comment]
Спасибо, а то что я выше написал, это не правильно? (хотя работает).

**Comment by maxsite** [comment]
Это тоже самое, только более корректный синтаксис.

**Comment by Sergeysem** [comment]
Спасибо.
