### ISSUE TITLE
Ошибка 500 при авторизации

### ISSUE THREAD

**Issue by grin-baks** [maxsite/cms#295]
Замечено что при повторной авторизации (из другого окна например) появляется ошибка 500. Так же порой она возникает при входе по прямой ссылке в админку. Кто то сталкивался ? Как исправить?  Версия 101.

**Comment by maxsite** [comment]
Скорее всего на сервере слишком малый размер для http-заголовка (куки). Или очистите куки в браузере.

**Comment by grin-baks** [comment]
Нашел решение здесь https://forum.vestacp.com/viewtopic.php?t=3889
добавил в файле /etc/nginx/nginx.conf в конец раздела    # Proxy settings
proxy_buffers 16 128k;
proxy_busy_buffers_size 128k;
proxy_buffer_size 128k;
