### ISSUE TITLE
Неактивное лого

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#296]
не то что проблема, но есть маленькое неудобство, которое состоит в том, что лого остаётся логотипом, если я просматриваю архив записей постранично. Т.е., если я нахожусь по адресу _сайт/home/next/7_ , то лого не делается ссылкой, а хотелось бы. Сейчас оно становится ссылкой, только если просматриваю отдельную запись.

**Comment by Sergeysem** [comment]
В файле application\maxsite\templates\ваш_шаблон\components\top1\top1.php где то  в районе 36 строки добавить это..
`if (!is_type('')) $logo = '<a href="' . getinfo('siteurl') . '">' . $logo . '</a>';`

Если там стоит похожая, то заменить ее на эту. Перед изменениями создать копию файла.

**Comment by maxsite** [comment]
Ну конечно, `is_type('')` никуда не годится. :)
 
Условие может быть такким:

`if (is_type('home') and mso_current_paged() > 0) { ... }`

То есть нужно играть страницей пагинацией и type-home.

**Comment by maxsite** [comment]
Как вы думаете, что возвращает строчка `(!is_type(''))` ?

**Comment by Sergeysem** [comment]
Если тип страницы не пусто, то выводим ссылку в лого.

**Comment by maxsite** [comment]
Нет такого типа данных. Это условие всегда возвращает одно и тоже значение.

**Comment by Sergeysem** [comment]
Максим, ну я не знаю, работает ведь.

**Comment by Furnicarium** [comment]
пишем `if (is_type('home') or mso_current_paged() > 0)`  в top1 на 37 строчке и всё работает!!! спасибо, закрываю тикет
