### ISSUE TITLE
Png теряет прозрачность при наложении водяного знака

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#297]
где поковыряться, чтобы при загрузке png файлов сохранялась прозрачность? 
Уточню, прозрачность сохраняется, если не пользоваться опцией наложения водяного знака. Но если пользоваться, то теряется прозрачность и у ватермарки, и у всего изображения.. 
НЕ критичная проблема.

**Comment by maxsite** [comment]
Для png прозрачность сохраняется только при resize. В остальных случаях — нет.
