### ISSUE TITLE
Код миниатюры не срабатывает

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#298]
создаю пост, добавляю к нему картинку, рядом с картинкой жму [img] (вставить в текст код изображения) - всё работает.
Но когда нажимаю [image] (вставить в текст код миниатюры), то в текст вставляется код вида 
`[image=миниатюра]большая картинка[/image]`
и **так и остаётся в виде текста**. редактор стандартный, плагин BB-code включен. Что не так работает?

**Comment by maxsite** [comment]
Плагин лайтбокса включите.

**Comment by Furnicarium** [comment]
> Плагин лайтбокса включите.
заработало, благодарю. я до модальных окон ещё не дошёл, так как не решил более важных задач. 
ещё маленький вопрос,  image_for_page - это актуальное **метаполе** для превьюшек или оно другое? нужно для работы плагина и виджета, но не подхватывает такое значение, делает пустое поле, prev тоже не помогает.

**Comment by maxsite** [comment]
Это поле для изображения записи. Превьюшки строятся на его основе.
