### ISSUE TITLE
Совместимость в будущей версии MaxSite CMS

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#30]
Потохонечку пришел к выводу, что новая версия должна уже быть с «подчищенными хвостами». Если оставить как есть, но костыли ради совместимости со старыми версиями и дальше будут тормозить развитие системы. Через какое-то время всё-равно придется переделывать.

Итак, что может поменяться.

1. Шаблон должен быть полностью сам в себе. То есть никаких связей с default-каталогом быть не должно.

2. Связи с shared-каталогом только на уровне каталогов main, meta, options, stock и type. Там сложный php-код. 

3. В shared-каталоге functions, css-less, js удаляются (переносятся в каталог шаблона). В blanks остаются только каркасы для новых плагинов.

4. В common/jquery остается только те jQuery, которые используются системой. Всё остальное — удаляется. В шаблоне можно будет загрузить свою верси jQuery, вместо системной.

5. PHP-компилятор less полностью удаляется из ядра системы. Он безнадежно устарел, нет смысла его тянуть дальше. Однако, подумать и сделать его в виде плагина (less_compiling) — кому нужно, пусть используют и дальше.

6. Внести изменения в парсере текста. Идея в том, чтобы при редактировании страницы была возможность указать обработчик. Стандартный — как сейчас, с авторасстановкой абзацей. Без обработки — отдавать как есть (годится для html-кода), и какой-то сторонний, например simple из LPF. Такая схема позволит снять проблемы при использовании сторонних визуальных редакторов — для записи просто указывается нужный парсер. Открытый вопрос — должен ли парсер быть один для записи (выбор select) или можно указать несколько (checkbox). Если несколько, то как определять приоритет срабатывания? В общем это крупная переделка.

Скорее всегго такие изменения приведут к частичной потере совместимости со старыми шаблонами. Поэтому версию придется дольше потестировать, а также продумать инструкцию как сделать переход для старых шаблонов. По-идее там простое копирование файлов.

**Comment by vimruler** [comment]
С необходимостью подчистить хвосты - полностью согласен. Тянуть смысла нет. 

По 2-му пункту есть вопрос - а нет ли возможности перенести логику на уровень плагинов? Тогда гибкость ещё больше будет, за счёт возможности подменить любой плагин своим.

По 5 - да, надо бы оставить less-компилятор хотя бы в виде плагина.

По 6 - настройки парсера будет в общих настройках сайта? По идее могут быть нужны несколько обработчиков. А вот с заданием приоритета срабатывания да, сложно. Тут варианты пока только такие в голову приходят: текстовое поле (но тогда нужно где-то перечислять какие варианты доступны) или множественный select (но тогда нужно как-то прикручивать jquery для эффекта перетаскивания и как-то обрабатывать результат).

**Comment by maxsite** [comment]
> По 2-му пункту есть вопрос - а нет ли возможности перенести логику на уровень плагинов? Тогда гибкость ещё больше будет, за счёт возможности подменить любой плагин своим.

Плагины тут не при чем. Подключения из shared происходят на уровне шаблонов. Например type-файлы. Если не устраивает какой-то вариант, то делаем свой в шаблоне. И т.п.

> По 6 - настройки парсера будет в общих настройках сайта? 

Нет, только на уровне редактирования страницы. Это должно быть мета-поле. Если у него есть какое-то значение, то выполняется обработка контента этим парсером. Если нет, то срабатывает текущий стандартный вариант. Ну и будет вариант без обработки. Теоретически он должен полностью быть совместим с любым визуальным редактором — именно он формирует html-код.

**Comment by leonovmax** [comment]
1,2,3 - очень хорошее решение
4 - Вариант загрузки jQuery , при выборе из внешнего источника может добавить возможность  выбора версии jQuery ?
......

>Стандартно в MaxSite CMS используются типы «blog» и  «static». 

Будет ли возможность добавлять/удалять!! новые типы, т.к. сейчас добавить можно ,а вот удалить нельзя.

>Для того, чтобы задействовать новые типы страниц, скорее всего потребуется отдельное программирование шаблона. 

Может  брать за основу уже существующие шаблоны(статик например), дабы не программировать новый ?

.....
Будет ли возможность группового удаления записей *?

**Comment by maxsite** [comment]
>  4 - Вариант загрузки jQuery , при выборе из внешнего источника может добавить возможность выбора версии jQuery ?

Тут нужно подумать. 

> Будет ли возможность добавлять/удалять!! новые типы, т.к. сейчас добавить можно ,а вот удалить нельзя.

Это задача для админки. Пока в планах не стоит. 

> Может брать за основу уже существующие шаблоны(статик например), дабы не программировать новый ?

Я не вижу задач, где требуется больше чем blog и static. В любом случае это вопрос программирования шаблона. 

>  Будет ли возможность группового удаления записей *? 

Опять же, это уровень админки. Групповое удаление довольно затратная штука для сервера.

**Comment by cuprum** [comment]
>Вариант загрузки jQuery , при выборе из внешнего источника может добавить возможность выбора версии jQuery ?

На сайте jquery сейчас две ветки - с поддержкой старых IE и без нее. Если будет возможность выбора, то думаю этих 2-х вариантов хватит.

**Comment by leonovmax** [comment]
По поводу относительных ссылок, а точнее создание якорных ссылок в main menu: сейчас, к примеру,  если указать " #layer | текст" на выходе получаем <a href="http://site.ru/#layer"><span>текст</span></a>, хотелось бы <a href="#layer"><span>текст</span></a>
Понимаю, что это индивидуальное требование, пришлось под себя править код движка, чего делать  категорически не хотелось, там и так все продумано, но может передавать ещё один параметр, который будет указывать на вид создаваемой ссылки(отн/абс) :
ссылка | название | подсказка | class | class_для_span | относительная или абсолютная

.....
Мультизагрузка файлов будет или пока что нет в планах?

**Comment by maxsite** [comment]
С jQuery мне кажется нужно предусмотреть какой-то вариант, вообще отключающий её загрузку. Тогда через custom/head.php что угодно можно подключить. Как вариант через mso_set_val() устанавливать произвольный url-загрузки.

> По поводу относительных ссылок, а точнее создание якорных ссылок в main menu: сейчас, к примеру, если указать " #layer | текст" на выходе получаем 

Спасибо, что напомнили. У меня в LPF это уже реализовано. Для ссылок с # и ?. Перенесу код.
