### ISSUE TITLE
admin_ip

### ISSUE THREAD

**Issue by SOTVM** [maxsite/cms#301]
не плохо бы иметь возможность указать диапазон IP по маске 
192.168.0.1 - 192.168.0.254 или так 192.168.0.0 / 24
а так же добавить опцию/поле для ввода URL перенаправления или вставки html кода

у меня  ума хватило только чтобы дописать/поправить в admin_ip/index.php
75 строка  if (!$ok) die('Access denied'); // рубим
```
if (!$ok) 
echo '<img src="fuck.jpg" style="position: absolute;left: 50%;top: 50%;margin-left: -180px;margin-top: -240px;width: 360px;height: 480px;">'; // fuck по центру
//require '403.html' ; //или подключаем  страницу
die(); // рубим
```

**Comment by maxsite** [comment]
Нужно думать. Довльно сложный парсинг текста получается.

**Comment by SOTVM** [comment]
> Нужно думать. Довльно сложный парсинг текста получается.
IP динамический 
я имел ввиду простейшее а-ля
#!/bin/bash
ip="192.168.33.44"
mask="192.168."
test=$(echo $ip | grep -o '^192.168.')
 if [ "$test"  != "" ];
 then echo  OK $ip;
 exit
 fi;
 echo BAD

**Comment by maxsite** [comment]
Баш тут не поможет. Скорее всего нужно регулярку делать.

**Comment by SOTVM** [comment]
> Баш тут не поможет

все реализуемо на php
я просто привёл пример

**Comment by maxsite** [comment]
Делайте на php, показывайте. У меня пока нет времени этим заниматься.

**Comment by SOTVM** [comment]
так если бы у меня хватало мозгов :)
я идею закинул
тот ,кто более менее понимает в  php,выдаст решение (а я не кодер)
на этом и живёт опенсурс

**Comment by SOTVM** [comment]
что то не получается c if ( preg_match("/^$ip/","$curr_ip") == 1 )
	```
if ($options['ip'])
	{
		// указаны IP

		$ips = explode("\n", $options['ip']);
		$curr_ip = $MSO->data['session']['ip_address'];

		$ok = false; // признак, что доступ разрешен
		foreach ($ips as $ip)
		{
			if ( trim($ip) == $curr_ip)
			//if ( preg_match("/^$ip/","$curr_ip") == 1 )
			{
				$ok = true;
				break;
			}
		}
```

**Comment by SOTVM** [comment]
вот так работает ,забыл фигурные скобки после if
```

	if ($options['ip'])
	{
		// указаны IP

		$ips = explode("\n", $options['ip']);
		$curr_ip = $MSO->data['session']['ip_address'];

		$ok = false; // признак, что доступ разрешен
		foreach ($ips as $ip)
		{
			//if ( trim($ip) == $curr_ip)
			if ( preg_match("/^$ip/","$curr_ip") === 1 )
			{
				$ok = true;
				break;
			}
		}

		//if (!$ok) die('Access denied'); // рубим
		if (!$ok) {require '403.html';//подключааем
		die();} // рубим
	}

```
