### ISSUE TITLE
Доп. поля и другие нубские вопросы

### ISSUE THREAD

**Issue by seoshnek** [maxsite/cms#302]
Здравствуйте, не пинайте сильно только разбираюсь.

1. Это единственный форум по cms? Вижу разные ссылки на forum.какой-то-из-доменов.com - там ничего нет, или я плохо искал?

2. Мне нужно сделать произвольные поля в записях и возможность их вывода в поиске по сайту - есть такая функция? Вот я нагуглил плагин: http://max-3000.com/page/opcii-v-maxsite-cms  - он ведет сюда - >http://maxsite.org/ras30 (404). 

3. Карта сайта планируется огромная, вообще сайт в планах огромный на миллионы страниц - я вижу у вас все в порядке с оптимизацией запросов - поэтому понадобится xml-карта сайта с разбивкой на 50к записей и сжатием в gzip - так работает плагин карты сайта?

Непонятно в общем, где актуальная информация находится? 3 (или больше?) домена вижу, везде все раскидано, но форума не нашел, с плагинами тоже не могу найти, где найти этот ras30?

Спасибо

**Comment by maxsite** [comment]
> Это единственный форум по cms? Вижу разные ссылки на forum.какой-то-из-доменов.com - там ничего нет, или я плохо искал?

Да, все обсуждения здесь.

> Мне нужно сделать произвольные поля в записях и возможность их вывода в поиске по сайту - есть такая функция? Вот я нагуглил плагин: http://max-3000.com/page/opcii-v-maxsite-cms - он ведет сюда - >http://maxsite.org/ras30 (404).

Это старая WP-рассылка. Там ничего полезного, поэтому давно удалена. :) 

Для своих опций делаете файл в шаблоне custom/my_meta.ini где их и задаёте. Примеры можно посмотреть в shared-каталоге.

> Карта сайта планируется огромная, вообще сайт в планах огромный на миллионы страниц - я вижу у вас все в порядке с оптимизацией запросов - поэтому понадобится xml-карта сайта с разбивкой на 50к записей и сжатием в gzip - так работает плагин карты сайта?

В последней dev-версии Илья как раз сделал такую возможность.

**Comment by seoshnek** [comment]
Здравствуйте. Положил тестовую опцию с выводом текста в 
`maxsite\templates\default\options\my_meta.ini
(этот путь я взял исходя из readme.txt в нем)

и сюда еще (как вы написали выше):
`maxsite\templates\default\custom\my_meta.ini

Непонятно точно, туда или сюда класть?

Затем вывожу в 

`maxsite\templates\default\main\blocks\content.php

код

```
{ 
	global $CONTENT_OUT; 
	echo $CONTENT_OUT; 
	
	echo mso_get_option('my_text', 'templates', '');
}

```
Не выводится :)  

вот [тут ](http://max-3000.com/page/maxsite-cms-dlja-chajnikov-opcii-nastrojki
) написано:

> Сохраняем файл и в админке в Настройке шаблона видим нашу опцию.

Не вижу её.

Я напутал с путями?

**Comment by maxsite** [comment]
Вы путаете мета-поля записи и опции. Если вы хотите как в своём примере, то используйте произвольные ini-файлы в каталоге options шаблона. Примеры см. application\maxsite\shared\options\default\

**Comment by seoshnek** [comment]
Нет, мне нужны именно **мета-поля для каждой записи.** То есть мне какой вариант нужно делать? 

Я видимо изначально нечетко задал вопрос в ветке, извините.

> Примеры см. application\maxsite\shared\options\default\

Да, я понимаю синтаксис, это все ясно, там они по всему сайту, эти опции. Не ясно, куда класть :)

**Comment by maxsite** [comment]
Делайте как я написал.
