### ISSUE TITLE
Проблема с версией 101 ошибка в разделах в админ-панели

### ISSUE THREAD

**Issue by Veronikai** [maxsite/cms#303]
Здравствуйте, Максим!
Полностью переустановила сайт на 101 версию, предварительно изменив версию php на 7.2. 
Но всё равно в админ-панели в разделах:

- Все записи
- Комментарии
- Комментаторы 
 выдаёт ошибку: 

A PHP Error was encountered
Severity: Warning

Message: require_once(/home/host1438682/sociopraktikum.ru/htdocs/www/application/maxsite/plugins/plugins/pagination/index.php): failed to open stream: No such file or directory

Filename: admin/common.php

Line Number: 210

Fatal error: require_once(): Failed opening required '/home/host1438682/sociopraktikum.ru/htdocs/www/application/maxsite/plugins/plugins/pagination/index.php' (include_path='.:/usr/local/php/php-7.2/lib/php') in /home/host1438682/sociopraktikum.ru/htdocs/www/application/maxsite/admin/common.php on line 210

Реально ли это как-то исправить? 

Благодарю Вас за поддержку!

**Comment by maxsite** [comment]
Здравствуйте, Вероника! Просто обновитесь до последней dev-версии. :)

**Comment by Veronikai** [comment]
Хорошо, попробую. Сердечное Вам спасибо за помощь. :)

**Comment by lisok77** [comment]
На ютьюбе оставлял Вам вопрос, после обновления с 099 версии на 100.... все съежает в шаблоне, шаблон дефолтный, меню идет сверху вниз на красной широчезной полосе, превью или картинки вообще не отображаються. Как это исправить? Есть какой нибудь мануал по адаптации хотя бы дефолтного шаблона между версиями 09... и 10.... Или как перенести все статьи и катигории на чистый движок?

**Comment by lisok77** [comment]
Да и пресоедтняюсь к парвому вопросу, я так и не смог ее решить ни какими обновлениями. У меня стоит ПХП 5.6 7.2 не пробовал, под версии 10...  ПХП 7.2 обязательно?

**Comment by maxsite** [comment]
Попробуйте еще раз обновиться до последней **dev**-версии. Никаких изменений с вашей стороны больше не должно быть.

**Comment by maxsite** [comment]
У меня в FireFox нормально. Цвета браузера какие-то «левые» на вашем скриншоте. Нажмите несколько раз F5, может браузер обновит стили. Верхнее меню не должно быть многоуровневым.

**Comment by lisok77** [comment]
Да действительно все встало в норму, а я сутки уже борюсь с этим и не додумался до того, что надо кеш и куки попробовать очистить. Спасибо Вам!
