### ISSUE TITLE
Английский язык в maxsite cms

### ISSUE THREAD

**Issue by raptorcc** [maxsite/cms#304]
Здравствуйте, как полностью подключить английский язык?
В файле mso_config.php прописал $MSO->language = 'en'; // english 
на сайте перевод не полный, чередуется с русским языком как исправить?
Версия maxsite 101

**Comment by maxsite** [comment]
Язык админки можно в настройках выбрать. А внешнюю часть сайта обычно настраивают через опции, виджеты и т.п. Перевод требуется для фраз, которые генерирует система. Если есь желание, можете дополнить перевод.

**Comment by raptorcc** [comment]
дата публикации на русском, где нужно редактировать?

**Comment by maxsite** [comment]
В файле перевода.

**Comment by raptorcc** [comment]
в файле en.php строчка 187 переименовал $lang['г.']='y.'; 
год все равно отображается на русском

**Comment by maxsite** [comment]
Смотря откуда выводится текст. Может в файле без языковой функции выводится.

**Comment by raptorcc** [comment]
![screenshot 2019-01-23 002](https://user-images.githubusercontent.com/46967333/51626977-b5309380-1f38-11e9-847c-c1d17421d8cf.png)

**Comment by maxsite** [comment]
Ну там и правьте.

**Comment by raptorcc** [comment]
где править?

**Comment by maxsite** [comment]
В файле, где выводится дата.

**Comment by raptorcc** [comment]
везде перелопатил, не нашел где именно редактируется

**Comment by maxsite** [comment]
Ну я тоже не гадалка.

**Comment by raptorcc** [comment]
Проблема актуальна.

**Comment by maxsite** [comment]
Вы уже получили мой ответ.
