### ISSUE TITLE
Warning-и в админке нового сайта на странице /admin/page

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#305]
Вновь установленная система выдает в админке на странице _/admin/page_ такие сообщения
> Severity: Warning
> Message: require_once(/var/www/u0633662/data/www/sps46.ru/application/maxsite/plugins/plugins\pagination\index.php): failed to open stream: No such file or directory
> Filename: admin/common.php
> Line Number: 210
`210 require_once(getinfo('plugins_dir') . 'plugins\pagination\index.php');`
Пока не включишь плагин пагинации.

> A PHP Error was encountered
> Severity: Warning
> Message: A non-numeric value encountered
> Filename: common/common.php
> Line Number: 1967
`$time = $time + getinfo('time_zone') * 60 * 60;`

Мелочь, но неприятно.

**Comment by maxsite** [comment]
1. Уже исправлено в dev-версии.
2. Наверное таймзона неверно на сервере выставлена.

**Comment by maxsite** [comment]
Хотя нет, таймзона верно. Скорее всего у вас старая версия MaxSite CMS и новая PHP. Нужно обновиться.

**Comment by Filsadovnik** [comment]
2. Ошибку показывает на страницах админки пока на странице /admin/options не нажмешь "Сохранить".

**Comment by maxsite** [comment]
Читайте внимательно мои ответы.
