### ISSUE TITLE
Ошибка сессии! Обновите страницу

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#306]
При отправке комментария выдает такую ошибку.

![2019-01-24_18-16-04](https://user-images.githubusercontent.com/44212501/51684047-9d264600-2004-11e9-981c-b9b6d1e9d0c6.png)

Скрин прислал комментатор. Я сам не смог воспроизвести эту ошибку.

Вопрос, это комментатор держит страницу открытой минут 30 и потом пытается что то написать или как избавиться от этого, если он пишет сразу и эта ошибка вылетает?

**Comment by maxsite** [comment]
Сессия устанавливается на 7200 секунд. Так что всё нормально.

**Comment by Sergeysem** [comment]
А если комментатор отправляет сразу комментарий и появляется эта ошибка?

**Comment by maxsite** [comment]
Ну сессия — это кука. Если она недествительна, то и будет это сообщение. Может ip поменялся, может браузер и т.п.

**Comment by Sergeysem** [comment]
Спасибо.

**Comment by Sergeysem** [comment]
Максим. А где можно увеличить длительность сессии ну скажем  с 7200 сек до 1 суток? Можно так сделать? Надоело логинится постоянно на сайте или длительность сессии и время логина разные вещи?

**Comment by maxsite** [comment]
Это сессия обычного посетителя. Для комюзера время 1 год. Для юзера продлевается при каждой активности.

**Comment by Sergeysem** [comment]
> Для юзера продлевается при каждой активности
А какое время для юзера? 

Вчера на одном сайте авторизовался комюзером, сегодня захожу на сайт, авторизация не слетела.
На другой сайт авторизовался админом, сегодня захожу на сайт, авторизация слетела, пришлось входить по новой.

Не понимаю, как продлить время логина админа?

**Comment by maxsite** [comment]
Это общее время сессии. Вы же нужные строчки привели... Но если кука слетела, то будет новая сессия.

**Comment by Sergeysem** [comment]
То есть во всех трех строках нужно изменить на большее число и логин админа не будет слетать?

IP адрес статический. Почему у комюзера за ночь не слетает, а у юзера слетает тогда при значении 7200 сек?

**Comment by maxsite** [comment]
Ну конечно. Если не было активности админа, то через 2 часа кука станет недействительной. Если активность была, то происходит автопродление сессии. Посмотрите в браузере срок действия куки, станет понятно. Кука сбрасывается если сменился браузер, адрес или ip. Если произошел сброс, то что-то произошло с этим. Чудес не бывает.

**Comment by Sergeysem** [comment]
Так поменять значения нужно во всех 3 строках или только в первой достаточно?

**Comment by maxsite** [comment]
Не помню. Наверное sess_expiration.

**Comment by Sergeysem** [comment]
Спасибо.
