### ISSUE TITLE
Якоря bbcode

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#309]
Доброго времени.
Не могу понять, как в редакторе записи воспроизвести с помощью bbcode этот фрагмент кода:

```
<ul>
<li><a href="#1">Ссылка на текст</a>
</ul>
<h2 id="1">Текст</h2>
```
Делаю так, но как проставить якоря не понимаю.
```
[ul]
[*]Ссылка на текст
[/ul]

[h2]Текст[/h2]
```
В самом редакторе как я понимаю, нет такой возможности или я не вижу? Хотелось бы все же через bbcode делать.

**Comment by maxsite** [comment]
Кнопка есть. Можно Ctrl+L по выделенному тексту.

`[url=#1]ссылка[/url] `

**Comment by Sergeysem** [comment]
Понял, а id=1 я так понимаю вручную прописывать?

[ul]
[*][url=#1]Ссылка на текст[/url]
[/ul]

[h2 id=1]Текст[/h2]

**Comment by Sergeysem** [comment]
Делаю без кавычек, смотрю в html код страницы, там с кавычками..
```
[h3 id=1]Текст[/h3]
<h3 id="1">Текст</h3>
```
Так надо или не надо кавычки, если учесть что они на автомате сами прописываются в html коде?

**Comment by maxsite** [comment]
```
[h3 id="1"]Текст[/h3]
[h3 id=1]Текст[/h3]

<h3 id="1">Текст</h3
<h3 id=1>Текст</h3>
```

**Comment by Sergeysem** [comment]
А в каком браузере так? Vivaldi и Chrome с кавычками в html коде в обоих случаях.

**Comment by Sergeysem** [comment]
А тут тоже с кавычками надо? 
```
[url=#1]Ссылка на текст[/url]
[url="#1"]Ссылка на текст[/url]
```

**Comment by maxsite** [comment]
Значит неверно смотрите. Ctrl+U.

**Comment by Sergeysem** [comment]
Смотрел через "инспектировать".

Спасибо.
