### ISSUE TITLE
maxsite 101 openssl_decrypt()

### ISSUE THREAD

**Issue by giovanni86g** [maxsite/cms#310]
Помоги пожалуйста Махим. Hosting HTTP Server Header: nginx/1.14.1 PHP 7.1
Выдаёт  такие ошибки когда пытаюсь входит на сайте под свои логин и пароль. Что делать? Спасибо.

A PHP Error was encountered
Severity: Warning

Message: openssl_decrypt(): IV passed is 26 bytes long which is longer than the 16 expected by selected cipher, truncating

Filename: common/common.php

Line Number: 4734

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at ......./public_html/system/core/Exceptions.php:186)

Filename: libraries/Session.php

Line Number: 432

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at ......./public_html/system/core/Exceptions.php:186)

Filename: common/common.php

Line Number: 1546

**Comment by maxsite** [comment]
Сложно сказать. Может такие настройки сервера, может что-то неверно кодируется. Коди кодировщика «классический», по идее должен работать на любом сервере.
