### ISSUE TITLE
Ревизия записи

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#311]
Доброго времени.
Произошло такое непонятно явление. Писал статью, нажимал "Сохранить в фоне", смотрел в новом окне изменения записи. Но что то произошло, в редакторе записи, после обновления этой страницы (страницы редактора), все изменения удалились. То есть код статьи сейчас выглядит как будто я ни чего не делал. В новой вкладке открыта статья с изменениями, ее, прямо из браузера скопировал (а если бы ее закрыл?).

Собственно вопрос, почему сохраняя в фоне, после обновления страницы все слетело и есть ли ревизии статей в движке?

Как можно вернуть код, статья большая, целый день писал (то что скопировал с браузера, не удобно для восстановления, это же не код)?

Статью писал на OpenServer.

**Comment by maxsite** [comment]
Ревизий, естественно, нет. Есть Быстрое сохранение Ctrl+S — текст записывается в файл, можно его оттуда взять.

**Comment by Sergeysem** [comment]
А причина?

**Comment by Sergeysem** [comment]
Если возможность, браузер Chrome, открыть страницу до обновления?

**Comment by maxsite** [comment]
Вы думаете что описания «что то произошло» достаточно??? Я не гадалка, мне уже порядком надоело об этом все сообщать. Если вы не в состоянии нормально описать проблему, то не ждите помощи. Тикет закрываю, как бесмысленный.

**Comment by Sergeysem** [comment]
Что то произошло, это подробно написано в первом сообщении. А ИМЕННО, ОБНОВИЛ СТРАНИЦУ БРАУЗЕРА СО СТРАНИЦЕЙ РЕДАКТОРА ЗАПИСИ И КОД ЗАПИСИ СЛЕТЕЛ!!!!!!!!!!!!!!!!!

Прочитайте еще раз первое сообщение, если не хотите отвечать, не надо писать, что к вам как гадалке тут ходят, читайте, простыню же написал, куда еще подробней?????????????

**Comment by Sergeysem** [comment]
Спасибо что добавили ревизии к статьям. Было бы не плохо, если бы ревизия сохранялась и при нажатии сохранить в фоне или просто сохранить.

**Comment by maxsite** [comment]
Нужна какая-то опция, потому что не все нужны ревизии, а файлов может оказаться довольно много. Поэтому пока и сделал как явная команда.

**Comment by Sergeysem** [comment]
Спасибо Максим.
