### ISSUE TITLE
403 в настройках шаблона

### ISSUE THREAD

**Issue by uncleeugene** [maxsite/cms#312]
День добрый! Столкнулся с проблемой после обновления движка, ищу совета или подсказки. Вчера обновился до 101 версии, с 09-какой-то. Всё работает нормально, кроме одного: в админке. кнопка "Сохранить" в настройках шаблона (любого) возвращает 403. Остальное всё работает. На всякий случай сделал чистую установку - то же самое.

**Comment by maxsite** [comment]
На dev-версии тоже самое? Скриншот можете показать?

**Comment by uncleeugene** [comment]
Скриншот не делал, разобрался. Виноват был на стороне провайдера modsecurity.d. Он блокировал передачу URI методом POST, или что-то в этом роде. Ложное срабатывание. Вылечилось просьбой отключить modsecurity.

Вот, для информации, кусочек лога:

[client 188.246.247.223] ModSecurity: [file "/etc/httpd/conf/modsecurity.d/rules/tortix/modsec/50_plesk_basic_asl_rules.conf"] [line "258"] [id "33350147"] [rev "143"] [msg "Protected by Atomicorp.com Basic Non-Realtime WAF Rules: Potentially Untrusted Web Content Detected"] [data ""] [severity "CRITICAL"] Access denied with code 403 (phase 2). Match of "rx ((?:submit(?:\\\\+| )?(request)?(?:\\\\+| )?>+|<<(?:\\\\+| )remove|(?:sign ?in|log ?(?:in|out)|next|modifier|envoyer|add|continue|weiter|account|results|select)?(?:\\\\+| )?>+)$|^< ?\\\\??(?: |\\\\+)?xml|^<samlp|^>> ?$)" against "ARGS:f_options[lightslider_m_s_o_default]" required. [hostname "nasa.gov"] [uri "/admin/template_options"] [unique_id "XFm7Jk4oUFlmx43VwtyVgwAAAAI"], referer: http://www.nasa.gov/admin/template_options

До того как разобрался, пробовал и dev-версию, и откатывал на 0.97. Неизменно тот же результат. Теперь непонятно, как раньше работало :)

**Comment by maxsite** [comment]
Ну главное что NASA теперь MaxSite CMS использует. :)

**Comment by uncleeugene** [comment]
Первое, что в голову пришло :)
