### ISSUE TITLE
постоянно висит фантомная частота 50 дб

### ISSUE THREAD

**Issue by evgen74ru** [maxsite/cms#313]
Доброго времени, на хакрф ван при включении через sdrsharp в спектре отображается сигнал 50 дб, при прокрутке частот не изменяет своего местоположения.
подскажите пожалуйста, непонятно
![1111](https://user-images.githubusercontent.com/47363753/52293034-c09fa800-2997-11e9-88a4-be3bb12f3c90.JPG)

**Comment by maxsite** [comment]
Ну вот просто интересно, что такое «хакрф ван»?

**Comment by Den2016** [comment]
палата №6? )))
