### ISSUE TITLE
Проблема с Drag&Drop в /admin/page HTTPS

### ISSUE THREAD

**Issue by Anchovys** [maxsite/cms#314]
Доброго времени суток, при переносе на HTTPS заметил проблему с маленькой, но удобной фичей - Drag&Drop загрузчиком картинок в редакторе поста. Весь сайт завелся и работает исправно, но данная проблема не дает мне покоя. При попытке загрузить файл, он просто не загружается,  пишет PREPARING.. (якобы как ошибку, красным) и не грузит. Есть предложения, как можно исправить?  P.S. Переехал на dns Cloudflare.
![default](https://user-images.githubusercontent.com/25356773/52323962-f346b080-2a2a-11e9-8cbc-b61cec02e67d.PNG)

**Comment by maxsite** [comment]
Посмотрите в логах php-ошибок, может там указана ошибка.

**Comment by Anchovys** [comment]
Проблема в том, что хостер не дает смотреть лог ошибок PHP. Я так понял за backend часть отвечает файл: /application/maxsite/admin/plugins/admin_pageuploads-require-maxsite.php. Можно произвести проверку что приходит, а что не приходит и уже от этого делать правки.  У меня догадки что часть суперглобальных переменных $_SERVER не доходит до скрипта и фильтруется Cloadflare.

**Comment by maxsite** [comment]
Вряд ли. «Preparing» — это вообще ещё js. До PHP  загрузка не дошла. Может просто браузер как-то фильтрует аякс-запрос?

**Comment by Anchovys** [comment]
Возможно так оно и есть, сменил браузер, ошибка уже другая. По моему, это уже на сервере, так?
![default](https://user-images.githubusercontent.com/25356773/52330578-77a42e00-2a41-11e9-82ac-8023abd751bd.PNG)

**Comment by Anchovys** [comment]
И да, в "инспекторе", в хроме видно как он блокирует попытку загрузить файл, т.к где-то вызывается с http:// и хром это распознает как небезопасное соединение и не дает загрузить скрипт. Только вот где подправить так чтоб было https://?
![default](https://user-images.githubusercontent.com/25356773/52330806-14ff6200-2a42-11e9-9906-27a93dbf8f7d.PNG)

**Comment by maxsite** [comment]
Протокол без разницы. Если сайт работает на http, то браузеру на это плевать — главное, чтобы это был один и тот же сайт/домен. Попробуйте другой файл, обычный текст, потом какой-то другой (например jpg).

**Comment by Anchovys** [comment]
С любым расширением загрузить то есть? То же самое, пробовал .txt, .jpg и другие. Тут я почти уверен что проблема именно в протоколе, потому что в этих случаях браузер обрывает соединение и пишет что не может загрузить файлы с сайта, мол он "непроверенный", в и этом конкретном случае возникает аналогичная проблема.
![default](https://user-images.githubusercontent.com/25356773/52331466-fc904700-2a43-11e9-9f77-3532bb11caa5.PNG)

**Comment by maxsite** [comment]
Честно говоря я даже не понимаю что это сообщение означает. Что значит «из непроверенных источников»? Это аякс, там если адрес не меняется то браузер всегда его пропускает. Может всё-таки дело в браузере? Попробуйте отключить эту самую блокировку.

**Comment by Anchovys** [comment]
Когда я жму "Загрузить небезопасные скрипты", страница перезагружается и сверху пишет красным зачеркнутый HTTPS, а при "Закидывании" файла та же самая ошибка (Uploading NaN%). Хотя в инспекторе видно что скрипты обработались и загружаются, то есть запрос вроде как проходит.

**Comment by maxsite** [comment]
У вас сайт по какому протоколу работает?

**Comment by Anchovys** [comment]
Я так понимаю "из непроверенных источников", это когда основная страница, работающая на HTTPS://, подтягивает скрипты с сайтов без защищенного протокола HTTPS, то есть нарушается все соединение с основным хостом. Я так понял, что гугл видит https://mysite.ru и http://mysite.ru как два абсолютно разных сайта, так получается вот такая история.

**Comment by Anchovys** [comment]
Сайт на HTTPS работает.

**Comment by maxsite** [comment]
В FireFox на вкладке Сеть посмотрите, может что-то по http подтягивается. В плагине range_url можно поставить главное зеркало с https — будет авторедирект. Еще можно включить/выключить в настройках универсальный протокол («//») — может он сбивает браузер с толку.

Домен анлоязычный?

**Comment by Anchovys** [comment]
Тут получается так, что в самом начале я тестировал на FireFox, там проблема с Prepairing...
Следующим был Chrome, там проблема уже с Uploading Nan..

Во вкладке сеть по http подгружаются картинки смайлов (это при загрузке страницы). Когда срабатывает Drag&Drop AJAX сработал с https://, но добавилась только одна строчка, когда в Chrome их было две. Выполнился AJAX типа domain.ru/ajax/YWRtaW4vcGx1Z2lucy9hZG1pbl9wYWdlL2FsbC1maWxlcy11cGRhdGUtYWpheC5waHA= и все.
Плагин range_url отключен у меня, если я его включаю происходит циклическая перезагрузка сайта и сайт перестает работать. Ковырять это пока не пробовал.
Универсальный протокол что включен, что отключен - разницы нет. Ну он всегда был включен, сразу после установки CMS.
Домен в зоне ru, там нет русских букв, только латиница.

**Comment by maxsite** [comment]
Протокол должен быть всегда один. Почему смайлы идут по http? И что значит «циклическая перезагрузка»? Так не должно быть. Если сайт корректно работает по https, то никакого цикла быть не должно. Думаю, что в этом и есть проблема. Браузер думает, что вы смешиваете два сайта, отсюда и сообщение. Проверяйте .htaccess, настройки хостинга так, чтобы везде был только https.

**Comment by Anchovys** [comment]
В .htaccess не вносилось никаких изменений (там нету вхождений с протоколом вообще), range_url заработал с основным зеркалом (https), без циклической перезагрузки, когда я отключил "Always Use HTTPS" в настройках Cloudflare. Сбросил кеш системы. То же самое. Смайлы - не знаю, никаких визуальных редакторов не стоит, то есть работает стандартный markItUp, видимо где-то там они подключаются по http.

**Comment by Anchovys** [comment]
Смайлы подгружаются с http потому что функция getinfo('uploads_url') в /application/maxsite/admin/plugins/editor_markitup/index.php:68 отдает http://mysite.ru/uploads/, а не https://mysite.ru/uploads/. Где эта функция объявляется?

**Comment by maxsite** [comment]
Проверьте что отдает в application\config\config.php $config['base_url'] после начального блока кода. Может $_SERVER['HTTPS'] на сервере не работает?

**Comment by Den2016** [comment]
вот и вылезли грабли с getinfo, когда она отдает (по своему разумению) абсолютную ссылку на сайт, жестко подставляя http://site.domain/uploads... А ведь есть нормальные механизмы относительной адресации, когда достаточно просто указать /uploads и любой(!) браузер корректно обработает и правильно подставит http или https.

Уберите getinfo, замените на просто '/uploads'. Уверен на 100%, что ни один сайт на этой CMS не кастомизирует /uploads на какой нить /superpuperuploads без явного вмешательства либо в процессе установки, либо без ковыряния в коде.

**Comment by maxsite** [comment]
Уверены? Вы понимаете как вообще работают относительные адреса?

**Comment by Anchovys** [comment]
$config['base_url'] отдает без https, типа такого http://mysite.ru/

**Comment by maxsite** [comment]
Тогда пропишите там явный адрес сайта без его автоопределения. Проверьте. Если работает, то нужно смотреть по докам хостера почему он не отдает этот признак.

**Comment by Anchovys** [comment]
> Уберите getinfo, замените на просто '/uploads'.
Если прописать /uploads, то возникнет проблема с работой сайта не в коренной директории, например если сайт лежит в папке /site/123, он будет обращаться не к /site/123/uploads, а /upload

**Comment by Den2016** [comment]
ну тогда хз. я так не извращался ни разу

**Comment by Anchovys** [comment]
Поставил в $config['base_url'] явный адрес с https, при беглом осмотре сайта заметил что не работает главная страница, он отбрасывает 404.
 $_SERVER['HTTPS'] пуста.

**Comment by maxsite** [comment]
Да, там же проверка $_SERVER['HTTPS' дет в разных частях кода... Нужн подумать. Не смотрели почему хостер не отдает этот признак? Может получится его явно задать?

`$_SERVER['HTTPS'] = "on";`

**Comment by Anchovys** [comment]
Задать получилось, главная страница работает, но плагин range_url не перекидывает на основное зеркало с HTTPS, указанное в настройках. А при попытке загрузить файлик получается так, что снизу отрисовывается главная страница сайта 0_0 , то есть полностью HTML код главной страницы, видимо вместо сообщения о загрузке.

**Comment by maxsite** [comment]
Сам плагин оставьте, а главное зеркало не включайте. Но главная проблема всё-таки что-то с сервером. Может есть какие-то особые настройки php/https. $_SERVER['HTTPS'] должен отдаваться корректно. Я бы в эту сторону копал.

ps Отвечу уже вечером

**Comment by Anchovys** [comment]
Хостинг Jino используется, там вроде бы особо каких-то расширенных настроек по SSL нету, всего по мнимому.

**Comment by maxsite** [comment]
Попробуйте всё-таки написать хостеру, пусть что-то сделает на сервере. У меня была как-то похожая ситуация (не помню с каким хостером, но тоже не было метки https). Админ что-то там на сервере подкрутил, всё заработало.

**Comment by Anchovys** [comment]
Написал в поддержку, за одно загуглил какими еще переменными можно определить http или нет.
1. $_SERVER['HTTP_X_FORWARDED_PROTO'] - вернет http или https (в моем случае — https)
2. $_SERVER["HTTP_USESSL"] - также как и $_SERVER['HTTPS'], она Undefined, вообще не объявлена.
3. $_SERVER['SERVER_PORT'] - 80 или 443 (у меня 80, что ставит под сомнение правильность настройки веб сервера.)
Вывод таков, что скорее всего действительно проблема в настройке веб сервера. Буду ждать ответа поддержки.

**Comment by Anchovys** [comment]
Итак, ответ поступил от СП, предложили добавить $_SERVER['HTTPS'] = "on"; в index.php, в самое начало. Сервера не отдают эту директиву так как (цитирую) "Соединение проксируют NGINX, nginx передает переменную: x_forwarded_for". Ну есть из этого один плюс, что то стало происходить с Drag&Drop, он якобы стал загружать изображение, явно намекая фразой Uploading, но потом красная тонкая линия, видимо без текста все перебивает. Это на браузере Mozilla.
![default](https://user-images.githubusercontent.com/25356773/52399042-be0f9080-2b06-11e9-9ee3-e6693872824c.png)
![default](https://user-images.githubusercontent.com/25356773/52399178-1b0b4680-2b07-11e9-81c3-6d1982808552.PNG)

**Comment by Anchovys** [comment]
В Chrome все тоже самое, только вот теперь стало понятно, что за красная линия.. Если несколько раз попытаться загрузить файлы, то внутри нее отображается html страница сайта, на котором видно что там ошибка 404, тут по моему что-то явно не так.

**Comment by maxsite** [comment]
Скорее всего адрес сайта при загрузке меняется. То есть браузер думает, что это http, поэтому формирует аякс-ссылку с http, а должен отдавать с https.

У нас аякс-ссылка формируется без протокола «//», чтобы всегда отдавать тот же протокол, что и у сайта. Но браузер всё равно думает, что это http. Отсюда и поблема.

**Comment by maxsite** [comment]
Почему-то у других хостеров тоже nginx и таких проблем нет. Может поискать нормальный хостинг, если админ не может напрячься и исправить проблему?

**Comment by maxsite** [comment]
Можете попробовать в _common.php_ с 201 строки и ниже изменить адрес `ajax`. Заменить два  вхождения `'//'` на `https://` и проверить результат.

**Comment by Anchovys** [comment]
Увы, но то же самое.

**Comment by maxsite** [comment]
Значит дело в настройках сервера. Как-то некорректно настроен https.

**Comment by Anchovys** [comment]
А какой адрес до /require-maxsite/? Разве корень? Он при загрузке файла его не находит и выдает ошибку 404, из-за этого происходит перенаправление на другую страницу /404, вот и показывает страницу сайта (задано в шаблоне). Когда я смотрю в инспекторе вкладу сеть, я наблюдаю вот такую картину.
![default](https://user-images.githubusercontent.com/25356773/52466850-75f37b00-2ba5-11e9-99c1-0ff3d5a50f1c.PNG)
Очевидно, это зашифрованый в base64 адрес "admin/plugins/admin_page/uploads-require-maxsite.php", и он отдает 404. В нормальных условиях должно так быть, если нет, то как?

**Comment by Anchovys** [comment]
То есть xhr запрос уходит "в никуда", с адресом  https://site.ru/require-maxsite/YWRtaW4vcGx1Z2lucy9hZG1pbl9wYWdlL3VwbG9hZHMtcmVxdWlyZS1tYXhzaXRlLnBocA==

**Comment by maxsite** [comment]
Здесь путь задаётся относительно /maxsite/.

**Comment by Anchovys** [comment]
Хмммм, а почему он пытается подключиться к /require-maxsite, а не /application/maxsite/require-maxsite/?

**Comment by Anchovys** [comment]
Адреса правильные, проверил с Maxsite на localhost. Даже если я вручную открою этот путь в новой вкладке, мне пишет no file на белом фоне. Хотя на рабочем сайте возвращает 404 почему то.

**Comment by Anchovys** [comment]
Выходит что проблема не в ajax и не в Js вообще, проблема с /require-maxsite/, он не отдается по этому адресу.

**Comment by maxsite** [comment]
Это специальный тип данных require-maxsite. Задается в view. Можете там проверить, что на входе получается.

**Comment by Anchovys** [comment]
Нашел. Теперь немого имею представление о нем. То есть он берет второй сегмент из URL, после HOST, и просто отдает что нужно? Только вот я не вижу там header заголовков, которые бы отдавали 404. Следовательно, первое что пришло в голову - что-то блокирует этот адрес, если это после инициализации плагинов, то это какой-то из плагинов скорее всего.

**Comment by maxsite** [comment]
Это служебный адрес по нему вообще никаких заголовков не должно отдаваться.

**Comment by Anchovys** [comment]
Его обходит мимо, он не исполняется вообще, я даже die() там в начале поставил, ни на что не влияет.

**Comment by maxsite** [comment]
Там echo '11' в самам навале нужно поставить, вызвать сайт/require-maxsite и посмотреть выводится ли текст. Если нет, то единственное место — это плагины (хук init). Попробуйте их поотключать, может что-то всплывёт.

**Comment by Anchovys** [comment]
Текст не выводится. А какие плагины могут повлиять на эту проблему? Кроме стандартных никакие не устанавливал. Включены: bbcode , captcha , page_views , pagination , parser_default , range_url , rater , run_php , shjs , sitemap , spoiler , ushki , xml_sitemap

**Comment by maxsite** [comment]
В теории — никакие. Пробуйте отключать все и проверяйте. Ну и на дефолтном шаблоне. Если ситуация не меняется, то скорее всего что-то на сервере. Иногда админы настраивают адрес sitemap на sitemap.xml, но чтобы с require такое было — ещё не сталкивался.

**Comment by Anchovys** [comment]
Что характерно, отдается 404 код и при открытии require выводится стандартная для шаблона ошибка 404.

**Comment by Anchovys** [comment]
Поставил еще одну Maxsite рядом, на поддомен дописал $_SERVER['HTTPS'] в index.php, система заработала исправно, побежал, создал страницу, попытался загрузить файл - работает! Попробую "перетянуть" сайт на основу.

**Comment by Anchovys** [comment]
Проблема решилась. Перезалил все файлы из папок /application, /system.
Не могу точно сказать, что это было, возможно что-то сломалось при переходе на HTTPS, ведь раньше сайт работал на HTTP и до перехода в системе ничего не менялось. 
Я бы рекомендовал выполнить полную переустановку системы при переходе на HTTPS. 
Благодарю за поддержку в решении вопроса.
