### ISSUE TITLE
Проблемы с вложенными тегами bbcode

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#315]
Обнаружил проблемы с bbcode-плагином, когда при использовании списков [ul][/ul] и [ol][/ol] или [pre lang=xml][/pre], например, не удается нормально использовать вложенные bb-теги? 

Например, для изменения цвета отдельных слов или отображения ссылок - bb-теги не срабатывают и просто отображаются целиком со своими квадратными скобочками. Это баг или фича?

**Comment by maxsite** [comment]
Вложенность bb-кодов довольно сложная штука, она может и сбоить. Приведите примеры, чтобы было понятна проблема.

**Comment by trommo** [comment]
В этом примере цвето-теги срабатывают, а тег принудительного переноса [br] остаётся несработавшим:
[quote]
[color=purple]int[/color] lineCount;
[br]
[color=teal]assert[/color](lineCount == [color=teal]null[/color]);
[/quote]

В этом примере цвето-теги уже не срабатывают:
[pre lang=xml][color=purple]int[/color] lineCount;
[color=teal]assert[/color](lineCount == [color=teal]null[/color]);[/pre]

Также не срабатывают теги кода в списках, когда внутри них идет цвето-тег:
[ul]
[*]строка[code][color=green]100[/color][/code].
[/ul]

[ol]
[*]строка[code][color=green]100[/color][/code].
[/ol]

Но при этом все отлично работает, когда у нас не список, а обычный параграф:

[p(t-left)]строка[code][color=green]100[/color][/code].[/p]

**Comment by trommo** [comment]
Вот тоже не благополучный случай, когда меняем местами цвето-тег с кодо-тегом:

[ul]
[*]строка[color=green][code]100[/code][/color].
[/ul]

**Comment by maxsite** [comment]
Ну это очень сложные вложения. Поскольку многие bb-коды допускают дополнительные параметры, то вложенный код уже неверно интерпретируется. Думаю, что в таких случаях лучше уже на html перейти или хотя бы simple.
