### ISSUE TITLE
Переход с MaxSite CMS: 0.806 на MaxSite CMS: 101

### ISSUE THREAD

**Issue by BuxarNET** [maxsite/cms#317]
Давно не обновлялся в виду того что изменения в шаблонах меня всегда одталкивали, дизайн менять не хочу, а перетягивать как то времени небыло.

Но назрел момент обновиться, так как на сервере ПО тоже обновлять планирую.

Вопрос следующий.
Как обновиться без потерь базы и функционала плагинов.
Используются плагины:
addzakl
antispam
bbcode
 captcha
category
 comment_smiles
down_count 
 editor_extra
feedcount
 global_cache
lightbox 
maxsite_auth
multipage
page_comments
 page_views
 pagination 
perelinks
profile
 random_pages
samborsky_ping
 sapemod 
sitemap
smiles
 spoiler
tabs
tagclouds3d
text_block
tree_comments
xml_sitemap

В последней версии они поддерживаются?
Не будет проблем с переносом настроек при обновлении?

**Comment by maxsite** [comment]
Обновляетесь как написано в инстукции и проверяете **сами**.

**Comment by Filsadovnik** [comment]
Версия плагина profile, которая работает в MaxSite CMS 101
http://fil-tec.ru/page/profile
Если в старом плагине имеется виджет, то вывод заголовка виджета возможно придется отредактировать.
`
	if ( isset($options['header']) and $options['header'] )
		$options['header'] = mso_get_val('widget_header_start', '<div class="mso-widget-header"><span>') . $options['header'] . mso_get_val('widget_header_end', '</span></div>');
	else $options['header'] = '';
`
Если что-то выводится по хуку 'content_out' - сейчас в дефолтном шаблоне этот хук не используется.
Писал об этом в комментарии к плагину **specialbox**
http://maxhub.ru/page/plugin-specialbox#comment-2759

**Comment by BuxarNET** [comment]
Спасибо, придется ставить тестовую копию, что бы обновиться и искать баги

**Comment by trommo** [comment]
При обновлении у вас не исчез вывод записей на страницах категорий?

**Comment by BuxarNET** [comment]
я еще не обновлял, раз тут нужно все досканально проверять и перепроверять, время займет много, а его пока нет
