### ISSUE TITLE
Добавить возможность работы с SQLite

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#318]
Давно хотелось добавить SQLite в MaxSite CMS, но как-то всё откладывал этот момент. Смысл в том, что база SQLite — это отдельный самостоятельный файл, которому не нужна никакая обвязка. На серверах, насколько я знаю драйвера SQLite3 давно уже как стандарт, поэтому с доступностью проблем быть не должно.

Мы давно уже используем float-опции, например те же ушки. По сути это обычный текстовый файл и есть только одна проблема: когда файл большой и в момент записи вдруг идёт еще одна запись в файл, то он может повреждаться. Наверное многие сталкивались со сбитым значением у [dc]. Вот это как раз их этой области.  

Если перейти на SQLite, то этой проблемы быть не должно, поскольку это уже полноценная БД, где транзакции уже защищены.

То есть  я думаю, что должна быть какая-то библиотека (вот здесь я привожу пример: http://maxsite.org/page/sqlite-pdo ), где будет несколько функций для работы с SQLite. Вначале под неё переделать какой-то один плагин (например DC, с возможностью конвертировать старые данные), после замахнуться на те же ушки.

**Comment by Kotgo** [comment]
Хорошая идея, пользуюсь на других скриптах SQLite 3 удобно в установке и резервировании, но пока не разобрался с помощью чего эту базу редактировать
И как переносить данные с MySql на SQLite 3 ?

**Comment by maxsite** [comment]
Данные переносятся черех sql-запросы. Админить можно например так: phpLiteAdmin http://www.phpliteadmin.org/

**Comment by Kotgo** [comment]
Понял, спасибо. Только у хостеров, которыми пользуюсь нет такой установки как phpLiteAdmin.

Но в принципе, за всё время использования Sqlite3 как базы данных, пришлось только раз столкнуться с тем, чтобы что-то редактировать, это был вопрос перевода сайта с windows-1251 на UTF-8 , так и не перенёс, пользуюсь до сих пор windows-1251

Максим, а можете сделать, чтобы была возможность автоматического переноса с Mysql на Sqlite3 ?

В целом поддерживаю идею Sqlite3 и чтобы MySql была для тех, кто не умеет переносить базу.

**Comment by Kotgo** [comment]
Вот ещё нашёл https://sqlitebrowser.org/ , но пока не пользовался.

**Comment by maxsite** [comment]
> Понял, спасибо. Только у хостеров, которыми пользуюсь нет такой установки как phpLiteAdmin.

Так и не нужно. Это отдельный php-скрипт. Просто загружаете на свой сервер, прописываете конфиг с базами и дальше работаете через браузер.

> Максим, а можете сделать, чтобы была возможность автоматического переноса с Mysql на Sqlite3 ?

Зачем? Есть стандартные операции импорта/экспорта через sql-запросы.

**Comment by Kotgo** [comment]
> 
Так и не нужно. Это отдельный php-скрипт. Просто загружаете на свой сервер, прописываете конфиг с базами и дальше работаете через браузер.
> 
Понял, спасибо.

**Comment by Kotgo** [comment]
> 
Зачем? Есть стандартные операции импорта/экспорта через sql-запросы.
> 
К сожалению, я не знаю как это делать между двумя разными типами баз данных.

**Comment by Kotgo** [comment]
Максим, подскажите, а когда планируете добавить SQLite версию?

**Comment by maxsite** [comment]
Пока думаю над этим вопросом. Есть сложность с переносом данных из файлов в sqlite-базу — там всё не так просто. Так же неясно стоит ли делать общую библиотеку или ограничиться чем-то более простым. Если сейчас ошибиться, то потом возврат будет сложен, можно что-нибудь «сломать».

**Comment by Kotgo** [comment]
Понял, тогда лучше не торопиться с этим вопросом.
