### ISSUE TITLE
Откуда берется надпись "Выбрать файлы" на кнопке загрузки изображений?

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#319]
Вот эта кнопка:
`<input class="w-auto mar10-b" type="file" id="upload_fileselect" name="upload_fileselect[]" multiple="multiple">`
Что-то очень простое, а не находится - заранее извиняюсь..

**Comment by maxsite** [comment]
Это от браузера и ОС зависит.

**Comment by Filsadovnik** [comment]
Ни за что бы не догадался сам.
