### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by Orkzed** [maxsite/cms#320]
![indeks](https://user-images.githubusercontent.com/47955049/53307084-2d7ad380-38ae-11e9-8d76-d3239351d99e.png)

При создание записи выскакивает такая ошибка.

Кроме того возникает такая проблема: 

`Disallowed Key Characters.`

Захожу через IP.

**Comment by maxsite** [comment]
Какой шаблон?

**Comment by Orkzed** [comment]
Шаблон тот который по умолчанию (https://prnt.sc/mpr8v9). Но скажу что во время инсталляции я поставил галочку чтобы загрузились демо записи.

**Comment by maxsite** [comment]
Проверю, пока ничего не скажу.

**Comment by maxsite** [comment]
Посмотрел, ошибок не вижу. Возможно не все файлы загрузили или они битые. У вас на скриншоте ошибка в символе, которого вообще нет.

**Comment by maxsite** [comment]
Загружали файлы по ftp?

**Comment by Orkzed** [comment]
Ага, потом подумал может не так загружает FTP client, скачал через веб-интерфейс. И тоже самое происходит. Особенно бесит: 

`Disallowed Key Characters.`

**Comment by maxsite** [comment]
Приводите полные логи ошибок, так ничего не понятно.

**Comment by Orkzed** [comment]
> Что такое «Disallowed Key Characters»?

Когда перехожу по разделом на админке вдруг все обновляется и вижу вот это: https://prnt.sc/mpty8y
Все, нечего не открывается. Не сайт, не админка, не разделы. Везде только такая ошибка. Спасает только очистка кеша и после все заново повторяется. Я об этом писал на офф. сайте в разделе комментариев, но пока не опубликовали. 

> Что такое «Захожу через IP»?

Это значит что у хоста нет прикрепленного домена в данный момент. Захожу и просматриваю сайт классическим методом: IP/~hostname

**Comment by maxsite** [comment]
Ну так значит в этом всё и дело. Пропишите домен как нужно. Система не может корректно его определить, вот и вываливается «белиберда».

**Comment by Orkzed** [comment]
Вопрос решен. Спасибо.
