### ISSUE TITLE
Проблемы с формированием url при переходе на https

### ISSUE THREAD

**Issue by miguralex** [maxsite/cms#321]
Добрый вечер, Максим. Решил обновить пару сайтов, переехать на https и на php 7.1. Всё вроде бы прошло гладко, без каких-либо сложностей, но заметил одно но. Google почти месяц отказывается индексировать https версию, Яндекс же всё "скушал" без проблем.

Начал искать проблему, спустя 3 дня кажется нашел. Сайты переносил с адресов http://www.site.ru на https://site.ru. Чтобы избежать двойного редиректа (со страниц с www на страницы без www, а потом на https) .htaccess сделал таким:

> <IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L,QSA]
RewriteCond %{HTTPS} off [OR]
RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
RewriteRule ^(.*)$ https://site.ru/$1 [L,R=301]
</IfModule>

И вроде бы всё работает, НО! Если запросить страницу записи с алиасом www, то в адрес самой записи добавляется index.php. В качестве примера:
Если идем на http://www.site.ru/page/some-page-theme
то нас перекидывает на
https://site.ru/index.php/page/some-page-theme

Эти страницы с index.php периодически стали проскакивать в выдаче google, потом снова исчезать. Подскажите, как решить данный вопрос. Спасибо.

**Comment by maxsite** [comment]
Не совсем понятно зачем здесь редирект с www. Включите определение главного зеркала в range_url — он будет работать автоматом. В .htaccess же оставьте только редирект с http на https. Сам код нужно подбирать — это от сервера зависит (можно у хостера уточнить).

**Comment by miguralex** [comment]
Спасибо, Максим. С плагином range_url всё заработало как надо.

**Comment by miguralex** [comment]
Максим, уже писал Вам как-то на сайте. Добавьте пожалуйста какую нибудь альтернативу Webmoney на страницу помощи - http://max-3000.com/page/donation. В Украине сейчас с Webmoney совсем тяжело, а периодически поддерживать этот замечательный проект желание есть. Спасибо.

**Comment by maxsite** [comment]
Да я в курсе. :) Просто единственный вариант — это карточка, но «светить» её не лучший вариант.

**Comment by miguralex** [comment]
Ну почему, например Яндекс Деньги одинаково хорошо теперь работают как в Украине (через VPN), так и в РФ. С недавнего времени идентификацию пользователя в Украине можно пройти Online. Причем дают не именной, а именно идентифицированный статус. Соответственно никаких проблем с вводом/выводом средства, плюс можно прикрутить кнопку для донатиков прямо на сайте.

Инструкция по идентификации: https://yandex.ru/support/money/identification/outside-russia.html

**Comment by maxsite** [comment]
Не, я с этой вражеской конторой раньше уже связывался. Еле избавился от их фантиков. Доната через яд — мизер, так что оно этого не стоит.
