### ISSUE TITLE
Поменялись заголовки с h1 на h3 после обновления до 102.3

### ISSUE THREAD

**Issue by Sergeysem** [maxsite/cms#322]
Доброго времени.
После обновления, поменялись заголовки с h1 на h3 на страницах:
Карта сайта `<h3>Карта сайта (архив)</h3>` было `<h1>Карта сайта (архив)</h1>` 
Обратная связь `<h3>Обратная связь</h3>` было `<h1>Обратная связь</h1>`

**Comment by Sergeysem** [comment]
\application\maxsite\shared\type\sitemap\sitemap.php

![2019-02-28_22-25-03](https://user-images.githubusercontent.com/44212501/53589051-d0ca3200-3ba7-11e9-8015-b5cd3e4d333e.jpg)

В другом файле наверно также, не проверял. Максим подправьте.

**Comment by maxsite** [comment]
Так и задумано. Верстка приведена к одному виду.

**Comment by Sergeysem** [comment]
К одному виду с чем? Например страница site.ru/comments заголовок h1, site.ru/guestbook заголовок h1.

**Comment by Sergeysem** [comment]
То есть теперь, после каждого обновления, нужно править заголовки? Странно то, что у страницы не будет заголовка h1. Может к этому виду нужно приводить, а не к h3?

**Comment by maxsite** [comment]
Это служебные страницы и h3 больше подходит по размеру.

**Comment by Sergeysem** [comment]
Бррр.. нет смайлов, чтобы выразить свое недоумение.)))
