### ISSUE TITLE
CSS профиль paragraph-justify.css портить формы

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#323]
Если включить в **/admin/template_options->CSS профили**, то подписи в формах (регистрации, обратной связи ...) растягиваются и становятся нечитаемы.

**Comment by maxsite** [comment]
Ну наверное потому что это и есть суть данного профиля.

**Comment by Filsadovnik** [comment]
Понятно, но разве он не должен влиять только на content?
Какой в нем смысл, если часть сайта портится при его включении?

**Comment by maxsite** [comment]
Смысл в том, чтобы использовать его при редактировании конкретной записи.

**Comment by Filsadovnik** [comment]
А, вот в чем дело.
