### ISSUE TITLE
Какой css применить для вывода пункта menu справа?

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#324]
Собственно, первый пункт, связанный с админкой, переношу в конец и надо чтобы он был справа.
Указание t-right пункту приводит к тому что его подпункты оказываются справа, но не сам пункт.
`
$menu .= NR . '# | | Админ-панель MaxSite CMS |t-right | i-maxcdn;
`
Разбитие меню на два меню не помогает.
```

<ul class="menu menu-no-load menu-hover menu-tablet">
       <?php
               $menu = NR . mso_get_option('top_menu', 'templates', tf('   .................   '));;
              if ($menu) echo mso_menu_build($menu, 'selected', false);
       ?>
</ul>
<ul class="menu menu-no-load menu-hover menu-tablet t-right">
      <?php		
            $menu = '';
            if (is_login())
           {
	         $menu .= NR . '[';
	         $menu .= NR . '# | | Админ-панель MaxSite CMS | | i-maxcdn';
                  .......................
           }
    ?>
</ul></nav>


```

**Comment by maxsite** [comment]
Пунктами не получится сделать — это же ul/li список. Менять сам порядок пунктов. Смотрите что в итоговом $menu — переносите так чтобы админ-пунты оказались справа.

**Comment by Filsadovnik** [comment]
Порядок то поменял.  Проблема в том чтобы последний пункт (который теперь админ-пункт) прилип в правый конец строки меню.

**Comment by maxsite** [comment]
Нужен правый, выводится справа. В чём проблема-то?

**Comment by Filsadovnik** [comment]
Чтобы все пункты меню шли подряд слева на право, а последний прилип в самый правый угол сайиа в строке меню. Как соцсети или корзина.

**Comment by maxsite** [comment]
Думаю, что лучше разбить меню на две части. Загнать их в ячейки flex — правую выровнять вправо. Тогда это будут разные меню.

**Comment by Filsadovnik** [comment]
Ключевое слово было flex , спасибо.
Отличный результат так получился:
```
<div class="menu1 menu1-tablet clearfix">
   <div class="wrap flex">
	<nav>
       ......menu1..........
	</nav>
	<div class="t-right">
	      <nav>
	           <ul class="menu menu-no-load menu-hover t-left pad20-rl">
                        ......menu2..........
	          </ul>
             </nav>
        </div>
  </div>
</div>
```
