### ISSUE TITLE
Опции компонентов - вопрос в целях саморазвития.

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#325]
Почему опции компонентов сохраняются поотдельности 
`$rules = trim(mso_get_option('top1_rules_output', getinfo('template'), ''))`
, а не массивом 
`'options_'top1' = array ('rules_output ...')`

**Comment by maxsite** [comment]
Опция может быть любой, хоть скалярной, хоть массивом. Вопрос только в организации её получения. Если мы получаем массив, то требуется ещё дополнительная обработка с проверкой наличия нужного ключа. Со скалярной сразу получаем требуемые данные. 

В mso_admin_plugin_options как раз используется массив, а сама опция одна. Поэтому какой вариант выбрать зависит только от самого разработчика плагина.
