### ISSUE TITLE
После обновления до версии 102.3 перестали выводиться записи на страницах категорий

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#326]
Обновил сразу несколько сайтов с различных версий 0.9* до 102.3 по причине обновления ПО на сервере. Первый же баг, который был замечен - это прекращение вывода списка записей на страницах рубрик:

> 404. Ничего не найдено...
> 
> Извините, ничего не найдено

Экспериментировал - баг наблюдается при "быстром обновлении" через _update_mso, при правильном обновлении, и даже в том случае, когда полностью сносишь все файлы движка и ставишь систему по-новой.

Сегодня с утра попробовал на пустом домене поставить систему - тот же баг. Можете сами убедиться - u200.org.

Может быть при обновлении ПХП до версии 7.2 надо было какой-либо модуль доставить, чтобы вывод списка записей в категории нормально работал?

**Comment by maxsite** [comment]
У вас вообще пустой сайт. Сложно сделать ещё записей?

**Comment by trommo** [comment]
Сделал несколько тестовых записей в нескольких категориях - результат тот же.

Страницы меток выводят свои записи: u200.org/tag/метка3.
Страницы категорий - нет.

**Comment by maxsite** [comment]
На дефолтном шаблоне проверьте. Плагины сторонние ставили? Время сервера проверьте в настройках.

**Comment by trommo** [comment]
На дефолтном то же самое, я проверял же уже на нескольких сайтах.
Здесь всё родное, сторонних плагинов нет, за категории отвечает родной category, который входит в сборку.

Что именно с временем сервера надо проверить? У меня такое ощущение, что что-то из софта на сервер не установлено.

**Comment by maxsite** [comment]
Поставьте дату публикации на вчера и проверьте.

**Comment by trommo** [comment]
Изменил у пары записей даты на вчерашнюю и позавчерашнюю - не помогло.

**Comment by maxsite** [comment]
В настройках служебное проверьте смещение времени.

**Comment by trommo** [comment]
Стояло нулевое смещение. Попробовал сначала сдвинуть на +1.00, затем +2.00 - не помогло.

**Comment by maxsite** [comment]
В логах php ошибки есть?

**Comment by trommo** [comment]
Нет, не вижу. Попробую перенастроить сегодня с нуля вывод логов ПХП в отдельный файл. Они сейчас вместе с апачевскими, как я понял, пишутся.

**Comment by trommo** [comment]
Настроил вывод ошибок ПХП на сервре - тестовые ошибки, которые я генерирую специально - фиксируются. А вот от нескольких сайтов на MaxSite CMS, у которых не работает вывод записей на страницах категорий, ошибки не выводятся.

**Comment by maxsite** [comment]
В файле common/page.php в 239 строке 
https://github.com/maxsite/cms/blob/master/application/maxsite/common/page.php#L239
уберите комментарий с `pr($query_sql);` Зайдите на страницу рубрики и увидите sql-запрос. Покажите его.

**Comment by trommo** [comment]
Вот что выдало, когда зашел на страницу категории:

SELECT `mso_page`.`page_id`, `page_type_name`, `page_slug`, `page_title`, `page_date_publish`, `page_status`, `users_nik`, `page_content`, `page_view_count`, `page_rating`, `page_rating_count`, `page_password`, `page_comment_allow`, `page_id_parent`, `users_avatar_url`, `mso_category`.`category_name`, `mso_page`.`page_id_autor`, `users_description`, `users_login`
FROM (`mso_page`)
JOIN `mso_users` ON `mso_users`.`users_id` = `mso_page`.`page_id_autor`
JOIN `mso_page_type` ON `mso_page_type`.`page_type_id` = `mso_page`.`page_type_id`
JOIN `mso_cat2obj` ON `mso_cat2obj`.`page_id` = `mso_page`.`page_id`
JOIN `mso_category` ON `mso_cat2obj`.`category_id` = `mso_category`.`category_id`
WHERE `page_status` =  'publish'
AND `mso_category`.`category_slug` =  'drevnosti'
GROUP BY `mso_page`.`page_id`
ORDER BY `page_date_publish` desc
LIMIT 7

**Comment by maxsite** [comment]
Тут всё нормально. Попробуйте выполнить этот запрос в БД через phpMyAdmin. Если возвращает ноль записей, значит что-то с самой базой. Других вариантов просто не вижу.

**Comment by maxsite** [comment]
Кстати, версия MySQL какая?

**Comment by trommo** [comment]
После введения в консоли команды `mysql --version`
выводится такое:
> mysql Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using EditLine wrapper 

Получается, MySQL забыл обновить?
Потому что когда выполняю запрос в БД через phpMyAdmin, выводит ошибку:

> Статический анализ:
 Найдено 4 ошибок при анализе.
     Ожидалось выражение. (near "(" at position 372)
     Неожиданный токен. (near "(" at position 372)
     Неожиданный токен. (near "`mso_page`" at position 373)
     Неожиданный токен. (near ")" at position 383)
 SQL запрос:
 =======
 повторение самого запроса
 =======
  Ответ MySQL: Документация
 #1055 - Expression #16 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'u200.mso_category.category_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by maxsite** [comment]
Скорее всего что-то с режимом MySQL sql_mode.

**Comment by maxsite** [comment]
В общем дело в новых настройках MySQL 5.7, где по умолчанию включен режим ONLY_FULL_GROUP_BY, что и приводит к ошибке SQL-запроса. Попробуйте в 953 строчке заменить код с group_by:
`$CI->db->group_by(array('page.page_id', 'category.category_name'));`

Второй путь — отключить этот режим MySQL на более щадящий.

**Comment by trommo** [comment]
Похоже, что дело в обновлении MySQL , начиная с версий 5.7.*...

Из того, что было доступным на [stackoverflow.com](https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql) и помогло мне - пришлось в файл /etc/my.cnf дописывать следующее:

> [mysqld]
> sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

После чего перегрузить MySQL на сервере.

Тему можно закрывать, надеюсь, она поможет тем, у кого подобный VPS на Убунту.

**Comment by trommo** [comment]
Ну, код движка я принципиально менять не хочу, тогда придётся при каждом обновлении ЦМС его править. Поэтому пока обошлось "малой кровью" с редактированием настроек MySQL...

**Comment by maxsite** [comment]
Попробуйте всё-таки мой вариант — я внесу изменения в MaxSite CMS, поэтому ничего править не придется. Я протестировал на своём сервере, проблем с этим кодом нет, но лучше чтобы проверил ещё кто-нибудь. Тут, всё действительно завязано на конфигурацию MySQL 5.7.

**Comment by trommo** [comment]
ОК, сейчас сделаю правки в /application/maxsite/common/page.php

**Comment by trommo** [comment]
Не знаю, как лучше будет - создавать новый пост или продолжать здесь?

В общем, на обновлённых движках после всех этих обновлений софта на сервере перестали создаваться новые записи - проверил на двух сайтах. В то время как на тестовом домене u200.org, где система была установлена с нуля, всё ОК - записи создаются.

Запись не создаётся ни в одном из предложенных вариантах - ни при публикации, ни в черновик, ни в "личное". При этом сверху появляется красная полоса с текстом "ошибка создания страницы". Проверил лог ПХП - ошибки не выводит.

**Comment by maxsite** [comment]
Лучше здесь. 

Я вижу, что рубрики теперь нормально выводятся. Но проблема при создании новых записей? Это на существующем сайте или сразу после новой установки?

**Comment by trommo** [comment]
На всех сайтах, где было обновление. На тестовом сайте, где я недавно движок с нуля поставил - все ОК, новые записи создаются.

Проверил публикацию вчерашним числом  и сдвижку по времени - та же беда, выдает "Ошибка создания страницы" на красной полосе сверху.

**Comment by maxsite** [comment]
На всех сайтах стоит MySQL 5.7 и последняя версия MaxSite CMS, где внесена приведенная мной правка?

**Comment by trommo** [comment]
Да, везде из /application/maxsite/common/page.php удалено `category.category_name` в двух строках и везде MySQL 5.7.*.

**Comment by maxsite** [comment]
Я смог воспроизвести ошибку на тестовом сервере с выводом рубрик, а с созданием записи ошибок не вижу. То есть нужно как-то воспроизвести проблему.

**Comment by maxsite** [comment]
При создании записи вы какие данные вводите?

**Comment by trommo** [comment]
Заголовок, тело статьи, отмечаю рубрику - уже даёт ошибку. Если далее заполняю тайтл, дескрипшн, ключевые слова - то же самое. Добавляю короткую ссылку - тоже та же ошибка.

**Comment by maxsite** [comment]
То есть проблема не только при создании новой записи, но и обновлении существующей?

**Comment by trommo** [comment]
Нет, обновление существующих происходит без проблем.

**Comment by maxsite** [comment]
Попробуйте в файле maxsite\common\functions-edit.php в строчке 713 раскоментировать
`pr($ins_data);`
Чуть ниже **перед**  `if ($res)` добавьте 

`pr($res);`

**Comment by trommo** [comment]
Раскомментировал и добавил, при попытке создания записи выводит следующее:

`Array
(
    [page_type_id] => 1
    [page_id_parent] => 0
    [page_id_autor] => 1
    [page_title] => Test page
    [page_content] => Тест тест тест.
    [page_status] => publish
    [page_slug] => test-page
    [page_password] => 
    [page_comment_allow] => 1
    [page_ping_allow] => 0
    [page_feed_allow] => 1
    [page_date_publish] => 2019-03-10 13:46:22
    [page_last_modified] => 2019-03-10 13:46:22
    [page_menu_order] => 0
)`

А ниже - красную полосу с фразой про ошибку создания страницы.

**Comment by maxsite** [comment]
Должно вывсети ещё 1 или 0.

**Comment by maxsite** [comment]
Значит не выполняется sql-запрос с INSERT. Тут уже кухня CodeIgniter... Думаю, что нужно включать лог sql-запросов на сервере и там уже смотреть в чём проблема.

**Comment by maxsite** [comment]
Вот что можно сделать. В файле **system\database\DB_active_rec.php** в строке 1195 после строчки «$sql = ...» допишите:

`pr($sql);`

Это выведет все сформированные запросы. Что там?

**Comment by trommo** [comment]
Между массивом и нулём добавило строку:

`INSERT INTO `mso_page` (`page_type_id`, `page_id_parent`, `page_id_autor`, `page_title`, `page_content`, `page_status`, `page_slug`, `page_password`, `page_comment_allow`, `page_ping_allow`, `page_feed_allow`, `page_date_publish`, `page_last_modified`, `page_menu_order`) VALUES ('1', '0', 1, 'Test page', 'dfafasf', 'publish', 'test-page', '', 1, 0, 1, '2019-03-10 16:01:36', '2019-03-10 16:01:36', 0)`

**Comment by maxsite** [comment]
Вроде всё нормально. Попробуйте это запрос в phpMyAdmin выполнить.

**Comment by trommo** [comment]
PhpMyAdmin что-то к настройкам времени придирается:

#1292 - Incorrect datetime value: '0000-00-00 00:00:00' for column 'page_date_dead' at row 1

При этом снова попробовал опубликоваться от прошлого месяца, сместив предварительно настройки времени в "Общих" - та же ошибка.

**Comment by maxsite** [comment]
Хм... Откуда вообще берется такое значение даты?.. В phpMyAdmin посмотрите в структуре таблицы mso_page какое значение по умолчанию у page_date_dead? Должно быть 2008-01-01 00:00:00.

![111](https://user-images.githubusercontent.com/2226781/54090175-07f3cc80-437a-11e9-9704-d9bda690c6ac.png)

**Comment by trommo** [comment]
Просмотрел для всех сайтов на MaxSite CMS, - везде page_date_dead обнулён, даже в БД тех сайтов, которые уже давно не используются и их домены просрочены. Получается, что это "косяк" обновления MySQL, поскольку в БД сайта u200.org с установленной "с нуля" системой ничего не обнулено, а стоит дата `2008-01-01 00:00:00`.

**Comment by maxsite** [comment]
Скорее всего это очень старые сайты, где могла использоваться такая дата (при установке MaxSite CMS). В MySQL 5.7 такое теперь запрещено, поэтому ошибка и вывалилась. Для это версии базы, если старый сайт, нужно внести правки в таблицу, либо отключать строгий режим MySQL. 

Посмотрел по коммитам где было это исправление: https://github.com/maxsite/cms/commit/0aa1e23f756c932dfab4dc429b3c97f98927b481#diff-e0b06e3992ab4c1812c20a5daa4e5c75

**Comment by trommo** [comment]
Ну да. Самому молодому 6 лет в апреле будет. Самому старому - 12. Ещё несколько штук где-то между.

Интересно, когда делали изменения в инсталляционном коде для совместимости с MySQL 5.7 - не было ли подобных жалоб, как в моём случае? Ну по поводу багов у обновлённых сайтов?

**Comment by maxsite** [comment]
Не было. Исправление внесли, когда на MySQL кто-то включил строгий режим и мы это выяснили. Просто MySQL 5.7 если и используют, то в нестрогом режиме, поскольку куча сайтов просто посыпится.

**Comment by trommo** [comment]
Прошелся по архиву, нашел [ветку](https://github.com/maxsite/cms/issues/161#issuecomment-251965012) с подобной проблемой. 

Так а все-таки, как-то можно исправить БД уже существующих проектов, чтобы не трогать строгий режим MySQL?

**Comment by trommo** [comment]
Вручную изменил в ПМА на одном из проблемный сайтов нулевую дату у `page_date_dead` на 

> 2008-01-01 00:00:00

Вроде бы помогло. Сейчас пойду с другими сайтами то же самое сделаю.

**Comment by maxsite** [comment]
Ну так и нужно — вручную исправлять. :-)

**Comment by trommo** [comment]
"Наша песня хороша, начинай сначала" (С)

Когда создал новую запись с указанием картинки записи, то последняя не генерируется.

<img src="http://icecream.me/uploads/cb47d7cccf28889a10996ca6a92bbc2f.png" />

**Comment by maxsite** [comment]
Так путь проверьте, пишет что нет файла или каталога.

**Comment by trommo** [comment]
Папки все есть по пути. Почему-то он файл не создаёт.

Ошибка указывает на файл 
/application/maxsite/shared/stock/thumb/thumb.php

В нем на 337 строке следующее:

`$image_info = GetImageSize(getinfo('uploads_dir') . $this->new_file);`

**Comment by maxsite** [comment]
Не знаю. Ошибка же не просто так показывается. Может прав не хватает.
