### ISSUE TITLE
Опечатка в закрывающем теге

### ISSUE THREAD

**Issue by NtTel** [maxsite/cms#327]
https://github.com/maxsite/cms/blob/e9ff35516227f1ee3ac26c7ec2fa4e575c355c7b/application/maxsite/shared/type/sitemap/sitemap.php#L12

**Comment by maxsite** [comment]
Спасибо, исправлю.

**Comment by Sergeysem** [comment]
Максим, я об этом писал уже.. https://github.com/maxsite/cms/issues/322#issuecomment-468382773, но вы не наверно не смотрели на скрины.
И вопрос, почему было принято решение заменить h1 на h3, ссылаясь на то, что бы размер был везде одинаковый?
Для этого есть стили ( я вам говорил в одном из вопросов, что нужно добавит br в код, вы мне сказали что есть стили, а тут вон оно как) и негоже удалять тег h1 со страницы.

Сделайте тег h1 c классом и кому не нравится размер, подправят его в стилях. Я не прав?

**Comment by maxsite** [comment]
Это служебные страницы. Изначально для них и был H3, но на некоторых я упустил этот момент и получилость, то на одних H1, как на полноценных страницах, а где-то H3, как на служебных. Поэтому я просто пивёл всё к одному виду. И чисто визуально там не нужен бльшой заголовок. Пользы от H1 там нет никакой.

**Comment by Sergeysem** [comment]
Ну хорошо, тогда к h3 на этих страницах, можете добавить класс?

**Comment by maxsite** [comment]
Зачем? Используйте каскадность CSS.

**Comment by Sergeysem** [comment]
Нет!!! Придется менять h3 на h1 при каждом обновлении, и это только из за того, что автору понадобилось подгонять под какие то размеры шрифтов, таким непонятным способом.

**Comment by maxsite** [comment]
Хотите свою разметку? Копируйте файл в свой шаблон и там делайте что душе угодно. Автор же привёл вёрстку к одному виду. Жаль, что вы этого не хотите понять.

**Comment by akaguny** [comment]
с точки зрения семантики h1 на странице таки должен быть.
опционально h1 в html5 секции может быть в секции свой.
применение hN для стилизации в корне не верно, hN применяется для структуризации документов.
назначение страницы не имеет значения в вопросе разметки если она будет показана пользователю.

**Comment by maxsite** [comment]
Ну, ну... Приведите-ка ссылку на документацию, где написано, что H1 обязательный заголовок и «должен быть».

**Comment by akaguny** [comment]
> с точки зрения семантики h1 на странице таки должен быть.

Речь не про обязательность)

Если нужна ссылка на документацию, то https://www.w3.org/TR/2011/WD-html5-author-20110705/the-h1-h2-h3-h4-h5-and-h6-elements.html. Однако я уверен что ты более чем знаком с ней)
Могу также скинуть ссылку на [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes) в статье явно говорится:
```
* Heading information may be used by user agents, for example, to construct a table of contents for a document automatically.
* Не используйте низкие уровни чтобы снизить размер шрифта: используйте CSS font-size вместо.
Избегайте пропуск уровней заголовков: всегда начинайте с <h1>, потом используйте <h2>, и так далее.
* Вам следует рассмотреть избегание использования <h1> более раза на страницу. Смотрите Defining sections в Using HTML sections and outlines.
```

**Comment by maxsite** [comment]
Как видите, в документации HTML5 (MDN — это не стандарт) нет ни слова про обязательность H1 (N) или их очерёдность. Есть только «ранг заголовка» и в данных страницах он и должен быть понижен, чтобы дать возможность нижнему тексту получить более высокий приоритет. Если вы не согласны, то никто вам не мешает сделать свой вариант.

**Comment by akaguny** [comment]
> Как видите, в документации HTML5 (MDN — это не стандарт) нет ни слова про обязательность H1 (N) или их очерёдность.

Очень даже есть:
@maxsite Если походить по ссылкам из спецификации, точнее по одной, где описана семантическое значение заголовков то там есть не прозрачный намёк на то как надо использовать и примеры по использованию:
```
Sections may contain headings of any rank, but authors are strongly encouraged to either use only h1 elements, or to use elements of the appropriate rank for the section's nesting level.

Authors are also encouraged to explicitly wrap sections in elements of sectioning content, instead of relying on the implicit sections generated by having multiple headings in one element of sectioning content.
```
https://www.w3.org/TR/2011/WD-html5-author-20110705/headings-and-sections.html#headings-and-sections

> Есть только «ранг заголовка» и в данных страницах он и должен быть понижен

на самом деле при отсутствии других заголовков более высокого ранга по спецификации ваш hN+1 будет самый высокий не уступающий h1 в случае его наличия.

**Comment by maxsite** [comment]
Вообще-то здесь речь идёт об Headings and sections — размещении заголовках в секциях. Рекомендации для тех случаев, когда заголовки разбивают тексты и когда каждая секция не отмечена специально. Вам же приведены примеры разметки, где смешаны заголовки и секции. Посмотрите, поизучайте. Я абсолютно уверен, что вы даже не потрудились посмотреть какая в sitemap генерируется html-разметка и почему будет правильным понизить заголовок страницы до уровня остальных заголовков этой страницы.
