### ISSUE TITLE
После обновления на 102.7 появилась ошибка

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#328]
Максим, обновился до 102.7 и появилась ошибка:

A PHP Error was encountered

Severity: Warning

Message: array_map() [function.array-map]: Argument #2 should be an array

Filename: common/common.php

Line Number: 3254

Вернулся на прежнюю версию. Подскажите что не так и как исправить ?

Спасибо.

**Comment by maxsite** [comment]
В шаблоне есть каталог type_foreach?

**Comment by maxsite** [comment]
B какая версия PHP?

**Comment by Kotgo** [comment]
У меня шаблон default из 100 версии с изменёнными немного стилями , там есть папка type_foreach

**Comment by Kotgo** [comment]
PHP Version 5.3.29

**Comment by maxsite** [comment]
Понятно. Версия PHP должна быть как минимум 5.4, но лучше сразу переходите на 7.0 и выше. В течение года я буду повышать требования к версии PHP и в конце года минимум будет — 7.0 (или 7.1 — ещё не решил).

**Comment by Kotgo** [comment]
Понял, спасибо, буду исправлять.

**Comment by Sergeysem** [comment]
> Версия PHP должна быть как минимум 5.4, но лучше сразу переходите на 7.0 и выше. В течение года я буду повышать требования к версии PHP и в конце года минимум будет — 7.0
То есть нужно менять хостинг, если обновиться?

**Comment by maxsite** [comment]
Достаточно только PHP. Уточните у хостера, возможно версию можно в панели хостинга переключить.
