### ISSUE TITLE
Идея: номер страницы в title страниц (sitemap, category, tag, etc)

### ISSUE THREAD

**Issue by Anchovys** [maxsite/cms#329]
Приветствую. 
Для избежания дублей при индексации предлагаю в Title страниц с поддержкой пагинации, передавать номер страницы, например для: `/category/cars/next/11` выдавать титул `Автомобили: страница 11` и т.д

**Comment by Anchovys** [comment]
Подозреваю, что это можно сделать при помощи Segment. Выбрать из полного адреса нужный сегмент и подставить его в титул. Хотелось бы чтобы данный функционал был добавлен в основную ветку maxsite, поскольку он точно не помешает для оптимизации сайта в поиске.

**Comment by maxsite** [comment]
Да, можно подумать...

**Comment by Anchovys** [comment]
Вот так наверно.. Это грязный код без функций движка
```php

$full_url = $_SERVER['REQUEST_URI'];

$full_url = explode("/", $full_url );

if($full_url [count($full_url)-2] == "next" && $full_url[count($full_url)-1] != "") 
        $title_suffix = " - стр: ".$full_url[count($full_url)-1];


mso_head_meta('title', $pages, '%category_name%'. $title_suffix ); //  meta title страницы
mso_head_meta('description', $pages, '%category_desc%'); // meta description страницы
mso_head_meta('keywords', $pages, '%category_name%'); // meta keywords страницы

**Comment by maxsite** [comment]
Ну для этого есть готовая функция: mso_current_paged(). Такое нужно делать только создав отдельную опцию, чтобы каждый сам мог настроить что выводить. Иначе будет много недовольных. :)

**Comment by Anchovys** [comment]
Можно сделать checkbox где-то в настройках: Выводить нумерацию страницы в Meta Title

**Comment by maxsite** [comment]
Скорее формат вывода. Чуть позже подумаю.
