### ISSUE TITLE
Удалить все meta keywords

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#330]
Проскольку поисковики давно уже не поддерживают это meta-свойство, то можно выпилить из MaxSite CMS опции и часть кода.

**Comment by Kotgo** [comment]
Тему пропустил. Максим, а можно оставить ключи для тех, кто хочет использовать эти ключи в meta?

**Comment by maxsite** [comment]
Я же ответил — делайте свои ini-файлы в шаблоне.

**Comment by Sergeysem** [comment]
А где можно прочитать, что поисковики не поддерживают meta keywords? Или это кто то где то сказал и все понесли?

**Comment by maxsite** [comment]
Например потрудиться поискать в google.com.

**Comment by dignityinside** [comment]
Google:
https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html
https://www.youtube.com/watch?v=jK7IPbnmvVU&
