### ISSUE TITLE
Не работала обработка тега [br]

### ISSUE THREAD

**Issue by mbgroot** [maxsite/cms#331]
Добавил в bbcode/index.php строчку:
`'~\[br\]~si'                    => '<br clear="all">',`
Заработало. 

Или так и было задумано?

**Comment by maxsite** [comment]
Это лишнее. Обработка [br] происходит в плагинах парсера текста parser_simple и parser_default.

**Comment by mbgroot** [comment]
Ясно. Судя по всему parser_simple у меня почему-то не работает...

**Comment by Kotgo** [comment]
Максим, поставил версию 102.8 на новый сайт и тоже не обрабатываются [br] в плагинах включил два плагина parser_default 1.1 и parser_simple 2018.08.25 , но всё равно не работает. Хотя в версиях 102.7 обновлённых с 100 версии всё работает. 
Подскажите, пожалуйста, как исправить?

**Comment by Kotgo** [comment]
То есть на двух старых сайтах  обновленных до 102.7 всё работает, а на новом с версией 102.8 не работает.

**Comment by Kotgo** [comment]
Блин. Всё решил. Вопрос решён.

**Comment by Kotgo** [comment]
включяем два плагина parser_default 1.1 и parser_simple 2018.08.25
затем 
в **Редактирование записи**
пункт **Обработчик HTML**
включаем **Default**

Всё работает! :-)
