### ISSUE TITLE
Адаптивные колонки для стихов - как сделать адаптивные блоки рядом в Default шаблоне 

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#333]
Подскажите, пожалуйста, как оптимальнее сделать в Default шаблоне адаптивные колонки, чтобы стихи шли не текстом, а блоками рядом. То есть стих рядом с другим, а не переносился на новый абзац . И чтобы адаптивность дизайна не нарушалась.

**Comment by maxsite** [comment]
Колонки — это flex. См. UniCSS — там есть примеры.

**Comment by Kotgo** [comment]
Понял, спасибо!

**Comment by maxsite** [comment]
Тогда можно закрыть тикет. :)
