### ISSUE TITLE
Ключевые слова больше не используются

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#334]
Максим, подскажите, возможно ли оставить ключевые слова во всех версиях , для тех кому они нужны или уже этого сделать нельзя?

**Comment by maxsite** [comment]
Так они нигде не используются, польза от них = 0. Если нужно, то на уровне шаблона свои ini-опции. Код вывода я не резал, поэтому будет работать.

**Comment by Kotgo** [comment]
Хорошо, что не резали. Вдруг в алгоритмах поисковиков что-то изменится, да и старые ключи не хочется терять.

**Comment by maxsite** [comment]
Ничего там не изменится... Сейчас это просто лишняя сущность, никому не нужная.

**Comment by Kotgo** [comment]
Mail и Bing по ключам же проверяют тематику сайта?

**Comment by Kotgo** [comment]
> Если нужно, то на уровне шаблона свои ini-опции

Подскажите, пожалуйста, а где именно это правится?

**Comment by Kotgo** [comment]
Нашёл файл meta.ini вернул ключевые слова.
