### ISSUE TITLE
Что автоматически расставляет <p>?

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#335]
На одном сайте теги p для абзацев расставляются сами, что очень радует.
На другом сайте не хотят теги сами расставляться.
Что их расставляет?
Версия 101.
Плагин parser_default 1.0 включен и там и там.
parser_simple 2018.08.25 не включен ни там ни там.

**Comment by Filsadovnik** [comment]
Направление куда копать нашел: bb-код [br] не обрабатывается - на сайте так и выводится, несмотря на то что bb-код [p] обрабатывается нормально.
Похоже какой-то мой плагин не отдает дальше хук.
Но все равно интересно - где расставляет <p>.

**Comment by Filsadovnik** [comment]
Случайно закрыл обсуждение.

**Comment by maxsite** [comment]
Ну а у записи парсер текста выбран?

**Comment by Filsadovnik** [comment]
Конечно же нет. Теперь понятно.
Тут я попался в логическую ловушку.
Когда плагин _parser_default_ включен - в редакторе страницы автоматически подставляется **Обработчик HTML - default**.
Если изначально парсер выключен, то ничего не подставляется и потом, при включении парсера, 
в уже добавленные записи не добавляется **Обработчик HTML - default** понятно что не добавляется. Хоть сколько его включай.
А понять что _парсер_ и _обработчик_ - это одно и то же не удосужился.
И еще сбило с толку что [p] обрабатывается всегда, а [br] только если включен parser/обработчик.

**Comment by Filsadovnik** [comment]
2 обсуждения назад что-то подобное оказывается обсуждалось.

**Comment by Filsadovnik** [comment]
Предлагаю вынести поле Обработчик HTML в настройки редактора. Как сделан вывод изображения _Вывод изображения записи по умолчанию_. 
Чтобы можно было задать по умолчанию отсутствие парсера даже если плагин парсера включен.
Кроме дополнительного удобства можно акцентрировать внимание пользователя на особенности работы парсеров.

**Comment by maxsite** [comment]
Там есть это поле.
