### ISSUE TITLE
Обвновление 103 и ошибки

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#336]
Обновился до  версии 103 на одном сайте, появились заменяющие символы в конце текста 

> измен�[...]

Если не ошибаюсь то это вывод на главной в юнитах
```
read = <span class="icon0 i-angle-double-right mar10-l t-white bg-gray700 hover-bg-red pad15-rl" title="Читать дальше"></span>
read_start = [...]
```

Максим подскажите, пожалуйста, как убрать заменяющий символ. Там по идее должен быть пробел, так как где нет пробела, то нет заменяющего символа.

На сайте с версией 102.7 всё в порядке.

А ещё не исчезает уведомление о последней версии 103 на сайте, который обновлён до 103 версии.

**Comment by Kotgo** [comment]
Доплнение.
В версии PHP alt-php72  сайт работает хоршо.

В версии PHP  ea-php72 не работает вообще и в админке кучу ошибок выдает.

Значение alt-php72  и ea-php72 не нашёл в сети, но факт что в одной версии всё работает, а  в другой нет.

**Comment by Kotgo** [comment]
Поменял версию на PHP 7.1 (alt-php71) и заменяющие символы исчезли. У меня только такое?

**Comment by Kotgo** [comment]
У меня работает только на  PHP 7.1 (alt-php71)

**Comment by maxsite** [comment]
Я не знаю что такое alt-php. :(

**Comment by Kotgo** [comment]
В панели хостинга Cpanel  в Multi PHP manager  можно выбирать версию PHP и в списке есть такие версии.  Я тоже не нашёл подробную информацию об этом. Но у многих хостингов такое есть. Возможно это пакеты сборок PHP для мульти выбора версии.
А **заменяющие символы** � в конце текста появляются в версии PHP 7.2  **alt-php72** вместо символа точка.
В версии PHP 7.2 **ea-php72** сайт не работает, просто белый экран.
Сайт нормально функционирует только в версии PHP 7.1 (alt-php71).

**Comment by maxsite** [comment]
Единственное, что приходит в голову, что в ваших версиях PHP не включена (или не настроена) библиотека mbstrings. Поэтому обрезка utf-строк происходит некорректно.

**Comment by Kotgo** [comment]
Максим, благодарю за разъяснения, буду у хостинг консультанта уточнять и разбираться.
Да, вероятнее, это у них пакеты сборок PHP для мульти выбора.

**Comment by Kotgo** [comment]
Я вручную обновляю сайты, так как вносил изменения в плагин последних комментариев для немного другого отображения вывода комментариев, сам скрипт не трогал, только некоторые тэги удалил или заменил.

Сейчас на обоих сайтах версия 103, но почему-то в админ панели, слева вверху, отмечена версия 103, но зелёное уведомление о 103 версии не исчезает, как раньше.

**Comment by maxsite** [comment]
Ну вот вообще ничего не понятно...
