### ISSUE TITLE
BB-code image миниатюра

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#338]
![01,06,19(10-25-15)](https://user-images.githubusercontent.com/25066218/58745292-c8f48500-8457-11e9-9f8c-de8405b714b7.png)

Установил чистую систему 103 версии. Включил плагины bbcode, parser Simple и стандартный парсер. Редактор дефолтный. 
Собственно, проблема на скрине - не работает кликабельная миниатюра изображения, вместо неё текст вида [image=миниатюра]полное изображение[/image].

UPD: пока писал тикет, переклинило и вспомнил способ лечения. Совсем неочевидно то, что эта функция работает лишь при включенном плагине Lightbox, считаю, что стоит это указать в подсказке, иначе человек подумает, что движок нерабочий, либо второй вариант - сделать чтоб полная картинка открывалась в новом окне или новой вкладке браузера без включения плагина.

**Comment by maxsite** [comment]
Потому что код [image] реализован именно в плагине Lightbox. При желании его может реализовать и другой вместо этого, плагин.
