### ISSUE TITLE
Стал барахлить поиск

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#339]
![07,06,19(22-27-29)](https://user-images.githubusercontent.com/25066218/59128781-aee50600-8973-11e9-8b9e-5d7ba08f2672.png)

Работаю с движком на локальном сервере, вчера всё было идеально, но сегодня поиск стал странно себя вести. Например, на запрос "жених" он кидает на белую страницу с надписью 

> "Object not found!
> The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again. "

либо

> Object not found!
> 
> The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.
> 
> If you think this is a server error, please contact the webmaster. 

т.е. это даже не 404 страница движка.
В то же время по запросам "ж", "же", "жен", "жени" он работает правильно. С чем может быть связано, как починить?

upd: заметил, что проблема со всеми словами, где есть буква "х", но ещё вчера с этим проблем не было. Стал догадываться, что виноват не поиск, а защитная часть. Возможно, проблемы возникли из-за того, что я тестировал все редакторы на рабочесть.

**Comment by maxsite** [comment]
Сервер-то какой?

**Comment by Furnicarium** [comment]
![08,06,19(03-10-38)](https://user-images.githubusercontent.com/25066218/59139361-51fd4600-899b-11e9-9a46-d3e83f74b5fd.png)

такое. и вчера таким же был, когда всё работало.

**Comment by Furnicarium** [comment]
![08,06,19(03-26-59)](https://user-images.githubusercontent.com/25066218/59139695-722e0480-899d-11e9-9da7-866a6a6b1c50.png)

постепенно понижал конфигурацию, пока не заработало на версии Apache 2.2 и php 5.4
проблема устранилась, но причины такой странной поломки остались не ясны.

**Comment by maxsite** [comment]
Вроде бы уже обсуждалась эта проблема... Это из-за апача на виндовс. Русская буква «х» в адресе почему-то не корректно воспринимается из-за разных кодировок. У нас поиск как раз основан на get-запросах в адресе, поэтому вываливается ошибка. Решить можно только если менять регулярку в .htaccess, но это чревато другими проблемами. На реальном сервере (где линукс), такой проблемы нет.

**Comment by Furnicarium** [comment]
раз Шiпdoшs, то это многое объясняет. просто странно, что работало-работало и отвалилось. благодарю, закрываю тикет.
