### ISSUE TITLE
Encryption key больше не требуется при установке?

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#340]
Раньше при установке системы мы заполняли поле "ключ шифрования" (или же путаю с secret key), теперь же этого больше не делаем, потому что не спрашивается системой. 
Забыли, не нужно или же можно/нельзя?  т.е. не урезан ли уровень безопасности и защищённости?

**Comment by maxsite** [comment]
Он автоматом формируется в момент установки.
