### ISSUE TITLE
Помощь по юнитам

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#341]
![10,06,19(17-51-55)](https://user-images.githubusercontent.com/25066218/59204066-84c85980-8ba8-11e9-8dde-032fc2bde63e.png)

У меня проблема, я вчера целый день провозился с настройкой вида главной страницы через юниты, (работаю локально, windows) пока до меня не дошло, что подключаемые файлы это не php файлы, а на самом деле подставляются как **текст**. ок, в документации так и на писано, я видать невнимателен. Но документации явно не достаточно, у меня ни одним из способов, кроме приведённого в примере (var@title = Книги) не удалось задать и вывести переменную. Файлы в правильных папках, подключенный php-файл с текстом "var@rtitle = Материал" не передаёт переменную на главную страницу, и главная не может его взять из этого файла.  
- Где ещё можно прочесть про юниты, кроме как на одной странице в документации? 
- Точно ли в выделенном месте должно стоять слово "использованы"? Может "заданы"? если использованы, то как должен быть оформлен этот файл? Работает ли эта фукнция сейчас вообще? (передача/получение переменных из другого файла и какие правила задания (var @ $ или что вообще))
- По факту получается, что var это не меременная, а константа, она просто может быть использована в нескольких местах, а задана в 1 месте. 
- @USE_PHP@ - эту конструкцию я тоже где только не вставлял, не получилось из результата работы php кода получить переменную.. 
----
чего я конкретно хотел добиться - чтоб заголовок (у моих постов он пустой) заменялся на одно из слов, которые есть в массиве. слово получается рандомно из массива значений и подставляется в переменную. Я её смог применить, лишь отредактировав файл units/last-pages.php, но в этом случае все заголовки приобретают одно и то же значение, при обновлении  страницы - другое, а мне нужен рандом. Какой файл отвечает за **цикл** вывода постов на главной?  

upd: так, действительно, нашёл файл, который отвечает за вывод постов в настоящем цикле. это **type-for-each/my-template/page-header-only.php**, но он не взаимодействует с юнитами. мне надо, чтоб юниты брали откуда-то непустой заголовок.. или чтоб редактор поста генерировал заголовок..

**Comment by Furnicarium** [comment]
в общем, ладно, отбой, я нашёл решение путём правки page-out.php, но таким образом я лишился вообще всех настоящих заголовков на сайте, а хотел только на главной..

**Comment by maxsite** [comment]
Есть var-переменные, есть php-переменные. При чем тут цикл вывода, случайный заголовок — всё в куче, понять что именно нужно нереально. :(

**Comment by Furnicarium** [comment]
ладно, забей.
просто в руководстве говорится про var@ переменные и даются примеры по прикреплению php файла и меня это сбило с толку, я пытался задать $ - такого вида php переменную.
