### ISSUE TITLE
Список комментаторов там, где не нужен

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#342]
![11,06,19(08-38-22)](https://user-images.githubusercontent.com/25066218/59246212-56885f80-8c24-11e9-8b26-28862a27ce96.png)

кажется, я нашёл хвост. предположим, я не могу залогиниться, и нажимаю "восстановление пароля", а мне в придачу выдаётся ссылка на всех комментаторов, которая мне в данный момент не нужна.

**Comment by maxsite** [comment]
В чём здесь проблема?

**Comment by Furnicarium** [comment]
в логике. почему именно список комментаторов на странице восстановления пароля?
почему он именно тут?

**Comment by maxsite** [comment]
Если комюзер перешел к восстановлению пароля, то он забыл кто такой. Возможно список комментаторов ему поможет.
