### ISSUE TITLE
Предлагаю доработать файл _next-prev.php и поиск

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#343]
Предлагаю включить проверку на наличие заголовка у соседней записи, потому что если заголовка нет, то и ссылки на следующую запись нет, а лучше бы было что-то вроде "Без заголовка". 
В результатах поиска то же самое. Поиск выдал результат по искомому слову, а оно находится в посте, у которого отсутствует заголовок и перейти к результату невозможно. 
Не для себя прошу, а для тех, кто будет щупать движок в будущем, они сделают пост без заголовка, т.к. система это позволяет, а потом будут говорить, что ничего не работает, ни стрелочки, ни поиск.

**Comment by maxsite** [comment]
Нужно подумать.

**Comment by Furnicarium** [comment]
если делать это, то и в списке последних комментариев, это файл shared-type-comments-comment.php
там тоже если у записи нет заголовка, то будет пустое поле и невозможно попасть на страницу записи.
Наверное, такая же ситуация и там, где выводятся все комментарии комюзера и все посты автора.. пока что не дошёл до этого этапа.

**Comment by Furnicarium** [comment]
и карта сайта не позволяет перейти к нужной записи, если у неё нет заголовка.

**Comment by maxsite** [comment]
Я посмотрел, получаются сложности. Записи получаются стандартно, поэтому выводятся ровно так, как и задумал автор: без заголовка, значит без заголовка. Поэтому замены пустых заголовков можно сделать только на уровне конечного вывода. Но там лишний код появляется, который просто не нужен 99% пользователей, которые как положено ставят заголовок записи. Поэтому оставим как есть.

**Comment by Furnicarium** [comment]
ок, не проблема, спасибо
