### ISSUE TITLE
Надо разбить шапку

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#344]
Думаю, что шапку стоит разделить и выполнить в виде нескольких компонентов, которые подключаются-отключаются через админку.
На данный момент шапка это просто файл top-1, в котором лежит всё в куче - 
- логотип и девиз сайта
- обычное меню (главная, комментарии, форма связи) (не точно)
- выпадающее (вроде) меню, которое прилипает к верхней части страницы при прокрутке вниз
- хлебные крошки  и ПОИСК всё вместе
- КОРЗИНА, работа над которой ещё не завершена.
---
Зачем это нужно? 
- ну допустим мне поиск не нужен или я хочу его вывести в другом месте (футер) или прям рядом с лого.
- допустим, я лого хочу в футере выводить
- допустим, мне не надо два меню, одно из них я хочу выключить или перенести опять в футер
- допустим, у меня нет категорий на сайте, а поиск я хочу оставить вверху. сегодня надо выбирать, либо хлебные крошки (которые при одной категории "новости" мне не нужны, т.к. становятся безсмысленными) + поиск в довесок, либо ничего, да ещё и лого удалится при выключении компонента top1.
-------
В общем, чтоб легко настроить сайт и решить все эти проблемы, каждую отдельную функцию предлагаю вынести в компонент. 
---
Опять же, не для себя прошу, я-то отредактировал код (хотя если учесть затраты времени, то это ощутимо дольше, чем настройка через админку того же футера, где всё легко и отдельно), но представьте новичка, он установит систему, решит, что настроил её, увидит неработающую корзину, не поймёт, как отдельно отключить логотип или второе меню, не станет разбираться и сделает вывод, что движок ничего не умеет и никуда не годится, это нежелательная ситуация.

**Comment by maxsite** [comment]
Ну когда-то так и было — куча разных компонентов, которые можно было произвольным образом указывать в настройке шаблона. Сложность в том, что хоть компоненты получаются разные и необходимо обеспечить между ними нормальное отображение. Например у какого-то компонента есть верхний отступ. Но если его переставит в другое положение, то этот отступ уже нужно убирать или менять. Чем больше таких факторов, тем сложнее верстка и возникает много нюансов.

Поэтому я использую другой подход — компонент один, а управление его внутренними блоками реализуется с помощью его же опций. Второй подход — если пользователю нужно изменить стандартный компонент, то делается его копия и в ней нужные правки. Это проще и быстрей, чем заниматься «подгонкой» отдельных компонентов.
