### ISSUE TITLE
Вопрос по Font Awesome 5

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#345]
https://github.com/maxsite/cms/issues/14 этот тикет про обновление с 3 до 4 я прочёл, с тех пор прошло уже 4 года и они добавили кучу других значков благодаря проекту на кикстартере и выпустили уже 5 версию, где 1534 бесплатные иконки. если платно, то почти 4000. 
Мне нужны новые значки, что делать, чтоб на сайте можно было использовать новые значки?
Я увидел связку с файлом шрифта и файлом 2-awesome.css, но открываю его, а там в скобках одни знаки вопроса и не пойму, как добавить **хотя бы один** новый значок.

**Comment by maxsite** [comment]
В FA 5 сильно поменяли структуру файлов стилей, шрифты разбили на несколько файлов, увеличили объем. Поэтому дали одной иконки грузить лишние 200кБ, я решил не стоит. Есл нужный свои иконки, то в Сети есть сайты, где можно сделать свой набор иконок и подключить отдельным файлом.

**Comment by Furnicarium** [comment]
понятно, не знал, что они всё так усложнили. спасибо.
