### ISSUE TITLE
Автоизменение короткой ссылки

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#349]
![18,06,19(02-45-39)](https://user-images.githubusercontent.com/25066218/59643913-4ff16f00-9173-11e9-92be-beb341e1bb85.png)

Вопрос: как средстами настроек системы или плагинов к ней сделать так, чтобы при обновлении заголовка и сохранении статьи автоматически менялась короткая ссылка к ней?
Кажется, где-то видел сочетание слов "замена коротких ссылок", но через поиск не смог найти нигде, помогите советом.

**Comment by Furnicarium** [comment]
пытался найти решение в файле functions-edit.php, менял значения с false на true, но это не помогло, затем я заметил такой момент и хочу поинтересоваться - а это правильно? не должно ли != быть вне одинарных кавычек? 

![18,06,19(03-06-46)](https://user-images.githubusercontent.com/25066218/59644644-78c73380-9176-11e9-8122-fc9dc79eb71f.png)

**Comment by maxsite** [comment]
Просто очистите это поле, оно автоматом сформируется.

**Comment by Furnicarium** [comment]
блин, благодарен.
