### ISSUE TITLE
Кастомизация текстов всех емайл-сообщений

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#35]
Надо сделать так, чтобы можно было настраивать тексты стандартных емайл-уведомлений. Также, возможно, имеет смысл реализовать пропускание этих текстов через спейциальный хук (хуки?) перед отправкой писем.

**Comment by maxsite** [comment]
Оптимально, конечно, это сделать отдельную опцию, где можно задать произвольный текст шаблона. 

— В секции Email-адреса admin\plugins\admin_options\general.ini добавить новые textarea опции 

template_email_message_new_comment — будет использоваться как шаблон в email_message_new_comment()

template_email_message_new_comuser — в mso_email_message_new_comuser() 

Еще есть mso_email_message_new_comment_subscribe(), но я не уверен, что для него нужен шаблон письма.

— Текст шаблона использовать стандартный как сейчас, для замен используем аля-bb-код
[NAME_SITE] — это getinfo('name_site')
[SITE_URL] — getinfo('site_url')
и т.д.

Вы или кто-то еще зарегистрировал ваш адрес на сайте [NAME_SITE]  — [SITE_URL]  и т.д.

Илья, если будешь делать, то посмотри но новый плагин last_pages — там как раз подобная задача по заменам решается. Вначале получаем все переменные, а после через str_replace их заменяем. На выходе — готовый текст.

**Comment by vimruler** [comment]
Хорошо, Максим. Беру задачу на себя. Рекомендации понял. Будут вопросы - напишу.

**Comment by cuprum** [comment]
@vimruler Еще будет просьба. Не присылать уведомление на ящик админа, когда сам админ оставляет комментарий.

**Comment by dignityinside** [comment]
@cuprum согласен!

**Comment by vimruler** [comment]
> Не присылать уведомление на ящик админа, когда сам админ оставляет комментарий.

Юра, я правильно понимаю, что этот функционал должен быть опциональным?

**Comment by cuprum** [comment]
@vimruler Думаю, можно и опцией, но уже предустановленной - чекбокс отмечен.

**Comment by vimruler** [comment]
@maxsite, начал реализацию и возникло несколько вопросов. Вот шаблон уведомлений (по поводу нового камента), который получается:
```
Новый комментарий на "[PAGE_TITLE]"
[SITE_URL]page/[PAGE_SLUG]#comment-[COMMENT_ID]

Автор IP: [IP]
Referer: [REFERER]
Дата: [DATE]
[COMUSER]
Комюзер: id=[COMUSER_ID], ник: [COMUSER_NIK], email: [COMUSER_EMAIL]
Профиль: [SITE_URL]users/[COMUSER_ID]
[/COMUSER]
[ANONIM]
Аноним: [ANONIM_NAME]
[/ANONIM]

Текст: 
[COMMENT_TEXT]

Администрировать комментарий вы можете по ссылке:
[SITE_URL]admin/comments/edit/[COMMENT_ID]
```

1. **Как поступим с адресами страниц?** Будем вводить общие псевдо-коды (типа [PAGE_URL], [COMMENT_EDIT_URL]) или пусть вебмастер сам составляет нужный урл из имеющихся фрагментов (сейчас [SITE_URL], [PAGE_SLUG])? Второй вариант мне видится более гибким, но всё же нужно определиться.

2. **Как поступим с альтернативными вариантами внутри шаблона?** В частности, у нас есть блок, который по разному отображается для комюзера и для анонима. Сейчас в примере шаблона я ввел возможность указать по отдельности код для вывода только комюзеру ([COMUSER][/COMUSER]) и отдельно только для анонима ([ANONIM][/ANONIM]). Может нужно иначе реализовать?

3. После появления [шаблонизатора](https://github.com/maxsite/cms/issues/46) встал вопрос - может всё сделать через него?

**Comment by maxsite** [comment]
Вот это ``` [SITE_URL]page/[PAGE_SLUG]#comment-[COMMENT_ID] ``` меняется на ```[COMMENT_URL]```

Это ``` [SITE_URL]admin/comments/edit/[COMMENT_ID]``` на ``` [EDIT_LINK] ```

Это ```[SITE_URL]users/[COMUSER_ID]``` на ``` [COMUSER_URL] ```

То есть не нужно делать такие сложные конструкци. Заранее подготовить готовые переменные и их использовать.

> После появления шаблонизатора встал вопрос - может всё сделать через него?

Именно так и нужно сделать. :)

**Comment by vimruler** [comment]
> Именно так и нужно сделать. :)

Насколько я понимаю, в этом случае нет нужды внедрять псевдокоды. Так? Т.е. нужно просто сделать подключение шаблона при его наличии или оставить старую логику формирования письма.

**Comment by maxsite** [comment]
Немного не так. В функции формируются все переменные ( например {{ $comment_url }} ). После получается шаблон письма из опции (её тоже нужно добавить). Если опции нет (или пустая), то используем свой типовой вариант. Берем шаблон, пропускаем через mso_tmpl_prepare() и выполняем его через eval();

В конце common.php добавь пока недостающую функцию mso_tmpl_prepare().

```php
function mso_tmpl_prepare($template, $replace = true)
{
	$template = '?>' . str_replace(array('{{', '}}', '{%', '%}'), array('<?=', '?>', '<?php', '?>'), $template);
		
	if ($replace)
		$template = str_replace(array("\t", "\r", "\n\n"), array("", "", "\n"), $template);
	
	return $template;
}

```

**Comment by vimruler** [comment]
> Берем шаблон, пропускаем через mso_tmpl_prepare() и выполняем его через eval();

Берём как? Функцией mso_tmpl_ts?

```php
if ($template = mso_tmpl_ts('type/_def_out/emails/email-message-new-comment-tmpl.php'))
{
	eval($template);
}
```

Если так, то зачем нужна **mso_tmpl_prepare** если те же самые действия выполняются в рамках mso_tmpl?

Второй вопрос: **type/_def_out/emails/email-message-new-comment-tmpl.php** - куда класть шаблон письма? 

И ещё вопрос: **eval** будет исполнять код шаблона, но нам же нужно получить строковую переменную для передачи в **mso_mail** - значит нужно оборачивать в код буферизации вывода?

Ну и так и не понял - что делать с псевдокодами? Через опции должен задаваться шаблон с псевдо-кодами или они не нужны и в опциях шаблон для шаблонизатора( с обращением к переменным {{ $comment_url }} )?

**Comment by maxsite** [comment]
Илья, ты всё напутал. Шаблон письма будет в виде опции в админке. Никакого отдельного файла не нужно. Поэтому в функциях (email_message_new_comment) получается эта опция уже как html-шаблон. И он прогоняется через  mso_tmpl_prepare(), которая принимает не файл, а текст шаблона.

1. Создаем опцию. Выше уже написал как.
2. В функциях  email_message_new_comment и т.п. получаем эту опцию.
3. Подготавливаем все переменные для полученного шаблона. 
4. Прогоняем шаблон через mso_tmpl_prepare. Функция делает из шаблона готовый php-код.
5. Выполняем этот код через eval(), предварительно включив буферизацию.
6. Результат в $message, которая скармливается в mso_mail

**Comment by vimruler** [comment]
@maxsite, спасибо, что пояснил. Теперь более-менее понятно. Такой вопрос возник: если в опциях админом будет задана пустота, то как поступать? не отправлять уведомление или подставлять шаблон по-умолчанию (хотя он будет продублирован в general.ini)?

**Comment by maxsite** [comment]
Думаю, что лучше использовать шаблон по-умолчанию. Он будет продублирован в функции и в ini-файле.

**Comment by vimruler** [comment]
Внутри функции **mso_email_message_new_comment** получился примерно такой код:

```php
...
	// шаблон уведомления
	$template = mso_get_option('template_email_message_new_comment', 'general', 'Новый комментарий на "{{ $page_title }}"'.NR.'{{ $comment_url }}'.NR2.'Автор IP: {{ $comment_ip }}'.NR.'Referer: {{ $comment_referer }}'.NR.'Дата: {{ $comment_date }}'.NR.'{% if (isset($user_id)) { %}Пользователь :{{ $user_id }}'.NR.'{% } elseif (isset($comuser_id)) { %}Комюзер: id={{ $comuser_id }}, ник: {{ $comuser_nik }}, email: {{ $comuser_email }}'.NR.'Профиль: {{ $comuser_url }}'.NR.'{% } elseif (isset($anonim)) { %}Аноним : {{ $anonim }}'.NR.'{% } %}'.NR.'Текст: '.NR.'{{ $comment_content }}'.NR2.'Администрировать комментарий вы можете по ссылке:'.NR.'{{ $edit_link }}'.NR);
		
	$comment_url = mso_get_permalink_page($data['comments_page_id'])  . '#comment-' . $id;
		
	$comments_approved = $data['comments_approved'];
		
	$comment_ip = $data['comments_author_ip'];	
		
	$comment_referer = $_SERVER['HTTP_REFERER'];
		
	$comment_date = $data['comments_date'];
		
	if (isset($data['comments_users_id']))
	{
		$user_id = $data['comments_users_id'];
	}
	elseif (isset($data['comments_comusers_id']))
	{
		$comuser_id = $data['comments_comusers_id'];
		
		$CI->db->select('comusers_nik, comusers_email');
		$CI->db->from('comusers');
		$CI->db->where('comusers_id', $data['comments_comusers_id']);

		$query = $CI->db->get();

		if ($query->num_rows() > 0)
		{
			$comusers = $query->row();
			
			$comuser_nik = $comusers->comusers_nik;
			$comuser_email = $comusers->comusers_email;
			$comuser_url = getinfo('siteurl') . 'users/' . $data['comments_comusers_id'];
		}
	}
	elseif (isset($data['comments_author_name']))
	{
		$anonim = $data['comments_author_name'];
	}
		
	$comment_content = $data['comments_content'];
		
	$edit_link = getinfo('site_admin_url') . 'comments/edit/' . $id;
		
	$template = mso_tmpl_prepare($template);
	ob_start();
	eval( $template );
	$text = ob_get_contents();	ob_end_clean();

	$data = array_merge($data, array('comment' => true));      //Чтобы плагин smtp_mail точно знал, что ему подсунули коммент, а не вычислял это по subject
	return mso_mail($email, $subject, $text, $false, $data);   //А зная о комментарии, он сможет сотворить некоторые бонусы.
```
Опция описывается так:

```ini
[Шаблон уведомления администратору о новом комментарии]
options_key = template_email_message_new_comment
options_type = general
type = textarea
rows = 12
description = "Задайте шаблон письма администратору с уведомлением о новом комментарии. Доступны псевдокоды: "
default = "Новый комментарий на _QUOT_{{ $page_title }}_QUOT__NR_{{ $comment_url }}_NR__NR_{% if ($comments_approved == 0) { %}Комментарий требует модерации:_NR_{{ $edit_link}}{% } %}_NR__NR_Автор IP: {{ $comment_ip }}_NR_Referer: {{ $comment_referer }}_NR_Дата: {{ $comment_date }}_NR_{% if (isset($user_id)) { %}Пользователь :{{ $user_id }}_NR_{% } elseif (isset($comuser_id)) { %}Комюзер: id={{ $comuser_id }}, ник: {{ $comuser_nik }}, email: {{ $comuser_email }}_NR_Профиль: {{ $comuser_url }}_NR_{% } elseif (isset($anonim)) { %}Аноним : {{ $anonim }}_NR_{% } %}_NR_Текст: _NR_{{ $comment_content }}_NR__NR_Администрировать комментарий вы можете по ссылке:_NR_{{ $edit_link }}_NR_"

```
@maxsite, описание шаблона такое должно было быть? Код вроде работает. Но смущает то, что переносы строк съедаются (особенно, для варианта по-умолчанию, когда опция не сохранена). Можешь по сниппету сказать что ещё поправить или всё таки прислать весь код на почту?

**Comment by maxsite** [comment]
В mso_get_option не нужно делать строчку с NR. Лучше так:

```php
$def_option = '
Новый комментарий на "{{ $page_title }}"'
{{ $comment_url }}
и т.д.
';
```
И эту переменную уже подсунуть mso_get_option.
