### ISSUE TITLE
Сброс кеша по ключу

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#350]
Добавляю кеш по ключу:
```
$my_array` = 'custom_1';
mso_add_cache($cache_key, $my_array);
```
Потом пытаюсь сбросить по маске (зачем сбрасывать кеш всего сайта, если конкретная совокупность информации модифицируется):
`mso_flush_cache_mask( 'custom');`
Не сбрасывается кеш локально по части ключа.
Смотрим как реализовано.
В функции _function mso_add_cache_ мы конструируем имя файла кеша, используя **mso_md5**:
`$cache_path .= mso_md5($key . $CI->config->item('base_url'));`
В функции же _mso_flush_cache_mask_ мы используем конструкцию без **mso_md5**:
`$pos = strpos($file, $mask);`
Толи слишком жарко, но, что-то тут не так.

**Comment by maxsite** [comment]
У mso_add_cache() есть параметр $custom_fn которым можно указать имя файла без кодирования.

**Comment by Filsadovnik** [comment]
Думал это какая-то кустомная функция передается, а это файлнейм. Понятно.
