### ISSUE TITLE
Редактирование только своих комментариев

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#351]
Обнаружил, что комюзеры не могут отредактировать свою анкету. Закрытый тикет от 2017 года по этому вопросу тоже апнул. (7.1 php)
Обнаружилось, что комюзер не может редактировать свои комментарии. Ок, могу перевести его в группу авторов (users) и дать админ-доступ к редактированию комментариев, но тогда он получает возможность удалить вообще все комментарии, даже чужие.
Известна ли эта проблема и реально ли сделать разграничение на право доступа к комментариям такое же, какое уже есть по вопросу редактирования постов?

**Comment by maxsite** [comment]
Не нужно старые тикеты открывать. Лучше новый сделать.

Что в логах ошибок? Как именно проявляется ошибка?

**Comment by Furnicarium** [comment]
никаких ошибок не появляется, просто обновляется страница и ничего не меняется. Смотрел какие-то логи, в первую очередь вываливается ошибка о том, что не подгружаются картинки, больше ничего не заметил. 
`2019/06/25 07:59:21 [error] 6536#2596: *1 CreateFile()`
и действительно, не отображаются лого и картинка из футера, наверное, с http/s связано, ещё понаблюдаю.

**Comment by maxsite** [comment]
Как воспроизвести проблему?

**Comment by Furnicarium** [comment]
если мы говорим о том, что комюзер не может отредактировать свой профиль, то чтобы это воспроизвести, нужно зарегистрироваться на сайте как комюзер (ну а по-другому нельзя) и попытаться изменить аватарку или заполнить инфорацию о себе. ничего не сохраняется.

**Comment by maxsite** [comment]
Ну вот я проверяю, всё работает.

**Comment by Furnicarium** [comment]
у меня и локально та же проблема была, нужно либо подтверждение от других пользователей (версия движка 103), либо самому установить всё заново, но это того не стоит, не такая критичная проблема, всё равно в интернете больше не регистрируются и не оставляют комментариев.
