### ISSUE TITLE
Добавить возможность клонировать записи

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#352]
Максим, привет!

Давно хотел спросить - а нет ли в планах добавить функцию клонирования записей? На мой взгляд было бы очень полезно, ибо часто приходится создавать однотипные записи и утомляет необходимость вручную выставлять значения мета-полей, рубрик, тайтлов (однотипных) и т.п. параметров. Если можно было бы клонировать, то работа по созданию новой записи сводилась бы только к правке нужных значений и контента.

**Comment by maxsite** [comment]
Привет, Илья! Можно через AutoPost сохранить запись в текст, после поправить новый заголовок и дальше загрузить. Будет новая запись.

**Comment by vimruler** [comment]
Да, я знаю про такой вариант. В целом, он рабочий. Просто много лишних телодвижений приходится делать :-) Так то, можно плагин запилить, который кнопку клонирования реализует, просто хотел уточнить, чтобы не делать двойной работы, если руки дойдут :-)

**Comment by maxsite** [comment]
С клоном сложно, все равно придется делать новый заголовок. Мне приходилось делать много копий записей, но через AutoPost самое простое, потому что достаточно подготовить файлы, а потом одним махом закинуть. С файлами по любому проще и быстрей работать, чем в админке через браузер. Последний раз так делал, записей 200 или 300 было. :-)

**Comment by vimruler** [comment]
Эх, когда надо разово клонировать кучу записей - AutoPost шикарен! Был такой опыт. Но сейчас я больше о случаях, когда надо в разные случайные даты создать один клон конкретного поста. В таких случаях явно избыточно лезть в дебри AutoPost...

Про заголовок - понимаю, что надо менять, да и короткий адрес. Но тут, на мой взгляд, достаточно тоже же алгоритма, по которому не допускается дублирование коротких адресов - т.е. циферку добавить в конец. Ну и клона надо в черновике сохранять, само собой.

**Comment by maxsite** [comment]
Ну да, согласен, можно и так. Пока такой задачи не стоит, наверное лучше отдельным плагином сделать — простой список записей, отметил нужную, нажал «Сделать клон» и дальше перекидывает на редактирование (или сюда же).
