### ISSUE TITLE
Тег SHOW. Что за него отвечает?

### ISSUE THREAD

**Issue by Anchovys** [maxsite/cms#353]
Приветствую. 
Что за плагин или раздел системы отвечает за тег [show] [/show]?
Могу ошибаться, но по моему за него отвечал плагин, а в списке плагинов не могу его найти. Почему-то стали появляться с ним проблемы. 
В данном случае, проблема проявляется в том, что все списки 'развернуты', а при нажатии на ссылку появляется якорь # и кидает кверху страницы. Ошибок в инспекторе - нет. Его аналог - плагин spoiler - работает без всяких проблем. Раньше вроде все работало отлично

**Comment by maxsite** [comment]
Это плагин bbcode.

```
[show Заголовок]
текст 
[/show]
```

**Comment by Anchovys** [comment]
Хорошо, понял. Обновлю систему, заменив файлы на новые и посмотрю что из этого выйдет.
