### ISSUE TITLE
Не нужные мне строки в таблице meta

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#354]
что заметил: допустим, я глобально определил настройки для всего сайта, чтоб нигде не показывались изображения записи, чтоб под записью не выводились похожие материалы и что парсер записей Default. Я так решил навсегда и не собираюсь передумывать, допустим.
Но теперь я создаю запись и в таблицу прописывается 3 лишние строки, которые, на мой взгляд, уже не нужны. таким образом, у меня таблица раздувается в 2-4 раза, зависит от количества тегов.

![01,07,19(13-29-10)](https://user-images.githubusercontent.com/25066218/60430286-9af49300-9c05-11e9-86e8-965e02cdb5c3.png)

Я знаю, как сильно ты не любишь раздутые таблицы Вордпресса, поэтому вопрос - можно ли отключить создание этих трёх строк на основании настроек? Я знаю, что их можно и удалять время от времени, но зачем лишние движения, если вдруг это можно где-то отключить.

**Comment by maxsite** [comment]
Записи получаются только если они определены в ini-файле (meta). В данном примере, как раз наоборот, лучше эти данные сохранять, поскольку выборка их из базу быстрее, чем проверять каждый раз дефолтное значение.

**Comment by Furnicarium** [comment]
а, ясно. благодарю)
