### ISSUE TITLE
Редактирование футера из админки

### ISSUE THREAD

**Issue by Furnicarium** [maxsite/cms#355]
![02,07,19(04-06-25)](https://user-images.githubusercontent.com/25066218/60477938-8a85fc00-9c89-11e9-9a5f-62792dbe6640.png)

Проблема: Если отредактировать файл footer-copy-stat из админки, то переменные, отвечающие за вывод времени и потребление памяти, приобретают текстовое постоянное значение. Количество же запросов так и остаётся переменной.  Пришлось доставать оригинал файла, чтоб узнать, что там были за переменные, т.к. файл на фтп перезаписался. Надо либо запретить править этот файл из админки, либо предупредить, что там должно стоять, либо по-другому выполнить вывод.
1. не для себя прошу, я-то разобрался, а для новичков, которые сломают футер и будут потом говорить, что движок плохо работает, т.к. неправильно показывает отчёт о генерации страницы.
2. Стоит проверить и остальные файлы, которые при редактировании из админки могут сломаться. 
--
Если такое поведение не задумано, то подозреваю, что это результат работы плагина глобального кэширования, больше ничего предположить не могу.

**Comment by maxsite** [comment]
Думаю, что если новичок решил править php-файл, то он уже понимает что делает. Файл очень простой и если например не менять php-часть, то проблем не будет. Другое дело, что файл будет постоянно затираться при обновлении, поэтому нужно либо сделать копию компонента, либо копию шаблона, где править уже что угодно.
