### ISSUE TITLE
Ошибка создания страницы

### ISSUE THREAD

**Issue by Anchovys** [maxsite/cms#356]
Приветствую! Собрался переезжать на VDS и при тестировании системы обнаружил, что запись отказывается добавляться. По каким причинам вообще выдается это сообщение и где копать? Подозрение на настройки Mysql, но может есть какие-то другие подноготные?

**Comment by Anchovys** [comment]
Исправил самостоятельно. Выполнил SQL запрос такого рода 
 ```
SET GLOBAL sql_mode = 'modes';
```
Затем перезагрузил все это дело так:

```
/etc/init.d/mysql restart
```

Вроде бы работает :) Подсмотрел [тут](https://ru.stackoverflow.com/questions/805322/%D0%9E%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%B8%D0%B9-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC).

**Comment by Anchovys** [comment]
Единственный вопрос: можно ли внести правки в систему так, чтобы не пришлось ковыряться в настройках Mysql и т.д.  Поскольку я думаю что эта проблема будет охватывать не малое число людей. К примеру, я устанавливал самый обычный mysql, командой apt install mysql-server. Он подтянулся естественно, самой последней версии и там по видимому включен 'Строгий режим', который и вызывает эту проблему. (насколько я понимаю)

**Comment by maxsite** [comment]
Не думаю, что MaxSite CMS должна отвечать за настройку MySQL.

**Comment by Anchovys** [comment]
Кстати, какие модули для apache и php необходимы для нормальной работы системы? Не может же быть такого, что ей нужен только mbstring?

**Comment by maxsite** [comment]
Всё остальное стандартно.

**Comment by Anchovys** [comment]
Тут проблема возникла, которая меня вводит в ступор. В общем есть система, накатанная с демо-статьями. Шаблон Default, все по стандарт (только поставил). 

Сразу после установки, на главной - пустота (белый экран).
Если глянуть код страницы, где белый экран, то вижу одну строку:
`<div class="bg-gray800 pad20 mar30-b t-white bor3 bor-solid-b bor-red">`, и все, больше ничего.
Перехожу в админку, админка работает исправно, ошибок нигде нет.
Дальше. Статьи частично отображаются. Некоторые просто текст на белом фоне 
![image](https://user-images.githubusercontent.com/25356773/60986722-8462e000-a359-11e9-841f-d3bb26f14577.png)

Некоторые отображаются нормально.

**Comment by Anchovys** [comment]
По логам нашел, что проблема в Fatal error: Call to undefined function: imagecreate()
Как уж она сильно завязана на работе движка?)
Поставил в общем пакет `php7.2-gd`, и права на /var/www/html поставил 755, пока работает.

**Comment by maxsite** [comment]
Смотрите логи, настраивайте сервер.

**Comment by Anchovys** [comment]
В общем, возвращаясь к вопросу о "Ошибке создания страницы", расскажу как ее исправить (для тех, у кого вдруг такая- же ошибка).

Стандартным изменением sql_mode через SQL запрос тут не обойтись (настройки будут сбрасываться при каждой перезагрузки ОС).

Для решения вопроса нужно в файле `/etc/mysql/mysql.cnf`, в конец файла прописать две таких строчки:
```
[mysqld]
sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
```

А потом перезагружаем сервер и смотрим..
Надеюсь для кого-то будет полезно)
