### ISSUE TITLE
_update_mso a non well formed numeric value encountered in pclzip.lib.php

### ISSUE THREAD

**Issue by v0vas** [maxsite/cms#357]
При обновлении появилось такое предупреждение:

> Последняя версия MaxSite CMS: 103
> Ваша версия MaxSite CMS: 101
> Обновление...

`Notice: A non well formed numeric value encountered in /home/data/www/site/_update_mso/pclzip.lib.php on line 1845 Call Stack: 0.0016 450048 1. {main}() /home/data/www/site/_update_mso/index.php:0 3.3575 1114288 2. PclZip->extract() /home/data/www/site/_update_mso/index.php:51 3.3576 1114744 3. PclZip->privOptionDefaultThreshold() /home/data/www/site/_update_mso/pclzip.lib.php:801 Unzip master.zip OK!`
> Перейти к сайту
> Новая версия MaxSite CMS: 103
> Готово! Не забудьте оставить своё мнение в твиттере о MaxSite CMS!

Сайт вроде работает нормально, но не знаю корректно ли отработала программа по обновлению.
Версия PHP 7.3.7

**Comment by maxsite** [comment]
См. http://max-3000.com/page/maxsite-cms-101
