### ISSUE TITLE
Время последнего удачного сохранения в админке.

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#359]
Когда-то вроде было время.
Сейчас появляется и исчезает надпись "Сохранено".
Вот бы чтобы отображалось время последнего сохранения.
А то - нажал сохранить, переключился, обратно - и не ясно: сохранено или нет.

**Comment by maxsite** [comment]
Время есть только у быстрого сохранения.

**Comment by Filsadovnik** [comment]
Речь и идет о работе кнопки "Сохранить в фоне".
При ее нажатии появляется надпись "сохранение" а потом кратковременно "Запись сохранена".
И все, спустя секунды уже не ясно - сохранена ли запись или ее невозможно сохранить из-за потери соединения.
Если бы надпись "Запись сохранена!" исчезала только только при нажатии кнопки "Сохранить в фоне", а после сохранения висела бы постоянно.
Или обновлялась бы надпись о времени последнего сохранения.
У меня версия 101 - может в новых версиях уже по другому.

**Comment by maxsite** [comment]
Быстрое сохранение — это Ctrl+S, а фоновое это тоже что и обычное, только в фоне. Там нет времени.
