### ISSUE TITLE
Переход с HTTP на HTTPS - правильно

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#361]
Подскажите, пожалуйста, правильный код для .htaccess ,
чтобы правильно настроить полный редирект с HTTP на HTTPS  всех страниц и домена, а также с www на домен c HTTPS на MaxsiteCMS.

**Comment by maxsite** [comment]
Это зависит от сервера. Но в целом, поищите в гугле, там полно примеров.

**Comment by Kotgo** [comment]
Максим, да, примеров много, а ваш рабочий вариант можете показать?

**Comment by maxsite** [comment]
Я не использую https. Ищите в гугле или уточняйте у своего хостера.

**Comment by Kmartynov** [comment]
@Kotgo Попробуйте следующий вариант
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
            
Options +FollowSymLinks
Options -Indexes
DirectoryIndex index.php index.html
AddDefaultCharset UTF-8

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?$1 [L,QSA]
</IfModule>

**Comment by Kotgo** [comment]
> 
 Kmartynov , благодарю вас за вариант, попробую.

**Comment by maxsite** [comment]
Добавлю в дистрибутив такой вариант. Должен подходить под большинство хостингов.

```
<IfModule mod_rewrite.c>
RewriteEngine on

# for 301-redirect http to https
RewriteCond %{HTTPS} !=on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,QSA,L] 

RewriteBase /
RewriteCond $1 !^(index\.php|uploads|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L,QSA] 
</IfModule>
```
