### ISSUE TITLE
Админка, пагинация, долгая обработка

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#362]
Максим, привет!

Обновляю сайт, у которого в базе около 76000 записей. Движок стоял 0.853. Поставил рядом 103.1, скопировал старую базу и начал постепенное обновление шаблона, плагинов и т.д. И вот в какой-то момент сунулся в раздел админки "Все записи" (без фильтров, именно все записи) и страница не открылась. Задумалась надолго. На старой копии сайта этот раздел открывался нормально.

Может зря, но полез искать что вешает. Поиски привели в функцию _mso_sql_build_home файла \application\maxsite\common\page.php в место, где идёт вычисление параметров пагинации (строка 630 в новой версии). Вывел зависающий запрос. Получил это:

> SELECT mso_page.`page_id`
FROM (`mso_page`)
JOIN `mso_page_type` ON `mso_page_type`.`page_type_id` = `mso_page`.`page_type_id`
LEFT JOIN `mso_cat2obj` ON `mso_cat2obj`.`page_id` = `mso_page`.`page_id`
LEFT JOIN `mso_category` ON `mso_cat2obj`.`category_id` = `mso_category`.`category_id`
GROUP BY `mso_page`.`page_id`
ORDER BY `page_date_publish` desc

Сходил в старый файл, примерно в это же место (строка 557). Получил запрос:

> SELECT SQL_BUFFER_RESULT mso_page.`page_id`
FROM (`mso_page`)
JOIN `mso_page_type` ON `mso_page_type`.`page_type_id` = `mso_page`.`page_type_id`
GROUP BY `mso_page`.`page_id`
ORDER BY `page_date_publish` desc

При комментировании в новом запросе строк с LEFT JOIN запрос отрабатывает нормально, т.е. не вызывает подвисания.

Php код соответствующего места для нового файла:

>		$CI->db->join('page_type', 'page_type.page_type_id = page.page_type_id');
>		$CI->db->join('cat2obj', 'cat2obj.page_id = page.page_id', 'left');
>		$CI->db->join('category', 'cat2obj.category_id = category.category_id', 'left');
>
>		if ($cat_id)
>			$CI->db->where_in('category.category_id', $cat_id);

Для старого файла:
> 		if ($cat_id) // указаны рубрики
>		{
>			$CI->db->join('cat2obj', 'cat2obj.page_id = page.page_id', 'left');
>			$CI->db->join('category', 'cat2obj.category_id = category.category_id');
>			$CI->db->where_in('category.category_id', $cat_id);
>		}

Скажи, ты тестировал на больших объёмах? Так и должно быть? Т.е. на мой взгляд старый код выглядит логичнее, но почему тогда в новой версии произошло изменение? В чём логика? Можешь как-то прокомментировать или что-то посоветовать глянуть ещё?

PS: Тестирую локально на OpenServer, mysql 5.7, php 5.5

**Comment by maxsite** [comment]
Привет, Илья! Конечно у меня нет такого количества записей. :-) 

Изменения были связаны со строгим режимом MySQL новых версий, с которым он выдавал ошибку. Сам по себе LEFT JOIN довольно ресурсозатратная операция, но вроде бы здесь не должно тормозить. Смысл введений был в том, чтобы дать возможность указывать номер рубрики. Этот «home» - универсальный запрос, который используется в юнитах главной.

Думаю, что при такой большой базе, нужно настроить сервер MySQL в плане выделения больших объемов памяти. Там много ключей, поэтому нужно погуглить. Можно ещё выполнить профилирование в phpMyAdmin под эти запросы — будет понятна причина торможения на уровне MySQL.

Ну и в принципе я согласен, что можно будет подумать и всё-таки составить сложные if-условия, чтобы исключить join('category'... там где он не используется. Но всё-равно он будет срабатывать в тех же юнитах, поэтому всё-равно придётся оптимизировать сервер базы.

**Comment by maxsite** [comment]
Илья, попробуй перед строчкой 

`$CI->db->join('category', 'cat2obj.category_id = category.category_id', 'left');`

добавить условие, чтобы получилось так:

```
	if ($cat_id or $categories or $exclude_cat_id)
		$CI->db->join('category', 'cat2obj.category_id = category.category_id', 'left');
```

**Comment by maxsite** [comment]
Там два раза нужно сделать в блоке пагинации и ниже в основном запросе.

**Comment by vimruler** [comment]
Спасибо, Максим! Попробую и отпишусь!

**Comment by vimruler** [comment]
Попробовал. Получилось заставить работать только с таким кодом для пагинации:
>
		if ($r['type']) 
		{
			$CI->db->join('page_type', 'page_type.page_type_id = page.page_type_id');
	
			if (is_array($r['type'])) 
				$CI->db->where_in('page_type.page_type_name', $r['type']);
			else 
				$CI->db->where('page_type.page_type_name', $r['type']);
		}

		if ($cat_id or $categories or $exclude_cat_id)
		{
			$CI->db->join('cat2obj', 'cat2obj.page_id = page.page_id', 'left');
			$CI->db->join('category', 'cat2obj.category_id = category.category_id', 'left');
		}

и второй фрагмент в основном запросе:
>
	$CI->db->join('page_type', 'page_type.page_type_id = page.page_type_id', 'left');
	$CI->db->join('users', 'users.users_id = page.page_id_autor', 'left');
	if ($cat_id or $categories or $exclude_cat_id)
	{	
		$CI->db->join('cat2obj', 'cat2obj.page_id = page.page_id', 'left');
		$CI->db->join('category', 'cat2obj.category_id = category.category_id', 'left');
	}
	...
	if ($r['type']) 
	{
		if (is_array($r['type'])) 
			$CI->db->where_in('page_type_name', $r['type']);
		else 
			$CI->db->where('page_type_name', $r['type']);
	}


Во втором случае почему-то без условия для page_type обошлось. Причём если для пагинации оставлять безусловное join-добавление page_type, то зависало.

> Думаю, что при такой большой базе, нужно настроить сервер MySQL в плане выделения больших объемов памяти. 

Локально я вроде и так много памяти выделил во всех параметрах, которые нашёл. Но не шибко помогло. 

Профилирование попытался сделать для исходного запроса - недождался результата. Кстати, посмотрел ещё в базу - там ещё один нюанс, что в page_type прописаны 28 типов контента. JOIN вполне может уже на этом моменте загибаться. 

В общем, пока удовлетворяющее проект решение найдено. Хорошо, если оно попадёт в движок.

**Comment by maxsite** [comment]
Не совсем уловил в чём именно здесь различие от того что было? Получается тот же самый запрос.

**Comment by vimruler** [comment]
> Не совсем уловил в чём именно здесь различие от того что было? Получается тот же самый запрос.

Ну как, при наличии условий в запрос не попадают ненужные join и поэтому работает лучше. Конечно, при наличии фильтров выборки записей запрос остаётся прежним и, по сути, мы вернёмся к обсуждению оптимизации запроса когда количество записей, например, для рубрики станет близким к тем же 70000. Пока у меня нет такого примера :-) Так что спасибо за сделанную правку, её пока достаточно!  :-)

**Comment by maxsite** [comment]
Ну ок. :) Тогда тикет закрываю. Если что ещё найдёшь на такой большой базе, пиши.
