### ISSUE TITLE
Ошибка PHP: A non-numeric value encountered

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#363]
Добрый день.
При загрузки картинки на сайт + установка Watermark возникают вот такие ошибки:
![Opera Снимок_2019-09-01_012409_www fafofu ru](https://user-images.githubusercontent.com/1073471/64069702-b3aa1500-cc57-11e9-8187-77a0e4a655ed.png)
Вот с такими настройками:
![Opera Снимок_2019-09-01_012437_www fafofu ru](https://user-images.githubusercontent.com/1073471/64069703-b6a50580-cc57-11e9-8637-cae3e27ca77f.png)

Картинка при этом загружается, watermark появляется на ней.
В интернете пишут, что связано это с переходом на версию PHP 7.1
https://kirkizh.ru/2018/02/php7-non-numeric-value/
У меня установлена версия PHP 7.2.

Имя файла который заливаю "IMG_20190728_232318_DRO.jpg"
Если заливать картинки без watermark ошибок не возникает.
![Opera Снимок_2019-09-01_013121_www fafofu ru](https://user-images.githubusercontent.com/1073471/64069720-40ed6980-cc58-11e9-9441-1dd6c2338375.png)

**Comment by maxsite** [comment]
Вот этот фикс установлен? 
https://github.com/maxsite/cms/commit/7edfe69f5987bb4defbb9f6663757be41b991e27

**Comment by maxsite** [comment]
Нашёл в чём дело. Исправлю.

**Comment by Fafofu** [comment]
В версии max-site 103.2 проблемы нет.
