### ISSUE TITLE
Плагин для Турбо страниц Яндекса

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#364]
Подскажите, пожалуйста, возможно ли добавить плагин для Турбо страниц Яндекса?
Для многих пользователей пригодится.
https://yandex.ru/dev/turbo/doc/rss/markup-docpage/
Там особая разметка RSS, чтобы можно было страницы добавлять через специальный RSS канал для Турбо страниц Яндекса.

**Comment by maxsite** [comment]
Мне это не нужно. Хотите, делайте.
