### ISSUE TITLE
Ошибки при автоматическом обновлении Warning chmod() 

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#365]
Добрый день. Использую автообновление сайта. И при обновлении возникают вот такие ошибки:

Последняя версия MaxSite CMS 103.2
Ваша версия MaxSite CMS 103.1
Обновление...
Unzip master.zip OK!
`Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 193 Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 193 Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 193 Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 193 Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 193 Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 193 Warning chmod() Operation not permitted in volume1wwwfafofuru_update_maxindex.php on line 173` Перейти к сайту
Новая версия MaxSite CMS 103.2

Готово!

После этого всё работает. Но я переживаю, что что-то не обновилось. Как убедиться, что всё обновилось?

**Comment by maxsite** [comment]
Не обязательно весь лог сюда кидать, достаточно пары строк. Проблема с правами для php-скриптов. Либо на сервере запрещена php-функция chmod().

**Comment by Fafofu** [comment]
> Не обязательно весь лог сюда кидать, достаточно пары строк. Проблема с правами для php-скриптов. Либо на сервере запрещена php-функция chmod().

Угу. Т.е. обновление проходит, всё обновилось, просто "PHP" не может проверить права на папки?

**Comment by Fafofu** [comment]
Я вот вижу, что ошибка должна быть вот такая 
Warning: chmod(): Operation not permitted
Если запрещена такая операция.
И какая может быть проблема если обновление проходит?
Ругается только на две строчки.

**Comment by Fafofu** [comment]
А вот, нашёл.

При работе различных сторонних модулей (а в ранних версиях Magento - порой и при работе ядра) может происходить сбой chmod(): Operation not permitted.

Причиной этого сбоя является невозможность интерпретатора PHP изменить права доступа к каким-то файлам или папкам.

В таком сбое обычно в некоторой степени виноваты обе стороны: и разработчик модуля (который не предусмеотрел, что прав на chmod может не быть), и администратор магазина (который отнял такие права).

Операцию chmod имеют право выполнять только владелец объекта (файла, папки), над которым производится эта операция, и суперадминистратор (root): http://unix.stackexchange.com/a/68453
Обратите внимание, что даже прав на удаление файла недостаточно для смену прав доступа к нему.

Для устранения сбоя администратору нужно назначить пользователя операционной системы, от лица которого работает интерпретатор PHP, владельцем всех файлов внутри папки, где установлена Magento.
Обратите внимание, что Magento никаких файлов за пределами своей установочной папки не меняет (и сторонние модули этого не делают).

**Comment by maxsite** [comment]
У вас php запускается с низкими правами, отсюда и проблема. То есть с помощью php вы не сможете например создать файл или каталог. А изменить можно лишь только те, на которые есть права. Это проблема сервера, а не PHP.

**Comment by Fafofu** [comment]
> У вас php запускается с низкими правами, отсюда и проблема. То есть с помощью php вы не сможете например создать файл или каталог. А изменить можно лишь только те, на которые есть права. Это проблема сервера, а не PHP.

Как убедится, что обновление прошло успешно? Можно обновление повторно запустить не повредив данные в базе данных?

**Comment by maxsite** [comment]
Можно. При обновлении БД не используется. Можно ставить любую версию MaxSite CMS загрузив файлы поверх предыдущей.
