### ISSUE TITLE
Кнопку загрузки уносит за пределы экрана в админке

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#366]
На странице "Загрузки" в Хроме кнопка "Загрузить" почему-то уносится вправо, практически за экран. В Firefox такого нет. Версия движка - 103

Отвечающего за это стиля не увидел. Наверно плохо смотрю.

Максим, у тебя такого глюка не наблюдается?

**Comment by maxsite** [comment]
Похоже, что в хроме поменяли поведение width: 100%. В общем исправлю.
