### ISSUE TITLE
Как добавить поле Ваш E-mail в  упрощенную форму комментариев?

### ISSUE THREAD

**Issue by Crackload** [maxsite/cms#368]
Здравствуйте, как добавить поле Ваш E-mail в  упрощенную форму комментариев?
Чтобы было Ваше имя и Ваш E-mail.

**Comment by maxsite** [comment]
Используйте обычную. Там есть это поле.

**Comment by Crackload** [comment]
Мне обычная не нужна, нужна в упрощенной форме.

**Comment by maxsite** [comment]
Я не понимаю, что именно это поле будет делать. Email нужен для регистрации. А значит и пароль. Это все есть в обычной форме. Но в любом случае можете перестроить форму как душе угодно, скопировав её в свой шаблон из `shared/type/page/units/page-comment-form-tmpl.php`

**Comment by Crackload** [comment]
Мне нужно примерно так: http://i86.fastpic.ru/big/2019/0929/03/6dd3a4c9a1c237dfa1f5c4beef8dbb03.png
На многих сайтах это поле присутствует.

**Comment by maxsite** [comment]
Какой нормальный человек будет оставлять свой email??? Чтобы потом тонну спама получить. ;-)
