### ISSUE TITLE
Как дебажить админку?

### ISSUE THREAD

**Issue by nicothin** [maxsite/cms#369]
Когда-то делал другу сайт с MaxSite. Вчера друг отписал, что из админки не может сохранить никакие настройки шаблона. 
Захожу Настройки → Шаблон, меняю к-л поле, жму сохранить, вижу то, что было до изменения.
А вот контент страниц меняется без проблем при сохранении.
Другу кажется, что это началось после перехода на https. Но переход был давненько, а заметил проблему он недавно...

Вопрос: можно как-то понять что не так и на каком этапе? Какой-то лог/сообщение ответа БД при сохранении или что-то в таком духе?
Версия MaxsiteCMS старая: 0.862

**Comment by maxsite** [comment]
Версия PHP какая?

**Comment by maxsite** [comment]
Тогда так сложно сказать. Что в логах php-ошибок?

**Comment by nicothin** [comment]
Выяснил, что логи php ошибок не пишутся. Выясню как включить, запишу, вернусь.

**Comment by nicothin** [comment]
1. включил на хостинге запись error_log
2. зашел в админку: Настройки - Шаблон, поменял поле, сохранил, получил то же состояние поля, что до изменения.
3. файл с логами ошибок не появился :(

все ли я верно сделал?

**Comment by maxsite** [comment]
Если лог включен и нет ошибок, то такая ситуация возможна — просто нет php-ошибок. Хотя по идее лог-файл должен быть, просто пустой. 

Я думаю, что в процессе обновления опций возникает какая-то ошибка и функция вываливается, не внеся изменений в базу. Другой вариант — это сломанная таблица в базе. Это можно посмотреть в phpMyAdmin, выбрать всё и операцию проверить (после оптимизировать). Если это не помогает, то всё-таки это php-ошибка — может неверно на сервере включили лог.

**Comment by nicothin** [comment]
Проверка таблиц выдала статус OK. Попробую разобраться с логом ошибок...

**Comment by maxsite** [comment]
Иногда бывает похожее, если место на аккаунте закончилось. Но если добавляется новая запись, то вряд ли...

**Comment by nicothin** [comment]
Не, на заканчивающееся место не похоже.
Проблема касается только сохранения настроек, сохранение данных о пользователе или о записи на сайте не вызывает проблем, все сохраняется.

**Comment by maxsite** [comment]
Тогда скорее всего какая-то ошибка. Нужно пробовать её отловить.

**Comment by nicothin** [comment]
Не могу найти место, где в админке принимается POST и, соответственно, ф-ю, которая отправляет данные в БД (через CI же?) и анализирует результат. :(
@maxsite не подскажите где искать?
Может, если станет ясно что уходит и что приходит, будет понятно куда дальше рыть?..

**Comment by maxsite** [comment]
Это файл inifile.php и функция mso_check_post_ini()

**Comment by nicothin** [comment]
![image](https://user-images.githubusercontent.com/3499680/67488292-3eb3f400-f678-11e9-82e5-57fc1b3ef139.png)

Функция вызывается, но условие не выполняется.
Я поменял поле, ткнул снизу отправку... POST отсутствует. Мистика.

**Comment by maxsite** [comment]
В начало функции добавьте:

`pr($_POST);`

**Comment by nicothin** [comment]
> В начало функции добавьте:
> `pr($_POST);`

Массив нулевой длины. 
Попробую где-то выше посмотреть приходит ли пост вообще.

**Comment by maxsite** [comment]
Если здесь нет, значит post вообще не идёт. В другом браузере пробовали? Может что-то блокирует запросы к сайту.

**Comment by maxsite** [comment]
Ещё можно проверить через исходный код в браузере (Ctrl+U) адреса — они точно с https?

**Comment by nicothin** [comment]
Пытаюсь понять как ))

**Comment by maxsite** [comment]
Можно через phpinfo() — файл на сервер кинуть с этой функцией. Или так:

```
phpinfo();
echo '<pre>';
print_r($_SERVER);
echo '</pre>';
```

**Comment by nicothin** [comment]
В общем, он возвращает `on` ))
Все страньше и страньше...

**Comment by maxsite** [comment]
Тогда странно... Адрес формируется функцией mso_current_url(). Может там посмотреть...

**Comment by nicothin** [comment]
Проблему решил "тупо в лоб", хотя и не разобрался чем была вызвана.
Огромное спасибо @maxsite !
