### ISSUE TITLE
Баг с выводом записей на главной

### ISSUE THREAD

**Issue by miguralex** [maxsite/cms#370]
После установки последней версии Maxsite v103.3 заметил странный баг:
Установил систему с демо-данными (nginx, php 7.2), начал настраивать через админку сайта. Как только сохранил настройки - полностью пропал вывод главной.

Спустя 40 минут мытарств, восстановить вывод так и не удалось ни с юнитами, ни без, ни через поля "номера записей для главной", "номера рубрик для главной". Смена версий php и переустановка движка так же не помогли.

Если необходимо - могу предоставить данные для доступа к сайту.
![2019-11-03_19-36-00](https://user-images.githubusercontent.com/45785831/68089565-c8cb3c00-fe72-11e9-85a2-414c43a7d28c.png)

**Comment by miguralex** [comment]
При выборе в настройках "Шаблон вывода по-умолчанию" -> content-only получаю экран только с элементом <body>, в котором ничего нет:
![2019-11-03_20-13-24](https://user-images.githubusercontent.com/45785831/68089954-d256a300-fe76-11e9-8f3e-a5bdcc8e731f.png)

**Comment by miguralex** [comment]
Спустя еще 30 минут попыток исправить ситуацию, после включения/отключения плагинов системы всё заработало само-собой... С Maxsite работаю не первый год, но с такими глюками столкнулся впервые...

**Comment by maxsite** [comment]
Просто так настроили вывод сайта.

**Comment by miguralex** [comment]
Нашел в чем была загвоздка. После установки CMS на хостинг в настройках указывал часовой пояс -1. Соответственно время установки CMS и время сервера отличалось на минус 1 час. И пока этот час не пройдет, записи не отображаются.
