### ISSUE TITLE
Ошибка 500 Internal Server Error Sorry, something went wrong при регистрации

### ISSUE THREAD

**Issue by Crackload** [maxsite/cms#371]
Здравствуйте, при регистрации нового юзера на странице registration возникает ошибка 500 Internal Server Error Sorry, something went wrong как исправить?

Сайт на VPS и Vesta  panel.  Версия Maxsite - 103

**Comment by Crackload** [comment]
![screenshot 2019-12-14 001](https://user-images.githubusercontent.com/55942172/70848575-d6c2a280-1e9d-11ea-8b15-403c38e1e8b2.png)

**Comment by Den2016** [comment]
ну, я так думаю, надо сначала в логах сервера смотреть, там более детальная информация

**Comment by Crackload** [comment]
Пробывал это решение https://github.com/maxsite/cms/issues/295#issuecomment-451676776 не помогло

**Comment by Crackload** [comment]
Никто не сталкивался с такой ошибкой?

**Comment by maxsite** [comment]
Логи смотрите.

**Comment by Crackload** [comment]
Логи ничего показывают

**Comment by maxsite** [comment]
Значит пишите админу — это ошибка сервера. Без детальных технических данных никто ничего вам не скажет.

**Comment by Crackload** [comment]
Нашел лог пишет

> 2019/12/15 23:44:35 [error] 22556#22556: *44 upstream sent too big header while reading response header from upstream, client: 37.99.2.6, server: crackloads.com, request: "GET / HTTP/1.1", upstream: "https://213.166.70.126:8443/", host: "crackloads.com", referrer: "https://crackloads.com/registration"

2019/12/15 23:44:41 [error] 22556#22556: *46 upstream sent too big header while reading response header from upstream, client: 37.99.2.6, server: crackloads.com, request: "GET / HTTP/1.1", upstream: "https://213.166.70.126:8443/", host: "crackloads.com", referrer: "https://crackloads.com/registration"

2019/12/15 23:46:51 [error] 22556#22556: *77 upstream sent too big header while reading response header from upstream, client: 37.99.2.6, server: crackloads.com, request: "POST /registration HTTP/1.1", upstream: "https://213.166.70.126:8443/registration", host: "crackloads.com", referrer: "https://crackloads.com/registration"

**Comment by maxsite** [comment]
Что мешает вбить эту ошибку в гугле?

**Comment by Crackload** [comment]
@maxsite 
А помочь не как нельзя? Тем более это maxsite а не другая CMS.
На этом VPS работают другие сайты с разными CMS там нет таких проблем.
Что за подход "ищи в гугле"? 
Если не знаешь проблему пиши не знаю.

**Comment by Crackload** [comment]
Все разобрался увеличил лимиты в nginx.conf
http {
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k;
}

Заработало.
