### ISSUE TITLE
Как добавить новогоднюю гирлянду от Яндекса (со звуком)

### ISSUE THREAD

**Issue by Crackload** [maxsite/cms#372]
Добрый день как добавить новогоднюю гирлянду от Яндекса (со звуком)?

**демо** https://pcvector.net/demo.html?link=/uploads/demo/scripts/other/newyear_garland/index.html

Делал как по инструкции
https://www.pandoge.com/moduli-i-skripty/novogodnyaya-motnya-ot-yandeksa-so-zvukom 
https://pcvector.net/240-novogodnyaya-motnya-ot-yandeksa.html
не работает.

Что нужно сделать?

**Comment by dragomano** [comment]
https://gitlab.com/dragomano/maxsite_plugins/tree/master/ny_headline
