### ISSUE TITLE
Не работает i-telegram

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#373]
В админке в "Соц.сети" вставка ` telegram=https t me ...` не приводит к отображению иконки.
Все другие иконки работают.
Меняю на сайте max-3000 com текст html-элемента иконок соц сетей, например, twitter на telegram - работает.
В чем же дело?
Version 103.3

**Comment by maxsite** [comment]
Может неверный код после «=»? Не видя полный текст сказать невозможно.

**Comment by Filsadovnik** [comment]
Меняю в коде только telegram на другие имена иконок все отображается.
А для telegram отображается квадратик.
Если неверный код - то ничего не отображается.

**Comment by Filsadovnik** [comment]
`<a class="my-social i-telegram t-gray100 hover-t-teal400" rel="nofollow" title="Подписаться на Twitter" href="//twitter.com/maxsite"></a>`
Это код на maxsite - все отображается

Хоть вставляю этот код в html редактор блока браузера, хоть вставляю только атрибуты класса в другой сайт - отображается вместо иконки telegram квадратик

**Comment by Filsadovnik** [comment]
меняю в этом коде i-telegram на любой другой возможный класс иконок - все отображается

**Comment by maxsite** [comment]
Может шрифт FA локально установлен? Если старая версия, то там не было телеграмма.

**Comment by Filsadovnik** [comment]
То же самое поведение на новом сайте, установленном локально.
Не работает только telegram - отображается квадратиком.
Меняю "telegram" на что угодно из набора доступных иконок - отображается нужная иконка.

**Comment by Filsadovnik** [comment]
Телеграм вроде есть: если иконки по этому имени нет - то ничего не показывает.
А тут вроде как заглушка.
На разных гаджетах одно и то же.

**Comment by maxsite** [comment]
Шрифт FA локальный? Версия какая?

**Comment by Filsadovnik** [comment]
Новый сайт установлен локально версия Version 103.5

**Comment by Filsadovnik** [comment]
Шрифта  FA нет установленного локально.

**Comment by Filsadovnik** [comment]
Я открыл файл "**templates/default/assets/css/lazy/2-fontawesome.css**" локального сайта, установленного в openServer только что скачанного дистрибутива maxsite и способом перебора обнаружил что не отображаются иконки после "**i-percent**".
Продолжаю эксперименты.

**Comment by maxsite** [comment]
Значит что-то не так со шрифтом FA. Других вариантов не вижу...

**Comment by Filsadovnik** [comment]
Сравнил файлы 
_/fonts/fontawesome/fontawesome-webfont.woff
/fonts/fontawesome/fontawesome-webfont.woff2
templates/default/assets/css/lazy/2-fontawesome.css_
вновь скачанного maxsite и сайта max-3000 - они идентичны.
Но на max-3000 работают все иконки, а на новом сайте нет.
В windows10 не установлены шрифты с подобными именами.
Подозреваю что я глубоко не в теме.

**Comment by maxsite** [comment]
В FireFox в инспекторе в шрифтах точно не локальный (системный) шрифт?
![fa](https://user-images.githubusercontent.com/2226781/71438969-6bc86580-2700-11ea-9641-a75294f38612.png)

**Comment by Filsadovnik** [comment]
Есть только FontAwesome Regular

**Comment by Filsadovnik** [comment]
Несисте
![Image 4](https://user-images.githubusercontent.com/46860240/71448722-a22dd100-2750-11ea-97d8-38221417e45f.png)

**Comment by maxsite** [comment]
Тогда не знаю. Должно работать.

**Comment by Filsadovnik** [comment]
Согласен, мистика. Может однажды докопаюсь.

**Comment by maxsite** [comment]
Может браузер так шалит.

**Comment by Filsadovnik** [comment]
Три браузера.

**Comment by Filsadovnik** [comment]
Я просто механизм работы не понимаю - может причина очевидна.

**Comment by Filsadovnik** [comment]
Загрузил _fontawesome-webfont.woff_ с max-3000 и заработало.
В скачанном вчера дистрибютиве maxsite этот файл не такой.

**Comment by maxsite** [comment]
Странно.

**Comment by Filsadovnik** [comment]
В дистрибютиве этот файл 82кб
а на сайте max-3000 96кб

**Comment by maxsite** [comment]
На http://max-3000.com/ другой шаблон MF. Наверное просто в default старая версия шрифта. Обновлять не буду, поскольку скоро будет новый дефолтный шаблон в системе.
