### ISSUE TITLE
Не отображается "Забыли пароль?" в плагине login_form 

### ISSUE THREAD

**Issue by raptorcc** [maxsite/cms#374]
Не отображается "Забыли пароль?" в плагине login_form  - Форма логина (виджет) как исправить чтобы отображалось?
![screenshot 2019-12-25 001](https://user-images.githubusercontent.com/46967333/71447072-9e9c4900-2754-11ea-9139-ad7125b3b1dc.png)

**Comment by maxsite** [comment]
Добавить ссылку в поле виджета. Или написать свой плагин.

**Comment by raptorcc** [comment]
Куда прописать? В плагине прописан но не отображается и в админке тоже не видно.

**Comment by maxsite** [comment]
Тут гадалок нет.
