### ISSUE TITLE
Перенаправление на страницу обслуживания через Админку.

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#375]
Добрый день. А есть возможность добавить в админку включение перенаправления на страницу обслуживания на время обслуживания сайта?

Есть элегантное решение: При нажатии на кнопку в админке, добавлять вот такой текст в начало файла ".htaccess", в корне сайта:

> #Включение перенаправления на страницу заглушки при обновлении сайта (начало)
> <IfModule mod_rewrite.c>
> RewriteEngine On
> #сюда будет подставляться текущий IP возвращённый браузером
> #и так же адреса добавленные в админке
> RewriteCond %{REMOTE_ADDR} !^10\.10\.10\.5
> RewriteCond %{DOCUMENT_ROOT}/maintenance.html -f
> RewriteCond %{DOCUMENT_ROOT}/maintenance.enable -f
> RewriteCond %{SCRIPT_FILENAME} !maintenance.html
> RewriteRule ^.*$ /maintenance.html [R=503,L]
> ErrorDocument 503 /maintenance.html
> Header Set Cache-Control "max-age=0, no-store"
> </IfModule>
> #Включение перенаправления на страницу заглушки при обновлении сайта (Конец)

И создание файла "maintenance.enable".

А то не всегда есть доступ к файловой системе на сервер.
И содержимое файла "maintenance.html" чтоб можно было редактировать тоже через админку.

Как Вам идея?

**Comment by maxsite** [comment]
Минусы — придется постоянно править IP, поскольку у многих он динамический. И все равно лезть на сервер для копироания maintenance.html. Проще кинуть свой index.php в качестве заглушки.

**Comment by Fafofu** [comment]
> Минусы — придется постоянно править IP, поскольку у многих он динамический. И все равно лезть на сервер для копироания maintenance.html. Проще кинуть свой index.php в качестве заглушки.

Ну так как на счёт сделать это через админку? Иногда нужно просто отключить сайт, не для обновления. Подключаться через SSH, потом манипулировать файлами, а так очень красиво, нажал кнопку и ВАХ, сайт на обслуживании :)

**Comment by maxsite** [comment]
Вроде был такой плагин, поищите.

**Comment by Fafofu** [comment]
> Вроде был такой плагин, поищите.

Поискал. Нашёл =D Я правильно понимаю, что плагин работает пока работает движок сайта? Т.е. если происходит обновление и переименование папок, то оно и не будет работать?

**Comment by maxsite** [comment]
Плагин без системы работать не будет. А копирование — это вообще из другой области — для этого закрывать сайт не нужно.
