### ISSUE TITLE
Ошибка входа в админку после обновления с версии 103.2 до 106.

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#376]
Добрый день. Обновился с версии 103.2 до 106 универсальным методом, не пускает в админку - пишет не верный логин/пароль. Восстановление пароля не приходит на почту... вернул всё обратно - логин работает нормально... Делал по инструкции у вас тут.
ЗЫ. Кэш сбрасывал, браузер менял... Апач перезагружал...

**Comment by maxsite** [comment]
Наверное старую секретную фразу не скопировали.

**Comment by Fafofu** [comment]
> Наверное старую секретную фразу не скопировали.

Какую секретную фразу? $db['default']['password'] = Это?

**Comment by maxsite** [comment]
Нет. Читайте внимательно:  /maxsite/mso_config.php

**Comment by Fafofu** [comment]
> Нет. Читайте внимательно: /maxsite/mso_config.php

Ээээ в этом файле вообще всё закомменитрованно...

> <?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
> 
> // Здесь можно переопределить конфигурацию CodeIgniter
> 
> 
> # $config['uri_protocol']	= "REQUEST_URI"; // для fastCGI
> # $config['compress_output'] = TRUE; // для сжатия трафика
> 
> 
> // Если вы хотите использовать возможность MaxSite CMS создавать
> // синонимы страниц page и category, то выставьте значение mso_permalink_no_slug = "yes"
> // Если закомментировать, то например, есть страница с короткой ссылкой hello, тогда 
> // http://сайт/page/hello и http://сайт/hello - будут синонимами
> // Аналогично для рубрик: есть рубрика news, тогда
> // http://сайт/category/news и http://сайт/news - будут синонимами
> 
> # $config['mso_permalink_no_slug'] = "yes"; // разрешить синонимы 
> # $config['mso_permalink_slug_cat'] = "yes"; // разрешить также синонимы рубрик
> 
> // язык сообщений CodeIgniter (application/language/)
> # $config['language']	= 'english';
> # $config['language']	= 'de';
> 
> /* End of file */

Не совсем понимаю причём тут база данных...
