### ISSUE TITLE
Ошибка при установке.

### ISSUE THREAD

**Issue by eugenewebdeveloper** [maxsite/cms#377]
Доброго времени суток Максим. У вас тут маленькая ошибка. Для многих локальных серверов пароль от бд отсутствует.
https://prnt.sc/qyjed6

**Comment by maxsite** [comment]
Не уверен. Хорошим тоном считается всё-таки указать хоть какой-нибудь пароль. Тем более, что на localhost это дело 1 минуты.

**Comment by eugenewebdeveloper** [comment]
Ну. Ок. Я для себя убрал обязательное заполнение. Делов 5 секунд. Благодарю за оперативный ответ.

**Comment by maxsite** [comment]
Можно и так. Или прямо в браузере поправить. Но для рабочих серверов — поле обязательное.
