### ISSUE TITLE
Ошибка при установке системы с нуля с помощью автоустановщика

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#378]
Попытался установить как делал это раньше, переименовав папку автоустановщика с  `_update_mso `на `auto`. При этом система выбросила ошибку, что ей незнакома функция `curl_init()` на 120-й строке в файле `index.php` автоустановщика:

> [Wed Feb 12 13:36:25.490443 2020] [php7:error] [pid 19322] [client 85.90.216.199:63348] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /srv/www/c***.ua/httpdocs/auto/index.php:120\nStack trace:\n#0 /srv/www/c***.ua/httpdocs/auto/index.php(10): v_get_file('https://raw.git...', '/srv/www/cabare...')\n#1 {main}\n  thrown in /srv/www/c***.ua/httpdocs/auto/index.php on line 120

Версия PHP 7.2.24 если что.

**Comment by maxsite** [comment]
Установите для php библиотеку curl.

**Comment by trommo** [comment]
Установил - та же ошибка. Сервер ребутил. Странно. Может ещё какую библиотеку надо поставить?

**Comment by maxsite** [comment]
Ну значит curl не поставили. Проверяйте через phpinfo().
