### ISSUE TITLE
Вывод записей дочерних рубрик в родительской (без галочки в админке)

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#379]
Здравствуйте!

Версия движка - 106.1, шаблон - дефолт.

Вопросы:
1) Как сделать показ записей из дочерних категорий в родительские без указания в админке?
2) Или же, как скрыть родительскую категорию с карточки записи на странице категорий, архивов, главной и т.д. и т.п. (по дефолту у записи показываются все категории, к которым она отмечена в админке, это весьма некрасиво смотрится)

Какая стоит задача:
Сами записи должны быть доступны и отображаться в в родительской и дочерней категории, а вот на карточках самих записей должна стоять ссылка только на дочернюю.

Суть проблемы на скрине:
http://prntscr.com/r4pm9x

**Comment by maxsite** [comment]
Вывод в type_foreach-файле, насколько я понимаю? Вам нужно не выводить [cat], а сделать свой обработчик массива данных из page_categories_detail

`$catInfo = $p->val('page_categories_detail');`

**Comment by W1SE95** [comment]
Да, и на главную в юниты тоже самое. Ладно, буду разбираться. Но сложно конечно:)

**Comment by maxsite** [comment]
Для юнитов можете вывод в свою функцию сделать, а потом выводить с помощью кода` [func@my_f]`.

`function my_f($p, $a1 = 0, $a2 = 10, $a3 = 0) {...}`
