### ISSUE TITLE
Использование функции mso_get_first_image_url

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#380]
Здравствуйте.

Подскажите пожалуйста как правильно использовать данную функцию для вывода юрл'а картинки для shema.org разметки на странице статьи, спасибо!

P.S.
И подскажите пожалуйста, к Вам можно обращаться по мелким правкам, естественно на платной основе?

**Comment by maxsite** [comment]
Я бы не советовал использовать эту функцию, поскольку вытягивание адреса из текста не самая лучшая идея. Сейчас есть отдельное поле для изображения записи, вот оттуда и нужно брать адрес изображения.

> И подскажите пожалуйста, к Вам можно обращаться по мелким правкам, естественно на платной основе?

Можно, конечно. На сайте есть контакты.

**Comment by W1SE95** [comment]
Понял Вас. Спасибо!
