### ISSUE TITLE
Пожелания по документации

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#381]
Через некоторое время я планирую обновить раздел документации MaxSite CMS. Если есть какие-то пожелания, то оставляйте их здесь. :-)

**Comment by Kotgo** [comment]
Как сделать блоки footer на подобии версий   102-105.

**Comment by Filsadovnik** [comment]
Предложу тему раздела документации Жизненный цикл комментария: создание - добавление в базу - извлечение из базы - вывод.
При выводе комментария используются хуки:
**comments_content_custom
comments_content_out
comments_content**

И функции:
**mso_comments_content
mso_comments_autotag
parser_default_content**

Не мудрено запутаться.

**Comment by Filsadovnik** [comment]
И еще тема - "способы хранения и передачи данных пользователем".
Где то же все уже было опубликовано - поиск ничего не находит.
В общем существуют такие функции:
mso_get_option
mso_get_cache
mso_get_val
mso_get_option
mso_get_info
Для разных целей может подойти разный плход

**Comment by maxsite** [comment]
У меня давно зреет мысль сделать справочник функций. Но их много и нужно выбрать с каких начать.

**Comment by Filsadovnik** [comment]
Достаточно, чтобы поиск по имени функции приводил к нахождению кода реализации этой функции, скажем, на github.
Неужели нельзя на github так сделать? Указать что это реализация такой-то функции.
Насколько я понимаю это можно сделать при помощи плагина , описываемого здесь:
https://help.github.com/en/github/managing-files-in-a-repository/navigating-code-on-github

**Comment by maxsite** [comment]
Дело не в поиске. Для этого даже Notepad++ годится (карта функций). Да и есть всякие парсилки вроде PHPXref. Думаю, что в справлчнике должно быть не только формальное описание функций, но и примеры и какие-то объяснялся. Этого в автоматическом режиме не сделать.

**Comment by Filsadovnik** [comment]
Описание функции с объяснением будет больше, чем сам код функции, где уже есть объяснения строчек.
А если еще и примеры ...
Много работы.
В блоге в виде статей сложно будет делать. 
Тут бы что-то типа википедии.
Думал что в github есть такой функционал.
Хотя если каждой функции делать свою запись и что-то надстроить в виде плагина ... велосипед?

**Comment by maxsite** [comment]
Здесь есть wiki, но всё равно придется вручную составлять тексты.

**Comment by NtTel** [comment]
**Изображения и файлы к записи**

Следует отметить, что во многих шаблонах, миниатюры формируются автоматически при выводе на страницах сайта. Их размер и метод формирования жестко прописывается в файлах шаблона, поэтому при загрузке **опицю** создания миниатюр можно отключить (выбрать пункт Не создавать миниатюру).

**Comment by NtTel** [comment]
> **[Изображения и файлы к записи](https://max-3000.com/book/images)**
>
> Следует отметить, что во многих шаблонах, миниатюры формируются автоматически при выводе на страницах сайта. Их размер и метод формирования жестко прописывается в файлах шаблона, поэтому при загрузке **опицю** создания миниатюр можно отключить (выбрать пункт Не создавать миниатюру).

Опечатка теперь другая - **опицию**<hr>**[Рубрики и структура вашего сайта](https://max-3000.com/book/category)**

Старайтесь не использовать более одного вложения рубрики. Такие громоздкие структуры создают ненужную сложность для посетителя — разбираться в хитросплетениях вашего сайта мало кому будет интересно. Поэтому обычная рекомендация: делать как можно меньше **вложеностей**, а если рубрик немного, то вовсе избегать подрубрик.

**Comment by NtTel** [comment]
**[Настройка главной страницы сайта](https://max-3000.com/book/home)**

Главная ~~**главная**~~ страница теперь выводится как и другие full-страницы, которые мы рассмотрели ранее.
<hr>

Юнитов может быть сколько угодно и все они выводятся последовательно. Это позволяет создавать сложные конструкции, **который особенно пригодится для вывода html-кода**, где каждый блок может быть вложен в другой.
<hr>

![image](https://user-images.githubusercontent.com/6689062/84413329-cc6a4100-ac53-11ea-9b3a-a344d24e3038.png)

**Comment by maxsite** [comment]
Поправил, спасибо.

**Comment by NtTel** [comment]
**[Каталог модулей Store](https://max-3000.com/book/store)**

> С технической точки зрения — лендинг удобно рассматривать как набор независимых блоков, которые **собиратся** как кубики Лего.

Пропущена буква в слове
<hr>

> Поскольку в таких блоках как правило много html-кода, то будет удобней вынести его отдельным файлом, **а юниты (или юниты)** подключать как модуль.

?
<hr>

**Comment by NtTel** [comment]
**[Шапка сайта](https://max-3000.com/book/home)**

> t180 — размер шрифта в процентах **о** базового (16px)

от 
<hr>

**[Шаблоны заголовков](https://max-3000.com/book/info-file)**

> задаёт **форма** вывода заголовка записи (код title). 

формат

**Comment by NtTel** [comment]
**[Раскрутка сайта. SEO-оптимизация](https://max-3000.com/book/seo)**

> В настройках плагина можно указать размеры изображения и несколько **друих** параметров, например ваш твиттер-ник.

других
<hr>

> При каждой **пубрикаци** или редактировании записей, файл будет обновляться.

публикации 
<hr>

> В типографике задействовать списки перечисления, блоки цитат и подходящие по смыслу **семантичные** html-тэги (**абревиатуры**, код, моно-текст, полужирное, курсивы и т.п.).

семантические, аббревиатуры
<hr>

> Использовали вы при этом десяток H1 или **не одного** — никакой роли не играет.

ни одного
<hr>

> К сожалению область SEO одна из тех, которая **обрасла** древними мифами и первая ошибка новичка — начать им следовать.

обросла

**Comment by NtTel** [comment]
**[HTML — язык разметки. Классы CSS](https://max-3000.com/book/use-html)**

> Классы Berry CSS настраиваются только **одир** раз, да и то, для случаев, если какого-то свойства не хватило (обычно фреймворк сразу перекрывает 90% потребностей).

один

**Comment by tecspda** [comment]
нужен справочник функций с микро примерами. микро - но надо.
вот здесь человек собрал все функции с описание.
[http://www.hostedredmine.com/projects/maxsitecms/wiki/API_MaxSite_CMS](url)
половину работы сделал.

осталось только примеры

**Comment by maxsite** [comment]
Это очень старая попытка. По сути просто список функций. Я бы с удовольствием что-то предложил, но на это нужно много времени.
