### ISSUE TITLE
Как image_for_page не выводить на  странице записи

### ISSUE THREAD

**Issue by wpgrabber-tune** [maxsite/cms#382]
версия 106.2 шаблон max-turdus

**Comment by maxsite** [comment]
А что стандартная опция не работает?

**Comment by wpgrabber-tune** [comment]
А где её искать?

**Comment by maxsite** [comment]
В редактировании записи.

**Comment by wpgrabber-tune** [comment]
Понятно. 
При создании надо в  meta_key => image_for_page_out сделать 
meta_value =>  no-page
Так, да?

**Comment by maxsite** [comment]
Просто выбираете «Не показывать на странице записи».

**Comment by wpgrabber-tune** [comment]
да мне надо при создании страницы, автоматом что бы

**Comment by maxsite** [comment]
Основные - Настройки редактора - Вывод изображения

**Comment by wpgrabber-tune** [comment]
я скриптом вставляю через INSERT INTO mso_page

**Comment by maxsite** [comment]
Тогда вручную.

**Comment by wpgrabber-tune** [comment]
нормально получилось

`INSERT INTO mso_meta (
            meta_id,
            meta_key,
            meta_id_obj,
            meta_table,
            meta_value,
            meta_desc,
            meta_menu_order,
            meta_slug
            )
            VALUES(NULL, "image_for_page_out",'. $idtxt. ',"page","no-page",NULL,0,NULL);`
