### ISSUE TITLE
Как сделать блоки footer на подобии версий   102-105.

### ISSUE THREAD

**Issue by Kotgo** [maxsite/cms#383]
Как сделать блоки footer на подобии версий   102-105? У меня в прошлых версиях исходя из того шаблона имелись блоки как сейчас на max-3000 , но в новом шаблоне отсутствуют такие блоки, подскажите, как их сделать или перенести из старой версии?

**Comment by maxsite** [comment]
Так скопируйте эти компоненты из старого default и пользуйтесь.
