### ISSUE TITLE
как удалить сразу несколько записей в разделе Все Записи?

### ISSUE THREAD

**Issue by sofandr** [maxsite/cms#384]

**Comment by maxsite** [comment]
Никак.

**Comment by sofandr** [comment]
Так и понял, удали прямо в базе, единственное, что количество записей не пересчитывает в рубрике.

**Comment by sofandr** [comment]
> Никак.

Так и понял, удали прямо в базе, единственное, что количество записей не пересчитывает в рубрике.

**Comment by maxsite** [comment]
Потому что данные считаются по другой таблице cat2obj.
