### ISSUE TITLE
Неправильный пароль при комментировании

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#385]
Привет, Максим!

Наткнулся на странный глюк в 103.3. Авторизованный комюзер пытается оставить комментарий, но получает сообщение "Неправильный пароль". 

Концы нашёл в /common/comments.php в строке 654. Чтобы проверка пароля прошла хорошо, пришлось добавить строку:

> $comments_password = mso_de_code($post['comments_password'], 'decode'); # наоборот надо дешифровать
> if ($row['comusers_password'] != $comments_password) // пароль неверный

Хота сюдя по предыдущему каменту кода - там не нужна дешифровка!

Посмотри, пожалуйста!

**Comment by maxsite** [comment]
Привет, Илья!

Сейчас такого кода нет и всё работает. Попробуй всё-таки обновиться, может была какая-то провка после твоей версии.

**Comment by Sergeysem** [comment]
Доброго времени. Та же самая проблема, версия MaxSite CMS Version 102.3.

Если закомментировать, то работает, но не знаю можно ли так оставить?

```
						// пароль не нужно шифровать mso_md5
						if (isset($post['comments_password_md']) and $post['comments_password_md'])
						{/*
							if ($row['comusers_password'] != $comments_password) // пароль неверный
								return '<div class="' . $args['css_error']. '">' . tf('Неверный пароль'). '</div>';
						*/}
						else
						{
							if ($row['comusers_password'] != mso_md5($comments_password)) // пароль неверный
								return '<div class="' . $args['css_error']. '">' . tf('Неверный пароль'). '</div>';
						}
```

**Comment by Sergeysem** [comment]
Живые есть?
