### ISSUE TITLE
Включить обработчик HTML по умолчанию?

### ISSUE THREAD

**Issue by lexxxx74** [maxsite/cms#386]
Не могу разобраться... Как можно по умолчанию включить для всех записей обработчик html как simple?
Пришлось обновить сайт, не мной сделанный, теперь кой-чего неверно выводится, местами код [br] стоит...

**Comment by maxsite** [comment]
Похоже, никак. Только выбирать при редактировании записи.

**Comment by lexxxx74** [comment]
Вот, блин... А у меня этих записей больше тысячи
В БД не вижу этого пункта, так бы может запросом в мускуле везде добавил...
Может как-то в код системы добавить подключение этого обработчика?

**Comment by maxsite** [comment]
Ну если вы добавляли записи как simple, то он там уже должен быть отмечен.

**Comment by lexxxx74** [comment]
А черт его знает как оно было отмечено до обновления... Но после обновления полезли проблемы с кодами навроде [br], помимо всего прочего. Остальные проблемы вычистил, осталась эта. Плагины включил, но не помогло
Обновлять пришлось тоже не на последнюю версию, на хостинге рядом лежит сайт без поддержки свежего php
Не пойму всё же где прописывается этот параметр. В базе данных не вижу в записях

**Comment by maxsite** [comment]
Если был старый сайт, то там не simple, а обычный парсер default. C ним ничего отмечать не нужно — он автоматом подхватывается, если не было редактирования. Плагины, есно, должны быть заранее включены.

**Comment by lexxxx74** [comment]
Опа... что-то я ступил
Старые записи выводятся нормально. Часть последних криво, там стоит обработчик "нет". Видать до или после переноса был сбой
Вопрос закрыт, спасибо!

**Comment by maxsite** [comment]
Нужно было вначале активировать плагин парсера default, а уже потом редактировать записи. Сейчас придется для этих записей ещё раз вручную указать парсер.

**Comment by lexxxx74** [comment]
Да, я так и сделал. Благо их там не так и много успели забить
Не сообразил, что проблема носит локальный, а не глобальный характер
