### ISSUE TITLE
Исключение показа хлебных крошек для типов страниц "static"

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#387]
Здравствуйте.

Подскажите пожалуйста, что нужно прописать в коде компонента хлебных крошек, чтобы
они не выводились на страницах типа page + подтипа static (дефолтные типы страниц)

Сейчас использую if (is_type('page')) { и погнал }, но вот что указать для запрета вывода на подтипах - не знаю.

**Comment by maxsite** [comment]
Вы можете смотреть любые данные записи и по ним уже создавать условия. 

Вот так можно посмотреть что доступно.

`pr($pageData);`

**Comment by W1SE95** [comment]
Понял, не сообразил сразу. Спасибо!
