### ISSUE TITLE
Кеширование в админке (проблема)

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#388]
Здравствуйте.

Файлы админки НЕ правил. Включено динамическое кеширование и глобальное кеширование, так же добавил сайт в CDN CloudFlare, в Page Rules (CloudFlare) - указал Cache Level:ByPass (т.е. ничего не кешировать).

Но вот при входе в админку и при любых действиях - приходится перезагружать страницу в ручную постоянно, чтобы увидеть изменения до и после.

Крайне НЕ удобно при написании и публикации постов... Возможно подскажите хотя бы в какой стороне искать причину данного изъяна...

Вариант полностью отключить CloudFlare - нет, хочу перейти на платный тариф, очень удобные вещи там есть + защита от перегрузки в случае атак, если вопрос не решается каким-то "костылем", тогда вопрос: 
Планируете ли Вы интегрировать API CloudFlare в плагин глобального кеширования? Спасибо!

**Comment by maxsite** [comment]
Никогда не пользовался, да и не уверен что это кому-то вообще нужно. Скорее всего проблема либо в браузере, либо хостинге.

**Comment by W1SE95** [comment]
Вы крайне не правы. При высоких посещениях - CDN необходим в первую очередь снижением нагрузки на сервер при атаках, а во вторых можно настроить статику да и вообще очень много всего... Зря Вы так сквозь пальцы смотрите на такие удобные веб-сервисы. Ладно, понял вас!

**Comment by maxsite** [comment]
Какое это вообще имеет отношение к MaxSite CMS??? Настраивайте свой хостинг, сервис или что-так ещё...

**Comment by W1SE95** [comment]
На данный момент никакого, просто я использовал до этого WordPress, но из-за высоких посещений и желания познать другие CMS, остановился на Вашей.

В WP, в самых нормальных плагинах кеширования есть синхронизация с CloudFlare и при очистке кеша, изменения настроек минимизации по CDN все изменения происходят на прямую через админку WP, что очень удобно.

**Comment by maxsite** [comment]
В вп есть только один нормальный плагин кэширования — это мой maxcache, который даже не плагин, а отдельный скрипт. Все остальные даже рядом не валяются, просто потому что вп настолько прожорлив и так сильно грузит сервер, что любое к нему http-обращение уже может завалить сервер. Не зря команда PHP использует вп именно как один из самых неоптимизированных набор php-скриптов для тестирования языка.

В MaxSite CMS кэширование — уже часть системы и для 99% пользователей его хватит с головой. Но для для 1% более чем достаточно плагина глобального кэширования, который по сути превращает сайт в статику (как maxcache). Поэтому для MaxSite CMS и не нужны никакие дополнительные и сторонние сервисы. Она и так неплохо работает.

**Comment by W1SE95** [comment]
Да, Вы правы. Я поэтому и перешел. Но мы сейчас говорим о кешировании непосредственно серверном, это очень хорошо что это изначально всё есть, из коробки... Этого действительно очень не хватает в ВП.

Но я сейчас имел ввиду кеширование на стороне других серверов. Очень много раз были обрывы хостинга, от этого никто не застрахован и + частые атаки ддосс, если проблема недоступности сервера возникнет, пока его техники хостинга исправят или перенесут проект на другой сервер, вас это скорее всего не устроит по времени.

Для таких случаев и делают интеграцию с CDN в самих плагинах кеширования, чтобы руководить своим проектом из одного места и знать, что всё функционирует правильно без танцев с бубном. 

Но это моё субъективное мнение, если Вы говорите что пользователи Вашей CMS не используют такого да и не нужного этого, то разговор естественно не предметный.

**Comment by maxsite** [comment]
Плагины кэширования ничего не должны знать о CDN, потому что кэширование — это в первую очередь снятие нагрузки с PHP/MySQL сервера, а CDN — это по сути получение трафика не с сервера, а со «стороны». Более того CDN - это вообще только статика, вроде картинок и это совсем уже не согласуется с динамической отдачей контента (как вы например собираетесь кэшировать страницы, залогиненных комментаторов?).

Поэтому я и разделяю мух от котлет. То что вы пишите — это крайний случай для очень высокопосещаемых проектов, которым нужно распределять трафик. Для 99% сайтов это не нужно. Просто вы привыкли к вп, где нагрузка на сервер высока и там пытаются любыми способами её снизить. Вот и предлагают CloudFlare, вместо того, чтобы оптимизировать свои php-скрипты.

**Comment by W1SE95** [comment]
Есть такое, привык, потому что ВП глючный, что ж поделать. Ну вот именно про комфортное распределённое кеширование я имел ввиду... На счёт комментариев я откровенно говоря приверженец сторонних сервисов, были и есть неплохие проекты с норм количеством аудитории и где-то стоят cackle, где-то FB, на последний установил виджет комментов от телеги. Ну каждому индивидуально всё. Но, Вашу точку зрения и доводы я понял, тогда не отвлекаю Вас. Спасибо что уделили время!

**Comment by W1SE95** [comment]
Макс, приношу свои искренние извинения. Вы потратили время на ответы мне по данному тикету, а причина крылась вовсе не в CMS или CDN. Я забыл что не настроил кеширование в самом модуле PWA. Весь день убил, а проблема была на самой поверхности, нужно было лишь обратить внимание на консоль.
