### ISSUE TITLE
Дочерние категории в url

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#389]
Здравствуйте.

Стандартными средствами из коробки можно ли реализовать правильную вложенность для дочерних категорий в URL? 

Пример: www.site.com/news/russia/sport.

Я пытаюсь обойтись без этого, с помощью тегов, но в некоторых категориях крайне сложно это структурно продумать всё.

**Comment by maxsite** [comment]
Нет, так не получится. В MaxSite CMS все рубрики равноправные.
