### ISSUE TITLE
Новый автопарсер текста

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#39]
В новом обновлении я перенес парсер текста из ядра системы в отдельный плагин parser_default. Если плагин не активирован, то при выводе старых записей, он подключается автоматом и тексты должны показываться нормально, как и раньше. При создании или редактировании записей, требуется включить плагин или текст будет отдаваться как есть без любой обработки. 

Теоретически такая схема позволяет подключить сторонние визуальные редактора, которые сами формируются html-код. То есть для них никакой парсер не нужен. **Это требуется протестировать**.

Плагин parser_simple из LPF — просто парсер для тех, кто сам привык контролировать html-код. Чуть позже в него добавлю обработчик тэгов PRE и CODE — будет автозамена спецсимволов.

Поскольку отключились масса хуков по обработке текстов, то **нужно прверить работу всех плагинов вроде вв-кода и т.п.**

Чем быстрее проведем тестирование, тем быстрее пойдем дальше. Подключайтесь, все кому не лень. :-) О багах можно здесь сообщать.

**Comment by leonovmax** [comment]
При попытке создать новую запись 
```
Fatal error: Call to undefined function mso_text_to_html() in D:\www\OpenServer\domains\cms-dev.com\application\maxsite\admin\plugins\admin_page\new.php on line 238
```

**Comment by maxsite** [comment]
Пофиксил.

**Comment by cuprum** [comment]
Вот такая теоретическая ситуация. Был сайт с дефолтным редактором, были опубликованы уже какие-то записи. Потом автор решил поменять дефолный редактор на какой-то другой. Если надо будет отредактировать старые записи (до установки нового редактора),это не поломает разметку?

**Comment by maxsite** [comment]
Если старые записи не редактировать, то сработает старый автопарсер текста. Если же запись редактируется, то сработает тот парсер, который будет выбран при редактировании.
