### ISSUE TITLE
Удаление лишних Типы страниц/записей через PhpMyAdmin

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#390]
Здравствуйте.

Пришлось чутка поменять некоторые наименования уже созданных типов страниц, но через админку я как понял это нельзя сделать, я пошёл по пути костыля и удалил строки ненужных мне типов страниц напрямую через PhpMyAdmin.

Вопрос заключается в следующем:

Ручное удаление прямо из бд на что-то влияет, то есть при удалении CMS будет продождать работать в норм режиме? 

P.S.
Как в шаблоне делать вывод тех или иных типов записей я уже научился.

**Comment by maxsite** [comment]
Главное, чтобы в базе не было записей у которых указан удалённый тип.
