### ISSUE TITLE
thumb_generate() объявлена в двух местах

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#391]
Просто акцентирую внимание - вдруг кто-то тоже попадется.
Version 106.6 поймал ошибку у себя:
> Fatal error: Cannot redeclare thumb_generate() (previously declared in C:\OSPanel\domains\auino\application\maxsite\common\core\images.php:11) in C:\OSPanel\domains\auino\application\maxsite\shared\stock\thumb\thumb.php on line 625

Причину нашел - в версии 101 подключал функцию **thumb_generate()** явно:

`require(getinfo('shared_dir')` . 'stock/thumb/thumb.php');

Теперь видимо она подключается где-то автоматом в **common\core\images.php** - вероятно про это где-то уже читал в статьях.
Решил проблему строчкой:

`if` (!function_exists('thumb_generate')) require(getinfo('shared_dir') . 'stock/thumb/thumb.php');

**Comment by Filsadovnik** [comment]
Можно наверное сразу закрыть это isue

**Comment by maxsite** [comment]
Ну да, сейчас thumb.php подключается всегда. 
См. https://max-3000.com/page/maxsite-cms-105

**Comment by Filsadovnik** [comment]
Ага - помню же что-то читал.

> Каталог share/stock, соответственно, удалён.

Понятно - просто этот каталог со старых версий затесался
