### ISSUE TITLE
Можно ли ввести в плагин Bbcode что-то вроде итератора или счётчика?

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#392]
Суть проблемы:

На сайте нужно создавать страницы с таблицами, содержащими множество строк и столбец с номером каждой строки таблицы (id). Когда потом в середину таблицы нужно добавить новую строку, то приходится сдвигать все последующие id на единицу или на то число, которое соответствует количеству добавленных строк. Это очень неудобно.

Пришла мысль, что можно было бы ввести в плагин [bbcode](https://github.com/maxsite/cms/tree/master/application/maxsite/plugins/bbcode) новый элемент, назовем его условно **[iterator]**, который бы при каждом появлении в коде страницы увеличивался бы на единицу. Т.е. при первом появлении на странице [iterator] бы заменялся на 1, при втором - на 2 и т.д.

**Comment by maxsite** [comment]
Для таких вещей лучше сделать какой-то свой шорткод.

**Comment by trommo** [comment]
Вот [здесь](https://gist.github.com/morontt/2c49983a946aa16ce7ff9a7fbfdef231) мне подсказали, как можно подобное реализовать.

А как дальше быть? Делать свой плагин?

**Comment by maxsite** [comment]
Ну да.
