### ISSUE TITLE
Breadcrumbs и добавление плагином своих страниц по хуку 404

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#393]
Компонент **breadcrumbs** позволяет добавлять сегменты при помощи `comp_breadcrumbs_add`
Но насколько я понял, если мы получили управление по хуку 404, то is_type('page_404') уже всегда вернет true и breadcrumbs добавит сегмент `$breadcrumbs['404. Ничего не найдено'] = '';` , который потом выведется?
Или мы можем как-то повлиять на содержимое is_type?
Вот например ставим плагин samborsky_polls и в нем, на странице архива голосований видим:
![404](https://user-images.githubusercontent.com/46860240/79692415-c10b2280-826d-11ea-8f63-67e5d6d454ee.png)
Как можно убрать  **404. Ничего не найдено**

**Comment by Filsadovnik** [comment]
```
elseif (is_type('page_404'))                 $breadcrumbs['404. Ничего не найдено'] = '';
elseif (mso_segment(1) == 'sitemap')           $breadcrumbs['Карта сайта'] = '';
elseif (mso_segment(1) == 'contact')           $breadcrumbs['Контактная форма'] = '';
elseif (mso_segment(1) == 'registration')      $breadcrumbs['Регистрация на сайте'] = '';
elseif (mso_segment(1) == 'login')             $breadcrumbs['Вход'] = '';
elseif (mso_segment(1) == 'comments')          $breadcrumbs['Комментарии'] = '';
elseif (mso_segment(1) == 'archive')           $breadcrumbs['Архив сайта'] = '';
elseif (mso_segment(1) == 'guestbook')         $breadcrumbs['Гостевая книга'] = '';
elseif (mso_segment(1) == 'search')            $breadcrumbs['Поиск'] = '';
elseif (mso_segment(1) == 'map')               $breadcrumbs['Карта сайта по рубрикам'] = '';
elseif (mso_segment(1) == 'map-tags')          $breadcrumbs['Карта сайта по меткам'] = '';
elseif (mso_segment(1) == 'polls-archive')     $breadcrumbs['Архив голосований'] = '';
```
(is_type('page_404') идет раньше, чем elseif (mso_segment(1) == 'polls-archive') и все равно ловится.
guestbook ведет себя так же

**Comment by Filsadovnik** [comment]
Как вариант перенести elseif (is_type('page_404')) в самый конец после if ($add = mso_get_val('comp_breadcrumbs_add', false))

**Comment by maxsite** [comment]
Да, что-то подобное должно быть...

**Comment by maxsite** [comment]
Можно так попробовать. Строчку  
`elseif (is_type('page_404'))   `

вообще убрать.  А после 

```
if ($add = mso_get_val('comp_breadcrumbs_add', false))
	$breadcrumbs = array_merge($breadcrumbs, $add);
```
Дописать:

`if (!$breadcrumbs) $breadcrumbs['404. Ничего не найдено'] = '';`

Проверьте такой вариант.

**Comment by Filsadovnik** [comment]
Теперь polls-archive и guestbook работает.
Буду пробовать сложные варианты.

**Comment by Filsadovnik** [comment]
Целесообразность использования 
`$breadcrumbs = array_reverse($breadcrumbs);`
под вопросом.
Если у нас 3-4 сегмента после главной и несколько страниц то сложно строить дерево наоборот.
Может обойтись без **array_reverse**, а просто в выводе добавить главную?

**Comment by Filsadovnik** [comment]
```
// можно указывать comp_breadcrumbs_add (это всегда массив) как дополнение к текущему
if ($add = mso_get_val('comp_breadcrumbs_add', false))
	$breadcrumbs = array_merge($breadcrumbs, $add);

if (!$breadcrumbs) $breadcrumbs['404. Ничего не найдено'] = '';

// всегда добавляем главную
//$breadcrumbs['Главная'] = getinfo('siteurl');

// $breadcrumbs = array_reverse($breadcrumbs);

// теперь вывод
$out = '<a href="' . getinfo('siteurl') . '">Главная</a>    ';

foreach ($breadcrumbs as $name => $link) {
	if ($link)
		$out .= '<a href="' . $link . '">' . htmlspecialchars($name) . '</a>    ';
	else
		$out .= $name . '    ';
}
```

**Comment by Filsadovnik** [comment]
Или вообще главную не добавлять автоматически, если comp_breadcrumbs_add указано - пусть пользователь сам решает.

**Comment by maxsite** [comment]
Такие вещи нужно решат индивидуально для каждого шаблона. Просто делаете копию компонента и там свои условия и вариант вывода.

**Comment by Filsadovnik** [comment]
Хочется добавлять плагином элементы в breadcrumbs как можно проще

**Comment by maxsite** [comment]
Сложно учесть все пожелания в таком простом компоненте.

**Comment by Filsadovnik** [comment]
Универсальные пожелания:
1. Возможность из плагина запретить вывод хлебных крошек компонентом (чтобы вывести по-своему).
2. Добавить свои сегменты, чтобы компонент вывел это единообразно со всем сайтом.
3. Добавлять сегменты нужно последовательно , чтобы не запутаться и не применять **array_reverse** в плагине, чтобы потом снова был **array_reverse**  в компоненте.

**Comment by maxsite** [comment]
Этот компонент всего -лишь вывод ссылок. Поэтому вы можете сделать копию и внести изменения под свой шаблон.
