### ISSUE TITLE
$this->load->helper('xml'); в shared\type\feed\home.php

### ISSUE THREAD

**Issue by Filsadovnik** [maxsite/cms#394]
Копируем этот файл чтобы сформировать RSS для произвольных нужд.
И вызываем по хуку 404.
Ругается на строчку 
`$this->load->helper('xml');`
Конечно работает, если заменить на
```
$CI = &get_instance();
$CI>load->helper('xml');
```
Но непонятно как же и откуда вызываются файлы для формирования RSS.

**Comment by maxsite** [comment]
В этом файле $this это и есть объект CodeIgniter. В другом подключении используйте get_instance().
