### ISSUE TITLE
Убрать ссылку у миниатюры на главной (units)

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#395]
Здравствуйте.

Подскажите, для отдельного модуля можно ли назначить thumb_link = false?
Я указываю такой код, но переменные false / true - НЕ работают.

Я что-то неправильно делаю?

Если напрямую в last-pages указать показывать или нет - работает, но это не удобно, придётся править все модули на главной.

**Comment by maxsite** [comment]
Наверное не модуля, а юнита. 

Используйте 0/1.
