### ISSUE TITLE
Смена домена

### ISSUE THREAD

**Issue by darkate** [maxsite/cms#397]
<details>
  <summary>Вступление</summary>
Привет!

Решил оживить один из старых проектов, но уже но другом домене. По этому вопросу Google ничего не подсказал — видимо, поскольку форум закрыт (почему бы его не оставить только для чтения, кстати?).

P.S.: я, конечно, сейчас запущу поиск по файлам и базе, но всё же хочется в следующий раз просто найти решение в сети. И другим может быть полезно.
</details>

**Вопрос**: какие файлы и/или таблицы надо править для успешной смены домена?

**Comment by maxsite** [comment]
Делаете дамп базы. В нём в текстовом редакторе делаете замены старого домена на новый. Загружаете дамп обратно. Всё.

**Comment by darkate** [comment]
Благодарю!

Текстовый редактор не осилил, но в phpMyAdmin нашёл тысячу строк, в основном в таблице **mso_page**.

Заменил командой:
update mso_page set page_content = replace(page_content, 'oldname.com', 'newname.com');

Может кому пригодится. Разумеется, oldname.com и newname.com необходимо заменить своими значениями.
