### ISSUE TITLE
Временной диапазон виджетов page_views и rater

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#399]
Здравствуйте.

Только обратил внимание на это, а за какой промежуток времени учитываются показы и рейтинг к материалам, которые выводятся в сайдбаре виджетами?

**Comment by maxsite** [comment]
В смысле — время? Это же прост счетчики.

**Comment by W1SE95** [comment]
> В смысле — время? Это же прост счетчики.

Я имею ввиду плагины - самые читаемые, самые рейтинговые материалы, в виджете счётчика просмотров для сайдбара можно показывать количество просмотров записи за сутки.

Вопрос - за какой временной диапазон собирается выборка для показа в сайдбаре?

Я просто сейчас пытаюсь реализовать показ самых просматриваемых и рейтинговых материалов за месяц.

И я что то не пойму логики плагинов

**Comment by maxsite** [comment]
Не «за сутки», а «в сутки». Делится кол-во просмотров на кол-во дней.

**Comment by W1SE95** [comment]
> Не «за сутки», а «в сутки». Делится кол-во просмотров на кол-во дней.

То есть, плагины показывают те материалы, у которых больше всего просмотров или рейтинга за все время - год, два и т.д. ?

Я правильно понимаю?

**Comment by maxsite** [comment]
Конечно. Это же обычные числа.
