### ISSUE TITLE
Не добавляет записи на главную

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#40]
Установка последней актуальной версии из dev-ветки.
Создаю в админке блоговую запись, публикую, но она не добавляется на главную.

**Comment by maxsite** [comment]
Со временем публикации ничего не напутал?

**Comment by cuprum** [comment]
@maxsite Вроде нет. По времени позже, чем запись "Привет, мир!". Своя страница (/page/...) создается, но на главную не хочет...
Проверил на другом домене версию чуть помладше, тот же результат. Теряюсь в догадках. Наверное что-то с локальным сервером.
Максим, пока не закрывай обсуждение. Разберусь - отпишусь.

**Comment by maxsite** [comment]
На локалхосте поправка времени должна быть нулевой. Обчно там часовой пояс ставят — получатся неверное смещение.

**Comment by cuprum** [comment]
@maxsite C настройками времени все ОК. Оказалось,это у меня dns-proxy выпендривался.
