### ISSUE TITLE
Вопросы по марафону :)

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#400]
Здесь только вопросы по текущему мини-марафону, которые проходит в моём телеграм-канале: https://t.me/maxsite

**Comment by NtTel** [comment]
Шаг 2
Компиляция scss даёт такой лог:
![image](https://user-images.githubusercontent.com/6689062/84914392-e649cf00-b0fe-11ea-81d0-9165acc30a20.png)

**Comment by maxsite** [comment]
Вы запускаете через bat-файл из корня каталога шаблона?

**Comment by maxsite** [comment]
Ещё версия sass какая?

`sass -v`

Должна быть 3.5 и выше.

**Comment by NtTel** [comment]
С версиями всё в порядке.
Может что-то с путями? Так например, в файле /assets/sass/lazy/3-colors.scss
`@import 'berry/variables/variables';` - так ошибка, а если исправить на:
`@import '../berry/variables/variables';` - ошибка уходит.

Прошёлся по всем файлам что давали ошибки и подправил пути.

**Comment by maxsite** [comment]
Нет, так не должно быть. Вы компилируете файлы каталога `assets/sass/`, а сама компиляция запускается из корня шаблона. Поэтому пути верные. То что вы указываете на верхний уровень, значит, что текущий каталог компилятора неверный.

**Comment by NtTel** [comment]
> Нет, так не должно быть. Вы компилируете файлы каталога `assets/sass/`, а сама компиляция запускается из корня шаблона. Поэтому пути верные. То что вы указываете на верхний уровень, значит, что текущий каталог компилятора неверный.

Бат файл лежит в корне шаблона. Уже думал может Node у меня не так настроен, переустанавливал не помогло. Пробовал через Scout-App, указывал источник папку `sass`, папку назначения `css` - та же ошибка: `Can't find stylesheet to import.`

И с путями что то совсем запутался:
файлы: `sass\lazy\3-colors.scss` и `sass\menu\menu2.scss`, например на одном уровне. Почему тогда в одном `@import 'berry/variables/variables';`, а в другом так: `@import './berry/variables/variables';`?

**Comment by maxsite** [comment]
Это указывает на один и тот же путь. Sass работает из каталога, откуда запущен. Дальше он смотрит каталог, относительно своего. То есть иерархия в @import идёт сверху вниз. То есть источник — это _корень шаблона + assets/sass_

**Comment by maxsite** [comment]
Можно попробовать в bat-файле явно указать каталог. Только в полном виде:

```
cd d:\domains\localhost\cms\application\maxsite\templates\default\
sass --update assets/sass/:assets/css/ --style compressed
```
Ну или запустить ручками из консоли и посмотреть какой там текущий каталог и что за ошибки.

**Comment by NtTel** [comment]
Может всё зависит от настроенного окружения для работы sass? Я так и не разобрался с путями инклудов. Вот тот же шрифт ubuntu из Шага 2 компилируется без проблем, путь что прописан при его настройке `../../fonts/ubuntu/` срабатывает без ошибок относительно файла `assets/sass/fonts/ubuntu.scss`, а не корня шаблона.

**Comment by maxsite** [comment]
В Sass `@import` работает относительно отслеживаемого каталога, а не каталога scss-файла. Поэтому в файле и не нужно указывать `../`-уровни. Может и есть какая-то настройка, но я не в курсе. Просто поставил Sass и он работает.

**Comment by NtTel** [comment]
Максим, подскажите пожалуйста файлы `block1.php`, `block2.php` и `block3.php` из шага 9-11 должны лежать там же в папке `myparts/footer/`?
Ошибка на сайте:
```
A PHP Error was encountered
Severity: Warning
Message: require(block1.php): failed to open stream: No such file or directory
Filename: file1/index.php(21) : eval()'d code
Line Number: 2
```

**Comment by maxsite** [comment]
Да, все файлы в одном каталоге.

**Comment by NtTel** [comment]
> Да, все файлы в одном каталоге.

Ок. С ошибкой разобрался. В настройках `File1` надо убрать галочку с `Использовать php-шаблонизатор (file1)`

**Comment by maxsite** [comment]
Да, точно. Я про это забыл упомянуть. :-) Вот так можно заменить подключение в `footer.php`

```
if ($fn = mso_fe('myparts/footer/block1.php')) require $fn;
if ($fn = mso_fe('myparts/footer/block2.php')) require $fn;
if ($fn = mso_fe('myparts/footer/block3.php')) require $fn;
```

**Comment by NtTel** [comment]
> В Sass `@import` работает относительно отслеживаемого каталога, а не каталога scss-файла. Поэтому в файле и не нужно указывать `../`-уровни. Может и есть какая-то настройка, но я не в курсе. Просто поставил Sass и он работает.

Разобрался!
Установил `Ruby Sass` (на сайте  sass заявлено что он более не поддерживается, поэтому его до этого не ставил) по уроку вашего курса [https://maxsite.org/course1/25](url)
Вот он все пути отрабатывает относительно папки запуска (папки шаблона).
А тот же node sass и другие учитывают все пути: так например если в `assets\sass\profiles\fontawesome5-lazy.scss` написано `@import 'fontawesome5/fontawesome';` так он и ищет `assets\sass\profiles\fontawesome5\_fontawesome.scss` соответственно.

**Comment by maxsite** [comment]
Хм... Даже не в курсе был, что они закрыли эту библиотеку. Вроде бы все на ней и сидели. Попробую поиграть другими вариантами, посмотрю что там.

**Comment by maxsite** [comment]
В общем, да, другое поведение теперь у Sass. То есть вы всё делали верно — нужно менять путь наверх, добавляя «../». Я проверил на Dart-sass https://github.com/sass/dart-sass/releases

Наверное нужно как-то явно указывать под какую библиотеку sass рассчитана компиляция.
