### ISSUE TITLE
MaxSite CMS 105     шаблон «Default»

### ISSUE THREAD

**Issue by website-999development** [maxsite/cms#401]
Здравствуйте.
Не могу поменять

Название сайта
Описание сайта
my@site.com
Франция, г. Париж

MaxSite CMS 105    
шаблон «Default»

**Comment by maxsite** [comment]
В настройках шаблона компоненты header1 и header2. Там меняете.

**Comment by website-999development** [comment]
спасибо. а еще насчет иконок
я сделал
https://www.facebook.com/ООО-Уралресурс-107494080610637/  | facebook | fab fa-facebook
и нигде не вывелось

**Comment by maxsite** [comment]
Где?

**Comment by website-999development** [comment]
а почему [social] не видно?

**Comment by website-999development** [comment]
в Соц.сети
Задайте иконки соц.сетей для своего сайта

**Comment by website-999development** [comment]
[social]
class = fab fa-skype t200 t-gray400 hover-t-cyan700
href = skype://8 800 500 70 83
title = Позвонить по Skype
[/social]

[social]
class = fab fa-whatsapp t200 t-gray400 hover-t-green700
href = https://wa.me/7 963 036-66-01
title = Позвонить по Whatsapp
[/social]

[social]
class = fab fa-telegram t200 t-gray400 hover-t-blue700
href = https://t.me/USER
title = Связаться через Telegam
[/social]

**Comment by maxsite** [comment]
иконка = адрес | подсказка | дополнительный css-класс

**Comment by website-999development** [comment]
facebook = //facebook.com/Сервисный-Центр-Дом-Быта-162198137814254/|  facebook | fab fa-facebook

так правильно?

**Comment by maxsite** [comment]
Укажите иконки в формате строки:
иконка = адрес \| подсказка \| дополнительный css-класс
Одна иконка в одной строке. 
Подсказка и дополнительный css-класс необязательны. 
Иконки задаются как css-классы. 
Например для Font Awesome 5: **fab fa-facebook**, fab fa-github, fab fa-skype, fab fa-twitter, fab fa-youtube.

**Comment by website-999development** [comment]
ну так и указал
но не видится

**Comment by website-999development** [comment]
Здравствуйте. так и не ответили
еще проблема удалить страницы сайта из результатов поиска.
# url Ответ Результат
1 https://remontpc96.ru/index.php 200 доступна
2 https://remontpc96.ru/ 200 доступна
3 https://remontpc96.ru// 200 доступна
4 https://remontpc96.ru/// 200 доступна
5 https://remontpc96.ru//// 200 доступна
6 https://remontpc96.ru///// 200 доступна
7 https://remontpc96.ru////// 200 доступна
8 https://remontpc96.ru/////// 200 доступна
9 https://remontpc96.ru//////// 200 доступна
10 https://remontpc96.ru///////// 200 доступна
11 https://remontpc96.ru////////// 200 доступна
12 https://remontpc96.ru/? 200 доступна
13 https://remontpc96.ru/index 200 доступна
14 https://remontpc96.ru/index/ 200 доступна
15 https://remontpc96.ru 200 доступна

**Comment by maxsite** [comment]
fab fa-facebook = фейсбук

**Comment by maxsite** [comment]
> 1 https://remontpc96.ru/index.php 200 доступна

Ну и что? Такие адреса не индексируются ПС.

**Comment by website-999development** [comment]
https://remontpc96.ru/index.php  https://remontpc96.ru/index/         эти не индексируются ПС?

**Comment by maxsite** [comment]
На них нет ни одной ссылки.

**Comment by website-999development** [comment]
Здравствуйте. Подскажите пожалуйста как сделать  верхней header шаблона. По факту  выводится только часть. 
[site]
name = Название сайта
name-class = t-robotoslab t180 t-gray800
description = <div class="t-gray600 pad40-l pad0-phone t-center-phone">Описание сайта</div>
icon = fab fa-google-wallet t200
effect = 1
[/site]

[block]
name = EMAIL
icon = fas fa-envelope
href = [siteurl]contact
link = contact@site.com
[/block]

[block]
name = PHONE
icon = fas fa-phone
href = tel:123123123
link = (012) 345-67-89
[/block]

[social]
class = fab fa-skype t150 t-gray400 hover-t-cyan700
href = skype://123123123
title = Позвонить по Skype
[/social]

[social]
class = fab fa-whatsapp t150 t-gray400 hover-t-green700
href = https://wa.me/123123123
title = Позвонить по Whatsapp
[/social]

[social]
class = fab fa-telegram t150 t-gray400 hover-t-blue700
href = https://t.me/USER
title = Связаться через Telegam
[/social]

[social]
class = fab fa-viber t150 t-gray400 hover-t-purple700
href = viber://chat?number=123123123
title = Связаться через Viber
[/social]

А выводится только часть. 

[site]
name = Название сайта
name-class = t-robotoslab t180 t-gray800
description = <div class="t-gray600 pad40-l pad0-phone t-center-phone">Описание сайта</div>
icon = fab fa-google-wallet t200
effect = 1
[/site]

[block]
name = EMAIL
icon = fas fa-envelope
href = [siteurl]contact
link = contact@site.com
[/block]

**Comment by maxsite** [comment]
Потому что вы всё в одну кучу смешали. В каталоге компонента есть файл `_default.txt`, посмотрите какие там параметры секций.

**Comment by website-999development** [comment]
а где каталог компонента

**Comment by website-999development** [comment]
сайт не  https://remontpc96.ru    а http://urvsp.0fees.us/   только что поставил с 0

**Comment by website-999development** [comment]
новый шаблон «Default» еще не изучал

**Comment by maxsite** [comment]
https://github.com/maxsite/cms/blob/master/application/maxsite/templates/default/components/header1/_default.txt
