### ISSUE TITLE
что то код не отрабатывает

### ISSUE THREAD

**Issue by jorjik** [maxsite/cms#402]
в админке
`[image=http://www.2donow.ru/blog/uploads/_pages/56/mini/mailspring-1.jpg]http://www.2donow.ru/blog/uploads/_pages/56/mailspring-1.jpg[/image]`
на сайте (вывод) тоже самое

скрины https://i.imgur.com/tRsgQw2.jpg https://i.imgur.com/x27fK6G.jpg
Version 102.6

**Comment by maxsite** [comment]
Включите плагин bb-кода.

**Comment by jorjik** [comment]
включен + вот такое работает:
[img]http://www.2donow.ru/blog/uploads/_pages/56/mailspring-1-png.png[/img]

**Comment by maxsite** [comment]
А, image - это плагин lightbox.
