### ISSUE TITLE
У вас работает плагин Поделится в Твиттер?

### ISSUE THREAD

**Issue by jorjik** [maxsite/cms#403]
У меня, походу - нет; линк формирует так
`http://twitter.com/home/?status=Лучший+бесплатный+почтовый+клиент+2020+http%3A%2F%2Fwww.2donow.ru%2Fblog%2Fpage%2Fluchshij-besplatnyj-pochtovyj-klient-2020`

**Comment by maxsite** [comment]
Какой-то левый линк. Правильный `https://twitter.com/intent/tweet?text=...`
