### ISSUE TITLE
Выбор подтипа записей типа PAGE

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#404]
Здравствуйте.
Подскажите пожалуйста, как реализовать код, который будет учитывать ещё и кастомные типы записей, которые создаются в админке.

Использую: if (is_type('page')) {код}.

**Comment by maxsite** [comment]
Этот код — тип данных. А типы записей получаются через mso_get_pages().

**Comment by maxsite** [comment]
https://max-3000.com/page/tipy-stranic-v-maxsite-cms

**Comment by W1SE95** [comment]
Да, это я знаю, читал документацию, показ сразу нескольких с пагинацией материалов по кастомным типам реализовал, но код то разный.

Я не программист, поэтому и интересуюсь данным вопросом, всего в написании одной строчки вся суть вопроса...

**Comment by maxsite** [comment]
Тогда просто указываете тип записей при получении в mso_get_pages().
