### ISSUE TITLE
sitemap fix need

### ISSUE THREAD

**Issue by jorjik** [maxsite/cms#405]
у меня плагин отдаёт карту сайта с урлами вида

`http://www.2donow.ru/blog/page/chto-rabotaet-v-seo`

а гугл индексирует без WWW
отсюда - дубли... как убрать?

p.s.  xml_sitemap v.3

**Comment by maxsite** [comment]
Возможно вы работаете в админке на www-адресе. Зайдите без него и отредактируйте любую запись. Файл обновится.
