### ISSUE TITLE
Показ шаблонных мета для определенного типа записей

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#406]
Здравствуйте.

Читаю документацию, там написано что есть специальный ключ - page_type, который можно указать в meta.ini(в папке CUSTOM в шаблоне) для отображения этой опции только для конкретного типа записей.

Я вот пробую:

[Наименование финансового оффера]
 options_key = textloan
 options_type = templates
 page_type = loans (это нужный тип)
 type = textfield
 description = ""
 default = "Кредит онлайн от Имя [Регион]"

И после выбора типа записи в её настройках И полной перезагрузки страницы - мета опция просто не показывается, что я делаю не так? Спасибо!

UPD:
https://max-3000.com/doc/template-meta

**Comment by maxsite** [comment]
Да, есть. Им уже сто лет никто не пользуется. Надо проверять работает эта возможность или нет.

**Comment by W1SE95** [comment]
> Да, есть. Им уже сто лет никто не пользуется. Надо проверять работает эта возможность или нет.

А почему не пользуются? 
Есть какой-то другой способ вбивать кастомные данные в настройках записи, а потом показывать их где нужно???

**Comment by W1SE95** [comment]
Просто много очень мета полей, под разные типы материалов, а всё в одной вкладке - это очень неудобно

**Comment by maxsite** [comment]
Это была хотелка уже не помню кого, поэтому и добавили в систему. Но реально она очень капризная и сложная в поддержке. наверное на каком-то обновлении сломалась. По мне так её бы вообще выпилить, а такие задачи решать на уровне шаблона. Есть специальный файл custom/my_meta.php, где можно сформировать массив $custom_meta с любыми условиями под любую свою задачу. Посмотрите application\maxsite\admin\plugins\admin_page\all_meta.php там видна его логика.

**Comment by W1SE95** [comment]
Понял вас. Спасибо за ответы!
