### ISSUE TITLE
Показ рейтинга записей в UNITS на главной

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#408]
Здравствуйте.

Подскажите пожалуйста план действий, чтобы я понимал откуда начинать, спасибо!

Очень не хватает показ рейтинга записей на главной и на страницах категорий, как на странице самой записи вывести - то легко (не стандартным способом), а вот здесь пока не получается...

**Comment by maxsite** [comment]
Рейтинг это что?

**Comment by W1SE95** [comment]
> Рейтинг это что?

Плагин rater, который идёт по дефолту

**Comment by maxsite** [comment]
Если нужен именно такой вывод, то его придётся делать вручную. Оптимальным вариантом будет создание для этого своей функции, которую вызывать в юнитах как [func@my_f|аргумент] или [func@my_f|аргумент1|аргумент2]
