### ISSUE TITLE
Несколько языков на сайте

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#409]
Здравствуйте.

Подскажите пожалуйста с чего стоит начать чтобы реализовать 2 версии сайта, например основной язык - русский, а второстепенный украинский, спасибо!

**Comment by maxsite** [comment]
Делаете на сервере подкаталог `uk`, в который ставите отдельной копией MaxSite CMS.

**Comment by W1SE95** [comment]
> Делаете на сервере подкаталог `uk`, в который ставите отдельной копией MaxSite CMS.

А как же линковка rel alternate uk с русской версии? (без этого ПС не правильно будут всё делать, проверенно)

Для категорий, для записей и других динамических страниц с адресами в юрл, которые мы указываем в админ панели.

**Comment by W1SE95** [comment]
> > Делаете на сервере подкаталог `uk`, в который ставите отдельной копией MaxSite CMS.
> 
> А как же линковка rel alternate uk с русской версии? (без этого ПС не правильно будут всё делать, проверенно)
> 
> Для категорий, для записей и других динамических страниц с адресами в юрл, которые мы указываем в админ панели.

<link href="https://site.com/" hreflang="x-default" rel="alternate" />
<link href="https://site.com/ua/" hreflang="uk" rel="alternate" />
<link href="https://site.com/" hreflang="ru" rel="alternate" />

**Comment by W1SE95** [comment]
<link href="https://site.com/" hreflang="x-default" rel="alternate" />
<link href="https://site.com/ua/" hreflang="uk" rel="alternate" />
<link href="https://site.com/" hreflang="ru" rel="alternate" />

И так необходимо в коде каждой страницы указать, в ручную сделать это не получится + через чур геморно и 100% не правильно

**Comment by maxsite** [comment]
Цепляетесь к хуку head и там выводите всё что угодно. Если slug у записей будет один и тот же, то можно автоматом прописывать адреса. Если разные, то вводите meta-поле к записи, где указываете адрес другой языковой версии.

**Comment by W1SE95** [comment]
> Цепляетесь к хуку head и там выводите всё что угодно. Если slug у записей будет один и тот же, то можно автоматом прописывать адреса. Если разные, то вводите meta-поле к записи, где указываете адрес другой языковой версии.

Спасибо Макс, все на самом деле просто!)
