### ISSUE TITLE
Перенос данных с БД основного сайта в БД другого (мультисайтовость)

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#410]
Здравствуйте.

Напоминаю суть: есть сайт на русском языке в подкаталог установил ещё одну копию CMS (укр версия сайта).

Со ссылками и head разобрался, возник следующий вопрос, каким лучше образом показывать на основной версии сайта и на украинской версии одни и те же данные по просмотрам, рейтингу и коментам?

Потому как если это через чур "невыполнимо", тогда это мероприятие однозначно убыточное изначально как по времени затратам так и логике.

UPD:
Используются разные БД и пользователи.
Возможно нужно было оба сайта в одну базу занести, только второй сайт указать с другим префиксом для бд?

Я просто раньше сталкивался с таким только с ВП, там можно мультисайтовость включить и слинковать всё.

**Comment by maxsite** [comment]
В ВП и денег на разработку выделяется на 50000000 порядков больше. :)

Разные сайты, базы, естественно всё будет раздельно.

**Comment by W1SE95** [comment]
Макс, постойте :)))

Мне ведь по факту нужно показывать только разный контент в записях, я вот в подпапке в конфиге указал данные с основного сайта (корень) и теперь нужно просто каким то образом просто добавить одно дополнительное поле для самого контента записи на другом языке с сохранением в БД.

Так ведь можно? )

**Comment by maxsite** [comment]
Такой подход реализуется немного по другому. 
- язык переключается с помощью куки. Посетитель выбирает иконку страны, скрипт прописывает куку языка. Либо язык определяется на основе предпочтений браузера.
- при выводе сайта смотрится эту кука и подключается lang-перевод шаблона. Какие-то фразы можно будет автоматом перевести.
- текст записи задается сразу в двух языках через какой-то разделитель. При выводе он через регулярку пропускается и выводится только нужный вариант.

Проблемы. Непонятно как будут переводиться рубрики, метки. Заголовок записи тоже должен переводиться, хотя можно через метаполе сделать. Часть блоков придётся разделять под разные языки. Так же непонятно как будет происходить индексация поисковиками — по одному url отдается разные контент.

**Comment by W1SE95** [comment]
> Такой подход реализуется немного по другому.
> 
> * язык переключается с помощью куки. Посетитель выбирает иконку страны, скрипт прописывает куку языка. Либо язык определяется на основе предпочтений браузера.
> * при выводе сайта смотрится эту кука и подключается lang-перевод шаблона. Какие-то фразы можно будет автоматом перевести.
> * текст записи задается сразу в двух языках через какой-то разделитель. При выводе он через регулярку пропускается и выводится только нужный вариант.
> 
> Проблемы. Непонятно как будут переводиться рубрики, метки. Заголовок записи тоже должен переводиться, хотя можно через метаполе сделать. Часть блоков придётся разделять под разные языки. Так же непонятно как будет происходить индексация поисковиками — по одному url отдается разные контент.

На счёт индексации: почему по одному юрл?
У меня основной сайт - site.com, укр версия с той же базой на site.com/ua/.
В сайтмап хмл - добавляться доп.папка в пути, все ссылки на укр версии тоже идут через доп.папку по автомату.

Или же я не понял о чём вы.
На счёт наименования записей - да, я так и хотел через мета, на счёт меток и рубрик - вообще не подумал....

Буду думать, возможно что то да и получится, понимаю что костыль, но использовать обычный скриптик от гугла qtranslate - очень не удобно и не гибко.

**Comment by maxsite** [comment]
Кука — это одна копия сайта.
