### ISSUE TITLE
Пример реализации функции [func@my_f] в units на главной

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#411]
Доброго времени суток в очередной раз!

Вы можете пожалуйста показать пример реализации своих функций:
 		/**
		 * произвольная php-функция [func@my_f]
		 * до 3-х аргументов [func@my_f|аргумент] или [func@my_f|аргумент1|аргумент2]
		 * в функцию передаём текущую page и аргументы. Функция должна быть уже объявлена
		 * function my_f($p, $a1 = 0, $a2 = 10, $a3 = 0) {...}
		 */
В документации не слова вообще на счет этого...
Где её алгоритм нужно прописывать (в каком файле) и как её правильно выводить в самих units? Спасибо!

**Comment by maxsite** [comment]
Используется в любых юнитах. Например в виде строчки:

`line3 = [func@my_rating|1|10]`

Либо в виде php-кода, например в info-top:

`$p->line('[func@my_rating|1|10]');`

В своём `custom\my-template.php` определяете функцию `my_rating()` с 4-я аргументами. Первый это массив данных записи, остальные для своей внутренней кухни:

```
function my_rating($p, $a1 = 0, $a2 = 10, $a3 = 0)
{
    pr($p); // это массив всех данных записи
... делаем что нужно
   return $out; // отдаем html-вывод
}
```
