### ISSUE TITLE
Систематизация мета полей в настройках записи во вкладке "Шаблонные"

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#412]
Здравствуйте.

Во первых спасибо огромное за Ваши коментарии на прошлые мои вопросы, всё реализовал, всё функционирует и даже добавил больший функционал чем планировал 👍 

Теперь стал следующий вопрос, у меня образовалось просто тьма мета полей в настройках записи (добавлял через custom/my_meta.ini), каким то образом можно визуально добавить какие-то секции или hr горизонт линии для разделения мета полей по группам?
![Screenshot_3](https://user-images.githubusercontent.com/60783381/96248913-0ad28c80-0fb5-11eb-8080-f00bed302c0b.png)

**Comment by maxsite** [comment]
Боюсь, что никак. Просто ничего не предусмотрено.

**Comment by W1SE95** [comment]
> Боюсь, что никак. Просто ничего не предусмотрено.

https://max-3000.com/doc/template-options
А то что в документации про секции в опциях?
Или же это не актуально уже?

**Comment by maxsite** [comment]
Для опций актуально. Для мета — нет. Там отдельный обработчик.

**Comment by W1SE95** [comment]
> Для опций актуально. Для мета — нет. Там отдельный обработчик.

Понял. Ну что ж, придется самому тогда допилить попробовать)

Спасибо за ответы!
