### ISSUE TITLE
Вопрос по пагинации для ПС (плагин: pagination 2.1)

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#413]
Здравствуйте.
Подскажите пожалуйста, каким-то образом можно на страницах пагинации НЕ показывать описание конкретной категории?

Потому что получается дубль по контенту на страницах пагинации...
![Screenshot_4](https://user-images.githubusercontent.com/60783381/96499029-85213c00-1255-11eb-84f2-17dcab357d35.png)

**Comment by maxsite** [comment]
Использовать свой type\category\units\category-header.php в шаблоне.Там прописать условия вывода. Либо там же подобрать подходящий type_foreach-файл.
