### ISSUE TITLE
Ошибка в плагине SHJS - Syntax Highlighting

### ISSUE THREAD

**Issue by smastykov** [maxsite/cms#416]
PHP 7.4., CMS v.107

В админ-панели в настройках плагина выводится сообщение об ошибке:

A PHP Error was encountered
Severity: 8192
Message: implode(): Passing glue string after array is deprecated. Swap the parameters
Filename: shjs/index.php
Line Number: 55

Плагин работает, но такая ошибка присутствует.

**Comment by maxsite** [comment]
Спасибо, поправлю.
