### ISSUE TITLE
Использование 1-го каталога uploads для двух сайтов с 1 БД

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#417]
Здравствуйте!
Есть 2 сайта, русская версия - site.com, укр. версия - site.com/ua

Можно ли указать для двух сайтов один каталог для использования изображений?

Я подразумеваю что это делается в данном файле:
![Screenshot_1](https://user-images.githubusercontent.com/60783381/97804733-6e69e480-1c5a-11eb-92c2-0c4f44537f4b.png)

**Comment by maxsite** [comment]
Можно тут, хотя uploads достаточно жестко прописан и может где-то явно указываться ещё.
