### ISSUE TITLE
Точка в начале названия записи 

### ISSUE THREAD

**Issue by smastykov** [maxsite/cms#418]
PHP 7.4., CMS v.107.1

Понадобилось сделать статью с таким названием ".htaccess что это такое?" При сохранении запись не сохраняется. Виной всему оказалась точка в начале названия записи. Не знаю баг это или фича, но в более старых версиях работало.

**Comment by maxsite** [comment]
Проверил, всё сохраняется.

**Comment by smastykov** [comment]
А у меня ни в какую не хочет. У провайдера сервер на линуксе, может из-за его настроек. Если что, могу дать доступ в админку чтобы разобраться.

**Comment by maxsite** [comment]
При чём тут провайдер? Может какой-то плагин так работает.

**Comment by smastykov** [comment]
Активные плагины:
addzakl 4
bbcode 9
captcha 4
catclouds 3.1
down_count 1.3
faq 1.3
forms 5.5
last_pages_unit 4
links 1.4
meta_robots 1
open_graph 1.3
page_parent 1.1
pagination 2.1
parser_simple 2020.08.26
range_url 3
rater 2.2
shjs 3.1
tagclouds 1.2
ushki 2
xml_sitemap 3

**Comment by maxsite** [comment]
Сложно сказать. Я ошибки не вижу, воспроизвести не получается.
