### ISSUE TITLE
Универсальный http-протокол и rel=canonical

### ISSUE THREAD

**Issue by alexvishweb** [maxsite/cms#420]
Эти 2 основные настройки мета-полей не работают вместе - в canonical получается href="//sitename.com/, а должно быть href="http://sitename.com/" или href="https://sitename.com/".
Lighthouse ругается.

**Comment by maxsite** [comment]
Значит отключите универсальный протокол в опциях.

**Comment by alexvishweb** [comment]
Да, это понятно, просто сообщаю об ошибке, чтобы ее можно было исправить или отметить этот момент в описании этих настроек, например.

**Comment by maxsite** [comment]
Универсальный протокол, это в любом случае костыль для проблемного https. Использовать нужно в особых случаях.
