### ISSUE TITLE
Редактироавние даты публикации

### ISSUE THREAD

**Issue by borzakap** [maxsite/cms#424]
при выборе даты публикации записи селект года заканчивается на 2020.... где хотя бы добавить еще пару лет? :-)

**Comment by maxsite** [comment]
Обновите MaxSite CMS.

**Comment by W1SE95** [comment]
Или можно было просто поправить одну строку в файле: 
путь: .../application/maxsite/admin/plugins/admin_page/post-edit-functions.php
Строка: $date_all_y = array();
Ниже будет диапазон дат =)

**Comment by maxsite** [comment]
Обновление MaxSite CMS на сайте — пара секунд.
