### ISSUE TITLE
Скачать старые версии

### ISSUE THREAD

**Issue by Alex-JTI** [maxsite/cms#425]
По причине отсутствия возможности переделывать шаблон под новые версии, я хочу скачать старые.
В частности 99 и 104. Однако ссылки на скачивание старых версий с https://max-3000.com/ были убраны.

Помогите, пожалуйста.

**Comment by maxsite** [comment]
https://github.com/maxsite/cms/releases

**Comment by Alex-JTI** [comment]
Спасибо большое, то что надо!
Второй вопрос - дефолтный шаблон от версии 0,96 может работать максимально с какой версией движка?

**Comment by maxsite** [comment]
С любой. Если что там правок на пару минут.

**Comment by Alex-JTI** [comment]
Благодарю!
Меня смутило то, что с 100 используется новый шаблон (объем изменений относительно большой) , а со 105 версии используется новый шаблон MF, и я так понял, что старые версии шаблонов не поддерживаются.

**Comment by maxsite** [comment]
Не трогайте новый defaulе-шаблон. Свой ставите на новую версию MaxSite CMS. Вносите правки в свой шаблон — там их будет немного.

**Comment by Alex-JTI** [comment]
Очень хорошая новость, благодарю!
