### ISSUE TITLE
После апгрейда на v.107.5 множественные ошибки

### ISSUE THREAD

**Issue by Alex-JTI** [maxsite/cms#426]
Обновил тестовый сайт с v104 на v107.5 универсальным способом.
Теперь на всем сайте множественные ошибки с любым шаблоном, в том числе дефолтным, который идет с новой версией:
```
A PHP Error was encountered
Severity: Notice

Message: Undefined index: default_lang

Filename: shjs/index.php

Line Number: 146
```
Кроме того, время и память в футере не выводятся:
Время: {elapsed_time} | SQL: 19 | Память: {memory_usage}

Пример http://maxsite.hww.ru/
На хостинге используется PHP 7.3.26

Когда возвращаю с старым папкам - все ок.
Подскажите, что нужно и где исправить?

**Comment by maxsite** [comment]
Сохраните опции в плагине shjs.

**Comment by Alex-JTI** [comment]
Спасибо, это помогло.
Обнаружилась еще проблема: не могу зайти с правильным логином и паролем в 107,5, однако если я переключаю папки на 104 версию, то могу с ними же зайти, после чего могу переименовать папки обратно не выходя из админки и работать уже в новой версии.
Ощущение, что в новой версии пароль хешируется иначе и не принимается.
Подскажите, что делать?

**Comment by maxsite** [comment]
Скорее всего не перенесли секретную фразу.

**Comment by Alex-JTI** [comment]
Да, все верно, обновил - заработало, спасибо.

Сейчас пытаюсь запустить старый шаблон MAX Elevation 2.0 и MAX Skyline 3.0 на 107,5 движке по вашему совету. 
Ошибки 500 такие:
[Sat Jan 30 16:16:17.428607 2021] [lsapi:error] [pid 729] [client 93.92.199.232:31561] [host maxsite.hww.ru] Backend fatal error: `PHP Fatal error:  Cannot declare class Page_out, because the name is already in use in /var/www/fms190/data/www/maxsite.hww.ru/application/maxsite/templates/max-skyline/stock/page-out/page-out.php on line 156\n`
`[Sat Jan 30 16:16:22.822881 2021] [lsapi:error] [pid 23716] [client 93.92.199.232:32089] [host maxsite.hww.ru] Backend fatal error: PHP Fatal error:  Cannot declare class Page_out, because the name is already in use in /var/www/fms190/data/www/maxsite.hww.ru/application/maxsite/templates/max-elevation/stock/page-out/page-out.php on line 10\n`

Что в коде шаблонов подправить?

**Comment by maxsite** [comment]
Там всё нужно менять. Очень старый шаблон.

**Comment by Alex-JTI** [comment]
Очень жаль, судя по своему до версии 104 они совместимы?

**Comment by maxsite** [comment]
Сомневаюсь. Шаблон 2012 года. Кому вообще нужно это старьё...

**Comment by Alex-JTI** [comment]
Ну дело в том, что задача перевести за день на новый сервер с PHP 7 старые сайты, времени переделывать шаблоны нет сейчас.

**Comment by maxsite** [comment]
Купить MF. Поставить. Выбрать из 14 компонентов шапок. Выбрать цвет из 11 вариантов. Настроить вывод главной (десятки вариантов).

**Comment by Alex-JTI** [comment]
C этим понятно.

Также хочу зарепортить об ошибке default шаблона от версии v104, который не совместим с 107.5
На страницах page ошибка PHP:
```
Message: require_once(/var/www/fms190/data/www/maxsite.hww.ru/application/maxsite/shared/stock/thumb/thumb.php): failed to open stream: No such file or directory

Filename: type_foreach/page-other-pages-out.php

Line Number: 7
```

Это достаточно странно, потому что шаблон от версии 99 (Default v8) работает с 107 прекрасно.

**Comment by maxsite** [comment]
Наверное можно вообще перестать писать о релизах MaxSite CMS, если их никто не читает... :( https://max-3000.com/page/maxsite-cms-105

**Comment by Alex-JTI** [comment]
Я лично прочитал о 10 релизах за раз, поэтому увы, не могу запомнить, в каком были какие изменения. Поэтому спасибо за ссылку,
