### ISSUE TITLE
Как изменить виджет

### ISSUE THREAD

**Issue by ottawa1** [maxsite/cms#427]
Приветствую. В начале 2020 года создал сайт на MAXSITE. В сайдбаре вверху установил текстовый виджет  "C наступившим 2020 годом! " Сейчас смотрю надо бы изменить дату. Но сколько не пробовал ничего не получается. Посоветуйте как быть. сайт http://junior.ruspalom.ru/

**Comment by maxsite** [comment]
Входите в настройки виджета, редактируете, сохраняете.

**Comment by ottawa1** [comment]
виджет называется text_block. Пробовал его Выключить или Деинсталлировать - ничего не получается. Так и остается в списке активных плагинов.  Есть же какой то способ его удалить ?  В настройки тоже входил ничего не меняется.

**Comment by maxsite** [comment]
Если настройки не сохраняются, возможно проблема в базе данных. Проверьте её через phpMyAdmin. Либо место не хостинге закончилось.

**Comment by ottawa1** [comment]
Вижу вы сами удивляетесь. места на хостинге много. в базе ничего не увидел особенного. скачал базу и все файлы проверю на Open Server заодно и перейду на новую версию 107

**Comment by ottawa1** [comment]
проверю на локальном сервере

**Comment by maxsite** [comment]
Ещё посмотрите лог ошибок.

**Comment by ottawa1532** [comment]
Добрый день. Кроме меня пробовал разобраться еще один программист.  Ничего не получилось. Установил на хостинг еще версию 107.5 http://prikos.ruspalom.ru  Установилось нормально. При попытке перейти в админ панель /admin дает ошибку 404 .В чем причина?

**Comment by maxsite** [comment]
ЧПУ не работает. См. .htaccess

**Comment by ottawa1532** [comment]
.htaccess подобрал в админпанель захожу. Теперь другое. Вид админпанели такой как будто не подключено css (таблицы стилей). В чем причина?
![admin](https://user-images.githubusercontent.com/79406182/108757349-c8b8e900-755a-11eb-9dbd-dd0071955191.jpg)

**Comment by maxsite** [comment]
Не подключены таблицы стилей. Проверяйте доступность css-файлов.

**Comment by ottawa1532** [comment]
после логина в админку все запросы к сайту начинают транслироваться в index.php, даже если это запрос к физически существующему файлу. Но возможно тут не в цмске проблема, а в каких то настройках сайта, но я  не могу понять в чем именно. Запускаю на open_server_5_3_7_basic_full  все нормально

**Comment by ottawa1532** [comment]
на локальном сервере админка нормально показывается.
