### ISSUE TITLE
Отложенная загрузка изображений

### ISSUE THREAD

**Issue by Nina150** [maxsite/cms#428]
Добрый день! 
У меня на сайте много картинок, и они долго загружаются. Я бы хотела сделать отложенную загрузку изображений. 
Это как-то реализовано в Maxsite? Подскажите, пожалуйста.

**Comment by eugenemir1991** [comment]
Нет это никак не реализовано, но можно реализовать. Есть 2 варианта 1. Использовать js. 2. использовать picture и создавать несколько картинок и для нужного устройства грузить свою. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by Nina150** [comment]
Спасибо большое!!! 
Пойду разбираться.
