### ISSUE TITLE
Добавить ссылки на редактирование и удаление записи в админке

### ISSUE THREAD

**Issue by dignityinside** [maxsite/cms#43]
Предлагаю добавить в "Содержимое" -> "Все записи" под каждую запись ссылки на редактирование и удаление записи (мелочь, а удобно).

**Comment by vimruler** [comment]
Ну вроде же есть ссылка на редактирование, нет? А вот с удалением вопрос - насколько безопасно будет размещение таких ссылок (случайное удаление) и как часто приходится удалять, чтобы перегружать интерфейс ссылками? Лично я редко удаляю записи, ибо предпочитаю наполнять их другим содержимым и снова публиковать.

**Comment by dignityinside** [comment]
Сейчас запись можно отредактировать только если нажать на заголовок, что не совсем очевидно. Удаления записи будет в любом случаи с подтверждением, поэтому случайного удалить не получится. Как вариант можно добавить две маленькие иконки, они не займут много места.

**Comment by cuprum** [comment]
@dignityinside По поводу удаления. На форуме уже как-то обсуждалась такая возможность. Лучше было бы добавить чекбокс рядом с каждой записью, как в разделе "Комментарии".

**Comment by dignityinside** [comment]
@cuprum ну или хотя бы так, хотя это не совсем удобно когда записей много, нужно скролить вниз.

**Comment by maxsite** [comment]
Я предлагаю, перед тем, как что-то менять,предлагать дизайн и компоновку админ-страницы. Саша, рисуй примеры, будем выбирать. А так это всё абстракция.

**Comment by dignityinside** [comment]
@maxsite ну как-то так: https://yadi.sk/i/wjIs6yqvg2P3o, можно сделать чтобы при наведении мышки на бокс, ссылки появлялись, при потери фокуса уходили.

**Comment by cuprum** [comment]
@dignityinside По-моему ссылка "редактировать" не нужна. Сейчас же есть ссылка "просмотр"; Вот если б ее не было, тогда действительно стало бы не понятно, куда ведет ссылка с названием записи.

**Comment by dignityinside** [comment]
@cuprum как вариант можно вообще сделать настройки, чтобы каждый мог выбирать что хочет видить :)

**Comment by maxsite** [comment]
Что-то я сомневаюсь, что это вообще нужно. Это очень редкая операция. Дополнительные ссылки только излишне перегрузят интерфейс.

**Comment by vimruler** [comment]
Кстати, если есть желание, то можно сделать плагин, который будет навешивать желаемые ссылки.

**Comment by dignityinside** [comment]
@vimruler вот это тоже хороший вариант.
