### ISSUE TITLE
Дата публикации при обновлении сбрасывает на 2005 год

### ISSUE THREAD

**Issue by raptorcc** [maxsite/cms#431]
Добрый день, столкнулся с проблемой при обновлении даты публикации сбрасывается на 2005 год.
![1](https://user-images.githubusercontent.com/46967333/109598871-62c4f680-7b44-11eb-9422-8d45292280c7.png)
 Из списка даты начинается 2005 год заканчивается 2020 год.
PHP 7.0 Maxsite 103, пробывал обновить до новой версии проблема остается

**Comment by maxsite** [comment]
Обновитесь до последней версии MaxSite CMS.
