### ISSUE TITLE
как вывести страницу с блогом на произвольной странице?

### ISSUE THREAD

**Issue by kelemator** [maxsite/cms#432]
есть сайт, на котором я планирую на главной разместить определенную "страницу" - сделал это с помощью юнитов, кое-как разобрался, вроде работает.
но теперь у меня нет главной страницы, с которой можно было бы листать страницы блога. то есть нужно, чтобы блог выводился по ссылке типа site.com/blog (или хотя бы site.com/page/blog). нужно чтобы было станадртно - с пагинацией и всем прочим.
как это сделать? шаблон - дефолтный.

(если можно, то пожалуйста, как для дурачков - какой файл взять, что с ним сделать и т.д. а то, боюсь, моих знаний на слишком умное объяснение не хватит )) )

всем заранее спасибо :)

**Comment by eugenemir1991** [comment]
День добрый. Нужно создать свой файл. type/blog/blog.php .
Внутрь него копируем код home. Можно еще отдельные настройки прикрутить создав соответственно файл опций и.т.д...
Адрес будет yousite.com/blog

**Comment by kelemator** [comment]
файл сделал, но не понял, что в него нужно скопировать. у меня в наличии только папка "type\home\", в которой лежат файлы units

и сразу вопрос, после всех манипуляций никакой страницы в админке создавать не нужно? адрес сразу должен открываться?

**Comment by eugenemir1991** [comment]
1. исходники "хомяка" тут: cms/application/maxsite/shared/type/home/  https://github.com/maxsite/cms/blob/master/application/maxsite/shared/type/home/home.php
2. Нет ничего создавать не нужно.

**Comment by eugenemir1991** [comment]
Надеюсь теперь достаточно понятно все описал?

**Comment by kelemator** [comment]
сделал!! спасибо :) открывается!!!
пока что там дублируется то, что и на главной, но, кажется, я уже понял, что там лишнее убрать. поэкспериментирую дальше! спасибо :)

**Comment by eugenemir1991** [comment]
Отлично. Всегда рад помочь! Да уберите код юнитов и оставьте только то что вам нужно для вывода блогов.
