### ISSUE TITLE
A PHP Error was encountered. Filename: d2/functions.php

### ISSUE THREAD

**Issue by v0vas** [maxsite/cms#433]
Всем привет!
Обновил через автообновление до версии 107.5 и включил тему D2. Теперь сайт вообще не открывается, появляется такая ошибка на главной:
> A PHP Error was encountered
> Severity: Warning
> 
> Message: require_once(/home/data/www/mysite.su/application/maxsite/shared/functions/template.php): failed to open stream: No such file or directory
> 
> Filename: d2/functions.php
> 
> Line Number: 18

Версия php 7.3.26
И далее:

> Fatal error: require_once(): Failed opening required >'/home/data/www/mysite.su/application/maxsite/shared/functions/template.php' >(include_path='.:/usr/share/pear:/usr/share/php') in >/home/data/www/mysite.su/application/maxsite/templates/d2/functions.php on line 18

Скрин: https://i114.fastpic.ru/big/2021/0308/5f/eac50034260c9fc08b5aa5f9cdc2155f.png

**Comment by eugenemir1991** [comment]
Слишком старый шаблон... Включите дефолтный.

**Comment by v0vas** [comment]
А как включить? Ни одна страница не открывается, везде такая ошибка, даже в админке

**Comment by eugenemir1991** [comment]
В админку то зайти можно?

**Comment by v0vas** [comment]
> В админку то зайти можно?

Нет, выше написал. Поищу, где можно в бд поменять шаблон

**Comment by eugenemir1991** [comment]
Вроде если удалить тему она автоматом сбросится на дефолтную.

**Comment by v0vas** [comment]
Отлично, помогло! Спасибо!
