### ISSUE TITLE
Работают не все иконки соц. сетей.

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#435]
Добрый день. Я уже всю голову себе сломал. Но у меня почему то не работают иконки социальных сетей в том виде в котором указано в документации. К примеру, если я пишу "fa-envelope-o" иконки с конвертом нет, но если я напишу "envelope-o" (без кавычек и то и то) тогда иконка с конвертом появляется. А вот к примеру иконка телеграмма не хочет появляться ни в каком виде. И "fa-vk" тоже приходится писать просто "vk". Что я мог отредактировать, что сломал? Я пробовал менять шаблон и тогда иконки вообще не отображаются... Хотя в коде они есть.

![icons](https://user-images.githubusercontent.com/1073471/111282304-e99ec680-864e-11eb-9910-fa0a82feaadf.jpg)

**Comment by KsenZ** [comment]
FontAwesome в шаблоне подключен?
Для VK иконка подключается как "fa fa-vk", т.е. не просто "fa-vk"

**Comment by Fafofu** [comment]
Я же написал. Что если написать как в документации то иконки не отображаются... Шрифт где подключать надо?
![Opera Снимок_2021-03-16_121413_www fafofu ru](https://user-images.githubusercontent.com/1073471/111284521-3edbd780-8651-11eb-9a33-0e36eec0ff8d.png)
![Opera Снимок_2021-03-16_121353_www fafofu ru](https://user-images.githubusercontent.com/1073471/111284528-3edbd780-8651-11eb-83eb-624eece511de.png)

**Comment by KsenZ** [comment]
На последней версии CMS, и Default шаблоне, это выглядит так
![image](https://user-images.githubusercontent.com/643267/111285116-5fb52480-8673-11eb-9897-f79182f8815b.png)

**Comment by Fafofu** [comment]
Оооо. Я перетащил из шаблона по умолчанию этот стиль в свой шаблон и подключил. Вот, что происходит если написать название иконки как в документации. =D
![Opera Снимок_2021-03-16_122642_www fafofu ru](https://user-images.githubusercontent.com/1073471/111286202-01784980-8653-11eb-899c-fecc35754424.png)

**Comment by Fafofu** [comment]
Так, а с шаблоном по умолчанию всё работает хорошо... Круг сужается. Но что я именно сломал :(

**Comment by KsenZ** [comment]
Только стиль? А сами шрифты?
templates/default/assets/fonts/fontawesome5

**Comment by Fafofu** [comment]
Перенёс... Не помогло... что-то ещё...

**Comment by maxsite** [comment]
Смотрите ещё компонент _social, как там задаются классы иконок.

**Comment by Fafofu** [comment]
Да, я PHP от туда перенёс в мой шаблон... не помогло... У меня кстати есть ещё вот такой шрифт "fontawesome" и он на сайте используется. Он отображает иконки стандартные. Дату там, рубрики... Похоже у меня очень старый шаблон...

**Comment by Fafofu** [comment]
В старом вот так: 
`<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
/*
	(c) MaxSite CMS, http://max-3000.com/
	
	вывод иконок
	Файл использовать в других компонентах
	используется глобальная опция social.templates
	
	Иконки произвольные из http://fortawesome.github.io/Font-Awesome/icons/

	иконка = адрес
	иконка = адрес | подсказка
	иконка = адрес | подсказка | дополнительный css-класс
	
	facebook = //facebook.com/my | Фейсбук
	
*/`

В новом вот так:
`<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
/*
	(c) MaxSite CMS, https://max-3000.com/
	
	Вывод иконок
	Файл использовать в других компонентах
	Используется глобальная опция social.templates
	
	Иконки произвольные из https://fontawesome.com/icons?d=gallery&m=free
	Поскольку используется FontAwesome 5, то нужно указывать двойной класс иконки 

	иконка = адрес
	иконка = адрес | подсказка
	иконка = адрес | подсказка | дополнительный css-класс
	
	fab fa-facebook = https://facebook.com/my | Фейсбук
	fas fa-rss = https://site.com/feed | RSS
	
*/`

**Comment by maxsite** [comment]
FA есть 4-й версии, он раньше использовался в default-шаблоне. Задавать иконки можно было так: facebook. В _social добавлялся префикс и получался css-класс i-facebook. В новом используется FA5, где класс задаётся как принято в FA5 fab fa-facebook.

Какие у вас в шаблоне классы иконок смотрите в css-файле. Такие и задавайте в опции. Также проверьте, чтобы css-файл иконок был доступен (наверное css-профиль). А также сам файл шрифтов, указанный в этом css-файле. Если всё загружается, значит иконки работают. В FA4 нет многих иконок  из FA5. Смотрите их сайт, чтобы точно узнать есть есть, а не гадать.

**Comment by Fafofu** [comment]
Понятно. Древний шаблон у меня :(
