### ISSUE TITLE
PHP 7.2 MaxSite 107.5 Ошибка при очистки кеша.

### ISSUE THREAD

**Issue by Fafofu** [maxsite/cms#436]
Обновился в ручную с версии 106 до 107.5 Вроде вначале было всё хорошо, но потом при повторной очистки кеша стала появляться вот такая ошибка:

![Opera Снимок_2021-03-16_152442_www fafofu ru](https://user-images.githubusercontent.com/1073471/111308903-4eb4e500-866c-11eb-9cf8-4f1d0f8de48f.png)

**Comment by maxsite** [comment]
Что-то не так с каталогом `uploads/_pages`. Создайте новую запись, если каталог не появился, сделайте его вручную и поставьте права 777.

**Comment by Fafofu** [comment]
Да нет. Всё в порядке и с папкой и с правами. При создании новой записи там появилась новая папка с номером записи.
![Opera Снимок_2021-03-16_155228_home fafofu ru](https://user-images.githubusercontent.com/1073471/111311744-a143d080-866f-11eb-8f24-43ad41fcc6bf.png)

**Comment by maxsite** [comment]
Тогда не знаю. Возможно что-то с правами файлов — скрипт не видит файлов и вываливается с ошибкой.

**Comment by Fafofu** [comment]
Он именно на папку "upload" ругается?

**Comment by maxsite** [comment]
Я не знаю. В этой строчке просто получается список файлов `uploads/_pages` и возвращается обычный массив. У вас значит не массив, а что-то другое. Возможно скрипт не имеет прав на чтение файлов или ещё какие-то права...

**Comment by KsenZ** [comment]
У меня есть пара вопросов:
1. На скришоте не видно, какие права на директорию.
2. Что у вас за хостинг? Доступ к SSH (консоли) есть? Если да, то выполните команду:
`ls -la uploads`
`ls -la uploads/_pages`
Конечно же находясь в корне директории сайта.
3. Ну и судя по ошибке, это может зависеть, от версии PHP. Я знаю, что вы писали о PHP 7.2, можно скриншот вывода phpinfo() ?

**Comment by maxsite** [comment]
При чём тут мой хостинг??? Смотрите логи своего,может там есть информация. Я не могу повторить ошибку, помочь не смогу.

**Comment by KsenZ** [comment]
Вопрос адресовался к "топикстартеру", не к вам :)

**Comment by Fafofu** [comment]
> У меня есть пара вопросов:
> 
> 1. На скришоте не видно, какие права на директорию.
> 2. Что у вас за хостинг? Доступ к SSH (консоли) есть? Если да, то выполните команду:
>    `ls -la uploads`
>    `ls -la uploads/_pages`
>    Конечно же находясь в корне директории сайта.
> 3. Ну и судя по ошибке, это может зависеть, от версии PHP. Я знаю, что вы писали о PHP 7.2, можно скриншот вывода phpinfo() ?

Вы знаете, действительно, обновлённая версия тут не при чём... Я вернул старую версию которая работала без ошибок, и ошибка сохранилась... У меня хостинг на NAS Synology дома на полке стоит... SSH то есть. Но там есть и доступ к папкам через графический интерфейс... Для проверки проблем с доступом я дал полные права для любого пользователя и это не помогло... И ещё меня смущает, что в админке в разделе "Upload" есть папки которых не существует... Вот картинку прилагаю. 

![Opera Снимок_2021-03-17_093852_www fafofu ru](https://user-images.githubusercontent.com/1073471/111425724-a010b300-8704-11eb-9742-c751b839bcc3.png)
![Opera Снимок_2021-03-17_093738_home fafofu ru](https://user-images.githubusercontent.com/1073471/111425728-a0a94980-8704-11eb-9be7-4e6b393a2852.png)
![uploads](https://user-images.githubusercontent.com/1073471/111425731-a141e000-8704-11eb-822e-6bb35f8e681c.jpg)

**Comment by Fafofu** [comment]
Кстати. https://qna.habr.com/q/637359

**Comment by Fafofu** [comment]
Насколько я вижу, тут написано в "admin.php" что это строка для удаления пустых папок. И пустые папки отлично удалятся. Но ошибка пишется при этом...

**Comment by Fafofu** [comment]
В Apache ошибок нет в момент этой ошибки... :(
