### ISSUE TITLE
Перенести пункт меню "Комментарии" в блок "Содержимое"

### ISSUE THREAD

**Issue by dignityinside** [maxsite/cms#44]
Предлагаю перенести пункт меню "Комментарии" в блок "Содержимое", ведь комментарии относятся именно к записям, и логичнее было бы если они находились в блоке "Содержимое", а не как сейчас, в блоке "Пользователи".

**Comment by vimruler** [comment]
Да, логичное предложение. Поддерживаю.

**Comment by denis-skripnik** [comment]
Поддерживаю.
