### ISSUE TITLE
Ошибки в шаблоне default

### ISSUE THREAD

**Issue by Tirixk** [maxsite/cms#444]
1. Не отображается текст в ссылке подробнее. Публикация.
2.  Некорректное отображение публикаций.
3. Когда в настройках шаблона задаешь основной цвет шрифта и  цвет фона, не ко всем элементам сайта применяется:[ustianski.site](https://www.ustianski.site) .
Ссылка с примером

**Comment by maxsite** [comment]
Так это вопрос дизайна. Как указали стили, так и будет показывать.

**Comment by Tirixk** [comment]
Я только указал цвет фона и цвет шрифта, всё остальное баги шаблоныа

**Comment by KsenZ** [comment]
Это не баги шаблона.

Например вы не включили FontAwesome, это то, что бросается в глаза.
Так и с остальными опциями.

**Comment by maxsite** [comment]
Шаблон нужно настроить под себя. Начните с основ https://max-3000.com/book

**Comment by Tirixk** [comment]
Активировал эти шрифты,

**Comment by Tirixk** [comment]
> Это не баги шаблона.
> 
> Например вы не включили FontAwesome, это то, что бросается в глаза.
> Так и с остальными опциями.
Активировал все шрифты, что-нибудь поменялось?
Сам имею только света ощущениях, могу отличить светлый от темного цвета, всё остальное помогает озвучка
