### ISSUE TITLE
wrong image type for favicon

### ISSUE THREAD

**Issue by mbonga** [maxsite/cms#449]
Привет, в шаблоне используется image/x-icon вне зависимости от типа изображения, это неправильно. 

~/application/maxsite/templates/default/custom/template.php

То же самое верно для всех шаблонов включая MF.

**Comment by maxsite** [comment]
Почему неправильно?

**Comment by mbonga** [comment]
Так не правильней? Современные браузеры отображают, но Яндекс не смог раздуплить что с типом image/x-icon на самом деле приезжает PNG, и бог знает где ещё это стреляет. 

image/svg+xml — для формата SVG;
image/x-icon или image/vnd.microsoft.icon — для формата ICO;
image/gif — для формата GIF;
image/jpeg — для формата JPEG;
image/png — для формата PNG;
image/bmp — для формата BMP.

**Comment by maxsite** [comment]
Ну на стринги мы ориентироваться точно не будем. :-) Киньте ссылку на документацию гугла по этому вопросу. Там и посмотрим.

**Comment by mbonga** [comment]
https://www.w3.org/2005/10/howto-favicon
http://www.iana.org/assignments/media-types/image/vnd.microsoft.icon

Сойдёт вместо Гугла? :)

**Comment by maxsite** [comment]
2005 год, серьёзно?

**Comment by mbonga** [comment]
Серьёзно. Это стандарт. Если есть такой стандарт, пихать PNG и объявлять его image/x-icon, покажите. 

Макс, я понимаю что на каждый чих не наздравствуешься, и у себя лично я эту проблему разумеется закрою. 
Хотел сделать продукт лучше.

**Comment by maxsite** [comment]
Я не вижу проблемы и не буду ничего делать, пока не будет её корректного описания.

**Comment by maxsite** [comment]
В общем решил просто добавить type_foreach-файл favicon для случаев, если нужно сделать сложную фавиконку, вроде сервиса https://realfavicongenerator.net/ Там много html-кода, одной строчкой не обойтись. Что касается документации, то она здесь: https://en.wikipedia.org/wiki/Favicon

**Comment by mbonga** [comment]
Спасибо. Я не стал уж давать ссылку на Википедию вчера, хотя на эту страницу есть ссылка с W3C страницы выше. 
Да, там малой кровью не обойтись к сожалению. И импакт непонятен, вроде в браузерах показывает и так.
