### ISSUE TITLE
mysql_escape_string() is deprecated в php 5.5

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#45]
При установке движка на OpenServer с php 5.5 на борту получил такие сообщения после авторизации (инасталляция прошла успешно):

> A PHP Error was encountered
> Severity: 8192
> Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() > instead.
> Filename: mysql/mysql_driver.php
> Line Number: 320
 
> A PHP Error was encountered
> Severity: 8192
> Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.
> Filename: mysql/mysql_driver.php
> Line Number: 320

При попытке использовать драйвер **mysqli** вместо **mysql** с помощью опции в **database.php** (`$db['default']['dbdriver'] = 'mysqli'`) получил другие сообщения:

> A PHP Error was encountered
> Severity: Warning
> Message: mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
> Filename: mysqli/mysqli_driver.php
> Line Number: 316

> A PHP Error was encountered
> Severity: Warning
> Message: mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
> Filename: mysqli/mysqli_driver.php
> Line Number: 316

Эту ошибку смог побороть только вот такой правкой файла **\system\database\drivers\mysqli\mysqli_driver.php** (в строке 315):

```php
if( !$this->conn_id)
{
	$this->initialize();
}
		
$str = mysqli_real_escape_string($this->conn_id, $str);
```

Может есть какие-то варианты, чтобы инсталляция движка не тербовала правки файлов CodeIgniter?

**Comment by dignityinside** [comment]
Это не ошибка даже, а просто уведомление о том, что в новой версии PHP данная функция скорее всего будет убрана.

**Comment by maxsite** [comment]
В варианте с драйвером mysql для mysql_escape_string нужно подавить предупреждение через @.

**Comment by vimruler** [comment]
В новой dev-версии проблема осталась. Сейчас в движке по умолчанию используется mysqli и поэтому проблема переместилась в файл **\system\database\drivers\mysqli\mysqli_driver.php** в строку 316. Столкнулся с этим при установке «с нуля» (т.е. скачал последнюю версию с гитхаба, настроил по инструкции на OpenServer с php 5.5) - при авторизации админом сайт выдавал «Неверный логин/пароль» (чтобы увидеть место ошибки пришлось стопорить код функции _mso_login() для выявляения проблемного места иначе происходит редирект и ошибку не видно). Применил указанный выше патч и получилось нормально войти.

Может кто-нибудь подтвердить или опроврегнуть появление этой проблемы именно на php старше версии 5.4?

**Comment by leonovmax** [comment]
Аналогичная ситуация. и на 5.4 и на 5.5, 5.6
И плюс на странице "контакты" -

A PHP Error was encountered
Severity: Notice
Message: Undefined index: file_count
Filename: forms/index.php
Line Number: 80

**Comment by Tiahin** [comment]
> В варианте с драйвером mysql для mysql_escape_string нужно подавить предупреждение через @.

Имхо, это решение лучше:
[mysql-escape-string-function-is-deprecated-use-mysql-real-escape-string-code](http://stackoverflow.com/questions/27873251/mysql-escape-string-function-is-deprecated-use-mysql-real-escape-string-code)

**Comment by maxsite** [comment]
Если не сложно, давайте попробуем найти такое решение, которое работает на 5.3-5.6. Внесем необходимые правки в файл CodeIgniter. Только делаем для драйвера mysqli — полностью переходим на него.

**Comment by Tiahin** [comment]
> Если не сложно, давайте попробуем найти такое решение, которое работает на 5.3-5.6.

Это решение не зависит от версии PHP.
Но я проверил у себя на 5.3 и 5.6 (других версий не имею) - вариант по ссылке выше работает отлично.

**Comment by maxsite** [comment]
Мы говорим об этом коде?

```php
if( !$this->conn_id)
{
    $this->initialize();
}

$str = mysqli_real_escape_string($this->conn_id, $str);
```

???

На 5.4 и 5.5. может кто-нибудь проверить?

**Comment by maxsite** [comment]
Я правильно понимаю, что больше нет проблем в любой версии php? Закрывать тикет?

**Comment by vimruler** [comment]
Я с ними пока не сталкивался. Думаю, что можно закрыть тикет.

**Comment by maxsite** [comment]
Ок.
