### ISSUE TITLE
Пустой экран после установки автоустановщиком

### ISSUE THREAD

**Issue by trommo** [maxsite/cms#455]
Переехал на шаредный хостинг с ВПС, заодно решил полностью переделать сайт на MaxSite CMS, поскольку он пропустил несколько обновлений. Использовал аутоустановщик, который после установки сообщил, что всё ОК, однако при переходе к сайту ничего не выводится: evrika.net.ua.

Конфигурацию сервера на хостинге можно посмотреть здесь: evrika.net.ua/1.php, версия PHP подходит под требуемую.

В чём может быть проблема? В настройках сервера или разрешениях для файлов и папок, например?

**Comment by maxsite** [comment]
Что в логах ошибок?

**Comment by trommo** [comment]
Stack trace:
#0 /home/u319**/evrika.net.ua/application/maxsite/common/core/block-pages.php(231): mso_holder('800', '600', false, '#EEEEEE')
#1 /home/u319**/evrika.net.ua/application/maxsite/templates/default/type/home/units/last-pages.php(233): Block_pages->output(Array)
#2 /home/u319**/evrika.net.ua/application/maxsite/common/core/units.php(135): require('/home/u319**/ev...')
#3 /home/u319**/evrika.net.ua/application/maxsite/shared/type/home/home.php(46): mso_units_out('<?php if (!defi...')
#4 /home/u319**/evrika.net.ua/application/maxsite/templates/default/index.php(15): require('/home/u319**/ev...')
#5 /home/u319**/evrika.net.ua/application/views/index.php(12): require('/home/u319**/ev...')
#6 /home/u319**/evrika.net.ua/system/core/Loader.php(834): include('/home/u319**/ev...')
#7 /home/u319**/evrika.net.ua/system/core/Loader.php(420): CI_Loader->_ci_load(Array)
#8 /home/u31 in /home/u319**/evrika.net.ua/application/maxsite/common/core/images.php on line 210

**Comment by maxsite** [comment]
Смотрите лог ошибок.

**Comment by trommo** [comment]
Я привёл не тот лог, что нужно?

**Comment by maxsite** [comment]
Что-то вроде error.log Там php-ошибки.

**Comment by trommo** [comment]
Хостинг-провайдер мне так и не ответил за всё это время после нескольких тикетов.... 

Путём проб и ошибок выяснил, что проблема в дефолтном шаблоне - его главную страницу не отображает, в то время как остальные работают нормально. Пришлось взять один из старых шаблонов - с ним всё ОК,
