### ISSUE TITLE
Как правильно подключить ушку или опцию в Units на главной для trigger?

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#469]
Здравствуйте.
Подскажите пожалуйста как это реализовать, спасибо!

Я прошлые разы реализовывал топорно, без ушек или опций. Всё очень не удобно, хочу нормально реализовать, чтобы с легкостью можно было инфу триггера менять через админку.

**Comment by maxsite** [comment]
Используйте php-код или даже лучше php-шаблонизатор. Там любые функции.

**Comment by W1SE95** [comment]
Попробовал реализовать через функцию - не получается. Более развернуто можете ответить? Просто далеко не все обладают теми знаниями что и вы.
![image](https://user-images.githubusercontent.com/60783381/141806531-ee368b36-a21e-42f9-a943-0f781c30487d.png)

**Comment by W1SE95** [comment]
Таким образом если реализовать - это правильно?
![image](https://user-images.githubusercontent.com/60783381/141808650-4a1d54a5-fc66-4045-8b98-ff831ce78697.png)

**Comment by maxsite** [comment]
Работает?

**Comment by W1SE95** [comment]
Да, работает. Ошибок нет никаких. Просто очень мало информации к сожалению по многим вещам, приходится все самому пробовать реализовывать, были б готовые примеры реализации.

**Comment by maxsite** [comment]
Ну что есть, то есть...
