### ISSUE TITLE
Выкатил обновление

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#47]
Очень много правок: https://github.com/maxsite/cms/commit/25eb82b7ca1965f161da1bd8435361c8d7ecb41c?diff=split

Тестировать нужно всё.

**Comment by cuprum** [comment]
Максим, я заметил, у тебя первоначальный вариант в компоненте top1.php. Это временно? Я там его [чуть корректировал](https://github.com/maxsite/cms/pull/42/files), лучше его.

**Comment by maxsite** [comment]
top1.php — это твой вариант. Я его чуть поправил. А top1-1.php это первоначальный старый вариант.

**Comment by cuprum** [comment]
@maxsite top1.php это мой первоначальный вариант. Я его потом обновил.

**Comment by maxsite** [comment]
Я запутался. Мне твой новый вариант взять?

**Comment by cuprum** [comment]
Ага, [вот](https://github.com/maxsite/cms/pull/42/files).

**Comment by maxsite** [comment]
Как-то не очень получилось... Куда-то плавность появления исчезла.

**Comment by cuprum** [comment]
@maxsite  Забыл совсем. Попробуй указать для поля ширину:
```css
.my-search {
  width: 180px;
}
```

**Comment by maxsite** [comment]
Так лучше. :)

Еще такой момент. Можно ли предусмотреть вариант, если input виден, то кнопка-иконка автоматом срабатывает как кнопка submit? То есть не только по enter, но и по клику на кнопку.

**Comment by cuprum** [comment]
А может не надо? Мне кажется это будет запутывать - два действия на одну кнопку.

**Comment by maxsite** [comment]
Так там же умные действия. :) Просто когда ввел поисковую фразу так и тянет нажать иконку.

**Comment by cuprum** [comment]
Гляну, напишу на почту.
