### ISSUE TITLE
Предложение о создании плагина импорта/экспорта БД для maxsite

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#471]
Здравствуйте.

Очень не удобно, что отсутствует возможность импорта/экспорта всей бд или нужных таблиц (например только записей) прямо из коробки.
Приходится каждый раз это делать через phpMyAdmin.

Это решение очень сильно поможет и существенно сэкономит время при долгосрочном использовании (создание дубликата или же перенос на новый домен) сайта на вашей CMS и так же при разработке.

Думаю данная тема заслуживает рассмотрения для внесения в ветку "Организация работ и обсуждений ".

**Comment by vimruler** [comment]
А чем sypex dumper не подходит? Если нет денег купить лицензию, то можно поискать в сети - когда-то попадалась есть доработанная (форк) бесплатная версия для работы на последних версиях php.

**Comment by KsenZ** [comment]
[Adminer](https://www.adminer.org/)
Всего 1 файл. Функционал, почти сопоставим с phpMyAdmin.

**Comment by maxsite** [comment]
Был уже такой, оказался дырявый. Проще использовать Adminer. :-)
