### ISSUE TITLE
Изменить порядок сортировки комментариев к записи

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#473]
Здравствуйте.
Подскажите пожалуйста как можно изменить это, или хотя бы напишите в каком файле и в каком месте применять все нужные изменения, спасибо!
![Screenshot_10](https://user-images.githubusercontent.com/60783381/147738449-f7fb40e1-f291-461c-901e-5844ffc11259.jpg)

**Comment by maxsite** [comment]
Смотрите функцию `mso_get_comments()`. Там в параметрах можно передать порядок сортировки. Переопределяется через `type\page\units\page-comments.php`
