### ISSUE TITLE
С 1 января сайт перестал работать

### ISSUE THREAD

**Issue by kelemator** [maxsite/cms#474]
Ребята, пожалуйста, помогите разобраться! 
На сайте неожиданно вылезла новодняя проблема. Ровно с 1 января упал сайт. "Морда сайта пустая", если зайти в какую-нибудь запись - запись показыватся, но только текст без шаблона. Админка работает, кэш сбрасывал - не помогает. 
Хотел автообновление по ссылке сделать - выдает "Curl library not found".
В логах на хостинге ровно с 1 января идут вот такие строчки (имя сайта и аккаунта хостинга изменены на XXX):

[Sat Jan 01 09:49:17.857854 2022] [php:error] [pid 4197] [client 95.108.213.54:10280] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /home/XXX/XXX.ru/www/application/maxsite/common/core/images.php:210\nStack trace:\n#0 /home/XXX/XXX.ru/www/application/maxsite/common/core/block-pages.php(231): mso_holder('100', '100', false, '#EEEEEE')\n#1 /home/XXX/XXX.ru/www/application/maxsite/templates/default/type/home/units/last-pages.php(233): Block_pages->output(Array)\n#2 /home/XXX/XXX.ru/www/application/maxsite/common/core/units.php(135): require('/home/XXX/go...')\n#3 /home/XXX/XXX.ru/www/application/maxsite/shared/type/home/home.php(46): mso_units_out('[unit]\\nfile = l...')\n#4 /home/XXX/XXX.ru/www/application/maxsite/templates/default/index.php(15): require('/home/XXX/go...')\n#5 /home/XXX/XXX.ru/www/application/views/index.php(12): require('/home/XXX/go...')\n#6 /home/XXX/XXX.ru/www/system/core/Loader.php(834): include('/home/XXX/go...')\n#7 /home/XXX/XXX.ru/www/system/core/Loader.php(420): CI_Loader->_ci_load(Array)\n#8 /home/XXX/XXX.ru/www/application/controllers/maxsite.php(116): CI_Loader->view('index', Array)\n#9 /home/XXX/XXX.ru/www/application/controllers/maxsite.php(53): Maxsite->_view_i('home')\n#10 /home/XXX/XXX.ru/www/system/core/CodeIgniter.php(326): Maxsite->_remap('home', Array)\n#11 /home/XXX/XXX.ru/www/index.php(202): require_once('/home/XXX/go...')\n#12 {main}\n  thrown in /home/XXX/XXX.ru/www/application/maxsite/common/core/images.php on line 210

Это хотинг (Мастерхост) с 1 января че-то сделал? Или код сайта как-то в 2022-м не хочет работать? Блин, я прям реально не знаю, в какую сторону копать. Выручайте, братцы!

**Comment by maxsite** [comment]
Такие вопрос задавайте здесь: https://github.com/maxsite/cms/discussions

Проверяйте библиотеку gd2 в  phph на сервере.
