### ISSUE TITLE
Вывод записей по тегу в конце контента PAGE

### ISSUE THREAD

**Issue by W1SE95** [maxsite/cms#475]
Здравствуйте. С Наступившим!

Подскажите пожалуйста, каким образом можно отфильтровать и показать на странице записи другие записи по тегу?

Попробовал реализовать так, но не пойму как фильтровать именно по нужному тегу:
`$pages2 = mso_get_pages([
    'custom_type' => 'home',	
	'meta_key' => $this_page_tag,
	'exclude_page_id' => $this_page_id,
	'type' => 'blog',
	'content' => false,
	'limit' => 3
    ], $pagination2);`

P.S.
$this_page_tag - это тег, родительской записи - $this_page_tag = implode(",", $p->val('page_tags'));
$this_page_id - $p->val('page_id');
'meta_key'  - может использоваться только на странице тега (_mso_sql_build_tag), это я прочел в файле get-pages (то есть уже неправильно я сделал)

Какая задача:
Показывать похожие записи по ТЕГУ внутри контента родительской страницы. (Оставляя при этом стандартные похожие записи по дефолту)

![Screenshot_11](https://user-images.githubusercontent.com/60783381/148238708-3a36a3f7-130b-4986-8d85-17a0fd8bb583.jpg)

**Comment by maxsite** [comment]
Чтобы использовать _mso_sql_build_tag() нужно указать custom_type = tag.

ps Такие вопросы нужно задавать на форуме https://github.com/maxsite/cms/discussions
