### ISSUE TITLE
Roadmap MaxSite CMS .87 .88 .89 .90

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#48]
Небольшой анонс по плану выпуска версий MaxSite CMS. Поскольку мы не можем полноценно выполнить тестирование всех нововведений, то сделаем проще. Ещё недельку сами погоняем, поправим хвосты dev и это будет релиз версии .87 (с анонсом, чтобы привлечь народ). Она будет как ветка dev (как сейчас). Дальше с интервалом в 1 неделю делаем версии .88 и .89. Они также будут как dev. Версия .90 будет уже как master. 

Текущая, которая .87 ещё нужно доделать дизайн default-шаблона. Это все те части, которые не зависят от плагинов/виджетов, а только завязаны на type-файлы и прочие части системы. 

Версия .88 работа с плагинами (виджетами). Тут много переделок по верстке.

Версия .89 планирую переход на новую верстку админ-панели. Дизайн хочу изменить и главное сделать адаптивность. 

Версия .90 — полноценный релиз. Пусть народ ставит, находит глюки, ошибки. Исправлять будем по ходу и выкладывать в ветку master, увеличивая номер версии пока не исправим.

В общем переходим в режим — если нет замечаний, значит всё работает отлично.

**Comment by maxsite** [comment]
Да, отдельно отмечу, сейчас есть хвост по плагину form — от него зависит контактная форма сайта. Думаю, что переделаю плагин под tmpl-файл (с html-шаблонизатором), чтобы его можно было кастомизировать на уровне шаблона.

**Comment by vimruler** [comment]
В целом всё понятно.

**Comment by cuprum** [comment]
@maxsite попробуй использовать теги при анонсах версий. Чтобы можно было видеть все версии на вкладке [релизов](https://github.com/maxsite/cms/releases). Например, как [тут](https://github.com/h5bp/html5-boilerplate/releases).

Как делать релизы описано в [справке](https://help.github.com/articles/creating-releases/).

Чтобы не путаться, предлагаю такой алгоритм - предварительные версии маркировать тремя цифрами после точки (0.873). Они будут основаны на ветке dev. При создании релиза указывать птичку "Пре-релиз" в настройках.

Обычные релизы, как обычно, две цифры после точки, основаны на ветке master.

**Comment by maxsite** [comment]
Если у нас ветка dev, то метку я могу поставить, но это не будет релизом?

**Comment by cuprum** [comment]
@maxsite Наверное ;). Я в живую пока не применял, сужу по описанию в справке. Видимо так: вводим номер версии (0.873) и выбираем из списка ветку dev. Еще надо выбрать птичку "пре-релиз". Релизы можно [редактировать и удалять](https://help.github.com/articles/editing-and-deleting-releases/). Поиграйся.

**Comment by maxsite** [comment]
У меня на LPF так и сделано: https://github.com/maxsite/landing/releases

Мне кажется, что для dev номер версии особой роли не играет. Изменения по коммитам и так видны.

**Comment by cuprum** [comment]
>Мне кажется, что для dev номер версии особой роли не играет. Изменения по коммитам и так видны.

Хм, но ты же написал:
>Ещё недельку сами погоняем, поправим хвосты dev и это будет релиз версии .87 (с анонсом, чтобы привлечь народ). Она будет как ветка dev (как сейчас). Дальше с интервалом в 1 неделю делаем версии .88 и .89. Они также будут как dev. Версия .90 будет уже как master. 

Получается, ты все-таки собираешься ставить версии на dev? Или я чего-то не понял...

**Comment by maxsite** [comment]
Ну поменяю в maxsite_lib.php и сделаю анонс на сайте. Вот и всё. :)

**Comment by maxsite** [comment]
Выкатил 0.87. Даже метку сделал. :)

**Comment by multVVM** [comment]
доброе, скачал версию cms-dev (0.90), пытаюсь установить с нуля, не устанавливается...
указал БД(database.php)
указал секретное слово(mso_config.php)
при нажатии на "Перейти к установке" переходит на несуществующую станицу ".../install/2"

до этого версия 0.87 установилась, правда были ошибки
Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() > instead.

**Comment by maxsite** [comment]
Каталог install удалили?

**Comment by multVVM** [comment]
удалил, все установилось, спс

**Comment by multVVM** [comment]
изменил файл mysqli_driver.php, как было предложено в одном из обсуждений

if( !$this->conn_id)
{
    $this->initialize();
}

$str = mysqli_real_escape_string($this->conn_id, $str);
смог зайти в админку

**Comment by maxsite** [comment]
версия php?

**Comment by multVVM** [comment]
denwer, PHP Version 5.3.13

**Comment by HaipaiUser** [comment]
Версия 0.87.1
Нет кнопок редактирования статей на главной и на самих страничках статей.

**Comment by vimruler** [comment]
Странно. Сделал чистую установку 0.87 на OpenServer с php 5.5 (скачал архив с ГитХаба, install, install не удалил пока) и ошибки mysql_escape_string не поймал хотя правок в CI-драйвере db обсуждаемых правок нет.

**Comment by multVVM** [comment]
обновил denwer до PHP Version 5.5.24, ошибки нет

**Comment by vimruler** [comment]
Научился воспроизведить и "скрывать" ошибку
> mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

Когда движок устанавливается в автоматическом режиме, то параметр $mso_install в maxsite/mso_config.php остаётся false. Ошибка не появляется и сайт нормально работает.

А вот если вручную исправить $mso_install на true (как раньше надо было делать по инструкции), то ошибка появляется «во весь рост».

**Comment by maxsite** [comment]
Странная зависимость... $mso_install «запускает» лишь проверку наличия таблицы mso_options. Илья, попробуй отловить в каком именно куске кода можно отсечь эту ошибку при $mso_install=true . В первую очередь смотри на контролер maxsite.php. Там в общем-то только один кусок кода:

```php
$CI = & get_instance();	
if ( !$CI->db->table_exists('options')) return $this->install();
```
Кроме того, в конструкторе срабатывает функция mso_initalizing(), где осуществляется такая же проверка. Если есть какая-то связь с $mso_install, то возможно, что CodeIgniter не может выполнить инициализацию БД на каких-то версиях PHP (хотя там autoload стоит). Если это так, то в общем-то мы можем попробовать добавить в той же mso_initalizing() или конструкторе контролера принудительную инициализацию базы.
```php
$this->load->database();
```

**Comment by cuprum** [comment]
Меня смущает пункт из install-ru "После установки, каталог «install» можно удалить". Можно - значит можно и оставить. В таком случае надо вносить Disallow: /install в robots. Неоднозначно как-то. А если такой вариант -  после автоустановки автоматически удалять папку install?

И еще - может вынести install-ru.txt в корень сайта?

**Comment by maxsite** [comment]
Каталог install не влияет на работоспособность системы. Даже если его 100 раз запускать, там умный алгоритм, ничего не сломается. А удалять для того, чтобы не плодить лишние сущности.

В robots можно и добавить. Это нормальное решение.

> может вынести install-ru.txt в корень сайта?
Уже такое было. Такие файлы лучше убрать с глаз.

**Comment by vimruler** [comment]
> Илья, попробуй отловить в каком именно куске кода можно отсечь эту ошибку при $mso_install=true 

Хорошо, буду смотреть.

> Кроме того, в конструкторе срабатывает функция mso_initalizing()

Пока что меня смущает только вот такая конструкция из функции mso_initalizing():

```php
# стоит ли флаг, что уже произведена инсталяция?
if (!isset($mso_install) or $mso_install == false)
{
	if ( !$CI->db->table_exists('options')) return false; # еще не установлен сайт
}
```

Дело в том, что при автоматической инсталляции движка переменная $mso_install устанавливается в false и значит проверка **!isset($mso_install)** просто не имеет смысла.

**Comment by maxsite** [comment]
Тут условие OR, поэтому при $mso_install == false как раз условие и срабатывает.

**Comment by vimruler** [comment]
Посмотрел. Обозначенная проблема именно в приведённом куске кода. Т.е.
```php
# стоит ли флаг, что уже произведена инсталяция?
if (!isset($mso_install) or $mso_install == false)
{
    if ( !$CI->db->table_exists('options')) return false; # еще не установлен сайт
}
```
Получается примерно такая ситуация. В текущей dev-версии движка после проведения установки условие **!isset($mso_install)** всегда будет равно **false**, т.к. при автоматической инсталляции создаётся файл **maxsite/mso_config.php** и там **$mso_install = false;** (т.е. переменная установлена), а при ручной установке файл **maxsite/mso_config.php** создаётся в ручную и переменная **$mso_install = true;** (т.е. переменная тоже установлена).

Раз **!isset($mso_install)** всегда **false**, то действительно работает OR и фактически всегда происходит проверка только одного условия - **$mso_install == false**. Вот здесь и кроется разница, которую я отмечал и которая влияет на проявление ошибки.

Если **$mso_install == false** даёт истину, то срабатывает проверка, в которой участвует **$CI->db->table_exists('options')**. Вызов функции проверки существования таблицы каким-то образом иницирует коннект с базой и дальше этот коннект нормально используется и ошибка с **mysqli_real_escape_string()** не возникает.

Если же **$mso_install == false** даёт ложь, то проверки нет, инициализация коннекта с базой не происходит и фреймворк формирует запросы к базе,и в результате чего доходит до вызова функции **mysqli_real_escape_string()**, где происходит ошибка.

Как происходит инициализация коннекта в **table_exists** ещё не смотрел, но думаю, что это уже и не важно.

Проверить мои выкладки можно простым **pr($CI->db);** при разных значениях $mso_install:
```php
pr($CI->db);
# стоит ли флаг, что уже произведена инсталяция?
if (!isset($mso_install) or $mso_install == false)
{
    if ( !$CI->db->table_exists('options')) return false; # еще не установлен сайт
}
pr($CI->db);
```
Тестировал на странице **/about**.

**Comment by maxsite** [comment]
Значит проблема в инициализации базы на стороне CodeIgniter. Сделай так. В файле контролёра перед ```mso_initalizing();``` добавить инициализацию базы.

```php
$this->db->initialize();
```
Думаю, этого будет достаточно.

**Comment by maxsite** [comment]
Да, сейчас в автоустановке остается $mso_install = false, но нужно будет переделать на $mso_install = true. Это просто недоработка.

**Comment by vimruler** [comment]
> Значит проблема в инициализации базы на стороне CodeIgniter.

Именно. Я ради эксперимента выставлял в настройках **database.php** параметр 
```php
$db['default']['autoinit'] = TRUE;
```
Ошибка пропадала.

> Сделай так. В файле контролёра перед mso_initalizing(); добавить инициализацию базы

Сделал. Действительно, ошибка пропала, т.е. этого достаточно.

**Comment by maxsite** [comment]
С autoinit может быть проблема при старой (полуавтоматической) установке. Я тогда провею еще этот вариант. Если откажемся от старогог варианта, то autoinit будет достаточно.

**Comment by maxsite** [comment]
В общем внес все необходимые правки. Install теперь только новый и $mso_install удалил за ненадобностью.

**Comment by HaipaiUser** [comment]
В инсталляторе лучше бы убрать обязательный ввод пароля для доступа к базе данных, и уменьшить количество символов для пароля админа с 8 до скажем 4. А то это сильно напрягает, когда пытаешься поставить на локальном сервере.

**Comment by HaipaiUser** [comment]
Также в новой админке, страничка /admin/files выглядит кривовато.
Вернее криво выглядят три поля ввода под файлы.

**Comment by maxsite** [comment]
Пароль db-пользователя, действительно может и не быть. Уберу required. Основной пароль меньше 8 символов — это плохо. Тем более, что он запоминается в полях формы браузера.

**Comment by maxsite** [comment]
Новая админка ещё требует очень большой работы. Я успел только основной каркас сделать. Остальное уже по ходу, после релиза 0.90

**Comment by maxsite** [comment]
Кстати, возник вопрос: как лучше сделать на гитхабе релиз 0.90? Сейчас есть ветка master, где старая версия 0.86 и dev (условно 0.90). Я думаю, что старую можно сохранить в виде отдельной ветки, а dev слить с master, чтобы какое-то время они были одинаковыми. Какие мысли?

**Comment by HaipaiUser** [comment]
Понятно что на рабочем сайте маленький основной пароль плохо.
Может сделать как в некоторых cms при вводе пароля если ввели меньше 8 символов просто писать - очень слабый пароль. А там пользователь пусть сам решает.

**Comment by vovansrnd** [comment]
да что вы с этим паролем, в самом-то деле. Какая разница, 8 единик .например, вверсти или 4?

Что до слияния с сновной веткой - по большому счёту, существенно значения это не имеет. Хотя я бы 0.90 пока оставил бы в dev. Хотя бы до первого следующего релиза.

**Comment by vimruler** [comment]
> Новая админка ещё требует очень большой работы. Я успел только основной каркас сделать. Остальное уже по ходу, после релиза 0.90

Понятно. А то к цветами некоторых элементов есть вопросы. Например, табы сейчас стали серыми и практически не различимы. Также кое-где поля ввода и чередование цветов сделано в серых цветах - имхо, выглядит "вырвиглазно". 

Кстати, то, что сайдбар в даминке не протягивается до нижней границы экрана на страницах с малым количеством контента - так и должно быть? 

> как лучше сделать на гитхабе релиз 0.90? Сейчас есть ветка master, где старая версия 0.86 и dev (условно 0.90). Я думаю, что старую можно сохранить в виде отдельной ветки, а dev слить с master, чтобы какое-то время они были одинаковыми.

До последних правок в админке мне нравилась версия 0.90 и я не планирую использовать  0.86 в чистом виде (ну разве что только компоненты и юниты на запчасти). Поэтому если она будет в виде отдельной ветки, а текущая dev станет master - то я поддержу. Единственное, что смущает, что по-моему сейчас админка всё таки сыровата по цветам (написал выше) чтобы её выкатывать в виде основной версии. Коллеги могут просто не понять и счесть за деградацию.

> да что вы с этим паролем, в самом-то деле. Какая разница, 8 единик .например, вверсти или 4?

Есть разница. Потом возможна ситуация, когда у вебмастера брутфорсят короткий пароль, а он обвиняет движок, что тот дырявый. Так что лучше пусть будет 8. Не так уж сложно придумать пароль на такую длину символов.

**Comment by vovansrnd** [comment]
я имел ввиду, какая разница тому, кто жалуется. А решение Макса на счёт пароля я поддерживаю.

**Comment by maxsite** [comment]
Админка не просто сыровата, она вообще только в начале переделок.В первую очередь я хотел сделать адаптивность и даже текущая версия в этом плане большой прорыв вперед. Но осилить весь объем работ по админке я сразу не смогу. Если ждать готовую админку, то на это потребуется еще несколько месяцев. Поэтому я не хочу зацикливаться на этом вопросе — будем править и дорабатывать уже по ходу. Тем более, что основное ядро и дефолтный шаблон уже отлажены и вопросов по ним нет, а это значит, что её можно пускать в свободное «плавание».

**Comment by vimruler** [comment]
Понятно. Тогда вопросов больше нет и согласен, что можно выводить в паблик.

**Comment by maxsite** [comment]
Кто у нас в гите разбирается? Не пойму в чём подвох. Делаю на своем локальном репозитории ветку v086, которая от master. Всё нормально, ветка есть. Теперь отправляю на гитхаб через push (как обычно). На гитхабе ветка не появляется. Что нужно сделать, чтобы она появилась?

**Comment by Tiahin** [comment]
Может быть эту ветку теперь надо поставить мастером - перенести на нее HEAD ?

**Comment by maxsite** [comment]
Выкатил 0.90. Это обсуждение закрываю.
