### ISSUE TITLE
Stored-Cross-Site-Scripting (XSS)(authenticated) --2

### ISSUE THREAD

**Issue by fuzzyap1** [maxsite/cms#485]
###  Stored-Cross-Site-Scripting (XSS) -2
a stored cross-site scripting (XSS) in maxsite cms targeted towards web admin through ~/admin/files  at via the parameter f_file_description .  
1. Navigate to admin page, go to http://localhost/admin/files,then update a xss.gif file 
![image](https://user-images.githubusercontent.com/95869214/154520039-1b30f25c-ab55-4b38-8631-830893cf5d5e.png)

3. insert xss payload  ` "><svg onload=alert(222)>` in the parameter f_file_description
![image](https://user-images.githubusercontent.com/95869214/154520277-d4bf0717-be5d-4212-bfb5-bca6da98b292.png)

4. click save 
You will observe that the payload successfully got stored into the database and when you are triggering the same functionality at that time JavaScript payload gets executed successfully and we'll get a pop-up.
![image](https://user-images.githubusercontent.com/95869214/154520359-cca32818-ca09-4745-8a4d-39b27d8dd654.png)

**Comment by maxsite** [comment]
Thank you for your work!
