### ISSUE TITLE
Правила именования css-классов MaxSite CMS

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#49]
Давайте определимся раз и навсегда с правилами именования css-классов в MaxSite CMS. У нас есть html, который формируется на уровне type-файлов, плагинов и шаблонов. 

Для шаблонов я предлагаю никаких правил не вводить вообще. То есть произвольное именование.

В type-файлах использовать приставку ```mso-``` Наример было ```<div class="type type_page">``` станет ```<div class="mso-type-page">```.  То есть во всех классах, которые формирует система использовать эту приставку.

В плагинах для главного блока задавать ```div.mso-plugin-ПЛАГИН``` А остальные классы вложенных блоков уже задаются уже призвольно.

При такой схеме мы полностью разделяем классы системы от любого другого css-фреймворка.

**Comment by vimruler** [comment]
Звучит логично и приемлемо. Для себя отмечаю, что нужно будет все свои плагины переделать соответствено.

**Comment by cuprum** [comment]
> Для шаблонов я предлагаю никаких правил не вводить вообще. То есть произвольное именование.

Тут не очень понял, поскольку

>В type-файлах использовать приставку mso- Наример было `<div class="type type_page">` станет `<div class="mso-type-page">`. То есть во всех классах, которые формирует система использовать эту приставку.

А разве type_page и прочие type не относятся к шаблонам?

**Comment by maxsite** [comment]
Эти классы проставляются в type-файлах в shared. Поэтому им и нужно ставить mso-. Если же нужно использовать type-файлы в самом каталоге шаблона, то именование произвольно.

**Comment by cuprum** [comment]
@maxsite Я правильно понял, что в shared префикс mso- будет добавляться ко всем внутренним классам: page_only, info-top, page_content, type_home_content и т.д.?

**Comment by maxsite** [comment]
Ну да.
