### ISSUE TITLE
You don't have permission to access /admin/plugin_ushki on this server.

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#490]
Привет, Максим.

Странность наблюдаю и пока не могу понять как поправить. Суть в том, что решил поправить ушки, но при сохранении новых значений получают страницу 403 ошибки с сообщением «**You don't have permission to access /admin/plugin_ushki on this server.**»

Пытался разобраться сам, но такое ощущение, что до плагина POST запрос не доходит вообще. 

Никаких изменений в плагин не вносил. Версия движка 108.1. Грешу на переход на пхп 8. Но пока проверить не могу.

**Comment by maxsite** [comment]
Скорее всего что-то с настройкой сервера Apache. Нужно гугулить, там много директив для «Forbidden Error».

**Comment by vimruler** [comment]
Да, нашёл причину - ложное срабатывание apache-модуля ModSecurity на одну из ушек, в которой был php код.
