### ISSUE TITLE
Доработка плагина popup

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#50]
В плагине popup версии 4.0 нужно добавить возможность затенения всего сайта (серая полупрозрачность), когда показывается popup-блок.

**Comment by cuprum** [comment]
Возьмусь. Попозже гляну, что там еще можно доработать.

**Comment by maxsite** [comment]
Еще нужно добавить возможность появления popup не при скроллинге, а по времени. Посетитель заходит на страницу и через XX секунд (время в опцию) всплывает popup.

**Comment by cuprum** [comment]
Может быть разбить этот плагин на два?:
1. обычный Popup - в нем останется только возможность показа появляющегося/выезжающего блока при скроллинге. Такой блок не будет затеняет фон, его задача - просто акцентировать внимание на какой-то дополнительно информации.
2. Модальный Popup. Тут все серьезно - фон затеняется, блок появляется по центру сайта. События срабатывания - таймер, уход курсора мыши за пределы окна, еще что-то...

**Comment by maxsite** [comment]
Я бы всё-таки просто расширил текущий вариант.

**Comment by cuprum** [comment]
@maxsite а может все-таки на 2?
Я вот им давно не пользовался, зашел тут в настройки плагина, и не сразу понял как настроить :smile:
А если будет два варианта, маневра будет побольше - можно настроить 2 независимых варианта сразу: для модального и для выезжающего.

**Comment by maxsite** [comment]
Так они же фактически дублируют друг друга. Проще опцию добавить.

**Comment by cuprum** [comment]
Я просто думаю, что будет слишком много настроек, трудно будет разобраться, не считаешь?

**Comment by maxsite** [comment]
В смысле много? Там нужно добавить опцию затенять сайт и время задержки popup-окна.

**Comment by v0ff4k** [comment]
да, проще будет один, но с минимальным функционалом. Чтобы для увеличения функционала, желающие,  - оплачивали отдельно. и денежка производителю, и радость желающему наворотить свой сайт.
