### ISSUE TITLE
Админка грузится вечно + решение проблемы

### ISSUE THREAD

**Issue by niklyadov** [maxsite/cms#509]
Заметил, что админ-панель моего сайта грузится вечно и методом тыка выявил, что проблема при подтягивании RSS ленты с сайта max-3000.com. Вероятно, сайт лежит или не отвечает. Код админки делает запрос к сайту разработчика и не может этого сделать, поскольку сайт разработчика лежит.

**Решение проблемы:**

Перейти в файл по пути /application/maxsite/admin/plugins/admin_home/admin.php, обратить внимание на строки 299-319
```php
if (!function_exists('rss_get_go'))
	require_once(getinfo('plugins_dir') . 'rss_get/index.php');

$rss = rss_get_go(array(
	'url' => '/feed', 
	'format' => '<li><a target="_blank" href="[link]">[title] ([category])</a> &bull; <span class="t90">[pubDate]</span></li>', 
	'fields' => 'title link description pubDate category',
	'count' => 7, 
	'format_date' => 'Y-m-d',  // 'd.m.Y H:i', 
	'max_word_description' => 40, 
	'time_cache' => 720, // 720 минут = 12 часов
	'fields_items' => 'items',
	'charset' => 'UTF-8',
));

if ($rss)
{
	echo '<h4 class="mar50-t i-maxcdn">' . t('Новости MaxSite CMS') . '</h4>';
	echo '<ul>' . $rss . '</ul>';
	
}
```

Закомментируйте или удалите эти строки (299-319) и сохраните файл. Админка вашего сайта снова станет доступна, но RSS лента разработчика перестанет отображаться.

**Comment by maxsite** [comment]
Сайт норм работает. Скорее дело в вашей сети.
