### ISSUE TITLE
Поддержка php 8.4

### ISSUE THREAD

**Issue by v0vas** [maxsite/cms#510]
Доброго дня!
Планируется ли поддержка указанной версии? Если да, то когда ожидать?

**Comment by maxsite** [comment]
Разве эта версия уже вышла? Ждем официального релиза, тогда поправлю код, если нужно.

**Comment by v0vas** [comment]
21 ноября планируется релиз. Попробовал потестировать, пока обнаружил следующие ошибки логах nginx

`[error] 12894#100627: *1191 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Constant E_STRICT is deprecated in /srv/www/website/system/core/Common.php on line 474;` 

Ну и sape ругается:

`
A PHP Error was encountered
Severity: 8192
Message: Creation of dynamic property SAPE_client::$_page_obligatory_output is deprecated
Filename: 696f4e92bf/sape.php
Line Number: 1244
`

**Comment by maxsite** [comment]
Попробуйте заменить E_STRICT на число 2048.

Сапу удалю из комплекта — плагин уже не актуальный.

**Comment by v0vas** [comment]
Спасибо! Помогло.
