### ISSUE TITLE
Добавить в mso_get_pages хук на обработку page_title

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#54]
В функции mso_get_pages есть такой фрагмент:

```php
		foreach ($pages as $key=>$page)
		{
			$all_page_id[] = $page['page_id'];
			

			$content = $page['page_content'];
			
			$content = mso_hook('content_init', $content);

			$output = mso_hook('content_complete', $output);
			
			...

			$pages[$key]['page_content'] = $output;

			$pages[$key]['page_categories'] = array();
			$pages[$key]['page_categories_detail'] = array();
			$pages[$key]['page_tags'] = array();
			$pages[$key]['page_meta'] = array();
		}

```

В этом фрагменте важно то, что контент записи передаётся на обработку в хуки и тем самым появляется возможность производить дополнительную обработку (например, обрабатывать бб-коды) содержимого записи ещё до его вывода на странице.

Хочу предложить добавить такую возможность ещё и для заголовка записи page_title. Например, так:

```php
		foreach ($pages as $key=>$page)
		{
			...
			$page_title = $page['page_title'];
			$page_title = mso_hook('page_title_out', $page_title);
			...
			$pages[$key]['page_title'] = $page_title;
			...
		}
```

Такая возможно может пригодиться, например, при формирвании подстраивающихся лендингов или А/Б тестировании.

**Comment by maxsite** [comment]
Чего я с трудом представляю себе такую потребность... Илья, хоть один реальный пример меняющегося заголовка покажи. :)

**Comment by vimruler** [comment]
Я писал на заказ плагин **mutation**, который позволяет через вставку бб-кода выводить разные варианты текста в зависимости от переменной **?var=id**. Клиент использует этот плагин на лендингах затачивая рекламный трафик под разные ключевые запросы. Например, нужно выводить в одном месте один из двух ключей «психолог» или «психиатр». Понятно же, что посетитель лучше конвертируется, когда видит запрошенное им слово. А вебмастеру не нужно делать две практически одинаковые страницы.

Так вот, сейчас у клиента наконец-то руки дошли и до кастомизации заголовков в H1. Я для него реализовал вариант c type_foreach (вызываю функцию плагина). Но это в каком-то смысле костыльно и не гибко, т.к. пришлось создать мета-поле для хранения заголовка с кодом мутации (иначе пришлось бы type_foreach файлы делать для всех мест, где выводится заголовок).

Достаточно актуально?

**Comment by maxsite** [comment]
Ну собственно на ум как раз и выходит использование именно type_foreach-файла. Но точно не хука. «Мутация» заголовка описывается либо в метаполе записи или в опциях шаблона (если я правильно понял), а в type_foreach-файле размещается весь остальной функционал. Хук тут не при чем.

**Comment by vimruler** [comment]
> «Мутация» заголовка описывается либо в метаполе записи или в опциях шаблона (если я правильно понял), а в type_foreach-файле размещается весь остальной функционал. Хук тут не при чем.

Так то да. Оба варианта возможны. Думаю скорее речь о том, что оптимальнее и менее ресурсоёмко - пустые строки в базе данных (у всех записей, у которых нет мутации заголовка) у одного вебмастера или проверка наличия обработчика хука у множества вебмастеров. С этой точки зрения да, хук не нужен. Хотя давал бы хороший потенциал для красивого технического решения.

**Comment by maxsite** [comment]
Хук добавить не проблема, это очевидно. Но я правда, просто не вижу его применения. Это настолько специфичная задача... Если бы был какой-то плагин для решения какой-то задачи по изменению заголовка, то это ещё куда ни шло. А так даже твой пример — прямой путь к бану поисковиков. То есть, опять же, очень большая специфика. :) Тем более, которая решается через другие механизмы без особого труда.

**Comment by vimruler** [comment]
Хорошо. Тогда можем пока отложить добавление хука.
