### ISSUE TITLE
Вынос папки assets из шаблона

### ISSUE THREAD

**Issue by HaipaiUser** [maxsite/cms#55]
Хочу предложить вынести папку assets из шаблона.
Вернее не то чтобы вынести, а сделать возможность выноса этой папки.

Поясню:
В настройках сайта сделать глобальную переменную(не в настройках конкретного шаблона, а именно глобальную) указывающую где находится папка assets:
1. В папке шаблона
2. В корне сайта
3. Указать вручную

А то если я к примеру сделал на сайте 2-3 шаблона на Bootstrap 3 и jquery, то мне приходится либо иметь 2-3 копии этой папки, либо править в каждом шаблоне шапку, чтоб указать на общую папку assets.

А так указал где эта папка находится и ничего править не придется.

**Comment by maxsite** [comment]
Ну так а что мешает такую опцию сделать на уровне шаблона?

**Comment by HaipaiUser** [comment]
На дак тогда опять возвращаемся к началу - придется пилить каждый шаблон.

**Comment by maxsite** [comment]
Я ничего не понял...

**Comment by HaipaiUser** [comment]
Объясняю:
в папке assets на ходятся так сказать ресурсы(css, less, js и т.п.)
Я использую в своих скинах бутстрап 3 и jquery.
Все хорошо, если на сайте 1 скин и у тебя 1 сайт.
А если 2 и более скинов на сайте используется, то получается у меня во всех скинах эта папка фактически будет дублироваться.
А если у меня 10 сайтов?

Чтоб зря не плодить эту папку я и предложил сделать глобальную настройку где находиться эта папка.

**Comment by maxsite** [comment]
Что такое скин?

**Comment by HaipaiUser** [comment]
шаблон

**Comment by vimruler** [comment]
Я тоже слабо понял о чём речь.

**Comment by HaipaiUser** [comment]
Тогда спрошу по другому.
Для чего в админке Основные->Служебные
есть пункт Вариант загрузки jQuery ?

**Comment by skull3d** [comment]
Да, это тоже лишнее, как и предлогаемая опция. Это проблемы разработчика шаблона, как и откуда грузить стили и скрипты, и прописать это один раз в шаблоне не проблема.
Тем более, что в 95% случаев используется 1 сайт - 1 шаблон.

**Comment by HaipaiUser** [comment]
skull3d, дак я и предлагаю все сделать по уму.
Сейчас таже jQuery вообще болтается не пойми где, даже не в папке assets шаблона.
А так залить все ресурсы в папку assets и указать где она находится.
Ну либо вообще выкосить все это из шаблона.

**Comment by maxsite** [comment]
Вебмастер сам решает что и откуда загружается. Всё исключительно на уровне шаблона. Делайте опцию, как вам нужно. Ниаких «на уровне системы» не будет. Мы только что от этого ушли.

**Comment by HaipaiUser** [comment]
Если бы ушили, то не было бы мусора в виде jQuery расположенном не пойми где :)

**Comment by maxsite** [comment]
Не знаю что там у вас какой мусор болтается, но по существу я ответил. Все раположения только на уровне шаблона. Обсуждать нечего.
