### ISSUE TITLE
Доработка meta property="og:image"

### ISSUE THREAD

**Issue by HaipaiUser** [maxsite/cms#56]
Неплохо было бы сделать проверку протокола в пути к картинке.
Поясняю:
При создании странички, чтоб этот мета тэг генерировался мне нужно вставить картинку и указать к ней путь в поле Изображение записи.
Но есть одно но...
Если сайт работает просто по протоколу http, то проблем нет, просто указываешь путь с протоколом и все.
А если сайт работает и на http и https, вот тут возникают проблемы.
Чтоб проблем не возникло я в записях вставляю картинки вида:
/uploads/путь_к_картинке/картинка.jpg
и тогда по какому бы протоколу я не заходил на сайт, все нормально.

Если вставить такую ссылку в  поле Изображение записи, то получим:
mеtа prоperty="og:imаge" content="/uploads/_pages/6/картинка.jpg"

Что не есть гуд.

**Comment by maxsite** [comment]
Думаю, что адес нужно указывать полностью. Относительные адреса — изначально проблемные. Если у вас разный протокол, то используйте единый универсальный «//».

**Comment by HaipaiUser** [comment]
Я про то и говорю, что адреса нужно указывать полностью :)
Но когда два протокола - это не реально.
Вот поэтому и предложил сделать проверку и подставлять в путь к файлу используемый в данный момент протокол.

**Comment by maxsite** [comment]
Делайте, предлагайте код.

**Comment by HaipaiUser** [comment]
Ну к примеру если на уровне скина, то в файле custom/template.php заменить:
```php
	if (is_type('page') and isset($page['page_meta']['image_for_page'][0]))
	{
		echo '<meta property="og:image" content="' . $page['page_meta']['image_for_page'][0] . '">';
	}
```
заменить на:
```php
	if (is_type('page') and isset($page['page_meta']['image_for_page'][0]))
	{
		$path_parts = $page['page_meta']['image_for_page'][0];
		$arr = parse_url($path_parts);
		$uri = substr(getinfo('site_url'), 0, -1);
		echo '<meta property="og:image" content="' . $uri, $arr['path'] . '">';
	}
```

**Comment by maxsite** [comment]
Функция parse_url не работает с относительными URL. Ещё раз — если вы используете два протокола, указывайте один универсальный.

**Comment by HaipaiUser** [comment]
parse_url не работает только с универсальным адресом, т.е. вида
//site.com/uploads/путьккартинке/картинка.jpg
но при этом замечательно работает с адресом вида:
/uploads/путьккартинке/картинка.jpg

Теперь далее:
Если указать универсальный протокол, то миниатюра все равно на страничке выводиться не будет. Чтоб выводилась миниатюра, надо указать протокол, т.е. возвращаемся к началу.

**Comment by HaipaiUser** [comment]
В общем самым менее ресурсоемким решением я пока вижу следующее:
На страничке в поле Изображение записи вписываем только путь до картинки,
т.е. вида /uploads/путьккартинке/картинка.jpg
Далее в файле custom/template.php кусок:
```php
	if (is_type('page') and isset($page['page_meta']['image_for_page'][0]))
	{
		echo '<meta property="og:image" content="' . $page['page_meta']['image_for_page'][0] . '">';
	}
```
меняем на:
```php
	if (is_type('page') and isset($page['page_meta']['image_for_page'][0]))
	{
        $path_parts = $page['page_meta']['image_for_page'][0];
        $uri = substr(getinfo('site_url'), 0, -1);
        echo '<meta property="og:image" content="' . $uri, $path_parts . '">';
	}
```
И во всех местах, где выводится миниатюра, тоже по этому же принципу меняем.
Что получаем: при любом протоколе, получаем правильные ссылки.

**Comment by maxsite** [comment]
Вообще-то parse_url  не работает с относительными адресами. http://php.net/manual/ru/function.parse-url.php 

Вы как раз указываете именно отнисительный адрес. Что будет на выходе этой функции придется только гадать. Тем более, что в PHP 5.4.7 изменили её поведение касаемо определения протокола. так что функция точно не годится.

>  Если указать универсальный протокол, то миниатюра все равно на страничке выводиться не будет. Чтоб выводилась миниатюра, надо указать протокол, т.е. возвращаемся к началу.

Я готов двигаться в сторону именно универсального протокола. И если стоит задача сделать миниатюру при таком адресе, то это вопрос вполне обсуждаемый. А вот городить то что вы предлагаете мне совершенно не хочется, поскольку это тупиковый вариант. В конце концов я могу предложить вам как минимум три более простых решения.

1. Получаете адрес из опции (всё равно откуда). Добавляете условие: если есть http но при этом текущий протокол сайта https, то делаете str_replace('http://', 'https://', 'адрес').

2. На сайте используйте редирект с http на https, чтобы сайт всегда работал под одному протоколу.

3. При отдаче страницы в браузер (main/blocks/_end.php) прогоните $OUTPUT через функцию замены протокола на универсальный. Такая функция уже есть в LPF.

**Comment by HaipaiUser** [comment]
К вопросу об parse_url
Ну как то так:
![parse_url](https://cloud.githubusercontent.com/assets/12243307/7985519/c68a776a-0aea-11e5-8924-425c6c9f4b4f.jpg)

**Comment by HaipaiUser** [comment]
Вот гугловские рекомендации на этот счет:
```
Используйте относительные URL для ресурсов, которые находятся на одном защищенном домене.
Например, для перехода на страницу на вашем сайте example.com, использовать <a href="/about/ourCompany.php"> предпочтительнее, чем <a href="https://example.com/about/ourCompany.php"> . Это гарантирует, что ваши ссылки и ресурсы всегда будут использовать HTTPS. За счет этого также уменьшается вероятность ошибок в локальном развитии сайта, так как изображения, страницы и другие ресурсы загружаются из локальной среды разработки, а не из производственной среды.
```

**Comment by maxsite** [comment]
Пошла демагогия. Я вам дал ссылку на доки. Там чётко сказано: не работает с относительными адресами. Кого вы хотите переубедить?

Дальше. Адреса нужно указывать полные. Относительные адреса — зло. Когды вы начнете стаить сайты в подкаталоги, тогда сами поймёте. В MaxSite CMS этот процесс полностью автоматизирован. У вас очень специфичная проблема, которую вы создали сами: а) вместо нормальных адресов используете относительные; б) используете два протокола, хотя можно использовать один. Я вам предложил три варианта решения. Ваш код никуда не годится. Я не хочу его обсуждать, поскольку он только для вас.

**Comment by HaipaiUser** [comment]
Ну если слова гугла про относительные ссылки - зло, тогда извиняйте.
А вышеприведенный код, это не для меня впринципе.
Для себя я уже давно все сделал :)
Я всего лишь написал, что данную функцию надо до ума довести, чтоб народу не заморачиваться, т.к. тот код, что сейчас используется впринципе не рабочий.

**Comment by maxsite** [comment]
Ну тогда и обсуждать нечего.
