### ISSUE TITLE
Добавить указание мета-тегов для категорий

### ISSUE THREAD

**Issue by skull3d** [maxsite/cms#57]
Предлагаю добавить возможность указания мета тегов для категорий (title, description) и дополнительного названия, которое будет выводится на странице категории (для меню одно, для страницы другое).

**Comment by maxsite** [comment]
Как-то попонятней можно?

**Comment by skull3d** [comment]
Предлагаю добавить дополнительные поля при создании/редактировании категорий:
* мета тег Title
* мета тег Description

И желательно еще:
* Название категории которое будет выводится на странице категории в <h1></h1> (и будет отличаться от названия категории выводимого в виджете категорий)

**Comment by maxsite** [comment]
Не понимаю, зачем дублировать то, что уже есть — тоже название и описание?..

**Comment by monenkeskinen** [comment]
Тут наверное имеется в виду, чтобы название и описание рубрик выводилось на странице одно, а теги title и description можно было указывать другие.
Насколько я помню, сейчас описание рубрики, которое выводится на странице, и description - это один и тот же текст. А товарищ хочет, видимо, возможность указывать разный. Как-то так.

**Comment by skull3d** [comment]
"зачем дублировать то, что уже есть"
Для того же, для чего мы дублируем это у публикаций, ведь у них тоже есть название и текст, но при этом и есть возможность указать дополнительно мета-теги.
При продвижении разделов это важно.

**Comment by maxsite** [comment]
Для 99% пользователей системы это вообще никакого значения не имеет.

**Comment by skull3d** [comment]
Ладно, попробую тогда реализовать это для 1% пользователей в виде плагина)

**Comment by maxsite** [comment]
Из пушки по воробьям? Для таких целей придуманы type_foreach-файлы.

**Comment by monenkeskinen** [comment]
Там плагин не нужен. Я, например, использую ушки и хуки, чтобы вывести на странице категории описательную статью, а в качестве title и description используется заголовок и описание категории соответственно. Можете пробовать так. Хотя я все же за то, чтобы это можно было делать на уровне системы.
Извини, Макс, я в PHP на уровне дилетанта, поэтому не совсем понимаю, почему это сложно реализовать. Кстати, такую функцию можно опциональной сделать, если что.

**Comment by skull3d** [comment]
Ну вот, процент заинтересованых явно выше)
MAX, с type_foreach для вывода информации я понимаю, но как доп поля в админку добавить без напильника?

**Comment by maxsite** [comment]
Считаю, что такие meta-поля просто не нужны. Вполне достаточно существующих стандартных. Если хотите доказать обратное, то должна быть полноценна аргументация. Пока её нет, естественно, никто ничего делать не будет. Тем более, что для тех, кому это требуется, могут сами её сделать на уровне шаблона.

Используйте type_foreach-файл. В админке делаете ini-опцию. В ней «секционую» опцию, например по ID рубрики. В type_foreach-файле считываете значения и подставляете в mso_head_meta().

**Comment by skull3d** [comment]
Ясно, через опции шаблона, спасибо.

Для любого контентного проекта это необходимо, для блогов наверное менее востребовано, хотя я себе и для блога делаю такую возможность.

**Comment by monenkeskinen** [comment]
Макс, дублировать мета-поля не нужно. Тут весь смысл в том, чтобы добавить текстовое поле к категориям, куда можно было бы написать статью. Пример:
Есть ресурс о создании сайтов. На нем есть категории о дизайне и продвижении. В каждой из них десяток статей. Пользователь в ПС ищет цикл таких статей по запросу "продвижение сайта" (это все например, опять-таки). У нас на странице категории о продвижении будет заточенная под этот ключ статья с title и description. Пользователь на нее попадает, проглядывает статью и видит ниже список статей на нужную тему.
Короче, это для сео удобно. Реализация по аналогии с главной страницей, где можно текст перед записями вывести.

**Comment by maxsite** [comment]
Описательный текст может быть очень большим, делать его через опцию неверно. Для таких случаев предусмотрены ушки category_SLUG-РУБРИКИ.

Точно также там куча type_foreach-файлов под разный вывод. Делаете файл в нем реализуете логику. Это может быть хоть ушка, хоть опции, хоть отдельные страницы.

**Comment by monenkeskinen** [comment]
Я ушками и делаю. Вроде даже не сложно. Но есть два нюанса:
1. Там не работают автотеги, как в обычной статье.
2. Если категорий много, то ушек приходится плодить тоже вагон.
Не спорю, что такие функции нужны не всем, но для продвижения они удобны. Мне как-то видится админ-страница категории в стиле такой же страницы с обычной статьей.

**Comment by maxsite** [comment]
Такие вещи делаются двумя путями. Первый — отдельный плагин, который добавляет новые возможности редактирования рубрик (и вообще всего что угодно). То есть отдельная страница в админке, где указываются все нужные данные. Второй путь — расширение через шаблон. И опять же — type_foreach-файл и в нем своя логика. И даже автотэги для ушки. Если ушки не годятся, то пусть это будут обычные текстовые файлы, опции и т.п.

**Comment by monenkeskinen** [comment]
Это все было бы замечательно, но для тех, кто дальше if else в php не ушел, плагины и прочие телодвижения будут сложными. Можно и заказать у знающих людей, но мне кажется, что плагин по умолчанию в стандартном наборе CMS позволил бы расширить аудиторию Maxsite.
Конечно, это все на твое усмотрение, Максим. Ты - шеф, тебе решать)

**Comment by maxsite** [comment]
Пока я не вижу смысла из-за этого менять систему. Поэтому единственный путь — кто-то сделает в виде type_foreach-файла или плагина. Дальше уже будем думать конкретно по коду.

**Comment by monenkeskinen** [comment]
Я честно не знаю, насколько это затрагивает основной код системы и насколько это трудозатратно. Поэтому просто поддерживаю такое нововведение. Будет ли оно на уровне плагина или целой системы (или будет ли вообще) - вам виднее. Я просто за это, так сказать, голосую))

**Comment by maxsite** [comment]
Могу пока не закрывать это обсуждение.

**Comment by monenkeskinen** [comment]
Было бы здорово. Спасибо, Максим, за поддержку мнения)

**Comment by skull3d** [comment]
Значит все-таки нужна пушка-плагин. Попробую сделать.

**Comment by HaipaiUser** [comment]
Я поддерживаю monenkeskinen, мысль хорошая.
Я подобное реализовывал для тэгов, но смысл тотже,
когда щелкаешь по тегу в облаке тэгов, то открывается список статей и там в начале мне нужно было добавлять описание к тегу.

Постараюсь объяснить вкратце, как я реализовывал.
Кстати все делалось за минут 10 :)

1. Создал папку для файлов описания.
2. Когда щелкаешь по тегу, то идет проверка есть ли в этой папке файл с именем совпадающим с этим тэгом, если есть то его содержимое выводится перед списком статей.
Если нет такого файла, то автоматом создается пустой файл и с именем тэга.
Потом только остается вписать нужный текст в файл.

Надеюсь понятно объяснил :)

**Comment by HaipaiUser** [comment]
Вот весь кусок кода:
```php
$querytextfiles = htmlspecialchars($qs);
$querytextfiles = strtr($querytextfiles, $qq_translit);

$querytextfile = 'Files/tags/'.$querytextfiles.'.txt';

if  (!file_exists($querytextfile))
	{
$fppp = fopen ("$querytextfile", "w");
fwrite($fppp, " ");
fclose($fppp);
	}
	else
	{
$querytext = file_get_contents ($querytextfile);
	}
```

**Comment by HaipaiUser** [comment]
В общем вот для категорий на скорую руку :)
Создаем папку к примеру в корне сайта assets, в ней еще одну category.

Далее в шаблоне в папке type_foreach создаем файл category-do-pages.php с содержимым:
```php
<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$querytextfiles = htmlspecialchars(mso_get_cat_key('category_name'));

$querytextfiles = mso_slug($querytextfiles);

$querytextfile = 'assets/category/'.$querytextfiles.'.txt';

if  (!file_exists($querytextfile))
    {
$fppp = fopen ("$querytextfile", "w");
fwrite($fppp, " ");
fclose($fppp);
    }
    else
    {
$querytext = file_get_contents ($querytextfile);
    }
echo $querytext;
# end file
```

Наслаждаемся :)

**Comment by flyasky** [comment]
Мне кажется, проще всего для таких целей завести отдельный тип страниц, чтобы они не мешались со статями. Потом сделать ушку, которая смотрит текущий урл и ищет в бд запись из указанного типа у которой, например, короткая ссылка == [имя категории]+[_description].
Удобнее же редактором пользоваться, а не на диск постоянно через ftp лазить. Я так недавно переделывал виджет "Случайные статьи" на предмет того, чтобы он в случае установленной галки "показывать контент" - показывал именно контент, а не заголовок. Получился отличный ротатор случайных коротких рекламных статей в футере.

**Comment by HaipaiUser** [comment]
Базу нагружать всякими глупостями - не есть гуд.
Лично у меня нет никакого желания уже при 1000 уников в сутки, брать выделенный сервер.
Тем более тут раз прописал и забыл.

**Comment by monenkeskinen** [comment]
Решения хорошие, пригодятся. Вот только как-то это все костыльно что ли... "Из коробки" бы все, да с использованием редактора и прочих плюшек!)

**Comment by denis-skripnik** [comment]
Поддерживаю. Часто бывает, что в категории надо прописать текст, а при таком варианте его нельзя впихивать в description.

**Comment by JekaWm** [comment]
Так есть же плагин: "Category title" где все в виде плагина...
http://wave.fantregata.com/page/category-title

**Comment by skull3d** [comment]
Точно, Wave уже давным-давно это реализовал и не палится. Отлично работает на 0.9.

**Comment by denis-skripnik** [comment]
Благодарю. Что-то забыл об этом плагине.

**Comment by ekkky** [comment]
А как можно добавить изображение к категории? Как такое реализовать?

**Comment by skull3d** [comment]
**ekkky**, такой функционал и обсуждался в данном вопросе и все ответы присутствуют.
Для страницы категории картинку можно добавить в описание категории, в него можно HTML вставлять, хоть целую статью с форматированием. Только без легкого напильника выводится она будет на всех страницах категории и в виджете (если он с описанием выводится).

**Comment by ekkky** [comment]
skull3d, куда именно в описание категории записывать картинку? В какое поле? И как считывать ту картинку?

**Comment by skull3d** [comment]
**ekkky**, у категорий одно поле описания, в него и вставляйте HTML код картинки.
