### ISSUE TITLE
Cannonical для статичных страниц без /page/

### ISSUE THREAD

**Issue by skull3d** [maxsite/cms#58]
И по умолчанию и у большинства сайтов на MS в меню, ссылки на статичные страницы, указаны без /page/, но коннонический адрес указывает на страницу с /page/.

**Comment by maxsite** [comment]
Потому что все страницы — это page.

**Comment by skull3d** [comment]
Да, я в курсе, но раз мы не можем генерировать разные каннонические адреса для разных типов страниц, значит логичнее прописывать ссылки в меню, на статические страницы - с page.

**Comment by maxsite** [comment]
Каннонические адреса вообще никакого отношения к меню не имеют. Вы меню указываете как хотите.

**Comment by Tiahin** [comment]
> Да, я в курсе, но раз мы не можем генерировать разные каннонические адреса для разных типов страниц, значит логичнее прописывать ссылки в меню, на статические страницы - с page.

Может я чего-то не понимаю, но что мешает создать новый тип страниц с требуемой частью (окончанием) в URL ?

И потом, поскольку:
> Потому что все страницы — это page.

всегда можно дописать правило в .htaccess-файл + парсилку удаления части *page* из html-кода и повесить ее на `$hook['display_override']`

**Comment by skull3d** [comment]
Данный вопрос возник потому что - в дефолтном шаблоне ссылки на статичные страницы проставлены без /page/, но при включении каннонических адресов, в идексе ПС будет жить страница с /page/. И люди использующие MS так и продолжают ссылаться из меню на неконнонические адреса. Это не великая проблема конечно, но чтобы CMS стала совсем идеальна, я и предложил - либо поправить генерацию cannonical, либо указывать ссылки на статику так же как и на блоговые публикации с /page/.

Tiahin, спасибо за наводку, но я против page в УРЛ ничего против не имею.

**Comment by maxsite** [comment]
Где в шаблоне для static проставлены адреса без page? У нас вообще все страницы формируются с page. Исключений нет.

**Comment by skull3d** [comment]
В меню.

**Comment by maxsite** [comment]
В каком меню?

**Comment by skull3d** [comment]
v0.9
templates\default\components\_menu\_menu.php
12 строка:
about | О сайте

**Comment by maxsite** [comment]
Конечно там должно быть page/about
