### ISSUE TITLE
-

### ISSUE THREAD

**Issue by HaipaiUser** [maxsite/cms#59]
-

**Comment by maxsite** [comment]
Сделайте опцию в шаблоне, где размещайте хоть готовый html-код меню.

**Comment by HaipaiUser** [comment]
Я не прошу сделать как мне надо, я лишь говорю что надо довести до ума эту функцию, отделив html от php, чтоб каждый мог настраивать как ему нужно.

**Comment by maxsite** [comment]
Пока создается впечатление, что вы хотите именно под себя переделать. Мне нужна полноценная аргументация. С примерами, описанием и т.п. Пока я не вижу зачем вообще менять этот код, который уже много лет великолепно работает и подстраивается через css как угодно. Если вам эта схема не нравится, то аргументируйте свою позицию в первую очередь с технической точки зрения. Я вообще с трудом представляю себе, что рядовой блогер будет менять html-разметку через админ-панель.

**Comment by HaipaiUser** [comment]
Сейчас большинство классов как для li, так и для span вынесено в шаблон в файл _menu.php.
Я не предлагаю изменить существующую схему формирования меню, а всего лишь предлагаю вынести оставшиеся классы из common.php в _menu.php.
Вот и все.

**Comment by maxsite** [comment]
Насколько я вижу, автоматом формируются только классы группы group. Остальные классы и так задаются в компоненте и через админку.

**Comment by HaipaiUser** [comment]
first, last, group-first, group-last

**Comment by HaipaiUser** [comment]
Вот к примеру из мануала по bootstrap

```php
        <li><a href="#">Link 1</a></li>
        <li class="active"><a href="#">Link 2</a></li>
        <li><a href="#">Link 3</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
```
Фактически то же самое :)
Из за какой то мелочи приходится лезть в common.php

А чутка доработав function mso_menu_build в common.php, то каждый сможет как ему надо сформировать меню.

**Comment by maxsite** [comment]
Ок. Подумаю.
