### ISSUE TITLE
Автоустановщик/автообновление MaxSite CMS

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#60]
Выкладываю каркас возможного автоустановщика MaxSite CMS. Не проверяйте на рабочем сайте!

http://max-3000.com/uploads/_update_mso.zip

Эта штука позволяет полностью автоматизировать загрузку zip-архива последней версии системы, распаковать его, скопировать на уровень выше и выдать ссылку на инсталяцию.

Порядок такой. Загрузить каталог _update_mso и три его файла на сервер. После набрать в браузере сайт/_update_mso 

Задача — протестировать этот код на разных серверах. Подозреваю, что из-за особенностей хостингов, может что-то неверно работать.

Если получится отработать эти вопросы, то можно будет доделать этот код до полного автообновления MaxSite CMS.

**Comment by HaipaiUser** [comment]
На Денвере работает :)

**Comment by smogendrr** [comment]
на локальном openserver  (apache 2.4.9 php 5.5.10 mysql 5.6.17) сработало нормально, восторг! ;)

однако есть пожелания.
вместе с кодом ошибки (например, нет такой базы) выводить соотвествующий кусок faq с вероятными причинами ошибки и способами исправления, можно просто ссылку на эту информацию.

**Comment by denis-skripnik** [comment]
Благодарю. Скачал. Протестирую на своём виртуальном сервере.
Завтра напишу о результатах.

**Comment by denis-skripnik** [comment]
Здравствуйте. Тест пройден успешно - движок обновился без проблем, вот только database.php пришлось новый загрузить - старый не работал: "Database not connected", но это было и при обычном обновлении.
Операционка Dibian 7, сервер nginx/1.2.1, работает в связке с apache, PHP/5.4.36-0+deb7u3.

**Comment by timurg11** [comment]
При обновлении через автоустановщик - ошибка "Database not connected"

**Comment by denis-skripnik** [comment]
Здравствуйте. Это нормально: перенесите данные базы данных в новый файл, который с движком идёт, и загрузите его, убрав окончание -distr. Всё заработает.

**Comment by timurg11** [comment]
Извините пожалуйста, а можно по-подробнее?

**Comment by timurg11** [comment]
К сожалению ( :( ) обновил боевой сервер, разметка расползлась. Это я сделаю. Еще тут в описании у вас ошибка "Пор!ы!док такой. Загрузить каталог _update_mso и три его файла на сервер. После набрать в браузере сайт/_update_mso ". И здорово было бы если бы добавили в описание автоустановщика о том как ошибку "Database not connected" исправить.

**Comment by maxsite** [comment]
Разметка — это адаптация шаблона к 0.90.

**Comment by maxsite** [comment]
Еще я заметил, что после такого обновления почему-то меняется конец символов в текстовых файлах (.php). Причем в разнобой: где-то LF (линукс), а где-то только CR (мак), хотя исходные либо LF, либо CR+ДА (виндовс). Отпишитесь, у кого такая же проблема.

**Comment by denis-skripnik** [comment]
Подробнее:
1. Открываете database.php вашего сайта.
2. Копируете сервер, логин, пароль и имя БД.
3. Заходите в /application/config и убираете у database.php-distr окончание -distr.
4. Вставляете в этот файл данные базы (В те же строки).
5. Загружаете файл с заменой старого.

**Comment by flyasky** [comment]
он совсем старые версии МСО правильно обновит?

**Comment by maxsite** [comment]
Пробуйте, отпишитесь по результату.

**Comment by maxsite** [comment]
Обновил автоустановщик. Добавил больше логики. Теперь сверка версии идет прямо с гитхаба. Загрузить по тому же адресу:

http://max-3000.com/uploads/_update_mso.zip

**Comment by cuprum** [comment]
На Open-server-e при чистой установке не завелся. Вроде все нормально загрузилось, но когда кликнул перейти к установке, выкинул 404. Ради интереса полностью очистил папку домена, заново залил файлы из _update_mso в корень домена, теперь пишет 
>Последняя версия MaxSite CMS: 0.91
Ваша версия MaxSite CMS: 0.91
Обновление не требуется

Как такое может быть?

**Comment by maxsite** [comment]
> Перейти к инсталяции MaxSite CMS

Проверь какой там указывается (получается) путь в ссылке? Каталог _update_mso должен быть на уровне каталога сайта. Может он тебе в другой каталог установку сделал.

**Comment by cuprum** [comment]
Блин, вот где собака зарыта! Первый пост не читай, сразу делай - про меня. :smile: 
Теперь все установилось, круто!
А можно показывать какой-то прогресс скачивания? сейчас пока идет скачивание и распаковка, в браузере висит ожидание. У меня проводной инет и все происходит быстро, но вот на мобильном интете, возможна приличная задержка, что может вызвать панику :snail:

**Comment by maxsite** [comment]
Какое-то отображение сделать сложно, поскольку должен отработать весь php-скрипт, а уже потом пойдет вывод в браузер. Единственный вариант — использовать нескольок этапов, гед после каждого нужно нажимать кнопку «Далее». Поэтому пока этот вопрос решить не получится.

**Comment by kirik8008** [comment]
Хотел попробовать обновить и вот что получилось.

Последняя версия MaxSite CMS: 0.91
Ваша версия MaxSite CMS: 0.86
Обновление...
Unzip master.zip OK!
Перейти к сайту
Новая версия MaxSite CMS: 0.86
Готово! Не забудьте оставить своё мнение в твиттере о MaxSite CMS!

**Comment by maxsite** [comment]
Скорее всего права на файлы уже установленной системы не позволяют скопировать новую версию.

**Comment by vimruler** [comment]
Сегодня протестировал на сервере с Debian 7. Обновлял с 0.91 до 0.91 вызвав __/_update_mso__ . В целом всё прошло без проблем. Вот только при первом входе в админку получил вот такой эффект "расширения" сайдбара:

![Скрин](http://friendly-urls.vizr.ru/uploads/admin-panel.png)

К слову, после нажатия F5 в браузере всё встало на свои места и больше не возвращалось пока. Странно. Так и не понял что это было.

**Comment by vimruler** [comment]
Кстати, о похожей штуке писали и на [Максхабе](http://maxhub.ru/page/novaja-versija-maxsite-cms-092#comment-1246)

**Comment by maxsite** [comment]
Браузер кэширует файл css-стилей. Обсуждать нечего.

**Comment by vimruler** [comment]
> Браузер кэширует файл css-стилей. Обсуждать нечего.
Уже разобрался. Согласен.

**Comment by andrex4k** [comment]
хм, установщик распаковал движок в &site-root/cms-master и в браузере попытался открыть &host/install которого конечно же там нет).

**Comment by trommo** [comment]
Была проблема с нехваткой cURL'а. Установил его. 

После этого автоустановщик выдает такое:

Последняя версия MaxSite CMS: 0.94
MaxSite CMS на вашем сервере не найдена
Обновление...
Unzip master.zip OK!
Ошибка копирования (index.php)

При этом в папке _update_mso появляется скачанный архив с системой master.zip, а также система в распакованной папке cms-master. По идее, автоустановщик должен был распаковать систему в папку одним уровнем выше, причем не в cms-master, а сразу в корень.

**Comment by maxsite** [comment]
Что это за каталог такой /srv/www/.ru/ ?

**Comment by trommo** [comment]
Это я имя домена заменил звездочками, только редактор Гитхаба его почему-то обрезал. Т.е. каталог называется как домен, как принято обычно.

**Comment by maxsite** [comment]
Возможно что на httpdocs нет прав на запись.

**Comment by trommo** [comment]
Сделал 777. Заработало. Но безопасно ли это? Или после установки-обовления у httpdocs снова убрать права на записи?

**Comment by maxsite** [comment]
Насчет прав это у хостера нужно уточнять. Обычно запись разрешена.

**Comment by trommo** [comment]
Пытался обновить еще один сайт с 0.93 до 0.94. Не получается. В логе ошибок следующие строки повторяются:


[Mon Feb 15 13:52:09.009625 2016] [:error] [pid 1703] [client 95.133.87.89:54259] PHP Warning:  chmod(): Operation not permitted in /srv/www/site.net.ua/httpdocs/_update_mso/index.php on line 192
[Mon Feb 15 13:52:09.009773 2016] [:error] [pid 1703] [client 95.133.87.89:54259] PHP Warning:  chmod(): Operation not permitted in /srv/www/site.net.ua/httpdocs/_update_mso/index.php on line 172
[Mon Feb 15 13:52:09.009835 2016] [:error] [pid 1703] [client 95.133.87.89:54259] PHP Warning:  copy(/srv/www/site.net.ua/httpdocs/index.php): failed to open stream: Permission denied in /srv/www/evrika.net.ua/httpdocs/_update_mso/index.php on line 170

Папка httpdocs имеет права 777, папка автоустановщика _update_mso тоже.

**Comment by maxsite** [comment]
Скорее всего на сервере запрещена функция chmod().

**Comment by trommo** [comment]
Но другие сайты обновлялись нормально, находясь на этом же сервере...

**Comment by trommo** [comment]
Пишет вот такое при вызове автоустановщика:

Последняя версия MaxSite CMS: 0.94
Ваша версия MaxSite CMS: 0.93
Обновление...
Unzip master.zip OK!
Перейти к сайту
Новая версия MaxSite CMS: 0.93
Готово! Не забудьте оставить своё мнение в твиттере о MaxSite CMS!

Похоже на случай у kirik'a: https://github.com/maxsite/cms/issues/60#issuecomment-129876013

**Comment by maxsite** [comment]
Вы ошибку видите? Operation not permitted  — запрещено выполнять функцию chmod. Либо функция заблокирована, либо юзер неверный, либо права каталога не подходят. Уточните у хостера, чего гадать-то?
