### ISSUE TITLE
Баг в плагине Forms 5.0

### ISSUE THREAD

**Issue by skull3d** [maxsite/cms#61]
Если разместить форму на странице без опций:
[options]
"любая опция"
[/options]

к примеру так:
[form]

[field]
require = 1
type = select
description = Тема письма
values = Пожелания по сайту # Нашел ошибку на сайте # Подскажите, пожалуйста
default = Пожелания по сайту
subject = 1
[/field]

[field]
require = 1
type = text
description = Ваше имя
placeholder = Ваше имя
[/field]

[/form]

То вываливаются PHP Notice:
Undefined index: require_title
Undefined index: antispam
Undefined index: reset
Undefined index: ushka

**Comment by maxsite** [comment]
Посмотрю.
