### ISSUE TITLE
(no-title) Вывод списка записей в админ-панели

### ISSUE THREAD

**Issue by polyanskian** [maxsite/cms#62]
## Почемуто всегда выводится `no-title`
Админ-панель > Все записи

ID | Заголовок | Дата... |
----|--------------- | ----------|
1 | no-title [Просмотр] | ...
2 | no-title [Просмотр] | ...
3 | no-title [Просмотр] | ...

Файл: application\maxsite\admin\plugins\admin_page\admin.php
LINE: 261
```
if (!$page['page_title']) $page['page_title'] = 'no-title';
```

$page['page_title'] - почему то всегда пуста???

по идее там долны отображаться данные из переменной `$page['page_slug']`

```
Для себя сделал так:
LINE: 248
if ( !$page['page_title'] ) $page['page_title'] = $page['page_slug'];
```

**Comment by maxsite** [comment]
Если не указан title, то slug также формируется как no-title. Поэтому правка не имеет смысла.

**Comment by polyanskian** [comment]
Странненько... у меня почему-то: 
`$page['page_title']` - всегда пуста :(
`$page['page_slug']` - есть
`$page[page_meta][title]` - есть

Похоже гдето у меня чтото косячит :(
Хочется чтобы отображалось хоть чтото:
либо `title`, либо `slug`... но пока только `no-title`

Причину самостоятельно найти пока не удалось.

**Comment by maxsite** [comment]
И заголовка записи нет?

**Comment by polyanskian** [comment]
>И заголовка записи нет?

Вопрос непонятен.


Создаю запись с демо текстром.
Отображается всегда no-title.
Данные в `$page` есть.
`$page['page_slug']` - есть
`$page[page_meta][title]` - есть

![x](https://cloud.githubusercontent.com/assets/12858739/8145969/d15be0a4-1227-11e5-9279-65f54daa3d69.jpg)

Видно гдето чтото неверно работает у меня.

(Стоял старый Denver PHP 5.2.12. На него поставлены - дополнительные модули, так как небыло Mcrypt)

Теперь стало: Denver: Apache/2.2.22 (Win32) mod_ssl/2.2.22 OpenSSL/1.0.1c PHP/5.3.13
Вроде всё работает, но вот заметил, что выводится в админке в списке записей no-title

**Comment by maxsite** [comment]
При чём тут «Титул страницы»? Заголовок записи указывайте.

**Comment by polyanskian** [comment]
Эх... затупил... стиль оформления очень непонятный в админпанели,
теперь заметил что там над редактором = ТИТУЛ
