### ISSUE TITLE
Список юзеров (авторов)

### ISSUE THREAD

**Issue by jimmyjonezz** [maxsite/cms#63]

**Comment by maxsite** [comment]
О каком списке вообще идет речь? Задача-то в чём состоит?

**Comment by jimmyjonezz** [comment]
Задача: отслеживать ВСЕХ комментаторов, в том числе и юзеров. Чтобы в списке "www.мой_сайт.ru/users" отображались не только комюзеры, но и юзеры.

**Comment by maxsite** [comment]
И где их выводить? Для авторов есть плагин authors.
