### ISSUE TITLE
Проблема с отступами из-за чрезмерного употребления "mar20-b"

### ISSUE THREAD

**Issue by jimmyjonezz** [maxsite/cms#65]
Есть вопрос по верстке. 
Перед блоком "info-top" и "info-bottom" стоят блоки "header" с классом "class="mar20-b" (нижний отступ в 20px). Вопрос и сложность в следующем - возможность контроля верхних и нижних отступов блока с текстом статьи (mso-page-content mso-type-home-content). Отсюда предложение, чтобы "class="mar20-b" перенести в блок mso-page-content, либо в те же "info-top" и "info-bottom". Надеюсь подробно объяснил свою проблему и надеюсь на понимание. Либо прошу меня поправить и объяснить где я заблуждаюсь.

**Comment by maxsite** [comment]
Файлы шаблона отданы на откуп вебмастера. То есть открываете нужный type_foreach-файл и там меняете классы под свою задачу.

**Comment by jimmyjonezz** [comment]
С type_foreach все понятно. Уже выучили. 
По моему мнению, предыдущий вариант шаблона был практически идеален. Была какая-то общность. Не могу объяснить правильнее. Сейчас же ощущение, что прошло некоторое дробление на более мелкие классы стилей. Появилось слишком много нюансов, которые нужно контролировать, как например мой вышеизложенный вариант.

**Comment by cuprum** [comment]
@jimmyjonezz Сейчас шаблоны обладают большей "автономностью", если что-то не устраивает, пилите свой каркас-шаблон для себя. И потом уже, на его основе достаточно просто делать другие шаблоны.
