### ISSUE TITLE
Для чего делать отступ перед заголовками?

### ISSUE THREAD

**Issue by jimmyjonezz** [maxsite/cms#66]
Есть стиль (в style.css), предполагающий, что перед заголовками есть отступ в ЦЕЛЫХ 30px (зачем???):
*+h1, *+h2, *+h3, *+h4, *+h5, *+h6 {
margin-top: 30px;
}

В подключаемых файлах, например info-top, указаны стили для заголовка статьи (вот сюда и можно впихнуть эти 30 px!!!):
```
$p->format('title', '<h1 clаss="t-grаy700 bor-double-b bor3px bor-gray300''>', '</h1>', true);
```

Теперь к сути. Я хочу перед заголовком поставить дату, ну или какой либо другой элемент оформления и у меня получается, что его нужно опускать на 30 px вниз. Хочу обратить внимание, на это у автора CMS. Все в том же style.css есть еще один дублирующий стиль:

h1, h2, h3, h4, h5, h6 {
margin: 10px 0;
}

А вот он зачем?

**Comment by maxsite** [comment]
Давайте так: предположим, что у вас нет доступа к редактированию css/less-файла. То есть подключается какой-то css-файл с набором стилей и изменить его невозможно. 

Где-то в шаблоне/странице/файле (без разницы) есть html-тэг, у которого нужно поменять поведение. В вашем примере убрать отступ margin в H1. Ответьте, каким образом вы будете это делать?

**Comment by jimmyjonezz** [comment]
> Давайте так: предположим, что у вас нет доступа к редактированию css/less-файла.
Почему нет доступа!? Если мне не изменяет память, идеология maxsite зиждется на том, чтобы с легкостью менять css/less стили при создании шаблонов. Меняю CSS - получаю новый шаблон. Разве нет?

> Ответьте, каким образом вы будете это делать?
Созданием отдельного type-файла, с присвоением своих стилей, наверное. Либо перекрываю их своими стилями. Ведь пользовательские стили рангом выше стоят - я о var_style. 

Суть в дублировании стилей?
h1, h2, h3, h4, h5, h6 {
margin: 10px 0;
}

и

*+h1, *+h2, *+h3, *+h4, *+h5, *+h6 {
margin-top: 30px;
} 

И если у меня нет доступа к CSS, то такая конструкция выглядит еще плачевней. 
> h1 clаss="t-grаy700 bor-double-b bor3px bor-gray300

**Comment by maxsite** [comment]
Вы вообще имеете понятие, что такое веб-типографика и как она задаётся? Я не могу объяснять азы вёрстки. В конце-концов потратье хоть немного времени на ознакомление с UniCSS и тога вопросы отпадут сами собой. Конкретно по вашему вопросу — достаточно обнулить или указать любой другой отступ с помощью классов **.marXX.**
