### ISSUE TITLE
Чекбокс в плагинах

### ISSUE THREAD

**Issue by jimmyjonezz** [maxsite/cms#67]
Функция "mso_widget_create_form -> form_checkbox" практически нигде в плагинах не используется, но здесь закралась ошибка оформления этого блока. При использовании следующих стилей:
div.admin-edit-widgets div.admin_widgets input, div.admin-edit-widgets div.admin_widgets select, div.admin-edit-widgets div.admin_widgets textarea {
width: 100%;
}

происходит растягивание флажка и его надпись съезжает - выглядит некрасиво. А если есть описание к флажку, то оно сливается со значением. 
https://drive.google.com/file/d/0B1dO9CmQP4ILOVk4Wkhnb2RlUzA

**Comment by maxsite** [comment]
Это где?

**Comment by jimmyjonezz** [comment]
Допустим если взять плагин random page. В моем примере был использован мой плагин.

**Comment by maxsite** [comment]
Виджет. Увидел. Исправлю.
