### ISSUE TITLE
Настраиваемые ЧПУ

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#68]
Есть ли вероятность, что в будующих версиях MS "из коробки" будет возможность привести ЧПУ к виду?
* для категорий: **nazvanie-saita/nazvanie-categorii/nazvanie-podkategorii**
* для страниц: **nazvanie-saita/nazvanie-categorii/nazvanie-podkategorii/nazvanie-stranici.html** (или без **.html**)

**Comment by skull3d** [comment]
Хорошее предложение, хоть и польза исключительно - эстетическая. Но Макс категоричен в этом вопросе, поэтому из коробки такое врядли такое будет.

**Comment by maxsite** [comment]
Мне просто интересно — а зачем? В чём польза от такого ЧПУ?

**Comment by skull3d** [comment]
Глаз порадовать, особенно для сайтов-визиток на MaxSite.
К примеру статика будет без категории - site/about
А новости в соответствующей категории - site/news/nazvanie-stranici

**Comment by maxsite** [comment]
Для «глаз порадовать» можно и плагином редиректа воспользоваться. Там вообще любой адрес можно придумать.

**Comment by ekkky** [comment]
Для организации логичной иерархии страниц. Яндекс понимает это. Например, страницы:
> /kategorija**A**/stranica**1**
> /kategorija**A**/stranica**2**
> /kategorija**A**/stranica**3**

Будут объединены в рамках одного кластера. Смотреть здесь: *Вебмастер - Индексирование сайта - Структура сайта*

**Comment by maxsite** [comment]
Яндекс любые адреса понимает. Они все абсолютно равнозначные и никак не влияют на поисковую выдачу.

**Comment by ekkky** [comment]
Преимущество при ранжировании в Яндексе есть (у правильных ЧПУ). Еще плюс: возможность использовать на сайте поиск Яндекса, с функционалом поиска по конкретному разделу.

**Comment by maxsite** [comment]
Дайте ссылку на «правильные ЧПУ». Я Яндексом не польузюсь, также дайте ссылку на «функционалом поиска по конкретному разделу».

**Comment by ekkky** [comment]
Вся справка Яндекса для вебмастеров оперирует понятием "раздел сайта". Логичная структура такая: на сайте есть разделы (директории), внутри которых расположены тематические материалы (страницы). То есть происходит логичное разделение на "группы по интересам" - разделы. http://help.yandex.ru/webmaster/site-indexing/site-structure.xml
Какая у нас иерархия страниц (структура сайта): кучас страниц внутри одного единственного раздела "page".

Про поиск по разделу: http://webmaster.ya.ru/replies.xml?item_no=13323

**Comment by maxsite** [comment]
Вообще-то там ни слова о «правильном» ЧПУ. Там вообще нет никаких рекомендаций по поводу адресов.

**Comment by ekkky** [comment]
У них справка именно так построена: http://help.yandex.ru/

**Comment by maxsite** [comment]
И что? Я повторю свой вопрос: «Дайте ссылку на "правильные ЧПУ"».

**Comment by ekkky** [comment]
Здесь частично: http://help.yandex.ru/webmaster/recommendations/site-structure.xml
> Каждый документ должен относиться к своему разделу. Желательно, чтобы вид URL давал представление о том, что содержится на соответствующей странице.

**Comment by maxsite** [comment]
Да ну? Ничего, что вы выдрали два несвязанных между собой предложения?

> Поддерживайте четкую ссылочную структуру на сайте. Каждый документ должен относиться к своему разделу. Следите, чтобы на каждый документ можно было попасть по обычной ссылке

В MaxSite CMS так и сделано.

> Каждая страница должна иметь уникальный адрес (URL). Желательно, чтобы вид URL давал представление о том, что содержится на соответствующей странице. Использование транслитерации в адресах страниц также позволит роботу понять, о чем может быть страница. 

Именно так это сейчас и сделано.

Повторю третий раз вопрос: дайте ссылку на описание «правильный/неправльный» ЧПУ. Бесмысслено что-то обсуждать, пока вы не предоставите полноценную аргументацию своей позиции.

**Comment by ekkky** [comment]
ЧПУ сейчас не являются неправильными, но их можно сделать лучше.
> Да ну? Ничего, что вы выдрали два несвязанных между собой предложения?

Было дело. А как вас еще переубедить, Шерлок?! Возможно, что нет официальных источников, в которых говорится: "Делать ЧПУ именно ТАК ВОТ". Но это не значит, что нет поля для маневров по улучшению ЧПУ!

**Comment by maxsite** [comment]
Обманом вы точно никого не убедите. Единственная причина менять ЧПУ была озвучена выше — «порадовать глаз». Никакой выгоды изменение текущего ЧПУ вы не получите. Таким образом не стоит говорить об «улучшении» ЧПУ. Оно и так полностью покрывает все существующие задачи. Поэтому ваше желание просто не имеет смысла.

**Comment by ekkky** [comment]
О каком обмане речь? Я действительно считаю, что те ЧПУ, которые я предложила в первом посте, отвечают больше этой фразе, чем текущие:
> Каждый документ должен относиться к своему разделу. Желательно, чтобы вид URL давал представление о том, что содержится на соответствующей странице.

Заметьте, перед той фразой я написала "здесь **ЧАСТИЧНО**", то есть это не было **ИДЕАЛЬНОЙ** цитатой, что подразумевает **вольность в изложении**.  А вот вы меня обвинили во лжи, напрасно!

Последний раз обращалась напрямую к разработчику MS CMS около 2 лет назад. Для того, чтобы негатив "осел", потребовались эти годы. Думаю, в следующий раз обращусь не раньше прошествия этого срока!

**Comment by maxsite** [comment]
Вы не можете аргументировать свою позицию, а также нет никаких указаний на сей счет ни на одном поисковике, потому этого просто не может быть. Поисковикам вооще пофиг какие адреса на сайте. Поэтому вы и придумали якобы цитату. Я вас подловил, можете обижаться сколько угодно.

**Comment by flyasky** [comment]
@ekkky, понятие "разделы сайта" отмирает уже лет 8 все никак не отомрет. Делов том, что в том, что выглядет как подкаталог в современном мире может быть вовсе не подкаталог, а другой сайт, другой сервис и вообще это может быть параметр GET запроса. То что идет в URL через "/" вообще воспринимать как подкаталог вредно. Действительно поисковики на количество слешей не реагируют и в начале треда вам посоветовали сделать это через плагин редиректы, если заказчик так хочет видеть "разделы" в УРЛ.

**Comment by skull3d** [comment]
Когда MS достигнет эпогея своей эволюции, возможно Макс все-таки и удовлетворить многочисленные просьбы и добавит возможность генерации ЧПУ по своему шаблону, к примеру как у WP. 
А пока, не убираем далеко костыли и сосредоточимся на другом)

**Comment by ekkky** [comment]
> Поэтому вы и придумали якобы цитату.

Были взяты выдержки из страницы, которые, как мне показалось, могут поставить вас на правильный путь, цитатой их никто не называл, вы сами так интерпретировали. Однако, вместо того, чтобы добавить уже эту фишку с ЧПУ, вы решили играть в сыщика и подлавливать людей!
> Можете обижаться сколько угодно.

Придется! Если решите сменить позицию, то предлагаю бартер: закрытие обиды в обмен на красивые ЧПУ!

P.S. В официальных источниках (в справках ПС) не нашла. Возможно, напишу в Яндекс.

**Comment by vimruler** [comment]
Опубликовал мой вариант [плагина настраиваемых ЧПУ](http://vizr.ru/page/plugin-friendly-urls)
