### ISSUE TITLE
Запрет проверки коментария на XSS

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#69]
Будет ли в новых версия возможность отключения проверки конкретного комментария на XSS/спам/и т.д.
Например, при редактировании комментария появляется такая опция:
![comms](https://cloud.githubusercontent.com/assets/13200830/8545705/80b05a4e-24ca-11e5-974a-2c058b319443.png)

**Comment by maxsite** [comment]
Мы даже не поняли и чём речь. ;-)

**Comment by ekkky** [comment]
**Как допустить к публикации такой комментарий, в первоначальном состоянии, без вмешательства системы?**

Скрин №1:
![1](https://cloud.githubusercontent.com/assets/13200830/8617897/e22a3cd2-2721-11e5-84e1-0bea667ad547.png)
Скрин №2:
![2](https://cloud.githubusercontent.com/assets/13200830/8617910/04ac29fa-2722-11e5-99fc-5c7f2a60e0e0.png)

Чтобы "**Полный текст комментария**" был одобрен.

**Comment by maxsite** [comment]
Приведите полный текст комментария, который вызывает срабатывание XSS-фильтра.

**Comment by ekkky** [comment]
А это и был полный текст:
```
<p style="color: red;">Текст комментария</p>
```

**Comment by maxsite** [comment]
Это в 0.90?

**Comment by ekkky** [comment]
Да, Макс, именно так.
Почему славяне решили разоъбниться? http://vk.com/video?q=%D1%81%D0%B2%D1%8F%D1%89%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F%20%D0%B2%D0%BE%D0%B9%D0%BD%D0%B0&section=search&z=video35171090_159802098

**Comment by ekkky** [comment]
http://vk.com/audios59047350

**Comment by ekkky** [comment]
0.90 включительно!

**Comment by maxsite** [comment]
У меня такого не наблюдается.
