### ISSUE TITLE
Идеи

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#70]
Здравствуйте.
1. Сделать мультизагрузку файлов в загрузках - гораздо удобнее, чем по 3 файла.
2. Не вижу смысла использовать для вывода главной админки и других страниц плагины админские, например, admin_home. Не лучше ли вынести это всё в type? Тогда у создателей шаблонов появится возможность сотворения уникальных интерфейсов со множеством функций. Ту же проблему с ссылкой редактирования записи каждый сможет решить, как захочет, не меняя файлы плагинов, а значит не рискуя потерять всё после обновления. Можно также сделать папку с файлами, позволяющими менять внешний вид, ссылаясь на плагин (Если нет желания кординально всё менять).
3. Видел в 0.863, что в шаблоне админки есть заготовка под панель уведомлений. Предлагаю:
1. Вывести текст о том, что появилась новая версия со ссылкой на страницу новой версии, а когда будет доработан скрипт автообновления - с кнопкой "Обновить";
2. Ссылка в той-же панели на страницу с комментариями. Она выводится только в том случае, если новые комментарии, требующие проверки, имеются. Это будет очень удобно для тех, кто сделал проверку новых комментов перед публикацией.
4. Добавьте Editor_trumbowig в стандартную поставку движка - новички скажут спасибо.
5. Нравится в Wordpress то, что можно проверять обновления всех шаблонов и плагинов из админки. Было бы замечательно, если была бы страница, на которой разработчики плагинов и шаблонов могли бы менять версию при выпуске обновления и указывать ссылку на скачивание.
Ещё один вариант - это использование скрипта автообновления, только вместо CMS обновляется плагин или шаблон. Естественно будут проверяться обновления у тех плагинов и шаблонов, в папке которого имеется созданный вами скрипт, адаптированный под этот плагин (шаблон). Тогда ничего вам дополнительно создавать не надо (Только систему, которая ищет данный скрипт в папке с плагином и предлагает найти обновления).

**Comment by maxsite** [comment]
> 1. Сделать мультизагрузку файлов в загрузках - гораздо удобнее, чем по 3 файла.

Количество файлов можно указать другое в настройке админки. Вообще попытки сделать аякс-загрузку с произвольным количеством полей уже были, но не получилось.

>  3. Видел в 0.863, что в шаблоне админки есть заготовка под панель уведомлений. Предлагаю:

Она оказалась невостребованной, ноэтому в .9x её уже нет. Чем наполнить admin_home никто толком не знает. Там должна быть какая-то полезная информация. Пусть кто-нибудь возьмется и нарисует концепт admin_home с блоками, нужной функциональностью. Дальше обсудим и подумаем как реализовать.

>  4. Добавьте Editor_trumbowig в стандартную поставку движка - новички скажут спасибо.

Добавить-то не проблема, но кто будет его поддерживать? Вот сейчас я вижу проблемы с редактированием старых записей в этом редакторе — весь текст оказывается в едином мессиве. Как только будут желающие взять полноценую длительную поддержку редактора, тогда модно говорить и о включении в комплект системы.

>  5. Нравится в Wordpress то, что можно проверять обновления всех шаблонов и плагинов из админки. Было бы замечательно, если была бы страница, на которой разработчики плагинов и шаблонов могли бы менять версию при выпуске обновления и указывать ссылку на скачивание.

Такой вараинт у нас не получится, поскольку у нас нет центрального сервера, где храняться и обновляются все плагины. У WordPress есть специальный API, через который можно добавлять на центральный сервер свои разработки. 

>  2. Не вижу смысла использовать для вывода главной админки и других страниц плагины админские, например, admin_home. Не лучше ли вынести это всё в type? Тогда у создателей шаблонов появится возможность сотворения уникальных интерфейсов со множеством функций. Ту же проблему с ссылкой редактирования записи каждый сможет решить, как захочет, не меняя файлы плагинов, а значит не рискуя потерять всё после обновления. Можно также сделать папку с файлами, позволяющими менять внешний вид, ссылаясь на плагин (Если нет желания кординально всё менять).

Вот тут не понял... Как это, type-файлы для админки? В плагинах админки нет никаких type-файлов.

**Comment by denis-skripnik** [comment]
Со всем согласен, что вы написали. По поводу type-файлов. Я предлагаю вместо админских плагинов использовать type-файлы внутри шаблона. То есть, например, maxsite/admin/template/default/type
В этой папке уже находятся папки типов страниц.
Я знаю, что этого нет - это предложение.
Можно вместо type использовать type_foreach. Суть в том, чтобы в этих файлах подключался плагин, а затем уже обрабатывался внешний вид этого плагина.

**Comment by maxsite** [comment]
Я не понимаю о каких админ-плагинах идет речь. Там нет никаких type или type_foreach-файлов.

**Comment by denis-skripnik** [comment]
admin/plugins/admin_home, admin/plugins/admin_page и так далее.

**Comment by maxsite** [comment]
Денис, это абстракция. Админ-плагины выполняют какую-то сложную задачу. Их невозможно как-то кастомизировать со стороны шаблона. Поэтому если действительно нужно что-то добавить/изменить в админ-плагине, то лучше оформить отдельным тикетом под точную задачу. Лучше всего такие вещи делать через хуки.

**Comment by ekkky** [comment]
Как вам идея: возможность изменения адреса админ-панели на произвольный. Например:
> меняем **site.ru/admin** на **site.ru/xyz**

В целях безопасности!

**Comment by denis-skripnik** [comment]
По поводу плагинов - ясно.
"меняем site.ru/admin на site.ru/xyz".
Хорошо бы, но я понимаю, что на уровне ядра сделать это очень сложно (Придётся каким-то образом переделывать все плагины, менять код в многих ядровых файлах, а также проверять значение адреса каждый раз). Читал инструкцию по смене адреса на одном из блогов - много чего надо делать как в ядре, так и в плагинах.

**Comment by maxsite** [comment]
> В целях безопасности!

И с каких это пор адрес админки вдруг стал влиять на безопасность?

**Comment by ekkky** [comment]
Незнание адреса сделает невозможным подбор пароля.

**Comment by monenkeskinen** [comment]
Пароль можно подобрать и не зная адреса админки. Через виджет логина, по кнопке "вход" в комментариях и т.д. Так что не очень целесообразно, думаю)

**Comment by cuprum** [comment]
Кстати, по поводу обновлений. Предметно я не изучал, но если порассуждать, то для всех компонентов (шаблоны, плагины), выкладываемых на Гитхаб, наверное, можно придумать какой-то общий механизм автообновлений (или по крайней мере, уведомление о новых версиях), который будет встроен в систему. 
По крайней мере, продукты, которые хостятся на аналогичном SourceForge прекрасно обновляются в автоматическом режиме, Видимо, API сайта это позволяет.

**Comment by maxsite** [comment]
Теоретически обновление возможно, если есть адрес на zip-архив где скачка файла) и конечное расположение каталога (каталога, шаблона — без разницы) на сервере. Само по себе обновление работает довольно просто — скачать файл, распаковать в temp-каталог на сервере и проверить отличие файлов от существующих. Если есть различия, то заменить файлы. Всё. Поэтому чтобы сделать автообновление, то это в первую очередь не проблема MaxSite CMS или php-скрипта, а проблема разработчика плагина, который должен каким-то невероятным способом сообщить данные для загрузки. Лично я вижу только один выход — создание центрального сервера, где и будет храниться вся информация. Придумать же API в общем-то не сложно.
