### ISSUE TITLE
Произвольный css-класс виджета

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#71]
В настройках сайдбара можно указать не только условие отображения, но и произвольный css-класс. Класс указывается внутри блока ` @класс@ ` в произвольном месте строки, например
```
category_widget @t-red visible-tablet@
category_widget рубрики @t-red visible-tablet@
category_widget 7 is_type('page') @t-red visible-tablet@
```

**Comment by ekkky** [comment]
Вопрос: зачем это нужно? Для кастомизации .css все есть.
Если у нас один category_widget, то указываем стили для него. Если несколько: 7, 8, 9, то для каждого есть возможность указать стили.

**Comment by maxsite** [comment]
Например таким образом можно скрывать виджет для мобильной версии без правки css-кода.

**Comment by monenkeskinen** [comment]
Кстати, удобно. Можно из админки более гибко настраивать условия вывода виджетов и внешний вид. До этого приходилось постоянно открывать файл стилей.

**Comment by maxsite** [comment]
Готово.
