### ISSUE TITLE
Об уведомлениях о новых комментариях

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#72]
Здравствуйте. Прошу убрать уведомление о комментарии, оставленном человеком. Т есть когда человек отправляет комментарий, получает сообщение о нём - этого не нужно. Вот что попросила читательница:
"Денис, а есть возможность отключить оповещение о моем сообщении? Я же не идиотка, написав коммент, забыть о чем он?. Сильно раздражает эта приблуда =(".
Буду благодарен за изменение или инструкцию по отключению. Хотя думаю, что все согласятся, что это должно быть на уровне ядра.

**Comment by denis-skripnik** [comment]
Забыл. Вот страница, где оставлен коммент (Чтобы не быть голословным): http://denis-skripnik.ru/page/udobstvo-blogov-dlja-ljudej
Заранее очень благодарю.
P. S. Инструкция тоже не помешает даже если платформа будет обновляться.
P. P. S. Maxsite CMS v0.863

**Comment by ekkky** [comment]
Не факт. Мне, например, иногда нужна копия своего сообщения. Можно такое реализовать, но опционально, по-умолчанию такого делать не надо, ИМХО!

**Comment by denis-skripnik** [comment]
Да: лучше сделать опцию в комментировании, позволяющую или запрещающую рассылку сообщения при отправке комментария.

**Comment by maxsite** [comment]
Для админов есть опция «Уведомлять о своих комментариях». Для комюзеров нужно думать. По-идее это должна быть опция на своей странице.

**Comment by denis-skripnik** [comment]
Я с вами согласен. Только админ должен указать, отмечена эта галочка по умолчанию или нет.
Благодарю за внедрение.
