### ISSUE TITLE
Записи только в дочерней рубрике

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#73]
Имеем рубрику "**rubrika**", у нее есть подрубрика "**podrubrika**". Вот они:
> site.ru/category/**rubrika**
> site.ru/category/**podrubrika**

Есть запись "**zapis**", она принадлежит и rubrika, и podrubrika. Вот она:
> site.ru/page/**zapis**

Данная запись будет выводиться и на страницах **rubrika**, и на страницах **podrubrika**.
Идея (опционально): запись должна выводиться только на страница самой последней подрубрики. В данной примере, только на страницах **podrubrika**.

**Comment by maxsite** [comment]
Отмечаете только podrubrika и запись выводится только там. Сейчас так всё и работает.
