### ISSUE TITLE
Размеры миниатюры

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#74]
Сейчас мы можем указать только одну сторону (по максимальной стороне).

**Идея: возможность указывать обе стороны!**

Например, изображение 700x200px. Мы указываем значения обрезки: 100px по ширине и 10px по высоте, выбираем метод обрезки **(crop) по центру**.

Было:
![123](https://cloud.githubusercontent.com/assets/13200830/8619444/8915c364-2730-11e5-8d35-ad2035f91103.jpg)

Получили миниатюру по нашим правилам:
![1234](https://cloud.githubusercontent.com/assets/13200830/8619354/f0389748-272f-11e5-8734-1ad775a86e7e.jpg)

**Comment by ekkky** [comment]
reserved

**Comment by ekkky** [comment]
reserved

**Comment by maxsite** [comment]
Ну а где в этом практическая польза? В настройках уже есть опции с шириной и высотой изображения для записи.
