### ISSUE TITLE
Привязка комментария к другой записи

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#75]
Предлагаю доработать панель редактирования комментария в админ-панели таким образом, чтобы вебмастер мог перенести комментарий от одной записи (к которой был оставлен комментарий) к другой. Т.е. чтобы мог изменить привязку комментария к записи.

Иногда посетители оставляют комментарий там, «где придётся». Я как вебмастер часто вижу, что некоторые комментарии было бы уместно привязать к другим соответствующим записям. Но сейчас есть возможность это сделать только путём ручной правки базы данных.

В общем, хотел бы услышать возможные минусы-плюсы и идеи реализации такой функции в админке. Возможно я бы сам её реализовал, если будет понятно, что такое нужно не только мне и понятно как реализовать лучше всего.

**Comment by ekkky** [comment]
Ни разу не сталкивалась с такой проблемой. Говорю просто для статистики.

**Comment by vimruler** [comment]
Катя, спасибо. Я тоже не сразу пришёл к этой проблеме. Сейчас, например, мне хочется создать отдельный пост для благодарностей и скидывать туда каменты, где текст тиапа «Спасибо!», чтобы они сохранились, но не «болтались по ногами» :)

**Comment by ekkky** [comment]
Илья, идея понятна! :cat2:

**Comment by maxsite** [comment]
Илья, это если и делать, то отдельным админ-плагином или файлом (admin_comments_admin по 3-му сегменту). Сам я тоже пока не вижу в этом потребности, но файл маленький, так что на твоё усмотрение.
