### ISSUE TITLE
Плагин hotlink — произвольные URL

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#77]
C помощью плагина можно будет выстроить соответствие произвольным URL  типовому адресу MaxSite CMS. Например, чтобы типовой page/about был доступен по адресу (произвольно) putin-huilo, в плагине указывается правило

``` putin-huilo| page| about ```

Формат

``` адрес | тип данных | короткая ссылка```

Допускается использование регулярных выражений. 

Ещё примеры:

```
about/contact | category | news
blog/(.*) | category | $1
about | page | about 
```
Данная возможность фактически позволяет задавать произвольное ЧПУ под свою здачу. 

ps Кто-то там хотел много денег за эту возможность заплатить, самое время. ;-)

**Comment by skull3d** [comment]
Круто, самый ожидаемый сообществом плагин ))
А с функцией генерации cannonical дружить будет?

**Comment by monenkeskinen** [comment]
Гибкость системы с каждым разом просто зашкаливает!) Спасибо.

**Comment by maxsite** [comment]
>  А с функцией генерации cannonical дружить будет?

Будет.

**Comment by ekkky** [comment]
Отличное решение затевается! Но зачем негатив опять?

**Comment by maxsite** [comment]
Объявляю такую схему. Если плагин кому-то реально нужен, то пусть указывает сумму, которую он готов за него заплатить. То есть ничего сразу платить не нужно, просто отметиться сколько готов денег пложить в разработку. Посмотрим какая итоговая сумма будет задекларирована.

**Comment by skull3d** [comment]
5$ отдам не задумываясь.
Надо на офсайте эту тему поднять, тут мало народа.

**Comment by denis-skripnik** [comment]
300 рублей, если он будет позволять заменять слаг для всех страниц, а не для определённой, например так:
http://site.ru/my/*.* | http://site.ru/page/*.* и он не будет создавать дублей, то есть будет на обычных адресах ошибка 404, 500 рублей.
Если будет возможность создания виджетов последних записей, внедрения в шаблон без труда, создания виджетов последних комментариев и т. п. В общем, чтобы не было проблем со ссылками, например, в категориях или метках, 1500 рублей.

**Comment by maxsite** [comment]
Старые адреса остаются, куда они денутся-то? Работает плагин ровно как я описал: входяший адрес можно соотнести с произвольным type и slug.

**Comment by smogendrr** [comment]
Макс, а редирект со старого адреса на новый можно будет сделать или старый должен оставаться доступным?

Если конфликтов с прошлыми наработками не создаст, готов вложить 1000 руб.

**Comment by maxsite** [comment]
Ещё раз — старые адреса остаются, это часть системы и она никуда не денется. Но, появляется возможность использовать любые другие адреса, коорые будут соответствовать типу данных системы.
