### ISSUE TITLE
Проблемы с плагином less_compiling

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#79]
С nodejs-ным less-ом вообще не завелся, выдает пустой итоговый css.
С php-ным сыплет ошибками:
```
lessphp fatal error: .pad0-tb is undefined: failed at `s';
` line: 15

    /* .UniCSS -> http://unicss.maxsite.com.ua/ */
    // mixins
    @import 'unicss/mixins/less-framework-lite.less';
    @import 'unicss/mixins/colors-gmd.less';
    // less-variables
    @import 'main/variables.less';
    // UniCSS
    @import 'unicss/unicss.less';
    // main
    @import 'main/extension-unicss.less';
    @import 'main/base.less';
    @import 'main/forms.less';
    @import 'main/my-template.less';
    @import 'component/menu.less';
```

**Comment by maxsite** [comment]
С lessphp и не будет работать — он несовместим с less-кодом. А lessc — проверь путь к файлу. Может он по другому адресу расположен.

**Comment by cuprum** [comment]
@maxsite Не, адрес верный.
Смотри что у меня выдает 'pr($com);'
```
c:^\Users^\Yrst^\AppData^\Roaming^\npm^\lessc.cmd ^"D:^\OpenServer^\domains^\mxxdev.ru^\application^\maxsite^\plugins^\rrr^\style.less^" ^> ^"D:^\OpenServer^\domains^\mxxdev.ru^\application^\maxsite^\plugins^\rrr^\style.css^"
```
Так и надо?

**Comment by maxsite** [comment]
Ты проверь есть ли реально файл c:\Users\Yrst\AppData\Roaming\npm\lessc.cmd

**Comment by cuprum** [comment]
Он точно есть ;)

**Comment by cuprum** [comment]
@maxsite меня смущают вот эти крышки `^` в путях. Набрал пути вручную в командной строке без них, все скомпилировалось, с ^ кидает ошибку "файл не найден"

**Comment by maxsite** [comment]
Если файл находится, то компиляция должна быть. Ещё может быть проблема если если в less коде ошибки. «Крышки» должны быть - это экранирование для php-функции exec.

**Comment by cuprum** [comment]
А может дело в чем-то другом? Я временно закомментил escapeshellcmd и скопировал, что выдает pr($com); в ConEmu. Less прекрасно компилируется. Но при том же пути, переданном в exec, у итогового css только изменяется дата его модификации, а сам он остается пустым.

**Comment by maxsite** [comment]
Мне сложно туту что-то сказать. Формально exec() — это и есть командная строка. То есть она как-бы ничего и не делает, только запускает этот bat-ник. Возможно еще причина в ненайденных путях. То есть можжет быть нужно прописать PATH «где-то» и указывающий на что-то, например node.js. Я просто не знаю.

Вот на всякий случай мой lessc.cmd

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\less\bin\lessc" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\less\bin\lessc" %*
)
```

**Comment by cuprum** [comment]
Разобрался. В общем, это частный случай. В настройках Open-server на вкладке "сервер" у переменной Path должно быть выбрано значение из списка "Свой Path + Win Path".

**Comment by maxsite** [comment]
Ок. Закрывать тикет?

**Comment by cuprum** [comment]
Ага. Если у кого-то будут проблемы с компиляцией на Open server можно направлять сюда.
