### ISSUE TITLE
Плагин colorbox

### ISSUE THREAD

**Issue by xlarin** [maxsite/cms#8]
В последней версии не работает плагин colorbox

**Comment by maxsite** [comment]
Нужно чтобы кто-то проверил можно ли заменить colorbox на последнюю версию https://github.com/jackmoore/colorbox и какие при этом менять стили.

**Comment by skull3d** [comment]
На свежеустановленной - 0.863 версии, colorbox прекрасно работает, но обновить все равно не помешает.

**Comment by vimruler** [comment]
Там бы ещё в плагин добавить возможность добавления своего стиля оформления...

**Comment by maxsite** [comment]
Перенес на новую задачу: https://github.com/maxsite/cms/issues/52
