### ISSUE TITLE
Редактор текстовых файлов

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#80]
Это обычный textarea, без наворотов, только сохранение текста по аяксу. Смысл редактора в том, чтобы позволить пользователю редактировать какие-то предопределенные файлы.

Например, где-то в файле шаблона задается список файлов для редактирования (скажем файл компонента, css-файл, php-файл и т.п.). При входе в редактор, пользователь видит выпадающий список этих файлов. Выбирает, текст загружается в редактор. Дальше правка и сохранение.

Нужно ли такое?

**Comment by skull3d** [comment]
Да, отличная идея, конечно пригодится. Кстати во многих CMS есть подобная возможность, а MS то лучше.

**Comment by maxsite** [comment]
Сделал такую возможность. Можно редактировать любой файл текущего шаблона.

**Comment by ekkky** [comment]
Полезная вещь!

**Comment by maxsite** [comment]
В textarea не может быть подсветки кода.

**Comment by vimruler** [comment]
> Почему бы не подключить подсветку кода для textarea? Вообще хорошо будет!
> В textarea не может быть подсветки кода.

Я такой js-библиотеки не видел. Но если кто-то найдёт нормальную, то можно было бы подумать о подключении. А пока, Катя, увы.

**Comment by ekkky** [comment]
> В textarea не может быть подсветки кода.

Ясно. Жаль. Я имела в виду, что-то похожее, как подсветка кода в Notepad ++.

> Я такой js-библиотеки не видел. Но если кто-то найдёт нормальную, то можно было бы подумать о подключении. А пока, Катя, увы.

Круто было бы! Очень удобно!

**Comment by skull3d** [comment]
Для подсветки можно что-то типа Ace прикрутить - http://ace.c9.io/#nav=embedding, только нужно ли.

**Comment by vimruler** [comment]
> Для подсветки можно что-то типа Ace прикрутить - http://ace.c9.io/#nav=embedding, только нужно ли.

@maxsite как думаешь, нужно прикручивать непосредственно в плагин editor_files или делать отдельный плагин для желающих раскрашивать код? Хочу попробовать прикрутить, но мне нужно знать как лучше это сделать.

**Comment by maxsite** [comment]
Зачем там вообще подсветка нужна?

**Comment by vimruler** [comment]
> Зачем там вообще подсветка нужна?

Думаю, что так было бы легче ориентироваться в коде, когда ищешь нужный фрагмент для правки.

**Comment by maxsite** [comment]
Этот редактор очень специфичный под редкие задачи. Навешивать на него тонну тормознутых js-скриптов, только ради бессмысленной раскраски текста, это явный перебор. Таких перделок-украшалок в Сети вагон и маленькая тележка. Но чтобы что-то прикручивать, вначале нужно определить, а нужно ли? Возникнет потребность, тогда и будем думать.
