### ISSUE TITLE
О опциях меню

### ISSUE THREAD

**Issue by JekaWm** [maxsite/cms#81]
Доброго времени суток.
В данный момент когда настраиваем меню вижу подсказку как и в "старых" версиях:

Полный формат: ссылка | название | подсказка | css-класс

Хотя если взглянуть на функцию, то это не совсем корректно. Как я понимаю можно с версии 0,90 делать так:

ссылка | название | подсказка | li -css-класс |span -css-класс(иконка) | свойство ссылки( rel="nofollow")

P.s: очень удобно, понравилось нововведение.

**Comment by maxsite** [comment]
Ок. Поправлю.
