### ISSUE TITLE
Не хватает быстрой отписки от уведомлений о комментариях

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#82]
Здравствуйте. Вот что прислали:
"Денис, привет! Это конечно все хорошо, но как допустим отписаться от комментариев. Я, например, не".
Буду благодарен, если в конце письма будет ссылка на страницу отписки или прямая ссылка на отписку от комментариев к определённой статье.
Благодарю. Это очень важно, иначе большая часть пользователей Maxsite CMS сталкнётся с проблемой попадания писем в спам.

**Comment by maxsite** [comment]
Существует опция у комюзера на подсписку новых комментариев, где он участвует. Как сделать отписку конкретной одной записи, я пока не знаю. Предлагайте идеи.

**Comment by denis-skripnik** [comment]
Путём генерации временной ссылки, по клику на которую открывается страница, её можно сделать в type.
Ссылка генерируется на основе id статьи и id комментатора.
Также можно было бы сделать подписку к каждой статье отдельно под формой комментирования, дабы дать возможность выбирать, на чт подписываться.
Я плохо знаком с принципами php/mysql, но вот как наверное должно всё работать:
В таблице комментаторов создаётся новое поле - usersubscribes, где выводится список id записей.
Система проверяет наличие записи в списке и присылает уведомление, попутно создав ссылку отписки, по клику на которую отправляется запрос на удаление id записи.
Когда пользователь отмечает запись в качестве подписываемой, в базу отправляется новый id.
Мне кажется, что управлять частями полей нельзя, но как сделать иначе, не знаю (Нельзя ведь создать подтаблицу).
Можно конечно для каждого пользователя создавать отдельное поле, но это нерационально.

**Comment by maxsite** [comment]
Тут фишка в том, что требуется создавать связку comuser_id и page_id, где и хранить отметку об отписке. Это потребует довольно больших изменений в системе. Поэтому я пока оставлю тикет для обсуждения.

**Comment by denis-skripnik** [comment]
а если создать новую таблицу subscribe, где будет выводиться соответствие записей и пользователей без ссвязки их таблиц? или так нельзя.

**Comment by denis-skripnik** [comment]
Сейчас обнаружил, что подписка на комментарии на некоторых wordpress блогах выполняется через wordpress.com.
Может и тут также сделать? Когда человек отправляет комментарий с отмеченной галочкой, информация о записи и e-mail посетителя отправляется на сервер центральный, после этого через мониторинг rss комментариев отправляет информацию о новых комментах посетителю. Когда он захочет отписаться, нажимает на ссылку в письме и переходит на страницу отписки на центральном сервере.
Коме этого, это можно монитизировать, разрешив прикрутку поддоменов и сделав возможным установки плагина (Опции в плагине), который будет конвертировать ссылку отписки в виде адреса сайта.
Можно размещать баннер в начале письма и отключать его за деньги небольшие.

**Comment by maxsite** [comment]
Проще тогда дискус использовать.

**Comment by denis-skripnik** [comment]
Дискус неудобная система. Общался с некоторыми: многие так считают. Неудобная с точки зрения комментирования.

**Comment by denis-skripnik** [comment]
Тогда добавьте в письма уведомлений ссылку на редактирование профиля посетителя, где он сможет отписаться. Вот только можно было бы сделать отписку в самом верху...

**Comment by cuprum** [comment]
@denis-skripnik А какие недостатки у Дискуса? Просто интересно. По опыту комментирования единственное, что не нравится, это как работает система антиспама. Иногда белый и пушистый комментарий может быть принят за спам и пользователь автоматически банится.

**Comment by denis-skripnik** [comment]
1. Нет Русских социалок.
2. Нет наглядного выбора анонимного комментирования, а авторизовываться или регистрироваться лень - надоели пароли.
3. Лишний вывод записей блога внутри фрейма системы.

**Comment by maxsite** [comment]
Оффтоп. Дискус — самая распространенная система и её прелесть как раз в том, что достаточно один раз зарегистрироваться и участвовать в обсуждении на любом сайте (поэтому iframe и используется). Такая вот кроссайтовая авторизация. Лично я бы с удовольствием отказался бы от нативного комментирования в пользу дискуса или другой подобной системы. Отсутствие контактика меня не смущает. Чем меньше детей на сайте, тем лучше. Пусть вон, на солнышке погуляют. :-)

**Comment by denis-skripnik** [comment]
Мне нравится svkament, но нельзя сделать импорт всех комментариев за всё время.
А по поводу Вконтакте: там не одни дети - это уже в прошлом. :-)
У меня 100 с чем-то друзей-блоггеров там, которым по 20-50 лет.
