### ISSUE TITLE
Продублировать readme

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#83]
Предлагаю сделать дубль readme в виде единого (install-ru.txt + team.txt + ссылки на лицезии) html-файла и положить в корень дистрибутива (как в wp).  Плюсы:

* Сразу видно где лежит. Сейчас, если чел скачал архив CMS по ссылке, не заходя на главную страницу репозитория, приходится искать файл описания в `install\readme\`.
* Ссылки внутри файла действительно станут ссылками.
* Наконец, можно как-нибудь оформить, приятнее читать :smiley:

**Comment by maxsite** [comment]
Меня, если честно, больше волнует как сделать ссылку на автоустановку, чтобы можно было только её скачать и через неё уже устанавливать систему.

**Comment by cuprum** [comment]
А можно поподробнее. Закачиваем на сервер какой-то один php-файл, запускаем в браузере и идет полная установка дистрибутива системы. Ты про это?

**Comment by maxsite** [comment]
Ну да — https://github.com/maxsite/cms/issues/60

**Comment by cuprum** [comment]
Ок. Попробую.
