### ISSUE TITLE
Добавить указатели в админке у сворачивающихся блоков.

### ISSUE THREAD

**Issue by cuprum** [maxsite/cms#84]
Собственно, я про это: 
![2015-08-06_212725](https://cloud.githubusercontent.com/assets/532546/9120020/986c3e3a-3c82-11e5-83f7-ac7333ca0b11.png)
Т. е. когда Блоки (Содержимое, Настройки, Пользователи) свернуты, добавлять к ним такую "птичку".

**Comment by maxsite** [comment]
Можно.

**Comment by cuprum** [comment]
Я вот подумал, может создать для админки, какой-то долгоиграющий тикет, где обсуждать все аспекты, пока ты делаешь новую версию?

**Comment by maxsite** [comment]
Так вроде по админке замечаний нет совсем.  Для меня это сигнал, что всех админка  на 100% устраивает.

**Comment by vimruler** [comment]
> Так вроде по админке замечаний нет совсем. Для меня это сигнал, что всех админка на 100% устраивает.

Хм. Я наверно что-то пропустил, ибо помнится была фраза о том, что работы по оформлению админки не закончены и как-бы пока рано что-то предъявлять. Так то у меня много "претензий" по оформлению и я просто жду когда ты реализуешь всё, что задумал, а потом уже хотел подключиться к работе по оформлению...

**Comment by maxsite** [comment]
Не, я ничего в админке уже не делаю. Ты знаешь правила:  нет замечаний, значит всё работает как нужно.

**Comment by cuprum** [comment]
У меня почему-то сложилось такое же впечатление как у Ильи. По-крайней мере в посте про 090 было
>Админ-панель переделана на адаптивный дизайн. Однако она пока ещё в стадии работы и будет дорабатываться уже по ходу. 
А больше ничего. Вот и получается, что не совсем понятная стадия работы над админкой.

**Comment by cuprum** [comment]
Случайно закрыл.
В общем, есть еще мысли по админке. Лучше конечно ее обсуждать в отдельном тикете...

**Comment by vimruler** [comment]
> Лучше, конечно, ее обсуждать в отдельном тикете...

Да, давайте создадим специальный тикет для обсуждения.
