### ISSUE TITLE
Улучшения админ-панели

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#85]
Завожу отдельный топик для высказывания пожеланий и идей по улучшению админ-панели.

То, что беспокоит меня:

1. Цветовое оформление. Точнее засилие серого цвета при оформлении таблиц и форм. Возможно дело привычки, но лично мне сложновато ориентироваться и находить нужные элементы. Раньше (в прошлой версии) как-то всё отчётливее всё было. Сейчас отчётливость появляется только у элементов форм и то только при выделении элемента.

2. Сайдбар админки не на всех страницах упирается в пол (тестировал на 0.90). Это как бы и не проблема вроде. Но чисто визуально воспринимается как недоработка.

3. Хотелось бы навести порядок с плагинами, которые выводят пункт меню в сайдбар админки - не все плагины должны постоянно "болтаться" там. Так, плагин "Ушки" хоть и нужный, но всё таки не настолько часто к нему обращаться приходится чтобы держать ссылку на его настройки в сайдбаре админки. Для этого есть специальное место со ссылками на опции плагинов. Ещё могу припомнить такую же проблему с плагином Colorbox.

**Comment by maxsite** [comment]
В бытность моей работы в полиграфии, было такое правило — не знаешь какой использовать цвет, используй серый. :) Предложи свой вариант цветового решения.

**Comment by vimruler** [comment]
> Предложи свой вариант цветового решения.

Хорошо. Могу свои цвета прислать как реализую. Но сперва хотел бы понять причину, по которой ты вообще решил сменить цветовую гамму? Ведь в прошлой 0.86 цвета были вполне приемлемые и современные...

**Comment by maxsite** [comment]
Новые лучше. Например контраст выше.

**Comment by vimruler** [comment]
> Новые лучше. Например контраст выше.
Ты сейчас о цветах оформления сайдбара и табов? Тогда согласен, они вполне устраивают. Значит остаётся только с "серыми" элементами думать.

**Comment by maxsite** [comment]
По хорошему нужно нарисовать дизайн в графике, а уже после его верстать. Поменять один цвет на другой, принципиально ничего не изменит. Нужно еще отступы, расположение, размеры и т.п.

**Comment by vimruler** [comment]
@maxsite, ещё заметил одну странность в оформлении админки.

Раньше для оформления сообщения об ошибке был прописан класс div.error с красным фоном. Теперь найти его не удалось. Сейчас (0.91) в файле my-template.less есть только div.update для "хороших" сообщений. Как быть? Где взять стандартное сообщение красного цвета?

**Comment by maxsite** [comment]
Ок. Добавлю класс .error.

**Comment by cuprum** [comment]
Максим, подожди закрывать. Пусть повисит открытым :smirk:
У меня на последней dev-ревизии в админке сайдбар что-то совсем растянулся:

![admin](https://cloud.githubusercontent.com/assets/532546/9527389/8a666d9e-4cf7-11e5-936f-5367c6f1d0b6.png)
Вот еще:
- хотелось бы, чтоб сайдбар всегда был "в пол"
- подзаголовки в настройках плагина (это поля с `'type' => 'info'` в миниопциях) лучше как-то выделять, фоном или подчеркиванием, для лучшего восприятия.

**Comment by maxsite** [comment]
Закрыл, чтобы замечания были по одному. В куче отказываюсь принимать.

**Comment by vimruler** [comment]
> Закрыл, чтобы замечания были по одному. В куче отказываюсь принимать.

Понятно! А я всё гадал, почему обсуждение не заладилось :) Хорошо, тогда буду "раскидывать" по отдельным тикетам свои пожелания.

**Comment by cuprum** [comment]
@maxsite как вариант - ты можешь заглавным постом тикета указывать [подзадачи](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments) и отмечать выполненные.
