### ISSUE TITLE
Минимизация HTML, CSS и JS

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#86]
:thumbsup:
**"Сборщик/Обработчик" HTML, CSS и JS, который внедрял бы все файлы .css и .js прямо на страницу и "минимизировал" (удаление пробелов и тд).**

Например, имеем страницу:
```html
<html>
   <head>
      <link rel="stylesheet" href="/style.css">
      <script src="/script.js"></script>
   </head>
   <body>
      <p>Текст</p>
   </body>
</html>
```
Файл style.css содержит:
```css
body {
  margin: 0;
}
```
Файл script.js содержит:
```javascript
document.write("JavaScript");
```
Далее, наш обработчик собирает все файлы на страницу:
```html
<html>
   <head>
      <style>
         body {
           margin: 0;
         }
      </style>
      <script>
         document.write("JavaScript");
      </script>
   </head>
   <body>
      <p>Текст</p>
   </body>
</html>
```

После этого происходит "минимизация" кода (удаление пробелов всех необязательных символов).

**Comment by maxsite** [comment]
Ужас какой-то...

**Comment by vimruler** [comment]
Катя, а чем вам плагин [RG-Minify](http://maxhub.ru/page/plagin-rg-minify-szhatie-stilej-skriptov-i-html) не угодил?

**Comment by ekkky** [comment]
Спасибо, Илья, изучу его! Вопрос в его актуальности. Интересно, занимается ли автор еще MS?
