### ISSUE TITLE
Скрытие формы при отправке сообщения

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#88]
При отправке сообщения выводится сообщение ("Сообщение отправлено"), форма скрывается. Давайте не будем ее скрывать (опционально)?
Можно ли в текущей версии запретить скрытие формы после отправки сообщения?

**Comment by vimruler** [comment]
Катя, я не понял о каких сообщениях и соответствующей форме идёт речь. Можете прояснить?

**Comment by ekkky** [comment]
В MS, как я понимаю, все формы строятся с помощью плагина FORMS. То есть в любом месте, где используются формы, при отправке сообщения сама форма исчезает, и выводится сообщение: "Ваше сообщение отправлено".
Можно ли запретить скрытие формы, чтобы она оставалась на месте?

**Comment by vimruler** [comment]
Форма на основе FORMS в дефолтном шаблоне только в одном месте - страница контактов. Формы комментирования строятся другим способом. Поэтому ваша проблема сводится к пожеланию доработать плагин forms. Собственно, там есть код, который заставляет отображаться форму при ошибке и вам, по сути, нужно сделать нечто подобное для ситуации, когда "всё нормально".

**Comment by ekkky** [comment]
В версии 0.90 при ошибке в адресе выводится: "[error]". Сам текст ошибки не выводится. Проверяла на свежей системе.
