### ISSUE TITLE
Учебные материалы по MaxSite CMS. Нужно?

### ISSUE THREAD

**Issue by maxsite** [maxsite/cms#89]
Хотя новая линейка MaxSite CMS вышла уже давно, я не выкладывал на сайте никаких учебных материалов по этой версии. Не хочется «стрелять» в пустоту, поэтому предлагаю здесь обсудить какие именно вопросы требуют разъяснений.

**Comment by vimruler** [comment]
Однозначно нужно. В шаблоне новая структура файлов/папок, много новых возможностей, много изменений в стандартных возможностях (тот же forms имеет изменения), изменилась работа с компонентами (меньше стандартных). Снова же изменения в LESS и стандартных css-классах.

**Comment by Sambala** [comment]
Конечно нужно! Я слаб в сайтостроении, но в пред идущих версиях разбирался, да и материал был где прочитать, как настроить шаблон под себя. Тут очень тяжело мне понять, чем он лучше какие плюсы, а они однозначно есть(ведь не зря произведена такая работа). По этому тоже хотел бы в первую очередь узнать где и что можно менять в шаблоне, как изменить цвет, расстояние межу шапкаой сайта и содержимым и т.д. В общем хочется использовать шаблон по максимум его возможностей. Кстати устанавливал CMS через авто установку, все нормально.

**Comment by maxsite** [comment]
Насколько я понял, это не нужно. Тогда я перехожу на платные консультации и обучалки. Если есть вопросы, составляйте их список, я буду отвечать только индивидульно.

**Comment by vimruler** [comment]
Максим, погоди закрывать тему. Вопросы собираются/обсуждаются уже [здесь](http://maxhub.ru/page/kakie-uchebnye-materialy-po-maxsite-cms-nuzhny).

**Comment by maxsite** [comment]
Ок. Жду вопросы только до 1 сентября.

**Comment by vimruler** [comment]
> Если есть вопросы, составляйте их список, я буду отвечать только индивидульно.

Насколько детализирована должна быть формулировка вопроса, чтобы у тебя возникло желание дать ответ на него?

Выше я обозначил свои вопросы, но судя по всему, такая формулировка не подходит (раз тема закрывалась). Парни на указанной странице тоже очень обще ставят вопросы. Чтобы к 1 сентября было что сюда переносить мне нужно понять требуемый уровень детализации вопросов.

**Comment by maxsite** [comment]
Я не вижу заинтересованности. Мне как бы тоже есть чем заняться, и тратить кучу времени на нулевую реакцию, мне не очень-то хочется. Я не знаю с чем именно сталкиваются разработчики сайтов на MaxSite CMS и не знаю какие при этом у них возникают проблемы и вопросы. Вопросы должны быть конкретные, которые подразумевают технический ответ. Всякая абстракция меня, естественно, теперь мало интересует. Если нет вопросов, значит будут консультировать индивидуально только тех, кому нужна помощь. Мне просто жаль своего времени и труда выкинутого в пустоту.

**Comment by vimruler** [comment]
> Мне просто жаль своего времени и труда выкинутого в пустоту.
Максим, я тебя понимаю. Поэтому если нормальных вопросов не поступит, то закроем тему. Мне тоже есть чем заниматься.

**Comment by denis-skripnik** [comment]
Пока не могу сообразить, что именно мне интересно, но слышал, что кто-то хотел узнать, как партировать html шаблон на Maxsite CMS. Думаю также актуальна информация по переносу шаблона из Wordpress.

**Comment by denis-skripnik** [comment]
Вот вопросы с Максхаба:
1. "Не помешает знать какие важные функции применяются в шаблоне и зачем. А то порой приходится из дефолтного в свой переносить многое при обновлении".
2. "Многое станет понятно, если показать, на примере, интеграцию дизайна, шаблона и шаблонных функций на MaxSite CMS. 
Шаблон можно усложнить - добавив другой тип страниц, примеры вывода блоков записей на главной, рубриках, подключить всплывающую (встроенную в CMS) форму для обратной связи. 
Шаблон для работы могу предложить: http://maxhub.ru/uploads/_pages/103/nightclub.zip"
3. "я за то, чтоб теория была поддержкой практики.
а практика для меня сейчас - это перенос шаблона и плагинов в новый движок.
если уже есть какие кейсы на эту тему, интересно будет почитать.
например список неактуальных плагинов, замен для них.
также интересен подробный разбор переноса шаблона на новый движок, чтоб с кодом и скринами.
еще интересны демо новых возможностей движка. что я смогу получить, поставив новую версию"?
4. "Предлагаю организовать раздел "Вопросы новичка". Думаю, Максим ориентирует MaxSite CMS не только на вебмастреов, но и обычных юзеров, которые хотели бы ее использовать в первую очередь в качестве хобби. Привлечь подобного юзера не так просто, т.к. на всех без исключениях форумах на простой вопрос слышишь ответ: "...а погуглить слабо", после этого интерес пропадает. Максим много времени уделял публикации обучающих материалов и Вопросы новичка могут помочь ему в сотавлении руководств по MaxSite CMS".
Если будут у вас ответы, я перешлю.

**Comment by denis-skripnik** [comment]
И теперь вопрос от меня: хотелось бы почитать, как сделать работоспособным любой php скрипт, не привязанный к какой-либо CMS. Тоесть как его сделать работоспособным.
Пример: скачал php скрипт обратной связи, внедрил в плагин, но он не срабатывает корректно.

**Comment by maxsite** [comment]
Я здесь не вижу ни одного конкретного вопроса.

**Comment by jimmyjonezz** [comment]
Однозначно нужно. Интересует применение хуков, новых особенностей шаблона и структуры CMS. С введением новых возможностей, хотелось бы видеть их практическое применение.

**Comment by amigoscs** [comment]
Бало бы неплохо дать раскладку по хукам, которая была в http://wiki.max-3000.com/pmwiki.php?n=Main.Hooks
