### ISSUE TITLE
Нужно обновить jQuery с v1.8.2 до 1.11.3

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#90]
С недавних пор Firefox в консоли выдаёт сообщение:

> Метод getPreventDefault() является устаревшим. Для его замены используйте метод defaultPrevented.   - jquery.min.js:2:0

Очевидно из-за этого в Отладчике Firefox-а исходник библиотеки помещается в «черный ящик».

Выбор загрузки из сторонних источников не помогает, т.к. в __mso_load_jquery__ жестко прописана версия - 1.8.2 

С одной стороны, ссылаться на последнюю версию библиотеки - рисковать стабильностью сайта. Но с другой стороны, если я уверен, что всё будет нормально, то нужны средства, задать загружаемую версию. Чтобы не приходилось обновлять файл __jquery.min.js__ вручную каждый раз или ждать когда движок сам его обновит (хотя, конечно, с внедрением автообновления станет полегче с этим). Максим, как думаешь?

**Comment by maxsite** [comment]
Кидаешь в свой шаблон assets/js/jquery.min.js любой версии.

**Comment by vimruler** [comment]
Понятно. Тогда можно закрывать тикет.
