### ISSUE TITLE
Вариант дефаулт шаблона - только сброс стилей [предложение]

### ISSUE THREAD

**Issue by ekkky** [maxsite/cms#93]
Новый вариант дефолтного шаблона - это нулевой шаблон, только сброс стилей.

**Comment by vimruler** [comment]
Можно по подробнее, что значит нулевой шаблон? Что конкретно нужно обнулить?

**Comment by skull3d** [comment]
Возможно речь о неком каркасе без стилей оформления.

**Comment by ekkky** [comment]
> Возможно речь о неком каркасе без стилей оформления.

Ага, типа того. Вообще, может еще кто-то выскажет свои идеи насчет этого.

**Comment by skull3d** [comment]
Поддерживаю идею Base/Starter Theme для MS (как для WP - http://codex.wordpress.org/Theme_Frameworks#Base.2FStarter_Theme)
Но кто это будет делать?
