### ISSUE TITLE
По поводу версии для разработчиков

### ISSUE THREAD

**Issue by denis-skripnik** [maxsite/cms#94]
Здравствуйте. Тестировал редактор - всё хорошо работает, только не хватает описаний (какой файл за что отвечает). Можно сделать как на уровне движка, так и на уровне самого файла - добавить внутри перед всем остальным инфо-секцию, из которой будет браться название.
Ещё бы хотелось, чтобы выводилось всё не одним списком, а следующим образом: сначала выбираем папку, а потом - файл в ней.
И ещё желательно бы, чтобы можно было установить дополнительный пароль к этому разделу, например, на странице самого раздела, чтобы злоумышленник не смог изменить его, либо по секретной ссылке.
Какие-то ещё были изменения?
P. S. Предлагаю сделать в версии для разработчиков форму обратной связи в админке по клику на "Сообщить о проблеме" - так вам не придётся залазить сюда в поисках новых проблем, а чтобы было проще, в качестве имени и e-mail использовались админские данные пользователя версии для разработчиков - тогда достаточно будет ввести текст.

**Comment by ekkky** [comment]
Интересные идеи! Все идеи нравятся, вот только последняя, "Сообщить о проблеме", вроде не очень нужна. Можно же и тут высказаться, вроде не сложно сюда зайти.

**Comment by maxsite** [comment]
> не хватает описаний (какой файл за что отвечает). Можно сделать как на уровне движка, так и на уровне самого файла - добавить внутри перед всем остальным инфо-секцию, из которой будет браться название.

Если вы не знаете что за файл, то и редактировать его незачем. Выводить лишние сущности ни к чему.

> Ещё бы хотелось, чтобы выводилось всё не одним списком, а следующим образом: сначала выбираем папку, а потом - файл в ней.

Первоначально и был такой вариант. Получается файловый менеджер, сложный и запутанный. Так что такого не будет. 

> И ещё желательно бы, чтобы можно было установить дополнительный пароль к этому разделу, например, на странице самого раздела, чтобы злоумышленник не смог изменить его, либо по секретной ссылке.

Будет обычное разрешение. Забыл просто сразу его прописать.

> редлагаю сделать в версии для разработчиков форму обратной связи в админке по клику на "Сообщить о проблеме" - так вам не придётся залазить сюда в поисках новых проблем, а чтобы было проще, в качестве имени и e-mail использовались админские данные пользователя версии для разработчиков - тогда достаточно будет ввести текст.

Для этого есть гитхаб.
