### ISSUE TITLE
Мелкая правка mso_admin_plugin_options

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#95]
Предлагаю при определении функции __mso_admin_plugin_options__ (\application\maxsite\admin\plugins\admin_plugin_options\index.php) изменить значение параметра функции __$show_goto_plugins__ с __true__ на __false__. Т.е.:

Сейчас:
```php
function mso_admin_plugin_options($key, $type, 
$ar, $title = '', $info = '', $text_other = '', $show_goto_plugins = true)
```
Предлагаю:
```php
function mso_admin_plugin_options($key, $type, 
$ar, $title = '', $info = '', $text_other = '', $show_goto_plugins = false)
```

Это нужно для того, чтобы скрыть по умолчанию ссылку на страницу плагинов. Эта ссылка появляется на месте хлебных крошек. Мы вроде решили избавится от них в админке, но сейчас по умолчанию ссылка выводится для опций некоторых плагинов (у которых страница опций формируется функцией mso_admin_plugin_options).

@maxsite что скажешь?

ЗЫ: Могу потом проверить код движка на наличие плагинов, где принудительно выводится эта ссылка.

**Comment by skull3d** [comment]
Согласен, ссылка лишняя. Но теперь знаю как ее убрать, спасибо)

**Comment by maxsite** [comment]
Ок. Согласен.
