### ISSUE TITLE
Переход на HTTPS

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#96]
Просто хочу обозначить проблему и инициировать обсуждение. Думаю, что важность постепенного перехода сайтов на протокол HTTPS коллегами под сомнение не ставится (не для всех сайтов актуально, но задача вполне реальная). Тем более, если протокол станет фактором ранжирования в поисковиках.

При переходе на HTTPS мало настроить редиректы. Нужно ещё выловить на страницах ссылки на ресурсы, подгружаемые по протоколу HTTP (иначе желанный "замочек" в адресной строке не появится).

Так вот, если ссылки находятся в шаблоне, то их можно подправить. Но есть ещё часть ссылок (на ресурсы), которые формируются самим движком и которые тоже нужны с правильным протоколом. 

Также имело бы смысл простые ссылки на страницы внутри сайта как-то сделать соответствующими протоколу HTTPS.

Пока не готов привести конкретные примеры. Также понимаю, что править придётся много и не везде можно обойтись простой заменой строк.

Единственно, что могу сказать точно, что очень помогает использование "относительного протокола". Т.е. когда вместо конкретного "http://" или "https://" используется просто "//". В этом случае браузер сам выбирает протокол.

**Comment by maxsite** [comment]
Сейчас система формрует тот протокол, по которому работает сайт. То есть система формирует правильные адреса. Если где-то выскакивает другое, то это можно поправить. Всё остальное уже давно решено в LPF.

**Comment by vimruler** [comment]
То, что движок подхватывает протокол и подставляет его по максимуму - я видел и тут нареканий нет. Тему я создавал как раз для возможности скидывать места, где ещё остались негибкие пережитки и которые нужно подправить.

Так, я вспомнил, где точно видел такое месте, которому требуется внимание: функция mso_load_jquery. Когда идёт подключение из папки шаблона или движка - всё нормально. Проблема при подключении из разных CDN-ов. Там жестко прописаны http.

**Comment by maxsite** [comment]
Да, это можно заменить на //
