### ISSUE TITLE
Ошибки с jquery.tablesorter.js в админке

### ISSUE THREAD

**Issue by vimruler** [maxsite/cms#98]
Обратил внимание, что на странице __/admin/comusers__ (0.92) при отсутствии комюзеров (когда нулевой сайт) в консоли браузера отображается ошибка:

> TypeError: table.tBodies[0] is undefined - \application\maxsite\admin\template\default\assets\js\jquery.tablesorter.js 

Полез смотреть что к чему и увидел другую проблему - в __\application\maxsite\admin\plugins\admin_comusers\comusers.php__ происходит дублированное подключение jquery.tablesorter.js из двух разных мест:

> /application/maxsite/admin/template/default/assets/js/jquery.tablesorter.js

и

> /application/maxsite/common/jquery/jquery.tablesorter.js

Если с дублированием можно как-то порешать (вот только наверно стоит проверить и остальные плагины - нет ли и там дублированного подключения?), то с первой ошибкой нужно думать. Т.к. она всегда будет появляться пока таблица пустая.

@maxsite, что скажешь?

**Comment by maxsite** [comment]
Убрать лишнее. Тем более, что common/jquery/jquery.tablesorter.js нет.
